### ISSUE TITLE
Reading pcap or pcapng files HAVE to have and extension???

### ISSUE THREAD

**Issue by Jeff4Success** [seladb/PcapPlusPlus#101]
I was trying to read a capture file that I had written moments earlier from a live capture. I was reading a captured test file earlier in my coding and it worked every time. So I decided to move on in my project and read some files using live captured packets. I named my file '`jeff`' just because. Well I immediately got an out of range crash when I ran code to read it to `stdout`. So I tried my "test" file and it worked, so a goose chase ensued.
If the file I was trying to read did not have an extension, i.e."`jeff.cap`" it would always error with an out of range crash. The `PcapFileDevice.cpp` code, around line 81, is looking for an extension in a filename by reading a sub-string starting after the first '.'
I didn't catch it with my test capture file, because I was running it with a command line input for the filename that INCLUDED a dot in the path, i.e. `mycode --input "../myTestFile"`

Not sure if this is a bug but thought I would make someone aware of it. Thanks for some great code, I love learning to use it!!!

**Comment by seladb** [comment]
Thanks for finding this bug! 
I pushed a fix to master, please pull the latest code
