### ISSUE TITLE
IFileReaderDevice filtering on UDP port with high port number not working

### ISSUE THREAD

**Issue by ECquadrat** [seladb/PcapPlusPlus#103]
Filtering on packets in files seems not to work correctly. The same filter settings works on live-devices. I used a filter setting with many filters combined with AND. For reproducing this issue I stripped it down to only one UDP port filter:

**Example:**
```
// Note: This example uses spdlog library for logging

unsigned int mPacketCnt;

// This method interface is also used for live-devices, so the pcapDev parameter is
// unused here in case of fileReader usage.
void EthPcapCapturer::parseEthPackage(pcpp::PcapLiveDevice* pcapDev, pcpp::RawPacket* rawPacket)
{
    // ==== Print some debug infos ====
    pcpp::Packet pk = pcpp::Packet(rawPacket);
    std::string sSIp = "-";
    std::string sDIp = "-";
    uint16_t sPort = 0;
    uint16_t dPort = 0;

    if (pk.isPacketOfType(pcpp::ProtocolType::IPv4)) {
        sSIp = pk.getLayerOfType<pcpp::IPv4Layer>()->getSrcIpAddress().toString();
        sDIp = pk.getLayerOfType<pcpp::IPv4Layer>()->getDstIpAddress().toString();
        if (pk.isPacketOfType(pcpp::ProtocolType::UDP)) {
            sPort = ntohs(pk.getLayerOfType<pcpp::UdpLayer>()->getUdpHeader()->portSrc);
            dPort = ntohs(pk.getLayerOfType<pcpp::UdpLayer>()->getUdpHeader()->portDst);
            SomeIpDataWrapper sdw = SomeIpDataWrapper(pk.getLayerOfType<pcpp::UdpLayer>()->getData());
        }
    }
    logger->info("Replay: enqueued packet {}: Src-IP:{}, Dst-IP:{}, Src-Port:{}, Dst-Port:{}",
        ++mPacketCnt, sSIp, sDIp, sPort, dPort);
}

void configureFilter () {
#ifdef LOW_UDP_PORT
    pcpp::PortFilter portSetting(137, pcpp::Direction::SRC);
#else
    pcpp::PortFilter portSetting(40001, pcpp::Direction::SRC);
#endif
    if (smFileReader->setFilter(portSetting)) {
        std::string tmp;
        portSetting.parseToString(tmp);
        logger->info("EthPcapCapturer_ReplayModule: Setting PCap file filter: {}", tmp);
    }
    else {
        logger->error("EthPcapCapturer_ReplayModule: Setting PCap file filter failed!");
    }
}

void run() {
    mPacketCnt = 0;
    
    smFileReader = pcpp::IFileReaderDevice::getReader("testdata_6Udp_packets.pcapng");
    if (smFileReader == nullptr) {
        logger->error("Error: File not found!");
        return;
    }
    if (!smFileReader->open()) {
        logger->error("Error: File '{}' couldn't be opened!", filename);
        return;
    }
    configureFilter();
    while (smFileReader->getNextPacket(rawPacket)) {
        parseEthPackage(nullptr, &rawPacket);
    }
    smFileReader->close();
}
```
With ```#define LOW_UDP_PORT``` there is one packet printed which is contained in the test data file. => OK.
With ```#undef LOW_UDP_PORT``` there is no packet printed but there are two contained in the test data file. => Wrong.

Am I doing something wrong? The htons() macro doesn't help either for the port number, so I assume it is not needed here (it is neither used in the PCap++ filtering tutorial and the test with port 137 should fail also in this case).

The same issue occurs if I try to filter on the protocol with ```pcpp::ProtoFilter protoSetting(pcpp::UDP);``` instead of the UDP port filter. In that case I also only get the UDP packet with port 137 printed and the other events with port 40001 are missing.

Thank you in advance!
Marc

**Test-System:**
Ubuntu 16.04 LTS 64bit inside VMware on Windows host
PcapPlusPlus V17.11

**File used in the example:**
[testdata_6Udp_packets.pcapng.gz](https://github.com/seladb/PcapPlusPlus/files/1931252/testdata_6Udp_packets.pcapng.gz)

**Comment by seladb** [comment]
Thanks for reporting this issue!
I had a look in the pcapng file you attached and the issue is this: PcapPlusPlus filtering mechanism is based on libpcap/WinPcap filtering (you can read about it [here](https://linux.die.net/man/7/pcap-filter)). PcapPlusPlus filtering is just a wrapper on-top of this mechanism. 

There is a limitation/bug in libpcap/WinPcap filtering which doesn't work well with VLAN layers, so whenever packets contain VLANs you can't expect the filter to work. That's why your filter works with port 137 (where the packet doesn't include VLAN) and doesn't work with port 40001 (where the 2 packets include VLAN).

Since it's a limitation in libpcap/WinPcap I'm not sure how to fix it...

Please let me know if you have more questions

**Comment by ECquadrat** [comment]
Thanks a lot for the fast reply!
Could you please point me to the VLAN issue number in libpcap you mentioned? It looks like the libpcap team is currently working on a new release - maybe this issue is fixed then.
Furthermore I'm wondering why I can see those UDP packets with VPN bits in Wireshark, because Wireshark seems to use the same library for fetching events from the eth interface.
When opening recorded files in Wireshark I can also filter on those UDP packets with enabled UDP port filters in the opening dialog - but here I'm not sure whether this filter string is really passed to the libpcap library. It may be some filtering which is done in the high-level code of Wireshark.

**Comment by seladb** [comment]
Regarding the VLAN issue number - I didn't manage to find it. Actually it may be already fixed in later versions of libpcap. Which version are you using? Maybe you can update to the latest version of libpcap and try again

Regarding Wireshark - it's indeed using libpcap for capturing packets, but it has a different filtering mechanism (it doesn't use libpcap's filtering engine). That's why you can see these packets as well as run this filter in Wireshark. There is no relation between these 2 filtering mechanisms.

I hope I answered your question, please let me know if you need more info

**Comment by seladb** [comment]
Do you have any updates or further questions on this issue?

**Comment by ECquadrat** [comment]
According to tcpdump.org, I'm using the latest version V1.8.1 of libpcap. As I read in the issue list of libpcap a new release is in work, so maybe the VLAN issue is fixed then. I'm working in the automotive industries where nearly all Ethernet packets have a VLAN layer, so currently I'm implementing a workaround by filtering the packets for myself without using libpcap filtering engine.

Thank you very much for your help!

**Comment by ECquadrat** [comment]
According to tcpdump.org, I'm using the latest version V1.8.1 of libpcap. As I read in the issue list of libpcap a new release is in work, so maybe the VLAN issue is fixed then. I'm working in the automotive industries where nearly all Ethernet packets have a VLAN layer, so currently I'm implementing a workaround by filtering the packets for myself without using libpcap filtering engine.

Thank you very much for your help! As you already noticed that there is not much you can do in PCap++ on this issue, I'll close this ticket.
