### ISSUE TITLE
Incomplete Parsing of TLS Extensions

### ISSUE THREAD

**Issue by axmahr** [seladb/PcapPlusPlus#1039]
Hello!
While parsing the extensions of Server Hello messages, I came across the problem that sometimes the last extension listed in a Server Hello message is not detected.

To reproduce the issue, see the attached pcap file in [bug.zip](https://github.com/seladb/PcapPlusPlus/files/10435123/bug.zip).

I used the following code for reading all parsed extensions:
```c++
#include <PcapFileDevice.h>
#include <Packet.h>
#include <SSLLayer.h>
#include <SSLHandshake.h>
#include <iostream>

int main() {

    pcpp::PcapFileReaderDevice pcapReader("bug.pcap");
    pcapReader.open();

    pcpp::RawPacket rawPacket;
    while(pcapReader.getNextPacket(rawPacket)){
        pcpp::Packet parsedPacket(&rawPacket);
        pcpp::SSLLayer *sslLayer = dynamic_cast<pcpp::SSLLayer*>(parsedPacket.getLayerOfType(pcpp::SSL, 0));
        pcpp::SSLHandshakeMessage *handshakeMessage = dynamic_cast<pcpp::SSLHandshakeLayer *>(sslLayer)->getHandshakeMessageAt(0);
        pcpp::SSLServerHelloMessage *serverHelloMessage = dynamic_cast<pcpp::SSLServerHelloMessage*>(handshakeMessage);

        std::cout << "We have " << serverHelloMessage->getExtensionCount() << " extensions:" << std::endl;
        for(size_t i = 0; i < serverHelloMessage->getExtensionCount(); i++) {
            std::cout << i+1 << ". type " << serverHelloMessage->getExtension(i)->getType() << std::endl;
        }
    }
}
```
Running this code with the supplied pcap file yields the following output:
```
We have 3 extensions:
1. type 65281
2. type 35
3. type 22
```
But as you can see in the pcap file, the Server Hello message consists of 4 extensions. The extended master secret extension is not detected.
Unfortunately I was not able to locate the origin of this problem, maybe something gets confused during the creation of the `SSLHandshakeMessage`

**Comment by seladb** [comment]
Hi @axmahr ! Thanks for reporting this issue, and I really appreciate the code and pcap file that reproduces it, it made my life very easy in finding/fixing the bug.

I opened a draft PR with the fix: https://github.com/seladb/PcapPlusPlus/pull/1042

I still need to add your pcap file to the tests which I'll do very soon.

**Comment by seladb** [comment]
Fixed in this PR: https://github.com/seladb/PcapPlusPlus/pull/1042

Thank you @axmahr for reporting this issue, much appreciated! 🙏
