### ISSUE TITLE
about capture 

### ISSUE THREAD

**Issue by TCZWJ** [seladb/PcapPlusPlus#106]
Can PcapPlusPlus capture packets writing pcap files from NIC by dpdk driver??

**Comment by seladb** [comment]
I'm not sure I understand the question. Could you please elaborate on what you're trying to do?

**Comment by TCZWJ** [comment]
i want to capture packets from NIC by DPDK, and writing the packets to pcap files.  What i want to do just like tcpdump on linux to capture  and write packets.  i am not very familiar with pcapplusplus and hope you can understand my description.

**Comment by seladb** [comment]
Sure, that should be quite easy. Please take a look at [DpdkExample-FilterTraffic](https://github.com/seladb/PcapPlusPlus/tree/master/Examples/DpdkExample-FilterTraffic), you should be able to figure out how to do this from the code. Please let me know if you need additional help.

Please notice that writing to pcap files which consume a lot of I/O won't work in very high traffic. You should only save to disk (pcap files) a small portion of the traffic, unless you have some extremely fast storage which can take the load of saving all of the network traffic

**Comment by seladb** [comment]
I didn't see any response from you for a while so I'm closing this issue. Please reopen it if you have additional questions
