### ISSUE TITLE
etherType value is not right

### ISSUE THREAD

**Issue by jason-yau** [seladb/PcapPlusPlus#1064]
https://github.com/seladb/PcapPlusPlus/blob/33058b6d270faf668dbbd51cbfeaee1d32a9813b/Packet%2B%2B/header/EthLayer.h#L21-L29
The pointer of `ether_header` can't point directly to the data. The memory order is different to  `uint16_t`.
Wrong code:
https://github.com/seladb/PcapPlusPlus/blob/33058b6d270faf668dbbd51cbfeaee1d32a9813b/Packet%2B%2B/header/EthLayer.h#L108

**Comment by seladb** [comment]
Yes that's correct, the order is indeed different. To get the host order value you should use `ntohs()` or a similar method, for example:

https://github.com/seladb/PcapPlusPlus/blob/33058b6d270faf668dbbd51cbfeaee1d32a9813b/Tests/Packet%2B%2BTest/Tests/EthAndArpTests.cpp#L30

**Comment by seladb** [comment]
@jason-yau does it answer your question? Should we close this issue?
