### ISSUE TITLE
Pcapsplitter writing to fifo can consume all memory

### ISSUE THREAD

**Issue by CyberTaoFlow** [seladb/PcapPlusPlus#107]
Hello I am using pcapsplitter to read packets from a fifo and write to multiple fifo's which are each read by a bro instance.  This works well unless one of the consumers crashes or dies.  

 If a consumer dies (fifo is closed) then restarts and reopens the fifo then the  pcapsplitter will not resume sending packets to that output and will instead buffer them in memory until all memory is consumed.

**Comment by seladb** [comment]
I'm not sure I fully understand your setup and it'll probably not be easy for me to create it. Do you think you can reproduce this issue without those fifos and bro?

**Comment by CyberTaoFlow** [comment]
I will try to reproduce with a file as output by simply deleting then recreating the file during operation.

**Comment by seladb** [comment]
Cool, please let me know if you succeed and what are the steps to reproduce it

**Comment by seladb** [comment]
Any updates on this?

**Comment by seladb** [comment]
I'm not sure PcapSplitter should support this special configuration. It's mainly designed to split pcap files. I wouldn't want to add code for specific use-case as it may break something else.

Please let me know what you think
