### ISSUE TITLE
SIP 608

### ISSUE THREAD

**Issue by silviucpp** [seladb/PcapPlusPlus#1070]
The 608 sip code is not parsed. 

https://en.wikipedia.org/wiki/List_of_SIP_response_codes

This code was added recently because of [STIR/SHAKEN](https://en.wikipedia.org/wiki/STIR/SHAKEN)

The library is not treating it and you receive SipStatusCodeUnknown

Silviu

**Comment by seladb** [comment]
Thank you for reporting this @silviucpp !

I went over the list of codes and there are 2 more codes that are missing:
- `425 Bad Alert Message`
- `555 Push Notification Service Not Supported`
- `608 Rejected`

It should be a very easy fix. Would you consider opening a PR?
