### ISSUE TITLE
DpdkDeviceList::initDpdk  EAL Init "--master-lcore " "0"

### ISSUE THREAD

**Issue by shidaoxuan** [seladb/PcapPlusPlus#108]
In function "DpdkDeviceList::initDpdk()" EAL init, some parameters are fixed to '0'.
    dpdkParamsStream << "--master-lcore ";
    dpdkParamsStream << "0";
i think configuring "--master-lcore" with Least significant bit of coremask is better.

**Comment by seladb** [comment]
I'm not sure using the LSB will be obvious enough for users. Maybe it's better to add a new parameter to configure the master core. What do you think?
I'd be great if you do this change and issue a PR

**Comment by seladb** [comment]
Fixed! Please pull the latest code and let me know if you see any issues. I'll close this bug for now

**Comment by shidaoxuan** [comment]
Thank you for fixing it.
