### ISSUE TITLE
Can't get network device live from getPcapLiveDevicesList()

### ISSUE THREAD

**Issue by kokose1234** [seladb/PcapPlusPlus#1084]
Hello @seladb 
I'm using Visual Studio 2022 on Windows 11 and Npcap 1.72.
I can't get any device from PcapLiveDeviceList class.
I installed PcapPlusPlus using vcpkg with this command. `vcpkg install pcapplusplus:x64-windows`

this is my code
```cpp
#include <PcapLiveDeviceList.h>

  for (auto device : pcpp::PcapLiveDeviceList::getInstance().getPcapLiveDevicesList()) {
    std::cout << device->getName() << std::endl;
    std::cout << device->getDesc() << std::endl;
  }
```

**Comment by seladb** [comment]
@kokose1234 it's hard to figure out the issue without further information. Do you see any network interfaces using Wireshark on this machine? Can you share the list you see?

also - can you please run `ipconfig` and paste the result?

Are you able to capture packets on this machine using Wireshark?

**Comment by kokose1234** [comment]
@seladb sure they are showing same devices
![1](https://user-images.githubusercontent.com/11906209/222415766-35603e42-c55a-4527-a17a-6a52aba6b27b.png)
![2](https://user-images.githubusercontent.com/11906209/222415777-9936f3c5-601b-4c27-9f6e-f09cd41ac981.png)
but if i delete wpcap.dll in my compiled files and uninstall npcap and install winpcap it works with some errors.
```
[ERROR: D:\vcpkg\buildtrees\pcapplusplus\src\v22.11-e3390d66ff.clean\Pcap++\src\PcapLiveDevice.cpp: pcpp::PcapLiveDevice::setDeviceMtu:728] Error in retrieving MTU: PacketRequest failed
0.0.0.0
TAP-NordVPN Windows Adapter V9
192.168.50.49
Intel(R) I211 Gigabit Network Connection
0.0.0.0
MT7612US_RL
0.0.0.0
TAP-Windows Adapter V9```
i downloaded npcap sdk from this url https://npcap.com/dist/npcap-sdk-1.13.zip

**Comment by seladb** [comment]
Did you install Npcap on your machine? https://npcap.com/#download
Maybe there is a mismatch between the `wpcap.dll` version installed on your system (under `C:\Windows\System32` or `C:\Windows\SysWOW64`) and `npcap-sdk`?

You can try to delete all versions of `wpcap.dll` installed on your machine and re-install Npcap, I think this solved an issue I once had on my machine...

PcapPlusPlus is just a wrapper on top of WinPcap/Npcap, it doesn't touch the internals of these packets capture engines so it's not easy to debug

**Comment by seladb** [comment]
@kokose1234 did you manage to solve the issue? Should we keep the issue open?

**Comment by kokose1234** [comment]
@seladb I solved the issue with replacing npcap to winpcap. you can close the issue.

**Comment by seladb** [comment]
This might be a related issue: https://github.com/seladb/PcapPlusPlus/issues/1100

Also happened in Windows 11 and VS 2022.
I'll try to get a Windows 11 / VS 2022 VM and see if I can reproduce the issues

**Comment by seladb** [comment]
@kokose1234 please see this comment: https://github.com/seladb/PcapPlusPlus/issues/1100#issuecomment-1464885416

Maybe try to install Npcap in WinPcap API-compatible mode?

**Comment by kokose1234** [comment]
@seladb Yes i installed with winpacp compatible option

**Comment by seladb** [comment]
@kokose1234 I think this is related to the fact that you installed PcapPlusPlus via `vcpkg`. Unfortunately `vcpkg` doesn't have Npcap so the only option for PcapPlusPlus is to use WinPcap as a dependency. WinPcap is older than Npcap hence it isn't necessarily compatible with Npcap. 

Can you please provide your `CMakeLists` or `Makefile` and your source code that I can run locally and debug?

Also - you can try building PcapPlusPlus from source and see if it works.

**Comment by kokose1234** [comment]
@seladb my project use msbuild for compiling. Is it ok?

**Comment by seladb** [comment]
yes sure, I can test it on a Windows 11 / VS 2022 VM

**Comment by kokose1234** [comment]
@seladb Sorry for the delay. this is my project file
[RapidAuctionAnalyzer.zip](https://github.com/seladb/PcapPlusPlus/files/10982231/RapidAuctionAnalyzer.zip)

**Comment by seladb** [comment]
Thanks @kokose1234 , I'll take a look in the next few days and keep you posted

**Comment by seladb** [comment]
@kokose1234 I'm not a Visual Studio expert so I couldn't figure out how to add PcapPlusPlus to your solution.

So instead I configured PcapPlusPlus on a Windows 11 / Visual Studio 2022 VM and built it from source. Then I modified one of example apps provided with PcapPlusPlus to run your code:

```cpp
#include <PcapLiveDeviceList.h>

  for (auto device : pcpp::PcapLiveDeviceList::getInstance().getPcapLiveDevicesList()) {
    std::cout << device->getName() << std::endl;
    std::cout << device->getDesc() << std::endl;
  }
```

I am able to see the machine interfaces:

```text
PS C:\Users\User\PcapPlusPlus\build\examples_bin\Debug> .\Arping.exe
10.0.2.15
Intel(R) PRO/1000 MT Desktop Adapter
0.0.0.0
Adapter for loopback traffic capture
```

Maybe you can try to do the same: build PcapPlusPlus from source and modify one of the example apps?
If it doesn't work then it's probably some permission issue for Npcap to read the network interfaces...

**Comment by seladb** [comment]
@kokose1234 let me know what we should do with this issue, should we keep it open or close it?

**Comment by kokose1234** [comment]
You may close the issue. Thanks for the support

**Comment by UInSomnia** [comment]
Hi! I'm facing the same problem. Everything is fine on Linux Ubuntu. I don't see any machine network interfaces on Windows. I build through MSYS2, cmake, make. Can you please help me?

**Comment by seladb** [comment]
@UInSomnia I'm sorry for the late response. Were you able to figure it out?

**Comment by UInSomnia** [comment]
Everything became perfectly assembled and executed when assembling according to this recipe:

Install MSYS2

Terminal MSYS2 MinGW64

pacman -Syu
pacman -Su
# pacman -S mingw-w64-clang-x86_64-toolchain
pacman -S mingw-w64-x86_64-gcc
pacman -S mingw-w64-x86_64-cmake
pacman -S make
g++ --version
cmake --version
make --version
pacman -S git
git --version

cd /c/Libs/
git clone https://github.com/seladb/PcapPlusPlus.git

Install npcap-1.81.exe
Take dir npcap-sdk-1.15
cd /c/Libs/PcapPlusPlus/
mkdir build
cd build
cmake -G "Unix Makefiles" -DPCAPPP_BUILD_EXAMPLES=OFF -DPCAPPP_BUILD_TESTS=OFF -DPCAPPP_BUILD_TUTORIALS=OFF -DPCAP_ROOT=/c/Libs/npcap-sdk-1.15 ..
make
make install

Take dir C:\Libs\PcapPlusPlus\Examples\ExampleApp
cd /c/Projects/ExampleApp/
mkdir build
cd build
cmake -G "Unix Makefiles" -DPcapPlusPlus_ROOT=/c/Libs/PcapPlusPlus -DPCAP_ROOT=/c/Libs/npcap-sdk-1.15 -DPacket_ROOT=/c/Libs/npcap-sdk-1.15 ..
make
./example-app.exe
