### ISSUE TITLE
No way to set compile flags

### ISSUE THREAD

**Issue by krisk0** [seladb/PcapPlusPlus#109]
In order to use PcapPlusPlus in a Python extension, I had to add `-fPIC` flag. Found no way to do it properly, had to dirty-hack Makefiles like that
```
for i in `find . -name Makefile` ; do
    sed -i 's:-O2 -g -Wall:-O2 -fPIC -Wall:g' $i
    sed -i 's:-O2 -Wall:-O2 -fPIC -Wall:g' $i
    sed -i 's:-Wall -O2:-O2 -fPIC -Wall:g' $i
done
```
Altering CFLAGS is a must-have feature, for any serious C++ library, and PcapPlusPlus looks serious. I therefore suggest that configure script should respect CXXFLAG or CFLAG env var (or a command-line parameter like --cflags).

**Comment by seladb** [comment]
That would certainly be a nice addition to PcapPlusPlus. I'd go for the --cflags option. Would you mind adding it and create a PR?

**Comment by krisk0** [comment]
I don't understand what PR means here, but if you want me to fix PcapPlusPlus build scripts and create merge request, then no, sorry. 

// I don't understand the idea behind non-standard build system of PcapPlusPlus, suggest that `cmake`, `scons` or some other standard build system is used.

**Comment by seladb** [comment]
The idea behind PcapPlusPlus build system is that it's as basic as possible so it can be easily integrated in any project, regarding of its build system.
For example: if PcapPlusPlus use `cmake` and your project doesn't use `cmake` - how could you integrate PcapPlusPlus in your project?

Regarding adding the cflags option - I'll see how easy it is to add this
