### ISSUE TITLE
MSVC disable warning C4819

### ISSUE THREAD

**Issue by traversebitree** [seladb/PcapPlusPlus#1096]
This is for commit `7e965f4ef698308c929495a5cf983bed628058fa`

When compiling Pcap++ using CMake and MSVC, the warning C4819 appears.

> warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data ...

And you set `COMPILE_WARNING_AS_ERROR`.  The way to solve this is add compile option `/wd4819` in "pcapplusplus/CMakeLists.txt":
```cmake
if(PCAPPP_TARGET_COMPILER_MSVC)
  # Disable VS warnings: Unknown pragma (4068), Zero-sized array in struct/union (4200), Possible loss of data (4244),
  # Possible loss of data (4267)
  add_definitions("/wd4068 /wd4200 /wd4244 /wd4267 /wd4819") # Here add /wd4819
endif()
```
By the way, Information of my system:
OS: Windows 11 22621.1265
Language: Simplified Chinese

**Comment by seladb** [comment]
Thanks for reaching out @traversebitree ! Which Visual Studio version are you running?

We run VS 2019 and 2022 in CI and don't see any issue:

https://github.com/seladb/PcapPlusPlus/blob/master/.github/workflows/build_and_test.yml#L369

**Comment by traversebitree** [comment]
> 

I'm using VS2022 17.5.0.
![image](https://user-images.githubusercontent.com/30373236/224246870-7afe2ac9-6bd2-49f0-8c3b-b8f9b690d40d.png)

**Comment by seladb** [comment]
We run VS 2022 in CI and it passes so I wonder how it fails for you 🤔 

@egecetin - what do you think?

**Comment by egecetin** [comment]
@traversebitree Because of Chinese localization if you edit some of the source files for some reason and add characters (or even add/remove whitespace) using your localization probably VS updated the encoding. Can you try these options below and share the results;

- Remove if any comments added in your local language (using Chinese characters) and try to compile again.
- Add your comments again and apply this quotation below and compile
> To save a file in Unicode format, in Visual Studio, choose File > Save As. In the Save File As dialog box, select the drop-down on the Save button and choose Save with Encoding. If you save to the same file name, you may need to confirm that you want to replace the file. In the Advanced Save Options dialog, choose an encoding that can represent all the characters in the file—for example, Unicode (UTF-8 with signature) - Codepage 65001—and then choose OK.

From  https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4819?view=msvc-170


@seladb If the second option is enough for solution this is not a big deal since VS fixes this but if it is not works disabling this warning might be better idea.

**Comment by traversebitree** [comment]
> 

I guess the localization causes. I didn't modify any source files and didn't add any comments too. I use it as follows in CMake:

```cmake
set(BUILD_SHARED_LIBS FALSE CACHE INTERNAL "Build Dll" FORCE)
FetchContent_Declare(
    npcap
    SYSTEM

    URL https://npcap.com/dist/npcap-sdk-1.13.zip
    # URL https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
)

FetchContent_MakeAvailable(npcap)

FetchContent_Declare(
    pcapplusplus
    SYSTEM
    GIT_REPOSITORY https://ghproxy.com/https://github.com/seladb/PcapPlusPlus
    GIT_TAG 7e965f4ef698308c929495a5cf983bed628058fa
)
set(PCAP_ROOT "${npcap_SOURCE_DIR}")
set(Packet_ROOT "${npcap_SOURCE_DIR}")
FetchContent_MakeAvailable(pcapplusplus)
```

**Comment by seladb** [comment]
thank you @egecetin for the quick response!

let's wait for @traversebitree to check both options and decide

**Comment by egecetin** [comment]
@seladb @traversebitree Looks like everyone fast today :). Since you are using FetchContent we can 100% sure you not modified it. We can update and disable warning I think

**Comment by seladb** [comment]
Thank you everyone for the quick turnaround!

I agree we can suppress this warning, it should be a very small PR. Can one of you volunteer to open it?

**Comment by egecetin** [comment]
@traversebitree Because you noticed it would you open a PR with fix?

**Comment by traversebitree** [comment]
@seladb @egecetin  Yes, I'll try it, maybe slow. Because I have not opened a PR :). So let me have a try.

**Comment by seladb** [comment]
Thank you @traversebitree for reporting this issue and for providing a quick fix! 🙏 ❤️ 
Your PR has been merged to `master`.

Thank you @egecetin for your assistance with identifying the issue and suggesting a solution! 🙏 ❤️
