### ISSUE TITLE
pcapplusplus  dpdk how  to do l2fwd with only two cpu cores

### ISSUE THREAD

**Issue by GREATwo** [seladb/PcapPlusPlus#1099]
I only have two cpu cores. How can I use pcapplusplus dpdk for Layer 2 forwarding? l2fwd in dpdk is OK, but dpdkbridge is not

**Comment by seladb** [comment]
DpdkBridge needs 3 cores:
- 1 management core (where the main thread runs)
- 2 worker cores - each worker receives network traffic from one interface and passes it to the other. Since there are 2 interfaces the workers work in opposite directions

Please let me know if it makes sense

**Comment by GREATwo** [comment]
> DpdkBridge needs 3 cores:
> 
>     * 1 management core (where the main thread runs)
> 
>     * 2 worker cores - each worker receives network traffic from one interface and passes it to the other. Since there are 2 interfaces the workers work in opposite directions
> 
> 
> Please let me know if it makes sense
> 
> EDIT: the architecture is described here with more details: https://pcapplusplus.github.io/docs/tutorials/dpdk#introduction

I think this is unreasonable. My cpu only has two cores. If I use dpdk l2fwd, it can work normally, but I Cannot use pcapplusplus dpdk, and Cannot run worker thread on DPDK master core

**Comment by seladb** [comment]
DpdkBridge is just an example app that shows how to use PcapPlusPlus with DPDK. It's not meant to be a production app.

You're more than welcome to modify it to match your needs

**Comment by GREATwo** [comment]
> 
It's not all dpdkbridge, judging master core in DpdkDeviceList.cpp causes at least three cpu cores to be needed, I modified this file and now two cpu cores are running


if (coreMask & getDpdkMasterCore().Mask)
	{
		PCPP_LOG_ERROR("Cannot run worker thread on DPDK master core");
		return false;
	}

**Comment by seladb** [comment]
Thanks for pointing this out. Usually it's not a good practice for a worker thread to run on the management core. However if you think there is value in it we can a boolean flag to `DpdkDeviceList::startDpdkWorkerThreads(...)` with a default value of `false`, maybe something like this:
```cpp
bool DpdkDeviceList::startDpdkWorkerThreads(CoreMask coreMask, std::vector<DpdkWorkerThread*>& workerThreadsVec, bool allowRunningOnMasterCore = false)
{
   ...
}
```

Would you consider opening a PR for this? Should be a pretty small change

**Comment by GREATwo** [comment]
Just add a Boolean flag no good, I use the rte_eal_mp_remote_launch (dpdkWorkerThreadStart, worker, CALL_MASTER); I don't know how to do that just with a bool flag

**Comment by seladb** [comment]
I'm not sure I understand. You said the part you'd like to disable is this:
https://github.com/seladb/PcapPlusPlus/blob/master/Pcap%2B%2B/src/DpdkDeviceList.cpp#L364-L368

The boolean flag should help to achieve that, no?

Can you paste the code you're trying to run so I can understand better?

**Comment by GREATwo** [comment]
Here is the code I modified to add a function startDpdkWorkerThread


bool DpdkDeviceList::startDpdkWorkerThread(CoreMask coreMask, DpdkWorkerThread* worker)
{
	if (!isInitialized())
	{
		PCPP_LOG_ERROR("DpdkDeviceList not initialized");
		return false;
	}

	CoreMask tempCoreMask = coreMask;
	size_t numOfCoresInMask = 0;
	int coreNum = 0;
	while (tempCoreMask > 0)
	{
		if (tempCoreMask & 1)
		{
			if (!rte_lcore_is_enabled(coreNum))
			{
				PCPP_LOG_ERROR("Trying to use core #" << coreNum << " which isn't initialized by DPDK");
				return false;
			}

			numOfCoresInMask++;
		}
		tempCoreMask = tempCoreMask >> 1;
		coreNum++;
	}

	if (numOfCoresInMask == 0)
	{
		PCPP_LOG_ERROR("Number of cores in mask is 0");
		return false;
	}
	m_WorkerThreads.clear();
        rte_eal_mp_remote_launch(dpdkWorkerThreadStart,worker, CALL_MASTER);
	m_WorkerThreads.push_back(worker);

	return true;
}

**Comment by seladb** [comment]
I'm not sure I understand why you removed this loop:
https://github.com/seladb/PcapPlusPlus/blob/master/Pcap%2B%2B/src/DpdkDeviceList.cpp#L372-L398

All you need to do is remove/disable this part: https://github.com/seladb/PcapPlusPlus/blob/master/Pcap%2B%2B/src/DpdkDeviceList.cpp#L364-L368

And everything should work. Unless I'm missing something...

**Comment by GREATwo** [comment]
My cpu only has two cores, one of which is for master core. If I do not delete this loop, if workerThreadsVec.size()==2, only one of my worker threads is running properly and the other run worker thread is not running, At this point workerThreadsVec makes no sense and misleads me, this change is only for my scene

Maybe I misunderstood

**Comment by seladb** [comment]
I'm confused again... do you want your master core to run as a worker thread and then you'll have 2 workers: one running on the master core and one running on the other core)?

Or do you want only 1 worker running on your non-master core?

**Comment by GREATwo** [comment]
Let me put it another way, I only have two cpu cores according to the method you provided, modify this to

https://github.com/seladb/PcapPlusPlus/blob/master/Examples/Tutorials/Tutorial-DpdkL2Fwd/main.cpp#L105-L108
```


for (int i = 0;  i <= 1;  i++)

{

workersCoreMask = workersCoreMask | (1 << i);

}
```


In theory, it should work fine, forwarding the packet, but my test results show that only one thread executes the callback function

https://github.com/seladb/PcapPlusPlus/blob/master/Examples/Tutorials/Tutorial-DpdkL2Fwd/WorkerThread.cpp#L11

What I need is two worker threads running

**Comment by seladb** [comment]
And if you disable JUST this part: https://github.com/seladb/PcapPlusPlus/blob/4e5b3e781d75395aaf3688cb542232540002225e/Pcap%2B%2B/src/DpdkDeviceList.cpp#L364-L368

It still doesn't work?

**Comment by seladb** [comment]
I think I got your point now: DPDK offers only 2 options:
- [`rte_eal_remote_launch`](https://doc.dpdk.org/api-19.02/rte__launch_8h.html#a7456c48bfd011b04cc1c17baac5aa058) to run a worker on a slave core only (which is what PcapPlusPlus is using)
- [`rte_eal_mp_remote_launch`](https://doc.dpdk.org/api-19.02/rte__launch_8h.html#a2f78fc845135fe22c1ba1c870954b60a) to run a worker on all cores, including the master core if called with [`CALL_MASTER`](https://doc.dpdk.org/api-19.02/rte__launch_8h.html#a83b0efa9e30a74217e7a95956845e2ada39ec34f33f669f99bd28ab7c58a952ac)

I didn't see an option to run on selective cores (like `rte_eal_remote_launch` does) but with an option that these core can be the master core.

So I'm not really sure how to solve it. One option is to expose a new API in PcapPlusPlus that allows running on all cores, maybe something like this:

```cpp
bool DpdkDeviceList::startDpdkWorkerThreads(std::vector<DpdkWorkerThread*>& workerThreadsVec, bool runAlsoOnMasterCore)
```

This API can call `rte_eal_mp_remote_launch`.

Please let me know what you think

**Comment by GREATwo** [comment]
This API can call rte_eal_mp_remote_launch is okay，But there is a problem with the master core blocking the main thread. I fix it by starting a child thread in the master thread's callback function to handle the packet

**Comment by seladb** [comment]
It feels to me like a specific use case that will need quite a lot of changes, I'm not sure if it's worth adding it. But if you want please feel free to create a PR and we can continue discussing then...

**Comment by GREATwo** [comment]
i create a PR

**Comment by seladb** [comment]
@GREATwo I'll close this issue now, please reopen if still relevant
