### ISSUE TITLE
IPv4 reassembly has small bug

### ISSUE THREAD

**Issue by dlbattle123** [seladb/PcapPlusPlus#110]
In the IPReassembly.cpp lines 442 and 522:
tempPacket.getLayerOfType<IPv4Layer>()->getIPv4Header()->totalLength = fragData->currentOffset + tempPacket.getLayerOfType<IPv4Layer>()->getHeaderLen();

Is missing a needed ntohs() around the new value for totalLength.  My work environment does not allow me to supply sample data or even submit patches.

**Comment by seladb** [comment]
Thanks for reporting this issue, it does look like a bug. I will try to provide a fix soon

**Comment by seladb** [comment]
Bug is fixed now
