### ISSUE TITLE
Can not work with Npcap

### ISSUE THREAD

**Issue by traversebitree** [seladb/PcapPlusPlus#1100]
OS: Windows 11 22621.1265
Compiler: VS 2022 (17.5.1)
CMake Version: 3.25.2

For reproductions, just clone this (Use `FetchContent` for all deps): [https://github.com/traversebitree/PcapPlusPlus-example](https://github.com/traversebitree/PcapPlusPlus-example).

The C++ code is just from [https://github.com/seladb/PcapPlusPlus#getting-started](https://github.com/seladb/PcapPlusPlus#getting-started).

When using `PcapPlusPlus` + `WinPcap`, the program runs ok.
![gif1](https://user-images.githubusercontent.com/30373236/224367981-38d2de16-2f79-4f92-b1d2-bf2f667e3eed.gif)

But when using `PcapPlusPlus` + `Npcap`, the program runs failed without any prompt (Can build but run failed).
![gif2](https://user-images.githubusercontent.com/30373236/224369164-5390eb99-2772-4582-86cc-c344bb5456d3.gif)

**Comment by seladb** [comment]
@traversebitree can you try to debug and see if it crashes and where?

This code doesn't even use a network interface - it just reads the content of a pcap file. I see no reason why it shouldn't work

**Comment by seladb** [comment]
This might be a related issue: https://github.com/seladb/PcapPlusPlus/issues/1084

Both occur on Windows 11 / VS 2022

**Comment by traversebitree** [comment]
@seladb I have debugged it. When using `PcapPlusPlus` + `WinPcap`, Debug works ok, but when using `PcapPlusPlus` + `Npcap`, Debug failed. (I have installed Npcap's driver)
- Use `PcapPlusPlus` + `WinPcap`, debug works ok:
![gif1](https://user-images.githubusercontent.com/30373236/224472338-d5737fdb-df94-4026-87f1-a75d1e650150.gif)


- Use `PcapPlusPlus` + `Npcap`, debug failed.
![gif2](https://user-images.githubusercontent.com/30373236/224472342-7ab1b9f5-dde4-46ab-97da-1f7e12cd58f2.gif)


![image](https://user-images.githubusercontent.com/30373236/224472129-3a4e34d4-d9fe-4d4b-9e66-f3f25c657b5e.png)
![image](https://user-images.githubusercontent.com/30373236/224472146-6098b152-8655-4fe3-86f9-2cb93449e035.png)
![image](https://user-images.githubusercontent.com/30373236/224472151-bd7f6152-d1b0-4e95-8275-55150a162541.png)

**Comment by traversebitree** [comment]
@seladb I also used VCPKG's PcapPlusPlus lib, I inspected the build process of VCPKG, it builds PcapPlusPlus depending on `WinPcap` rather than `Npcap` (VCPKG automatically builds `WinPcap` before building `PcapPlusPlus`).

**Comment by seladb** [comment]
I'm not sure why it happens. Maybe you can add prints in the code to see where it fails (old-style debugging)? 🤔

**Comment by traversebitree** [comment]
I've added a print, but when using `PcapPlusPlus` + `Npcap`, the program couldn't even start and couldn't output anything. I guess the problem arises from `Npcap`?
- `PcapPlusPlus` + `WinPcap` is Ok, can print something:
![gif1](https://user-images.githubusercontent.com/30373236/224473007-ebb935cf-936c-419f-bd3c-9676ad70d015.gif)

- `PcapPlusPlus` + `Npcap` failed, nothing printed:
![gif2](https://user-images.githubusercontent.com/30373236/224473017-cdef1609-b9b6-4347-b97b-bff41a008970.gif)

**Comment by seladb** [comment]
Yes, this is probably something with Npcap, but I'm trying to figure out what 🤔

**Comment by seladb** [comment]
I'm trying to get a VM with Windows 11 and VS 2022, it might take me some time to set it up. In the meantime maybe you can try to do further investigation to find out where the issue is?

BTW, does Wireshark work well with Npcap?

**Comment by traversebitree** [comment]
Wireshark works well with Npcap. And I used to use `dpkt` [https://github.com/kbandla/dpkt](https://github.com/kbandla/dpkt) in Python and `gopacket` [https://github.com/google/gopacket](https://github.com/google/gopacket) in Golang, all works well.

**Comment by seladb** [comment]
@traversebitree which Npcap version are you using?

Also - which Npcap SDK version?

https://npcap.com/#download

**Comment by traversebitree** [comment]
@seladb 
Npcap version: 1.72
Npcap sdk version: 1.13
All latest. And I've tried sdk verson 1.12, also failed.

**Comment by seladb** [comment]
ok, I'll test it on my VM and let you know (might take me some time).

By the way - did you test with VS 2019 and/or Windows 10?

**Comment by traversebitree** [comment]
@seladb  Not yet. I'll try to start a VM later and have a try.

**Comment by seladb** [comment]
I test it on a VM with the same system and your program seems to work well:
- Windows 11
- VS 2022 (17.5.1)
- CMake 3.25
- Npcap version: 1.72
- Npcap SDK version: 1.13

![image](https://user-images.githubusercontent.com/9059541/224479585-0e499a9f-de09-41e7-b897-6ed63b2c3fab.png)

**Comment by traversebitree** [comment]
@seladb Do you use this one in CMake??
![image](https://user-images.githubusercontent.com/30373236/224479689-3bea775b-f4b0-491e-984b-44763c5e29ad.png)

**Comment by seladb** [comment]
Yes:

![image](https://user-images.githubusercontent.com/9059541/224480049-cbfcc181-0a50-4579-9909-0c4a44c5bd8f.png)

**Comment by traversebitree** [comment]
@seladb Wow... Why? Isn't it just to install the installer [https://npcap.com/dist/npcap-1.72.exe](https://npcap.com/dist/npcap-1.72.exe) directly is OK?

**Comment by seladb** [comment]
Maybe you should install Npcap in WinPcap API-compatible more (I think that's what I did)

**Comment by traversebitree** [comment]
> Maybe you should install Npcap in WinPcap API-compatible mode (I think that's what I did)

@seladb Yes my brother, I checked this option (Install Npcap in WinPcap API-compatible Mode), and it works.
Thank you so much for such a detailed and hard-to-find problem.

**Comment by seladb** [comment]
Awesome!! Maybe we should mention it in PcapPlusPlus documentation: 

https://pcapplusplus.github.io/docs/next/install/vs
https://pcapplusplus.github.io/docs/next/install/mingw

I'll make sure to do that
