### ISSUE TITLE
Large UDP packets truncated

### ISSUE THREAD

**Issue by ri28856** [seladb/PcapPlusPlus#1115]
Hello,

I've been experimenting with PcapPlusPlus on a RHEL9 system attached to a Mellanox switch. I have an application to decode a custom protocol built on top of UDP. I am using libpcap as my capture library. 

Sometimes I encounter a packet that is slightly larger than my MTU of 9000 bytes. I suspect this might be due to my NIC handling some of the packet assembly, and the measurement point happens before that. 

Here is a wireshark capture:
![image](https://user-images.githubusercontent.com/123106555/229923533-17d38b13-3970-40eb-9d94-8ab54afde72a.png)

The IPV4 header + payload comes out to exactly the MTU. The total bytes received with the Ethernet frame header is 9014. The RawPacket that the PcapLiveDevice returns to me is always 9000 bytes long, and includes the ethernet header, meaning I'm missing the final 14 bytes of my UDP payload. Is there any way I could capture all 9014 bytes?

Honestly I have no idea if this is a bug, or if I'm abusing this library, or I have something misconfigured. Any guidance would be appreciated.

**Comment by seladb** [comment]
thanks for reaching out @ri28856 ! Can you please share the code you wrote to capture and parse the packet?

I think I found the issue! the default `DEFAULT_SNAPLEN` configured for any device is 9000 bytes: https://github.com/seladb/PcapPlusPlus/blob/6b0febc99c46da163c9809df11206dbab03e8857/Pcap%2B%2B/src/PcapLiveDevice.cpp#L47

However you can change this configuration using [`DeviceConfiguration.snapshotLength`](https://github.com/seladb/PcapPlusPlus/blob/6b0febc99c46da163c9809df11206dbab03e8857/Pcap%2B%2B/header/PcapLiveDevice.h#L212).

When opening the device you can do something like this:
```cpp
pcpp::PcapLiveDevice::DeviceConfiguration devConfig;
devConfig.snapshotLength = 9014;

dev->open(devConfig);
...
```

Please let me know if this solves the issue.

**Comment by seladb** [comment]
I'm happy it worked, thanks again for reaching out!
