### ISSUE TITLE
Unable to write with nanoseconds precision

### ISSUE THREAD

**Issue by rychale** [seladb/PcapPlusPlus#112]
Is it possible to generate PCAPNG file with packets having nanoseconds timestamp precision?

**Comment by seladb** [comment]
Unfortunately PcapPlusPlus doesn't currently support writing or reading packets with nanoseconds timestamp precision. I may add this feature sometime in the future but I can't promise when.

**Comment by Akvinikym** [comment]
Hello! It's an old issue, but we encountered it as well, so I am going to implement this feature. Will land a PR as soon as it's ready

**Comment by seladb** [comment]
That'd be awesome, thank you! Looking forward for your PR

**Comment by seladb** [comment]
@Akvinikym I just noticed you were using a non-GitHub username for your commits (Pavel) so you're not included in the contributors list of PcapPlusPlus. If you'd like to be included you need to add the email address you were using to your GitHub account (you can do this here: https://github.com/settings/emails)

**Comment by Akvinikym** [comment]
@seladb added the email

**Comment by seladb** [comment]
@Akvinikym thank you so much for your contribution to this project, I really appreciate it!

I'll close this issue now
