### ISSUE TITLE
memory leak in pcpp::PcapLiveDeviceList

### ISSUE THREAD

**Issue by faust403** [seladb/PcapPlusPlus#1122]
How can i prevent this memory leak?

```
# include <pcapplusplus/PcapLiveDeviceList.h>
int main(void)
{
    pcpp::PcapLiveDeviceList const& List = pcpp::PcapLiveDeviceList::getInstance();
}
```

valgrind ./main
==27455== Memcheck, a memory error detector
==27455== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==27455== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
==27455== Command: ./main
==27455== 
==27455== 
==27455== HEAP SUMMARY:
==27455==     in use at exit: 660 bytes in 25 blocks
==27455==   total heap usage: 1,862 allocs, 1,837 frees, 324,203 bytes allocated
==27455== 
==27455== LEAK SUMMARY:
==27455==    definitely lost: _**120 bytes in 3 blocks**_
==27455==    indirectly lost: **_540 bytes in 22 blocks_**
==27455==      possibly lost: 0 bytes in 0 blocks
==27455==    still reachable: 0 bytes in 0 blocks
==27455==         suppressed: 0 bytes in 0 blocks
==27455== Rerun with --leak-check=full to see details of leaked memory
==27455== 
==27455== For lists of detected and suppressed errors, rerun with: -s
==27455== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**Comment by seladb** [comment]
@faust403 maybe this is because `PcapLiveDeviceList` is a singleton?
https://github.com/seladb/PcapPlusPlus/blob/master/Pcap%2B%2B/header/PcapLiveDeviceList.h#L45-L49

**Comment by seladb** [comment]
Thank you @leha-bot for the info!

@faust403 can we close the issue?

**Comment by faust403** [comment]
y, thank you!
