### ISSUE TITLE
virtio_dev_configure(): Unsupported Rx multi queue mode 1 Port0 dev_configure = -22 [ERROR: src/DpdkDevice.cpp: configurePort:268        ] Failed to configure device [DPDK_0]. error is: 'Unknown error -22' [Error code: -22]  ERROR: Couldn't open DPDK device #0, PMD 'net_virtio'

### ISSUE THREAD

**Issue by Bangyan-Zhang** [seladb/PcapPlusPlus#1125]
I am running the case: DpdkTrafficFilter in an Alibaba Cloud instance. I encountered an error and found online that DPDK virtio PMD does not support RSS. Is this the case?

**Comment by seladb** [comment]
@Bangyan-Zhang yes, I suspect this is the reason for this error. It's returned from DPDK when calling `rte_eth_dev_configure()` with RSS configuration

**Comment by Bangyan-Zhang** [comment]
@seladb Thank you for your answer. Previously, I used dpdk20.11, but later I discovered that DPDK virtio PMD for dpdk21.11 supports RSS. Therefore, I installed dpdk21.11 with Pcap+22.11 and ran DpdkTrafficFilter, but encountered an error: RSS unsupported device. My network card is Red Hat, Inc. Virtio network device. Have you tested this network card before? If I don't want to use RSS, can I ask how to set it in pcap++? I have tried changing the default value of rssHashFunction in DpdkDeviceConfiguration from RSS_DEFAULT changed toRSS_NONE，but it didn't work.

**Comment by seladb** [comment]
@Bangyan-Zhang I never tested with this network card, but PcapPlusPlus should support cards that don't support RSS...

Can you write code (or modify `DpdkTrafficFilter`) that will call `dev->getSupportedRssHashFunctions()` on your DPDK device and share the output? I'm curious if the device really doesn't support RSS, or maybe it's something else...

**Comment by Bangyan-Zhang** [comment]
@seladb 
I add the code `uint64_t devnumber = dev->getSupportedRssHashFunctions();
		EXIT_WITH_ERROR("SupportedRssHashFunctions = " << devnumber);` in 
I added these two lines of code `uint64_t devnumber = dev->getSupportedRssHashFunctions();
		EXIT_WITH_ERROR("SupportedRssHashFunctions = " << devnumber);` to line 494 in main.cpp of DpdkTrafficFilter, but after compiling and running, I received the following error message:
# ./DpdkTrafficFilter -d 0
EAL: Detected CPU lcores: 12
EAL: Detected NUMA nodes: 1
EAL: Detected shared linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available 1048576 kB hugepages reported
EAL: VFIO support initialized
EAL: Probe PCI driver: net_virtio (1af4:1000) device: 0000:00:03.0 (socket 0)
eth_virtio_pci_init(): Failed to init PCI device
EAL: Requested device 0000:00:03.0 cannot be used
EAL: Probe PCI driver: net_virtio (1af4:1000) device: 0000:00:07.0 (socket 0)
EAL: Using IOMMU type 8 (No-IOMMU)
TELEMETRY: No legacy callbacks, legacy socket not created

ERROR: SupportedRssHashFunctions = 0


Without adding these two lines of code, the error message is as follows:
# ./Bin/DpdkTrafficFilter -d 0
EAL: Detected CPU lcores: 12
EAL: Detected NUMA nodes: 1
EAL: Detected shared linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available 1048576 kB hugepages reported
EAL: VFIO support initialized
EAL: Probe PCI driver: net_virtio (1af4:1000) device: 0000:00:03.0 (socket 0)
eth_virtio_pci_init(): Failed to init PCI device
EAL: Requested device 0000:00:03.0 cannot be used
EAL: Probe PCI driver: net_virtio (1af4:1000) device: 0000:00:07.0 (socket 0)
EAL: Using IOMMU type 8 (No-IOMMU)
TELEMETRY: No legacy callbacks, legacy socket not created
virtio_dev_configure(): RSS support requested but not supported by the device
Port0 dev_configure = -95
[ERROR: src/DpdkDevice.cpp: configurePort:268        ] Failed to configure device [DPDK_0]. error is: 'Unknown error -95' [Error code: -95]

ERROR: Couldn't open DPDK device #0, PMD 'net_virtio'

**Comment by Bangyan-Zhang** [comment]
@seladb 
I added these two lines of code `uint64_t devnumber = dev->getSupportedRssHashFunctions();
		EXIT_WITH_ERROR("SupportedRssHashFunctions = " << devnumber);` to line 494 in main.cpp of DpdkTrafficFilter, but after compiling and running, I received the following error message:
# ./DpdkTrafficFilter -d 0
EAL: Detected CPU lcores: 12
EAL: Detected NUMA nodes: 1
EAL: Detected shared linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available 1048576 kB hugepages reported
EAL: VFIO support initialized
EAL: Probe PCI driver: net_virtio (1af4:1000) device: 0000:00:03.0 (socket 0)
eth_virtio_pci_init(): Failed to init PCI device
EAL: Requested device 0000:00:03.0 cannot be used
EAL: Probe PCI driver: net_virtio (1af4:1000) device: 0000:00:07.0 (socket 0)
EAL: Using IOMMU type 8 (No-IOMMU)
TELEMETRY: No legacy callbacks, legacy socket not created

ERROR: SupportedRssHashFunctions = 0


Without adding these two lines of code, the error message is as follows:
# ./Bin/DpdkTrafficFilter -d 0
EAL: Detected CPU lcores: 12
EAL: Detected NUMA nodes: 1
EAL: Detected shared linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available 1048576 kB hugepages reported
EAL: VFIO support initialized
EAL: Probe PCI driver: net_virtio (1af4:1000) device: 0000:00:03.0 (socket 0)
eth_virtio_pci_init(): Failed to init PCI device
EAL: Requested device 0000:00:03.0 cannot be used
EAL: Probe PCI driver: net_virtio (1af4:1000) device: 0000:00:07.0 (socket 0)
EAL: Using IOMMU type 8 (No-IOMMU)
TELEMETRY: No legacy callbacks, legacy socket not created
virtio_dev_configure(): RSS support requested but not supported by the device
Port0 dev_configure = -95
[ERROR: src/DpdkDevice.cpp: configurePort:268        ] Failed to configure device [DPDK_0]. error is: 'Unknown error -95' [Error code: -95]

ERROR: Couldn't open DPDK device #0, PMD 'net_virtio'

**Comment by seladb** [comment]
it identifies correctly that RSS is not supported... can you share the complete "RSS unsupported device" that you get? Which part of PcapPlusPlus code throws it?

**Comment by Bangyan-Zhang** [comment]
@seladb ，hi， seladb. I want to convert the mq of dpdk_ Set mode to ETH_ MQ_ RX_ NONE, how can I implement it in Pcap++? I did not see the relevant interface implementing this function.

**Comment by seladb** [comment]
Hmm I'm not sure there is a way to do that, maybe that's the reason it's not working?

You can try to set it here: https://github.com/seladb/PcapPlusPlus/blob/fb3a560482cbc3d5f12c2fa0b49e55cb3e0ab139/Pcap%2B%2B/src/DpdkDevice.cpp#L262

Let me know if that works, if it does maybe we can fix that

**Comment by Bangyan-Zhang** [comment]
In the morning, I took the DPDK_ CONFIG_ MQ_ Change the value of MODE to ETH_ MQ_  RX_  After NONE, it works.

**Comment by Bangyan-Zhang** [comment]
I can open a PR, what should I do?

**Comment by Bangyan-Zhang** [comment]
I have never opened PR before

**Comment by seladb** [comment]
You can read this documentation from GitHub on how to open PRs (pull requests): https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

Also please refer to [`CONTRIBUTING.md`](https://github.com/seladb/PcapPlusPlus/blob/master/CONTRIBUTING.md) to learn how to open PRs for PcapPlusPlus

**Comment by Bangyan-Zhang** [comment]
Thank you very much. I will read it carefully.

**Comment by seladb** [comment]
@Bangyan-Zhang are you still planning to open a PR with the fix?

**Comment by Bangyan-Zhang** [comment]
Sorry, I don't have time to do this in the short term.

**Comment by seladb** [comment]
@Bangyan-Zhang the fix was merged to `master`. Can you please verify it works?

I'll close the issue for now, if the fix doesn't work we can reopen it
