### ISSUE TITLE
EAL: FATAL: Invalid 'command line' arguments.

### ISSUE THREAD

**Issue by Bangyan-Zhang** [seladb/PcapPlusPlus#1127]
I am trying to generate a CoreMask using the functions createCoreMaskFromCoreVector and createCoreMaskFromCoreIds. The codes for both methods are as follows:
createCoreMaskFromCoreVector :
 std::vector<pcpp::SystemCore> cores = {{ 0x02, 1 }, { 0x04, 2 }, { 0x08, 3 }};
 pcpp::CoreMask coreMaskToUse = pcpp::createCoreMaskFromCoreVector(cores);
createCoreMaskFromCoreIds:
std::vector<int> cores = {1, 2, 3};
 pcpp::CoreMask coreMaskToUse =pcpp::createCoreMaskFromCoreIds(cores);
But I encountered an error:
EAL: FATAL: Invalid 'command line' arguments.
EAL: Invalid 'command line' arguments.
[ERROR: src/DpdkDeviceList.cpp: initDpdk:143         ] failed to init the DPDK EAL

May I ask where I was wrong?

@

**Comment by seladb** [comment]
Here is how you should use these methods:

```cpp
auto coreVector = std::vector<pcpp::SystemCore>{pcpp::SystemCores::Core1, pcpp::SystemCores::Core2, pcpp::SystemCores::Core3};
auto coreMask = pcpp::createCoreMaskFromCoreVector(coreVector);

auto coreIdVector = std::vector<int>{1, 2, 3};
auto coreMask2 = pcpp::createCoreMaskFromCoreIds(coreIdVector);

```

**Comment by Bangyan-Zhang** [comment]
I have tried the way you said it, but it is still the same mistake.
@seladb

**Comment by seladb** [comment]
Which version of PcapPlusPlus are you using?

**Comment by Bangyan-Zhang** [comment]
@seladb  22.11

**Comment by seladb** [comment]
It's hard to say... maybe you can debug it and try to figure out what's the issue?

**Comment by Bangyan-Zhang** [comment]
Okay, after I finish working for a while, I will debug and see where the bug is.

**Comment by seladb** [comment]
@Bangyan-Zhang did you make any progress on this?

**Comment by seladb** [comment]
@Bangyan-Zhang I'll close this issue now, please reopen if still relevant
