### ISSUE TITLE
How to use Pcap++to convert dpdk's mq_ Set mode to ETH_ MQ_ RX_ NONE

### ISSUE THREAD

**Issue by Bangyan-Zhang** [seladb/PcapPlusPlus#1128]
I want to convert the mq of dpdk_ Set mode to ETH_ MQ_ RX_ NONE, how can I implement it in Pcap++? I did not see the relevant interface implementing this function.

**Comment by seladb** [comment]
It looks like the same question as here: https://github.com/seladb/PcapPlusPlus/issues/1125#issuecomment-1521079244
Please see my answer here: https://github.com/seladb/PcapPlusPlus/issues/1125#issuecomment-1521229198

I'll close this issue so we can discuss it there
