### ISSUE TITLE
Dns MX record

### ISSUE THREAD

**Issue by inbrahimnasson** [seladb/PcapPlusPlus#113]
1. In constructing a dns MX answer there is no way to set the PREFERENCE of the mail exchange answer

2. As in RFC 1035 section 4.1.4 (  https://tools.ietf.org/html/rfc1035 )  please would add a possible way to use dnsQuery pointer to the query name offset ,instead of using string inDnsResource->setName() in which cause the packet to increase in size ,

E.g  message compression

DnsResource *res=dnsLayer->addAnswer( dnsQuery->getNameOffset,DNS_TYPE_MX,DNS_CLASS_IN,preference, “thanks.help.me”)

**Comment by seladb** [comment]
These are good enhancement suggestions. Do you mind doing these changes and create a PR?

**Comment by inbrahimnasson** [comment]
Sure i will do it

**Comment by seladb** [comment]
Thanks! Please create a PR once it's ready

**Comment by seladb** [comment]
For the MX part I came up with a new design for DNS records data that should fix this. Please give me a couple of days to complete the implementation and tests and I'll push it to master.

Then I'll have a look at the second request which is adding pointers instead of full names

**Comment by seladb** [comment]
Fixed both issues:

1. When adding a DNS record you can now add MX data, for example:
```
pcpp::DnsLayer* dnsLayer = dnsPacket.getLayerOfType<pcpp::DnsLayer>();
pcpp::MxDnsResourceData mxDnsData(1, "mta5.am0.yahoodns.net");
pcpp::DnsResource* answer = dnsLayer->addAnswer("yahoo.com", pcpp::DNS_TYPE_MX, pcpp::DNS_CLASS_IN, 187, &mxDnsData);
```

2. You can now set DNS RR name or data with pointers using a string that contains `#{offset}`, for example:
```
pcpp::DnsResource* dnsAnswerRR = ...;
dnsAnswerRR->setName("my.subdomain.#12");
```
  Or:
```
pcpp::DnsLayer* dnsLayer = dnsPacket.getLayerOfType<pcpp::DnsLayer>();
pcpp::MxDnsResourceData mxDnsData(1, "mta5.am0.#12");
pcpp::DnsResource* answer = dnsLayer->addAnswer("yahoo.com", pcpp::DNS_TYPE_MX, pcpp::DNS_CLASS_IN, 187, &mxDnsData);
```

**Comment by ibrahimnasson** [comment]
Thanks
