### ISSUE TITLE
Read compressed pcapng file with index

### ISSUE THREAD

**Issue by YIFEI-MA** [seladb/PcapPlusPlus#1132]
I am working on a project that recording (write) and playback (read) compressed pcapng.zstd files using pcap++. For playback in my use case, it frequently require changing playback progress. All the recorded packets are sorted by timestamp when it wrote to pcapng files. I noticed that currently there is no method to get packets by indices in PcapNgFileReaderDevice (sequential read with getNextPacket() is very slow when jump progress backwards). Any ideas on how to implement this feature? Or any other ideas in improving performance on changing progress when reading large compressed pcapng files?

**Comment by seladb** [comment]
@YIFEI-MA I don't think there is an easy way to read a packet by index. The pcapng format is a long list of packet blocks so retrieving a packet by index would anyway require going over all the blocks until reaching the desired index.

Here is the low-level implementation of `light_get_next_packet` which gets the next packet in a pcapng file: https://github.com/seladb/PcapPlusPlus/blob/44b1ec4819724cf36302ce29535c28f2c0224045/3rdParty/LightPcapNg/LightPcapNg/src/light_pcapng_ext.c#L377

If you think there's a way to significantly improve iterating over the packets in a file, please feel free to open a PR

**Comment by seladb** [comment]
@YIFEI-MA I'll close this issue now, please feel free to reopen if you find a way to implement it
