### ISSUE TITLE
DPDK forwarding - memory problem

### ISSUE THREAD

**Issue by c0zak** [seladb/PcapPlusPlus#1141]
**Describe the bug**

Created traffic redirect between two dpdk interfaces, input traffic - QinQ (double vlan tag), output traffic - 802.1q (single vlan tag). Based on the Tutorial-DpdkL2Fwd example.
If a single packet arrives first, and then the interface is heavily loaded with the same packets, a failure occurs with the following description:

_

> Tutorial-DpdkL2Fwd: malloc.c:2415: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

_

**To Reproduce**

1) In the Tutorial-DpdkL2Fwd example, make changes to the WorkerThread.cpp file, change the packet forwarding cycle:

``` c++
while (!m_Stop){
	// receive packets from RX device
	uint16_t numOfPackets = m_RxDevice->receivePackets(mbufArr, 64, 0);
	if (numOfPackets > 0)
	{
		for (int i = 0; i < numOfPackets; i++) {
			pcpp::RawPacket* inPacket = mbufArr[i];
			int length = inPacket->getRawDataLen();
			const uint8_t* payload = inPacket->getRawData();
			if (length > 24) {
				if (payload[12] == 0x81 && payload[13] == 0x00 && payload[16] == 0x81 && payload[17] == 0x00 &&
					payload[20] == 0x08 && payload[21] == 0x00 && payload[22] == 0x45 && payload[23] == 0x00) {
						
						uint8_t* outPayload = new uint8_t[length - 4];
						memcpy(outPayload, payload, 14);
						outPayload[14] = 0x01;
						outPayload[15] = 0xF4;
						memcpy(outPayload + 16, payload + 20, length - 16);
						inPacket->setRawData(outPayload, length, inPacket->getPacketTimeStamp()); //This call produce error
				}
			}
		}
		// send received packet on the TX device
		m_TxDevice->sendPackets(mbufArr, numOfPackets, 0);
	}
}
```

2) With any traffic generator that supports dual vlan tags (like packETH), send one packet first and then send a stream of the same packets.

**Comment by c0zak** [comment]
Hi @seladb!

I'm afraid that the mistake was still in me :)

1) Research has shown that the first problem is related to using the memcpy function to pass data to a non-const array:

```c++
memcpy(outPayload, payload, 14);
```

Under certain conditions, this call caused a crash.

2) The second problem was reusing the RawPacket object with a non-const array:

```c++
uint8_t* outPayload = new uint8_t[length - 4];
...
inPacket->setRawData(outPayload, length, inPacket->getPacketTimeStamp());
```

It could also cause an error, and generally regardless of the conditions.

3) Research has also shown that if a RawPacket object is created using **uint8_t*** rather than **const uint8_t***, the memory is not freed after it is used, even if the **deleteRawDataAtDestructor** flag is set to true. Using delete on a RawPacket object will cause a double free error. First you need to change the pointer type.

4) In general, here is a fully working version of this code that does not suffer from memory leaks and crashes, and is also significantly faster than recompiling packets by using Packet object with VlanLayer:

``` c++
while (!m_Stop)
	{
		uint16_t numOfPackets = m_RxDevice->receivePackets(mbufArr, DEEP, 0);
		if (numOfPackets > 0)
		{
			
			for (int i = 0; i < numOfPackets; i++)
			{
				pcpp::RawPacket* inPacket = mbufArr[i];
				const uint8_t* payload = inPacket->getRawData();
				int length = inPacket->getRawDataLen();
				uint8_t* outPayload = new uint8_t[length - 4];
				if (payload[12] == 0x81 && payload[13] == 0x00 && payload[16] == 0x81 && payload[17] == 0x00) {
					for (int i = 0; i < 14; i++)
						outPayload[i] = payload[i];
					outPayload[14] = 0x01;
					outPayload[15] = 0xF4;
					for (int i = 16; i < length - 4; i++)
						outPayload[i] = payload[i+4];
				}

				const uint8_t* mock = reinterpret_cast<const uint8_t*>(outPayload);
				pcpp::RawPacket* packet = new pcpp::RawPacket(mock, length - 4, mbufArr[i]->getPacketTimeStamp(), true);
				m_TxDevice->sendPacket(*packet);
				delete packet;
			}
		}
	}

	return true;
}
```

That's all, I think the issue can be closed :)

P.S. 
Speed of work:

![изображение](https://github.com/seladb/PcapPlusPlus/assets/68700317/642eddb1-c0d2-46b2-9f6b-99c6936ee84b)
Packet size 64 bytes

![изображение](https://github.com/seladb/PcapPlusPlus/assets/68700317/41bd3612-18d9-43c8-b5ee-1d313bdcca14)
Packet size 1500 bytes

**Comment by seladb** [comment]
Thank you @c0zak for the thorough explanation!
