### ISSUE TITLE
question about HttpResponseLayer/HttpRequest

### ISSUE THREAD

**Issue by ccworkhard** [seladb/PcapPlusPlus#1145]
In this library, HttpResponseLayer/HttpRequest Layer will analyze the request body. I noticed that it checks each package. I have a question. If a complete http request is divided into two packages and arrives at the server, will the second packet be detected and mark it HTTP?

**Comment by seladb** [comment]
I'm sorry for the delayed response @ccworkhard . `HttpRequestLayer` and `HttpResponseLayer` only parse the request header, not the request body. If the header is divided into multiple packets, only the first one will be analyzed. You can know if the header is complete or not by using the method `isHeaderComplete()`

**Comment by seladb** [comment]
well, I thought about it, but didn't actually implement it yet. Currently PcapPlusPlus only supports parsing of individual packets. As a workaround you can use TCP reassembly, save the output as a packet and then parse it. But this will require some additional code

**Comment by ccworkhard** [comment]
> well, I thought about it, but didn't actually implement it yet. Currently PcapPlusPlus only supports parsing of individual packets. As a workaround you can use TCP reassembly, save the output as a packet and then parse it. But this will require some additional code

i'm trying to complete it. wow, Can i be a contributor?

**Comment by ccworkhard** [comment]
> Yes of course! You're more than welcome to contribute to this project.
> 
> However please take into account that implementing such a feature (not the workaround I suggested) is going to be somewhat tricky...

yeah, I noticed that it may need a thread pool, a buffer, file IO... 
But I'll give it a try, see you next time in the PR.

**Comment by tigercosmos** [comment]
seems https://github.com/seladb/PcapPlusPlus/pull/1212 is working on it.

**Comment by tigercosmos** [comment]
> > seems #1212 is working on it.
> 
> ![image](https://private-user-images.githubusercontent.com/64669718/309967706-afb645fd-bb29-49dc-b37e-24985e01992e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTMyOTcsIm5iZiI6MTcwOTYxMjk5NywicGF0aCI6Ii82NDY2OTcxOC8zMDk5Njc3MDYtYWZiNjQ1ZmQtYmIyOS00OWRjLWIzN2UtMjQ5ODVlMDE5OTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA0Mjk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4OGJhYWMxZDg1ZjQxMTFmNDRjZWNhODI0YTc0OTUxMGJiMGQzNTYwYTgxZWRkZThhMzAyOTU1ZjgzYmU1ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yE4s9Bq1ZDRwBS6Z3kCHc5rsp-BTag0smbKFOFb6zJc)
> 
> Do you know a good library for parsing http like this one, not too slow?
> 
> I just need to implement this parsing of HTTP request and response packets.
> 
> The pair corresponds to 2 elements, the http request and the response.

PcapPlusPlus already helps you distinguish between request and response.
If the response involves more than 1 packet, the easiest way is to concat the packet payload by yourself. Of course, if the packets are out of order, it may be more difficult.

**Comment by seladb** [comment]
> By the way, do you have any knowledge of projects that implement this complete HTTP request and HTTP return?

do you need a library that parses HTTP traffic from network packets?

**Comment by seladb** [comment]
if you just need to handle HTTP traffic, you can use any web server, including those included in Python or Javascript/Typescript?

**Comment by seladb** [comment]
maybe you can use this library? https://github.com/hsiafan/httpdump
