### ISSUE TITLE
pcpp::Packet::destructPacketData() segfault

### ISSUE THREAD

**Issue by asqapro** [seladb/PcapPlusPlus#1149]
I'm using v22.11, installed on Linux from source. 

Code that segfaults:

```
pcpp::Packet segfault_example()
{
    pcpp::EthLayer newEthernetLayer(pcpp::MacAddress("00:50:43:11:22:33"), pcpp::MacAddress("aa:bb:cc:dd:ee"));
    pcpp::Packet newPacket(100);
    newPacket.addLayer(&newEthernetLayer);
    return newPacket; // segfault here
}

int main()
{
    segfault_example();
    return 0;
}
```

I repurposed the example from the [PcapPlusPlus tutorial](https://pcapplusplus.github.io/docs/tutorials/packet-crafting#packet-creation) for crafting a packet and placed it into a function to create ICMP packets. After trying to run the function, I got a segfault with no obvious reason why. I stripped out most of the code that was not related to the segfault and set breakpoints to find the actual code that was breaking. I traced it down to:

 `Packet++ -> src -> Packet.cpp -> Packet::destructPacketData()`

```
[145] void Packet::destructPacketData()
[146] {
[147]     Layer* curLayer = m_FirstLayer;
[148]     while (curLayer != NULL)
[149]     {
[150]         Layer* nextLayer = curLayer->getNextLayer();
[151]         if (curLayer->m_IsAllocatedInPacket)
[152]             delete curLayer;
[153]         curLayer = nextLayer;
[154]     }
[155]
[156]     if (m_RawPacket != NULL && m_FreeRawPacket)
[157]     {
[158]         delete m_RawPacket;
[159]     }
[160] }
```

Line 152 specifically. In the example code that I used, the `EthLayer` object was created without using `new`, so when `destructPacketData()` gets called, it tries to `delete` an object that doesn't have a corresponding `new` call and segfaults. On line 151 of `Packet.cpp`, I can see there's a check to see if `m_IsAllocatedInPacket` is `true`, but when I create a watch for that variable and break on that line, its value is `72`, not `true` or `false`. 

Even stranger, if I add a line that calls `getDestMac()` or `getSourceMac()` on the `EthLayer` before `return newPacket`, it no longer segfaults. If I break on line 151 in `Packet.cpp`, I can see that `m_IsAllocatedInPacket` is set to `false`. Below is an example of what I mean:

```
pcpp::Packet no_segfault_example()
{
    pcpp::EthLayer newEthernetLayer(pcpp::MacAddress("00:50:43:11:22:33"), pcpp::MacAddress("aa:bb:cc:dd:ee"));
    newEthernetLayer.getDestMac(); // new addition
    pcpp::Packet newPacket(100);
    newPacket.addLayer(&newEthernetLayer);
    return newPacket; // no segfault here
}

int main()
{
    no_segfault_example();
    return 0;
}
```

I can simply use `new` when creating `newEthernetLayer`, but I believe this segfault is unintended. It seems like the issue lies with the initialization of `m_IsAllocatedInPacket`, but I'm not sure.

**Comment by seladb** [comment]
@asqapro I'm sorry for the late response. Maybe it's related to the fact that both `newEthernetLayer` and `newPacket` are created as local variables on the stack which means they're freed when `segfault_example()` ends, plus a copy constructor is called to copy `newPacket` to the return value. But to be honest, I'm not sure I can pinpoint where the failure is exactly.
Unfortunately I don't have a lot of time to dig deeper into the problem. Maybe you can debug it further?

**Comment by seladb** [comment]
@asqapro I'll close this issue now, please reopen if still relevant
