### ISSUE TITLE
Setup fails on MinGW-w64 Windows

### ISSUE THREAD

**Issue by MinGW64User** [seladb/PcapPlusPlus#115]
Using MinGW-w64 version: i686-8.1.0-posix-dwarf-rt_v6-rev0.

I followed the install instructions [in here.](http://seladb.github.io/PcapPlusPlus-Doc/download.html#mingw32_mingww64)

I skipped this section as I'm not using mingw32: "Download and installation instructions for MinGW32"

Problems start here: "Run mingw32-make.exe all from PcapPlusPlus main directory". The file called "mingw32-make.exe" doesn't exist in the PcapPlusPlus directory, so I copied it there from mingws bin folder into the PcapPlusPlus  folder. Then I run the command "mingw32-make.exe all" from that folder. I get the following error:
```
process_begin: CreateProcess(NULL, uname, ...) failed.
mingw32-make: Makefile:29: pipe: No error
process_begin: CreateProcess(NULL, rm.exe -rf Dist, ...) failed.
make (e=2): The system cannot find the file specified.
mingw32-make: *** [Makefile:82: libs] Error 2
```

I tried searching for the "Dist" folder that is supposed to be created but can't find it anywhere.

I checked the configuration file (PcapPlusPlus.mk) that was created on a previous step and it looks like [this.](https://pastebin.com/nJfdJRcJ)

All the file paths were configured there.

Screenshot of each of the folders that are configured in the "PcapPlusPlus.mk" file.
[PcapPlusPlus](https://i.imgur.com/yAgod1P.png)
[mingw32](https://i.imgur.com/eo83oOw.png)
[WpdPack](https://i.imgur.com/snP6RbD.png) (WinPCap developer version)
[msys64](https://i.imgur.com/yYDkUyv.png)

**Comment by MinGW64User** [comment]
Did this:

1. Open cmd

2. cd here:
cd C:\Users\m\Downloads\temp\packetCapture\PcapPlusPlus

3. add path:
path C:\Program Files\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin

4. run cmd command:
mingw32-make.exe all

5. Result:
process_begin: CreateProcess(NULL, uname, ...) failed.
mingw32-make.exe: Makefile:29: pipe: No error
process_begin: CreateProcess(NULL, rm.exe -rf Dist, ...) failed.
make (e=2): The system cannot find the file specified.
mingw32-make.exe: *** [Makefile:82: libs] Error 2

[Screenshot](https://i.imgur.com/fZbI4pI.png)

**Comment by seladb** [comment]
It seems it can't find `rm.exe`, could you make sure this file is there? If it's there, in what path?

**Comment by MinGW64User** [comment]
Msys2

the rm.exe is located in C:\Program Files\msys64\usr\bin

**Comment by seladb** [comment]
Could you add this folder to `PATH` and see if it works?

**Comment by MinGW64User** [comment]
Added the folder that has rm.exe to path:

```
process_begin: CreateProcess(NULL, uname, ...) failed.
mingw32-make.exe: Makefile:29: pipe: No error
process_begin: CreateProcess(NULL, rm.exe -rf Dist, ...) failed.
make (e=2): The system cannot find the file specified.
mingw32-make.exe: *** [Makefile:82: libs] Error 2
```

I've also tried to compile the libraries with Visual studio but get several errors. One of them gives the error:
`Unknown command "C:/Program"`
Almost like there are quotes missing around a file-path somewhere (folders that contain spaces need to have quotes around them, otherwise the folder is not found). I'm not sure if it's related to this mingw problem but I mention it since it might have relevance.

**Comment by seladb** [comment]
I guess it's because of the space in "Program Files". Maybe you can move msys2 to another folder and see if it solves the issue

**Comment by MinGW64User** [comment]
1. Removed old path from path variable.
2. Reinstalled to C:\msys64.
3. Then configured the paths again with configure-windows-mingw.bat
PcapPlusPlus.mk  file now has new path:
`MSYS_HOME := C:/msys64`
4. Then ran the command:
`mingw32-make.exe all`

Same error. Also tried adding the the new path of "rm.exe"  (C:\msys64\usr\bin)  to windows environment variables. Same error.

**Comment by MinGW64User** [comment]
Ok. Tried this:

1. Added to windows system path:  `C:\msys64\usr\bin`
2. Added to windows system path:  `C:\Program Files\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin`

Rm.exe  was found this time.
 `>rm.exe
rm: missing operand
Try 'rm --help' for more information.`


3. Created a [new empty folder](https://i.imgur.com/XmfWRRs.png).
4. Open cmd and cd to main folder
`cd C:\Users\m\Downloads\temp\packetCapture\PcapPlusPlus`
5. run mingw32-make.exe
 `>mingw32-make.exe all
==> Building target: Common++
Building file: src/Logger.cpp
g++.exe: error: Files/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/include/ddk: No such file or directory
mingw32-make[1]: *** [Makefile:41: Obj/Logger.o] Error 1
mingw32-make.exe: *** [Makefile:83: libs] Error 2`

Got a different error. Some progress at least!


That folder doesn't exist.  [Screenshot ](https://i.imgur.com/1IrKmep.png)of the folder. Next I'll try to figure out what's ddk.

**Comment by MinGW64User** [comment]
Did 2 changes and got a bit further this time.  There seems to be some error in PcapFilter.cpp file.

1. I moved all installations to C:\code. Makefiles don't work well with file paths that have a space bar in them.
2. Added environment paths for `msys `and `mingw`:
```
    C:\code\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin
    C:\code\msys64\usr\bin
```

It still fails ([image](https://i.imgur.com/7niuDgY.png)) due to a problem in PcapFilter.cpp. Pastebin link for relevant piece of [code in PcapFilter.cpp.](https://pastebin.com/xy1HTnqv). The lines that have a problem are specified in there.

**Comment by seladb** [comment]
I never got this error. Could you please try to install a lower version on mingw-w64 and see if that works?

**Comment by MinGW64User** [comment]
Several errors on the more recent versions. I made a spreadsheet: https://1drv.ms/x/s!AmEZdVzlIQc_aeASTn9EfRmD6yI




Could you add 3 new notes to the [website guide](http://seladb.github.io/PcapPlusPlus-Doc/download.html#mingw32_mingww64)
**1. Mingw64 install directories.**
Adding the main path is not enough (e.g. `C:\code\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64.` There are actually 2 folders that contain the bin, lib & include directories the bat file mentions, which could result in a lot of confusion:
```
C:\code\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64      <-- contains mingw32-make.exe, (gcc.exe etc.)   in the bin subfolder. Let's call this "MakePath"
C:\code\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\x86_64-w64-mingw32       <--contains several required libraries e.g. "include/ddk".  Let's call this "Library path"
```

The "Library path" does NOT contain any executables required for compilation (g++, gcc, mingw32-make). 

The subfolder prefix of the "Library path" depends on the version of mingw64 you installed. 
32bit mingw64 --> `i686-w64-mingw32`
63bit mingw64 --> `x86_64-w64-mingw32`

I added the "Library path" as the path during the configuration of the .bat file
I added the "MakePath" to windows environment variables (path), since the setup will only ask for one path.

**2. x64 support for MinGW or not?**
 It seems that x64 compilations all failed. Is it supported for MinGW? The guide on the Website didn't mention anything about it not supporting x64bit compilation.

**3. None of the folder paths that are referenced can contain a spacebar.**
CMake seems to not work with it. I even added quotes around the folder paths during running the bat file and also edited the .mk files to contains quotes, but it still wouldn't work. Only way to make it work was to put everything in a folder that does not contain a spacebar anywhere in the build path.

**Comment by seladb** [comment]
Thank you for the deep dive and investigation!
I will add the comments you suggested to the building instructions page.

x64 is not supported for MinGW, mainly because WinPcap doesn't support it. I thought I actually wrote that in the building instructions but I can't find it now. I will add it.

**Comment by seladb** [comment]
Done! Please see commit: seladb/PcapPlusPlus-Doc@597df94a1748e62b76cbc69f7226231a299bc729

I'll close this issue for now, please reopen it if anything is missing
