### ISSUE TITLE
IPFilter with direction fails to match DST IPv4 raw packets

### ISSUE THREAD

**Issue by JasMetzger** [seladb/PcapPlusPlus#1153]
A module creates a list of filters to match packets. One IPFilter matches IPv4 on the source address, another matches on the destination address. 

If the rawpacket is compared to the first filter in the list (matching SRC) , it matches appropriately. When it does not match, the routine attempts the match on the second filter in the list (matching DST): though the BPF syntax is correct, and the filter compiles, it fails to match.

**Comment by seladb** [comment]
I'm not sure I fully understand. Can you please share some source code that can reproduce?

Also, it'd be nice if you attach a pcap file that can be used with this code to reproduce the issue

**Comment by JasMetzger** [comment]
Hey

Thanks for responding.

See attached file


  *   The PPFilter class encapsulates pcpp::IPFilter for IPv4 address + direction
  *   Two of these (one for SRC one for DST) are added to list used by PPManager to test against raw packet

When I apply these against a raw packet (considerRawPacket) it’ll match for SRC addresses but not  when packets match DST addresses

James

**Comment by seladb** [comment]
@JasMetzger unfortunately I can't see any attached file...

**Comment by JasMetzger** [comment]
I will try again,

I will need to duplicate the issue in a stand-alone example.
It works in one instance but not the one I represent here.

**Comment by seladb** [comment]
@JasMetzger I still can't see any attached file, maybe it's because you're replying from you email? 🤔

**Comment by JasMetzger** [comment]
I attached it here too. In case it doesn't work, I have pasted here:


class PPFilter
{
public:
      PPFilter()
      {
            initialize();
      }

      PPFilter(std::shared_ptr<const glycine::data::mediation::provisionkey::Info>& pkeyinfo,
                  std::shared_ptr<const glycine::data::mediation::stream::Info>& streaminfo)
      {
            initialize();

            if (pkeyinfo->getDirection() == glycine::data::mediation::pdu::Direction::DESTINATION)
                  pcppdir = pcpp::Direction::DST;
            else if (pkeyinfo->getDirection() == glycine::data::mediation::pdu::Direction::SOURCE)
                  pcppdir = pcpp::Direction::SRC;
            else
                  pcppdir = pcpp::Direction::SRC_OR_DST;

            glycine::data::mediation::stream::Criterion* criterion = streaminfo->getStaticCriterion();

            if (criterion)
            {
                  streamtype_ = criterion->getType();

                  switch (criterion->getType())
                  {
                  case glycine::data::mediation::stream::CriterionType::IPV4ADDRESS:
                        {
                              pcppfilter = new pcpp::IPFilter(criterion->getIdentifier(), pcppdir);
                              address_.fromStringIP(criterion->getIdentifier());
                        }
                        break;

                  default:
                        break;
                  }
            }
      }

      ~PPFilter()
      {
            if (pcppfilter)
            {
                  delete pcppfilter;
                  pcppfilter = nullptr;
            }
      }

      void initialize()
      {
            pcppfilter = nullptr;
            pcppdir = pcpp::Direction::SRC_OR_DST;
      }


      bool matches(pcpp::RawPacket* rawPacket)
      {
            bool doesmatch = false;

            if (pcppfilter)
            {
                  doesmatch = pcppfilter->matchPacketWithFilter(rawPacket);
            }
            return(doesmatch);
      }
}


// ************* //

void
PPManager::considerRawPacket(pcpp::RawPacket* rawPacket)
{
      if (rawPacket->getRawDataLen() > 0)
      {

            auto ppiter = ppfilters_.begin();
            while (ppiter != ppfilters_.end())
            {
                  auto pkeyoid = ppiter->first;
                  PPFilter* ppi = ppiter->second;

                  if (ppi && ppi->isActive())
                  {
                        iapstatus_.counted(pkeyoid);

                        if (ppi->matches(rawPacket))
                        {

                              // does not match when IPv4 is destination
                        }
                  }
            }
      }
}

**Comment by seladb** [comment]
Thanks @JasMetzger ! I'll take a look soon and let you know

**Comment by JasMetzger** [comment]
Thanks. I must say that in another part of code I am able to detect both SRC and DST occurrences. I am not sure why the circumstance is different in this code fragment not working.

**Comment by seladb** [comment]
I'm sorry @JasMetzger but I still can't see the pcap file that contains the raw packet. Without the pcap file there's very little I can do to help...
