### ISSUE TITLE
PcapSplitter is dropping packets

### ISSUE THREAD

**Issue by shubhamjain0594** [seladb/PcapPlusPlus#1161]
I am splitting a dataset of PCAPs using `-m connection` and the number of packets in the split files, are almost half of the packets in the original file.

I am not sure why this would be happening.

**Comment by seladb** [comment]
Maybe the dropped packets are not part of a connection?

**Comment by shubhamjain0594** [comment]
I looked at all the files created by PcapSplitter, aggregated the number of packets to come to the conclusion. On digging deeper this is the error it is giving:

```
[ERROR: src/PcapFileDevice.cpp: open:717             ] Pcap file has a different link layer type than the one chosen in PcapFileWriterDevice c'tor, 101, 12
```

**Comment by shubhamjain0594** [comment]
Tshark analysis of the PCAP gives following output. So I dont think the file in itself has multiple link layers.
<img width="780" alt="Screenshot 2023-07-21 at 10 22 36" src="https://github.com/seladb/PcapPlusPlus/assets/5080900/4194aa14-4df9-4b91-947d-8fbf87c8c253">

**Comment by egecetin** [comment]
Is this a concatenated pcap file? I mean, captured from different devices/interfaces etc. then merged into single file. It might cause the different type of link layers

**Comment by shubhamjain0594** [comment]
I found a work around by converting `pcap` file to `pcapng` and it works.

**Comment by seladb** [comment]
There is something wrong with the pcap file, that's probably why tshark gives the error message of "the file ... appears to have been cut short in the middle of the packet".

The pcap format supports only one link layer type. Multiple link layer types are only supported in pcapng. Maybe it's actually a pcapng file with `.pcap` extension? 🤔 In that case renaming the file to `.pcapng` will solve the problem

**Comment by seladb** [comment]
@shubhamjain0594 I'll close this issue now, please reopen it if needed
