### ISSUE TITLE
Add soversion to shared libraries

### ISSUE THREAD

**Issue by topazus** [seladb/PcapPlusPlus#1164]

**Comment by seladb** [comment]
@topazus I'm not sure how to do that... @clementperon maybe you know?

**Comment by clementperon** [comment]
@topazus are you talking about previous releases or the new cmake build system? 

It should now be properly versioned.

**Comment by seladb** [comment]
Thanks @clementperon !

@topazus just to provide more context: the latest release (v22.11) was built with the previous build system, but since then we switched to CMake. We don't yet have an official release with CMake

**Comment by seladb** [comment]
@topazus should we close this issue now?
