### ISSUE TITLE
Fix NFLOG error: Operation not permitted

### ISSUE THREAD

**Issue by MrPeck** [seladb/PcapPlusPlus#1166]
When opening a NFLOG device we receive the following error:

`[ERROR: /<MY-PATH>/PcapPlusPlus/Pcap++/src/PcapLiveDevice.cpp: doOpen:267] Can't listen on group group index: Operation not permitted`

This error is cause because in function `bool PcapLiveDevice::open(const DeviceConfiguration& config)`, the device is opened twice. one descriptor is used to capture packets while the second one is to send packets, as described in the source code:

PcapLiveDevice.h
```
// This is a second descriptor for the same device. It is needed because of a bug
// that occurs in libpcap on Linux (on Windows using WinPcap/Npcap it works well):
// It's impossible to capture packets sent by the same descriptor
pcap_t* m_PcapSendDescriptor;
````

PcapLiveDevice.cpp
```
bool PcapLiveDevice::open(const DeviceConfiguration& config)
{
    [...]

    m_PcapDescriptor = doOpen(config);
    m_PcapSendDescriptor = doOpen(config);

    if (m_PcapDescriptor == nullptr || m_PcapSendDescriptor == nullptr)
    {
        m_DeviceOpened = false;
        return false;
    }
    
    [...]
}
```

This cannot be done for NFLOG as a NFLOG device (with a given NFLOG Group) cannot have more than one open instance at a time.

Issue is reproducible by simply opening an nflog device:

```
dev = pcpp::PcapLiveDeviceList::getInstance().getPcapLiveDeviceByName("nflog");
if (dev == nullptr)
{
	std::cerr << "Cannot find nflog interface" << std::endl;
	return 1;
}

if (!dev->open())
{
	std::cerr << "Cannot open device" << std::endl;
	return 1;
}
```

**General Info**
I'm running this in a Linux arm64 emulation, but the issue also happens in ubuntu machines. Let me know if there is any other data required. I will soon be making a pull request with a suggestion for a fix.

**Comment by seladb** [comment]
Thank you @MrPeck for fixing this issue, much appreciated! 🙏
