### ISSUE TITLE
Add support for choosing NFLOG groups when opening to NFLOG device

### ISSUE THREAD

**Issue by MrPeck** [seladb/PcapPlusPlus#1167]
NFLOG packets are sent to the device "nflog" in a specified NFLOG Group. When not specified which group, 0 is the default.
There is no support for choosing which group to listen to on the device.

**Example**
`tcpdump -i nflog:123`

When running this command, you will listen to nflog on NFLOG Group 123.

I'll later make a pull request with a suggestion for the feature :)

**Comment by seladb** [comment]
Thank you @MrPeck for fixing this issue, much appreciated!  🙏
