### ISSUE TITLE
HTTP Request, Response Parsing

### ISSUE THREAD

**Issue by quantumcore** [seladb/PcapPlusPlus#1168]
Does this library allows parsing of HTTP Requests? I read somewhere that it can only parse HTTP Headers and not get HTTP Body. If this is possible can you provide an example using the HTTPRequest and response layer. 

Thanks.

**Comment by egecetin** [comment]
There is `HttpRequestLayer` (check [this](https://github.com/seladb/PcapPlusPlus/blob/5cdf3b7a0617eca37d69e6ee2a2d71c4513b5983/Packet%2B%2B/header/HttpLayer.h#L124)) and `HttpResponseLayer` (check [this](https://github.com/seladb/PcapPlusPlus/blob/5cdf3b7a0617eca37d69e6ee2a2d71c4513b5983/Packet%2B%2B/header/HttpLayer.h#L231C8-L231C26)) in library.

I don't have any example code for now but maybe you can check implementations in the library examples and tests,
https://github.com/seladb/PcapPlusPlus/blob/5cdf3b7a0617eca37d69e6ee2a2d71c4513b5983/Examples/HttpAnalyzer/HttpStatsCollector.h#L161-L174

Simply if this is an HTTP packet you can use `getLayerOfType()` function to get a pointer to request or response layer. If the pointer is not `nullptr`, you can use methods of these layers to access properties. Also you can use the `getFieldByName()` function to get all of the HTTP fields,

https://github.com/seladb/PcapPlusPlus/blob/5cdf3b7a0617eca37d69e6ee2a2d71c4513b5983/Tests/Pcap%2B%2BTest/Tests/PacketParsingTests.cpp#L175-L204

**Comment by quantumcore** [comment]
In the second example you provided, It is getting content type field. I am able to get all headers, except for body. And using ``getFieldByName()`` you say, We can only get : 
```cpp
	/** Host field */
#define PCPP_HTTP_HOST_FIELD 				"Host"
	/** Connection field */
#define PCPP_HTTP_CONNECTION_FIELD 			"Connection"
	/** User-Agent field */
#define PCPP_HTTP_USER_AGENT_FIELD			"User-Agent"
	/** Referer field */
#define PCPP_HTTP_REFERER_FIELD				"Referer"
	/** Accept field */
#define PCPP_HTTP_ACCEPT_FIELD 				"Accept"
	/** Accept-Encoding field */
#define PCPP_HTTP_ACCEPT_ENCODING_FIELD		"Accept-Encoding"
	/** Accept-Language field */
#define PCPP_HTTP_ACCEPT_LANGUAGE_FIELD		"Accept-Language"
	/** Cookie field */
#define PCPP_HTTP_COOKIE_FIELD 				"Cookie"
	/** Content-Length field */
#define PCPP_HTTP_CONTENT_LENGTH_FIELD		"Content-Length"
	/** Content-Encoding field */
#define PCPP_HTTP_CONTENT_ENCODING_FIELD 	"Content-Encoding"
	/** Content-Type field */
#define PCPP_HTTP_CONTENT_TYPE_FIELD		"Content-Type"
	/** Transfer-Encoding field */
#define PCPP_HTTP_TRANSFER_ENCODING_FIELD	"Transfer-Encoding"
	/** Server field */
#define PCPP_HTTP_SERVER_FIELD				"Server"
```

So I can get all the headers using getFieldByName, but how to get body? 
Much appreciated!

**Comment by egecetin** [comment]
To be honest not fully tested since I don't have much time sorry, but something like should work,

```
pcpp::HttpResponseLayer *res = httpPacket->getLayerOfType<pcpp::HttpResponseLayer>();
uint8_t *bodyPtr = res->getLayerPayload();

// Just for printing to make sure it is body of packet
std::string bodyString((char *)bodyPtr);
std::cout << "-----------------------------" << std::endl;
std::cout << bodyString << std::endl;
```

and the output for a packet,

```
-----------------------------
<HTML><HEAD><TITLE>Yahoo!</TITLE>
</HEAD><BODY BGCOLOR=white vlink=blue><center>
<table width=675 cellpadding=0 cellspacing=2 border=0>
        <tr>
        <td width=1% valign=top><a href="http://www.yahoo.com"><img src=http://l.yimg.com/a/i/yahoo.gif width=147 height=31 border=0 alt="Yahoo"></a></td>
        <td align=right><font face=arial size=-1><a href="/404/*http://www.yahoo.com">Yahoo!</a> - <a href="http://help.yahoo.com">Help</a></font><hr size=1 noshade></td>
        </tr>
</table>
<br>
<table border=0 width=675 cellspacing=0 cellpadding=3>
<tr>
<td bgcolor=003399 colspan=2>
<font face=Arial size=+1 color=white><b>Sorry, the page you requested was not found.</b></font>
</td>
</tr></table>
<br>
<table border=0 width=675 cellspacing=0 cellpadding=1>
<tr>
<td valign=top width=229 bgcolor=ffffff>

<table width="100%" cellpadding=1 cellspacing=0 border=0 bgcolor=dcdcdc><
-----------------------------
```

**Comment by quantumcore** [comment]
Works! Thanks alot!
```cpp
        pcpp::HttpResponseLayer *res = m_packet.getLayerOfType<pcpp::HttpResponseLayer>();
        uint8_t *bodyPtr = res->getLayerPayload();
        size_t bodySize = res->getLayerPayloadSize();

        // Create a std::string from the payload data and its size
        std::string bodyString(reinterpret_cast<char*>(bodyPtr), bodySize);

        std::cout << "Response Body\n-----------------------------" << std::endl;
        std::cout << bodyString << std::endl;
```
