### ISSUE TITLE
Common++/src/SystemUtils.cpp:124   "Out-of-bounds access of arrays"

### ISSUE THREAD

**Issue by shidaoxuan** [seladb/PcapPlusPlus#117]
if "int getNumOfCores()"  returns an integer greater than 32.
then "result = result | SystemCores::IdToSystemCore[i].Mask;" will lead to out-of-bounds array access.

In fact my server(DELL PowerEdge R930) has 72 logic cores.

**Comment by shidaoxuan** [comment]
i'think you can limit the numOfCores like:
" int numOfCores = getNumOfCore() < 32 ? getNumOfCores() : 32; "

**Comment by seladb** [comment]
That's a great point! I never thought someone with more that 32 cores will run PcapPlusPlus :)
Do you mind doing this small change and create a PR?

**Comment by seladb** [comment]
Thanks for the PR! I'm closing the issues now
