### ISSUE TITLE
How to uninstall software built from source?

### ISSUE THREAD

**Issue by NanXiao** [seladb/PcapPlusPlus#1171]
Hello,

I built master code using `cmake` and installed it, but it seems there is no `uninstall` command. Just curious how to uninstall? Thanks very much in advance!

Best Regards
Nan Xiao

**Comment by seladb** [comment]
@clementperon can you advise?

**Comment by clementperon** [comment]
@NanXiao there is no such feature at the moment.

If you would like to submit a PR you can follow this:
https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake

**Comment by NanXiao** [comment]
@seladb @clementperon Got it, thanks very much for your replies!

**Comment by seladb** [comment]
Thank you @tbhaxor for adding this capability, I really appreciate it! 🙏 ❤️ 
Your PR was merged to the `master` branch.
