### ISSUE TITLE
[Question] I want to implement more L2 packet formats

### ISSUE THREAD

**Issue by tbhaxor** [seladb/PcapPlusPlus#1184]
I want to implement WiFi packet format for both adding feature and learning internals of this libraries

- RadioTap Header
- Beacon Frame and other management frames
- Data Header (when encrypted)
- HTTP, Arp, DNS ... already implemented in upper layers

I would like to know the best approach for it and how can I start working

**Comment by seladb** [comment]
That would be great @tbhaxor , thank you for offering to help!

Implementing new protocols can be very easy or a bit more complex, depending on the protocol of course 😄 

Maybe you can start by looking at PRs of new protocols that were added recently, that would help you to get a rough understanding of the changes needed:
- SLL2 (Linux cooked capture v2): https://github.com/seladb/PcapPlusPlus/pull/1138
- COTP: https://github.com/seladb/PcapPlusPlus/pull/1146
- VRRP: https://github.com/seladb/PcapPlusPlus/pull/1118

I'm not very familiar with RadioTap and Beacon frames, can you send me an example pcap and the RFC with the packet structure?

**Comment by tbhaxor** [comment]
Please keep this issue open, we can coordinate here for more details

**Comment by seladb** [comment]
@tbhaxor are you still planning to add these protocols or can we close this issue?

**Comment by tbhaxor** [comment]
Yes @seladb. I was engaged in some other work. I am planning to continue it now.

**Comment by seladb** [comment]
Sure @tbhaxor we can keep it open for now

**Comment by tbhaxor** [comment]
@seladb I am closing it for now, as my question "How" is answered https://github.com/seladb/PcapPlusPlus/issues/1184#issuecomment-1682863094 here. If I will have any doubt, I will ask you here.
