### ISSUE TITLE
implement HttpResponseStatusCode getMessage() function

### ISSUE THREAD

**Issue by tigercosmos** [seladb/PcapPlusPlus#1187]
per https://github.com/seladb/PcapPlusPlus/pull/1180#discussion_r1296572283

```cpp
HttpResponseStatusCode statusCode1(HttpResponseStatusCode::Http200OK);
HttpResponseStatusCode statusCode2(HttpResponseStatusCode::Http200OK, "Custom message");

std::cout << statusCode1.getMessage();
// prints "OK"
std::cout << statusCode2.getMessage();
// prints "Custom message"
```

**Comment by seladb** [comment]
@tigercosmos would you consider working on this enhancement?

**Comment by tigercosmos** [comment]
@seladb Yes, I would like to help this, actually I am already working on it, but not at a fast speed.

**Comment by seladb** [comment]
> @seladb Yes, I would like to help this, actually I am already working on it, but not at a fast speed.

That's great, thank you! Please take your time and let me know if you need my help

**Comment by seladb** [comment]
This was added in https://github.com/seladb/PcapPlusPlus/pull/1190 that is merged to `master`

Thank you so much @tigercosmos for working on it! 🙏
