### ISSUE TITLE
[VCPKG] replace winpcap with npcap

### ISSUE THREAD

**Issue by maordadush** [seladb/PcapPlusPlus#1188]
Hi, 
do you have any plan to replace winpcap dependency with npcap in vcpkg.json (https://github.com/microsoft/vcpkg/blob/927bc12e31148b0d44ae9d174b96c20e3bcf08eb/ports/pcapplusplus/vcpkg.json#L26C16-L26C23)?

In the meantime, I use the old port version (https://github.com/microsoft/vcpkg/issues/33249), so I can use your library but I still get the following errors in the build process:

> Packet.lib(Packet32.obj) : error LNK2005: DllMain already defined in wpcap.lib(pcap-win32.obj)
> Packet.lib(Packet32.obj) : error LNK2005: LoadLibrarySafe already defined in wpcap.lib(pcap-tc.obj)
>  fatal error LNK1169: one or more multiply defined symbols found

Thanks!

**Comment by seladb** [comment]
Unfortunately I don't think Vcpkg has an Npcap port, there is only a WinPcap port.

I did some research and found these closed issues:
https://github.com/microsoft/vcpkg/issues/10873
https://github.com/microsoft/vcpkg/issues/19890

The second one is misleading because `nmap` also uses WinPcap instead of Npcap!
https://github.com/microsoft/vcpkg/blob/e21c414460498b0c7c94d815ad6d1a3d313ff28b/ports/nmap/vcpkg.json#L25

**Comment by maordadush** [comment]
thanks, Maybe can you fix the packet.lib linking, please?

https://github.com/microsoft/vcpkg/pull/11954

**Comment by seladb** [comment]
This issue is related to `libtins`,  not PcapPlusPlus... 🤔

**Comment by maordadush** [comment]
I added it for reference because when I use PcapPlusPlus I get the same errors


> Hi, do you have any plan to replace winpcap dependency with npcap in vcpkg.json (https://github.com/microsoft/vcpkg/blob/927bc12e31148b0d44ae9d174b96c20e3bcf08eb/ports/pcapplusplus/vcpkg.json#L26C16-L26C23)?
> 
> In the meantime, I use the old port version ([microsoft/vcpkg#33249](https://github.com/microsoft/vcpkg/issues/33249)), so I can use your library but I still get the following errors in the build process:
> 
> > Packet.lib(Packet32.obj) : error LNK2005: DllMain already defined in wpcap.lib(pcap-win32.obj)
> > Packet.lib(Packet32.obj) : error LNK2005: LoadLibrarySafe already defined in wpcap.lib(pcap-tc.obj)
> > fatal error LNK1169: one or more multiply defined symbols found
> 
> Thanks!

**Comment by seladb** [comment]
I'm not sure I have time to work on it now, but if you know how to solve it please feel free to open a PR in the Vcpkg repo, I can help to review it

**Comment by seladb** [comment]
@maordadush please see [this PR](https://github.com/microsoft/vcpkg/pull/33215) and specifically [this comment](https://github.com/microsoft/vcpkg/pull/33215#issuecomment-1727606051) in the Vcpkg repo. I'm not sure they want to add Npcap, and they certainly don't want to remove WinPcap. 

We know that currently WinPcap port is broken (see [this issue](https://github.com/microsoft/vcpkg/issues/33249)), hopefully it'll be fixed soon, and then we'll update the PcapPlusPlus port to v23.09.

I'll close this issue now as it's already discuss in Vcpkg

**Comment by maordadush** [comment]
@seladb I have an existing project that uses vcpkg with **x64-windows-static** triplet and in the meantime I am wondering if there is any way I can compile my code with pcapplusplus binaries.

Thanks!

**Comment by seladb** [comment]
@maordadush I think you should be able to build your code using PcapPlusPlus binaries, do you see any issue?

**Comment by seladb** [comment]
@clementperon can you please advise?

**Comment by clementperon** [comment]
Are you still using pcapplusplus 22.11? Could you give it a try With 23.09?

**Comment by maordadush** [comment]
@clementperon maybe it's related to this error?

`vcpkg.exe install pcapplusplus:x64-windows-static`

> Computing installation plan...
> winpcap is only supported on 'windows & !uwp & !arm & !static', which does not match x64-windows-static. This usually means that there are known build failures, or runtime problems, when building other platforms. To ignore this and attempt to build winpcap anyway, rerun vcpkg with `--allow-unsupported`.

**Comment by ruijiexie** [comment]
1
