### ISSUE TITLE
"dpdk segmentation fault"  MBufRawPacket::~MBufRawPacket()

### ISSUE THREAD

**Issue by shidaoxuan** [seladb/PcapPlusPlus#119]
My dpdk demo calls startCaptureMultiThreads() to capture packets without sending out.
this demo is similar to “PCAPP_TEST(TestDpdkMultiThread)”,  after few senconds, the demo crash because MBufRawPacket::~MBufRawPacket() called "rte_pktmbuf_free(m_MBuf);". i found m_Mbuf is an abnormal data. m_Mbuf.pool is 0. so rte_pktmbuf_free() cause segmentation fault.

I am confused about this, I do not know why this data has become abnormal.

**Comment by shidaoxuan** [comment]
I found the reason.  In class DpdkDevice , a member named "struct rte_mbuf* m_mBufArray[256];", DpdkDevice.m_mBufArray will be shared by all capture threads, it's unsafe, this data member will be overwrite by multithreading.
My suggestion is as follows:
DpdkDevice.h:1018 ----> struct rte_mbuf* m_mBufArray[MAX_NUM_OF_CORES][256];

DpdkDevice.cpp:922 ----> uint32_t numOfPktsReceived = rte_eth_rx_burst(pThis->m_Id, queueId, pThis->m_mBufArray[coreId], MAX_BURST_SIZE);

DpdkDevice.cpp:935 ----> struct rte_mbuf* mBuf = pThis->m_mBufArray[coreId][index];

**Comment by echo-Mike** [comment]
Hi, @shidaoxuan.
You have found a general flaw in callback based system in DpdkDevice class. The proposed solution is not bad but it implies false sharing if cache line alignment is not meet.
I do not see any easy way to fix this issue except to **not to use callback based system** by now.

**Comment by echo-Mike** [comment]
@shidaoxuan, @seladb I possibly have found a solution, will make PR today near **22:00 CET**

**Comment by seladb** [comment]
Thanks @shidaoxuan , this is indeed a bug and I'm not sure how I didn't find it until now so thanks for reporting it!

Your suggested solution seems reasonable. @echo-Mike - is this what you had in mind?

**Comment by echo-Mike** [comment]
@seladb please see my commit above.
## Proposed solution
The **m_mBufArray** field is an opaque member field of ```DpdkDevice``` that is not used anywhere besides places mentioned above. There is no reason to store it inside ```DpdkDevice``` object and as we saw there is a reason to made this array **thread local** value that is located on thread stack.
Library gives no guarantee to users about accessibility or lifetime of **m_mBufArray** member and about ```DpdkDevice``` class ABI so nobody's code must be broken.
### Another fixes
1. The implementation of ```rawPakets``` array variable is **not C++ compatiple**!!! This syntax with variable length arrays is a C syntax. But ther is not real reason to do so as no guarantee  is geven to users of PCPP lib about lifetime of  objects in this array. I strongly suggest to change ```m_OnPacketsArriveCallback``` signature to (a.e. ```OnDpdkPacketsArriveCallback``` type) from:
```C++
typedef void (*OnDpdkPacketsArriveCallback)(MBufRawPacket* packets, uint32_t numOfPackets, uint8_t threadId, DpdkDevice* device, void* userCookie);
```
to:
```C++
typedef void (*OnDpdkPacketsArriveCallback)(const MBufRawPacket* packets, uint32_t numOfPackets, uint8_t threadId, DpdkDevice* device, void* userCookie);
```
2.  The used size of ```mBufArray``` and ```rawPackets``` never exceed ```MAX_BURST_SIZE```.

**Comment by echo-Mike** [comment]
Currently my *fix* misses one essential feature:
On https://github.com/seladb/PcapPlusPlus/blob/24dd4afa91f3234a9ba07ecb7b7d3b50d4e9bb1b/Pcap%2B%2B/src/DpdkDevice.cpp#L940
the destructors of ```MBufRawPacket``` objects created on https://github.com/seladb/PcapPlusPlus/blob/24dd4afa91f3234a9ba07ecb7b7d3b50d4e9bb1b/Pcap%2B%2B/src/DpdkDevice.cpp#L932 are called, so packets are released from DPDK memory, but in my code this must be implemented by hand.  
I may implement it in PR branch if @seladb is happy with proposed solution.

**Comment by echo-Mike** [comment]
@seladb as i mentioned in my comment above the solution proposed by @shidaoxuan is not optimal because if the cacheline alignment of ```m_mBufArray[][256]``` is not meet that will significantly slow down execution.

**Comment by seladb** [comment]
@echo-Mike I agree with you approach. Your solution should work just fine if you keep `MBufRawPacket rawPackets[MAX_BURST_SIZE]` in its original place. Could you do that fix and create a PR?
