### ISSUE TITLE
Streaming pcap reader

### ISSUE THREAD

**Issue by NewbiZ** [seladb/PcapPlusPlus#1204]
I have a use case where I would like to be able to start reading a pcap while the file is being downloaded. As far as I understand, PcapPlusPlus is only able to read from a path, and not from e. g. an `ifstream`.

Am I missing something? I had a look at the different classes around the pcap reader, and they seem to rely on `libpcap`'s `open_offline*()`, which themselves accept just a path.

Is that possible at all?

**Comment by seladb** [comment]
You're right. Currently, PcapPlusPlus doesn't support opening files from a stream. However libpcap does support it via the [`pcap_fopen_offline()`](https://linux.die.net/man/3/pcap_fopen_offline) API. Please note that it accepts C-style `FILE*` and not C++ objects like `ifstream`.

This is something we can add to PcapPlusPlus. The only challenge I currently see is that we keep a private member `m_FileName` for each file device, and in this case there won't be a name so we need to find a way around it...

**Comment by egecetin** [comment]
As a workaround, if you want a quick solution, you can create a virtual loopback interface and write a tiny program with a raw socket for sending downloaded packets to this interface. Since you will use raw socket nothing will be modified from the downloaded packets (MAC adresses, checksums etc). So your main program can read the "streaming" packets from this virtual interface with PcapPlusPlus like normal interface. Since no one (system applications etc) will use this interface you will most probably capture your packets only. But still you somehow need to read and distinguish every packet from partial downloaded pcap and wait if a packet is half downloaded etc via an API (of libpcap functions for example @seladb mentioned) or manually.

**Comment by NewbiZ** [comment]
It's going to be a pain. It's a lot of setup for the virtual loop back interface and raw sockets usage will require a capability.

I was thinking of a workaround with named pipes. I could feed the pipe with the `ifstream` and give that to the pcap reader. I could even re-pipe `xz` in between two pipes so that pcapplusplus reads  a streaming, decompressed `.pcap.gz` during download.

**Comment by seladb** [comment]
I think that if we change `PcapFileReaderDevice` to accept `FILE*` it'd be better to do the full implementation and use [`pcap_fopen_offline()`](https://linux.die.net/man/3/pcap_fopen_offline).

@NewbiZ would you consider working on this?

**Comment by NewbiZ** [comment]
@seladb Can't promise anything but I will give it a try.

**Comment by NewbiZ** [comment]
Apologies, I ended up using a different solution.

In my use case, I wanted to stream the contents of files stored on AWS S3. In practice though, the AWS C++ SDK ended up being unusable.

- It does not support parallel download of single files;
- It's not available on most linux distribution package managers;
- It's not available as a pre-built package, you have to build it from source;
- The build system is buggy and requires the user to manually tweak the pkg-config files after installation;
- Overall it adds a 5m link time since they expose millions of useless symbols;
- My PRs fall in a black hole of committees and roadmaps at AWS and I have not much expectation of getting them merged in the decade to come;

For these reasons I figured using the AWS C++ SDK was not doing a favor to my users, and requiring the presence of `awscli` and spawning a subshell to download the files was just a better experience (sad).

So, as far as PcapPlusPlus is concerned, I moved to using a simple `AsynchronousFile` wrapper that creates a named pipe on the filesystem, and either `cat` a local file or `aws s3 cp` to it. It will also conditionally insert a `| gunzip` in the middle if the file ends with 'pcap.gz'. I then have PcapPlusPlus read from that named pipe and that's it.

**Comment by seladb** [comment]
Thanks for the info @NewbiZ ! Should we keep this issue open or should we close it?

**Comment by NewbiZ** [comment]
As far as I'm concerned, the named pipe solution works as expected with PcapPlusPlus and is reasonably easy to implement.

I will go ahead and close this issue, thanks a lot!
