### ISSUE TITLE
Does PCapPlusPlus support IEEE 1722 data parsing

### ISSUE THREAD

**Issue by mominggame** [seladb/PcapPlusPlus#1206]
Does PCapPlusPlus support IEEE 1722 data parsing? I noticed that Wireshark supports IEEE 1722 parsing. Does PCapPlusPlus use Wireshark as its underlying library?

**Comment by seladb** [comment]
> Does PCapPlusPlus support IEEE 1722 data parsing? 

No, unfortunately, PcapPlusPlus doesn't support IEEE 1722 currently
 
> I noticed that Wireshark supports IEEE 1722 parsing. Does PCapPlusPlus use Wireshark as its underlying library?

PcapPlusPlus doesn't use Wireshark as its underlying library, instead it uses libpcap/WinPcap/Npcap for capturing packets and contains its own parsers to parse the raw data. You can read more in PcapPlusPlus documentation:
https://pcapplusplus.github.io/
https://pcapplusplus.github.io/docs/features#supported-network-protocols

**Comment by mominggame** [comment]
Thank you
