### ISSUE TITLE
Memory leak and “mbuf” duplicate release.

### ISSUE THREAD

**Issue by shidaoxuan** [seladb/PcapPlusPlus#121]
**Q1: Memory leak**
DpdkDevice.cpp: L1112        MBufRawPacket* newRawPacket = new MBufRawPacket();
I can't find where to delete “newRawPacket”.
e.g. in "Tests/Pcap++Test/main.cpp:L379~L395"
```
while (!m_Stop)
{
	pthread_mutex_lock(m_QueueLock);
	uint16_t packetReceived = m_DpdkDevice->receivePackets(mBufArr, 32, m_QueueId);
	pthread_mutex_unlock(m_QueueLock);
	m_PacketCount += packetReceived;
	pthread_mutex_lock(m_QueueLock);
	uint16_t packetsSent = m_DpdkDevice->sendPackets(mBufArr, packetReceived, m_QueueId);
	PCAPP_ASSERT(packetsSent == packetReceived, "Couldn't send all received packets on thread %d", m_CoreId);
	pthread_mutex_unlock(m_QueueLock);
}

for (int i = 0; i < 32; i++)
{
	if (mBufArr[i] != NULL)
		delete mBufArr[i];
}
```
Only the last 32 mBufArr[i] are released.

**Q2: duplicate release**
DpdkDevice.cpp:L1278
```
uint16_t DpdkDevice::sendPackets(MBufRawPacket** rawPacketsArr, uint16_t arrLength, uint16_t txQueueId, bool useTxBuffer)
{
	uint16_t packetsSent = sendPacketsInner(txQueueId, (void*)rawPacketsArr, getNextPacketFromMBufRawPacketArray, arrLength, useTxBuffer);

	bool needToFreeMbuf = (!useTxBuffer && (packetsSent != arrLength));

	for (int index = 0; index < arrLength; index++)
		rawPacketsArr[index]->setFreeMbuf(needToFreeMbuf);

	return packetsSent;
}
```

this line "bool needToFreeMbuf = (!useTxBuffer && (packetsSent != arrLength));" is used to determine if it needs to be released.
but if "packetsSent != arrLength" is true, this means that only some of the mbufs were sent. so "for (int index = 0; index < arrLength; index++)" is not correct, only those mbufs that have not sent successfully need to be released in the destructor.

**Comment by seladb** [comment]
**Regarding Q1:** this is not a bug. The `receivePackets()` method returns an array of `MBufRawPacket` which should be free by the user, please refer to the [documentation for this method](http://seladb.github.io/PcapPlusPlus-Doc/Documentation/a00775.html#a407145da015517eca651735bb7b318a9): 

> Notice it's the user responsibility to free the array and its content when done using it

**Regarding Q2:** Please refer to the [documentation for this method](http://seladb.github.io/PcapPlusPlus-Doc/Documentation/a00775.html#ab991ad2aba22f2c292386c48af1fad13):

> The mbufs used in this method aren't freed by this method, they will be transparently freed by DPDK 

I didn't want to make an exception if not all packets are sent by DPDK, that's why I decided to free all of them

**Comment by shidaoxuan** [comment]
@seladb 
Q1: I agree with your point of view, MBufRawPacket which allocated in libPcap++ and should be free by the user.
But in "Tests/Pcap++Test/main.cpp:L379~L395",  mBufArr inside while (!m_Stop) clause: was not release. is this correct？

**Comment by shidaoxuan** [comment]
Q2:
The mbufs  will be transparently freed by DPDK when the packets actually sent by "rte_eth_tx_burst()".
Applications that implement a "send as many packets to transmit as possible" policy can check this specific case and keep invoking the rte_eth_tx_burst() function until a value less than nb_pkts is returned.
so you can find some code segment like this in dpdk example:
dpdk:   examples/ip_fragmentation/main.c
```
        ret = rte_eth_tx_burst(port, queueid, m_table, n);
        if (unlikely(ret < n)) {
                do {
                        rte_pktmbuf_free(m_table[ret]);
                } while (++ret < n);
        }
```
you must manually release the mbuf that failed to send.

**Comment by shidaoxuan** [comment]
@seladb 
My understanding is wrong. Repeated release is allowed, even if a successfully sent mbuf can be released again.
One is a transparent release(rte_eth_tx_burst) and the other is a manual release(rte_pktmbuf_free).

**Comment by seladb** [comment]
Regarding Q1: I agree that the unit-test code is wrong. I'll fix that when I have the time, but I don't think it's urgent. Please let me know me if you agree  

Regarding Q2: this code can indeed be changed to release just the mbufs that weren't sent, but as you mention double release is also allowed. What do you think?

**Comment by shidaoxuan** [comment]
Regarding Q2: In my test, repeated release will generate some extra consumption, which becomes more obvious in large traffic scenarios.

**Comment by seladb** [comment]
Sure. Do you have the time and capacity to do this fix and create a PR?

**Comment by seladb** [comment]
I was wrong in my answer on Q1: the unit-test code is actually fine: this `while` loop receives packets into an array and immediately sends them. The send method should take care of freeing all the mbufs, so there is nothing else to free and there should be no memory leak. Please let me know if you have other observation

In the meantime I'll fix only the issue you raised in Q2

**Comment by shidaoxuan** [comment]
DpdkDevice.cpp: L1110
```
for (size_t index = 0; index < packetsReceived; ++index)
{
	struct rte_mbuf* mBuf = mBufArray[index];
	if (rawPacketsArr[index] == NULL)
		rawPacketsArr[index] = new MBufRawPacket();

	rawPacketsArr[index]->setMBuf(mBuf, time);
}
```
Each time this API(uint16_t DpdkDevice::receivePackets(MBufRawPacket** rawPacketsArr, ...) is called, multiple MBufRawPacket class objects are allocated. But where do you release the class object allocated here?

 My changes are as follows in "Tests/Pcap++Test/main.cpp:L379~L395".
```
while (!m_Stop)
{
	pthread_mutex_lock(m_QueueLock);
	uint16_t packetReceived = m_DpdkDevice->receivePackets(mBufArr, 32, m_QueueId);
	pthread_mutex_unlock(m_QueueLock);
	m_PacketCount += packetReceived;
	pthread_mutex_lock(m_QueueLock);
	uint16_t packetsSent = m_DpdkDevice->sendPackets(mBufArr, packetReceived, m_QueueId);
	PCAPP_ASSERT(packetsSent == packetReceived, "Couldn't send all received packets on thread %d", m_CoreId);
	pthread_mutex_unlock(m_QueueLock);
	for (int i = 0; i < 32; i++)
	{
		if (mBufArr[i] != NULL) {
			delete mBufArr[i];
			mBufArr[i] = NULL；
		}
	}
}

PCAPP_DEBUG_PRINT("Worker thread on %d stopped", m_CoreId);
```

**Comment by seladb** [comment]
There is no need to free the elements (of type MBufRawPacket) in mBufArr.
They will be reused in each iteration of the loop.
The sendPackets() method will just free the mbufs inside this elements, it
won't create them again if they already exist.

Please let me know what you think

**Comment by seladb** [comment]
Fixed the double release issue. Please verify the code and reopen this issue if you find any problem
