### ISSUE TITLE
Unable to capture packets larger than MTU

### ISSUE THREAD

**Issue by cloud-yd** [seladb/PcapPlusPlus#1218]
I cannot capture a packet larger than 1514 bytes. 
For example, if the SIPRequest length is greater than 1514, I cannot resolve the request.

**Comment by cloud-yd** [comment]
![image](https://github.com/seladb/PcapPlusPlus/assets/34154498/5f966fc7-699f-4677-a733-64d4c62ea67a)
I can't parse 200OK

**Comment by seladb** [comment]
From the screenshot you shared it looks like there is IP fragmentation and your network card splits the SIP request into 2 packets.
PcapPlusPlus can only capture whatever your network card gets...

**Comment by cloud-yd** [comment]
Thank you very much for your answer.
Can this problem be solved using pcpp::IPReassembly?

**Comment by cloud-yd** [comment]
Thank you. I understand

**Comment by seladb** [comment]
@cloud-yd should we close this issue now?

**Comment by cloud-yd** [comment]
Yes, thanks again
