### ISSUE TITLE
Extremely High CPU usage compared to WireShark

### ISSUE THREAD

**Issue by MinGW64User** [seladb/PcapPlusPlus#122]
I see this issue being raised before, but no feasible solutions were available back then. Even a 0.2 second delay in the packets would be acceptable, but I can't find a place where I could configure this.

Note: Using the "[Asynchronous packet capture using a callback function](http://seladb.github.io/PcapPlusPlus-Doc/tutorial_live_capture.html#capture_packets)" method, since it seems the most customizable. (e.g. Capturing and reading from a packet vector with the help of mutex to guarantee safe reads & writes.)

I've tried these methods to reduce CPU usage:
**1.** Added delays in the libraries themselves. I wasn't able to find a place where this delay could be added in a way that would reduce CPU usage.
**2.** Added a 0.1 second sleep in the callback function. This causes the packet to be delayed by several seconds. Not good.
**3.** Used [BES ](http://mion.faireal.net/BES/)(Battle Encoder Shirase) to limit CPU usage. Limited the CPU usage of the program by 95%. Not a single packet were lost while doing this, which leads me to believe that there is a location where this sleep could possibly be added safely. Limiting CPU across the board is an  extremely bad option since I would need the other threads of my program to do CPU intensive tasks such as image recognition. Using BES is a really bad option due to this reason.

Wireshark manages to capture the packets fine with out burning your CPU to crisp ([one core at 100%](https://i.imgur.com/UQJfshx.png)). Is there a way to reduce the CPU usage of the capturing somehow? If so, then how?

**Comment by seladb** [comment]
The only way I can think that may reduce CPU is adding more sleep in the infinite while loop: [here](https://github.com/seladb/PcapPlusPlus/blob/b51ae2643bc80a3ec8f669f885a9ef32fa44700e/Pcap%2B%2B/src/PcapLiveDevice.cpp#L400), [here](https://github.com/seladb/PcapPlusPlus/blob/b51ae2643bc80a3ec8f669f885a9ef32fa44700e/Pcap%2B%2B/src/PcapLiveDevice.cpp#L409), [here](https://github.com/seladb/PcapPlusPlus/blob/b51ae2643bc80a3ec8f669f885a9ef32fa44700e/Pcap%2B%2B/src/PcapLiveDevice.cpp#L181) or [here](https://github.com/seladb/PcapPlusPlus/blob/b51ae2643bc80a3ec8f669f885a9ef32fa44700e/Pcap%2B%2B/src/PcapLiveDevice.cpp#L186) (depends which method you're using).

Other than that I don't have any more creative ideas. Please let me know if you can think of something. You can also add sleeps where I suggest and see if that lowers CPU usage

**Comment by MinGW64User** [comment]
That one did it:
`pcap_dispatch(pThis->m_PcapDescriptor, -1, onPacketArrives, (uint8_t*)pThis);`

Added a 0.1 sec sleep in there. Now CPU usage is much more reasonable. Thank you!

**Comment by seladb** [comment]
Awesome, I’m glad that worked. Maybe we cam consider adding this as a feature, please let me know what you think

**Comment by seladb** [comment]
I'd appreciate your answer. Should we keep this issue open or close it?

**Comment by seladb** [comment]
I'm closing the issue for now, please re-open it if you have any more comments or questions

**Comment by seladb** [comment]
I thought you might be interested to know that I just added the functionality you requested. Please take a look at the fix for this issue: https://github.com/seladb/PcapPlusPlus/issues/126

**Comment by limindong** [comment]
pcpp::PcapLiveDevice::DeviceConfiguration config;
config.packetBufferTimeoutMs = 1; // set number above 0
device->open(config)
