### ISSUE TITLE
support `pcap_get_selectable_fd`

### ISSUE THREAD

**Issue by tigercosmos** [seladb/PcapPlusPlus#1220]
as discussed with @seladb 
> we can expose the fd from `PcapLiveDevice` for users to use with poll() and select(). Please note that pcap_get_selectable_fd has a few limitations explained [here](https://man7.org/linux/man-pages/man3/pcap_get_selectable_fd.3pcap.html) so we probably only want to expose it for certain platforms 

so, Windows is not supported for sure, seems macOS 10.7 after can be supported?
Linux/Unix should be all supported.

**Comment by seladb** [comment]
Thanks for opening the issue @tigercosmos !
I think we can assume it's supported on Linux and macOS and not on Windows

**Comment by seladb** [comment]
@tigercosmos when I think about it more, the current [`PcapLiveDevice::startCaptureBlockingMode()`](https://github.com/seladb/PcapPlusPlus/blob/8c4f231cf0432b5ca1ef42cd26322e15f2a78489/Pcap%2B%2B/src/PcapLiveDevice.cpp#L469) already does more or less the same thing:
- It runs in an endless loop that will break only if the user returns `true` in the callback
- In each iteration of the loop it calls `pcap_dispatch` which essentially waits for the next packet (similar to `poll()`), then calls an internal callback `onPacketArrivesBlockingMode`
- This internal callback creates a `RawPacket` object and calls the user's callback. If the user's callback returns `true` it sets a flag to stop capturing packets

I think this covers the scenario you described above without using `poll()` and without opening another thread. Am I missing something?

**Comment by tigercosmos** [comment]
@seladb  True, indeed it's more or less the same.

The current `startCaptureBlockingMode` works fine and it ensures compatibility for all platforms.

However, if a programmer is going to use blocking mode (or serial programing), there is no need to open another thread. That's why I am proposing to add new support for `pcap_get_delectable_fd`.

**Comment by seladb** [comment]
@tigercosmos with the example you described above, how can the program do other logic while waiting for a packet in `poll()`?
When there are no incoming packets, the program is stuck in `poll()` and when there are incoming packets, the program handles them, there is no other logic that can happen in between 🤔

**Comment by tigercosmos** [comment]
True, sorry for confusing you. 
I just read the implementation of `startCaptureBlockingMode` again.
Actually, `startCaptureBlockingMode`  doesn't open any thread (though there are many "thread" keywords, which are confusing); however, it uses *busy looping* while running before timeout.
```cpp
while(1) {
  dev->startCaptureBlockingMode(callback, cookie, timeout);
}
```
instead, if the user uses `poll`, the program will not do busy looping and only process packets when there are packets arrived.
```cpp
while(1) {
    int retval = poll(fds, 1, -1); // waiting
    if (fds[0].revents & POLLIN) {
      pcap_dispatch(handle, 1, packet_handler_callback, nullptr);
    }
}
```

**Comment by seladb** [comment]
If I remember correctly `pcap_dispatch()` does polling internally, meaning if there are no packets `pcap_dispatch()` won't return. Can you please verify that? It may also vary per platform...

If this is not the case, I agree that polling may help and we can use it inside `startCaptureBlockingMode()`. Please let me know what you think

**Comment by seladb** [comment]
I'm not sure what's the behavior on Windows, maybe `pcap_dispatch()` doesn't get stuck if there are no packets. I think it changes per platform.

But yeah, I guess we can use `poll()` to wait for packets before calling `pcap_dispatch()`. We just need to test it carefully and make sure it works (with/without packets, with/without timeout, etc.)

**Comment by tigercosmos** [comment]
@seladb  just let you know that I am working on this.

The current signature of the function is :
```cpp
startCaptureBlockingMode(OnPacketArrivesStopBlocking onPacketArrives, void* userCookie, int timeout)
```
the `timeout` is set as seconds for now, do you mind to change the `timeout` to  milliseconds? I think  millisecond is more flexible for user controling the timeout.

Since the current blocking mode's timeout is actually not working correcly now... I don't think it will affact people? Or we can also have a new function name and make the current one deprecated?

**Comment by seladb** [comment]
@tigercosmos I think we can leave the `timeout` on seconds because on Windows (at least) `poll()` is not supported, so changing it to milliseconds will be confusing.

Another thing we can do to maintain backward compatibility is to add a new attribute to `DeviceConfiguration`: `usePoll` which can default to `true`, and use this property (together with the platform) to decide whether to use `poll()` or not

**Comment by seladb** [comment]
ok, I guess we can change `int` to `double` to get a better granularity. On Windows or if `DeviceConfiguration::usePoll == false` we should still support the previous behavior, and in this case we can probably round the `double` back to `int`?

**Comment by tigercosmos** [comment]
@seladb  I think the return value may need to change as well.

current return value:
```
 * @return -1 if timeout expired, 1 if blocking was stopped via onPacketArrives callback or 0 if an error occurred (such as device
		 * not open etc.). When returning 0 an appropriate error message is printed to log
```

If we refer to  `pcap_dispatch` and `poll` return values:

```
 pcap_dispatch() returns the number of packets processed on success; this can be 0 if no packets were read from
       a  live  capture  (if,  for example, they were discarded because they didn't pass the packet filter, or if, on
       platforms that support a packet buffer timeout that starts before any packets arrive, the timeout expires  be‐
       fore any packets arrive, or if the file descriptor for the capture device is in non-blocking mode and no pack‐
       ets were available to be read) or if no more packets are available in a ``savefile.'' It returns PCAP_ERROR if
       an  error occurs or PCAP_ERROR_BREAK if the loop terminated due to a call to pcap_breakloop() before any pack‐
       ets were processed.  If your application uses pcap_breakloop(),  make  sure  that  you  explicitly  check  for
       PCAP_ERROR and PCAP_ERROR_BREAK, rather than just checking for a return value < 0.
```

```
RETURN VALUE
       On  success,  a positive number is returned; this is the number of structures which have nonzero revents fields (in other words, those
       descriptors with events or errors reported).  A value of 0 indicates that the call timed out and no file descriptors were  ready.   On
       error, -1 is returned, and errno is set appropriately.    
```

I think it makes more sense that the return value:
- return a possible number: the count of packets processed before encountering a timeout or being manually stopped.
- return 0: no packets were processed before encountering a timeout or being manually stopped.
- return a negative number: errors


I believe there's no necessity for a return value indicating "timeout" in the function, as it will only return under two conditions: (1) when a timeout occurs, or (2) when the user manually invokes the "stop" function. The user will be able to discern the reason for the return value. Furthermore, I posit that users would find the information on "the number of processed packets" more compelling than knowing whether a timeout has transpired.

**Comment by seladb** [comment]
I'm not sure how users could know a timeout occurred if there is no return value indicating that?

The number of packets captured might be useful but users can also get it via `getStatistics()`.

However the main problem I have with changing the return value is that it would be a breaking change, so existing projects that use this method and expect a certain return value would need to change. People rely on this project so I want to make as little breaking changes as possible, especially on such a method that is being widely used
