### ISSUE TITLE
vcpkg installed old version. 22.11

### ISSUE THREAD

**Issue by xkungxfu** [seladb/PcapPlusPlus#1223]
.\vcpkg install pcapplusplus:x64-windows
windows10, use above command, vcpkg installed old version. 22.11

modify file \vcpkg\ports\pcapplusplus\portfile.cmake 
if changed 22.11 to 23.09 
```

.\vcpkg install pcapplusplus:x64-windows
Computing installation plan...
error: while looking for pcapplusplus:x64-windows:
error: while loading I:\CXXTools\vcpkg\vcpkg-2023.06.20\ports\pcapplusplus\vcpkg.json:
$ (a manifest): error: `23.09` is not a valid relaxed version (semver with arbitrary numeric element count).

```

**Comment by seladb** [comment]
yes, we're aware of that. I think @clementperon is working on it

**Comment by clementperon** [comment]
@xkungxfu I have this branch WIP: https://github.com/clementperon/vcpkg

If you want to test it

**Comment by clementperon** [comment]
MR opened: https://github.com/microsoft/vcpkg/pull/34767

**Comment by clementperon** [comment]
@xkungxfu MR has been merged could you test and close the Issue if it's ok for you ?

**Comment by seladb** [comment]
@xkungxfu I'll close this issue now, please reopen it if you find issues with the new vcpkg port
