### ISSUE TITLE
How to combine AND and OR filters

### ISSUE THREAD

**Issue by quintanapablo** [seladb/PcapPlusPlus#1225]
Hello. I need to capture the following packets:

(ip.addr eq 192.168.0.112 and ip.addr eq 192.168.0.74) and (udp.port eq 5960 or tcp.port eq 5961)

Can you help me with the correct syntax?

**Comment by seladb** [comment]
Something is wrong with this filter:
`(ip.addr eq 192.168.0.112 and ip.addr eq 192.168.0.74)`

Should one of them be the source and the other the dst IP address?

**Comment by quintanapablo** [comment]
Well, I need both. One filter where one IP is the source and the other the destination, but for other reasons I'd like to see both directions of the conversation between the hosts.

**Comment by seladb** [comment]
Got it. The filter classes offer composition, so something like this might work (although I didn't test it myself):
```cpp
pcpp::IPFilter ipFilter1("192.168.0.112", pcpp::SRC_OR_DST);
pcpp::IPFilter ipFilter2("192.168.0.74", pcpp::SRC_OR_DST);

pcpp::AndFilter ipFilters;
ipFilters.addFilter(&ipFilter1);
ipFilters.addFilter(&ipFilter2);

pcpp::PortFilter portFilter1(5960, pcpp::SRC_OR_DST);
pcpp::PortFilter portFilter2(5961, pcpp::SRC_OR_DST);

pcpp::OrFilter portFilters;
portFilters.addFilter(&portFilter1);
portFilters.addFilter(&portFilter2);

pcpp::AndFilter overallFilter;
overallFilter.addFilter(&ipFilters);
overallFilter.addFilter(&portFilters);
```

Please let me know if this code works as expected

**Comment by quintanapablo** [comment]
Thanks seladb. Is there a way to print the string that is used with BPF after using your filter classes? That way we could check the backend string used for filtering.

**Comment by seladb** [comment]
> Thanks seladb. Is there a way to print the string that is used with BPF after using your filter classes? That way we could check the backend string used for filtering.

Yes, here is how to do it:
```cpp
std::string str;
overallFilter.parseToString(str);
```

by the way, you can learn more about packet filtering by looking at PcapPlusPlus documentation and examples:
https://pcapplusplus.github.io/docs/tutorials/capture-packets#filtering-packets
https://pcapplusplus.github.io/api-docs/v23.09/_pcap_filter_8h.html
https://github.com/seladb/PcapPlusPlus/tree/master/Examples

**Comment by seladb** [comment]
@quintanapablo should we close this issue now?

**Comment by quintanapablo** [comment]
Yes please.
