### ISSUE TITLE
Porting PcapPlusPlus to buckaroo c++ package manager

### ISSUE THREAD

**Issue by brlebtag** [seladb/PcapPlusPlus#123]
It would be amazing if we could port PcapPlusPlus to buckaroo c++ package manager. (https://buckaroo.pm).

It would make life more easy.

I open a issue requesting PcapPlusPlus in buckaroo (https://github.com/LoopPerfect/buckaroo-wishlist/issues/96).

**Comment by seladb** [comment]
Sound like a great idea! I took a look at buckaroo and it shouldn't be so hard to do this. Would you like to try?

**Comment by seladb** [comment]
Awesome! Please let me know if you need my help, we can work on this together

**Comment by seladb** [comment]
Just curious - any update on that?

**Comment by brlebtag** [comment]
No. They didn't get in touch. I think you can close the issue. Buckaroo is a great idea but the project seems not very active which is a shame. Thank you for your support anyway.

**Comment by seladb** [comment]
Sure, I'll close it now, please reopen it if needed in the future

**Comment by njlr** [comment]
For those who stumble on this, there is now a PcapPlusPlus package for [Buckaroo](https://github.com/LoopPerfect/buckaroo) here: https://github.com/buckaroo-pm/seladb-PcapPlusPlus

**Comment by seladb** [comment]
is this something that  can be merged into the main branch?
