### ISSUE TITLE
[vcpkg] Static linking support

### ISSUE THREAD

**Issue by maordadush** [seladb/PcapPlusPlus#1235]
I tried to install the PcapPlusPlus static version using vcpkg and got the following error:

`vcpkg.exe install pcapplusplus:x64-windows-static`

> Computing installation plan...
> winpcap is only supported on 'windows & !uwp & !arm & !static', which does not match x64-windows-static. This usually means that there are known build failures, or runtime problems, when building other platforms. To ignore this and attempt to build winpcap anyway, rerun vcpkg with `--allow-unsupported`.

I understand from this message that the winpcap does not support a static version, does this mean that PcapPlusPlus doesn't support it either?

thanks!

**Comment by seladb** [comment]
Adding @clementperon who worked on it and might know vcpkg a bit better

**Comment by gardc** [comment]
same here, not being able to use this library is a bummer

**Comment by seladb** [comment]
@clementperon did you have a chance to look into it?

**Comment by clementperon** [comment]
Pcapplusplus doesn't support dynamic linkage.
So 'vcpkg install pcapplusplus' will already set pcapplusplus to static.

We can't enforce WinPcap to be static unfortunately.
