### ISSUE TITLE
TCP Reassembling: Flowkey not unique (ICMP-packet)

### ISSUE THREAD

**Issue by jannik3141** [seladb/PcapPlusPlus#124]
Hello,

If got an error message from this line:

https://github.com/seladb/PcapPlusPlus/blob/24dd4afa91f3234a9ba07ecb7b7d3b50d4e9bb1b/Packet%2B%2B/src/TcpReassembly.cpp#L297

 I figured out, that it was produced by an ICMP-packet. The hash5Tuple() function returns zero for every ICMP-packet, so it causes a hash collision. The ICMP-packet contained a TCP-layer therefor it was relevant for TCP-Reassembly. A quick help would be to add "could be caused by an ICMP-packet" to the error message in the above line. Another option would be to implement [hash5Tuple()](https://github.com/seladb/PcapPlusPlus/blob/b51ae2643bc80a3ec8f669f885a9ef32fa44700e/Packet%2B%2B/src/PacketUtils.cpp#L12) for ICMP, but I don't know how much effort would be needed. What would happen if the check  
 `if (packet->isPacketOfType(ICMP))  
return 0;`
would be deleted?

For me personally the encancement is probably not very important. But it would be nice to include the extended error message to help people with the same problem.

Best regards,
Jannik

**Comment by seladb** [comment]
Hi Jannik, usually ICMP packets don't contain a TCP layer, that's why TCP reassembly aren't relevant for them. Could you please attach an example of the packets you're working on so I can assess the right solution?

**Comment by seladb** [comment]
Hi Jannik, as far as I understand this example doesn't necessarily have to be ICMP tunneling. It can be just a standard "destination unreachable" message that contains (part of) the original packet.
Anyway, I'm not sure how common ICMP tunneling is and whether TCP reassembly should support it. I'd love to hear your opinion about it

**Comment by jannik3141** [comment]
Hi, you are probably right about the example. I will talk with my colleagues next weak and write again regarding ICMP-tunneling. Thanks so far!

**Comment by seladb** [comment]
Sure! I'll be looking forward for your answer. In the mean time - would you like to keep the issue open or close it and then reopen if needed?

**Comment by seladb** [comment]
I agree with you. ICMP packets containing TCP data should not be throwing errors, but rather be ignored, just like any other non-TCP packet.  I'll make that fix and output an appropriate debug message. Thanks for reporting this issue!

**Comment by seladb** [comment]
Fixed! Please let me know if the solution works. I'll close the issue, please reopen if necessary

**Comment by jannik3141** [comment]
Hi @seladb, thank you! The fix is working for me. I have talked to my colleagues and we don't think supporting ICMP-tunneling is necessary, so i won't reopen the issue. Thanks for your fast responses the fast fixing!

**Comment by seladb** [comment]
Sure, thanks for reporting the issue and contributing to the PcapPlusPlus project!
