### ISSUE TITLE
LIBPCAP_OPEN_LIVE_TIMEOUT=-1  caused  highly CPU utilization

### ISSUE THREAD

**Issue by ahuzjx** [seladb/PcapPlusPlus#126]
[http://www.tcpdump.org/manpages/pcap_set_timeout.3pcap.html](url)
pcap_set_timeout() sets the packet buffer timeout that will be used on a capture handle when the handle is activated to to_ms, which is in units of milliseconds. (See pcap(3PCAP) for an explanation of the packet buffer timeout.)
The behavior, if the timeout isn't specified, is undefined, as is the behavior if the timeout is set to zero or to a negative value. We recommend always setting the timeout to a non-zero value unless immediate mode is set, in which case the timeout has no effect.   

Is it possible to provide an interface to set the param?

**Comment by seladb** [comment]
I will provide a fix soon. This issue was raised by other people as well. I'll provide an interface to set the packet buffer timeout as well the packet buffer size

**Comment by seladb** [comment]
I added an overload to `PcapLiveDevice::open()` that enables to open a device with a non-default configuration, including changing the buffer timeout. Please take a look at: [here](http://seladb.github.io/PcapPlusPlus-Doc/Documentation/a01235.html#a3f58e22a71cbed9109ae75bd1759e8ed)

I'm closing the issue now. Please reopen it if you think it's necessary

**Comment by Dysl3xik** [comment]
I just stumbled upon this because I was searching for high CPU usage in windows. 

May I suggest you add somthing about this in the documentation or consider setting the default to 1 in windows? I was capturing on 2x nics and burning up 25% of my i7!

**Comment by seladb** [comment]
It is already documented in PcapPlusPlus API: https://pcapplusplus.github.io/api-docs/structpcpp_1_1_pcap_live_device_1_1_device_configuration.html

Regarding changing the default value on Windows - it will indeed decrease CPU usage but will also impact performance. That's a tough choice...
