### ISSUE TITLE
Why OnPacketArrivesCallback is not std::function

### ISSUE THREAD

**Issue by vaguue** [seladb/PcapPlusPlus#1261]
Hello and thank you for this great project! I wonder why OnPacketArrivesCallback is defined as a C-style function pointer, while there's a C++ std::function.

Sincerely,
Seva D.

**Comment by seladb** [comment]
This is because until some time ago PcapPlusPlus supported C++98/03. We moved PcapPlusPlus to C++11 only in version 22.05 (about 1.5 years ago). We can change it to `std::function` but it'll be a breaking change and we try to avoid such changes as much as possible to be backward compatible

**Comment by tigercosmos** [comment]
I think we can also support `std::fucntion` by overloading and still keep the backward compatibility?

**Comment by seladb** [comment]
Yes, I guess we can add an overload if we need to 🤔 
If we do that we can make the existing overloads as deprecated and at one of the future versions remove them

**Comment by vaguue** [comment]
If we agree on this approach, I can help out and prepare a PR by next weekend

**Comment by tigercosmos** [comment]
go ahead :)

**Comment by tigercosmos** [comment]
@seladb  we can close this one.
