### ISSUE TITLE
Could not found pcapplusplus/Syslog.h header file

### ISSUE THREAD

**Issue by g88827929g** [seladb/PcapPlusPlus#1262]

**Comment by seladb** [comment]
@g88827929g we need more details to assist because PcapPlusPlus doesn't use syslog anywhere
- Which platform are you using?
- Which version of PcapPlusPlus?
- Can you share the code that causes this error?
- Can you share the output you see?

**Comment by g88827929g** [comment]
does pcapplusplus support parsing syslog?

**Comment by seladb** [comment]
> does pcapplusplus support parsing syslog?

Do you mean parsing syslog files?
PcapPlusPlus is meant for parsing network packets, not files... unless you're referring to a specific network protocol used by syslog?

**Comment by g88827929g** [comment]
What I mean is to parse the syslog network protocol to obtain the message

**Comment by seladb** [comment]
No, PcapPlusPlus doesn't currently support this protocol

**Comment by seladb** [comment]
I'll close this issue now, please reopen if needed
