### ISSUE TITLE
ICMP payload extraction problem

### ISSUE THREAD

**Issue by soysc** [seladb/PcapPlusPlus#1272]
Hi, I hope this message finds you well. I am writing to bring attention to an issue I encountered while using your project.

When attempting to retrieve the ICMP layer payload from a captured ICMP packet, I discovered that the payload data can only be accurately extracted when adjusting the data pointer by subtracting 8 and the dataLength by adding 8. Here is my code and pcap file.

```
for (pcpp::Layer *layer = packet.getFirstLayer(); layer != NULL; layer = layer->getNextLayer()) {
    switch (layer->getProtocol()) {
        case pcpp::ICMP: {
            pcpp::IcmpLayer *icmp_layer = static_cast<pcpp::IcmpLayer *>(layer);
            pcpp::icmp_echo_reply *icmp_data = icmp_layer->getEchoReplyData();
            string payload((char *)(icmp_data->data - 8), icmp_data->dataLength + 8);
            break;
        }
        default:
            break;
    }
}
```
[1.zip](https://github.com/seladb/PcapPlusPlus/files/13742690/1.zip)

It appears that my ICMP packet does not have an 8-byte timestamp, as defined in the _struct icmp_echo_hdr_. Could there be an issue with my code? Thank a lot!

**Comment by seladb** [comment]
@soysc you're right, the ICMP layer parser assumes the first 8 bytes of the data is always the timestamp. This is correct in many of the cases but apparently not in yours. However I'm not sure how PcapPlusPlus can automatically detect if a timestamp exists or not 🤔

**Comment by soysc** [comment]
> @soysc you're right, the ICMP layer parser assumes the first 8 bytes of the data is always the timestamp. This is correct in many of the cases but apparently not in yours. However I'm not sure how PcapPlusPlus can automatically detect if a timestamp exists or not 🤔

Thank you very much for your response. I think the possible reason is that I construct the ping payload myself. For the time being, I will proceed with running the code using the pointer shift of 8 bytes as mentioned above.

**Comment by seladb** [comment]
@soysc should we close this issue?

**Comment by soysc** [comment]
> @soysc should we close this issue?

ok, thanks
