### ISSUE TITLE
 "(tcp.seq == 1)" filter is not working pcpp::PcapNgFileReaderDevice 

### ISSUE THREAD

**Issue by mkurkute** [seladb/PcapPlusPlus#1274]
Hi,
I am setting following filter string to set to the pcpp::PcapNgFileReaderDevice but not working.

"(tcp[tcpflags] & tcp-push != 0) and (tcp[tcpflags] & tcp-ack != 0) and (tcp.seq == 1)"

I found that filter "(tcp.seq == 1)" is not accepted, how can I set the filter on TCP relative sequence number ?

Thanks in advance,
-Mak

**Comment by seladb** [comment]
Can you please post your code?

**Comment by mkurkute** [comment]
pcpp::RawPacket rawPacket;
 pcpp::PcapNgFileReaderDevice readerInbound("c:\\00test.pcapng");
 if (readerInbound.open())
 {
     if (!readerInbound.setFilter("(tcp[tcpflags] & tcp-push != 0) and (tcp[tcpflags] & tcp-ack != 0) and and (tcp.seq == 1) "))
         cout<<"Inbound Filter NOT set";

     pcpp::RawPacket rawPacket;
     if (readerInbound.getNextPacket(rawPacket))
     {
         std::string packetComment;
         while (readerInbound.getNextPacket(rawPacket, packetComment))
         {
             // parse the raw packet into a parsed packet
             pcpp::Packet parsedPacket(&rawPacket);
             // verify the packet is IPv4
             if (parsedPacket.isPacketOfType(pcpp::IPv4))
             {
                 // extract source and dest IPs
                 pcpp::IPv4Address srcIP = parsedPacket.getLayerOfType<pcpp::IPv4Layer>()->getSrcIPv4Address();
                 pcpp::IPv4Address destIP = parsedPacket.getLayerOfType<pcpp::IPv4Layer>()->getDstIPv4Address();
                 pcpp::TcpLayer* tcpLayer = parsedPacket.getLayerOfType<pcpp::TcpLayer>();
                 std::string strPID = packetComment.substr(packetComment.find_first_of("=") + 1, (packetComment.find_first_of(" ") - 2) - packetComment.find_first_of("=") + 1);
                 DWORD m_dwPID = stoi(strPID);
             }
         }
     }

**Comment by seladb** [comment]
I don't think `tcp.seq` is a valid [BPF filter syntax](https://biot.com/capstats/bpf.html). PcapPlusPlus uses libpcap/WinPcap/NPcap to filter packets which in turn uses BPF filters to do the filtering. I'm not sure if there is an easy way to filter by TCP sequence...

As an alternative you can use PcapPlusPlus to parse the packets, extract the TCP layer and do the filtering yourself. This shouldn't be more than a few lines of code, but obviously a bit slower than using BPF filters

**Comment by seladb** [comment]
@mkurkute should we close this issue?
