### ISSUE TITLE
Pcap with nested vlan

### ISSUE THREAD

**Issue by gjshar** [seladb/PcapPlusPlus#129]
Not sure if pcap files with nested vlan can be generated. If yes, example will be highly appreciated. Thanks.

**Comment by seladb** [comment]
Yes, this should be very easy to create packets with nested vlans. You can see an example in PcapPlusPlus unit-tests (lines 280-292): https://github.com/seladb/PcapPlusPlus/blob/7920a9cf77bc27730b9ee4f077923dc0bc75710a/Tests/Packet%2B%2BTest/main.cpp#L280

Please let me know if you need more information

**Comment by seladb** [comment]
Please let me know if more information is needed

**Comment by gjshar** [comment]
Thank you. End up not using as needed pcap with nanosecond precision.

**Comment by seladb** [comment]
Sure. I'll close the issue now. Please reopen it if necessary
