### ISSUE TITLE
numOfPacketsToRead of IFileReaderDevice::getNextPackets doesn't match doc

### ISSUE THREAD

**Issue by sinall** [seladb/PcapPlusPlus#131]
Doc:

> Number of packets to read. If value <0 all remaining packets in the file will be read into the raw packet vector (this is the default value)

Code:
```
int IFileReaderDevice::getNextPackets(RawPacketVector& packetVec, int numOfPacketsToRead)
{
	if (numOfPacketsToRead == 0)
		return 0;

	int numOfPacketsRead = 0;

	while (true)
	{
		RawPacket* newPacket = new RawPacket();
		bool packetRead = getNextPacket(*newPacket);
		if (packetRead)
		{
			packetVec.pushBack(newPacket);
			numOfPacketsRead++;
			if (numOfPacketsRead >= numOfPacketsToRead) //<-- I think 'numOfPacketsToRead < 0' need to checked here.
				return numOfPacketsRead;
		}
		else
		{
			delete newPacket;
			return numOfPacketsRead;
		}
	}

	return numOfPacketsRead;
}
```

**Comment by sinall** [comment]
@seladb I suggest the another part of doc may need to be changed:

> The number of packets actually read. This value will be equal to numOfPacketsToRead if numOfPacketsToRead > 0 and enough packets remain to read, or less than numOfPacketsToRead if numOfPacketsToRead > 0 and not enough packets remain to read, or **if numOfPacketsToRead < 0 the return value will be the number of packets remain to read**

The return value may just be the 'The number of packets actually read'.

**Comment by seladb** [comment]
Thanks for reporting this issue! Do you think you can provide a quick PR that fixes this?

I'll take care of the documentation update

**Comment by sinall** [comment]
@seladb 
I'm still struggling with poor network in China. Hopefully I could download the source and make a PR later.

Here's the code I think could work:
```
int IFileReaderDevice::getNextPackets(RawPacketVector& packetVec, int numOfPacketsToRead)
{
	int numOfPacketsRead = 0;

	for (; numOfPacketsToRead < 0 || numOfPacketsRead < numOfPacketsToRead; numOfPacketsRead++)
	{
		RawPacket* newPacket = new RawPacket();
		bool packetRead = getNextPacket(*newPacket);
		if (packetRead)
		{
			packetVec.pushBack(newPacket);
		}
		else
		{
			delete newPacket;
			break;
		}
	}

	return numOfPacketsRead;
}

```
