### ISSUE TITLE
Refactor PointerVector to use std::unique_ptr internally?

### ISSUE THREAD

**Issue by Dimi1010** [seladb/PcapPlusPlus#1326]
It would remove the need to manually track 'new'/'delete' calls of objects and will minimize the risk of memory leaks.

`PonterVector`'s copy ctor has a potential memory leak:
```
PointerVector(const PointerVector& other)
{
	for (const auto iter : other)
	{
		T* objCopy = new T(*iter);
		m_Vector.push_back(objCopy);  // <-- If this throws objCopy is leaked.
	}
}
```

**Comment by seladb** [comment]
@Dimi1010 do you mean use `std::unique_ptr` only in the copy c'tor?

**Comment by tigercosmos** [comment]
Should be fixed
