### ISSUE TITLE
How to rebuild a packet?

### ISSUE THREAD

**Issue by sinall** [seladb/PcapPlusPlus#133]
I'm trying to decrypt a socket protocol. The request/response packet between client and server are encrypted.

My plan is using PcapPlusPlus to decrypt the packets and regenerate a decrypted pcapng file so I can view the packets in Wireshark easily.

I find the `Packet.getLayerOfType<pcpp::PayloadLayer>()` return the data, which I can decrypt and then replace into `Packet`. But I don't find a way to regenerate `RawPacket` from a parsed `Packet`.

Any suggestions?

**Comment by seladb** [comment]
I'm not sure I understand your question. Are you trying to take the payload, decrypt it and replace the encrypted data with the decrypted one in the `PayloadLayer`? Or are you trying to replace the whole `RawPacket` with something else?

**Comment by sinall** [comment]
Yes, I'm trying to take the payload, decrypt it and replace the encrypted data with the decrypted one in the `PayloadLayer`. And I want to **rebuild the RawPacket** so I can write the decrypted packet into another **pcapng** file, then I will be able to view the plain data in Wireshark.

Currently I take the **first 54 bytes**(some headers AFAIK) from RawPacket, append the decrypted PayloadLayer data to construct the `RawPacket`, the problem is there is a **Frame check sequence error** in 'Ethernet II' section in Wireshark.

**Comment by seladb** [comment]
You shouldn't really rebuild the `RawPacket`, it's already being updated when you update the various layers. You should probably create a new `PayloadLayer` with the new data, remove the existing `PayloadLayer` from the packet by using `Packet::removeLayer()` and add the new `PayloadLayer` by using `Packet::addLayer()`. Finally run `Packet::computeCalculateFields()` to re-calculate checksums etc.

Please let me know if that works

**Comment by sinall** [comment]
That is what I was looking for. Thanks. It looks much better now.

There are still an issues: the **info** column of Wireshark shows `[TCP Retransmission]` or `[TCP ACKed unseen segment] [TCP Retransmission]`.

**Comment by seladb** [comment]
Are you trying to decrypt one packet or a whole stream?
When trying to show TCP packets in Wireshark that don't have their equivalent "ACK" packets, Wireshark would give that message

**Comment by sinall** [comment]
I'm trying to process all packets (decrypt the encrypted packets, keep the non-encrypted packets).
Here's the code snippet:

```
{
	if (!reader.getNextPackets(rawPacketVec_, (std::numeric_limits<int>::max)())) {
		std::cout << "Couldn't read packets in the file" << std::endl;
		return;
	}

	for (auto iter = rawPacketVec_.begin(); iter < rawPacketVec_.end(); iter++) {
		auto& rawPacket = **iter;
		pcpp::Packet packet(&rawPacket);
		auto ipv4Layer = packet.getLayerOfType<pcpp::IPv4Layer>();
		if (!ipv4Layer) {
			writer.writePacket(rawPacket);
			continue;
		}
		auto payloadLayer = packet.getLayerOfType<pcpp::PayloadLayer>();
		if (!payloadLayer) {
			writer.writePacket(rawPacket);
			continue;
		}
		auto payload = std::string((char*)payloadLayer->getData(), payloadLayer->getDataLen());

		auto isRequest = boost::algorithm::starts_with(ipv4Layer->getSrcIpAddress().toString(), "192.168");
		if (isRequest) {
			if (IsFirstRequest(payload)) {
				//...
				writer.writePacket(rawPacket, "First request");
			}
			else if (IsSecondRequest(payload)) {
                                // *** Decrypt and re-create new packet
                                //
				auto rawPayload = packetParser->ParseSecondRequest(payload);
				auto newPacket = CreatePacket(packet, rawPayload);
				writer.writePacket(newPacket, "Second request");
			}
			else {
                                // *** Decrypt and re-create new packet
                                //
				auto rawPayload = packetParser->ParseRequest(payload);
				auto newPacket = CreatePacket(packet, rawPayload);
				writer.writePacket(newPacket);
			}
		}
		else {
			if (IsFirstResponse(payload)) {
				writer.writePacket(rawPacket, "First response");
			}
			else if (IsSecondResponse(payload)) {
                                // *** Decrypt and re-create new packet
                                //
				auto rawPayload = packetParser->ParseSecondResponse(payload);
				auto newPacket = CreatePacket(packet, rawPayload);
				writer.writePacket(newPacket, "Second response");
			}
			else {
                                // *** Decrypt and re-create new packet
                                //
				auto rawPayload = packetParser->ParseResponse(payload);
				auto newPacket = CreatePacket(packet, rawPayload);
				writer.writePacket(newPacket);
			}
		}
	}
}

pcpp::RawPacket MyAnalyzer::CreatePacket(pcpp::Packet& packet, const std::string& newPayload) const {
	auto payloadLayer = packet.getLayerOfType<pcpp::PayloadLayer>();
	auto newPayloadLayer = new pcpp::PayloadLayer((uint8_t*)newPayload.data(), newPayload.length(), false);
	packet.removeLayer(payloadLayer);
	packet.addLayer(newPayloadLayer);
	packet.computeCalculateFields();
	auto rawPacket = packet.getRawPacket();
	return *rawPacket;
}

```

**Comment by seladb** [comment]
It's hard to understand from the code what causes this issue. Can you attach sample pcap files of the input and output of your program?

**Comment by sinall** [comment]
What I can see is if the length changed, then It will lead [TCP Retransmission] problem.

I append a '\0' char to existing payload, then the problem appears.

```
pcpp::RawPacket ThsAnalyzer::CreatePacket(pcpp::Packet& packet, const std::string& newPayload) const {
	auto payloadLayer = packet.getLayerOfType<pcpp::PayloadLayer>();
	std::string newPalyload = std::string((char*)payloadLayer->getData(), payloadLayer->getDataLen());
	newPalyload += ""s;
	//newPalyload += "\0"s; // <-- This line makes the [TCP Retransmission] problem.
	auto newPayloadLayer = new pcpp::PayloadLayer((uint8_t*)newPalyload.data(), newPalyload.length(), false);
	packet.removeLayer(payloadLayer);
	packet.addLayer(newPayloadLayer);
	packet.computeCalculateFields();
	auto rawPacket = packet.getRawPacket();
	return *rawPacket;
}

```

**Comment by seladb** [comment]
I'm not sure why this happens. I'll need to see a pcap example to investigate more

**Comment by sinall** [comment]
The current pcapng file has some sensitive info, so I take one from '**Tutorial-PcapFiles**'. I append 'abc' to existing payload, there will be some similar problems [TCP Out-Of-Order].

```
	pcpp::PcapFileReaderDevice reader(inputFileName.c_str());
	if (!reader.open()) {
		std::cout << "Error opening the pcap file" << std::endl;
		return;
	}

	if (!reader.getNextPackets(rawPacketVec_, (std::numeric_limits<int>::max)())) {
		std::cout << "Couldn't read the first packet in the file" << std::endl;
		return;
	}
	reader.close();

	pcpp::PcapFileWriterDevice writer(outputFileName.c_str());
	writer.open();
	PacketParser::Ptr packetParser(new MockPacketParser());

	for (auto iter = rawPacketVec_.begin(); iter < rawPacketVec_.end(); iter++) {
		auto& rawPacket = **iter;
		pcpp::Packet packet(&rawPacket);
		auto ipv4Layer = packet.getLayerOfType<pcpp::IPv4Layer>();
		if (!ipv4Layer) {
			writer.writePacket(rawPacket);
			continue;
		}
		auto payloadLayer = packet.getLayerOfType<pcpp::PayloadLayer>();
		if (!payloadLayer) {
			writer.writePacket(rawPacket);
			continue;
		}
		auto payload = std::string((char*)payloadLayer->getData(), payloadLayer->getDataLen());
		auto newPalyload = payload + "abc"s; // <-- This line causes problem.
		auto newPayloadLayer = new pcpp::PayloadLayer((uint8_t*)newPalyload.data(), newPalyload.length(), false);
		packet.removeLayer(payloadLayer);
		packet.addLayer(newPayloadLayer);
		packet.computeCalculateFields();
		auto newRawPacket = packet.getRawPacket();
		writer.writePacket(*newRawPacket);
	}
	writer.close();
```


[Debug.zip](https://github.com/seladb/PcapPlusPlus/files/2342022/Debug.zip)

**Comment by sinall** [comment]
@seladb not urgent, since the code already works, I can view the data in decrypted packet.

**Comment by seladb** [comment]
I had a look at your code and I think I understand the issue you see in Wireshark:

From the info you provided I assume the packets carrying the encrypted payload are TCP packets. You also mentioned the decryption process adds 1 or more characters to the payload, meaning the original size of the packets is different than the size after decryption. 

The way the TCP protocol works is it keeps track the stream by measuring the size of the TCP payload in each packet. Each TCP packet keeps the current offset in the stream (in "seq number" field) and each ACK packet acknowledges the offset it has seen (in the "ack number" field). By changing the size of the payload you scramble this order and that's why you're getting these errors in Wireshark.

The way to solve this is to change the "seq number" and "ack number" of the packets to reflect the new size of the packets, or try to keep the decrypted and encrypted payload size equal.

Please let me know if you need more info

**Comment by seladb** [comment]
There is a module in PcapPlusPlus called [TCP reassembly](https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/header/TcpReassembly.h) which uses "seq number" and "ack number" to retrieve TCP streams from packets. You can look at the code there.

In general, PcapPlusPlus parses packets one by one without keeping track of previous packets. That's why you can't see "seq num" and "ack num" adjustments. You can also read about how TCP protocol works and figure out how to do these changes. If you still need help please reach out and I'll try to provide more info

**Comment by seladb** [comment]
Did you manage to fix the seq and ack numbers?

**Comment by sinall** [comment]
Not yet, don't know how to deal with it. So just hold the issue for now.

**Comment by seladb** [comment]
Since it's not a PcapPlusPlus issue, do you mind if I close it for now and you can reopen it if you have more questions?
