### ISSUE TITLE
TCP Reassembly: Wrong calculation of missing data length

### ISSUE THREAD

**Issue by axmahr** [seladb/PcapPlusPlus#1333]
Hi,

in the attached pcap file in [tcp_missing_data_out_of_order.zip](https://github.com/seladb/PcapPlusPlus/files/14496265/tcp_missing_data_out_of_order.zip), there is an unlucky combination of missing data and one out-of-order packet where the TCP reassembly functionality of PcapPlusPlus doesn't calculate the correct amount of the missing bytes. For triggering this, I used your tool [TcpReassembly](https://github.com/seladb/PcapPlusPlus/tree/master/Examples/TcpReassembly) and passed the pcap file to it.

Investigating the affected connection in Wireshark, the correct number of 1460 missing bytes is determined by taking the difference between the sequence number of the out-of-order packet 10 and packet 7. However, PcapPlusPlus uses the sequence number of packet 8 instead of packet 10 resulting in 2697 missing bytes. At the end, the TCP payload of packet 10 is not contained in the reconstructed TCP stream.

**Comment by seladb** [comment]
@axmahr the reason this happens is because the first packet that has a missing data has the FIN flag set, so TCP reassembly thinks the connection is ending:

![image](https://github.com/seladb/PcapPlusPlus/assets/9059541/4d09aa9d-2fb6-4515-9884-8ed767cdeb47)

**Comment by axmahr** [comment]
Ah I see, thanks. I manually unset the mentioned FIN flag in the capture file and then PcapPlusPlus reconstructs the stream as intended.

Is there a way to modify the TCP reassembly functionality so that, even if the FIN flag is set, later (possible out-of-order) packets are considered so that at the end, PcapPlusPlus ends up giving the same result as Wireshark for the capture file I sent you?

**Comment by seladb** [comment]
> Ah I see, thanks. I manually unset the mentioned FIN flag in the capture file and then PcapPlusPlus reconstructs the stream as intended.
> 
> Is there a way to modify the TCP reassembly functionality so that, even if the FIN flag is set, later (possible out-of-order) packets are considered so that at the end, PcapPlusPlus ends up giving the same result as Wireshark for the capture file I sent you?

@axmahr I'm not sure how Wireshark does it, but a FIN flag usually indicates to the other side (client/server) that the flow is ending. Any packet after that shouldn't really be part of the flow. Theoretically, packets that come after might belong to a different flow with the same TCP ports (seems unlikely to happen, but still). I'm not sure how to fix the logic in PcapPlusPlus to accommodate this scenario... what do you think?

**Comment by axmahr** [comment]
@seladb I also don't know how Wireshark approaches this and have no idea how this could be fixed in PcapPlusPlus.

**Comment by seladb** [comment]
@axmahr I think this is kind of an edge case so not sure we can/should fix it. Are you ok with closing this issue?

If we hear about it more we can consider diving deeper and try to find a solution

**Comment by axmahr** [comment]
@seladb Yes I'm ok with closing the issue. Thanks a lot for investigating! :)
