### ISSUE TITLE
Why is std::byte not used?

### ISSUE THREAD

**Issue by T-640** [seladb/PcapPlusPlus#1338]
Greetings!

After a quick look I see that the uint8_t type is used to represent a byte instead. I am curious: is there a particular reason for that or you just want to keep the compatibility with the older C++ standard?

**Comment by tigercosmos** [comment]
@T-640  Hi, this project is now based on C++11, and std:byte is C++17 feature. In addition, this project has existed for a long time since the era of C++98.

**Comment by seladb** [comment]
> @T-640 Hi, this project is now based on C++11, and std:byte is C++17 feature. In addition, this project has existed for a long time since the era of C++98.

Just a small correction: the project does exist for a long time, but not since the era of C++98 🙂 It's just when I started it (~10 years ago) I wanted C++ code that was compatible with C++98. We finally moved to C++11 about 1-2 years ago, but we're not yet ready to move to C++17 😄
