### ISSUE TITLE
corrupted DevicesList and corrupted PcapFileWriterDevice

### ISSUE THREAD

**Issue by ChaosSaber** [seladb/PcapPlusPlus#134]
OS: Windows 10.0.17134 Build 17134 64-Bit
IDE: Visual Studio 2015
version: https://github.com/seladb/PcapPlusPlus/tree/5a0405eb4fc8d3d589449da0abac66d34bd55afc

Issue 1 (getPcapLiveDevicesList): all network interfaces found on my system have no name and invalid IP and mac Addresses. In version 18.08 every interfaces had a name and valid ip and mac adresses. 
Example Code:
```
    for (auto dev : pcpp::PcapLiveDeviceList::getInstance().getPcapLiveDevicesList())
    {
        std::cout << dev->getDesc() << std::endl;
        if (!dev->getName())
        {
            std::cout << "\tno name" << std::endl;
            continue;
        }
        std::cout << "\t" << dev->getMacAddress().toString() << std::endl;
        std::cout << "\t" << std::string(dev->getName()) << std::endl;
        std::cout << "\t" << dev->getIPv4Address().toString() << std::endl;
    }
```
Expected Output:
```
Oracle
        0a:00:27:00:00:15
        \Device\NPF_{880DBE05-6B9E-435D-B509-17D918D5C0CC}
        192.168.56.1
NdisWan Adapter
        00:00:00:00:00:00
        \Device\NPF_{FA7CAA1D-106C-4854-85BE-543E775F7CCB}
        0.0.0.0
....
```
gotten output:
```
 \Device\NPF_{880DBE05-6B9E-435D-B509-17D918D5C0CC}
        no name
 \Device\NPF_{FA7CAA1D-106C-4854-85BE-543E775F7CCB}
        no name
.....
```

Issue 2 (PcapFileWriterDevice): when i allocate memory for a PcapFileWriterDevice and then delete it i get a heap corruption. 
Example Code: 
```
    auto writer = new pcpp::PcapFileWriterDevice("test.pcap");
    if (writer)
        delete writer; // <----- Heap Corruption here
```
If anything is unclear, just ask

**Comment by seladb** [comment]
Hi, I tried to run the code you published on Win10 and VS2015 and didn't encounter any of these issues. Maybe it is something with your configuration?

**Comment by ChaosSaber** [comment]
yeah ok, my fault. I just copied the newly build libs and forgot to copy the new headers. Sorry for the false alarm. 
Well, i will stick to the v18.08. for now. It works now and i try to keep it that way.
