### ISSUE TITLE
Power of 2 restriction for number of queues in DpdkDevice

### ISSUE THREAD

**Issue by lucashc** [seladb/PcapPlusPlus#1340]
Hi there,

First of all, thank you for this amazing project. I am currently using the DpdkDevice class to set-up a PCIe ethernet card.
I noticed that when using the `DpdkDevice::openMultiQueues` a check gets executed whether the number of queues is a power of 2. I believe that this is necessary for VF devices, but this is not necessary for raw PCIe devices like the devices supported by the MLX5 driver. 

I have a pure C program that calls DPDK directly, and it operators correctly on a MLX5 device with 15 RX/TX queues. The reason for having that precise number of queues is that on a 16-core system, one has 1 core as main core and then 15 worker queues, each of which is hooked up to one RX/TX queue pair. Using 16 queues in this scenario with 15 worker cores, would leave some packets dangling.

The specific code is: [`Pcap++/src/DpdkDevice.cpp:292`](https://github.com/seladb/PcapPlusPlus/blob/1ff377c5de22caf9907fcc31f3f71ea138346155/Pcap%2B%2B/src/DpdkDevice.cpp#L292).

Could this check be expanded such that it only runs on VF devices, but not on other devices?
Or better, is the check really necessary? Doesn't DPDk throw a descriptive error in that case?

**Comment by seladb** [comment]
Thanks @lucashc for flagging it! I wasn't aware that PCIe cards don't have this restriction. There is a very easy fix for it: we already have an [`isVirtual()`](https://github.com/seladb/PcapPlusPlus/blob/1ff377c5de22caf9907fcc31f3f71ea138346155/Pcap%2B%2B/src/DpdkDevice.cpp#L546) method that we can use to determine whether or not to do this check. We only need to add it.

Would you consider opening a PR with the fix?

**Comment by seladb** [comment]
Fixed in #1343
