### ISSUE TITLE
Issue changing DeviceConfiguration packetBufferSize

### ISSUE THREAD

**Issue by dnlbaines** [seladb/PcapPlusPlus#137]
I am trying to change the packet buffer size for a PcapLiveDevice by doing the following:
```
pcpp::PcapLiveDevice::DeviceConfiguration config;
config.packetBufferSize = 100;
if (!dev->open(config))
{
	printf("Cannot open device\n");
 	exit(1);
}
```

Setting the buffer size to 100 or greater causes the following error when running the program:
```
can't mmap rx ring: Invalid argument
Cannot open device
```
I know it works with values under 100 as then it just uses the default but can't get it to work with a custom value. If you can reproduce this that would be great (I am using Ubuntu 16.04), otherwise suggestions are welcome on how I can solve this issue.

**Comment by seladb** [comment]
Yes, that's a good idea, I'll do that

**Comment by seladb** [comment]
Done, please let me know if you think anything is missing

**Comment by dnlbaines** [comment]
That looks good to me!
