### ISSUE TITLE
Packet::removeLayer() returns succesfull but layer can't be added to another packet

### ISSUE THREAD

**Issue by ChaosSaber** [seladb/PcapPlusPlus#138]
OS: Windows 10.0.17134 Build 17134 64-Bit
IDE: Visual Studio 2015
version: 18.08

I tried to remove a layer from a packet and add it to another packet. The adding process failed with the message: "Layer is already allocated to another packet. Cannot use layer in more than one packet" despite that removeLayer returned true.
Code to reproduce:
```
pcpp::EthLayer eth(pcpp::MacAddress("0a:00:27:00:00:15"), pcpp::MacAddress("0a:00:27:00:00:16"));
pcpp::Packet packet1, packet2;
if (packet1.addLayer(&eth))
    std::cout << "succesfully added layer" << std::endl;
else
    std::cout << "adding layer failed" << std::endl;
std::cout << "Packet size: " << packet1.getRawPacket()->getRawDataLen() << std::endl;
if (packet1.removeLayer(&eth))
    std::cout << "succesfully removed layer" << std::endl;
else
    std::cout << "removing layer failed" << std::endl;
std::cout << "Packet size: " << packet1.getRawPacket()->getRawDataLen() << std::endl;
if (packet2.addLayer(&eth))
    std::cout << "succesfully added layer" << std::endl;
else
    std::cout << "adding layer failed" << std::endl;
```
Output:
```
succesfully added layer
Packet size: 14
succesfully removed layer
Packet size: 0
Layer is already allocated to another packet. Cannot use layer in more than one packet
adding layer failed
```
The layer was obviously removed from the packet, but for whatever reason can't be added to the new packet.
adding `layer->m_packet = NULL` at the end of the removeLayer function caused a crash. So the easy Solution unfortunately didn't work (at least for me).

**Comment by seladb** [comment]
That is indeed an edge case that is not handled properly. I can fix it but it may take me some time, how urgent is it for you?

**Comment by seladb** [comment]
Thanks for your patience. I'll try to provide a fix as soon as I can. 

Regarding your question: you can definitely modify a layer after you add it to a packet. The packet data and size will change according to the layer's data

**Comment by ChaosSaber** [comment]
hmm, ok, last question for now. How is that handled? I have a custom payload layer. I add some data to it. Do i have to check in the function from the layer if it is part of a packet and have to act differently or is there allready a function somewhere i can use?

**Comment by seladb** [comment]
You don't have to check whether the layer is part of a packet or not. You can go ahead and change the layer's data directly from the layer instance. It will figure out by itself whether it's a stand-alone layer of part of a packet and will act accordingly

**Comment by seladb** [comment]
Done.
I also added unit-tests with the case you describe: 

https://github.com/seladb/PcapPlusPlus/blob/5d92c442d6e29a1b5b8abdf0624c32d9ba055ca5/Tests/Packet%2B%2BTest/main.cpp#L1924

**Comment by seladb** [comment]
Following this issue I did a major revamp in `Packet::removeLayer()` and the logic is more straight forward now. For your case there is a new API called [Packet::detachLayer()](http://seladb.github.io/PcapPlusPlus-Doc/Documentation/a01128.html#a54d83577cda897699f28595477f2d92d) which does exactly what you need.

Please take a look at the code snippet inside the unit-tests: 
https://github.com/seladb/PcapPlusPlus/blob/e4a8d95d16815f56f30cb2be0f7f5dc0bdd5c90d/Tests/Packet%2B%2BTest/main.cpp#L1960

**Comment by ChaosSaber** [comment]
Ok, thanks for the info.
