### ISSUE TITLE
SNI Extension with zero length

### ISSUE THREAD

**Issue by dhananjaykum** [seladb/PcapPlusPlus#1380]
We use PcapPlusPlus to get the server hostname from SSLServerNameIndicationExtension. However we found a crash once in a machine where the extension has length 0.

As a result when fetching the hostname we get a null pointer exception and our program crashes here https://github.com/seladb/PcapPlusPlus/blob/4d48615c9bfb2ef0c61d50e1e1dd3e3d63a82be0/Packet%2B%2B/src/SSLHandshake.cpp#L1121. 

We have seen this issue once. What scenario can cause this? Should the caller always check if getData() is not null before calling getHostName()?

OS Version:            macOS 14.4.1 (23E224)

Crash at:
0x10246dcec pcpp::SSLServerNameIndicationExtension::getHostName() const + 44

**Comment by tigercosmos** [comment]
Not sure why `getData` got a `nullptr`, but we do need to check if it is `nullptr` in `getHostName`.

**Comment by tigercosmos** [comment]
just notice that it's already addressed in https://github.com/seladb/PcapPlusPlus/pull/1377
