### ISSUE TITLE
Find alternative package for netifaces 

### ISSUE THREAD

**Issue by zhengfeihe** [seladb/PcapPlusPlus#1384]
I found `netifaces` package is no longer under maintained since python3.9 , detailed info here: https://github.com/al45tair/netifaces/issues/78. Some other projects have moved to using other packages, eg `psutil`: https://github.com/ros2/ros2cli/pull/875

Maybe we can also move to using other under maintained, reliable packages as well.

**Comment by zhengfeihe** [comment]
I'd like to work on this after I finish my current pr.

**Comment by seladb** [comment]
@zhengfeihe are you still planning to work on this?

**Comment by seladb** [comment]
By the way, there is this project: https://github.com/SamuelYvon/netifaces-2

But I'm not sure it'll work well on FreeBSD: https://github.com/SamuelYvon/netifaces-2/issues/36

**Comment by tigercosmos** [comment]
FreeBSD can be treated as a special case, I guess.

**Comment by seladb** [comment]
> FreeBSD can be treated as a special case, I guess.

Maybe... or we can try to fix this package to work with FreeBSD, or we can choose another library 🙂

**Comment by zhengfeihe** [comment]
> @zhengfeihe are you still planning to work on this?

Yes.. Just got delayed onmy current pr. I will start working on this soon.

**Comment by tigercosmos** [comment]
@zhengfeihe  I think you might want to work on this, going to assign you.

**Comment by zhengfeihe** [comment]
> @zhengfeihe I think you might want to work on this, going to assign you.

Thanks! I already started.

**Comment by tigercosmos** [comment]
As we need to support Ubuntu24.04, this issue seems to become critical at the moment.
Some error happens in the CI of the PR #1486: [Log](https://github.com/seladb/PcapPlusPlus/actions/runs/9825638625/job/27126039912)

**Comment by tigercosmos** [comment]
@zhengfeihe  please confirm if you can submit the PR for this by today; otherwise, I am sorry that I have to unassign you and take over this issue.

**Comment by zhengfeihe** [comment]
> @zhengfeihe please confirm if you can submit the PR for this by today; otherwise, I am sorry that I have to unassign you and take over this issue.

I will submit the pr by the end of the day.

**Comment by tigercosmos** [comment]
addressed in https://github.com/seladb/PcapPlusPlus/pull/1489
