### ISSUE TITLE
Transfer this repository into PcapPlusPlus GitHub organization

### ISSUE THREAD

**Issue by Neustradamus** [seladb/PcapPlusPlus#1388]
Dear @seladb, @PcapPlusPlus team,

It is possible to move https://github.com/seladb/PcapPlusPlus into the PcapPlusPlus organization like other repositories?
- https://github.com/PcapPlusPlus

It will be better for this project.

Thanks in advance.

**Comment by seladb** [comment]
@Neustradamus thanks for this suggestion! I've considered it in the past, but the current link appears in too many places and I think it'd be painful to move the project to the PcapPlusPlus organization. There isn't any harm in keeping it under my user, am I wrong?

**Comment by tigercosmos** [comment]
@seladb GitHub will redirect the URL if you transfer the owner, so you don't need to worry about this. 

Nevertheless, it's fine to put the project under a personal name, but sometimes people will be confused because there is an organization using the same name as the project name.

**Comment by seladb** [comment]
Thanks @tigercosmos I didn't know that! Still, people might get confused if they get automatically redirected... 

Maybe I need to think about it a bit more because it's a pretty big change 🙂

**Comment by seladb** [comment]
@Neustradamus I prefer not to do it at the moment, maybe we'll re-consider sometime in the future

**Comment by Neustradamus** [comment]
@seladb: This ticket is not solved, please reopen this ticket.

**Comment by tigercosmos** [comment]
@Neustradamus No, it is clear that we don't move the project under the organization.

**Comment by seladb** [comment]
@Neustradamus I closed it as not planned which is more accurate. Thanks for the insight!

**Comment by Neustradamus** [comment]
@seladb: Can you remove the @PcapPlusPlus organization in this case?

**Comment by Neustradamus** [comment]
I do not understand, why there is a repository at another place instead of all at one good place.

**Comment by tigercosmos** [comment]
@seladb  One thing is different, for example, you cannot have a "testing" repo yourself. For example, last time I contributed to a GitHub issue template that needed a master branch to experiment. Therefore, the drawback is that you cannot do any aggressive testing on the current repo.

**Comment by seladb** [comment]
But you can do it on your own fork, that's how we actually tested the GitHub template. Shouldn't this be enough? 🤔

**Comment by tigercosmos** [comment]
@seladb you didn't get my point, I meant you cannot experiment yourself if you want to do some similar testing. So only the owner of the repo matters. Anyway, I just want to share one point of view of the drawbacks.

**Comment by Neustradamus** [comment]
@seladb: Have you progressed on it?

**Comment by seladb** [comment]
@Neustradamus I don't think I'd like to pursue this at the moment

**Comment by Neustradamus** [comment]
@seladb: I have edited the main description with all details.

It takes few seconds to do and redirections will be here, and all will be in one place?

**Comment by seladb** [comment]
Thanks @Neustradamus ! Let me think about it a bit more.
Is there an advantage of moving it to an org instead under my user, other than having the web-site and the repo in the same place? 🤔

**Comment by Neustradamus** [comment]
@seladb: First, organization already exists, so it is very easy (one step less which takes 15s).
Better management for you, better visibility, ...
People will be not lost between different places and all old redirections will be here.
You commits will be shown in your personal profile and the organization will be showed.
You can pin the repositories too.
...

2 years ago, @egecetin has done a good screenshot.

Personally, I do not understand, how it is possible to use for the SAME project, different places currently... but it will be solved if you take few seconds to transfer...

**Comment by Neustradamus** [comment]
PS: Do not forget to update the organization with description, links, and to verify the org...

**Comment by Neustradamus** [comment]
@seladb: Have you seen the @egecetin screenshot here (2024-05-07):
- https://github.com/seladb/PcapPlusPlus/issues/1388#issuecomment-2097650853

@tigercosmos has done a comment here (2024-05-07):
- https://github.com/seladb/PcapPlusPlus/issues/1388#issuecomment-2097602720

Have you progressed on it?
