### ISSUE TITLE
Use data in a package captured by PcapPlusPlus

### ISSUE THREAD

**Issue by larsvlent** [seladb/PcapPlusPlus#139]
I have a question about the rawdata in pcap++.
In python I made a prove of concept for reading a pcap file and used information which is send in the data part of a packet. In pyton I used struct.unpack("xxx", raw_data), but in c++ this is not possible but I thought this has to be possible in PcapPlusPlus, right? I just don't know how.
With rawPacket.getRawData() or getRawDataReadOnly() I can see a nice overview what is inside. However, is it possible to use the data which is inside a package like I did in python? (Hex data, see second screen capture)
I hope someone can help me with this

Python code
![python_struct_code](https://user-images.githubusercontent.com/38524841/46869689-e6bf9c00-ce2c-11e8-80cb-9f0b489302d4.PNG)

Wireshark capture
![data_wireshark](https://user-images.githubusercontent.com/38524841/46869860-5766b880-ce2d-11e8-8e7b-293f03862704.PNG)

**Comment by larsvlent** [comment]
I want to read the data which is send by UDP (screenshot from wireshark), it will give data like rotation and distance. With this data the system should make some decisions. The rotation and distance are given in 2x 2hex values (FF FF for instance). So the program has to read that data from the pcap file and convert it to a decimal value and then some action will follow.
The following code is a part of the code I have, I'm now printing rawPacket, but I don't know how to print it correctly or to convert it to the decimal value's (the standard hex/dec commands don't work), because this way only a few hex data is correct converted to decimal value's. Should rwpkt maybe not be an integer? Or should I not take rawPacket but something else?

rwpkt2 and rwpkt3 contains rotation data and rwpkt4 and 5 contains distance data. 2&3 and 4&5 etc has to be switched in order so the order will be rwpkt 3, rwpkt2, rwpkt 5, rwpkt4, etc.. And then this data has to be converted from hex to decimal and then the program will do things with the decimal value's.

`	int rwpkt0, rwpkt1, rwpkt2, rwpkt3;
	int rwpkt4, rwpkt5, rwpkt6, rwpkt7;

	while (reader->getNextPacket(rawPacket) && packetCountSoFar != packetCount)
	{
		// parse the raw packet into a parsed packet
		pcpp::Packet parsedPacket(&rawPacket);

		// print packet to string
		std::cout << std::endl << parsedPacket.toString() <<
				  std::endl << rawPacket.getRawDataLen() <<
				  std::endl;

		std::cout << rawPacket.getRawDataReadOnly() << std::endl;
		std::cout << rawPacket.getRawData() <<std::endl;

		for(int i = 0; i<12; i++){
			rwpkt0 = rawPacket.getRawDataReadOnly()[i*100+0+42];
			rwpkt1 = rawPacket.getRawDataReadOnly()[i*100+1+42];
			rwpkt2 = rawPacket.getRawDataReadOnly()[i*100+2+42];
			rwpkt3 = rawPacket.getRawDataReadOnly()[i*100+3+42];
			rwpkt4 = rawPacket.getRawDataReadOnly()[i*100+4+42];
			rwpkt5 = rawPacket.getRawDataReadOnly()[i*100+5+42];
			rwpkt6 = rawPacket.getRawDataReadOnly()[i*100+6+42];
			rwpkt7 = rawPacket.getRawDataReadOnly()[i*100+7+42];
			std::cout << "BEGIN" << std::endl <<
					rwpkt0 << std::endl <<
					rwpkt1 << std::endl <<
					rwpkt2 << std::endl <<
					rwpkt3 << std::endl <<
					rwpkt4 << std::endl <<
					rwpkt5 << std::endl <<
					rwpkt6 << std::endl <<
					rwpkt7 << std::endl <<
					"END" << std::endl;
		}

		packetCountSoFar++;
	}`
The output I get:
![screenshot from 2018-10-15 07-44-07](https://user-images.githubusercontent.com/38524841/46932058-36c97900-d04e-11e8-9e28-0faa1daf1cd6.png)

**Comment by larsvlent** [comment]
I think I already figured it out. Thank you anyway for making this 👍

**Comment by tylerccg** [comment]
larsvlent, did you ever get the data decoded into something usable like UTF8?

**Comment by tylerccg** [comment]
> I already figured it out. Thank you anyway for making this

larsvlent, did you ever get the data decoded into something usable like UTF8?
