### ISSUE TITLE
Introduce GitHub issue template

### ISSUE THREAD

**Issue by tigercosmos** [seladb/PcapPlusPlus#1407]
We can introduce GitHub issue template.

For example, CPython has already introduced this feature. https://github.com/python/cpython/tree/main/.github/ISSUE_TEMPLATE

We can have templates for questions, bug reports, feature requests, etc.

The following are the screenshots from CPython GitHub issue pages:

![image](https://github.com/seladb/PcapPlusPlus/assets/18013815/f28eb931-31ee-4b39-8076-d2f6ca8c2f0d)

![image](https://github.com/seladb/PcapPlusPlus/assets/18013815/8ae86247-552e-4665-92f4-1c11419071e7)

**Comment by seladb** [comment]
Sure, we can create an issue template, I think we should keep it simple so it'd be easy to open an issue.

So you have a suggestion of such template?

**Comment by tigercosmos** [comment]
I think we can start with a few templates first. Maybe just "Bug", "Feature Request", and "Question". I will find time to work on it.

**Comment by egecetin** [comment]
Fixed with #1413
