### ISSUE TITLE
Unnecessary SomeIpSdLayer API dependency to 3rd party header EndianPortable.h

### ISSUE THREAD

**Issue by rahagal** [seladb/PcapPlusPlus#1435]
The SomeIpSdLayer header has an unnecessary dependency towards the 3rd party header EndianPortable.h - which is not part of the deployed headers with PcapPlusPlus package. thus creating a problem for the user of SomeIpSdLayer API
see https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/header/SomeIpSdLayer.h#L3

This include line can be moved to the SomeIpSdLayer.cpp file - as in the other Layers implementation.

I will gladly create a PR with this adaptation according to your feedback.

Thanks! :)

**Comment by tigercosmos** [comment]
@rahagal  thanks for reporting this. feel free to open a PR :)

**Comment by seladb** [comment]
Good catch @rahagal , thanks for reporting it! This is indeed a bug, we'd really appreciate if you can open a PR with the fix

**Comment by seladb** [comment]
Thank you so much @rahagal for the quick fix, much appreciated! 🙏
