### ISSUE TITLE
Support DESTDIR

### ISSUE THREAD

**Issue by rkeene** [seladb/PcapPlusPlus#145]
The current "install" target of the Makefile does not respect the DESTDIR environment variable.  This is very useful for creating packages.

**Comment by seladb** [comment]
I can definitely add that, but isn't the `--install-dir` parameter that exists in `configure-linux.sh` and `configure-mac_os_x.sh` enough?

**Comment by rkeene** [comment]
No, because those options record the specified directory in places.  The DESTDIR directory only exists at packaging time, and not at run-time.

**Comment by seladb** [comment]
I'm not sure I'm following you. The `--install-dir` parameter allows the user to configure PcapPlusPlus to install in a custom folder. For example: let's say you want to install PcapPlusPlus in `/my/install/folder` on a Linux machine. Here are the steps you need to run:
```
seladb@seladb:~/PcapPlusPlus$ ./configure-linux.sh --default --install-dir /my/install/folder

****************************************
PcapPlusPlus Linux configuration script 
****************************************

Number of arguments: 3

PcapPlusPlus configuration is complete. Files created (or modified): mk/platform.mk, mk/PcapPlusPlus.mk, mk/install.sh, mk/uninstall.sh

seladb@seladb:~/PcapPlusPlus$ make
...
...

seladb@seladb:~/PcapPlusPlus$ make install
Installation complete!
```

**Comment by seladb** [comment]
Any updates on that?

**Comment by seladb** [comment]
I'll close this issue for now, please reopen it if needed
