### ISSUE TITLE
DNS MX records parsing

### ISSUE THREAD

**Issue by jhilgert** [seladb/PcapPlusPlus#149]
It seems like the getDataAsString() method for an MX record fails when the preference contains a "0x00" value. In this case the returned string has a length of zero. Examples for this can be seen in [this pcap](https://giantpanda.gtisc.gatech.edu/malrec/pcap/0b9f7916-bfa5-41c7-9366-c41a6d04ec25.pcap) in paket 2256 (`udp.dstport eq 61302`). 

What about converting the preference integer to a hex string representation of the number e.g. "0x0000MAILSERVER.COM"? Or do you got any other idea?

**Comment by seladb** [comment]
Thanks for reporting this issue! Could you please resend the link for the 2 pcap files? I can't open them (both links don't work)

**Comment by jhilgert** [comment]
Oh sorry they should work now, I just updated the links in the posts.

**Comment by seladb** [comment]
Thanks, I'll take a look and let you know

**Comment by seladb** [comment]
I came up with a new design for DNS records data that should fix this. Please give me a couple of days to complete the implementation and tests and I'll push it to master

**Comment by seladb** [comment]
Fixed this issue. You can now get MX data from the DNS RR object. For example:

```
pcpp::DnsResource* dnsAnswer = dnsLayer->getFirstAnswer();
printf("MX data: %s\n", dnsAnswer->getData()->toString().c_str()); // for MX RRs it will return a string in the format of: 'pref: {preference_value}; mx: {mail_exchange_hostname_value}'
printf("Preference data: %d\n", dnsAnswer->getData()->castAs<MxDnsResourceData>()->getMxData().preference)
printf("MX hostname: %s\n", dnsAnswer->getData()->castAs<MxDnsResourceData>()->getMxData().mailExchange.c_str());
```
