### ISSUE TITLE
PcapLiveDevice stores IP addresses in structured that may be overwritten.

### ISSUE THREAD

**Issue by Dimi1010** [seladb/PcapPlusPlus#1499]
During initialization of `PcapLiveDeviceList` information of all devices is fetched via `pcap_findalldevs`. This information is used to populate `PcapLiveDevice` objects and then the list is freed. This results in an issue as the device instance holds its IP address information in `pcap_addr_t` structs that are technically dangling, but still working somehow.

The fix to this issue will be implemented as a two stage process.
- [x] Add new getter that returns `std::vector<IPAddress>` for all IP addresses and deprecate `PcapLiveDevice::getAddresses` as that returns a :vector of `pcap_addr_t` structs.
(#1500)
- [x] Remove `PcapLiveDevice::getAddresses` and refactor `PcapLiveDevice` to hold its IP information in a vector of `IPAddress` objects. (#1497)

**Comment by seladb** [comment]
This issue was fixed in #1500

**Comment by Dimi1010** [comment]
> This issue was fixed in #1500

It hasn't been fixed. That was only Task 1.
The underlying IP is still stored in `pcap_addr_t` which I can't remove until `PcapLiveDevice::getAddresses()` is removed.

**Comment by Dimi1010** [comment]
Fixed by #1497
