### ISSUE TITLE
Android fail to open wlan0

### ISSUE THREAD

**Issue by ArkhamKn1ght** [seladb/PcapPlusPlus#1511]
### Question

Hello!
I'm trying to use pcap++ with android. I build it using QT 6.5.3, NDK 25, Android API 30 on rooted device in permissive mode.

So, the problem is in this:
```cpp
pcpp::PcapLiveDeviceList::getInstance().getPcapLiveDeviceByName("wlan0");
```

This method tries to gets instance of wlan0 . Then I try to use it like this:
```cpp
if (!dev->open())
    {
        std::cout << "Cannot open device" << std::endl;
        return 1;
    }
   ```
But the problem is, it always fails to open device.
Any ideas to fix it?
I'm thinking about monitor mode, but the thing is, when I enable monitor mode for wlan0, it stops being an live device and goes into read-only state.

### Operating systems

Android

**Comment by tigercosmos** [comment]
Is this issue related to [this](https://github.com/seladb/PcapPlusPlus/issues/1509#issuecomment-2252404089)? Do you mean the device cannot be opened even with permissive mode?

**Comment by ArkhamKn1ght** [comment]
@tigercosmos Only implicitly.
My actions:
Build libpcap -> build pcap++ -> enable permissive mode -> enable monitor mode via `adb` under `su` using
```
ip link set wlan0 down
echo "4" > /sys/module/wlan/parameters/con_mode
ip link set wlan0 up
```
-> try to get live device by its name -> fail to get the device

This is if out wlan0 in monitor mode. If I enable monitor mode like this, wi-fi turns off, and stops being a live device. But monitor mode works just fine, airodump-ng works fine

If we skip enabling monitor mode, we can acquire the wlan0 live device, but we cant open it

**Comment by seladb** [comment]
@ArkhamKn1ght rooted Android devices in uncharted territory for me, so I'm not sure I can help. PcapPlusPlus is mostly a wrapper on top of libpcap. It'd be useful to debug it further and understand the error coming from libpcap, then go from there

**Comment by tigercosmos** [comment]
Yes, I would suggest to use libpcap to test first. If libpcap can work, PcapPlusPlus will probably be fine.

**Comment by ArkhamKn1ght** [comment]
Doing a bit of research, it turns out, that it's the problem on pcap++ side. Libpcap reads network interface perfectly!
Maybe it has something to do with with this implementation of getting the device?

```cpp
PcapLiveDevice* PcapLiveDeviceList::getPcapLiveDeviceByName(const std::string& name) const
{
	PCPP_LOG_DEBUG("Searching all live devices...");
	auto devIter = std::find_if(m_LiveDeviceList.begin(), m_LiveDeviceList.end(),
								[&name](const std::unique_ptr<PcapLiveDevice>& dev) { return dev->getName() == name; });

	if (devIter == m_LiveDeviceList.end())
	{
		PCPP_LOG_DEBUG("Found no live device with name '" << name << "'");
		return nullptr;
	}

	return devIter->get();
}
```
Basically we look for live device in list, but the thing is, on qualcomm provided `wlan0` network interface, this "interface" wont be live, but it actually works in monitor mode. Is it possible to add fix for this? Or add something that would allow us to create pcap++ device from libpcap device?

**Comment by ArkhamKn1ght** [comment]
```cpp
char *dev;
  char errbuf[300];
  pcap_t *handle;

  // Find a network device to sniff on
  dev = argv[1];
  printf("Device: %s\n", dev);

  // Open the device for sniffing
  handle = pcap_open_live(dev, BUFSIZ, 1, 1000, errbuf);
  if (handle == NULL) {
      fprintf(stderr, "Couldn't open device %s: %s\n", dev, errbuf);
      return 2;
  }

  // Start packet capture
  pcap_loop(handle, -1, packet_handler, NULL);
  // Close the handle
  pcap_close(handle);
  ```
  This code open not live network interface in monitor mode on android qualcomm `wlan0`

**Comment by tigercosmos** [comment]
`pcap_open_live` opens a non-live interface... cool..

Could you reproduce the issue on another Android?
Also, could you try adding this line to your program and paste the log here?
```
pcpp::Logger::getInstance().setAllModulesToLogLevel(pcpp::Logger::Debug);
```

**Comment by seladb** [comment]
@ArkhamKn1ght I'm not sure I follow: here is the code that finds all live devices: 
https://github.com/seladb/PcapPlusPlus/blob/master/Pcap%2B%2B/src/DeviceUtils.cpp

As you can see we call libpcap's `pcap_findalldevs()` to get all live devices, then [this code](https://github.com/seladb/PcapPlusPlus/blob/d21c05ccf8cd039a8faef77de02e2f7d7e1549b4/Pcap%2B%2B/src/PcapLiveDeviceList.cpp#L50) goes over the returned list and creates a `PcapLiveDevice` for each device.

If I understand correctly, you say that `pcap_findalldevs()` can't find `wlan0`, but `pcap_open_live()` can still open it?
This sounds a bit weird to me... 🤔

**Comment by ArkhamKn1ght** [comment]
@tigercosmos I don't exactly need to reproduce it on another android, since production device will be supplied with my app.

This snippet: 
```cpp
dev = argv[1];
  printf("Device: %s\n", dev);
  pcpp::PcapLiveDevice* dev1 = pcpp::PcapLiveDeviceList::getInstance().getPcapLiveDeviceByName(dev);
  if (dev1 == NULL)
  {
      printf("Couldn't find interface with name of: %s\n", dev);
  }
  // Open the device for sniffing
  handle = pcap_open_live(dev, BUFSIZ, 1, 1000, errbuf);
  if (handle == NULL) {
    printf("Couldn't open device %s\n", dev);
    return 2;
  } else {
    printf("Successfully opened device %s\n", dev);
      return 3;
  }
  ```
  Results in the following output:
  `"Device: wlan0 Couldn't find interface with name of: wlan0 Successfully opened device wlan0 "` on android by running bin file with provided snippet as part of `int main()` inside
  
 running `adb shell su - c ip link` results in this:
 
![image_2024-08-02_101911204](https://github.com/user-attachments/assets/16d8457f-06f2-421d-96ef-7995e06e6e1b)

**Comment by ArkhamKn1ght** [comment]
> @ArkhamKn1ght I'm not sure I follow: here is the code that finds all live devices: https://github.com/seladb/PcapPlusPlus/blob/master/Pcap%2B%2B/src/DeviceUtils.cpp
> 
> As you can see we call libpcap's `pcap_findalldevs()` to get all live devices, then [this code](https://github.com/seladb/PcapPlusPlus/blob/d21c05ccf8cd039a8faef77de02e2f7d7e1549b4/Pcap%2B%2B/src/PcapLiveDeviceList.cpp#L50) goes over the returned list and creates a `PcapLiveDevice` for each device.
> 
> If I understand correctly, you say that `pcap_findalldevs()` can't find `wlan0`, but `pcap_open_live()` can still open it? This sounds a bit weird to me... 🤔

Yep, that is EXACTLY what I mean

**Comment by ArkhamKn1ght** [comment]
![image](https://github.com/user-attachments/assets/5cac4d9b-1797-4414-ae81-57c08afd5b10)
:)
Modules is incorrect, but `modles`...
`pcpp::Logger::getInstance().setAllModlesToLogLevel(pcpp::Logger::LogLevel::Debug);`

**Comment by seladb** [comment]
Hmm there seems to be an issue in libpcap then 🤔 
From [their documentation](https://www.tcpdump.org/manpages/pcap_findalldevs.3pcap.html), it seems that `pcap_findalldevs()` should find all devices that can be opened with `pcap_open_live()`:


> pcap_findalldevs() constructs a list of network devices that can be opened with [pcap_create](https://www.tcpdump.org/manpages/pcap_create.3pcap.html)(3PCAP) and [pcap_activate](https://www.tcpdump.org/manpages/pcap_activate.3pcap.html)(3PCAP) or with [pcap_open_live](https://www.tcpdump.org/manpages/pcap_open_live.3pcap.html)(3PCAP). (Note that there may be network devices that cannot be opened by the process calling pcap_findalldevs(), because, for example, that process does not have sufficient privileges to open them for capturing; if so, those devices will not appear on the list.)

Maybe the process that initiates PcapPlusPlus doesn't have sufficient privileges to open this device, but the process that calls `pcap_open_live` does?

Maybe you can try to call `pcpp::PcapLiveDeviceList::getInstance().reset()` from the same context where you call `pcap_open_live` and see if the device is found?

**Comment by ArkhamKn1ght** [comment]
@seladb bear in mind, that i'm dealing with rooted android device, where monitor mode for network interface provided `as is`, meaning, it's mostly by workarounds I get access to it's packets. But the fact that libpcap can open it, and pcap++ can't, somewhat saddens me. 

About privileges:
It's **impossible**. The whole main block is running under `su` in android shell. Without `su` even `libpcap` cant open the device, since it requires usage of raw sockets, I guess. 
Is it possible for you to patch pcap++ and implement some sort of direct opening, without finding a device and parsing the list of devices? Something that get name as an argument and then directly tries to open it by using libpcap?

**Comment by seladb** [comment]
@ArkhamKn1ght it seems like an issue in libpcap, no?
I'd explore more to understand why it happens, maybe there is a way to make it work...

Anyway, it's not impossible to do what you ask, but it'll break the existing design because we can't create `PcapLiveDevice` without the information returned from `pcap_findalldevs()`. Of course we can implement an "ad-hoc" `PcapLiveDevice` but I don't think it's something that aligns with the current design and will benefit other PcapPlusPlus users. To be honest, I've never heard of this issue before (and I know people use PcapPlusPlus with rooted Android devices) so I assume not a lot of people need this functionality.

If you can't find any workaround for libpcap, maybe you can use libpcap to capture packets, and then pass the raw data to PcapPlusPlus to do the packet parsing etc.

**Comment by ArkhamKn1ght** [comment]
@tigercosmos  @seladb 
Logs:
```
 "Device: wlan0 [DEBUG:  init:49] Pcap lib version info: libpcap version 1.10.4 (with TPACKET_V3) 
[DEBUG:  PcapLiveDevice:78] Added live device: name=any; desc=Pseudo-device that captures on all interfaces 
[DEBUG:  PcapLiveDevice:79]    Addresses: 
[DEBUG:  setDeviceMtu:758] Error in retrieving MTU: ioctl() returned -1 
[DEBUG:  PcapLiveDevice:95]    MTU: 0 
[DEBUG:  PcapLiveDevice:101]    Default Gateway: 0.0.0.0 "
 "[DEBUG:  setDeviceMacAddress:814] Error in retrieving MAC address: ioctl() returned -1 
[DEBUG:  PcapLiveDevice:78] Added live device: name=lo; desc= 
[DEBUG:  PcapLiveDevice:79]    Addresses: 
[DEBUG:  PcapLiveDevice:95]    MTU: 65536 
[DEBUG:  PcapLiveDevice:101]    Default Gateway: 0.0.0.0 
[DEBUG:  PcapLiveDevice:124]    MAC addr: 00:00:00:00:00:00 
[DEBUG:  PcapLiveDevice:78] Added live device: name=nflog; desc=Linux netfilter log (NFLOG) interface 
[DEBUG: 
 "[DEBUG:  PcapLiveDevice:79]    Addresses: 
        [DEBUG:  setDeviceMtu:758] Error in retrieving MTU: ioctl() returned -1 
        [DEBUG:  PcapLiveDevice:95]    MTU: 0 
        [DEBUG:  PcapLiveDevice:101]    Default Gateway: 0.0.0.0 
        [DEBUG:  setDeviceMacAddress:814] Error in retrieving MAC address: ioctl() returned -1 "
 "[DEBUG:  setDnsServers:112] Error retrieving DNS server list: nmcli doesn't exist "
 "[DEBUG:  init:65] Freeing live device data "
 "[DEBUG:  init:49] Pcap lib version info: libpcap version 1.10.4 (with TPACKET_V3) 
[DEBUG:  PcapLiveDevice:78] Added live device: name=any; desc=Pseudo-device that captures on all interfaces 
[DEBUG:  PcapLiveDevice:79]    Addresses: 
[DEBUG:  setDeviceMtu:758] Error in retrieving MTU: ioctl() returned -1 
[DEBUG:  PcapLiveDevice:95]    MTU: 0 
[DEBUG:  PcapLiveDevice:101]    Default Gateway: 0.0.0.0 
[DEBUG:  setDeviceMacAddress:814] Error in retrieving MAC address: ioctl() retu
 "[DEBUG:  setDnsServers:112] Error retrieving DNS server list: nmcli doesn't exist 
[DEBUG:  init:65] Freeing live device data 
[DEBUG:  getPcapLiveDeviceByName:318] Searching all live devices... "
 "Couldn't find interface with name of: wlan0 Successfully opened device wlan0 "
```

**Comment by ArkhamKn1ght** [comment]
> @ArkhamKn1ght it seems like an issue in libpcap, no? I'd explore more to understand why it happens, maybe there is a way to make it work...
> 
> Anyway, it's not impossible to do what you ask, but it'll break the existing design because we can't create `PcapLiveDevice` without the information returned from `pcap_findalldevs()`. Of course we can implement an "ad-hoc" `PcapLiveDevice` but I don't think it's something that aligns with the current design and will benefit other PcapPlusPlus users. To be honest, I've never heard of this issue before (and I know people use PcapPlusPlus with rooted Android devices) so I assume not a lot of people need this functionality.
> 
> If you can't find any workaround for libpcap, maybe you can use libpcap to capture packets, and then pass the raw data to PcapPlusPlus to do the packet parsing etc.

thats the base design.
About `libpcap`, I dont really think that its an issue, really. `ip link` shows the interface and it works. `airodump-ng` manages to collect packets, I can open raw sockets in C, `libpcap` can open the device. The issues is, that device is not listed as live, since android shell kind of `disables` it, when you turn the monitor mode on, but the interface actually listens to the channel you set using `iw dev`.

**Comment by seladb** [comment]
> thats the base design.
> About `libpcap`, I dont really think that its an issue, really. `ip link` shows the interface and it works. `airodump-ng` manages to collect packets, I can open raw sockets in C, `libpcap` can open the device. The issues is, that device is not listed as live, since android shell kind of `disables` it, when you turn the monitor mode on, but the interface actually listens to the channel you set using `iw dev`.

Is there a way to get the device info from libpcap? Maybe a different method which is not `pcap_findalldevs()` and can "see" disabled devices?
If we can find a way, then maybe we can do something to enhance `PcapLiveDeviceList` to accept devices outside of `pcap_findalldevs()`, but otherwise the only way is to create a non-private c'tor for `PcapLiveDevice` which asks the user for the data gathered by `pcap_findalldevs()`, which is not something I think we want to build...

**Comment by ArkhamKn1ght** [comment]
@seladb I have never actually tried to get the device info, since `pcap_open_live` opens the device, hence - no need for additional data.

**Comment by ArkhamKn1ght** [comment]
@seladb crafting my own rawpackets proved to be a working concept:
```cpp
void packet_handler(u_char *user_data, const struct pcap_pkthdr *pkthdr, const u_char *packet) {
    uint8_t* packetData = new uint8_t[pkthdr->caplen];
	  memcpy(packetData, packet, pkthdr->caplen);
    pcpp::RawPacket* rawPacketPtr = new pcpp::RawPacket(packetData, pkthdr->caplen, pkthdr->ts, true);
    pcpp::Packet parsedPacket(rawPacketPtr);
    
    stats.consumePacket(parsedPacket);
    for (pcpp::Layer* curLayer = parsedPacket.getFirstLayer(); curLayer != NULL; curLayer = curLayer->getNextLayer()) {
      printf("\n====DATA BEGIN====\n");
      printf("String: %s\n", curLayer->toString().c_str());
      printf("Total data: %d\n", curLayer->getDataLen());
      printf("Layer data: %d\n", curLayer->getHeaderLen());
      printf("Layer payload: %d\n", curLayer->getLayerPayloadSize());
      printf("====DATA END====\n");
      }
}
```
![image](https://github.com/user-attachments/assets/d6c693cc-b8e0-4ef2-986f-e8bfdbfb6bc0)

**Comment by seladb** [comment]
@ArkhamKn1ght nice!!

Let us know if we should close this issue

**Comment by tigercosmos** [comment]
Sorry, I think I didn't catch up.., so how did you resolve the issue, and what's is the potential issue in PCPP?

**Comment by ArkhamKn1ght** [comment]
> @ArkhamKn1ght nice!!
> 
> Let us know if we should close this issue

Not just yet. Why do I get only IEEE 802.3 layers? When I specify anything 802.11 related in pcpp::RawPacket(packetData, pkthdr->caplen, pkthdr->ts, true, <LINKTYPE>), i only get the payload.

**Comment by ArkhamKn1ght** [comment]
@tigercosmos pcpp checks for live devices before opening one. My device is not so much live, so it throws it away, but pcap_open_live opens the device perfectly

**Comment by ArkhamKn1ght** [comment]
Thanks for the help, issue closed
