### ISSUE TITLE
How to craft packet out of raw data?

### ISSUE THREAD

**Issue by ArkhamKn1ght** [seladb/PcapPlusPlus#1522]
### Question

I'm receiving raw-raw-raw data (literally just bytes, nothing more) from `wlan0` network interface. How do I craft packets from it using pcap++? PCAP++ tutorial only instructs how to process packets that were captured by pcap++ methods, where's I receive packets by raw C-style socket.

**Comment by tigercosmos** [comment]
@ArkhamKn1ght If you use wireshark or tcpdump, you can save them as pcap file, which will be easier. However, if you want to load them as raw binary, you can search `READ_FILE_AND_CREATE_PACKET` keyword in the "Tests" directory, which might be helpful for your question.

**Comment by seladb** [comment]
To expand on what @tigercosmos , here is the code I think you're looking for:

```cpp
uint8_t* buffer; // your byte array
size_t bufferLength; // your byte array length

// create a raw packet which is basically a wrapper over the byte array
pcpp::RawPacket rawPacket(buffer, bufferLength, time, true);

// create a parsed packet out of the raw data
pcpp::Packet parsedPacket(&rawPacket);
```

**Comment by seladb** [comment]
@ArkhamKn1ght can we close this issue?
