### ISSUE TITLE
Support millisecond resolution timeout in RawSocketDevice

### ISSUE THREAD

**Issue by rahagal** [seladb/PcapPlusPlus#1528]
Hello,
 
Is it possible to offer an enhancement to the receive() operations in the RawSocketDevice class?
It will be great to have the option to set timeout in a milliseconds resolution instead of seconds - helpful when we need to perform a lot of receive() calls with some timeout without it taking forever to perform.

will gladly create a PR with the needed adaptions :)

**Comment by Dimi1010** [comment]
Looking through the code, it should not be an issue to increase the resolution to milliseconds. At a first glance, both the [Win32](https://learn.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-setsockopt) and [Linux](https://pubs.opengroup.org/onlinepubs/007904975/functions/setsockopt.html) implementations support that resolution so it should be a minor change. Feel free to make the changes and submit a PR for review. :)

**Comment by tigercosmos** [comment]
@rahagal  Feel free to use the latest PcapPlusPlus for the feature :)

**Comment by rahagal** [comment]
Thank you for the incredibly quick support with this :)
