### ISSUE TITLE
Add WireGuard Packet Parsing Support

### ISSUE THREAD

**Issue by nadongjun** [seladb/PcapPlusPlus#1554]
@seladb I've observed that PcapPlusPlus currently does not support parsing WireGuard packets (parsing only, no decryption), which I needed for my project. To address this, I have implemented functionality to detect and parse various WireGuard message types, including Handshake Initiation, Handshake Response, Cookie Reply, and Transport Data.

I believe this addition could be valuable to PcapPlusPlus users, and I would like to contribute it. If you are open to this contribution, I would appreciate it if you could open a ticket to track the process.

**Comment by tigercosmos** [comment]
Hi @nadongjun any contribution is welcome. If your feature is too big, it is suggested to split it into multiple PRs. Since you are more familiar with the feature, feel free to open issues for your new feature, or you can reuse this issue can add more items here.

**Comment by nadongjun** [comment]
@tigercosmos Thank you for your quick response and guidance. I will work on splitting the feature into smaller PRs and will open new issues if needed.

**Comment by clementperon** [comment]
@nadongjun can we close the issue ?

**Comment by nadongjun** [comment]
@clementperon  Yes, I believe it's done. I'll go ahead and close this issue.
