### ISSUE TITLE
Apply Ruff for Python Code

### ISSUE THREAD

**Issue by tigercosmos** [seladb/PcapPlusPlus#1562]
[Ruff](https://github.com/astral-sh/ruff) is the fastest linter and formatter written in Rust for the Python code. Since we already introduce clang-format in the project for the C++ part, the next step is to start formatting and lintting on the Python side.

**Comment by seladb** [comment]
@tigercosmos do you suggest we use it instead of Black as a formatter or just for linting?

**Comment by tigercosmos** [comment]
@seladb  Ruff functions as both a formatter and a linter, and I chose it because it appears to be the fastest option. However, I'm open to discussing which tool we should use.

**Comment by tigercosmos** [comment]
@Dimi1010  @egecetin @clementperon please also share your opinions

**Comment by Dimi1010** [comment]
I don't have a strong opinion, so I am fine with either.

**Comment by egecetin** [comment]
I'm also fine with all options since the python code base is just for testing and really short in terms of line

**Comment by seladb** [comment]
I'm also okay with using it for both. It's a lot faster than Black / Pylint but we'll probably not notice it because our Python code base is very small

**Comment by tigercosmos** [comment]
Okay, all of us are fine with either tool. I will try to use Ruff first. :)

**Comment by seladb** [comment]
@tigercosmos can we close this issue?
