### ISSUE TITLE
Unable to build in MacOS Mojave

### ISSUE THREAD

**Issue by Deanseo** [seladb/PcapPlusPlus#157]
This issue comes from [my closed PR](https://github.com/seladb/PcapPlusPlus/pull/153).
For **MacOS Mojave** users, extra documentation would be appreciated for them to properly build it.

**Comment by seladb** [comment]
Thanks for opening this as an issue. What did you do to make it work?

**Comment by Deanseo** [comment]
@seladb Sorry for the late response. I've been on vacation during the lunar new years.
I have not tried tweaking the `include` path to make it work.

So far what I've tried is the closed PR.

I'll give it a shot and share it with you later.

**Comment by Deanseo** [comment]
Off-topic but I really don't see why Apple has decided to deprecate the good old default `/usr/include`, if one command liner can just *fix* it.

**Comment by seladb** [comment]
Thanks! I added the extra step: https://github.com/seladb/PcapPlusPlus-Doc/commit/42470a44c0c8c4ed98581238a92f268e82869019
