### ISSUE TITLE
How to do a deep copy of pcpp::IPAddress? 

### ISSUE THREAD

**Issue by zyl-one** [seladb/PcapPlusPlus#1571]
### Question

I want to achieve this order of execution, and to do so, I need to deep copy pcpp::IPAddress. How can I accomplish this?
```cpp
// This will be allocated using Winpcap / Npcap Packet() constructor in the callback (pcpp::Packet parsedPacket(*rawPacket,pcpp::OsiModelPresentationLayer))
pcpp::IPAddress* originalIP = new pcpp::IPAddress("192.168.1.1");

// I want to do a deep copy of the IPAddress
pcpp::IPAddress* copyIP = new pcpp::IPAddress(*originalIP);

// I will be deleting the original packet (the IPAddress also will be deleted) to save memory
delete originalIP;

// I want to access it post deletion of the original packet
std::cout << "Copied IP Address: " << copyIP->toString() << std::endl;
delete copyIP;
```

@seladb Kindly help!

### Operating systems

Windows

**Comment by Dimi1010** [comment]
> @Dimi1010 I got a **read-access violation** while accessing the copy. Can you please cross-check it?

Huh... which library version are you using, so I can check?

**Comment by zyl-one** [comment]
@Dimi1010 I am using the **v23.09** release. Thanks for your time, mate!

**Comment by Dimi1010** [comment]
@zyl-one Tested the sample code on v23.09, and it seems fine on my end. Read access violation during access makes me think there is a `nullptr` dereference. Are you sure the pointer to the copy you are using is valid?

Sample code:
```
pcpp::IPAddress* origIPAddr = new pcpp::IPAddress("192.168.1.1");

pcpp::IPAddress* copyIPAddr = new pcpp::IPAddress(*origIPAddr);

delete origIPAddr;

// I want to access it post deletion of the original packet
std::cout << "Copied IP Address: " << copyIPAddr->toString() << std::endl;

delete copyIPAddr;
```
Output:
![image](https://github.com/user-attachments/assets/5fdbb4f5-17fd-4236-8af3-6f790ef00acb)

Test System: Win 10 22H2, Npcap 1.79 Debug x64

**Comment by zyl-one** [comment]
@Dimi1010 , Can you try running it a few more times or maybe use a loop? It's actually weird, sometimes it works and sometimes it gives me this read access violation error.
 
I can't debug because I have CrowdStrike Falcon on my setup, which crashes Visual Studio on read access violation.

I'm on the same setup as you, except I'm using Windows 11. Thanks again.

**Comment by Dimi1010** [comment]
@zyl-one Ran the following a couple of times with no issues... so idk what is happening to give you access violation.

```
int main()
{ 
	for (int i = 0; i < 10000; i++)
	{
		pcpp::IPAddress *origIPAddr = new pcpp::IPAddress(i);

		pcpp::IPAddress *copyIPAddr = new pcpp::IPAddress(*origIPAddr);

		delete origIPAddr;

		// I want to access it post deletion of the original packet
		std::cout << "N:" << i << " "
				  << "Copied IP Address: " << copyIPAddr->toString() << std::endl;
		delete copyIPAddr;
	}

	return 0;
}
```

**Comment by zyl-one** [comment]
@Dimi1010 Thanks for the help. I used the = operator and it worked.
