### ISSUE TITLE
Exclude examples in release package to reduce binary size?

### ISSUE THREAD

**Issue by Doekin** [seladb/PcapPlusPlus#1593]
### Question

I was wondering if it’s necessary to include examples in the release package. Excluding them could potentially reduce the package size. Is this worth considering?

Below is a comparison of the release with examples included and the one without.

with examples
---
![图片](https://github.com/user-attachments/assets/6f3803cb-6687-443e-ba84-3aee07208317)
without examples
---
![图片](https://github.com/user-attachments/assets/cd2827bf-f424-4fdf-a7ec-6f6caabb4e8d)

**Comment by tigercosmos** [comment]
@Doekin We prefer to have examples. The size is not that big, and should be acceptable.

**Comment by Doekin** [comment]
Got it, thanks for the reply.
