### ISSUE TITLE
TCP Keep-Alive carrying data

### ISSUE THREAD

**Issue by gyl30** [seladb/PcapPlusPlus#1594]
I recently discovered an interesting phenomenon in a customer environment where TCP Keep-Alive packets appear every second or so and carry a byte of data, these Keep-Alive packets carry data that is intermingled with the normal data and can be passed through TcpReassembly. do we have a way to deal with this situation at PcapPlusPlus? Do we have a way in PcapPlusPlus to handle this situation? I have a screenshot here of Keep-Alive and HTTP data together, causing an error in HTTP parsing.
![image](https://github.com/user-attachments/assets/4a472afe-5191-4fcb-b943-0feaba23a7f9)

**Comment by gyl30** [comment]
I forgot to mention that all the TCP Keep-Alive packets I've observed in my environment carry one byte of data at 0x00.

**Comment by tigercosmos** [comment]
It sounds like an edge case. I don't know if it is general enough to modify the TcpReassembly. I also wonder if it's a bug of TcpReassembly. In this case, perhaps you may want to handle the packets yourself.

**Comment by gyl30** [comment]
Everyone who encounters this situation with PcapPlusPlus could benefit if it was handled within PcapPlusPlus. I see [here](https://serverfault.com/questions/447855/how-filter-only-keep-alive-packet-with-tcpdump)that it is possible to filter out such packets using the bpf filtering rule, but not when using dpdk Using bpf filtering rules

**Comment by seladb** [comment]
@gyl30 is there a pcap file you can share that includes this phenomenon?

**Comment by gyl30** [comment]
@seladb 
Sorry, the packet capture file involves client information that I can't provide, however, we should be able to reproduce this problem by writing a simple tcp program and setting SO_KEEP* related options

**Comment by tigercosmos** [comment]
@gyl30 I think it's possible to reproduce through a unit test. Probably you can consider providing a minimum reproducible test case.

**Comment by hidd3ncod3s** [comment]
It is a common windows behaviour
https://osqa-ask.wireshark.org/questions/44609/wireshark-tcp-keep-alive-detection/

**Comment by seladb** [comment]
> It is a common windows behaviour
> https://osqa-ask.wireshark.org/questions/44609/wireshark-tcp-keep-alive-detection/

@hidd3ncod3s there is a link to a pcapng flie, but unfortunately it's broken 😕 



> @seladb Sorry, the packet capture file involves client information that I can't provide, however, we should be able to reproduce this problem by writing a simple tcp program and setting SO_KEEP* related options

@gyl30 maybe you can write such program, record the TCP traffic, and attach a pcap file to this issue?

**Comment by gyl30** [comment]
@seladb @hidd3ncod3s @tigercosmos 
I've investigated this issue carefully and we probably can't fix it because the first packet received is a TCP Keep-Alive packet. This packet capture file reproduces the problem. Please change the filename suffix to pcapng
[Keep-Alive.zip](https://github.com/user-attachments/files/17305000/Keep-Alive.zip)

**Comment by gyl30** [comment]
> It is a common windows behaviour https://osqa-ask.wireshark.org/questions/44609/wireshark-tcp-keep-alive-detection/

Same problem, I should have caught it earlier

**Comment by seladb** [comment]
@gyl30 how come the TCP flow doesn't start with SYN? 🤔

**Comment by gyl30** [comment]
> @gyl30 how come the TCP flow doesn't start with SYN? 🤔为什么 TCP 流不以 SYN 开头？ 🤔

PcapPlusPlus works fine if you start from the SYN of the TCP stream, the problem I encountered in my client environment did not capture the SYN of the TCP stream for some unknown reason.Keep-Alive.zip was intentionally caused by me in order to reproduce the problem. I now know that this phenomenon is not a problem. This issue can be closed now.
