### ISSUE TITLE
Need help with build issue

### ISSUE THREAD

**Issue by zyl-one** [seladb/PcapPlusPlus#1605]
I am using PcapPlusPlus v23.09. My build keeps on failing. I am using CMake.
@clementperon 

cmake -A x64 -DPCAP_ROOT=d:\Webhost\04-10-2024\WindowsBuilds\My_Project\9213078\nativeftp\\My_Project\WpdPack -DPCAPPP_BUILD_TESTS=OFF -DPCAPPP_BUILD_EXAMPLES=OFF -DPCAPPP_BUILD_TUTORIALS=OFF -S d:\Webhost\04-10-2024\WindowsBuilds\My_Project\9213078\nativeftp\\My_Project\thirdparty_packages\pcapplusplus\v_23_09\PcapPlusPlus-23.09 -B d:\Webhost\04-10-2024\WindowsBuilds\My_Project\9213078\nativeftp\\My_Project\thirdparty_packages\pcapplusplus\v_23_09\PcapPlusPlus-23.09\x64Windows 
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- The CXX compiler identification is MSVC 19.40.33811.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - broken
CMake Error at D:/Python311_x64/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:60 (message):
  The C++ compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: D:/Webhost/04-10-2024/WindowsBuilds/My_Project/9213078/nativeftp/My_Project/thirdparty_packages/pcapplusplus/v_23_09/PcapPlusPlus-23.09/x64Windows/CMakeFiles/CMakeScratch/TryCompile-pg3u1r
    
    Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_f1a91.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.10.4+10fbfbf2e for .NET Framework
    Build started 04-10-2024 15:15:13.
    
    Project "D:\Webhost\04-10-2024\WindowsBuilds\My_Project\9213078\nativeftp\My_Project\thirdparty_packages\pcapplusplus\v_23_09\PcapPlusPlus-23.09\x64Windows\CMakeFiles\CMakeScratch\TryCompile-pg3u1r\cmTC_f1a91.vcxproj" on node 1 (default targets).
    PrepareForBuild:
      Creating directory "cmTC_f1a91.dir\Debug\".
      Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
      Creating directory "D:\Webhost\04-10-2024\WindowsBuilds\My_Project\9213078\nativeftp\My_Project\thirdparty_packages\pcapplusplus\v_23_09\PcapPlusPlus-23.09\x64Windows\CMakeFiles\CMakeScratch\TryCompile-pg3u1r\Debug\".
      Creating directory "cmTC_f1a91.dir\Debug\cmTC_f1a91.tlog\".
    InitializeBuildStatus:
      Creating "cmTC_f1a91.dir\Debug\cmTC_f1a91.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
      Touching "cmTC_f1a91.dir\Debug\cmTC_f1a91.tlog\unsuccessfulbuild".
    ClCompile:
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_f1a91.dir\Debug\\" /Fd"cmTC_f1a91.dir\Debug\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "D:\Webhost\04-10-2024\WindowsBuilds\My_Project\9213078\nativeftp\My_Project\thirdparty_packages\pcapplusplus\v_23_09\PcapPlusPlus-23.09\x64Windows\CMakeFiles\CMakeScratch\TryCompile-pg3u1r\testCXXCompiler.cxx"
      Microsoft (R) C/C++ Optimizing Compiler Version 19.40.33811 for x64
      Copyright (C) Microsoft Corporation.  All rights reserved.
      cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_f1a91.dir\Debug\\" /Fd"cmTC_f1a91.dir\Debug\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "D:\Webhost\04-10-2024\WindowsBuilds\My_Project\9213078\nativeftp\My_Project\thirdparty_packages\pcapplusplus\v_23_09\PcapPlusPlus-23.09\x64Windows\CMakeFiles\CMakeScratch\TryCompile-pg3u1r\testCXXCompiler.cxx"
      testCXXCompiler.cxx
    FileTracker : error FTK1011: could not create the new file tracking log file: D:\Webhost\04-10-2024\WindowsBuilds\My_Project\9213078\nativeftp\My_Project\thirdparty_packages\pcapplusplus\v_23_09\PcapPlusPlus-23.09\x64Windows\CMakeFiles\CMakeScratch\TryCompile-pg3u1r\cmTC_f1a91.dir\Debug\cmTC_f1a91.tlog\CL.read.1.tlog. The system cannot find the path specified. [D:\Webhost\04-10-2024\WindowsBuilds\My_Project\9213078\nativeftp\My_Project\thirdparty_packages\pcapplusplus\v_23_09\PcapPlusPlus-23.09\x64Windows\CMakeFiles\CMakeScratch\TryCompile-pg3u1r\cmTC_f1a91.vcxproj]
    FileTracker : error FTK1011: could not create the new file tracking log file: D:\Webhost\04-10-2024\WindowsBuilds\My_Project\9213078\nativeftp\My_Project\thirdparty_packages\pcapplusplus\v_23_09\PcapPlusPlus-23.09\x64Windows\CMakeFiles\CMakeScratch\TryCompile-pg3u1r\cmTC_f1a91.dir\Debug\cmTC_f1a91.tlog\CL.write.1.tlog. The system cannot find the path specified. [D:\Webhost\04-10-2024\WindowsBuilds\My_Project\9213078\nativeftp\My_Project\thirdparty_packages\pcapplusplus\v_23_09\PcapPlusPlus-23.09\x64Windows\CMakeFiles\CMakeScratch\TryCompile-pg3u1r\cmTC_f1a91.vcxproj]
    Done Building Project "D:\Webhost\04-10-2024\WindowsBuilds\My_Project\9213078\nativeftp\My_Project\thirdparty_packages\pcapplusplus\v_23_09\PcapPlusPlus-23.09\x64Windows\CMakeFiles\CMakeScratch\TryCompile-pg3u1r\cmTC_f1a91.vcxproj" (default targets) -- FAILED.
    
    Build FAILED.
    
    "D:\Webhost\04-10-2024\WindowsBuilds\My_Project\9213078\nativeftp\My_Project\thirdparty_packages\pcapplusplus\v_23_09\PcapPlusPlus-23.09\x64Windows\CMakeFiles\CMakeScratch\TryCompile-pg3u1r\cmTC_f1a91.vcxproj" (default target) (1) ->
    (ClCompile target) -> 
      FileTracker : error FTK1011: could not create the new file tracking log file: D:\Webhost\04-10-2024\WindowsBuilds\My_Project\9213078\nativeftp\My_Project\thirdparty_packages\pcapplusplus\v_23_09\PcapPlusPlus-23.09\x64Windows\CMakeFiles\CMakeScratch\TryCompile-pg3u1r\cmTC_f1a91.dir\Debug\cmTC_f1a91.tlog\CL.read.1.tlog. The system cannot find the path specified. [D:\Webhost\04-10-2024\WindowsBuilds\My_Project\9213078\nativeftp\My_Project\thirdparty_packages\pcapplusplus\v_23_09\PcapPlusPlus-23.09\x64Windows\CMakeFiles\CMakeScratch\TryCompile-pg3u1r\cmTC_f1a91.vcxproj]
      FileTracker : error FTK1011: could not create the new file tracking log file: D:\Webhost\04-10-2024\WindowsBuilds\My_Project\9213078\nativeftp\My_Project\thirdparty_packages\pcapplusplus\v_23_09\PcapPlusPlus-23.09\x64Windows\CMakeFiles\CMakeScratch\TryCompile-pg3u1r\cmTC_f1a91.dir\Debug\cmTC_f1a91.tlog\CL.write.1.tlog. The system cannot find the path specified. [D:\Webhost\04-10-2024\WindowsBuilds\My_Project\9213078\nativeftp\My_Project\thirdparty_packages\pcapplusplus\v_23_09\PcapPlusPlus-23.09\x64Windows\CMakeFiles\CMakeScratch\TryCompile-pg3u1r\cmTC_f1a91.vcxproj]
    
        0 Warning(s)
        2 Error(s)
    
    Time Elapsed 00:00:00.43
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:12 (project)

-- Configuring incomplete, errors occurred!

**Comment by egecetin** [comment]
@zyl-one Not sure but can you remove "." from the path try again? Maybe rename the folder or move it to a different directory?

`.....\v_23_09\PcapPlusPlus-23.09\.....` -> `.....\v_23_09\PcapPlusPlus-23_09\.....`

**Comment by zyl-one** [comment]
@egecetin The issue persists. It is not related to this -> `.....\v_23_09\PcapPlusPlus-23.09\..... -> .....\v_23_09\PcapPlusPlus-23_09\.....`

@clementperon Kindly help.

**Comment by clementperon** [comment]
@zyl-one I'm not expert in windows but regarding the warning message.
"FileTracker : error FTK1011: could not create the new file tracking log file"

I would say either you don't have the right or maybe it's stupid but can the path be too long? I know that I already trig this issue once but maybe it's fixed with recent windows.
"D:\Webhost\04-10-2024\WindowsBuilds\My_Project\9213078\nativeftp\My_Project\thirdparty_packages\pcapplusplus\v_23_09\PcapPlusPlus-23.09\x64Windows\CMakeFiles\CMakeScratch\TryCompile-pg3u1r\cmTC_f1a91.dir\Debug\cmTC_f1a91.tlog\CL.read.1.tlog"

Could you try to build in another directory or

**Comment by zyl-one** [comment]
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - broken
CMake Error at D:/Python311_x64/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:60 (message):
The C++ compiler
"C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe" 
is not able to compile a simple test program.

It fails with the following output:
Change Dir: D:/Webhost/04-10-2024/WindowsBuilds/My_Project/9213078/nativeftp/My_Project/thirdparty_packages/pcapplusplus/v_23_09/PcapPlusPlus-23.09/x64Windows/CMakeFiles/CMakeScratch/TryCompile-pg3u1r 

@clementperon I think the issue is likely the above command. Do you have any idea regarding this?

**Comment by Surya-Kumar-03** [comment]
The long size of the path was the issue. Thanks @clementperon @egecetin
