### ISSUE TITLE
detect_pcap_version.c should be a C++ file

### ISSUE THREAD

**Issue by kiwixz** [seladb/PcapPlusPlus#1606]
### Bug description

When trying to find_package PcapPlusPlus installed with vcpkg, it fails with the following:
```
CMake Error at build/vcpkg_installed/x64-linux/share/pcapplusplus/FindPCAP.cmake:113 (try_run):
  Unknown extension ".c" for file

    .../build/detect_pcap_version.c

  try_compile() works only for enabled languages.  Currently these are:

    CUDA CXX

  See project() command to enable other languages.
```

My project indeed only enable those two languages and not C.
It used to work but block my upgrade to PcapPlusPlus 24.09.

I think `detect_pcap_version.c` (introduced in 71e19fe1fbd2cc05094a152679ba4e4aa39b0aa9) should be a C++ file so it doesn't require C to be enabled.

### PcapPlusPlus versions tested on

Other (specify in the next question)

### Other PcapPlusPlus version (if applicable)

24.09

### Operating systems tested on

Linux

### Compiler version

gcc 13.2.0

**Comment by tigercosmos** [comment]
I think it's okay to make it a cpp file, feel free to open a PR. However, it will be in the next release.
Maybe you can consider adding C to your project as a workaround.

**Comment by seladb** [comment]
Fixed in https://github.com/seladb/PcapPlusPlus/pull/1607
