### ISSUE TITLE
Wrong link type in Packet::copyDataFrom()

### ISSUE THREAD

**Issue by jhilgert** [seladb/PcapPlusPlus#163]
Hey there,

we assume there is a bug in your copyDataFrom() method for packets, which is for example called when a parsed packet is handed over to another method by value. At this time copyDataFrom() creates a new m_FirstLayer which is always of type EthLayer. At this point it should actually check the underlying link type just like setRawPacket does, so that Linux cooked headers are correctly created.

Best wishes,
Jan

**Comment by seladb** [comment]
I agree, it seems like a bug. The right behavior would probably be to mimic the behavior of [Packet::setRawPacket()](https://github.com/seladb/PcapPlusPlus/blob/54527f6b4d62f59f22e0ccc030bd37f986c3430f/Packet%2B%2B/src/Packet.cpp#L54) and create the correct first layer. Would you mind suggesting a fix and submit a PR?

**Comment by jhilgert** [comment]
Okay, you were faster! I will give it a try, but I assume this fixes the problems we had. Will give it a try.

**Comment by seladb** [comment]
This is still in `dev` branch, I'm waiting for the CI to finish running and then I'll merge it to `master`

**Comment by jhilgert** [comment]
Awesome, thank you. Our problems were fixed by 81fe59914f97850b0276fe393fa6703e6318a8cd.

**Comment by seladb** [comment]
Cool, thanks for the feedback! I've merged it into `master` so you can take the code from there. I'll close the issue now, please reopen it if you see any issue
