### ISSUE TITLE
bpf/xsk.h file not found

### ISSUE THREAD

**Issue by Baruch-Fridman** [seladb/PcapPlusPlus#1635]
https://github.com/seladb/PcapPlusPlus/blob/35f486cfa677c4a11a9d3742d7f32ab51da9870e/Pcap%2B%2B/src/XdpDevice.cpp#L8C1-L8C21
Didn't this file move to libxdp and should be under xdp/xsk?

**Comment by seladb** [comment]
Do you have `libbpf-dev` installed?
Please take a look at our CI to see how to install libbpf: https://github.com/seladb/PcapPlusPlus/blob/35f486cfa677c4a11a9d3742d7f32ab51da9870e/.github/workflows/build_and_test.yml#L697

**Comment by Baruch-Fridman** [comment]
Yes I have libbpf-dev installed
$ ls /usr/include/bpf/
bpf.h            bpf_endian.h       bpf_helpers.h  btf.h     libbpf_common.h  libbpf_version.h  usdt.bpf.h
bpf_core_read.h  bpf_helper_defs.h  bpf_tracing.h  libbpf.h  libbpf_legacy.h  skel_internal.h
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble

**Comment by tigercosmos** [comment]
Seems the issue was resolved.
