### ISSUE TITLE
Hang in PcapLiveDevice::stopCapture()

### ISSUE THREAD

**Issue by nedsana** [seladb/PcapPlusPlus#1645]
### Bug description

Hi, 

Recently updated pcap++ to 24.10 and my app started hanging in PcapLiveDevice::stopCapture(), in the m_CaptureThread.join() call. Found similar problem reported here https://github.com/seladb/PcapPlusPlus/issues/606, but it was not helpful.

I read https://linux.die.net/man/3/pcap_breakloop, where they state:

> Note also that, in a multi-threaded application, if one thread is blocked in pcap_dispatch(), pcap_loop(), pcap_next(), or pcap_next_ex(), a call to pcap_breakloop() in a different thread will not unblock that thread; you will need to use whatever mechanism the OS provides for breaking a thread out of blocking calls in order to unblock the thread, such as thread cancellation in systems that support POSIX threads.

Inspecting the code I see indeed that there is a capture thread:
`m_CaptureThread = std::thread(&pcpp::PcapLiveDevice::captureThreadMain, this);` and a call to pcap_breakloop() in PcapLiveDevice::stopCapture().

So I called `pthread_cancel(m_CaptureThread.native_handle());` in PcapLiveDevice::stopCapture() and it no longer blocks.

Could you please, comment if this solution is appropriate? I use libpcap 1.8.1.

Also, reading https://linux.die.net/man/3/pcap_dispatch, the return values of pcap_dispatch are:
> the number of packets processed on success ... , -1 if an error occurs, **_or -2 if the loop terminated due to a call to pcap_breakloop()_** before any packets were processed.

I see that all calls to pcap_dispatch() compare against -1 to terminate their loops. And that smells like a potential issue to me, if someone tries to use pcap_breakloop. 

### PcapPlusPlus versions tested on

PcapPlusPlus master branch

### Operating systems tested on

Linux

### Compiler version

GCC 8.4.0

### Packet capture backend (if applicable)

libpcap

**Comment by tigercosmos** [comment]
It's interesting. I checked `man pcap_dispatch` on Debain 10, and the return value can only be 0 or -1. Not sure if this error is due to new update of pcap, but sure, we may need to handle this case.

**Comment by tigercosmos** [comment]
@nedsana  We will address the issue when we have availability, but you're welcome to contribute a PR if you'd like.

**Comment by seladb** [comment]
@nedsana can you try to update to a new version of libpcap and see if the issue persists?

We could use `pthread_cancel` if the thread is stuck, but we need to consider a few things:
- `pthread_cacnel` will only work on POSIX system. On Windows we should use `TerminateThread()`
- How do we know if a thread is stuck? We need some kind of timeout for `thread.join()`

**Comment by Dimi1010** [comment]
Timeout for thread join pretty much removes the ability to use thread join directly. Either you use OS specific functions, or you have some kind of atomic flag/cond variable that is set at the end of the thread, you can wait on with a timeout. And after that you call join.

**Comment by nedsana** [comment]
Hi,

I ran my app on Ubuntu 22.04, with libpcap 1.10.1 and there is no hanging.

As for the call of pthread_cancel:
- I added flag m_CaptureThreadStopped which is set to true just before captureThreadMain() exits. 
- In PcapLiveDevice::stopCapture(), after pcap_breakloop(m_PcapDescriptor.get()); I wait for 0.5s for m_CaptureThreadStopped to be set to true. If it is still false after that period, I call pthread_cancel().
Ugly but seems to work for me :)

```
void PcapLiveDevice::stopCapture()
{
    // in blocking mode stop capture isn't relevant
    if (m_cbOnPacketArrivesBlockingMode != nullptr)
        return;

    m_StopThread = true;
    if (m_CaptureThreadStarted)
    {
        pcap_breakloop(m_PcapDescriptor.get());

        int32_t poll_attempts {50};
        const int32_t poll_interval {10000};
        while (!m_CaptureThreadStopped && 0 < poll_attempts--)
        {
            usleep(poll_interval);
        }

        if (0 > poll_attempts)
        {
            PCPP_LOG_DEBUG("Cancelling capture thread, waiting for it to join...");
            pthread_cancel(m_CaptureThread.native_handle());
        }
        else
        {
            PCPP_LOG_DEBUG("Stopping capture thread, waiting for it to join...");
        }
        m_CaptureThread.join();
        m_CaptureThreadStarted = false;
        m_CaptureThreadStopped = false;
        PCPP_LOG_DEBUG("Capture thread stopped for device '" << m_InterfaceDetails.name << "'");
    }
    
    if (m_StatsThreadStarted)
    {
        PCPP_LOG_DEBUG("Stopping stats thread, waiting for it to join...");
        m_StatsThread.join();
        m_StatsThreadStarted = false;
        PCPP_LOG_DEBUG("Stats thread stopped for device '" << m_InterfaceDetails.name << "'");
    }

    m_StopThread = false;
}

```

**Comment by nedsana** [comment]
Indeed, after some time, it is inevitable to start using new version of libpcap. So this is a solution I accept.
I am not insisting for the above solution, I just reported it.

Thank you, closing the issue.

**Comment by tigercosmos** [comment]
It's still better to fix the return value of `pcap_dispatch` though.
