### ISSUE TITLE
Compilation Error in PcapLiveDevice.cpp - Control Reaches End of Non-Void Function

### ISSUE THREAD

**Issue by vectorzjl** [seladb/PcapPlusPlus#1665]
### Question

I've encountered an issue with the Pcap++ library when I enabled the HAS_SET_DIRECTION_ENABLED option. The error I'm facing is related to control reaching the end of a non-void function, which is flagged as an error due to the -Werror=return-type compiler flag. This error is located in the PcapLiveDevice.cpp file, specifically on line 84

**Comment by Dimi1010** [comment]
Fixed by #1666
