### ISSUE TITLE
[PATCH] segfault enumerating addresses of interfaces with null addresses

### ISSUE THREAD

**Issue by xloem** [seladb/PcapPlusPlus#170]
`Arping -l` segfaults on my system running the [android tun-easytether interface](http://www.mobile-stream.com/easytether/android.html).  The following patch fixes it.

```
diff --git a/Common++/src/IpUtils.cpp b/Common++/src/IpUtils.cpp
index aa7a519..21e8297 100644
--- a/Common++/src/IpUtils.cpp
+++ b/Common++/src/IpUtils.cpp
@@ -19,6 +19,8 @@ namespace pcpp
 
 in_addr* sockaddr2in_addr(struct sockaddr *sa)
 {
+    if (sa == NULL)
+        return NULL;
     if (sa->sa_family == AF_INET)
         return &(((struct sockaddr_in*)sa)->sin_addr);
     LOG_DEBUG("sockaddr family is not AF_INET. Returning NULL");

**Comment by seladb** [comment]
thanks for reporting this issue! if you already have a fix, why won't submit a PR?

**Comment by xloem** [comment]
it can be kind of hard for me to move my body and engage my computer at this point, so I take the easier paths a lot ;p  got you a PR !

**Comment by seladb** [comment]
Thanks for your contribution, much appreciated!
