### ISSUE TITLE
document have a mistake

### ISSUE THREAD

**Issue by dijiang** [seladb/PcapPlusPlus#173]
on website http://seladb.github.io/PcapPlusPlus-Doc/download.html, the guider build on max os

![image](https://user-images.githubusercontent.com/8736832/55450826-1775d680-5603-11e9-8478-29ca074bdb4e.png)

**Comment by seladb** [comment]
Thanks for reporting this issue!

Fixed in https://github.com/seladb/PcapPlusPlus-Doc/commit/8eb590d613d11f0ff6521403226c9797ec5609f6
