### ISSUE TITLE
Bug in Packet::removelayer

### ISSUE THREAD

**Issue by ibrahimnasson** [seladb/PcapPlusPlus#174]
size_t layerOldDataSize = layer->getHeaderLen();
	uint8_t* layerOldData = new uint8_t[layerOldDataSize];
	memcpy(layerOldData, layer->m_Data, layerOldDataSize);

	// remove data from raw packet
	size_t numOfBytesToRemove = layer->getHeaderLen();
	int indexOfDataToRemove = layer->m_Data - m_RawPacket->getRawData();
	

Instead of getHeaderLen shouldn't you use getDataLen 
Take for example of a RadiusLayer  in which the function does return the actual length of m_data

**Comment by ibrahimnasson** [comment]
As well as while parsing radius layer it's take by assumptions if it's on port 1812 is automatic a radius layer which can lead to false length of the layer hence memory leakage

**Comment by ibrahimnasson** [comment]
There alot of thinks can go wrong when  we use getHeaderLen to determine the size so as to delete

**Comment by seladb** [comment]
`getDataLen()` is different than `getHeaderLen()`. `getDataLen()` returns the overall size of the layer as well as the layers above it. For example, in the following packet:
```
1st layer: EthLayer
2nd layer: IPv4Layer
3rd layer: TcpLayer
4th layer: HttpRequestLayer
```
`IPv4Layer::getDataLen()` will return the size of the data of IPv4Layer + TcpLayer + HttpLayer whereas `IPv4Layer::getHeaderLen()` will return only the size of IPv4Layer.

If you find issues with `getHeaderLen()` for specific layers please let me know and I'll fix it. Otherwise you should use this method to get the layer's data length

**Comment by ibrahimnasson** [comment]
Take for example radius layer:
When a packet is received from network on port 
1812, the api immediately assumes it is  of type radius so then the length of the layer is set by casting the data to radius header of which the length is obtain during delete the header.

Now the problem comes what if the packet is not of radius layer but a payloadlayer on port 1812 so then it invalidates the length when calling the removealllayers after udplayer

**Comment by ibrahimnasson** [comment]
I think the problems comes 
E.g In RadiusLayer
When getHeaderlen is called before calling computeCalculateFields (because this is where the actual length is set)

**Comment by seladb** [comment]
In that case we can fix `getHeaderLen()` for `RadiusLayer` and add a check to make sure the length doesn't go beyond the data bounds.

Do you think you can do that and submit a PR?

**Comment by ibrahimnasson** [comment]
Why do not we return just return m_Datalen  instead of the ntohs(getRadiusHeader()->length)

**Comment by seladb** [comment]
This is an option, but `getRadiusHeader()->length` should usually contain the right size of the RADIUS header. Maybe it's better to write a code that first checks the value of `getRadiusHeader()->length` and if it doesn't make sense returns `m_DataLen`. Please let me know what you think

**Comment by seladb** [comment]
I've made a fix in `dev` branch. Could you please verify your issue is solved?

**Comment by seladb** [comment]
I'll close this issue for now, please reopen it if needed
