### ISSUE TITLE
DpdkBridge cann't send packets  in vf mode

### ISSUE THREAD

**Issue by BigTowChow** [seladb/PcapPlusPlus#178]
i have a Intel X520 NIC using SR-IOV mode. when test dpdkbridge example using vf nic ports, i found this process cann't forward packets to another port. In contrast, this example works fine when using  pf nics.
Can you give me some advice?

**Comment by seladb** [comment]
to be honest, I've never tested it in SR-IOV mode. I also don't have an Intel NIC available to do those tests. Did you try running the L2Fwd example that comes with DPDK? Does it work?

**Comment by shidaoxuan** [comment]
Yes, i tried DPDK L2Fwd example, it works fine. I'think some configurations are unsupported in SR-IOV mode, unfortunately, I didn't find out which configuration it was.

**Comment by seladb** [comment]
That's interesting. Unfortunately I don't have access to a system like you have so it won't be an easy thing to debug. Could you please describe what do you see? 

- Is the app crashing? If so, could you please print the stack trace?
- If it's not crashing, is it processing incoming packets?
- If it's processing incoming packets, do you see any packets going out on the other side? or non at all?

**Comment by shidaoxuan** [comment]
A1:  not crashing.
A2:  it can processing incoming packets.
A3: can't see any packets going out on the other side.

**Comment by seladb** [comment]
Can you please try the other example: https://github.com/seladb/PcapPlusPlus/tree/master/Examples/DpdkExample-FilterTraffic and let me know if it works as expected?

The other example doesn't send any packets, it just processes incoming packets. If it works it probably means the problem lies in the send packets mechanism.

**Comment by seladb** [comment]
Could you please try to run the other example mentioned above and let me know the results?

**Comment by shidaoxuan** [comment]
Sorry, I am on vacation, I will try ASAP.

**Comment by shidaoxuan** [comment]
Examples/DpdkExample-FilterTraffic can't works correctly, similar to the previous example. I think it is related to dpdk configuration.
But beyond that, i found a problem, at Examples/DpdkExample-FilterTraffic/AppWorkerThread.h :Line 131      "sendPacketsTo->sendPacket(*packetArr[i], 0);"  all threads using "txq=0", is that safe?

**Comment by echo-Mike** [comment]
@shidaoxuan 
Concurrent usage of single Rx/Tx queue is never safe except when PMD supports ```DEV_TX_OFFLOAD_MT_LOCKFREE``` for Tx queues

**Comment by seladb** [comment]
@shidaoxuan could you please specify which part in `DpdkExample-FilterTraffic` doesn't work as expected? Is the app receiving packets?

**Comment by shidaoxuan** [comment]
In SRIOV Mode, "DpdkExample-FilterTraffic" and "dpdkbridge" can't send packets, i can't find the root cause.

**Comment by seladb** [comment]
Just to double check: this is happening only with PcapPlusPlus examples, right? On built-in DPDK examples you see packet being sent?

**Comment by shidaoxuan** [comment]
Yes, dpdk l2fw-jobstats example is ok.

**Comment by seladb** [comment]
I can try help you debug if you can somehow share your environment (you can also reach out to me by email)

**Comment by seladb** [comment]
please let me know what could be the next steps

**Comment by BigTowChow** [comment]
I emailed my leader for debugging dpdk example, but he didn't allow it. i suggest hanging up this issue first.

**Comment by seladb** [comment]
What do you mean by hanging up this issue?

**Comment by BigTowChow** [comment]
I‘ll reopen it when there are new discoveries.
