### ISSUE TITLE
TcpReassembly: incorrect sign in if expression

### ISSUE THREAD

**Issue by gx740** [seladb/PcapPlusPlus#180]
I think there is an error in reassemblePacket method of class TcpReassembly at line 264.

Code block:
```
	else // connection already exists
	{
		tcpReassemblyData = iter->second;
		timeval currTime = tcpData.getRawPacket()->getPacketTimeStamp();
		if (currTime.tv_sec > tcpReassemblyData->connData.endTime.tv_sec)
		{
			tcpReassemblyData->connData.setEndTime(currTime); 
		}
		else if (currTime.tv_sec == tcpReassemblyData->connData.endTime.tv_sec)
		{
			if (currTime.tv_usec < tcpReassemblyData->connData.endTime.tv_usec)
			{
				tcpReassemblyData->connData.setEndTime(currTime);
			}
		}
	}

```
Code line: `if (currTime.tv_usec < tcpReassemblyData->connData.endTime.tv_usec).`

I guess the sign must be '>'not '<'.

**Comment by seladb** [comment]
I think you're right, this is indeed a bug. I pushed a fix into `dev` branch, could you please verify the fix before I push it to `master`?

**Comment by gx740** [comment]
I have no way to verify the fix because I found the bug during code studying.

**Comment by seladb** [comment]
Sure, I'll merge the code to master and close this issue. Please feel free to reopen it if needed

**Comment by gx740** [comment]
Ok

**Comment by seladb** [comment]
Merged into `master`, I'll close the issue now, please reopen it if needed
