### ISSUE TITLE
`RawPacket::getPacketTimeStamp()` should be const

### ISSUE THREAD

**Issue by eteran** [seladb/PcapPlusPlus#187]
https://github.com/seladb/PcapPlusPlus/blob/236e035be8d7109082e1b599abd435269f13032d/Packet%2B%2B/src/RawPacket.cpp#L120

This is a simple accessor, it should be const. Not being const, unfortunately, forces me to pass RawPacket by non-const reference simply because of this one method.

I **can** make a PR for this if that helps, but, it's also just  6 character patch ;-)

**Comment by echo-Mike** [comment]
Hi, @eteran
On most projects so called “const”-patches are welcome.  
If You can find more accessors with same problem and merge corrections to one patch it will be appreciated.

**Comment by seladb** [comment]
I agree. Even making a PR with just 6 chars patch will save me some time :)

**Comment by eteran** [comment]
OK, I see actually a **lot** of places where `const` shoudl be applied. Should the PR be against dev or master?

**Comment by echo-Mike** [comment]
I think to dev so it can be part of future release

**Comment by seladb** [comment]
yes, dev is better. I'll merge it to master later

**Comment by eteran** [comment]
OK, submitting a PR now.

**Comment by seladb** [comment]
Thanks for this contribution, much appreciated!
