### ISSUE TITLE
Issue with Initializing DPDK

### ISSUE THREAD

**Issue by austin-millan** [seladb/PcapPlusPlus#190]
I'm trying to run the `DpdkExample-FilterTraffic` example on Linux, but PcapPlusPlus is not picking up the DPDK port.

Here's the output from the example binary:
```
Bin/DpdkTrafficFilter -l
EAL: Detected 2 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
Zero DPDK ports are initialized. Something went wrong while initializing DPDK
Zero DPDK ports are initialized. Something went wrong while initializing DPDK
Zero DPDK ports are initialized. Something went wrong while initializing DPDK
Application terminated in error: couldn't initialize DPDK
```

Here's how I compiled DPDK:
```
PLATFORM="x86_64-native-linuxapp-gcc"
make config T=${PLATFORM} && make
```

I bind `igb_uio` to a ENA network interface, supported by DPDK.

PCPP:
```
$ sudo su
$ export RTE_SDK=/usr/src/dpdk
$ git clone https://github.com/seladb/PcapPlusPlus.git && \
    cd PcapPlusPlus && \
    ./configure-linux.sh --dpdk --dpdk-home /usr/src/dpdk && \
    make all && \
    make install
```

Network interfaces status:
```
./setup-dpdk.sh -s

*******************************
PcapPlusPlus setup DPDK script 
*******************************


Network devices using DPDK-compatible driver
============================================
0000:00:06.0 'Elastic Network Adapter (ENA) ec20' drv=igb_uio unused=ena,uio_pci_generic

Network devices using kernel driver
===================================
0000:00:05.0 'Elastic Network Adapter (ENA) ec20' if=eth0 drv=ena unused=igb_uio,uio_pci_generic *Active*

No 'Crypto' devices detected
============================

No 'Eventdev' devices detected
==============================

No 'Mempool' devices detected
=============================

No 'Compress' devices detected
==============================
```

Do you have any tips for troubleshooting this? Let me know if I should provide more info. I can supply the generated makefiles but they're pretty long. I checked them btw, and the RTE_SDK in the `mk/PcapPlusPlus.mk` point to `/usr/src/dpdk`, as it should. It resolves DPDK header files fine too, it's just not picking up the DPDK port, so the `Tests/Pcap++`  fail and the binaries don't work. 
Any help would be appreciated!

**Comment by seladb** [comment]
can you try running the app with `sudo`?

**Comment by austin-millan** [comment]
Yeah I have tried running with sudo, there was no difference, still get the issue with initializationv

**Comment by seladb** [comment]
According to the error message this error occurs within DPDK. I've never tested ec20 NICs.

My suggestion would be to try DPDK's sample apps first. If those work, we can debug PcapPlusPlus

**Comment by austin-millan** [comment]
I've tried out `testpmd` and the helloworld example in DPDK. I ran `testpmd` in IO mode on the same port, so it receives/transmits on the same port. There were no issues, it identified the port no w/ no dropped packets.

**Comment by seladb** [comment]
Could you please also compare the initialization steps of `testpmd` with those of PcapPlusPlus? Is it somehow different?

**Comment by austin-millan** [comment]
Can you clarify what you mean by initialization steps? Like initializing EAL? If so, `testpmd` initializes EAL the same whether I give it command line args for portmask or not. 

The error is logged [here](https://github.com/seladb/PcapPlusPlus/blob/master/Pcap%2B%2B/src/DpdkDeviceList.cpp#L165) in `Pcap++/src/DpdkDeviceList.cpp`. Pcap++ can detect that DPDK is initialized since nothing was logged previously about needing to call `initDpdk`, it is just determining that there are 0 DPDK ports available.

**Comment by seladb** [comment]
Somehow DPDK initialization doesn't initialize the port, I'm not sure why.

The DPDK initialization happens here (before the "Zero DPDK ports are initialized..." error): https://github.com/seladb/PcapPlusPlus/blob/e8d79712d779dbeeb0887d8bd5221e9263a94407/Pcap%2B%2B/src/DpdkDeviceList.cpp#L124

Maybe it's something with the parameters passed to `rte_eal_init`? I don't know...

Maybe it's possible to run DPDK in debug mode and paste the output. I'm curious to know whether DPDK even tries to initialize the ports and if the result is a success of a failure. You can read [here](https://stackoverflow.com/questions/46786206/how-can-i-enable-debug-mode-in-a-dpdk-based-application) how to run DPDK in debug mode. Please let me know what you think

**Comment by austin-millan** [comment]
I looked into this and compiled DPDK with a higher logging level. I'm not sure how much logging I was expecting, but it's not much different than providing `--log-level` to DPDK apps. So it still shows the same logs when running a app. 

But I stepped through `DpdkTrafficFilter` with GDB

`rte_eal_init` was called with the args from dpdkParamsArray:
dpdkParamsArray = {"pcapplusplusapp", "-n", "2", "-c", "0x03", "--master-lcore", "0"}

`testpmd` runs with those args, so these args look fine. I think you're right about DPDK not attempting to initialize ports, but I'm not sure why other DPDK apps work if DPDK doesn't init ports?

I'll look more into this though. I do see example apps and tests explicitly initializing ports themselves (e.g. defining their own `init_port`), but there are plenty of apps that don't seem to do this, including `helloworld`. Which makes me think that `rte_eal_init` is the issue

**Comment by seladb** [comment]
Thanks for providing these details.

Let me suggest testing [DPDK's L2Fwd sample app](https://doc.dpdk.org/guides-18.08/sample_app_ug/l2_forward_real_virtual.html). This app implements a simple bridge between 2 DPDK ports and transfers packets from one port to another. There is a similar example in PcapPlusPlus: [DpdkBridge](https://github.com/seladb/PcapPlusPlus/tree/master/Examples/DpdkBridge) so you can run both and compare them.

Please let me know if you find anything.

**Comment by seladb** [comment]
I'd like to follow up on that. Did you try testing DPDK's L2fwd example app?

**Comment by duanwujie** [comment]
I have the same question, but the dpdk version is dpdk-stable-16.11.9

**Comment by seladb** [comment]
what NIC are you using? Is it also `ec20`?

**Comment by duanwujie** [comment]
It's ```82599ES 10-Gigabit SFI/SFP+ Network Connection```

**Comment by duanwujie** [comment]
Here is the message:
```
root@Linx:/home/linx/duan/dpdk-stable-16.11.9# ./tools/dpdk-devbind.py --status

Network devices using DPDK-compatible driver
============================================
0003:01:00.1 '82599ES 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=ixgbe,vfio-pci
0005:01:00.3 'Ethernet Controller X710 for 10GbE SFP+' drv=vfio-pci unused=i40e,igb_uio

Network devices using kernel driver
===================================
0000:01:00.0 '82599ES 10-Gigabit SFI/SFP+ Network Connection' if=eth8 drv=ixgbe unused=igb_uio,vfio-pci 
0000:01:00.1 '82599ES 10-Gigabit SFI/SFP+ Network Connection' if=eth9 drv=ixgbe unused=igb_uio,vfio-pci 
0002:01:00.0 'Ethernet Controller X710/X557-AT 10GBASE-T' if=eth1 drv=i40e unused=igb_uio,vfio-pci *Active*
0002:01:00.1 'Ethernet Controller X710/X557-AT 10GBASE-T' if=eth2 drv=i40e unused=igb_uio,vfio-pci 
0002:01:00.2 'Ethernet Controller X710/X557-AT 10GBASE-T' if=eth3 drv=i40e unused=igb_uio,vfio-pci 
0002:01:00.3 'Ethernet Controller X710/X557-AT 10GBASE-T' if=eth4 drv=i40e unused=igb_uio,vfio-pci 
0003:01:00.0 '82599ES 10-Gigabit SFI/SFP+ Network Connection' if=eth6 drv=ixgbe unused=igb_uio,vfio-pci 
0005:01:00.0 'Ethernet Controller X710 for 10GbE SFP+' if=eth12 drv=i40e unused=igb_uio,vfio-pci 
0005:01:00.1 'Ethernet Controller X710 for 10GbE SFP+' if=eth13 drv=i40e unused=igb_uio,vfio-pci 
0005:01:00.2 'Ethernet Controller X710 for 10GbE SFP+' if=eth11 drv=i40e unused=igb_uio,vfio-pci 

Other network devices
=====================
<none>

Crypto devices using DPDK-compatible driver
===========================================
<none>

Crypto devices using kernel driver
==================================
<none>

Other crypto devices
====================
<none>

```
```
root@Linx:/home/linx/duan/dpdk-filter/Bin# ./DpdkTrafficFilter -l
EAL: Detected 128 lcore(s)
EAL: No free hugepages reported in hugepages-1024kB
EAL: No free hugepages reported in hugepages-16777216kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
Zero DPDK ports are initialized. Something went wrong while initializing DPDK
Zero DPDK ports are initialized. Something went wrong while initializing DPDK
Zero DPDK ports are initialized. Something went wrong while initializing DPDK
Application terminated in error: couldn't initialize DPDK
```

**Comment by duanwujie** [comment]
I also test the l2fwd example , output bellow:
```
root@Linx:/home/linx/duan/dpdk-stable-16.11.9/examples/l2fwd/build# ./l2fwd 
EAL: Detected 128 lcore(s)
EAL: No free hugepages reported in hugepages-1024kB
EAL: No free hugepages reported in hugepages-16777216kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
MAC updating enabled
EAL: Error - exiting with code: 1
  Cause: No Ethernet ports - bye
```

**Comment by seladb** [comment]
The message log says:
```
EAL: No free hugepages reported in hugepages-1024kB
EAL: No free hugepages reported in hugepages-16777216kB
```

Maybe there are no free hugepages. Could you please restart your machine and try again?

**Comment by seladb** [comment]
Did you try to restart?

**Comment by seladb** [comment]
Since I didn't see any response I'll close this issue now. Please reopen it if needed

**Comment by austin-millan** [comment]
I'm able to run `l2fwd` fine on a system with 2 cores and 2 DPDK ports:

```
./build/l2fwd -c 0x3 -n 2 -- -p 0x3
```
