### ISSUE TITLE
Unable to use run Tests (MinGW-w64)

### ISSUE THREAD

**Issue by mikeybro** [seladb/PcapPlusPlus#191]

**Comment by echo-Mike** [comment]
Hi @mikeybro !
Please specify what mingw distribution do You use? Also specify version of the gcc compiler. If possible - update it to latest version.

**Comment by mikeybro** [comment]
mingw32 

![gccVer](https://user-images.githubusercontent.com/13041084/57190038-be7fb380-6eca-11e9-8c20-d37eccb097b4.PNG)

**Comment by mikeybro** [comment]
im going to try mingw-w64

**Comment by mikeybro** [comment]
I think i got it to working, going to run the tests:
![works](https://user-images.githubusercontent.com/13041084/57190956-2f2bcd80-6ed5-11e9-9a9a-ea2079895d42.PNG)

**Comment by mikeybro** [comment]
many tests failed :| , can't access files:
![fail](https://user-images.githubusercontent.com/13041084/57191691-250dcd00-6edd-11e9-9196-bb30db1ec813.PNG)

**Comment by mikeybro** [comment]
I have got this far (above pic) using MinGW-w64, any ideas as to how I can get the tests 100%?

**Comment by mikeybro** [comment]
> Hi @mikeybro !
> Please specify what mingw distribution do You use? Also specify version of the gcc compiler. If possible - update it to latest version.

I am using MinGW-w64,  I've been able to pass a few of the tests, and compile and run the Tutorial-helloWorld.exe example. I am trying to figure out whats up with the failed tests.  Also for gcc I am not sure how to update to any other version of it other than whats on the MinGW updater/Installer, since I've gotten this far do you still think my version of gcc (version 8.1.0) could be apart of the issue? My path should be good, also im using msys 1.0,
Heres some snippets:
-- I don't know if this looks correct, but it works pretty good:
![gcc](https://user-images.githubusercontent.com/13041084/57199789-f5d87980-6f37-11e9-9d97-f37bfd3c7caa.PNG)

for the WpdPack, I passed this path to the .bat script, and that took a few different trys:
![wpd](https://user-images.githubusercontent.com/13041084/57199800-2e785300-6f38-11e9-8902-c6e75338eda4.PNG)

And, finally, my stitched together path, I am still learning alot:
![path](https://user-images.githubusercontent.com/13041084/57199817-929b1700-6f38-11e9-86fc-03ea6b960d24.PNG)

**Comment by echo-Mike** [comment]
It seams good at first glance. I pesonaly prefer MSYS2 distribution of mingw.
This error may be reoccurring because you start test scripts from wrong directory. See .appveyor file, it has correct commands for Windows environment.

**Comment by mikeybro** [comment]
That what I was thinking, I may have been running them improperly, I've been up to long and was just punching in commands:
![test](https://user-images.githubusercontent.com/13041084/57200704-c6c80500-6f43-11e9-87e9-02d7d7d62078.PNG)

And, Also, I had tried MSYS32 at one point, last night I tried a bunch of different mixtures, with varying results. I think I had reached the point I am at now with MSYS32 as well....

**Comment by seladb** [comment]
You got it right :)

Running `Pcap++Test` is very similar, the only difference is that you need to give it an IP address it can receive and send packets from. For example:

```shell
c:\MinGW\msys\1.0\home\PcapPlusPlus\Tests\Pcap++Test>Bin\Pcap++Test.exe -i <YOUR_IP_ADDRESS>
Using ip: <YOUR_IP_ADDRESS>
Debug mode: off
Starting tests...
TestIPAddress                 : PASSED
TestMacAddress                : PASSED
TestPcapFileReadWrite         : PASSED
TestPcapSllFileReadWrite      : PASSED
TestPcapFileAppend            : PASSED
TestPcapNgFileReadWrite       : PASSED
TestPcapNgFileReadWriteAdv    : PASSED
TestPcapLiveDeviceList        : PASSED
TestPcapLiveDeviceListSearch  : PASSED
TestPcapLiveDevice            : PASSED
TestPcapLiveDeviceNoNetworking: PASSED
TestPcapLiveDeviceStatsMode   : PASSED
TestPcapLiveDeviceBlockingMode: PASSED
TestWinPcapLiveDevice         : PASSED
TestPcapFilters               : PASSED
TestSendPacket                : PASSED
TestSendPackets               : PASSED
TestRemoteCapture             : PASSED
TestHttpRequestParsing        : PASSED
TestHttpResponseParsing       : PASSED
...
...
ALL TESTS PASSED!!
```

Please let me know if additional info is needed, otherwise please close the issue
