### ISSUE TITLE
KNI device interface

### ISSUE THREAD

**Issue by echo-Mike** [seladb/PcapPlusPlus#192]
I am currently working on adding support for DPDK KNI inreface.  
There is two kind of KNI interfaces:
  1. One that are created via ```--vdev net_kniN``` EAL param and can be controlled as usual DPDK interfaces;
  2. That are created thru DPDK rte_kni library interface and are separate entities from DPDK NICs.

This features are intended for second kind of KNI interfaces.  
The first code edidtion is now avaliable on [feature/kni_device](https://github.com/echo-Mike/PcapPlusPlus/tree/feature/kni_device) branch of my fork in files [KniDevice.cpp](https://github.com/echo-Mike/PcapPlusPlus/blob/feature/kni_device/Pcap%2B%2B/src/KniDevice.cpp), [KniDeviceLinux.cpp](https://github.com/echo-Mike/PcapPlusPlus/blob/feature/kni_device/Pcap%2B%2B/src/KniDeviceLinux.cpp) and [KniDevice.h](https://github.com/echo-Mike/PcapPlusPlus/blob/feature/kni_device/Pcap%2B%2B/header/KniDevice.h).  
Suggestions and critique are welcome and appreciated.

**Comment by echo-Mike** [comment]
TODO list:
- [ ] Add files to build system
- [ ] Add tests
- [ ] Add documentation

**Comment by echo-Mike** [comment]
KNI interface information:
* [DPDK Tests](https://doc.dpdk.org/dts/test_plans/kni_test_plan.html)
* [KNI Interface concept](https://doc.dpdk.org/guides/prog_guide/kernel_nic_interface.html) 
* [KNI PMD](https://doc.dpdk.org/guides/nics/kni.html)
* [KNI DPDK sample app](https://doc.dpdk.org/guides/sample_app_ug/kernel_nic_interface.html)

**Comment by echo-Mike** [comment]
Implementation is split in two files bacause DPDK and Linux kernel have incompatible definitions.

**Comment by seladb** [comment]
Thanks for working on this! Please give me a couple of days to go over the documentation and the code

**Comment by echo-Mike** [comment]
Hi @seladb it is ok, i planning to complete tests and docs by the 12.05.19
Currently build is failing for unknown reasons on Mac (Xcode 9.1 and 9.2):
https://travis-ci.org/echo-Mike/PcapPlusPlus/builds/528571669
I don't see a reason of this issues

**Comment by seladb** [comment]
Sure thanks!

Two initial comments:
- Maybe you should consider naming the class `DpdkKniDevice` instead of `KniDevice` to emphasize it's working with DPDK
- Please use camelCase style everywhere, for example: 
  - https://github.com/echo-Mike/PcapPlusPlus/blob/4d62ff8d7d1eb7024e0b2b979d26af2404db900c/Pcap%2B%2B/header/KniDevice.h#L154
  - https://github.com/echo-Mike/PcapPlusPlus/blob/4d62ff8d7d1eb7024e0b2b979d26af2404db900c/Pcap%2B%2B/header/KniDevice.h#L134

**Comment by echo-Mike** [comment]
I am against the renaming because as i mentioned before there is two kind of KNI devices and it makes code harder to write whithout any clarification of intent. One that uses and understends KNI concept shure understends what DPDK mean and how they correspond to each other.  

The ```#include "DpdkDevice.h"``` statement must clarify more for programmer than other things.  
The KNI code is guarded by ```USE_DPDK``` macro for further clarification.

I corrected snake case namimg for public variables where it is applicable (not a DPDK naming choice) for internal variables it is not important and in some cases confusing (naming update will come this evening).

**Comment by echo-Mike** [comment]
Hi @seladb i have added documentation for KNI device

**Comment by seladb** [comment]
Thanks @echo-Mike , please let me know when the code is ready. You can open a PR and I'll review it

**Comment by echo-Mike** [comment]
Hi @seladb.
Please review recent changes to MBufRawPacket class in [feature/no_kni_raw_packet](https://github.com/echo-Mike/PcapPlusPlus/tree/feature/no_kni_raw_packet) branch of my fork. 
I have separated declaration and implementation of MBufRawPacket  class to corresponding files and made it possible to initialize it from any device that have rte_mempool attached to it (by adding corresponding overloads to init and initFromRawPacket methods).
This change reduces unjustified complexity added by KniRawPacket class.

**Comment by seladb** [comment]
Thanks @echo-Mike ! regarding the changes in `MBufRawPacket` - can you give me the commit IDs to compare?

**Comment by echo-Mike** [comment]
> Thanks @echo-Mike ! regarding the changes in `MBufRawPacket` and `DpdkDevice` - can you give me the commit IDs to compare?

I think 784f288 and 03a6707 should work [compare link](https://github.com/seladb/PcapPlusPlus/compare/784f288..03a6707)

**Comment by echo-Mike** [comment]
@seladb I have a trouble - as I can see You don't initialize DPDK (via stup-dpdk.sh) on TravisCI tests, but KNI tests must be done with DPDK initialized.
So waht i need to do now?
I can just test all on my machine and report results and send KNI device tests to network category or something else. What did You think of it?

**Comment by seladb** [comment]
@echo-Mike you raise a good point. At the time I added DPDK support for PcapPlusPlus I didn't find a way to initialize DPDK inside a docker container (as you may have noticed, all tests are running inside a docker containers that runs in Travis CI worker). 

I think that might have changed since then. It'll be very beneficial if we can find a way to run at least the basic tests in Travis CI. It would also help the rest of the DPDK tests.

Would you mind exploring that option?

**Comment by echo-Mike** [comment]
Yes, running DPDK in a container is a vaible option by now. I have seen some guides on how to do it.
Sorry I really have no time by now to do something else but fix some issues in my PR. I had put a lot of efforts in last weeks in it. You may consider to start the new issue and I will assist when have more spare time.
So by now I think the KNI tests may be done by end user if he need it.
@seladb by now I want to hear Your thoughts about the next steps We should do to integrate PR into PCPP?

**Comment by seladb** [comment]
@echo-Mike I really appreciate all of the work you have put on this, this is a really major contribution to PcapPlusPlus. thank you!

I'm currently going over the PR. Overall it looks good. I'm putting comments inside the review. I already completed 80% of the review, hopefully tomorrow I'll complete it all.

Regarding running DPDK in a container - could you please send me relevant links? I can try to do it myself.

**Comment by echo-Mike** [comment]
Implemented with #196
Closed

**Comment by seladb** [comment]
Thank you so much @echo-Mike for your time and efforts in implementing this feature! You are definitely one of the biggest contributors to this project and I really appreciate your help.

Over the years PcapPlusPlus has become more popular and well-known and from the feedback I get it seems people like it and find it really useful. I think you play a major role in this journey and I feel I owe you a lot of this popularity and recognition.

# Thank You Mike!!!
