### ISSUE TITLE
about the “Benchmarks”

### ISSUE THREAD

**Issue by TCZWJ** [seladb/PcapPlusPlus#193]
When i read the source code in “Matias Fontanini's packet-capture-benchmarks project”, i found that the performance is just the capture performance of the four lib (libpcap、PcapPlusPlus 、libtins and libcrafter). I want to know : is the capture performance of pcapplusplus  based on DPDK?

**Comment by seladb** [comment]
Currently it's not. The current benchmark tests `libpcap` wrapper and compares it with the similar code used in `libtins` and `libcrafter`

**Comment by seladb** [comment]
Please let me know if you have more questions, otherwise please close the issue

**Comment by TCZWJ** [comment]
thx，I do not have any problems.
