### ISSUE TITLE
Is it possible to capture only inflow?

### ISSUE THREAD

**Issue by MrSiz** [seladb/PcapPlusPlus#203]
For example, we can use `tcpdump -Q in` to capture only inflow.  It seems that i cannot capture only inflow in promiscuous mode.

**Comment by seladb** [comment]
Yes, this should be possible using the filtering capabilities. For example, if you want to capture only incoming traffic to interface with IP address of `10.0.0.1` you need to write the following code: 

```cpp
pcpp::PcapLiveDevice* dev = pcpp::PcapLiveDeviceList::getInstance().getPcapLiveDeviceByIp("10.0.0.1");
dev->open();
pcpp::IPFilter ipFilter("10.0.0.1", pcpp::DST);
dev->setFilter(ipFilter);

// start capturing...
```

I didn't try to run this code so excuse me for any syntax errors, but this should give you the general idea. Please let me know if this helps

**Comment by MrSiz** [comment]
Thanks for your reply. But in promiscuous mode,  some packets  captured by the interface have different IP address which is differen from the host IP. I need a function like `    int pcap_setdirection(pcap_t *p, pcap_direction_t d)`. In that way, I can only capture the incoming traffic no matter what their destination IP address is,  then I can forward thoses packets one by one.  Hope you can understand me. Sorry for my poor English. :)

**Comment by seladb** [comment]
Got it, makes sense. I think this should be pretty easy to implement. Do you think you can do it yourself and submit a PR? I can guide you through it and provide all the support needed. Please let me know

**Comment by MrSiz** [comment]
I'm not sure whether I can solve it. But I want to try it!

**Comment by seladb** [comment]
You raise a very good point as `pcap_setdirection` is not supported in WinPcap and I'm also not sure in which version of libpcap it was introduced. So we probably need a compilation flag for it, similar to [immediate mode](https://github.com/seladb/PcapPlusPlus/blob/d4ed6aa7742c5b0a3275966ed945224a88a76e1b/configure-linux.sh#L57).

Regarding the code change itself, I'd recommend adding it to the [DeviceConfiguration](https://github.com/seladb/PcapPlusPlus/blob/d781f5c5505865818d47864c0905cc1c949a47de/Pcap%2B%2B/header/PcapLiveDevice.h#L156) struct. The default value can be "no filter" and the user can set IN or OUT. Then you can use this value in `doOpen` and call `pcap_setdirection`: https://github.com/seladb/PcapPlusPlus/blob/d781f5c5505865818d47864c0905cc1c949a47de/Pcap%2B%2B/src/PcapLiveDevice.cpp#L217 

Please let me know what you think

**Comment by MrSiz** [comment]
Thank you very much. I know what I should do now. If I encounter any other problems, I'll ask for your help again. :)

**Comment by seladb** [comment]
Thanks! Please submit a PR once you’re done and I’ll review it. Please don’t hesitate to ask any question you might have

**Comment by seladb** [comment]
Added in PR #208
