### ISSUE TITLE
Perf question

### ISSUE THREAD

**Issue by chenziliang** [seladb/PcapPlusPlus#206]
When taking a look at the benchmark http://seladb.github.io/PcapPlusPlus-Doc/benchmark.html, it looks like comparing to native pcap, PcapPlusPlus has quite a lot perf downgrade. May i ask why we have so much perf downgrade ?

**Comment by echo-Mike** [comment]
libpcap doesn't parse packets.

**Comment by chenziliang** [comment]
Thanks Mike. Look like it is no an apple to apple comparison. If this can be mentioned in the benchmark page, it will cause less confusion, i guess.
