### ISSUE TITLE
Using string functions for non-strings

### ISSUE THREAD

**Issue by Roman-Koshelev** [seladb/PcapPlusPlus#209]
src/HttpLayer.cpp:	char* verPos = strstr(data, " HTTP/");

"data" may not be a string. Is not it?

**Comment by echo-Mike** [comment]
Hi @Roman-Koshelev can You please use permalinks or code links to refer to some code parts it is hard to find specific line.
About using non-strings: in major compilers on major platforms (x32 and x64 non mainfraim) the type of `uint8_t` is pretty much always defined as alias to `unsigned char`. The C string functions in most cases described are compiler built-ins that analizes code on high level and can understand what suppose to be done.
About the `'\0'` cahr that required to be in the end of `data`: the code must be inspected to ensure that this is correct.

**Comment by Roman-Koshelev** [comment]
https://github.com/seladb/PcapPlusPlus/blob/fe2d92c3f5f3b171758cc096870b95961aeeac1c/Packet%2B%2B/src/HttpLayer.cpp#L356

**Comment by Roman-Koshelev** [comment]
About using non-strings: I agree. But with the signature "uint8_t * data, size_t dataLen" it is obvious that \0 may not be at the end. What if I even convey "(NULL, 0)"

**Comment by echo-Mike** [comment]
For what exact __signature__ do You refer? Does some function have it?

**Comment by Roman-Koshelev** [comment]
Например https://github.com/seladb/PcapPlusPlus/blob/fe2d92c3f5f3b171758cc096870b95961aeeac1c/Packet%2B%2B/header/HttpLayer.h#L161

**Comment by echo-Mike** [comment]
I addmit that it is an issue, but in most cases this is not. There is a lot less illformed HTTP packets to bother to correct it. The safe method is to use safe versions of `std::strstr` provided by coplier vendors or newer approach with algorithms (it is equal in code size) like `std::search`

**Comment by Roman-Koshelev** [comment]
Watching the code found an example of how to write beautifully, but not necessary.
https://github.com/seladb/PcapPlusPlus/blob/fe2d92c3f5f3b171758cc096870b95961aeeac1c/Packet%2B%2B/src/HttpLayer.cpp#L129

The number of redundant allocations, copies and passes is a bit too much. It makes sense to refactor up to 1 allocation and 1 copy. We also have std :: string and even connected <algorithm>

**Comment by seladb** [comment]
The reason I used memory allocations and copies is that `HttpRequestLayer::toString()` is usually not used in the critical processing path in most apps. 

But in the previous example `strstr` is used in HTTP parsing which is definitely part of the critical processing path hence the code needs to be as efficient as possible, so memory allocations and copies are out of the question.

We can replace `strstr` with [strnstr](https://www.freebsd.org/cgi/man.cgi?query=strnstr&sektion=3). It is not supported on all platforms, but there are various implementations of it in the Internet, for example [here](https://stackoverflow.com/questions/23999797/implementing-strnstr) and [here](https://codereview.stackexchange.com/questions/132519/a-simple-and-safe-implementation-for-strnstr-search-for-a-substring-in-the-firs)
