### ISSUE TITLE
Parsing and manipulating incoming packets causes segmentation fault

### ISSUE THREAD

**Issue by LeNormich** [seladb/PcapPlusPlus#213]
Hello,
I'm trying to parse incoming packets in order to differentiate streams based on their IP src.
The problème is that once I enter the callback function and try to get the source ip address, the program fails with segmentation fault.

Here the (lightened) content of my callback function:

	pcpp::Packet parsedPacket(pPacket);  //ok

	pcpp::IPv4Layer* iplayer = parsedPacket.getLayerOfType<pcpp::IPv4Layer>(); //this is ok

	std::string ipaddress = iplayer->toString();    //this step causes seg fault during execution (after a few seconds)

	//std::cout << ipaddress<< std::endl;

Code is running on Debian 9.3

The question is: am i doing something wrong here? is it not possible to manipulate incoming packets like this?

**Comment by echo-Mike** [comment]
Hello @LeNormich. The case of `SEGFAULT` may be in Your second line:
```C++
 pcpp::IPv4Layer* iplayer = parsedPacket.getLayerOfType<pcpp::IPv4Layer>();
```
it will return `NULL` if layer not found (not all packets that circulate over tne network have the IPv4 leayer)

**Comment by LeNormich** [comment]
Oh I hadn't even thought of that... I feel a little stupid but thanks for the hint!
