### ISSUE TITLE
Is it possible to cross-compile PcapPlusPlus for ARM?

### ISSUE THREAD

**Issue by lexibrent** [seladb/PcapPlusPlus#214]
Does anyone know if it would be possible to cross-compile PcapPlusPlus (specifically the DPDK wrappers) for ARM, or does the code utilize x86-specific instructions?

**Comment by seladb** [comment]
DPDK itself can cross-compile on ARM: https://doc.dpdk.org/guides/linux_gsg/cross_build_dpdk_for_arm64.html

Regarding PcapPlusPlus - I never tried because I don't have an ARM machine available. I'd appreciate if you can try and let me know.

**Comment by lexibrent** [comment]
Thanks for your reply! I managed to compile PcapPlusPlus for arm64 after changing these build flags: `-msse -msse2 -msse3` to `-march=native`

**Comment by seladb** [comment]
awesome, thanks for letting me know

**Comment by ibrahimnasson** [comment]
i use it on android and it's working well i guess  it's possible

**Comment by seladb** [comment]
is there any way you know to test it on CI?

Travis-CI and AppVeyor don't support ARM currently...

**Comment by seladb** [comment]
I can try to add an ARM64 build to PcapPlusPlus CI (specifically [ARMv8 64-bit](https://hub.docker.com/u/arm64v8/)). Please let me know if you think that will be useful
