### ISSUE TITLE
Possibility to create file in memory

### ISSUE THREAD

**Issue by LeNormich** [seladb/PcapPlusPlus#216]
Hello all,

Due to some constraints, I would like to use a PcapNgFileWriterDevice to create a file in memory instead of disk.
On regular files, this can be done using fmemopen or open_memstream but is it doable with this writer?

Thanks

**Comment by seladb** [comment]
currently this feature doesn't exist and only reading/writing to files is possible. If you need this urgently please feel free to implement and create a PR. I can guide you through the code if needed

**Comment by LeNormich** [comment]
This would have been a nice to have for me and I don't require this feature right now.
I'll probably try that in a few months, I'll ask you then!
