### ISSUE TITLE
User macro and pre + post build events issues in VS. 

### ISSUE THREAD

**Issue by Dysl3xik** [seladb/PcapPlusPlus#218]
Hello I recently submitted you a PR to fix an issue with your bat file to update the property sheets with correct paths to required libs.

I have now fully compiled your library and found a few other minor issues.

1. What is the purpose of the pre-build event fetch-git-info.bat? It does not seem to be properly configured and if I had to guess is something leftover from your own workflow?

2. The post build events again had an issue with spaces in the path, I added some more quotes to fix the issue and will submit a PR.

3.  Atleast for VS2017 I had to further modify the prop sheets to tell tell it the user macros exist. I will submit a PR for this but I just updated the file as follows:

```
  <PropertyGroup Label="UserMacros">
    <PcapPlusPlusHome>PUT_PCAPPLUSPLUS_HOME_HERE</PcapPlusPlusHome>
    <WinPcapHome>PUT_WIN_PCAP_HOME_HERE</WinPcapHome>
    <PThreadWin32Home>PUT_PTHREAD_HOME_HERE</PThreadWin32Home>
  </PropertyGroup>
  <!-- Tell VS to use these macros -->
  <ItemGroup>
    <BuildMacro Include="PcapPlusPlusHome">
      <Value>$(PcapPlusPlusHome)</Value>
    </BuildMacro>
	<BuildMacro Include="WinPcapHome">
      <Value>$(WinPcapHome)</Value>
    </BuildMacro>
	<BuildMacro Include="PThreadWin32Home">
      <Value>$(PThreadWin32Home)</Value>
    </BuildMacro>
  </ItemGroup>
```

**Comment by seladb** [comment]
Thanks @Dysl3xik for making these changes! I just merged your PR. I tested it on VS2015 and it seems to be working.

Regarding `fetch-git-info.bat` - it's being used in the following APIs:

- https://github.com/seladb/PcapPlusPlus/blob/236e035be8d7109082e1b599abd435269f13032d/Common%2B%2B/header/PcapPlusPlusVersion.h#L39
- https://github.com/seladb/PcapPlusPlus/blob/236e035be8d7109082e1b599abd435269f13032d/Common%2B%2B/header/PcapPlusPlusVersion.h#L44

Their purpose of these APIs is to expose the Git info. For all platforms that have a Makefile (which is all of them except for MSVC) I put the code that fetches the Git info in `Common++` Makefile:

https://github.com/seladb/PcapPlusPlus/blob/236e035be8d7109082e1b599abd435269f13032d/Common%2B%2B/Makefile#L27

But For VS2015 I had to come up with a different solution, so I wrote this batch file that runs as a PreBuildEvent. I know this solution is far from being perfect so I'd love to hear other suggestions.

**Comment by Dysl3xik** [comment]
Actually I went through and rechecked after fixing all the other issues the git bat file does work. It suffers from the same issue as the other bat file that the macros are "invisible" after creation because they are missing those entries to make them show up in the list. I added a few lines to the bat file to make them show up in the macro list.

I can give you another PR for this if you would like.

Aside from that if you want to get the commit hash and branch the only other trick I can think of is to scrape the HEAD file in .git\logs\refs\remotes\origin. However this is no better and is probably even worse than just using the feedback from the git commands.

**Comment by seladb** [comment]
Thanks @Dysl3xik ! I'm not sure I fully understand the issue you are talking about in the git bat file, but if you can provide a fix for that that'd be great!

**Comment by Dysl3xik** [comment]
"Issue" is relative, basically without extra entries in the props XML when you open the props sheet in VS it will not show that these macros exist although technically they do behind the scenes they won't be in the list of macros.

**Comment by seladb** [comment]
Oh, got it now :)

If you can provide a fix that'd be great. It seems you're more familiar with this stuff than me

**Comment by seladb** [comment]
Do you think you can provide a fix for that?

**Comment by Dysl3xik** [comment]
Yes I am crunching on the other issue I posted at the moment, but I will probably share contributions for both issues soon.

**Comment by seladb** [comment]
Great, thanks for your help!

**Comment by seladb** [comment]
BTW, this change is pretty small, right?

**Comment by Dysl3xik** [comment]
Yes just a few lines in bat file. This is already done and will be in my next PR so I will just close this for now.
