### ISSUE TITLE
loopback MTU

### ISSUE THREAD

**Issue by sashabel** [seladb/PcapPlusPlus#220]
Hello,

I'm using your wonderful library for recording and replaying network traffic.
However, the NPcap loopback device MTU  returned by the library is 14. 
'netsh interface ipv4 show subinterfaces' reports its value equals 1500.
?

**Comment by seladb** [comment]
Could you please post the code you wrote?

**Comment by sashabel** [comment]
The code is taken from the tutorials. After listing the device and choosing the loopback device:
```
// Get device info
	// ~~~~~~~~~~~~~~~

	// before capturing packets let's print some info about this interface
	printf("Interface info:\n");
	// get interface name
	printf("   Interface name:        %s\n", dev->getName());
	// get interface description
	printf("   Interface description: %s\n", dev->getDesc());
	// get interface MAC address
	printf("   MAC address:           %s\n", dev->getMacAddress().toString().c_str());
	// get default gateway for interface
	printf("   Default gateway:       %s\n", dev->getDefaultGateway().toString().c_str());
	// get interface MTU
	printf("   Interface MTU:         %d\n", dev->getMtu());
	// get DNS server if defined for this interface
	if (dev->getDnsServers().size() > 0)
		printf("   DNS server:            %s\n", dev->getDnsServers().at(0).toString().
```

**Comment by seladb** [comment]
Thanks, let me check that and get back to you

**Comment by seladb** [comment]
I found out why this is happening, please refer to the documentation for NPcap here https://nmap.org/npcap/guide/npcap-devguide.html#npcap-feature-loopback:

>  The MTU of “Npcap Loopback Adapter” is hard-coded to 65536 by Npcap. Software using Npcap should get this value automatically and no special handling is needed. This value is arbitrary and does not imply a limitation on the Windows loopback stack, so it may be possible to capture packets with a size larger than the adapter's MTU.

> Don't try to make OID requests to “Npcap Loopback Adapter” except OID_GEN_MAXIMUM_TOTAL_SIZE (MTU). Those requests will still succeed like other adapters do, but they only make sense for NDIS adapters and Npcap doesn't even use the NDIS way to handle the loopback traffic. The only handled OID request by Npcap is OID_GEN_MAXIMUM_TOTAL_SIZE. If you query its value, you will always get 65550 (65536 + **14**). If you try to set its value, the operation will always fail. 

That's the reason you're getting a value of 14, but since it is hard coded I think you can safely ignore it for the loopback interface

**Comment by seladb** [comment]
Please let me know if we can close this issue

**Comment by sashabel** [comment]
It is problematic to ignore it, because sending to this device fails with MTU size error

**Comment by seladb** [comment]
Got it, that’s a good point. Can you suggest a fix?

**Comment by seladb** [comment]
hi @sashabel please let me know if you can suggest a fix

**Comment by sashabel** [comment]
Hi, I didn't find suitable fix

**Comment by seladb** [comment]
here is my suggestion: in the method https://github.com/seladb/PcapPlusPlus/blob/898519e67f95ba2c4c5871554e51e3c08ee0f346/Pcap%2B%2B/src/PcapLiveDevice.cpp#L621

There is a section for Win adapters. There you can check the device name which should be `Npcap Loopback Adapter` for loopback adapters (this is according to the information mentioned [here](https://nmap.org/npcap/guide/npcap-devguide.html#npcap-feature-loopback)).

Then you can set the MTU as some hard-coded (magic) number or simply set it to to Npcap's hard coded number (65550).

Please let me know what you think.

**Comment by seladb** [comment]
hi @sashabel please let me know what you think of my suggestion. We can either make a fix of leave the code as is

**Comment by sashabel** [comment]
Hi , the suggestion seems reasonable . I am on vacation till the end o August so didn't have a chance to check it. Can you please wait till the end of month ?

**Comment by seladb** [comment]
thanks @sashabel . I'll try to do the fix myself, it shouldn't be much work. I'll keep you posted

**Comment by seladb** [comment]
The fix is even easier than I thought. There is already a loopback flag in `PcapLiveDevice` so I just used it when setting the MTU on Windows loopback interfaces. I tested using the code you published earlier and it seems to be working. Please pull the latest code from `master`.

I'll close the issue now, please reopen it if needed.
