### ISSUE TITLE
Npcap read + write wastes memory

### ISSUE THREAD

**Issue by Dysl3xik** [seladb/PcapPlusPlus#221]
**SKIP THIS POST AND GO TO BOTTOM - I was wrong here!**

Just FYI I am using NPCAP as my capture library behind the scenes and working in Windows 10.

In the example live capture code a simple example is given to capture live packets with a callback

```
// start capture in async mode. Give a callback function to call to whenever a packet is captured and the stats object as the cookie
dev->startCapture(onPacketArrives, &stats);

/**
 * A callback function for the async capture which is called each time a packet is captured
 */
static void onPacketArrives(pcpp::RawPacket* packet, pcpp::PcapLiveDevice* dev, void* cookie)
{
	// extract the stats object form the cookie
	PacketStats* stats = (PacketStats*)cookie;

	// parsed the raw packet
	pcpp::Packet parsedPacket(packet);

	// collect stats from packet
	stats->consumePacket(parsedPacket);
}
```
When i run this in windows the memory usage seems to be growing unbounded. Granted I have only run it for up to one minute (initial testing and dev) but memory usage is steadily ticking up. I would expect it to more or less reach a steady state and plateau (I am capturing from a sensor device that provides a more or less steady stream).

Looking at the live PcapLiveDevice code that runs our callback function it creates a RawPacket with the flag NOT to release the packet memory. Why?

```
void PcapLiveDevice::onPacketArrives(uint8_t *user, const struct pcap_pkthdr *pkthdr, const uint8_t *packet)
{
	PcapLiveDevice* pThis = (PcapLiveDevice*)user;
	if (pThis == NULL)
	{
		LOG_ERROR("Unable to extract PcapLiveDevice instance");
		return;
	}

	RawPacket rawPacket(packet, pkthdr->caplen, pkthdr->ts, false, pThis->getLinkType());

	if (pThis->m_cbOnPacketArrives != NULL)
		pThis->m_cbOnPacketArrives(&rawPacket, pThis, pThis->m_cbOnPacketArrivesUserCookie);
}
```

Are we expected to release the raw packet pointer in our callback? That isn't in the example code. Or is there something in the libraries behind the scene the it keeps a cache of captures and eventually cleans that up it self?

If I recompile the code with the flag swapped to true my memory plateaus at a few MB and stays steady (which is what I originally expected).

Anyways please let me know how the memory is expected to be managed here.

**Comment by Dysl3xik** [comment]
Oops when I tested with the flag swapped my sensor was offline! So no packets and of course no memory jumps haha. If I flip the flag it actually causes a crash, so that is a no-go period. 

The issue of unbounded memory is still a thing I need guidance about though.

**Comment by Dysl3xik** [comment]
Actually its not related to packets at all, its something in pcapng file generation. I am still digging more and may end up just closing this....

**Comment by Dysl3xik** [comment]
Ok it looks like all of the blocks for the pcapng file are maintained in a linked list and are not released until the file is closed? This may be OK for small captures but I have a high bandwidth application that will be capturing for a few minutes and could easily start eating up many hundreds of MBs and into GBs.

From the looks of things the data is already written to the file long before close is called, therefore I can't figure out why all this memory is held and not released until the file is closed? This seems like wasted memory. Am I missing something?

**Comment by seladb** [comment]
Yes, you're right and I'm aware of this. The reason it was built like that is because I use a 3rd party library for reading and writing pcapng files called [LightPcapNg](https://github.com/rvelea/LightPcapNg). Although this library is pretty lightweight and easy to use, it's far from being optimized.

You are more than welcome to take a look at the code of this library and change it. I remember that it seemed a pretty big change when I looked so I figured I'll do it only if there is a strong demand for it.

**Comment by Dysl3xik** [comment]
I fixed the writing already - the reading would take more effort. I really don't like dealing C code tho :(

Currently it does something similar in that it loads everything into memory then splits it out into the packets. Not only is this wasting 2x the memory because it first streams into memory as a glob, then splits into the structs, but it also prevents streaming the file which again wastes huge memory. At least in the reading case one can make an argument that having everything in memory at once can serve some purpose, as you may wish to move around the file.

I am also working (for my own needs) to add the ability to compress the output while streaming it with z-std. I may even be able to generalize this to allow plugging in other compression API types, but can certainly get z-std plugged in. Its BSD licensed so should work fine with this project.

Any thoughts?

**Comment by seladb** [comment]
Thanks for your efforts! so do you plan to fix the reading part as well?

Regarding z-std compression - this can be very useful for this project. Maybe we can also use it in HTTP messages - currently the main reason PcapPlusPlus doesn't support parsing HTTP body messages is the lack of compression support

**Comment by Dysl3xik** [comment]
I have completed the writing portion, files are now always written as a stream with no copy in memory, and if a compression level is specified it will automatically kick in z-std and compress while streaming to file. 

There is one other function that i didn't port yet but will probably do so, even though its not used anywhere and is probably a remnant from when you picked up this lib.
`int light_pcapng_to_file(const char *file_name, const light_pcapng pcapng)`

I will investigate the reading part next, along with possibly integrating the decompression as a stream. The decompression as a stream bit may be a little more effort because the chunking for compression will break the packet boundaries so there may need to be some level of synchronization between the streams.

**Comment by seladb** [comment]
Thank you for working on this, much appreciated!
I think for start maybe we can integrate it without z-std because adding an additional dependency requires testing it on all platforms, modifying the installation scripts and also the installation guides.
It'll be easier to start with the code changes only and add compression later. Please let me know what you think

**Comment by Dysl3xik** [comment]
Well, I need the compression now so I am going to integrate it now. However it should all be compatible with any existing code.

The lightpcapng code won't compile with zstd support unless you add a macro for where to find it (like your other libs), and furthermore I have a compile time macro to enable the functions and structs required for it to work. If you leave out this macro it should still compile and work, everything for compression just becomes nullptr and such. This way you still get the memory sparing code and I get my compression now.

I will do similar with the reading code so it will compile and function with and without zstd. When you a ready to updated docs and "fully" deploy this you can do it then, but in the meantime the code can exist and be dormant. 

I will further note that atleast with zstd you don't need to compile the libs yourself, then have ready to go redists you can grab so you already have the dll and libs. You just need to add them to the project properties. So adding it in isn't too much work.

**Comment by seladb** [comment]
Using macros make a lot of sense. That way I can integrate your code in phases, first without zstd and later on add zstd support.

Please let me know when you’re done with the reading piece and ready to create a PR

**Comment by Dysl3xik** [comment]
Work is done see PR #222 and PR #223

**Comment by seladb** [comment]
Thank @Dysl3xik for all the efforts!

Please note CI fails for both PRs, could you please take a look?

**Comment by Dysl3xik** [comment]
I looked quickly, it seems to not like alias names for function input
types. There was some tricks I did with forward declarations for a struct,
and in other files it uses typedefed struct ptrs. It builds and runs fine
in windows, maybe your error/warning level may be more aggressive?

**Comment by seladb** [comment]
thanks for clarifying! the thing is that the [Windows CI (powered by AppVeyor)](https://ci.appveyor.com/project/seladb/pcapplusplus/builds/26694500) also fail.

btw, what is the difference between the 2 PRs? Both seem to have the same changes...

**Comment by Dysl3xik** [comment]
I think I finally fixed the issues, I am unsure why my compiler didn't flag these things but hey whatever fixed now. Most of the linux builds have passed, and I suspect win ones should be fine now too.

There seems to still be an issue with the VS build, but its because of usage of std::copy in Common++ (not changes I made) and the windows SDL checks being on. It looks like the release builds are passing but the debug builds are failing because of the SDL checks. 

The two PR are the same except the second one includes changes to VS project files. The second one as it stands will not build without actually supplying the zstd stuff.

I will merge the fixed file changes back into the second PR and then all should be good to go!

**Comment by Dysl3xik** [comment]
OK I checked back in, everything is building now, but it is failing windows debug builds only because of the SDL checks. This happened KINDA because of me...

There was another set of existing code which was checking __cplusplus > 199711L. This is totally broken in every version of VS prior to the most recent 2017, and even then you have to add a special compiler flag to make it report the correct version. I had fixed some sections with this same flaw in a previous PR which you already merged into master by changing the check to __cplusplus > 199711L || _MSC_VER >= 1800. This translates to VS2013+ in visual studio which I believe supports std::copy and such.

However, when I changed this it enabled some code you have already added using std::copy and that ultimately caused the failed build (atleast in Debug). So you can either add the compiler flag -D_SCL_SECURE_NO_WARNINGS to disabled this error as in the error notes, or modify the std::copy code.

That isn't my code though so I will leave that item for you. Aside from this everything SEEMS to be in the clear now. I still can't believe some of these glaring errors were not flagged by the VS compiler on my machine....

**Comment by seladb** [comment]
Please let me review the code and get back to you. But before doing that, I still wonder why you created 2 PRs. Can we close one of them (probably #223)?

I would like to focus on the right PR...

Also, since this PR is quite big, is there a chance you can fork it from `dev` branch? That way we can run more tests before merging it to `master`.

**Comment by Dysl3xik** [comment]
OK. I closed 223. There was 1 extra commit in 223 that added changes to the VS project that actually enabled the build with zstd included. I didn't know any way to share a single commit with you that was why I had 2 PRs. 

For now I agree lets make your focus easy, and integrate the code. We can share notes about fully integrating zstd once you are ready for that later. PR #223 is closed for now.

I am not sure exactly how you wanted me to fork from the dev branch. The "easiest" solution I found was I issued yet another PR, identical to PR #222 but requested to merge into dev branch instead this is PR #224. I am unsure if this is exactly what you wanted, but it says the merge can be done and this is the easiest solution for me. If you intended something else I may be able to help, but hopefully this suffices.

If #224 merge into dev is what you wanted, close #223 and we can hopefully move on.

**Comment by seladb** [comment]
Thank you @Dysl3xik ! PR #224 is perfect so I'll close #222. Please give me some time to review the code and understand the exact source of the build issues on MSVC. I'll get back to you soon.

Thank you again for your continuous contribution to this project, I really appreciate that!

**Comment by Dysl3xik** [comment]
No problem, I am using it for a work application so I am still on the clock :D. Getting these contributions baked in makes it easier in the future to update to latest code without having to maintain our own custom build and potentially have conflicts.

To shorten your search for the MSVC build issue it is specifically this https://github.com/seladb/PcapPlusPlus/pull/224/commits/b2082cf4eb0feb7351a0b7a65a053e8039731b9f#diff-48d622d76da9bf08a86246dceaa63daa which triggered the failed builds.

When i flipped that switch it updated your code to use some newer C++ features specifically some code using std::copy. Apparently microsoft flagged this particular usage of std::copy as potentially risky because it can't check bounds in debug mode. See article discussing this kind of issue here https://devblogs.microsoft.com/cppblog/why-am-i-getting-these-_scl_secure_no_warnings-messages/ . You can either change your call to std::copy, or disable SDL, or similar . I will leave the remaining googling and decision to you.

**Comment by seladb** [comment]
PR #224 is merged, please let me know if we can close this issue

**Comment by Dysl3xik** [comment]
I believe so. Thanks for taking in the merge!

**Comment by Dysl3xik** [comment]
I believe so. Thanks for taking in the merge!
