### ISSUE TITLE
some features of pcap++

### ISSUE THREAD

**Issue by namedjmd** [seladb/PcapPlusPlus#225]
Does pcapplusplus surport modify  pcap file data,such as: src ip or dst ip or the mac?I want to do some security testing by replay the packages from client to server.

**Comment by seladb** [comment]
You cannot edit a pcap file directly but you can read packet by packet from file, edit them (change the IP address etc.) and write them to a new file. Please let me know if that should work

**Comment by seladb** [comment]
please let me know if we can close this issue

**Comment by seladb** [comment]
I'll close it for now, please reopen it if needed
