### ISSUE TITLE
[Bug]: Using 2^16 (which is 2 XOR 16) in NetworkUtils.cpp to get highest port number.

### ISSUE THREAD

**Issue by christinaa** [seladb/PcapPlusPlus#226]
Seems to be a minor bug in `NetworkUtils.cpp`, picked up by Clang:

```
.../third_party/pcapxx/Pcap++/src/NetworkUtils.cpp:391:38: error: result of '2^16' is 18; did you mean '1 << 16' (65536)? [-Werror,-Wxor-used-as-pow]
  int srcPortRange = (2^16) - srcPortLowest;
.../third_party/pcapxx/Pcap++/src/NetworkUtils.cpp:383:23: error: result of '2^16' is 18; did you mean '1 << 16' (65536)? [-Werror,-Wxor-used-as-pow]
  uint16_t transactionID = rand() % (2^16);
```

**Comment by seladb** [comment]
thanks for reporting this issue!

it's strange that Clang doesn't understand 2^16...

**Comment by christinaa** [comment]
Clang does understand it, but `^` operator is a a bitwise XOR in C/C++ (unless overloaded) so `2 ^ 16 = 0b10 xor 0b10000 = 0b10010 = 18`. Some languages treat `^` as exponentiation, hence the confusion, I think.

**Comment by seladb** [comment]
You're right, I got confused with other languages :)

Thanks for the quick fix! I merged the PR
