### ISSUE TITLE
[Windows Testing Error] file open : /proc/[pid]/maps failed

### ISSUE THREAD

**Issue by tylerccg** [seladb/PcapPlusPlus#230]
PCap++ is supposed to work across all OS's however I am getting this Unix type error and can't figure out how to get around it.  Screenshot is attached, please help

![pcap++cap](https://user-images.githubusercontent.com/50339567/63886341-e0cc9e00-c99f-11e9-8956-a8ed0f6fcabe.PNG)

**Comment by tylerccg** [comment]
Thank you for the info, I was hoping to use this as a working example to build a program that would simultaneously capture and filter based off of packet criteria.  Would you have an example that I can go off of?

**Comment by clearcapgroup** [comment]
I found your tutorial directory (sorry for the above comment) however when trying to compile LiveTraffic following the directions I am met with the following: 
![image](https://user-images.githubusercontent.com/11523601/63957012-39a64000-ca4d-11e9-9deb-7afc5356680c.png)

**Comment by tylerccg** [comment]
Just realized I made that comment under the company account^^^it was me though

**Comment by seladb** [comment]
could you please describe how you configured PcapPlusPlus? Are you using MinGW, MinGW-w64 or MSVC?

It'd be great if you can share PcapPlusPlus configuration and build log

**Comment by tylerccg** [comment]
MinGW32 I believe, I was following the guide and its been a couple of days but my install path is: C:\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32 so I'd assume I'm actually using the 32 bit.  Also the logs are attached, let me know anything else you'll need please.  Thanks for the replies
[Pcap++.log](https://github.com/seladb/PcapPlusPlus/files/3559967/Pcap%2B%2B.log)
[Pcap++.Build.CppClean.log](https://github.com/seladb/PcapPlusPlus/files/3559968/Pcap%2B%2B.Build.CppClean.log)

**Comment by seladb** [comment]
Are you sure you're building it using MinGW-w64? from the logs you attached it seems you're building it on MSVC. Please follow the instructions here: 

https://pcapplusplus.github.io/docs/install/build-source/mingw

**Comment by seladb** [comment]
Issue fixed in commit da0496a46cd8257e9f34d95ae5ede4aae1e84238, closing the issue now

**Comment by tylerccg** [comment]
Following the given doc for MinGW32 everything goes as expected until: "Run mingw32-make.exe all from PcapPlusPlus main directory" .... there is no mingw32-make.exe in the directory, ran "cd ..\..\PcapPlusPlus / mingw32-make.exe all" and got command not recognized, which led me to check MinGW directory to which this program is not there.  Any ideas?

**Comment by seladb** [comment]
That's correct. The `mingw32-make.exe` is MinGW `make` command and it's located in MinGW `bin` folder. You can either add it to you path or run it with full path, for example:

Option 1 (add to your `PATH`):

```
C:\PcapPlusPlus> PATH=%PATH%;C:\MinGW\bin
C:\PcapPlusPlus> mingw32-make.exe all
```

Option 2 (run with full path):

```
C:\PcapPlusPlus> C:\MinGW\bin\mingw32-make.exe all
```

**Comment by tylerccg** [comment]
I only have C:\MinGW\bin\mingw-get.exe & pthreadGC-3.dll in the bin dir

**Comment by seladb** [comment]
You should also install `g++` and all of the packages related to `pthreads`. Just go to MinGW installer and add those packages

**Comment by tylerccg** [comment]
Thanks for going through all the twists and turns with me, everything seems to be working.
