### ISSUE TITLE
激光雷达pcap解析

### ISSUE THREAD

**Issue by yhtsywfw** [seladb/PcapPlusPlus#231]
您好！请问pcap能解析成单帧pcd点云吗？

**Comment by seladb** [comment]
I don't understand Chinese, can you please translate to English?

**Comment by yhtsywfw** [comment]
Can PCAP be resolved into a single-frame PCD point cloud?

**Comment by seladb** [comment]
What is single-frame PCD point cloud?

**Comment by yhtsywfw** [comment]
Point cloud data refers to a set of vectors in a three-dimensional coordinate system. These vectors are usually expressed in three-dimensional coordinates of X,Y, and Z, and are typically used primarily to represent the shape of an object's outer surface. In addition to the geometric position information represented by (X,Y,Z), point cloud data can also represent the RGB color, grayscale value, depth, segmentation result, etc.

**Comment by seladb** [comment]
thanks for the thorough explanation. So how is this related to pcap and packet capture?

**Comment by yhtsywfw** [comment]
The packet is a pcap file that wants to parse into a point cloud of every moment.

**Comment by seladb** [comment]
maybe it's a different pcap format? The pcap format supported by PcapPlusPlus is for network packets captured from some network interface. I think the format you're talking about is completely different

**Comment by yhtsywfw** [comment]
yeah,  network packets captured from some network interface.UDP protocol.

**Comment by seladb** [comment]
PcapPlusPlus can decode UDP packets, but it doesn’t support decoding the protocol you’re talking about. You’re of course more than welcome to add this functionality to PcapPlusPlus, I can guide you on how to do it

**Comment by yhtsywfw** [comment]
OK， thanks。

**Comment by seladb** [comment]
Sure, please let me know if we can close this issue

**Comment by yhtsywfw** [comment]
ok，But I don't think I can solve it. I want to give up。

**Comment by seladb** [comment]
I'm closing this issue now. Please reopen it if needed
