### ISSUE TITLE
Centos 7 PCap++Test errors

### ISSUE THREAD

**Issue by tylerccg** [seladb/PcapPlusPlus#232]
Seladb I do not mean to bog you down with issues as I have moved from Windows to one of our Cent servers since pcap seems to be more native to Linux and I figured testing and building would be easier.  It would still be nice to get a clean Windows test but for now that could be put to the side with low priority (I'd rather focus on Linux now).  I've fixed a couple of issues in main.cpp for Pcap++Test however running it, I get a couple of different errors now that I am unsure of.  I am attaching a screenshot for your review, let me know if anything else is needed.  The steps I followed were the following:
https://seladb.github.io/PcapPlusPlus-Doc/download.html and I built with no DPDK nor PF_RING.
![pcap++test](https://user-images.githubusercontent.com/50339567/64031306-bef12980-cb0d-11e9-8913-eed21f7d67e4.PNG)

Its worth noting that the program got stuck at that point and never went any further.

Thank you again for your responsiveness (don't worry about my Windows issue for now 'back log')

**Comment by seladb** [comment]
you should run the tests from the `Pcap++Test` directory, like that: 

```
root@mymachine /home/seladb/PcapPlusPlus/Tests/Pcap++Test (master)$ Bin/Pcap++Test -i 10.1.15.21
```

**Comment by tylerccg** [comment]
Thanks that makes a lot of sense now that I noticed the cUrl dir.  I'm getting other assertion error now and still  getting the MTU larger error that I've received in other examples as well.  How would I fix the MTU error and get passed these assertion failures?
![pcap++test](https://user-images.githubusercontent.com/50339567/64065415-05f52280-cbd3-11e9-8b31-af09a9f2f868.PNG)

**Comment by seladb** [comment]
Yes, one more thing that is required is to have network traffic flowing while the tests are running. Some of the tests expect to capture and analyze TCP or HTTP/HTTPS packets.

**Comment by tylerccg** [comment]
Makes sense, thank you; however, I am still receiving the MTU error and trying to run "Tutorial-LiveTraffic" receives the same error with a different size.  How can I get past this?

![pcap++test](https://user-images.githubusercontent.com/50339567/64200524-53cb8e00-ce52-11e9-9ab4-7e89573d1379.PNG)

**Comment by seladb** [comment]
It seems you're sending Jumbo packets which are larger than the device MTU. You should try to send smaller packets

**Comment by tylerccg** [comment]
is this hard coded in main or is there a command line argument I can pass to the program?  I cannot seem to find the code

**Comment by seladb** [comment]
Here's the line that checks for packet length and throws an error in case packet length is larger than MTU:

https://github.com/seladb/PcapPlusPlus/blob/3df31699b1bcd0325faff9029df0a5d342de9ec3/Pcap%2B%2B/src/PcapLiveDevice.cpp#L545

**Comment by tylerccg** [comment]
Understood but I am assuming using the Tutorial there is some default packets being crafted and sent for tutorial purposes and this is where I am getting the error "Tutorial-LiveTraffic" ; how can I manage those to get them below MTU size?  Or am I just wrong, what packets is this tutorial analyzing?

**Comment by seladb** [comment]
Oh now I understand your question.

What this tutorial does is capture packets from your network and then sending them back to the network. Are you capturing and sending packets to the same interface?

**Comment by tylerccg** [comment]
I'm using everything default besides changing interfaceIPAddr to the IP of my NIC.  Does the tutorial capture and send packets to the same interface?

**Comment by seladb** [comment]
Yes it should. Can you please run the following command in your machine and paste the result?

```
ifconfig| grep -i MTU
```

**Comment by tylerccg** [comment]
em1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
em4: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
p2p1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
p2p2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500

I am using em1 for testing, I know I can change the config in software and it allows the program to run (tested it that way already) but this does nothing for the actual hardware restriction of MTU so I would've thought we could handle this error some other way rather than 'trickery in software'

**Comment by seladb** [comment]
I'm not sure I fully get you... the interface will not allow sending packets which are larger than the MTU. It will either fail or split them into smaller packets. So what is your suggestion?

**Comment by seladb** [comment]
It really depends on the hardware and network infrastructure. Both can happen...

**Comment by tylerccg** [comment]
Okay, thank you for your responsiveness
