### ISSUE TITLE
RawPacketsVector concurrent

### ISSUE THREAD

**Issue by KevinSmild** [seladb/PcapPlusPlus#234]
Hi. I would like to thank you for this nice library, it's much more simpler and C++ish than npcap or libpcap.

I would like to ask a question. Is there any way of making the Async capture with a vector thread concurrent without changing the library code?

**Comment by seladb** [comment]
thanks for the kind words :)

Could you please clarify your question? what do you mean by async capture with a vector thread?

**Comment by KevinSmild** [comment]
Sorry. 
What I meant is if there is a way of making "Asynchronous packet capture using a packet list (vector)" thread safe.

**Comment by KevinSmild** [comment]
I want to capture packets and process them at the same time (without stopping the capture). It would be nicer if I can process a bunch of packets at the same time instead of processing one by one. Hence, I would like to use the "Asynchronous packet capture using a packet list (vector)" capture mode of your library. 

That being said, I have (at least) two threads trying to use the same pcpp::RawPacketsVector, so I was wondering if there is a way of making it thread safe. Or do you have any other suggestion?

**Comment by seladb** [comment]
Thanks for clarifying your question. If I understand your ask, you're currently using the API:

```cpp
PcapLiveDevice::startCapture(RawPacketVector& capturedPacketsVector)
```

And you're looking for a way to start using the packets in the `RawPacketVector` before stopping the capture.

Unfortunately `RawPacketVector` (which is based on `std::vector`) is not thread safe so this may not work. But it's should be pretty easy to make it thread safe by adding a locking mechanism to that class. Please let me know what you think

**Comment by KevinSmild** [comment]
Thanks for your reply.
I'll work on that.

**Comment by seladb** [comment]
Thanks. Please create a PR once you're done and I'll review and merge it

**Comment by seladb** [comment]
hi @KevinSmild please let me know if you have the time to work on this

**Comment by seladb** [comment]
@gx740 what do you think about this?

**Comment by jafar75** [comment]
@seladb If it helps, i want to work on this issue and create PR if done.

**Comment by seladb** [comment]
Sure @jafar75 you're more than welcome! Please go for it, thank you!

**Comment by seladb** [comment]
To be honest, I don't think this is something worth investigating. I'll close this issue

**Comment by muthusaravanan3186** [comment]
can i work on this issue? I need rawpointer vector to be thread safe

**Comment by tigercosmos** [comment]
@muthusaravanan3186  I think it's easy to implement your own wrapper to achieve the goal.

**Comment by seladb** [comment]
@muthusaravanan3186 if you want to contribute, that'd be highly appreciated!

**Comment by tigercosmos** [comment]
make sure to have a proposal before starting the implementation..

**Comment by muthusaravanan3186** [comment]
can we have a mutex on raw pointer vector itself? or we need a lock-free mechanism?

**Comment by seladb** [comment]
> can we have a mutex on raw pointer vector itself? or we need a lock-free mechanism?

I think a mutex is good enough. @tigercosmos what do you think?

**Comment by tigercosmos** [comment]
I am okay with mutex, but not sure about the implementation yet. Later on, better to have a benchmark to see if there is some heavy overhead.

**Comment by seladb** [comment]
@muthusaravanan3186 feel free to suggest your implementation, we can discuss more during the PR review.

**Comment by muthusaravanan3186** [comment]
I am going with standard mutex and condition variable. will create a PR and share
