### ISSUE TITLE
Human Readable Data

### ISSUE THREAD

**Issue by tylerccg** [seladb/PcapPlusPlus#236]
seladb,

I am developing a packet capture, filter, and reader program and am currently working on extracting the raw data from the packets (after I have captured them).  My capture works fine, however when running getRawDataRead() & getRawDataReadOnly() I get some unfamiliar outputs.  I was wondering if you knew the output type (because it does not look like hex to me), and how to parse it into a human readable (most likely utf8) output?  Screenshot of the outputs attached 
![pcap++test](https://user-images.githubusercontent.com/50339567/64453910-452de280-d0af-11e9-8efd-daa151e7cf21.PNG)

Running on Centos 7 x64

**Comment by seladb** [comment]
The method that you mentioned provides a byte array that contains the raw packet data.
What do you mean by human readable data? Would you like to convert it into a hex stream (like 0x363a5f7e...) or extract the actual information in the packet?

**Comment by tylerccg** [comment]
Extract the actual information in the packet so something like bytes-->hex-->utf8

**Comment by seladb** [comment]
You can use [byteArrayToHexString()](https://pcapplusplus.github.io/api-docs/namespacepcpp.html#a13d338c123afbd98ee99a9b2ac78f59a), it takes a byte array and turns it into a hex stream. It is already being used in several places in PcapPlusPlus like here:

https://github.com/seladb/PcapPlusPlus/blob/36e72bc8ad29b9b71c3a51c21c9dff5a28d18ce5/Packet%2B%2B/src/PacketTrailerLayer.cpp#L9

**Comment by tylerccg** [comment]
Sorry to keep bogging you with so many questions as my C++ programming is being learned through this project; I got my hext string from the function above (thank you I didn't see that implementation before) and my output is looking like the following:
"100e7ec5f830d4ae"  ... which clearly looks like hex.  I've searched around online to try to find a way to convert this hex string into a readable string to view the data.  For example, in python I can say "codecs.decode("some_hex_string", "hex").decode('utf-8')" which would output "whatever string that data represents in human readable characters" .  Do you know how I would accomplish such a task?  Ultimately, I would like to view the data and from there decide what to do with that specific packet.  My code looks like the following:

`while (reader->getNextPacket(rawPacket)) {
		//parse raw packet
		pcpp::Packet parsedPacket(&rawPacket);

		//print packet to string
		std::cout << std::endl << parsedPacket.toString() << std::endl << rawPacket.getRawDataLen() << std::endl;
		printf("\n");
		std::cout << pcpp::byteArrayToHexString(rawPacket.getRawDataReadOnly(), sizeof(rawPacket.getRawDataReadOnly(), sizeof(rawPacket.getRawDataReadOnly() + 4))) << std::endl;
		printf("\n");
		std::cout << rawPacket.getRawData() << std::endl;
		printf("\n");
	}`

**Comment by tylerccg** [comment]
....the insert code seems to be broken

**Comment by tylerccg** [comment]
`std::string hex_to_string(const std::string& input)
{
	static const char* const lut = "0123456789ABCDEF";
	size_t len = input.length();
	if (len & 1) throw std::invalid_argument("odd length");

	std::string output;
	output.reserve(len / 2);
	for (size_t i = 0; i < len; i += 2)
	{
		char a = input[i];
		const char* p = std::lower_bound(lut, lut + 16, a);
		if (*p != a) throw std::invalid_argument("not a hex digit");

		char b = input[i + 1];
		const char* q = std::lower_bound(lut, lut + 16, b);
		if (*q != b) throw std::invalid_argument("not a hex digit");

		output.push_back(((p - lut) << 4) | (q - lut));
	}
	return output;
}`

`std::cout << hex_to_string(pcpp::byteArrayToHexString(rawPacket.getRawDataReadOnly(), sizeof(rawPacket.getRawDataReadOnly(), sizeof(rawPacket.getRawDataReadOnly() + 4)))) << std::endl;`

I've tried this and I am getting 'not a hex digit'.

**Comment by seladb** [comment]
I'm sure you're aware that most protocols are [binary protocols](https://en.wikipedia.org/wiki/Binary_protocol), meaning the data is encoded into bytes instead of human readable strings. There are a few exceptions for that like the HTTP and SIP protocols which are string encoded. Because most protocols are binary encoded people need libraries like PcapPlusPlus which provide methods and APIs to interpret the data behind this binary data and understand the information these bytes are representing.

If you're interested in a string summary for each protocol please look into the `toString()` method exposed by each layer. The `Packet::toString()` method aggregates the string information from all underlying layers into one big string.

I hope this answers your question. Please let me know if you need more details.

**Comment by tylerccg** [comment]
I'm sorry but I do believe I have been using that method at this line:
`std::cout << std::endl << parsedPacket.toString() << std::endl;`  
However that's not really what I was looking for.

I understand you would have to decode binary to utf8 as I have decoded binary through other languages and even further proven by me re-working some of my code and I am getting some data to extract but not all of its readable (on another thought, some of the data might be buffer data) but there should be some method in c++ to decode binary to utf8 as encodings and decodings are meant to be done and can be done both ways (while hashing is just a one way operation; binary encoding shouldn't be).  Furthermore, wireshark proves this by being able to display the encapsulated data in a readable form.  I hope that makes sense. (screenshot of part of the partially decoded data below)

![image](https://user-images.githubusercontent.com/50339567/64624350-2762c500-d3b0-11e9-87ce-a36b8983270f.png)


Would you know a cleaner method of decoding the data?

**Comment by seladb** [comment]
I'm still not sure I completely follow you so let me give you an example:

In IPv4 protocol IP addresses (both source and dest) are decoded as 4 bytes. For example, the IP address "12.13.14.15" is decoded as the following 4 bytes: `0x0C 0x0D 0x0E 0x0F`. So in order to decode these 4 bytes into the string "12.13.14.15" you cannot do a simple utf8 decoding. You should be familiar with the protocol and then do the decoding.

Please let me know if that helps. We can also chat more on Slack if you think it'd be more beneficial

**Comment by tylerccg** [comment]
We can slack if that'd be easier, but just to clarify, you have no method to extract the encapsulated payload data into readable characters in string form?

**Comment by seladb** [comment]
yes, that's correct. Please let me know if you'd like to further discuss on Slack

**Comment by tylerccg** [comment]
That'll be it, thank you for your time seladb.
