### ISSUE TITLE
vxlan udp port

### ISSUE THREAD

**Issue by chengwu** [seladb/PcapPlusPlus#239]
else if (portDst == 4789)
      m_NextLayer = new VxlanLayer(m_Data + sizeof(udphdr), m_DataLen - sizeof(udphdr), this, m_Packet);

there are maybe something wrong，vxlan udp port is congifurable

**Comment by chengwu** [comment]
Maybe interface for setup vxlan port is necessary.

**Comment by seladb** [comment]
do you have examples where vxlan port is different that 4789?

**Comment by chengwu** [comment]
rfc-7348 say like this:
 -  Destination Port: IANA has assigned the value 4789 for the
         VXLAN UDP port, and this value SHOULD be used by default as the
         destination UDP port.  Some early implementations of VXLAN have
         used other values for the destination port.  To enable
         interoperability with these implementations, the destination
         port SHOULD be configurable.

**Comment by seladb** [comment]
This is the case with many protocols, there is usually the default port(s) but there may be exceptions for this default.

Unfortunately PcapPlusPlus doesn't currently support changing the default ports for any protocol. If you really need this feature you can either add the port in the code or suggest an implementation of this feature. If you decide to go with the second option I can help and guide you.

**Comment by seladb** [comment]
I'll close the issue for now, please feel free to reopen of you have more questions
