### ISSUE TITLE
TcpReassembly returning different number of packets with two options in input.

### ISSUE THREAD

**Issue by Muhammad-Akram** [seladb/PcapPlusPlus#241]
TcpReassembly is giving different number of packets in a stream while using PCAP as input and receiving same stream on interface as input. I am unable to figure out issue here. Any help will be appreciated.

**Matadata output while using PCAP as input method:**

```
Number of data packets in side 0:  2827
Number of data packets in side 1:  2272
Total number of data packets:      5099

Number of bytes in side 0:         3690832
Number of bytes in side 1:         2025003
Total number of bytes:             5715835

Number of messages in side 0:      862
Number of messages in side 1:      862
```

**Matadata output while receiving same stream on inetface as input method:**

```
Number of data packets in side 0:  1889
Number of data packets in side 1:  2058
Total number of data packets:      3947

Number of bytes in side 0:         3182460
Number of bytes in side 1:         2025003
Total number of bytes:             5207463

Number of messages in side 0:      863
Number of messages in side 1:      863
```

**Comment by Muhammad-Akram** [comment]
It is working fine while using small Streams:

**Matadata output while using PCAP as input method:**
```
Number of data packets in side 0:  24
Number of data packets in side 1:  31
Total number of data packets:      55

Number of bytes in side 0:         20761
Number of bytes in side 1:         21167
Total number of bytes:             41928

Number of messages in side 0:      15
Number of messages in side 1:      15
```

**Matadata output while receiving same stream on inetface as input method:**

```
Number of data packets in side 0:  24
Number of data packets in side 1:  31
Total number of data packets:      55

Number of bytes in side 0:         20761
Number of bytes in side 1:         21167
Total number of bytes:             41928

Number of messages in side 0:      15
Number of messages in side 1:      15
```

**Comment by seladb** [comment]
it seems that you get a different number of packets when you stream packets from a network interface as opposed to the pcap file. This is usually the case because pcap is a "closed environment" where you can control which packets are coming in whereas in a network interface it's usually very difficult to control which packets go on the wire

**Comment by Muhammad-Akram** [comment]
In my environment, I am using tcpreplay to stream packets of the specific PCAP. All the packets are transmitted successfully but TcpReassembly is unable to completely Reassemble the streams.

**Comment by seladb** [comment]
Did you use tcpdump or wireshark to capture the received packets coming from the network? Did you verify all packets are the same?

**Comment by seladb** [comment]
Please let me know if this is still relevant, otherwise we can close it

**Comment by seladb** [comment]
I'll close this issue for now, please reopen it if needed
