### ISSUE TITLE
Incorrect RADIUS packet is decoded as correct

### ISSUE THREAD

**Issue by gx740** [seladb/PcapPlusPlus#242]
Hello.

During decoding of RADIUS packets (refer to `UdpLayer::parseNextLayer` method) the check of correctness of header is not carried out. I think, at least the length of header must be checked (It is better to check the correctness of whole packet with all attributes).

In the attached file is represented the incorrect RADIUS packet for which the `RadiusLayer` is created successfully. The processing of attributes of this packet leads to infinite loop when using following code:
```
for(auto attr = radiusLayer->getFirstAttribute(); attr.isNotNull(); attr = radiusLayer->getNextAttribute(attr))
{
// some code
}

```
In this case I can add the checks to eliminate this issue:
1. Checking the RADIUS header length
2. Checking the length of attribute. It must be at least 2 bytes (`attr.getTotalLength() >= 2`).

But it is not the correct way to fix it.

[radius.zip](https://github.com/seladb/PcapPlusPlus/files/3653587/radius.zip)

**Comment by gx740** [comment]
Moreover I think that the following methods of base class should be overridden in RadiusLayer class:
getFirstAttribute, getNextAttribute, getAttribute, getAttributeCount.
The additional check of attribute length should be added in all methods. If the length less than 2 then the packet is incorrect and method must return TLVRecordType(NULL).
Otherwise the client's code that handles the attributes must have such checks.

**Comment by seladb** [comment]
I agree with you, however these checks are not performed for any of the layers, mostly for performance reasons: parsing the whole layer well in advance will definitely cause performance degradation.

Having said that, we can add basic checks like making sure the layer length is greater than the RADIUS header. Also, we should prevent infinite loop if packet is malformed.

Would you mind making these fixes and create a PR?

**Comment by gx740** [comment]
Yes, I will make changes today

**Comment by seladb** [comment]
Your fix is merged into `master`. Thank you so much for your continuous contribution to this project!
