### ISSUE TITLE
.pcap files of normal traffic (does not contain malicious traffic)

### ISSUE THREAD

**Issue by asif48** [seladb/PcapPlusPlus#246]
Sir can I have .pcap files of only normal traffic?

That must not contain malicious traffic...

**Comment by seladb** [comment]
sure, you don't need me for that, you can simply google it :)

Here are a few web-sites you can consider:

https://wiki.wireshark.org/SampleCaptures

https://packetlife.net/

https://cloudshark.io/ (if you know which traffic you're looking for)

https://pcapr.net/home

You can also capture traffic from you own machine using Wireshark or tcpdump

**Comment by asif48** [comment]
Thanks very much ...
I was not been able to find that sites initially when I googled...
Glad to see your immediate response.

 

With Best Regards

Asif Rehman


OH ALLAH! Make useful for me what You taught me
and teach me knowledge that will be useful to me!

 

 
 

    On Sunday, September 29, 2019, 11:43:02 AM GMT+5, seladb <notifications@github.com> wrote:  
 
 
sure, you don't need me for that, you can simply google it :)

Here are a few web-sites you can consider:

https://wiki.wireshark.org/SampleCaptures

https://packetlife.net/

https://cloudshark.io/ (if you know which traffic you're looking for)

https://pcapr.net/home

You can also capture traffic from you own machine using Wireshark or tcpdump

**Comment by asif48** [comment]
One thing more...

I want to have .binetflow files also along with .pcap files.

**Comment by seladb** [comment]
I'm not sure what .binetflow files are...
