### ISSUE TITLE
cannot find -lgcc_s

### ISSUE THREAD

**Issue by counsellors** [seladb/PcapPlusPlus#25]
I'm attemping to build PcapTest++Test, then get the following error:

```
uname is: Linux
Building target: Pcap++Test
Invoking C++ Linker
g++ -L/home/moshe/git/PcapPlusPlus/Dist -L/home/moshe/git/PF_RING/kernel//userland/lib  -o "./Bin/Pcap++Test" Obj/main.o -lPcap++ -lPacket++ -lCommon++ -lpcap -lpthread -Wl,-Bstatic -lpfring -lnuma -lrt
/usr/bin/ld: cannot find -lgcc_s
/home/moshe/git/PcapPlusPlus/Dist/libCommon++.a(debug_new.o): In function `memset':
/usr/include/x86_64-linux-gnu/bits/string3.h:81: warning: memset used with constant zero length parameter; this could be due to transposed parameters
/usr/bin/ld: cannot find -lgcc_s
collect2: error: ld returned 1 exit status
make: *** [Pcap++Test] Error 1
```
The compiler version is:
  g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

and I could find the lib file *libgcc_s.so.1*.
```
sudo ldconfig -p |grep gcc
	libuno_salhelpergcc3.so.3 (libc6,x86-64) => /usr/lib/libuno_salhelpergcc3.so.3
	libuno_purpenvhelpergcc3.so.3 (libc6,x86-64) => /usr/lib/libuno_purpenvhelpergcc3.so.3
	libuno_cppuhelpergcc3.so.3 (libc6,x86-64) => /usr/lib/libuno_cppuhelpergcc3.so.3
	libgccpp.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgccpp.so.1
	libgcc_s.so.1 (libc6,x32) => /usr/libx32/libgcc_s.so.1
	libgcc_s.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libgcc_s.so.1
	libgcc_s.so.1 (libc6) => /usr/lib32/libgcc_s.so.1
	libgcc_s.so (libc6,x86-64) => /usr/local/lib/libgcc_s.so
```

**Comment by seladb** [comment]
I see you're trying to compile PcapPlusPlus with PF_RING. Did you also try to compile it without PF_RING? Did you succeed? This can help focus on the problem.
Please run _./configure-linux.sh_ and choose not to configure PF_RING compilation.
Then run _make clean_ and then _make all_ and tell me what happened

**Comment by counsellors** [comment]
It's successful to build target Pcap++Test without PF_RING after processing following your way。Is there any problem in PF_RING building?

I getted PF_RING from git site: [https://github.com/ntop/PF_RING.git](https://github.com/ntop/PF_RING.git)
build it with official suggestion:
```
cd PF_RING/kernel
make
sudo insmod ./pf_ring.ko
cd ../userland
make
```
libpfting.so would be created to link to this program.

**Comment by seladb** [comment]
I found the bug - it was redundant flags in the makefile for pf_ring. I removed these flags and now everything compiles and run
