### ISSUE TITLE
Memory Leak pcapng reader

### ISSUE THREAD

**Issue by Dysl3xik** [seladb/PcapPlusPlus#253]
I think I found a pretty big memory leak in my rework of the pcapng code.

in light_pcapng.c please add 
`free(local_data);`
to line 358
just before `*record = current;`

![image](https://user-images.githubusercontent.com/21955286/66226902-eb1e3e00-e6a9-11e9-8d53-6c0154666a44.png)

**Comment by Dysl3xik** [comment]
Sorry I don't have time to issue PR myself right now, but this should fix the issue!

**Comment by seladb** [comment]
sure, I can make the fix and test it
