### ISSUE TITLE
Issue in setDeviceMacAddress

### ISSUE THREAD

**Issue by mvpete** [seladb/PcapPlusPlus#26]
Hey there,

I think you have a bug in the setDeviceMacAddress. Firstly, thank you for making this library. I've been looking all over for an easy way to get a device MAC address in searching I found this to use a reference.

I believe that you need to actually allocate enough memory for your packet. Right now you're stomping over the stack when you do the packet request, because the PACKET_OID_DATA structure only has enough data for 1 byte.

So you need to allocate enough memory for the PACKET_OID_DATA and the MAC (6Bytes).

Also, just as a quick style comment. I've seen you have using std; in header files. This pollutes namespaces and you shouldn't force people using your library to get the entire std namespace brought into their project.

**Comment by seladb** [comment]
Thanks for the feedback, I'll look into it and fix it

**Comment by seladb** [comment]
You were right on both issues, I fixed them both. Thanks again!
