### ISSUE TITLE
eth 802.3 EOIP support

### ISSUE THREAD

**Issue by dayexi** [seladb/PcapPlusPlus#263]
Could you please add compatibility for eth 802.3?

in[ this link](https://kevincurran.org/com320/labs/wireshark/lab-ethernet.pdf)  in page 8, pcapplusplus can not get next layer of the ethernet and so on. In the code, 6byte mac + 6byte mac + 2 byte protocol type are read from the first 14 bytes but, the last 2 bytes are not protocol type, these 2 bytes demonstrate the length of full packet. How do we determine that these two bytes are proto type or length? Also in Ethernet over Ip (EOIP) protocols, the frames are sent after ip.

An example pcap: (please look at 3 frames at the end of pcap file)
https://kevincurran.org/com320/labs/wireshark/trace-ethernet.pcap

[A cheatsheet](https://packetlife.net/library/cheat-sheets/) for understanding the types of protocols that may be useful.

**Comment by seladb** [comment]
I'm not sure how to differentiate between Eth 802.3 to "standard" Eth. Do you know how Wireshark does it?

**Comment by dayexi** [comment]
I didnt but i will. Maybe the protocol number can not be lower than a value and it is determined in this way. I edited the length field of eth802.3 pcap sample in hex editor and changed the length to "08 00". Then wireshark  dissected the next packet as broken ip packet.

In the code, I have faced a few same warning in [this line:](https://github.com/seladb/PcapPlusPlus/blob/f25cf80f5fe4c5f9b837edfda775c57e04585d36/Packet%2B%2B/header/IPReassembly.h#L208) and don't want to create new issue. Dealed with it but didn't solved this warning. Using QT and gcc4.8x

> In copy constructor  pcpp::IPReassembly::IPv4PacketKey::IPv4PacketKey(const pcpp::IPReassembly::IPv4PacketKey&)';
> base class 'class pcpp::PacketKey' should be explicitly initialized in the copy constructor [-Wextra]

**Comment by seladb** [comment]
You can find Wireshark source code here: https://www.wireshark.org/download/automated/src/
If you can find out how Wireshark does it we can imitate the same logic.

Regarding the warning - please ignore it for now if possible

**Comment by seladb** [comment]
@dayexi please let me know if you can look into it

**Comment by dayexi** [comment]
> @dayexi please let me know if you can look into it
i found [this](https://www.wireshark.org/lists/wireshark-users/200803/msg00089.html)  but  i think it is not an exact solution.

**Comment by seladb** [comment]
I found the code in Wireshark that makes this decision, you can view it [here](https://code.wireshark.org/review/gitweb?p=wireshark.git;a=blob;f=epan/dissectors/packet-eth.c;h=fdd8496c85d17fcd86ade3171698c27e6590199f;hb=HEAD#l224).

>  223   /*
 224    * If the type/length field is <= the maximum 802.3 length,
 225    * and is not zero, this is an 802.3 frame, and it's a length
 226    * field; it might be an Novell "raw 802.3" frame, with no
 227    * 802.2 LLC header, or it might be a frame with an 802.2 LLC
 228    * header.
 229    *
 230    * If the type/length field is >= the minimum Ethernet II length,
 231    * this is an Ethernet II frame, and it's a type field.
 232    *
 233    * If the type/length field is > maximum 802.3 length and < minimum
 234    * Ethernet II length, then this is an invalid packet.
 235    *
 236    * If the type/length field is zero (ETHERTYPE_UNK), this is
 237    * a frame used internally by the Cisco MDS switch to contain
 238    * Fibre Channel ("Vegas").  We treat that as an Ethernet II
 239    * frame; the dissector for those frames registers itself with
 240    * an ethernet type of ETHERTYPE_UNK.
 241    */

Also:

```c
#define ETHERNET_II_MIN_LEN		1536
#define IEEE_802_3_MAX_LEN		1500
```

I think this much explains the logic. We can implement the same in PcapPlusPlus. Please let me know what you think

**Comment by seladb** [comment]
@dayexi please let me know what you think. Do you want to implement this functionality in PcapPlusPlus and create a PR?

**Comment by seladb** [comment]
@gx740 what do you think about this?

**Comment by seladb** [comment]
@dayexi please let me know if you're planning to work on that. Otherwise I can try to implement that

**Comment by seladb** [comment]
Done, please see the documentation here: https://pcapplusplus.github.io/api-docs/classpcpp_1_1_eth_dot3_layer.html
