### ISSUE TITLE
Why the source code does not use try-catch?

### ISSUE THREAD

**Issue by gx740** [seladb/PcapPlusPlus#265]
I have found a packet (a bogus IPv4 packet) that forces the `IPReassembly::processPacket` to throw the `bad_alloc`. Having looked the code I have found that `try-catch` block has never been used. For example:
```
// create a new IPFragment and copy the fragment data and params to it
IPFragment* newFrag = new IPFragment();
newFrag->fragmentOffset = fragWrapper->getFragmentOffset();
newFrag->fragmentData = new uint8_t[fragWrapper->getIPLayerPayloadSize()];
newFrag->fragmentDataLen = fragWrapper->getIPLayerPayloadSize();

```
If the second allocation fails we get a memory leak.
Why try-catch block was not added in this case? The use of try-catch has low (even zero) performance overhead when an exception is not being thrown.

Possible decision:
```
// create a new IPFragment and copy the fragment data and params to it
IPFragment *newFrag = new IPFragment();
try
{
  newFrag->fragmentOffset = fragWrapper->getFragmentOffset();
  newFrag->fragmentData = new uint8_t[fragWrapper->getIPLayerPayloadSize()];
  newFrag->fragmentDataLen = fragWrapper->getIPLayerPayloadSize();
  memcpy(newFrag->fragmentData, fragWrapper->getIPLayerPayload(), newFrag->fragmentDataLen);
  newFrag->lastFragment = fragWrapper->isLastFragment();

  // store the IPFragment in the out-of-order fragment list
  fragData->outOfOrderFragments.pushBack(newFrag);

  status = OUT_OF_ORDER_FRAGMENT;
  return NULL;
}
catch(...)
{
  delete newFrag;
  throw;
}

```

**Comment by gx740** [comment]
I've prepared PR #266.

**Comment by seladb** [comment]
yes I understand, however if we can avoid try-catch and handle the edge cases it'd be better. Please let me know if this is possilbe

**Comment by gx740** [comment]
For this certain case I have prepared the PR #269 which lets not to use try-catch.

**Comment by echo-Mike** [comment]
The #269 must not be merged and this suggestion makes no sense and that is why:
all cases covered by #269 in true C++ way must be handled not by try...catch blocks which is considered a __code smell__ but with proper use of smart pointers. For the case of Pcap++ that will be the std::auto_ptr (as We are in the realm of C++98, which must be changed ASAP by the way).

**Comment by seladb** [comment]
@gx740 just to make sure: is PR #269 replaces #266? In that case, can we close #266?

@echo-Mike it seems #269 doesn't contain any try...catch block, why shouldn't it be merged?

**Comment by gx740** [comment]
PR #266 can be closed

**Comment by gx740** [comment]
@echo-Mike: it is a good idea to use smart pointers. But this library is using raw pointers in all places so it is needed to rework whole library. I am not using the std::auto_ptr because there is a unique_ptr in C++11 but I found that there are restrictions in using of std::auto_ptr, such as:
- it cannot contain a pointer to array
- it cannot be used in containers of Standard Library

**Comment by seladb** [comment]
PR #269 doesn't have any try-catch blocks. @gx740 I've reviewed the PR and added a few comments.

@echo-Mike please feel free to review the PR as well and let us know if you have any concerns

**Comment by seladb** [comment]
PR #269 merged
