### ISSUE TITLE
Pollution of global namespace

### ISSUE THREAD

**Issue by mkaes** [seladb/PcapPlusPlus#27]
The library does not live in a namespace and is polluting the global namespace.
It would be nice if the library uses a namespace for all types and a prefix for all defines.
The issue can be reproduced by the following code snippet.

    #include <iostream>
    #include <boost/asio.hpp>
    #include "TcpLayer.h"
    int main() {
        return 0;
    }

This leads on a Kubuntu 16.04 to the following error:
>In file included from ../src/main.cpp:14:0:
/opt/pcapplusplus/header/TcpLayer.h:14:8: error: redefinition of ‘struct tcphdr’
> struct tcphdr {
>        ^
>In file included from /usr/include/boost/asio/detail/socket_types.hpp:73:0,
>                 from /usr/include/boost/asio/detail/epoll_reactor.hpp:30,
>                 from /usr/include/boost/asio/detail/reactor.hpp:21,
>                 from /usr/include/boost/asio/detail/impl/task_io_service.ipp:24,
>                 from /usr/include/boost/asio/detail/task_io_service.hpp:198,
>                 from /usr/include/boost/asio/impl/io_service.hpp:71,
>                 from /usr/include/boost/asio/io_service.hpp:767,
>                 from /usr/include/boost/asio/basic_io_object.hpp:19,
>                 from /usr/include/boost/asio/basic_socket.hpp:20,
>                 from /usr/include/boost/asio/basic_datagram_socket.hpp:20,
>                 from /usr/include/boost/asio.hpp:21,
>                 from ../src/main.cpp:13:
>/usr/include/netinet/tcp.h:82:8: error: previous definition of ‘struct tcphdr’
> struct tcphdr
>        ^
>/opt/pcapplusplus/header/TcpLayer.h:81:2: error: expected identifier before numeric constant
>  TCPOPT_NOP =    1,
>  ^
>/opt/pcapplusplus/header/TcpLayer.h:81:2: error: expected ‘}’ before numeric constant
>/opt/pcapplusplus/header/TcpLayer.h:81:2: error: expected unqualified-id before numeric constant
>In file included from ../src/main.cpp:14:0:
>/opt/pcapplusplus/header/TcpLayer.h:128:1: error: expected declaration before ‘}’ token
>};

I will create a pull request how I fixed this issue for me. Maybe it is helpful.

**Comment by seladb** [comment]
I merged your pull request to master and added the namespace to additional examples and files. I verified it compiles on Ubuntu, Windows and Mac OS.
Thanks for the fix!
