### ISSUE TITLE
[BUG] Incorrect TCP payload size check

### ISSUE THREAD

**Issue by rickyzhang82** [seladb/PcapPlusPlus#271]
Line 207-211 is useless size check. 

Do you intend to compare the total length defined in IPV4 header with TCP payload size in this check? 

https://github.com/seladb/PcapPlusPlus/blob/f25cf80f5fe4c5f9b837edfda775c57e04585d36/Packet%2B%2B/src/TcpReassembly.cpp#L195-L211

**Comment by seladb** [comment]
You're right, this is indeed a bug that was introduced in this commit: https://github.com/leoxiaofei/PcapPlusPlus/commit/4dc34581b44304c5af454e824481e15adc98c55f

I guess we can either remove:
https://github.com/seladb/PcapPlusPlus/blob/f25cf80f5fe4c5f9b837edfda775c57e04585d36/Packet%2B%2B/src/TcpReassembly.cpp#L207-L211

Or re-enable the code that checks the IPv4 data. What do you think?

**Comment by rickyzhang82** [comment]
Both IPv6 and IPv4 provides payload size in their header. But if we don't trust whatever defines in IP headers and override the payload size with our measured result, why we should enable a check?

IMO, remove the check.

**Comment by seladb** [comment]
makes sense. would you like to submit a PR with the fix or prefer me to fix it?

**Comment by rickyzhang82** [comment]
See PR #273

**Comment by seladb** [comment]
Let's keep it opened until the PR is merged

**Comment by seladb** [comment]
PR merged
