### ISSUE TITLE
Buffered Reading (from file io) of Raw Packet Files

### ISSUE THREAD

**Issue by jaredkeithwhite** [seladb/PcapPlusPlus#274]
Occasionally I need to reprocess very large pcap files.  I am using the `PcapFileReaderDevice` for this purpose.  I am curious if there are ways I can set the buffer size for buffered reading and writing?

**Comment by seladb** [comment]
`PcapFileReaderDevice` uses libpcap/WinPcap file reading capabilities which are already buffered, meaning it reads one packet at a time and it doesn't load the entire file into memory. I hope this answers your question, please let me know if you need more details

**Comment by seladb** [comment]
I'm closing this issue for now, please reopen if needed

**Comment by jaredkeithwhite** [comment]
Hi there, apologies I just saw that you had commented on this issue.  Have you considered exposing some of the buffering behavior so that we can control the size of buffering?

**Comment by seladb** [comment]
I'm not sure the buffer size is even exposed by libpcap/WinPcap. Do you know otherwise?

**Comment by jaredkeithwhite** [comment]
My consideration would be to use this API:
```
pcap_t *pcap_fopen_offline(FILE *fp, char *errbuf)

```
Coupled with `fopen` and a call to `setbuf`, here:

http://www.cplusplus.com/reference/cstdio/setbuf/

Would that work?

**Comment by seladb** [comment]
This may be possible, needs to be carefully tested. I'm still not sure though why the buffer size matters in your case. Did you find any limitations with the default buffer size?

**Comment by jaredkeithwhite** [comment]
I spin through 50-100gb worth of offline pcap files hundreds of times a
day.  So IO buffering is rather important to my use case.

**Comment by seladb** [comment]
Sure, I get that. But isn't the default buffer size sufficient for such large files? Could you please describe issues you're seeing with such files?

**Comment by jaredkeithwhite** [comment]
I would likely set a 25-50% file-size buffer for the files that I run and
run IO loading in a separate thread.  It's running on several SSDs in a
RAID0 already so at this point the disk can't get much faster.

At this point I'm optimizing the minutia because the remainder of the
software and hardware is effectively tapped out.

-Jared

**Comment by seladb** [comment]
sure, that makes sense. You can try to implement the solution you suggested and we can merge it later to the main branch. Please let me know if you need my help
