### ISSUE TITLE
httpstats only support port 80 & 8080?

### ISSUE THREAD

**Issue by ugenehan** [seladb/PcapPlusPlus#275]
httpstats only support port 80 & 8080?can not support other port?

**Comment by seladb** [comment]
yes, as of now the are the only supported ports:

https://github.com/seladb/PcapPlusPlus/blob/2eee2ad31ae37ce6bf3c70d21d85961aaf787d69/Packet%2B%2B/src/HttpLayer.cpp#L13-L19

Would you like to add a new port to this map?

**Comment by ugenehan** [comment]
> yes, as of now the are the only supported ports:
> 
> https://github.com/seladb/PcapPlusPlus/blob/2eee2ad31ae37ce6bf3c70d21d85961aaf787d69/Packet%2B%2B/src/HttpLayer.cpp#L13-L19
> 
> Would you like to add a new port to this map?

Many enterprise systems have custom ports.I have defined a static function in class 'HttpMessage',it can add port to HTTPPortMap.

**Comment by seladb** [comment]
I'm not sure adding custom specific port will be useful for many people. Do you have a suggestion to make it more generic?

**Comment by seladb** [comment]
I'm closing the issue for now, please reopen if needed

**Comment by gx740** [comment]
I can give an idea how to implement the support of any port number if needed.

**Comment by seladb** [comment]
thanks @gx740 , please feel free to suggest your ideas

**Comment by gx740** [comment]
The idea is ready for discussion in PR #298.
