### ISSUE TITLE
Does pcapluplus support dpdk Virtio_user for Container Networking？

### ISSUE THREAD

**Issue by Baby4eveR** [seladb/PcapPlusPlus#276]
Can I build pcapplusplus with dpdk to monitor pcakets in docker？Or how can I  process pcakets via sokcet file？
![fe654754b7acf2e586e899b39de80a2](https://user-images.githubusercontent.com/20334442/67752924-d9dd0d00-fa6e-11e9-94b5-40fcd3943f75.png)

**Comment by seladb** [comment]
I'm not sure how DPDK works in a container environment. Do you have some experience around that? If you do, I'll be glad to learn more about it.

**Comment by seladb** [comment]
I'm closing this issue for now due to lack of responsiveness, please reopen it if needed
