### ISSUE TITLE
IPReassembly not properly working

### ISSUE THREAD

**Issue by silviucpp** [seladb/PcapPlusPlus#280]
Hello,

I have a pcap  which has one UDP packet fragmented. Running `IPReassembly` when I receive the resembled packet the UDP layer still doesn't exist and it's seen as `PayloadLayer`.

Doing a debug I see that the creation of `reassembledPacket` is done as follow:

```c++
Packet* reassembledPacket = new Packet(fragData->data, true, parseUntil, parseUntilLayer);

if (fragData->packetKey->getProtocolType() == IPv4)
{
    // set the fragment offset to 0
    IPv4Layer* ipLayer = reassembledPacket->getLayerOfType<IPv4Layer>();
    ipLayer->getIPv4Header()->fragmentOffset = 0;

    // re-calculate all IPv4 fields
    ipLayer->computeCalculateFields();
}
else
{
    // remove fragment extension
    IPv6Layer* ipLayer = reassembledPacket->getLayerOfType<IPv6Layer>();
    ipLayer->removeAllExtensions();

    // re-calculate all IPv4 fields
    ipLayer->computeCalculateFields();
}		

```
Problem is that in Packet constructor all layers are parsed and here `fragmentOffset` is not 0 . It's equal with the one from first fragmented packet. Setting this one to 0 it's done later after all layers are parsed.

This makes `IPv4Layer` to execute:

```c++
if (isFragment())
{
    m_NextLayer = new PayloadLayer(m_Data + hdrLen, m_DataLen - hdrLen, this, m_Packet);
    return;
}
```

Which leads to a wrong layer.

**Comment by silviucpp** [comment]
You can test using the following pcap:

[save4.pcap.zip](https://github.com/seladb/PcapPlusPlus/files/3795488/save4.pcap.zip)

**Comment by seladb** [comment]
Let me check and get back to you

**Comment by silviucpp** [comment]
Hello,

I will  check this in a few days and let you know if works or not .

Silviu

**Comment by seladb** [comment]
Merged to `master`
