### ISSUE TITLE
LRUList: the complexity of method "put": is not O(1)

### ISSUE THREAD

**Issue by gx740** [seladb/PcapPlusPlus#281]
This method has the following code:
```
if (m_CacheItemsList.size() > m_MaxSize)
{
  ListIterator lruIter = m_CacheItemsList.end();
  lruIter--;
  T* deletedValue = new T(*lruIter);
  m_CacheItemsMap.erase(*lruIter);
  m_CacheItemsList.erase(lruIter);

  return deletedValue;
}
```
`m_CacheItemsList` is of type `std::list`. Unfortunately, the complexity of method `size` of linked list can be O(n) (refer to https://en.cppreference.com/w/cpp/container/list/size). The C++ standard guarantees the constant complexity for C++ 11 and newer. We need to rework this method because it is the significant impact on performance (LRUList is used by IPReassembly).

I have made the tests under CentOS-7 with g++ 8.3.1 and got that one call of `size()` is performed 2.4 milliseconds (the size of list was 500000). The same result will be for the default compiler (g++ 4.8).

I suggest to use an internal counter of elements stored in `m_CacheItemsList`.

**Comment by gx740** [comment]
If `m_CacheItemsList` contains the same number of elements as `m_CacheItemsMap` then we can use its method instead of creating internal counter.

**Comment by gx740** [comment]
Besides this method does not have the complexity O(1) at all because inserting into the map has O(log(size)).

**Comment by seladb** [comment]
You make a good point about the complexity of this method being more than O(1), I wasn't aware that `size()` doesn't guarantee complexity of O(1). Can you suggest a fix for that?

**Comment by gx740** [comment]
PR is almost ready

**Comment by seladb** [comment]
awesome, thanks!

**Comment by gx740** [comment]
The issue can be closed.
