### ISSUE TITLE
sending packet using PcapPlusPlus is not working 

### ISSUE THREAD

**Issue by mnjthk** [seladb/PcapPlusPlus#286]

**Comment by mnjthk** [comment]
I am trying to read from the captured file and changing their destination IP address and sending them.
All is going well till packet editing when sending them to the network is getting issues. 
while sending them to my own machine (source and destination IP is the same) my Wireshark captured those packets, but while sending them to different destination IP destination, my program showing sending them successfully, but Wireshark on the destination machine not able captured them.
[CraftingandSending.txt](https://github.com/seladb/PcapPlusPlus/files/3807756/CraftingandSending.txt)

**Comment by seladb** [comment]
It seems you're trying to change both IP address as will as MAC address. Depends on your network configuration, changing the MAC address may or may not work. Try to do the same without changing the MAC address and see if that works

**Comment by mnjthk** [comment]
Thanks for the quick reply. I just tried twice without changing the MAC address, still, it is not working for other destination IP machine, but it is ok on my own machine (sending to my own IP address).

**Comment by seladb** [comment]
I was wrong regarding the MAC address. I'm not sure from where the packets you're reading from the pcap file came from, but assuming the dest MAC address is not set to the MAC address of your gateway, the packets will be routed to an unknown destination. You should check your gateway MAC address and set the dest MAC to that address. If you're not sure what it is you can simply capture "regular" network traffic from your machine to the other machine using Wireshark and see what the MAC address is

**Comment by mnjthk** [comment]
I am still stuck. If we do not change MAC address and even though we only change destination IP and then send it.
(dev->send(...........) It should work as well as  Tutorials describe.
Thank you so much for your quick reply.

**Comment by seladb** [comment]
Yes this should work, however in order for packets to reach from one point to another you have to follow the routing rules. There are probably network devices (routers, switches, etc.) between your 2 devices that route network traffic based on different parameters such as MAC addresses, IP addresses an so on. There also might be firewalls blocking traffic from certain IP addresses or ports. You need to understand your network better in order to craft packets and send them over the network. Please let me know how I can help

**Comment by mnjthk** [comment]
Suppose we have raw packets save in a particular pcap file of  Wireshark. Using PcapPlusPlus API, we alter just destination IP of packets and save raw packets getting from using parsedPacket.getRawPacket() in a new pcap Wireshark file.
I want to know that whether the capture-file link-layer and newly created file link layer would be the same or not? 
Because I came to know that before sending packets to the network, it is important that the capture-file link-layer should be the same as the adapter's link-layer for otherwise, the transmission is pointless.

**Comment by seladb** [comment]
It depends how you create the pcap file writer. The default link layer in the constructor is Ethernet but you can change it to something else. Please take a look at [PcapFileWriterDevice documentation](https://pcapplusplus.github.io/api-docs/classpcpp_1_1_pcap_file_writer_device.html#a46b3b5c1ffed33d3540fa40db94010e2)

**Comment by seladb** [comment]
I'm closing this issue now, please reopen if needed

**Comment by mnjthk** [comment]
Sending packets to different destination IP is not working. I tried everything, but no luck. Reading from captured pcap file Wireshark and changing his destination IP and sending using PacpPlusPlus API is not working. Even I tried Wpcap for sending packets, showing status "Packets send" But not captured in Wireshark in the destination IP 's machine. Right now crafting packets and storing it to a new file as raw packets is successful but sending packets reading from this file using PcapPlusPlus or Wpcap is not working But return sending true. Please help and share with me if you have any Idea.

**Comment by seladb** [comment]
as I said before, it really depends on the configuration of your network. You can try is the following:

- Start with TCP. Choose a TCP port that you have in your pcap file
- Use `netcat` or some other tool to open a TCP connection on this port between the two machines
- Use Wireshark to capture the packets that are being sent and received
- Modify the packets on your pcap file that match this TCP port: change their MAC addresses, IP addresses and the rest of the Ethernet, IP and TCP params to match the ones you saw in the captured packets
- Use PcapPlusPlus to send these packets to the other machine and check if you see them

**Comment by shscy** [comment]
are  you using macos  ? maybe it can hep you  [https://forums.freebsd.org/threads/solved-creating-and-transmitting-raw-ip-packets.44058/](url)
