### ISSUE TITLE
'in.h' file not found #include <in.h>

### ISSUE THREAD

**Issue by tristancode** [seladb/PcapPlusPlus#29]
Hello 
I am running on Mac OS X and getting this probleme 

And have an issue when running the DNSSpoof example file.. Please help
Full Error: 

main.cpp:16:10: fatal error: 'in.h' file not found
#include <in.h>

**Comment by seladb** [comment]
Which Mac OS X version are you running?

**Comment by tristancode** [comment]
This worked the info you gave me fixed my issue.!

**Comment by seykuyinu** [comment]
Hi, 

I'm having the same issue when trying to compile PcapPlusPlus on OSX. I'm running on Yosemite, with Xcode 6.4. The error I get is:

> src/GreLayer.cpp:16:10: fatal error: 'in.h' file not found
> #include <in.h>

I've tried re-installing X-code developer tools, as well as using a different installation of g++, but no luck. 

Any help would be appreciated!

**Comment by seladb** [comment]
Can you please send me the entire compilation output until the error occurs?
Please run "make clean" before you run "make all"

**Comment by seykuyinu** [comment]
Here it is: [compilation.txt](https://github.com/seladb/PcapPlusPlus/files/380416/compilation.txt)

**Comment by seladb** [comment]
Did you run:
`./configure-mac_os_x.sh`
before you started compiling? If not, please run this configuration script, then run "make clean" and "make all". 
If you did run it, please check if you have the following directory: /usr/include/netinet
If you don't have it, it means the XCode developer tools weren't installed correctly for some reason

**Comment by seladb** [comment]
Fixed in [this commit](https://github.com/seladb/PcapPlusPlus/commit/2b8b254085bdaf8b9048461c81d470d94bfb9c9f)
