### ISSUE TITLE
Changing the type of return value in method SSLLayer::getSSLPortMap (discussion)

### ISSUE THREAD

**Issue by gx740** [seladb/PcapPlusPlus#290]
This method returns `std::map`. I suggest to change the type of return value to `std::vector` because the searching on vector is much faster than on the map especially when the size of vector is small.
I have made the tests and got that serial lookup in vector is the fastest.

Results of tests:
```
Serial search in vector by std::find: duration(ms): 112, count: 1000000
Serial search in vector by loop: duration(ms): 45, count: 1000000
Binary search in vector: duration(ms): 361, count: 1000000
Search in map: duration(ms): 1071, count: 1000000
Walking the map: duration(ms): 793, count: 1000000
```
Source code of tests:
[test.zip](https://github.com/seladb/PcapPlusPlus/files/3809682/test.zip)

**Comment by seladb** [comment]
how come serial search on a vector is faster than map search??

also, are these numbers true in smaller size as well?

**Comment by gx740** [comment]
> How come a serial search on a vector is faster than a map search?
The main reason, I think, is that the vector is cache friendly so the small vector/array is totally loaded into L1 cache at once. The lists, maps, trees are not cache friendly. Another reason is that the algorithm of serial lookup is simpler than binary search and tree search. It gives less the false branch predictions.

> also, are these numbers true in maps/vectors with smaller sizes?
As I had shown before the lookup in maps is slower than in arrays even for small maps. The tests had been made on containers with small size (the size is 14).

 > I guess PR #288 is related to this issue right?
No, it does not cover this case.

**Comment by gx740** [comment]
In test results the count means the total number of iterations not the size of container. I wrote incorrectly.

**Comment by gx740** [comment]
For big containers serial lookup is not applicable. But if the vector/array is ordered the binary search is faster than tree search. I have made tests again :) The size of containers is 1 000 000 and these contain the numbers from 1 to 1 000 000.

Test results:
1. The worst case: searching of 1 000 000:
```
Search in map: duration(ms): 3448, iterations: 1000000
Binary search in vector: duration(ms): 1132, iterations: 1000000
```
2. Searching of 500 000:
```
Search in map: duration(ms): 2089, iterations: 1000000
Binary search in vector: duration(ms): 1120, iterations: 1000000
```
3. Searching of 1:
```
Search in map: duration(ms): 1831, iterations: 1000000
Binary search in vector: duration(ms): 903, iterations: 1000000
```

The tests have been made under Win10 + VS2019 + Core i7 9700K.

```
#include <vector>
#include <map>
#include <cstdint>
#include <chrono>
#include <iostream>
#include <algorithm>

void testLookupBigContainer()
{
  constexpr auto tryCount = 1000000U;
  constexpr auto numToSearch = 1U;
  constexpr auto maxSize = 1000000;

  std::map<uint32_t, bool> map;
  std::vector<uint32_t> vec;
  vec.reserve(maxSize);

  for(auto i = 1U; i <= maxSize; ++i)
  {
    map[i] = true;
    vec.push_back(i);
  }

  // searching in map
  uint32_t count = 0;
  auto startTime = std::chrono::steady_clock::now();

  for(auto i = 0U; i < tryCount; ++i)
    if(map.find(numToSearch) != map.cend())
      ++count;

  auto duration = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now() - startTime);
  std::cout << "Search in map: duration(ms): " << duration.count() << ", iterations: " << count << '\n';

  // binary searching in vector
  count = 0;
  startTime = std::chrono::steady_clock::now();

  for(auto i = 0U; i < tryCount; ++i)
    if(std::binary_search(vec.data(), vec.data() + vec.size(), numToSearch))
      ++count;

  duration = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now() - startTime);
  std::cout << "Binary search in vector: duration(ms): " << duration.count() << ", iterations: " << count << '\n';
}

int main(int argc, char *argv[])
{
  testLookupBigContainer();
  return 0;
}
```

**Comment by seladb** [comment]
For ordered lists I can understand why vectors might be faster, and same goes for really short lists (where going over the list may be faster than calculating a hash value and finding the right bucket). 

However in use cases where lists are not super small or ordered I'm not sure I understand how map are slower... Regarding `SSLLayer::getSSLPortMap()` - I'm not sure how significant this change could be, especially if we add the optimization you suggested on PR #288 where you add a specific check for port 443

**Comment by gx740** [comment]
> However in use cases where lists are not super small or ordered I'm not sure I understand how map are slower...

Yes, it's my wrong that I had not properly said. Of course, lookup in map is faster for unsorted and/or big lists.

> I'm not sure how significant this change could be, especially if we add the optimization you suggested 

This method is public so the user can use it for some purposes. My suggestion, to give more effective way of lookup, is based on this assumption. I don't understand why this method had been made public because I don't see reasonable use cases.

PR #288 solves another task: to increase the speed of packet decoding.

**Comment by seladb** [comment]
> This method is public so the user can use it for some purposes. My suggestion, to give more effective way of lookup, is based on this assumption. I don't understand why this method had been made public because I don't see reasonable use cases.

This method is being used in the [SSLAnalyzer example](https://github.com/seladb/PcapPlusPlus/blob/236e035be8d7109082e1b599abd435269f13032d/Examples/SSLAnalyzer/SSLStatsCollector.h). It's being used it to count SSL connection by looking at the TCP port

**Comment by gx740** [comment]
Ok, let's close this issue
