### ISSUE TITLE
How to send corrupt ethernet frames?

### ISSUE THREAD

**Issue by Sebaschke** [seladb/PcapPlusPlus#292]
Hey, I‘m stuck on a problem for university, I quickly describe it: 
-	For network stressing in a sensor network, I want to send corrupt ethernet frames 
-	This means the frames should be e.g. <64 B or >1518 B  
-	I also want to send a wrong FCS
-	The traffic generator should be running on a raspberry pi 4 model B

I searched the internet and read many times that the network driver could become a problem. Does anybody know a way around this? I would be very thankful for any help/suggestions.
Cheers

**Comment by seladb** [comment]
Is this really a PcapPlusPlus issue or a general question?

For general question you can consider posting on other forums (like StackOverflow and such) or in [PcapPlusPlus Google Group](https://groups.google.com/forum/#!forum/pcapplusplus-support)

**Comment by rickyzhang82** [comment]
@Sebaschke scapy is your friend. see https://0xbharath.github.io/art-of-packet-crafting-with-scapy/scapy/creating_packets/index.html

**Comment by Sebaschke** [comment]
Thanks for the replies. I think you're right @seladb, this is more a general question concerning maybe the driver and therefore belongs in another forum.
I will open a thread in stackoverflow to continue, if the NIC allows in some way the injection of packets <64B on a RPi. Thanks.
@rickyzhang82 I will have a look at scapy but one requirement for my work is to write the application in C or C++.

**Comment by seladb** [comment]
Thanks, I'll close this issue now
