### ISSUE TITLE
Memory leak in TcpReassembly

### ISSUE THREAD

**Issue by rickyzhang82** [seladb/PcapPlusPlus#295]
https://github.com/seladb/PcapPlusPlus/blob/be1d148dd0cb05af9deb3233d6e56542bd35e06b/Packet%2B%2B/src/TcpReassembly.cpp#L837-L839

`m_ConnectionList` is ` std::map<uint32_t, TcpReassemblyData *>`. Erasing an element from the map doesn't clean up TcpReassemblyData object in the heap.

**Comment by gx740** [comment]
An object is being deleted in closeConnectionInternal method. Check again, please.

**Comment by gx740** [comment]
I had used `valgrind` to check memory leaks when developing this method. These were not found.

**Comment by rickyzhang82** [comment]
OK. I see. 

Why not move to `TcpReassembly::purgeClosedConnections`?
This can improve readability and also avoid potential read access violation if memory has been clean but the map still hold on to it.

**Comment by gx740** [comment]
On the one hand it increases the speed of the connection closing and improves readability, and on the other it increases the memory consumption.

To implement a delayed cleanup of `TcpReassemblyData` we need to change the type of `CleanupList` from
`std::map<time_t, std::list<uint32_t>>`
to
`std::map<time_t, std::list<std::pair<uint32_t,TcpReassemblyData*>>>`

and to make the changes in `purgeClosedConnections` and `insertIntoCleanupList`.

@seladb what you think about this suggestion?

**Comment by seladb** [comment]
I'm a little bit confused why we need `purgeClosedConnections` and why we can't clean up a connection when it's closed. I think we had a reason for that but I'm not quite sure. Could you please remind me?

**Comment by gx740** [comment]
There are two reasons:
1.  There is a public method `getConnectionInformation`:
```
/**
 * Get a map of all connections managed by this TcpReassembly instance (both connections that are open and those that are already closed)
 * @return A map of all connections managed. Notice this map is constant and cannot be changed by the user
 */
const ConnectionInfoList& getConnectionInformation() const { return m_ConnectionInfo; }
```
2. It is necessary to know that some connection is already closed (`reassemblePacket` does such check).

Issues #248 and #250.

**Comment by seladb** [comment]
Yes you're right, thanks for reminding me. At least for point number 2 we need to keep a list of recently closed connections. I suggest we keep the code as is. Please let me know what you think

**Comment by rickyzhang82** [comment]
@seladb's suggestion is fine in `TcpReassembly`. The premature clean up `TcpReassemblyData` won't cause too much trouble since it is transient. User can't access `TcpReassemblyData` outside of the class. It is just me who work on COPY & PASTE of the logic and need to pay a close attention to this.

Since the class doesn't implement TCP state machine, I wonder if the timer in clean up list serve as waiting for 2MSL (twice the Maximum Segment Lifetime) in `TIME_WAIT` state? If it were true, we may need to bump up the default 5s to 30s (or above).

https://github.com/seladb/PcapPlusPlus/blob/07d67c9368cbdb871aa957431df18ecd9c7f05ce/Packet%2B%2B/src/TcpReassembly.cpp#L142

**Comment by seladb** [comment]
@rickyzhang82 we arbitrarily decided of 5 sec as the default value. As you can see in the code it's configurable and can be set to any value

**Comment by rickyzhang82** [comment]
Fair enough. Please close it.
