### ISSUE TITLE
PcapLiveDevice::close() doesn't set IDevice::m_DeviceOpened to false

### ISSUE THREAD

**Issue by ugenehan** [seladb/PcapPlusPlus#306]
PcapLiveDevice::close() doesn't set IDevice::m_DeviceOpened to false

**Comment by seladb** [comment]
That's a good point, thanks for reporting this! I was sure we fixed it long back... would you mind suggesting a fix and add some test cases for that fix?

**Comment by seladb** [comment]
Fixed
