### ISSUE TITLE
Quic support

### ISSUE THREAD

**Issue by vrobles-gee** [seladb/PcapPlusPlus#314]
Hi.

We would like to parse/craft [QUIC](https://en.wikipedia.org/wiki/QUIC) layer using PcapPlusPlus for some features we need in our app. I took a look but found no QuicLayer or related classes. So I would like to ask if there is any work on this. If not, I can work on the feature, but I would like to ask you for general suggestion or guidelines based on the work you've already done with other layers.

Thanks,

**Comment by seladb** [comment]
Yes, as of now QUIC/HTTP3 is not supported. Of course you're more than welcome to work on this feature and I will provide all the support and guidance you need. Please let me know how I can help

**Comment by vrobles-gee** [comment]
Thanks. We should start working on this in about two weeks, so I will get back to you when we have some initial work for reviews and suggestions.

**Comment by seladb** [comment]
sure @vrobles-gee , please let me know how I can help

**Comment by seladb** [comment]
Did you start working on that already? Please let me know if you need any help

**Comment by vrobles-gee** [comment]
Hi. Sorry it took so long to reply, I was on holiday. Recently, we decided to delegate this on another team. Since we will still provide the requirements, before doing that, we will check with you about the better approach to structure the classes. We have already started checking the protocol draft (notice it is still not a standard, newer draft version is from last November) and I believe a similar approach to the one you use to represent different SSL header/layer/message types would work for QUIC (there are two header types, short and long, as well as several packet types that use short or long header). Can you please take a look and let us know if that would be a good approach? See [here](https://tools.ietf.org/html/draft-ietf-quic-transport-24#section-12). Thanks.

**Comment by seladb** [comment]
To be honest, I'm not familiar with Quic so it might take me some time to learn this protocol and understand how it works. Do you have any documentation which is simpler to read? RFCs are long and complex documents 😃

**Comment by seladb** [comment]
@vrobles-gee did you make any progress on this? should we keep this issue open?

**Comment by vrobles-gee** [comment]
Hi @seladb sorry about the late response, I thought I had replied to your previous comment. Here are some easier to read links that explain QUIC basics and shows the different header and frame formats I was talking about before:

- https://blog.cloudflare.com/the-road-to-quic/
- http://iepg.org/2019-03-24-ietf104/QUIC%20-%20IEPG%20-%20March%202019.pdf

About progress, we are not currently working on this due to several internal and external factors, but is still on our roadmap. So if it is OK with you, we can leave the issue open, and I will let you know whenever we resume work on this. Otherwise, please close it and I will reopen it when ready to take this task again.

Thanks,

**Comment by seladb** [comment]
Thanks @vrobles-gee , let me close this issue for now, please reopen when you resume the work
