### ISSUE TITLE
memory not freed in TcpReassembly 

### ISSUE THREAD

**Issue by cmwl** [seladb/PcapPlusPlus#318]
When download or upload a large file,the memory footprint is very high which is ok for me, but it keeps high and will not be freed after I call:
`dev->stopCapture();
dev->close();
tcpReassembly->closeAllConnections();
tcpReassembly->purgeClosedConnections(0xFFFFFFFF);
delete tcpReassembly;
`
Did I use it the wrong way??? I followed the TcpReassemble Example.

**Comment by gx740** [comment]
The call of `purgeClosedConnections` is unnecessary because the `tcpReassembly` is being destroyed and all internal data will cleared automatically.

Did you use an IP reassembly logic before TCP reassembly?

**Comment by cmwl** [comment]
I did not use IP reassembly, In fact I used the same logic as `Examples->TcpReassembly` which has the same issue.

**Comment by gx740** [comment]
I tested this application under `valgrind` and could not find significant memory leaks. A small memory leak have been fixed in PR #320.
