### ISSUE TITLE
Segmentation fault:  11

### ISSUE THREAD

**Issue by eostermueller** [seladb/PcapPlusPlus#33]
On Mac Yosemite version 10.10.3, I'm trying to display the response times of each HTTP session from a pcap file.

I downloaded this pcap file::
`https://github.com/open-nsm/course/blob/master/pcaps/nitroba.pcap`

I downloaded PcapSplitter from here:
`https://www.dropbox.com/sh/5go4ca778nu4zrm/AABbpDieIPBWQ0sGFNCWU7mza?dl=0`

Ran this command:
`PcapSplitter -m connection -f nitroba.pcap -o pcs`

And got this error:
`
Started...
Segmentation fault: 11
`

Any suggestions on what I'm doing wrong?

Thanks,

--Erik

**Comment by seladb** [comment]
In that link I see PcapSplitter was compile for Mac OS X Snow Leopard, not for Yosemite, that's probably the reason. Can you compile it for Yosemite?

**Comment by eostermueller** [comment]
Sorry, I'm not set up for that.

**Comment by seladb** [comment]
I don't have a Mac with Yosemite installed so I can't compile it for you, sorry...

**Comment by seladb** [comment]
Do you have someone with a Mac that can help you with that?

**Comment by eostermueller** [comment]
Got a mac, don't have the cpp dev environment.

**Comment by seladb** [comment]
Ok, if I'll find someone with a Yosemite I'll compile and and notify you
