### ISSUE TITLE
Splitting pcap based on 5-tuple info

### ISSUE THREAD

**Issue by kosnet2** [seladb/PcapPlusPlus#339]
Is it possible to split pcap file into multiple others ones based on src_ip, dst_ip, src_port, dst_port, protocol ?

**Comment by seladb** [comment]
Yes, this is possible using the `-m connection` flag, for example:

```shell
./PcapSplitter -f my_pcap.pcap -o /output_dir -m connection
```

**Comment by kosnet2** [comment]
> 
> 
> Yes, this is possible using the `-m connection` command-line switch, for example:
> 
> ```shell
> ./PcapSplitter -f my_pcap.pcap -o /output_dir -m connection
> ```

That is great. @seladb Thank you very much.

In my case I am interested only on UDP and TCP streams.

The utility splits the pcap to smaller ones based on the connection and I get an output like this: 
![image](https://user-images.githubusercontent.com/20568574/71309418-20683b80-2410-11ea-9ce6-dfe356ef59bf.png)

Is it possible to know the protocol of the splitted pcap? ( probably a naming convention, like [UDP]log.pcap-0001.pcap [TCP]log.pcap-0002.pcap  [ICMP]log.pcap-0003.pcap etc.. )

**Comment by seladb** [comment]
Yes, all packets which are not TCP or UDP will always be in file #0. The rest of the files will contain either UDP or TCP packets.

You can also filter the packets to split using the `-i` switch, for example:

```shell
./PcapSplitter -f my_pcap.pcap -o /output_dir -m connection -i "tcp|udp"
```

**Comment by kosnet2** [comment]
Great. Thank you very much.
