### ISSUE TITLE
Can is compile to /MT mode

### ISSUE THREAD

**Issue by muse117** [seladb/PcapPlusPlus#341]
Hi，I want to compile to /MT mode on the visual studio. but，It is not run and error.  Not Support it?

**Comment by seladb** [comment]
This flag is currently not officially supported

**Comment by muse117** [comment]
> This flag is currently not officially supported

I successfully ran the program in /mt mode, but, The program runs for a while and restarts automatically

![微信截图_20191226172419](https://user-images.githubusercontent.com/9733486/71469694-f3979800-2804-11ea-8176-f7f3d546971a.png)

**Comment by seladb** [comment]
thanks for the update! I don't know what your program does so it's hard to tell why it's crashing...

**Comment by muse117** [comment]
> thanks for the update! I don't know what your program does so it's hard to tell why it's crashing...

I'm checking, The same code is fine in /md mode
