### ISSUE TITLE
[Discussion] The cause of live libpcap packet loss

### ISSUE THREAD

**Issue by rickyzhang82** [seladb/PcapPlusPlus#342]
I knew this might not be the right place to discuss the issue. But I can't find any good information online. Perhaps somebody here can shed a light on the subject matters.

I wrote a TcpSorter class to do live capture packets. From time to time, I can detect TCP packet was not captured by libpcap, i.e. some TCP packets are missing during libpcap capture.

I wonder if it is because the my call back function invoked by `pcap_loop()` doesn't run fast enough thus user space memory buffer that stores the captured packets gets overflow.

To prove my hypothesis, I added a random time delay in the callback function. I did found more packet missing cases, such as a serious packet missing case that no first SYN flag in the TCP 3-way handshake.

If this were true, can I mitigate the issue by the following approach:

1. In callback function, clone a TCP packet from libpcap and added to the lock-free ring buffer.
1. Use semaphore to notify another thread that there is a incoming captured packet in the ring buffer. The callback ends quickly.
1. Another thread which run the TCP packet sorting logic get waken up by the semaphore and process the ring buffer until it is empty.

**Comment by gx740** [comment]
First, check whether the `libpcap` is able to capture the packets with the speed you expect. There are the libraries that support zero-copy: DPDK, PfRing. These are already used a ring buffer for packet capturing. At least in DPDK there is the ability to split the traffic into several queues that can be processed concurrently in separate threads.

> Use semaphore to notify another thread that there is a incoming captured packet in the ring buffer. The callback ends quickly.

Don't use the semaphore because any synchronization impacts to performance. Just make two threads: `receiver` and `processor`. Receiving thread will read the packets from `NIC` and put them into the ring buffer (or drop if a buffer is full). Create a loop in processing thread that reads the ring buffer without delays.

**Comment by seladb** [comment]
I agree with what @gx740 said, but using lock-free ring buffer is also a good option.

You can have one thread which only does packet capture and other threads that do the packet processing. You can use the lock-free ring for passing packets around.

I'd advise you to use [CPU affinity](https://en.wikipedia.org/wiki/Processor_affinity) if you have more than 1 core, especially for the packet capture thread (but also for the other threads). This will maximize the utilization of your machine

**Comment by rickyzhang82** [comment]
@gx740 

Regarding to the capturing speed capabilities of `libpcap`, where can I find its speed limit doc? I have hard time to find it by Google. I migrated pfSense configuration from my NetGate home router to run pfSense in my retired PC with Intel i7 2700k quad core CPU, [PCI-E dual port 1GiB NIC](https://www.amazon.com/gp/product/B07KGP342F/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1), 16GiB, and 500GiB SSD. I found that my packet capturing program only consumes less than 1% CPU usage time at any time. 

Regarding to your design plan, it is similar to what I planned to try it out except that I have to use semaphore to wake up another thread (or in your word `processor` thread). The semaphore in the libpcap capturing callback function (in your word `receiver` thread) only performs non-blocking V operation (`release()` in Java). The semaphore in the `processor` thread performs blocking P operation ( `acquire()` in Java). The empty ring buffer blocks the P operation until V operation wakes it up. I will give this a try.

@seladb 

I found boost::lockfree package implemented single-consumer-single-producer queue. That fits my purpose very well for a lock free ring buffer. But there is no sempahore implementation in C++11. I can either write my own using mutex and conditional variable in C++11 or use semaphore in C++17. In any case, I'd avoid reinvent the wheel at all cost.

I'm not sure CPU affinity in your context. I did found [a paper here] (http://www.syssec-project.eu/m/page-media/3/pcap-comcom.pdf). But honestly I have no idea what did this guy proposed to do. Or put in this way: I can't find actionable item for me to improve it from libpcap. I'd like to hear from your advice.

**Comment by seladb** [comment]
@rickyzhang82 if you're using lock-free buffers and CPU affinity you don't really have to use semaphores. 

CPU affinity is the concept of assigning a core to a specific thread or process so the OS won't use this core for any other process. This guarantees 100% utilization of this core to you process only. This is an OS-level functionality rather than libpcap-level. You can read [here](https://stackoverflow.com/questions/280909/how-to-set-cpu-affinity-for-a-process-from-c-or-c-in-linux) and [here](https://stackoverflow.com/questions/8153664/how-to-use-pthread-setaffinity-np) how to enable that. You can also look in DPDK code to see how they do it.

If you assign a specific core for your packet capture thread and other cores for your packets processing thread, and assuming you have lock-free buffers to pass packets between them, you don't need to use semaphores. What you can do is have each thread running an infinite loop: the packet capture thread will try to capture packets and put them in the buffer(s), and the packet processing threads will consume packets from the buffer and do the packet processing.

Please let me know if that makes sense

**Comment by gx740** [comment]
@rickyzhang82 I think you can't find anything about the speed limits because it depends from environment and only the tests will show how many packets can be processed per sec.

https://stackoverflow.com/questions/21200009/capturing-performance-with-pcap-vs-raw-socket
https://cloud.tencent.com/developer/article/1088078

**Comment by rickyzhang82** [comment]
hi guys,

I implemented the @seladb idea:

1. Added one independent threads -- a processing thread to do TCP packet sorting. I found that libpcap do packet capturing in an independent thread automatically. So I saw three threads are running in the process: one from main program, one from libpcap capturing callback, one from the TCP sorter processing.
1. Used `pthread_setaffinity_np` to bind the processing thread and the capturing thread to one CPU core.
1. Used `boost::lockfree::spsc_queue` a.k.a lock free single-producer-single-consumer ring buffer data structure to coordinate two threads.

In the 3rd bullet point, I also tried two different approach: with and without semaphore. Without semaphore, the processing thread just keep CPU warm and looping. With semaphore, the capturing thread needs to wake up the processing thread who is get blocked due to empty ring buffer.

Here is the result: the missing packet in capture always happens in both cases. I already pre-allocate a large enough ring buffer and use `std::move` to avoid copy cost. My home network is 100MBPS and the testing machine is Fedora 31 with i9-9900K CPU and libpcap-1.9.1-1.fc31.x86_64.

If you guys are interested in it, I will share the program in Github. Perhaps I need to look into alternative capturing engine. But I don't know if I could run DPDK in FreeBSD. Because my objective is to let it run in my pfSense router, which is a variant of FreeBSD.

Merry Christmas and Happy New Year!

**Comment by rickyzhang82** [comment]
In fact, it is PcapPlusPlus's `PcapLiveDevice::startCapture` that creates an independent thread from the thread than runs `main()`. It is not libpcap. The mystery solved. The libpcap is still a single threaded library.

**Comment by rickyzhang82** [comment]
I look into [libpcap buffer size man page](https://www.tcpdump.org/manpages/pcap_set_buffer_size.3pcap.html). In my driver program, I used the default configuration in PcapPlusPlus default. Perhaps, I should try to bump it up by trial and error approach.

**Comment by gx740** [comment]
I think the `libpcap` is able to capture the 100Mbit NIC without the packet loss even in single thread. The only question is how many processor time is used. It may vary on different platform.
If the packet loss occures even on Core i9 you should, at least, estimate the performance of TCP reorder logic. Under linux there are the profilers such as `oprofile` and `operf`. These can be very useful.

Notice the DPDK supports the limited set of NICs. So I think you cannot use it in router.

Under FreeBSD there is a `netmap`.

**Comment by seladb** [comment]
I agree with @gx740 that libpcap shouldn't drop packets at 100mbps. How does you packet capture thread/method look like? Does it do anything besides capturing packets and putting them into the buffer?

If you don't want PcapPlusPlus to open a separate thread for packet capture you can use `PcapLiveDevice::startCaptureBlockingMode()` which basically runs in an endless loop and captures packets until you tell it to stop.

One more thing you can try is to write simple code that uses plain libpcap code (without PcapPlusPlus wrapper). PcapPlusPlus obviously [has some overhead](https://pcapplusplus.github.io/docs/benchmark) but I believe this overhead shouldn't be very significant

**Comment by rickyzhang82** [comment]
Bumping up buffer size in libpcap doesn't resolve the missing packet problem.

I shared my PacketSorter app in [Github repo here](https://github.com/rickyzhang82/PacketSorter). It supports Linux and FreeBSD.

To build it, you need to build and install PcapPlusPlus from dev-tcp-sorter branch in my forked repo:

```
git clone -b dev-tcp-sorter https://github.com/rickyzhang82/PcapPlusPlus.git
```
Install boost library and CMake.

```
git clone https://github.com/rickyzhang82/PacketSorter.git
sh clean-build.sh
sudo ./build/bin/PacketSorter -i wlp58s0 -o /home/Ricky/Documents/tcpsorter -p 32
```
The missing packet log file will be written to `/home/Ricky/Documents/tcpsorter/capture.log`.

Here is the branch description:
- dev-bump-up-libpcap-buff-size. Override the default libpcap buffer size.
- dev-multithread. Employ multi-thread technique. Use lock free ring buffer and thread affinity. The packet processing runs in an indepdent thread.
- dev-multithread-wo-semaphore. Employ multi-thread technique. Use lock free ring buffer without semaphore to coordinate and thread affinity.
- dev-no-force-flush. Single threaded. The packet won't flush to disk until the TCP connection is closed due to idle time out.

I have been running the branch `dev-no-force-flush` in my pfSense router since Dec 22nd:

```
[2.4.4-RELEASE][admin@pfSense.localdomain]/root/tcpsorter: ls -al | wc -l
  101807
[2.4.4-RELEASE][admin@pfSense.localdomain]/root/tcpsorter: cat capture.log | wc -l
     316
```

There are 101,807 connections and 316 packet lost in capture. The percentage is 0.31%.

Note that my pfSense router runs on 1GiB NIC but my Internet speed is only 100Mbps. I tested the program in Fedora Linux box which runs on i9-9900K cpu and Intel wireless card (approx 200Mbps).

In multi-thread branch, the code that run packet capturing is minimal:

https://github.com/rickyzhang82/PacketSorter/blob/e05c73830158fc78b9b318fe748e0a527d4fb0c6/src/main.cpp#L584-L602

I'm out of ideas. I don't want to poke my finger into DPDK due to its complication in FreeBSD. I think I'm done with this exercise. I will live with the packet loss for now. For my personal project, I will drop those TCP connection packet capture pcap file from the missing packet `capture.log`.

I will write some UT first.

**Comment by seladb** [comment]
At this point I'd advise you to write a very simple program that uses plain libpcap (and not PcapPlusPlus). This program can count incoming packets for example, and do nothing else. See if you encounter packet loss there. If you do, it means libpcap cannot handle the load. If you don't, try to gradually add more code until you identify the bottleneck, for example: 

0. Step 0; simple libpcap code. If you don't see packet loss move to step 1
1. Step 1: exchange plain libpcap with PcapPlusPlus (which still does the same very simple thing). If you don't see packet loss move to step 2
2. Step 2: write incoming packets into the lock-less ring. If you don't see packet loss move to step 3
3. Step 3: add thread affinity. If you don't see packet loss move to step 4
4. Step 4: add additional threads that consume packets from the ring.
5. Step 5: .... and so on until you identify where the bottleneck is

**Comment by seladb** [comment]
@rickyzhang82 should we keep this issue open or can we close it?

**Comment by rickyzhang82** [comment]
I will close it.
