### ISSUE TITLE
[Discussion] TcpReassembly improvements

### ISSUE THREAD

**Issue by gx740** [seladb/PcapPlusPlus#343]
Currently, there is a private member `m_ConnectionInfo` of type `std::map<uint32_t, ConnectionData>` that is returned by the `getConnectionInformation` method. The same connection data is stored in `m_ConnectionList`. I propose to remove `m_ConnectionInfo` and to use `m_ConnectionList` for returning information to the user through the const iterator. It gains the performance and decreases the memory consumption.

The changes have to be made:
- create an iterator
- remove the `getConnectionInformation()`
- create the methods `begin`, `end` and `find` that returns an iterator

Let me know what you think.

**Comment by seladb** [comment]
So how will the new API look like?

btw, there's also a need to add a `size()` method so the user will know how many connections are currently being handled

**Comment by gx740** [comment]
| Current API	                                                            | New API                                                      |
|-------------------------------------------------------------------------|--------------------------------------------------------------|
| void                      reassemblePacket(Packet&)	                    | void           reassemblePacket(Packet&)                     |
| void                      reassemblePacket(RawPacket*)	                | void           reassemblePacket(RawPacket*)                  |
| void                      closeConnection(uint32_t)	                    | void           closeConnection(uint32_t)                     |
| void                      closeAllConnections()	                        | void           closeAllConnections()                         |
| int                       isConnectionOpen(const ConnectionData&) const | int            isConnectionOpen(const ConnectionData&) const |
| uint32_t                  purgeClosedConnections(uint32_t)	            | uint32_t       purgeClosedConnections(uint32_t)              |
| **const ConnectionInfoList& getConnectionInformation() const**	        | **const_iterator begin() const**                             |
| 	                                                                      | **const_iterator end() const**                               |
|	                                                                        | **const_iterator find(uint32_t flowKey) const**              |
|	                                                                        | **size_t         size() const**                              |

**Comment by seladb** [comment]
In my opinion adding those methods to the `TcpReassembly` class may be confusing for the users because this class is not an iterator. We could write a sub-class that will contain this logic but as I think about it more the current implementation should be ok for most use-cases. 

What do you think?

**Comment by gx740** [comment]
Let remain as is
