### ISSUE TITLE
typo in enum

### ISSUE THREAD

**Issue by ilsergente1993** [seladb/PcapPlusPlus#367]
I guess there's a typo here
https://github.com/seladb/PcapPlusPlus/blob/bddea1ec7fdd1d3b889200d38cd8195e27608a2f/Packet%2B%2B/header/HttpLayer.h#L255

Enum `http205ResetContent `instead of `Http205ResetContent`

Cheers

**Comment by seladb** [comment]
You’re more than welcome to fix the typo and create a PR 😃

**Comment by ilsergente1993** [comment]
Thank you @seladb , sorry if I couldn't provide the PR.
Thanks for the awesome project btw

**Comment by seladb** [comment]
Sure, thanks for the kind words!
