### ISSUE TITLE
Packet send fails for when MTU size is greater than 65535

### ISSUE THREAD

**Issue by jquinn60137** [seladb/PcapPlusPlus#368]
I ran into an interesting bug this morning.  I'm trying to send a packet over the loopback interface.  Send fails with this error:

Packet length [373] is larger than device MTU [0].

ifconfig reports a MTU value of 65536

After a few hours of troubleshooting I think I found the root cause.  In PcapLiveDevice::setDeviceMtu() ifr.ifr_mtu is set to 65536 (0x10000) correctly.  However, this value is copied to m_DeviceMtu which is defined as uint16_t.  As a result the MTU value gets truncated to 0 which causes the send failure.  

Should m_DeviceMtu be defined as type uint32_t since ifr_mtu is 4 bytes long?  If so, getMtu() and potentially anything that calls it will also need to change.  

Thanks for all you work on this project.  It is a really nice tool!

**Comment by seladb** [comment]
Thanks for reporting this issue!

I tend to agree with you, we should extend `m_DeviceMtu` to `uint32_t`. I verified that the MTU value we get from both Windows and non-Windows system calls is 4-byte long so I see no reason we don't return a 4-byte long value too.

Would you like to make the change and submit a PR?

**Comment by seladb** [comment]
Done. Can you please run the same test with the latest version from `master`?

**Comment by jquinn60137** [comment]
The fix looks good.  Thanks for the quick turn-around on this and the other bug I reported.
