### ISSUE TITLE
Is section header block read and written?

### ISSUE THREAD

**Issue by Akvinikym** [seladb/PcapPlusPlus#371]
Hello.

We are currently using the library to:

1. Open a `PcapNgFileWriterDevice` with some filters onto it
2. Open several pcapng files one-by-one and write their contents into the output file, opened in the first step, to achieve the filtering

But, now I have a question: are Section Header Blocks of those files read by the library and then written to the output file? 

After some search in the `LightPcapNg` 3-rd party library I discovered that it actually parses those blocks, but I don't see them written into the output file anywhere. The problem is that they contain such important data, as, for example, interfaces, from which the capture was done. 

To be concrete, this is the issue I encountered: I open two capture files, one of them contains captures from only one interface, while the other contains captures from two interfaces (they may or may not intersect, does not matter). When I firstly open the first file, then the second, the resulting file is corrupted - Wireshark tells that "interface index 2 is not less than interface count 1". When I open the files in the other order, everything works.

So, that's the part I don't understand - how the Section Header Blocks of the output file is formed? It's supposed to contain information about the capture interfaces as well, so this is what happens, as I understand: in the first case, Section Header Block with one interface is parsed and written to the output file, and two interfaces from the second file make the file corrupted; in the second case, the information about 2 interfaces is written to the output file, so everything goes OK.

There can be several blocks of this format in one file, so in a perfect world I think it should be like that:

1. Read the input file
2. Write its Section Header Block into the output file
3. Write its packets into the output file
4. Repeat

I would consider implementing this algorithm, if it's correct, but I am not sure, where to start. I have attempted to, but failed :)

Thank your very much for the answer in advance.

**Comment by seladb** [comment]
I'm sorry for the delayed response.

If I understand your question correctly you're interested to know whether the interface data is being read or written from/to pcapng files. Unfortunately this is currently not supported. The only metadata that is supported for read and write is: hardware info, OS info, application info and file comment.

As you can see here the the interface ID is set to 0 by default during packet write:
https://github.com/seladb/PcapPlusPlus/blob/eae97f3b76b0c3fca9ab5566f291a9dfe4f357f0/Pcap%2B%2B/src/PcapFileDevice.cpp#L726

I don't quite understand the corrupted file issue you mentioned. Could you please elaborate or share some code that reproduces this issue?

**Comment by Akvinikym** [comment]
Actually, this issue is partly my fault. We use the fork of your library, and there the line you mentioned is changed to ` pktHeader.interface_id = packet.getInterfaceId()`, which puts the same `interface_id`, as it was in the original packet. I didn't know about this change, so sorry for bothering.

I think, we will stick to your way and unify all interfaces into one - the 0 - in order to get well-formed `pcapng` files. But, maybe later we will implement the interfaces and section header blocks writing thing and land a PR to this implementation :) 

It should not be that hard, as everything that is needed to be done is just to copy original section header block and interface info blocks into the output file. As I understand, sections in `pcapng` file are absolutely independent from each other, so that's why we can do it like that (if I am wrong, please correct me). The only thing, which stopped me from implementing it right now is that `LightPcapNg` library does some magic with those blocks, and interfering with it can cause some issues.

Thank you for the response, the issue can be closed.

**Comment by seladb** [comment]
Thanks @Akvinikym, I'll close this issue for now. If you decide to implement this please let me know and I'll try to help
