### ISSUE TITLE
Compiler warning in PcapLiveDevice.h - possible bug

### ISSUE THREAD

**Issue by jquinn60137** [seladb/PcapPlusPlus#372]
When building I get the following warning:

/usr/local/include/pcapplusplus/PcapLiveDevice.h: In constructor ‘pcpp::PcapLiveDevice::DeviceConfiguration::DeviceConfiguration(pcpp::PcapLiveDevice::DeviceMode, int, int, pcpp::PcapLiveDevice::PcapDirection)’:

/usr/local/include/pcapplusplus/PcapLiveDevice.h:207:138: warning: unused parameter ‘direction’ [-Wunused-parameter]

 on(DeviceMode mode = Promiscuous, int packetBufferTimeoutMs = 0, int packetBufferSize = 0, PcapDirection direction = PCPP_INOUT)

Here is the source:

DeviceConfiguration(DeviceMode mode = Promiscuous, int packetBufferTimeoutMs = 0, int packetBufferSize = 0, PcapDirection direction = PCPP_INOUT)
			{
				this->mode = mode;
				this->packetBufferTimeoutMs = packetBufferTimeoutMs;
				this->packetBufferSize = packetBufferSize;
				this->direction = PCPP_INOUT;
			}

direction is passed in, but never used.  Should the code be:

this->direction = direction;

**Comment by seladb** [comment]
This is a very good point, thanks for reporting this!

Would you like to make a fix a submit a PR?
