### ISSUE TITLE
loopback support?

### ISSUE THREAD

**Issue by muse117** [seladb/PcapPlusPlus#389]
Do not support 127.0.0.1 and npcap loopback? I use method of getPcapLiveDeviceByIp. but , dev is nullptr. 
![微信截图_20200114101053](https://user-images.githubusercontent.com/9733486/72307791-74380e80-36b6-11ea-9142-75283664e2f3.png)
![微信截图_20200114101446](https://user-images.githubusercontent.com/9733486/72307862-b95c4080-36b6-11ea-9f31-925d09acf0f4.png)

**Comment by seladb** [comment]
There was a similar issue in the past: https://github.com/seladb/PcapPlusPlus/issues/210

Please take a look and let me know if it's working for you

**Comment by muse117** [comment]
> There was a similar issue in the past: #210
> 
> Please take a look and let me know if it's working for you

I have seen #210, This issue is used getPcapLiveDeviceByName , I want to use getPcapLiveDeviceByIp. whether support it?

**Comment by seladb** [comment]
I don't think this is supported by WinPcap/Npcap, otherwise you wouldn't get a null response when searching by IP

**Comment by muse117** [comment]
> I don't think this is supported by WinPcap/Npcap, otherwise you wouldn't get a null response when searching by IP

I see regedit, It is 0.0.0.0 ip of npcap. but, I can winapi get ip of npcap. I think whethter to establish the corresponding. 
![微信截图_20200114151542](https://user-images.githubusercontent.com/9733486/72322640-ca6e7700-36e1-11ea-91fb-af7c701f9a84.png)
![微信截图_20200114151834](https://user-images.githubusercontent.com/9733486/72322692-ed009000-36e1-11ea-96ff-8c800f352382.png)

**Comment by seladb** [comment]
while it may be possible using WinAPI, I'm not sure if Npcap or WinPcap actually support it. Since PcapPlusPlus is mostly a wrapper for those libraries, if they don't support it PcapPlusPlus won't either

**Comment by muse117** [comment]
> while it may be possible using WinAPI, I'm not sure if Npcap or WinPcap actually support it. Since PcapPlusPlus is mostly a wrapper for those libraries, if they don't support it PcapPlusPlus won't either

Ok, Thank you for your reply

**Comment by seladb** [comment]
if you find out the Npcap/WinPcap do support it plz let me know and I'll check that

**Comment by muse117** [comment]
> if you find out that Npcap/WinPcap do support it plz let me know and I'll check that

I directly use "\Device\NPF_Loopback". It is good.

**Comment by seladb** [comment]
Cool, I'll close the issue now, please reopen if needed
