### ISSUE TITLE
Getting issues when parsing large pcap file

### ISSUE THREAD

**Issue by stev3bb** [seladb/PcapPlusPlus#391]
Hi Community,

Background:
I using the pcap plus plus to parse large pcap files and separating them smaller files with respect to different types of protocols. The pcap files are captured with tcpdump and file are about 30-100gb.

I have encountered this problem below and was wondering where it is throwing this message "DNS parsing error: name pointer is illegal" as I am only able to parse half of a sample file. 

```
Skipping parsing DNS resources
DNS layer contains more than 300 resources, probably a bad packet. Skipping parsing DNS resources
DNS layer contains more than 300 resources, probably a bad packet. Skipping parsing DNS resources
DNS layer contains more than 300 resources, probably a bad packet. Skipping parsing DNS resources
DNS layer contains more than 300 resources, probably a bad packet. Skipping parsing DNS resources
DNS parsing error: name pointer is illegal
DNS parsing error: name pointer is illegal
DNS parsing error: name pointer is illegal
```

Any pointers would be super helpful!

**Comment by seladb** [comment]
These errors mean that the DNS packets in the pcap file are probably malformed. Could you please share a few samples so I can take a look?

**Comment by stev3bb** [comment]
Thank you for your reply, sounds about right as it didn't throw that error when I tested it with a smaller sample. Do you know of some issue with pf_ring version of tcpdump that might corrupt packets? 
I will take a deeper look at it and come back with some data.

**Comment by seladb** [comment]
I'm not aware of any issue with pf_ring version of tcpdump... please share some data when you have it

**Comment by seladb** [comment]
do you have an update on this?
