### ISSUE TITLE
TCP sequence 32-bit overflow handling.

### ISSUE THREAD

**Issue by alexdrobinsky** [seladb/PcapPlusPlus#402]
TCP sequence defined as uint32 which is perfectly fine :) The problem is that during reassembly sequence could easily rollover , in this situation current code will treat retransmitted packets as out-of-order fragments and vice versa, out-of-order packets will be dropped as "retransmitted". This is bare minimum list of issues btw.

**Comment by seladb** [comment]
I think a similar issue was raised here: https://github.com/seladb/PcapPlusPlus/issues/317
And was resolved in: https://github.com/seladb/PcapPlusPlus/commit/cb6ee56b31ad36966e39425ed22b6a950707fb07

Are you talking about a different issue?

**Comment by alexdrobinsky** [comment]
Indeed, looks like correct solution although I would need to invest some time to validate those macros :)

**Comment by seladb** [comment]
sure, please let me know if you find any issues
