### ISSUE TITLE
need android ndk compile file and tun device(can get fd from VpnService) supported

### ISSUE THREAD

**Issue by mccoysc** [seladb/PcapPlusPlus#403]
as the title

**Comment by seladb** [comment]
I'm not familiar with the Android eco-system, could you please provide more details on what needs to be done?

**Comment by mccoysc** [comment]
on android,there is an interface called VpnService and can get a tun device fd from this interface.
then you can use this fd by read/write and the data would be an ip packet(only one pkt per read/write) .


Entire all net traffic pkt would be routed to the tun device and you can get the out pkt by read the fd and make reply by write(ip_pkt).



发自我的iPhone


------------------ Original ------------------

**Comment by seladb** [comment]
Thanks for the details. Unfortunately I'm a few steps behind you because I've never used Android NDK so I don't know how to set it up, test it and so on.

Please feel free to either guide me how to get started or test it yourself an contribute back to the project.

**Comment by mccoysc** [comment]
> Thanks for the details. Unfortunately I'm a few steps behind you because I've never used Android NDK so I don't know how to set it up, test it and so on.
> 
> Please feel free to either guide me how to get started or test it yourself an contribute back to the project.

just make a file Android.mk like makefile  and ndk-build would do all for others.
or you can make a c/c++ interface which accept a "int  fd" param that you can read/write the fd to get ip packet other than libpcap.
and after that ,i can do "create a Android.mk" file and build it.

**Comment by mccoysc** [comment]
in really,i am programing an android vpn app that useing the VPNService interface.
but in fact,the data i get from the fd are all only raw ip packet.
i need reassembly the out packet to udp,tcp data,and also i need make reply packet(also raw ip packet) and keep some sessions for tcp packet so that i can make the good ip reply packet,it's so cpmplex.
the reassembly code in pcap++ just get the data,not "packet interaction".

**Comment by seladb** [comment]
If you're using raw socket you might want to look into [RawSocketDevice](https://github.com/seladb/PcapPlusPlus/blob/master/Pcap%2B%2B/header/RawSocketDevice.h). As for creating an `Android.mk` file and compile it using android-ndk - you can probably do it much faster than me

**Comment by mccoysc** [comment]
No, rawsocket can not be used in android.
I can only read raw data from the tun device's fd and forward the payload to remote server and make raw ip packet then write the raw ip packet to the fd as the reply



发自我的iPhone


------------------ Original ------------------

**Comment by mccoysc** [comment]
> If you're using raw socket you might want to look into [RawSocketDevice](https://github.com/seladb/PcapPlusPlus/blob/master/Pcap%2B%2B/header/RawSocketDevice.h). As for creating an `Android.mk` file and compile it using android-ndk - you can probably do it much faster than me

no,raw socket can not be used in android.
in my vpn app manner,i just send the payload wrapped by tcp socket to remote and receive the response by the same tcp socket,and then wrap the received data to raw ip packet and write to the tun device fd as a reply of previous syn flag.

**Comment by seladb** [comment]
Maybe you can write the code that gets and sets the data yourself and use PcapPlusPlus just for parsing the packets and running TCP reassembly?

**Comment by mccoysc** [comment]
> If you're using raw socket you might want to look into [RawSocketDevice](https://github.com/seladb/PcapPlusPlus/blob/master/Pcap%2B%2B/header/RawSocketDevice.h). As for creating an `Android.mk` file and compile it using android-ndk - you can probably do it much faster than me

my problem is that:
in my VpnApp,i need make reply packet for tcp(it means that i should keep tcp sessions so that i can create the reply packet correctlly ).
because i see you code the tcp-reassembly,so i hope you can add a "tcp packet interactor" which generate correct tcp reply packet to make a easy way that i can use to reply the "previous syn flag".

**Comment by seladb** [comment]
Ok, now I see what need. What you're basically asking for is to create a TCP/IP stack. Unfortunately this is currently out of the scope of this project because TCP/IP stack tends to be very complex with a lot of edge cases to handle. You can write a simple/naive version of a TCP/IP stack yourself using PcapPlusPlus, maybe you can even contribute is as one of the [Examples](https://github.com/seladb/PcapPlusPlus/tree/master/Examples)

**Comment by mccoysc** [comment]
but for only handle packet which is only from and to tun device,you can imagine that all edge cases are no need to handle.
the stack only interact with local kernel tcpip stack,not interact with remote server or client,so no &nbsp; &nbsp;you can ignore all edge cases.



send from my iphone


------------------ Original ------------------

**Comment by seladb** [comment]
Got it. Looks like you have much more expertise on android ndk and tun2socks than me. Why don’t you implement it and I’ll support you and provide guidance?

This will probably be more efficient than me learning all of that stuff...

**Comment by seladb** [comment]
please let me know what would be the next step

**Comment by mccoysc** [comment]
I found the badvpn and a modified version 'lwip' in it and i will use it as a packet interceptor.






------------------ Original ------------------

**Comment by seladb** [comment]
so can we close this issue now?

**Comment by mccoysc** [comment]
ok



发自我的iPhone


------------------ Original ------------------
