### ISSUE TITLE
LINKTYPE_NETLINK packet payload not parsed

### ISSUE THREAD

**Issue by ilsergente1993** [seladb/PcapPlusPlus#404]
I'm using your superb library to catch and parse packets that I intercept using `nfqueue`, an extension of iptables. Of course, on Linux.
I am having some trouble to parse the packet.

I use the following code to get the message and extract the payload:
```C
struct nfqnl_msg_packet_hdr *ph = nfq_get_msg_packet_hdr(nfa);
unsigned char *rawData = nullptr;
int len = nfq_get_payload(nfa, &rawData);
```

and in `rawData` I have the payload from where I can successfully build the Packet:
```C
pcpp::RawPacket *inPacketRaw = new pcpp::RawPacket(static_cast<uint8_t *>(rawData), len, timestamp, false, pcpp::LINKTYPE_RAW);
pcpp::Packet *inPacket = new pcpp::Packet(inPacketRaw);
```
In `inPacket` I have all the layers I capture, except level 2, and if I print them I get:
```
LEV: 3 => IPv4 Layer, Src: 165.22.66.x, Dst: 40.77.226.x
LEV: 4 => TCP Layer, [SYN], Src port: 43388, Dst port: 443
```
for example for a TCP packet.

If I change the link type to `LINKTYPE_NETLINK`, I get the level 2 with the mac addresses, but the payload is not parsed at all:
```
LEV: 2 => Ethernet II Layer, Src: 40:00:40:06:aa:xx, Dst: 45:00:00:3c:9e:xx
LEV: 7 => Payload Layer, Data length: 46 [Bytes]
```
Note: the packet is exactly the same, parsing the exactly same `rawData` value.

Am I missing something somewhere? 

Thanks in advance

**Comment by seladb** [comment]
Indeed, `LINKTYPE_NETLINK` is not yet supported, but can easily be added. 

The main change would be to add another `else if` clause here to parse the first layer: https://github.com/seladb/PcapPlusPlus/blob/e7b5de61155c3678134b539cfdce8b0d2fa349b9/Packet%2B%2B/src/Packet.cpp#L660 

Also, we should add a test case similar to this with an appropriate pcap file:
https://github.com/seladb/PcapPlusPlus/blob/a2a0fd098fa4ff3fbf055a6628cf8661eb270d2d/Tests/Pcap%2B%2BTest/main.cpp#L889

Would you like to make this change and submit a PR?

**Comment by ilsergente1993** [comment]
I would like, but unfortunately, I'm close to my university project deadline and have no time to make the changes. Maybe in 2/3 weeks, I can do this, if you are not in a hurry.

In the meantime, what's your suggestion to work around this problem? Build a packet from layer two, getting the MACs from the `LINKTYPE_ETHERNET` and then append layers three and up from the `LINKTYPE_RAW`?

**Comment by seladb** [comment]
I think the best workaround would be this simple fix that I suggested 😃 

If you don't have time to add test-cases I can do it, just send me a few pcap examples I can use

**Comment by ilsergente1993** [comment]
yeah, I got the same idea.
a clarification: the layer should be the `EthLayer` or a new one is needed? because it already falls into the `EthLayer` using `LINKTYPE_NETLINK`, as far as I understood because I am not able to debug the code.

https://github.com/seladb/PcapPlusPlus/blob/e7b5de61155c3678134b539cfdce8b0d2fa349b9/Packet%2B%2B/src/Packet.cpp#L710

**Comment by seladb** [comment]
I'm not sure what is the first layer but I don't think it's Ethernet. If you can send me a sample pcap file I will take a look

**Comment by seladb** [comment]
@ilsergente1993 can you please send me a sample pcap file to verify the first layer?

**Comment by ilsergente1993** [comment]
yes @seladb, but give me some time more. I live in Northern Italy and we're having some trouble right now.

**Comment by seladb** [comment]
sure @ilsergente1993, please stay safe and healthy. I'll keep the issue open for now, waiting for your response

**Comment by seladb** [comment]
hi @ilsergente1993 I'd like to follow up on this. I hope you feel well and stay safe.

Have you made any progress on this?

**Comment by ilsergente1993** [comment]
Hi @seladb , thank you for your messages. I appreciate very much it. We are good, getting better and close to the end of the lockdown. I hope you stay safe too. #stayathome ;)
I found a capture I've done that should be good, but I'm not sure.

The file is here: https://github.com/ilsergente1993/craftberry/blob/master/captures/out_1581267337.pcapng 

Tell me if it is good. 
Btw, thank your superb project I almost completed - this issue :) - my master project and got the highest score. Long-life to PcapPlusPlus 💯

**Comment by seladb** [comment]
thanks @ilsergente1993 for the kind words! I'm happy to hear that things are getting better in Italy and the lockdown will be over soon.

I tested the file you sent and this link type is actually already supported by PcapPlusPlus. It's the `Raw IP` link type. Here is the code that identifies it:
https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/src/Packet.cpp#L709-L723

You can test this file using the [PcapPrinter utility](https://github.com/seladb/PcapPlusPlus/tree/master/Examples/PcapPrinter). Here is the output I get for this file:

```shell
C:\out_1581267337.pcapng
File summary:
~~~~~~~~~~~~~
   File name: C:\out_1581267337.pcapng
   File size: 1048 bytes

Packet Comment: packet modified by craftberry
Link layer type: Raw IP (101)
Packet length: 125 [Bytes], Arrival time: 1972-12-29 08:23:27.863863995
IPv4 Layer, Src: 165.22.66.6, Dst: 185.81.2.84
TCP Layer, [ACK], Src port: 58234, Dst port: 80
HTTP request, GET /test.txt HTTP/1.1

Packet Comment: packet modified by craftberry
Link layer type: Raw IP (101)
Packet length: 125 [Bytes], Arrival time: 1972-12-29 08:23:27.863863995
IPv4 Layer, Src: 165.22.66.6, Dst: 185.81.2.84
TCP Layer, [ACK], Src port: 58234, Dst port: 80
HTTP request, GET /test.txt HTTP/1.1

Packet Comment: packet modified by craftberry
Link layer type: Raw IP (101)
Packet length: 125 [Bytes], Arrival time: 1972-12-29 08:23:27.863863995
IPv4 Layer, Src: 165.22.66.6, Dst: 185.81.2.84
TCP Layer, [ACK], Src port: 58234, Dst port: 80
HTTP request, GET /test.txt HTTP/1.1

Packet Comment: packet modified by craftberry
Link layer type: Raw IP (101)
Packet length: 125 [Bytes], Arrival time: 1972-12-29 08:23:27.863863995
IPv4 Layer, Src: 165.22.66.6, Dst: 185.81.2.84
TCP Layer, [FIN, ACK], Src port: 58234, Dst port: 80
HTTP request, GET /test.txt HTTP/1.1

Packet Comment: packet modified by craftberry
Link layer type: Raw IP (101)
Packet length: 125 [Bytes], Arrival time: 1972-12-29 08:23:27.863863995
IPv4 Layer, Src: 165.22.66.6, Dst: 185.81.2.84
TCP Layer, [FIN, ACK], Src port: 58234, Dst port: 80
HTTP request, GET /test.txt HTTP/1.1

Finished. Printed 5 packets
```

Should we keep the issue open or close it?

**Comment by seladb** [comment]
@ilsergente1993 have you got my previous message? Let me know if we can close this issue or not

**Comment by ilsergente1993** [comment]
I cannot provide any more samples, unfortunately, to show you the RAW IP was ok to parse the packet but with that, I get lost (not parsed) the level 2 data.
I think it's better to close the issue. Sorry, @seladb 
I'll close it then
