### ISSUE TITLE
add detection of layer 3 protocols

### ISSUE THREAD

**Issue by danas74** [seladb/PcapPlusPlus#407]
Hi,
I'm currently working on your library. Could you please add detection of protocol sctp and IcmpV6? no need for layer 4 fields but just additional protocols detection.
Thanks

**Comment by seladb** [comment]
I'm sorry for the late response.

I'm not sure what you mean by "protocol detection". With the current implementation you can take an existing IPv6 layer of a packet and check weather the next layer is ICMPv6:

```cpp
IPv6Layer* ipv6Layer = ... ;
if (ipv6Layer->getIPv6Header()->nextHeader == PACKETPP_IPPROTO_ICMPV6)
{
    printf("YAY\n");
}
else
{
    printf("NAY\n");
}
```

You can't do the same for SCTP because the enum value is not there but I can easily add it.

Would it be sufficient for your needs?

**Comment by danas74** [comment]
Hi,
Thanks for your answer.
I currently use your code  by running through all the layers. For each layer I use your getProtocol() function, which returns types from ProtocolType enum. With IPV6 next layer of udp\tcp I get the correct protocol. I thought icmpv6 would be extracted similarly.
Could you please add the ICMPV6 and SCTP to this enum?
Thanks

**Comment by seladb** [comment]
Unfortunately the library design doesn't work that way. `getProtocol()` works for parsed protocols only and ICMPv6 and SCTP a not part of them at the moment

**Comment by seladb** [comment]
should we keep this issue open or close it?

**Comment by danas74** [comment]
I handled it but I think it would be nice to have it under your package. What ever you want.
Thanks

**Comment by seladb** [comment]
Since it doesn't align with the design of the project I'll close it for now. In the future we may think of a way to implement it
