### ISSUE TITLE
[Feature request] Allow to modify packet timestamp after creation (i.e. RawPacket::setTimestamp) 

### ISSUE THREAD

**Issue by v0l0dia** [seladb/PcapPlusPlus#408]
Seems reasonable when saving/manipulating captured packets that have imprecise timestamps from underlying capture engines, without having to subclass those engines.

**Comment by seladb** [comment]
That's a good idea and is very easy to implement. Would you like to implement yourself and create a PR?

**Comment by v0l0dia** [comment]
Yes, I think I'll make a PR in 2 or 3 days.

**Comment by v0l0dia** [comment]
Had some issues with CI while preparing Pull request.
Appveyor stucks with mingw32 build (first one), it seems it's waiting for console input:

> Does C:\MinGW\include specify a file name
> or directory name on the target
> (F = file, D = directory)? 

Maybe create an issue?

**Comment by seladb** [comment]
can you please paste a link to the CI job?

**Comment by v0l0dia** [comment]
This
https://ci.appveyor.com/project/v0l0dia/pcapplusplus/build/job/8y011uwx8rbaueq0

**Comment by seladb** [comment]
there is an issue with npcap install that I need to fix. But I'm not sure why this error happens

For now you can just let this test fail

**Comment by v0l0dia** [comment]
I canceled my recent PR because new functions in RawPacket were added as virtual. Considering changes in vtable of base class, it breaks binary backward compatibility. Myabe we may add them as non-virtual?

**Comment by seladb** [comment]
>  Considering changes in vtable of base class, it breaks binary backward compatibility

I'm not sure what you mean by that. What is the issue with adding these methods as virtual?

**Comment by v0l0dia** [comment]
Well I can't bring some official explanations rn. Here's some on SO:
https://stackoverflow.com/questions/37149479/when-do-we-break-binary-compatibility

But AFAIK, virtual methods are generally implemented via some sort of vtable, which is a part of class memory layout. It may be compiler-dependent though, say MSVC allows(allowed earlier?) adding virtual methods to the end of class layout without breaking binary compatibility. But lots of compilers don't allow this, al least you get undefined behavior (which is worse than crash).

For more explanation: say someone linked his software with old version of library. Then he decides to upgrade to the latest one. Simply using new library binary may (will?) lead to UB/crash, as original software was compiled considering some other class layout. For instance, if you put new virtual function "before" some existing one, actual adress of this function may (will) change. And older software that uses newer library will call wrong/invalid adress.

But adding non-virtual methods is always OK, as it has nothing to do with vtables and other stuff.

**Comment by v0l0dia** [comment]
Oh, wait, but does PcapPlusPlus even supports dynamic library build? If it's not the case then everything's OKAY. At least until someone uses pre-built binaries with old headers.

**Comment by seladb** [comment]
That's correct, PcapPlusPlus doesn't support dynamic linking. And anyway when people upgrade to a newer version of the library they should consider new methods will be added (virtual or non-virtual)

**Comment by v0l0dia** [comment]
Then we're good, I'll reopen the PR

**Comment by seladb** [comment]
PR #411 merged
