### ISSUE TITLE
pcpp::VlanFilter in pcpp::AndFilter must be added before other filter types

### ISSUE THREAD

**Issue by vflg** [seladb/PcapPlusPlus#409]
Hi,
I tried to built a pcpp::AndFilter with a pcpp::IPFilter, a pcpp::PortFilter and a pcpp::VlanFilter.
Calling setFilter for a pcpp::IFileReaderDevice with the and filter only succeeds if the pcpp::VlanFilter is the first filter added to the pcpp::AndFilter.
The following minimum example details the issue:

```
pcpp::IFileReaderDevice* myFileReader;
myFileReader = pcpp::IFileReaderDevice::getReader("[valid path to a .pcap file]");
if (!myFileReader-> open()){
  // [stop file reading if this is not working]
}

pcpp::PortFilter myPortFilter{12345678, pcpp::SRC}; // a valid port is used here
pcpp::IPFilter myIPFilter{"123.456.7.8", pcpp::SRC}; // a valid ip address is used here
pcpp::VlanFilter myVlanFilter{1};
pcpp::AndFilter myAndFilter;

myAndFilter.addFilter(&myPortFilter);
myAndFilter.addFilter(&myIPFilter);
myAndFilter.addFilter(&myVlanFilter);

myFileReader->setFilter(myAndFilter);
```
Compiling this works, but during the execution the setFilter() throws an error:
> Error compiling filter. Error message is: expression rejects all packets

if I simply change the order of the addFilter() calls and add the pcpp::VlanFilter first, the setFilter() call will work and packets can be read from the file:

```
pcpp::IFileReaderDevice* myFileReader;
myFileReader = pcpp::IFileReaderDevice::getReader("[valid path to a .pcap file]");
if (!myFileReader-> open()){
  // [stop file reading if this is not working]
}

pcpp::PortFilter myPortFilter{12345678, pcpp::SRC}; // a valid port is used here
pcpp::IPFilter myIPFilter{"123.456.7.8", pcpp::SRC}; // a valid ip address is used here
pcpp::VlanFilter myVlanFilter{1};
pcpp::AndFilter myAndFilter;

myAndFilter.addFilter(&myVlanFilter);
myAndFilter.addFilter(&myPortFilter);
myAndFilter.addFilter(&myIPFilter);

myFileReader->setFilter(myAndFilter);
```

the order of the pcpp::IPFilter and the pcpp::PortFilter does not matter. I think the pcpp::VlanFilter should not matter, too.

**Comment by seladb** [comment]
thanks for reporting this issue. I'll take a look and keep you posted

**Comment by seladb** [comment]
could you please let me know which OS are you using?

I've tried it with both WinPcap (on Windows) and libpcap 1.8.1 (on Linux). In WinPcap I do see this error but it doesn't show in libpcap. This might be an issue with WinPcap or old versions of libpcap as this thread applies: http://mailman.icsi.berkeley.edu/pipermail/zeek/2001-September/000183.html

**Comment by vflg** [comment]
I'm using ubuntu 18.04 and libpcap version is 1.8.1

**Comment by seladb** [comment]
I tried again and I still don't see the error, however when letting libpcap compile the filter it returns an error.

I'm not sure why having `vlan` at the end of the filter doesn't work, but it looks like a bug in libpcap and I raised this bug there: https://github.com/the-tcpdump-group/libpcap/issues/916

Let's see what their answer will be

**Comment by seladb** [comment]
As mentioned in https://github.com/the-tcpdump-group/libpcap/issues/916 it's a limitation in libpcap. I'll close this issue for now as it's not in my control
