### ISSUE TITLE
Error compiling with boost asio included before TcpLayer.h

### ISSUE THREAD

**Issue by krepver** [seladb/PcapPlusPlus#41]
A simple program fails to compile
```cpp
#include <boost/asio.hpp>
#include <TcpLayer.h>

int main() {
  return 0;
}
```
Error is
```
/home/krepver/Dev/lib/PcapPlusPlus-master/Dist/header/TcpLayer.h:88:3: error: expected identifier before numeric constant
   TCPOPT_NOP =    1,
   ^
```

Boost ends up including <netinet/tcp.h>, which has line 163 `# define TCPOPT_NOP		1`, so TCPOPT_NOP in TcpOption enum is replaced by "1".

My system is Ubuntu 16.04, gcc 4.9, boost 1.55

**Comment by seladb** [comment]
If I understand you correctly, the fix that needs to be done is replacing all values in TcpOption enum with a different name (for example: PCPP_TCPOPT_NOP instead TCPOPT_NOP), right?
Can you do this change and send me a pull request or do you prefer me to do it?

**Comment by krepver** [comment]
Yes, but i'm not sure about others. Yes, i will try to change and then send you a pull request
