### ISSUE TITLE
pcpp::IFileDevice::close() / pcpp::PcapNgFileReaderDevice::close() seem to reset filters

### ISSUE THREAD

**Issue by vflg** [seladb/PcapPlusPlus#410]
Hi,
I experienced some unexpected result when iterating through a file two (or more) times.
The following minimal example shows the issue:

```
pcpp::IFileReaderDevice* myFileReader;
myFileReader = pcpp::IFileReaderDevice::getReader("[valid path to a .pcap file]");
if (!myFileReader-> open()){
  // [stop file reading if this is not working]
}

pcpp::PortFilter myPortFilter{12345678, pcpp::SRC}; // a valid port is used here
pcpp::IPFilter myIPFilter{"123.456.7.8", pcpp::SRC}; // a valid ip address is used here
pcpp::VlanFilter myVlanFilter{1};
pcpp::AndFilter myAndFilter;

myAndFilter.addFilter(&myVlanFilter);
myAndFilter.addFilter(&myPortFilter);
myAndFilter.addFilter(&myIPFilter);

myFileReader->setFilter(myAndFilter);

// iterate through file:
pcpp::RawPacket rawPacket;
while(myFileReader->getNextPacket(rawPacket){
// [calculate sleep based on timestamps in packets to pause the iteration for a short time]
// [do something with the packet..]
}

// if getNextPacket() failed I assume that the EOF was reached
// to reset the file pointer to the start of the file I close and reopen the file (I'm not aware of any other method to reset the file pointer to the begining)
myFileReader->close();
myFileReader->open();

// iterate through file a second time:
pcpp::RawPacket rawPacket;
while(myFileReader->getNextPacket(rawPacket){
// [calculate sleep based on timestamps in packets to pause the iteration for a short time]
// [do something with the packet..]
}

```

It seems that the filters are deleted / reset after closing and reopening the file, the resulting packages of iteration 1 and iteration 2 are not the same.

Is this the intended behavior? I haven't found any information about this in the docs.
If this is intended, is there a way to reset the file pointer to the beginning, or do I need to manually save my filter and call setFilter() again after opening the file the second time?

**Comment by seladb** [comment]
Apparently this is the behavior of the underlying engine (libpcap/WinPcap/Npcap). It clears out the filter automatically when file is closed. The best option would be to save the filter and call `setFilter()` again after file is reopened

**Comment by vflg** [comment]
thanks for the quick response. 
I did this in the current implementation (as workaround), just wanted to clarify if this is the intended behavior.
Maybe other users will get stuck here, too.

**Comment by seladb** [comment]
I will add this to `setFilter()` documentation so it'll be more clear to users
