### ISSUE TITLE
example PfRingExample-FilterTraffic failed

### ISSUE THREAD

**Issue by kdtiankong** [seladb/PcapPlusPlus#412]
pf_ring has been installed,I run program PfRingExample-FilterTraffic command : ./Bin/PfRingTrafficFilter -r TCP -n ens160 -f ./tcp.cap -t 2; Out of luck,it failed:

                  Couldn't set ring [1] in channel [0] to the cluster [0]
                  Application terminated in error: Couldn't open 2 RX channels on interface 'ens160'.

I debug it,found funcation PfRingDevice.cpp:260 failed，I don't know what the problem is.
Can you help me，how can i solve the problem?

**Comment by seladb** [comment]
can you please share details on the machine and NIC you're running it on?

**Comment by kdtiankong** [comment]
virtual vmware machine
OS: CentOS 7, 
kernel: 3.10.0-693.el7.x86_64

ens160: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.80.81.6  netmask 255.255.255.0  broadcast 10.80.81.255
        inet6 fe80::a1ac:49da:5dc9:d741  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:85:40:56  txqueuelen 1000  (Ethernet)
        RX packets 475032  bytes 629687240 (600.5 MiB)
        RX errors 0  dropped 17564  overruns 0  frame 0
        TX packets 266662  bytes 152482728 (145.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 216  bytes 18696 (18.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 216  bytes 18696 (18.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by seladb** [comment]
can you please debug the return value from `pfring_set_cluster`? Is it by any change `-7`?

**Comment by kdtiankong** [comment]
Breakpoint 1, pcpp::PfRingDevice::openMultiRxChannels (this=0x6d9150, numOfRxChannelsToOpen=<optimized out>, dist=<optimized out>) at src/PfRingDevice.cpp:260
260				if (pfring_set_cluster(m_PfRingDescriptors[ringsOpen], channelId, clusterType) < 0)
Missing separate debuginfos, use: debuginfo-install glibc-2.17-292.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64 numactl-libs-2.0.12-3.el7_7.1.x86_64
(gdb) p pfring_set_cluster(m_PfRingDescriptors[ringsOpen], channelId, clusterType)
$1 = -1
(gdb) 


-1 is returned

**Comment by kdtiankong** [comment]
[
![8](https://user-images.githubusercontent.com/53823502/76511834-a7b4d080-648e-11ea-9a13-15ab16056774.png)
](url)

**Comment by seladb** [comment]
I did some research in PF_RING code and here is what I found:

`pfring_set_cluster` is implemented here: https://github.com/ntop/PF_RING/blob/55245f99dc18d7329d79c20d7b94e70e55207361/userland/lib/pfring.c#L977

it calls `ring->set_cluster` which is implemented here: https://github.com/ntop/PF_RING/blob/55245f99dc18d7329d79c20d7b94e70e55207361/userland/lib/pfring_mod.c#L636

This code calls `setsockopt` which goes to PF_RING kernel module.

Looking at `setsockopt` documentation: https://linux.die.net/man/3/setsockopt
When return value is `-1` the error indicator will be in `errno`.

Can you please share the value of `errno` right after the call to `pfring_set_cluster`?

**Comment by kdtiankong** [comment]
(gdb) 
pcpp::PfRingDevice::openMultiRxChannels (this=0x6d9150, numOfRxChannelsToOpen=<optimized out>, dist=<optimized out>) at src/PfRingDevice.cpp:262
262					LOG_ERROR("Couldn't set ring [%d] in channel [%d] to the cluster [%d]", numOfRingsPerRxChannel+1, channelId, channelId);
(gdb) 

Couldn't set ring [1] in channel [0] to the cluster [0]
274		if (ringsOpen < numOfRxChannelsToOpen)
(gdb) 
276			for (uint8_t i = 0; i < ringsOpen; i++)
(gdb) p errno
$1 = 22

**Comment by kdtiankong** [comment]
errno 22 means invalid argument, The command line argument occurs this problem or other else?

**Comment by seladb** [comment]
I think I found the bug! 

in this line: https://github.com/seladb/PcapPlusPlus/blob/57b6bc98653c751c02d1ce38521a31fbd9d41698/Pcap%2B%2B/src/PfRingDevice.cpp#L260

when calling `pfring_set_cluster` - `channelId` should be changed to `channelId+1`. 

Same thing with the error message: https://github.com/seladb/PcapPlusPlus/blob/57b6bc98653c751c02d1ce38521a31fbd9d41698/Pcap%2B%2B/src/PfRingDevice.cpp#L262

`channelId` should be changed to `channelId+1`. 

Can you make this fix in the code and verify it works?

**Comment by kdtiankong** [comment]
The example PfRingTrafficFilter demo program run successfully!! 
Thanks a  lot!!

**Comment by seladb** [comment]
Great! would you consider making this fix and create a PR?

**Comment by kdtiankong** [comment]
No,You can fix it. Thanks
