### ISSUE TITLE
Publish nuget

### ISSUE THREAD

**Issue by flamencist** [seladb/PcapPlusPlus#420]
Could you please publish pcapplusplus as nuget to nuget.org for simplest installation to VS projects? I can help

**Comment by seladb** [comment]
I'm very open to add PcapPlusPlus to NuGet, but unfortunately I don't know much about it.

If you can help that'd be great!

**Comment by seladb** [comment]
by the way, I've noticed that the large majority of packages in [nuget.org](nuget.org) are .NET packages. Do you think it's being used for native libraries as well?

**Comment by flamencist** [comment]
Yes. Most of all packages are .NET packages. But also you can find native libraries. For example [easyhook](https://www.nuget.org/packages/EasyHookNativePackage.redist/) and [detours](https://www.nuget.org/packages/Detours/) and so on.

**Comment by seladb** [comment]
got it. As I said, I'm very open to the idea. Would you like to help?

**Comment by flamencist** [comment]
Yes. I will prepare pull request. But also need to signin to nuget.org.

**Comment by seladb** [comment]
sure, I will sign up to nuget.org

**Comment by seladb** [comment]
FYI I've completed the sign up process to nuget.org

**Comment by seladb** [comment]
I'd like to follow up on this. Have you made any progress on this?

**Comment by flamencist** [comment]
I've created [nuget config](https://github.com/flamencist/PcapPlusPlus/commit/00bf3d6fa218219676688d5c7d96693975cb1eea) - used [CoApp](http://coapp.org/reference/write-nugetpackage.html) autopkg file. It's working for [debug\x86\VS2019](https://github.com/flamencist/PcapPlusPlus/blob/00bf3d6fa218219676688d5c7d96693975cb1eea/PcapPlusPlus.autopkg#L75). 
```
      [x86,v142,debug] {
         //lib:     { .\Common++\Lib\Common++.lib, .\Pcap++\Lib\Pcap++.lib, .\Packet++\Lib\Packet++.lib };
         symbols: { .\Common++\Lib\Common++.pdb, .\Pcap++\Lib\Pcap++.pdb, .\Packet++\Lib\Packet++.pdb };
         bin:     { .\Common++\Lib\Common++.lib, .\Pcap++\Lib\Pcap++.lib, .\Packet++\Lib\Packet++.lib };
      };
```
For other kinds of VS need to use different build destinations for Debug\Release, for VS2015\VS2017\VS2019 and create .dll for dynamic linking and .lib for static linking

**Comment by seladb** [comment]
Thanks for your work! 

Are you planning to work on the rest of the configurations as well?

Please keep in mind that a shared library option (DLL) for PcapPlusPlus is currently not available. There is an open issue for it: https://github.com/seladb/PcapPlusPlus/issues/61

**Comment by seladb** [comment]
@flamencist any progress on this?

**Comment by thorichelli** [comment]
Is nuget option still on the table?

**Comment by seladb** [comment]
Yes of course, however I'd like somebody to help me out since I'm not familiar with nuget

**Comment by seladb** [comment]
@flamencist @thorichelli are we still planning to pursue this? I need your help on this since I'm not familiar with nuget

**Comment by flamencist** [comment]
Yes I am planning to support nuget packaging. But need to setup different paths for vs2015,vs2017,vs2019 builds.
For example we could use for Packet++.lib
.\v142\Packet++\Lib\Packet++.lib for vs2019, 
.\v141\Packet++\Lib\Packet++.lib for vs2017,
.\v140\Packet++\Lib\Packet++.lib for vs2015. 
What do you think @seladb >

**Comment by seladb** [comment]
@flamencist what do you mean by different paths?

**Comment by flamencist** [comment]
I mean for all VS builds and releases used the path ```$(PcapPlusPlusHome)\Common++\Lib``` 
https://github.com/seladb/PcapPlusPlus/blob/5ef0c6da8c34b5d4155f865e94bdf83cb18fcbad/mk/vs/Common%2B%2B.vcxproj.template#L92
So need to setup different paths If we want to automate nuget publishing

**Comment by seladb** [comment]
why is this needed for nuget?

btw, there is a post build event that copies all files to `$(PcapPlusPlusHome)\Dist\$(Platform)\$(Configuration)`, for example:

https://github.com/seladb/PcapPlusPlus/blob/5ef0c6da8c34b5d4155f865e94bdf83cb18fcbad/mk/vs/Common%2B%2B.vcxproj.template#L134-L136

**Comment by seladb** [comment]
@flamencist I'd like to follow up on this issue. Should we close it or keep it open?

To be very honest, I don't see a lot of demand for publishing PcapPlusPlus on Nuget, probably because it's mostly used for .NET app/libraries. 

Let me know what you think.

**Comment by seladb** [comment]
I'm closing this issue for now. Please reopen it if there is more demand for publishing PcapPlusPlus on Nuget
