### ISSUE TITLE
AppVeyor MinGW builds failing

### ISSUE THREAD

**Issue by maruu** [seladb/PcapPlusPlus#427]
Hi,

as you may know I am currently preparing a pull request.

As instructed here [Contributing](https://github.com/seladb/PcapPlusPlus/blob/master/CONTRIBUTING.md), I have created an account on AppVeyor and TravisCI.

Both MinGW builds are failing on AppVeyor.

I only receive this output, so I think it is a problem with the setup of the environment and not with my changes to the code. I am new to using AppVeyor and TravisCI, so I don't know if this is a problem on my side or not. 

I have appended the received output for both builds down below:

MinGW32:
```
Build started
git clone -q --branch=415_avoid_unnecessary_copying https://github.com/maruu/PcapPlusPlus.git C:\projects\pcapplusplus
git checkout -qf 5a2e44492332864a65ed133fd023d99e756ba42a
Running Install scripts
if "%pcap_lib%"=="npcap" (ci\install_npcap.bat) else (ci\install_winpcap.bat)
Using Npcap free version npcap-0.96.exe
Downloading npcap-0.96.exe (718,600 bytes)...100%
```

MinGW64:
```
Build started
git clone -q --branch=415_avoid_unnecessary_copying https://github.com/maruu/PcapPlusPlus.git C:\projects\pcapplusplus
git checkout -qf 5a2e44492332864a65ed133fd023d99e756ba42a
Running Install scripts
if "%pcap_lib%"=="npcap" (ci\install_npcap.bat) else (ci\install_winpcap.bat)
Cloning into 'winpcap-installer'...
Downloading WpdPack_4_1_2.zip (775,788 bytes)...100%
7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
Scanning the drive for archives:
1 file, 775788 bytes (758 KiB)
Extracting archive: .\WpdPack_4_1_2.zip
--
Path = .\WpdPack_4_1_2.zip
Type = zip
Physical Size = 775788
Everything is Ok
Folders: 33
Files: 317
Size:       3255124
Compressed: 775788
if "%compiler%"=="mingw32" set PATH=%PATH%;C:\MinGW\bin&& appveyor DownloadFile http://ftp.ntua.gr/mirror/mingw/MinGW/Base/pthreads-w32/pthreads-w32-2.10-pre-20160821-1/pthreads-GC-w32-2.10-mingw32-pre-20160821-1-dev.tar.xz && 7z e pthreads-GC-w32-2.10-mingw32-pre-20160821-1-dev.tar.xz -oC:\pthreads && 7z x C:\pthreads\pthreads-GC-w32-2.10-mingw32-pre-20160821-1-dev.tar -oC:\pthreads && xcopy /Y C:\pthreads\include\* C:\MinGW\include && xcopy /Y C:\pthreads\lib\* C:\MinGW\lib
if "%compiler%"=="mingw-w64" set PATH=%PATH%;C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
if "%compiler:~0,4%"=="vs20" powershell -command "Invoke-WebRequest ftp://sourceware.org/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip -OutFile pthreads-w32-2-9-1-release.zip" && 7z x pthreads-w32-2-9-1-release.zip -oC:\pthreads
if "%use_zstd%"=="true" ci\install_zstd.bat %platform%
if "%pcap_lib%"=="npcap" (set PCAP_SDK_DIR=C:\Npcap-sdk) else (set PCAP_SDK_DIR=C:\WpdPack)
cd C:\projects\PcapPlusPlus
if "%compiler%"=="mingw32" configure-windows-mingw.bat mingw32 -m C:\MinGW -w %PCAP_SDK_DIR%
if "%compiler%"=="mingw-w64" configure-windows-mingw.bat mingw-w64 -m C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1 -w %PCAP_SDK_DIR% -s C:\msys64\mingw32
******************************************
PcapPlusPlus Windows configuration script 
******************************************
MinGW directory 'C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1' does not exist
Command exited with code 1
```

All other builds are successful.

I would be thankful if you can help me with resolving this so I can create my PR.

Br,
maruu

**Comment by seladb** [comment]
Can you try to restart both jobs on AppVeyor? It should resolve the first issue at least.

Also, can you please share the links for the failing jobs?

**Comment by maruu** [comment]
Hi,

I have already tried restarting several times.. it always gives the same output unfortunately.

Here are the links to the respective jobs:

https://ci.appveyor.com/project/maruu/pcapplusplus/build/job/wof8unfs1uh314g1

https://ci.appveyor.com/project/maruu/pcapplusplus/build/job/o0n32q2xajutsopm

**Comment by seladb** [comment]
I'm not sure why this is happening... to unblock you, please remove these tests for now. I'll take a look later today or tomorrow

**Comment by seladb** [comment]
Do you want to further analyze this or should we close this isseue?

**Comment by maruu** [comment]
Do I understand your intention to close this correctly, so that this is only happening with my instance of appveyor? Running the builds in the workflow of the git checks for every PR does not have this problem?

If it is okay for you if I ignore the mingw32 and mingw64 builds for further pull requests on my side it is okay for me to close this. I don't think that I can come up with extra time to further debug this issue, especially without having any clue whats going on.

**Comment by seladb** [comment]
It look like it is running properly now:

![image](https://user-images.githubusercontent.com/9059541/81149625-680ce100-8f33-11ea-94a7-40c2856b84ed.png)

**Comment by maruu** [comment]
Unfortunately not on my side...

![image](https://user-images.githubusercontent.com/2047922/81153181-f52b5680-8f82-11ea-8f66-83132e380d4b.png)

So, is it okay if I ignore these two builds for future PRs? The builds will be executed by the github checks anyways, where they seem to succeed..

**Comment by seladb** [comment]
The checks for every open PR are running on my user as well so both of us can see if they succeed or not. I'm not sure why the same checks are failing on your user...

**Comment by maruu** [comment]
Okay, then I think we can close this :-)
