### ISSUE TITLE
pcap_setdirection not working

### ISSUE THREAD

**Issue by maruu** [seladb/PcapPlusPlus#428]
Hi,

I have found a bug with the implementation of pcap_setdirection in the DoOpen function of Pcap++.

I am not sure why this hasn't surfaced yet and why the unit test has not been able to detect this error. (Regarding the unit test: the unit test has no way to check if the selective capturing is actually successful, it just checks if it can receive something, which it also could if the selective capturing doesn't work.)

First issue:
https://github.com/seladb/PcapPlusPlus/blob/0f456fc2a30e7f780db413d391412f3d67df94e2/Pcap%2B%2B/src/PcapLiveDevice.cpp#L286

On this line, the return value of pcap_setdirection is interpreted incorrectly. pcap_setdirection returns 0 on success and negative values on error.

Second issue:
When fixing the first problem, the returned error code states that the handle has not been activated. This is due to calling pcap_setdirection before pcap_activate. If the whole ifdef'd block is moved after the pcap_activate call, pcap_setdirection works as expected.

I will create a PR for this, after my MinGW builds are working again (maybe you can help me with that - see [Issue](https://github.com/seladb/PcapPlusPlus/issues/427)

Br,
maruu

**Comment by seladb** [comment]
Thanks for sharing! I also wonder how it wasn't surfaced yet. 

After we fix the bug itself we probably need to fix the unit-tests as well.

I really appreciate your efforts, let me know how I can help. I already replied on MinGW issue, let's work together to get it to work

**Comment by seladb** [comment]
Thanks for providing the fix, I really appreciate your contribution to this project!

PR was merged to `master`
