### ISSUE TITLE
ReassemblyStatus for TCPReassembly?

### ISSUE THREAD

**Issue by starliiit** [seladb/PcapPlusPlus#434]
Many thanks for this awesome library! It seems PcapPlusPlus is the only packet processing library with tcp reassembly feature that's still under active development and maintainence. Keep up the good work!

I've been using it to write an nfqueue-based network filtering application. Basically it works like this:
1. My user application opens a netlink socket, and use `recv` to read netlink messages from the socket. Each netlink message represents an IP packet, and each packet has its own unique packet id.
2. After reading the packet from the socket, I use PcapPlusPlus to parse the packet and get its payload. Then I would do some scanning to see if the payload matches some predefined patterns and if it matches I would drop the packet.
3. Dropping or accepting the packet is done by sending its packet id and a flag(DROP or ACCEPT) via the netlink socket. This step is called "Verdict".

When a big chunk of payload is divided into multiple parts(e.g. when IP fragmentaion and TCP segementation happen), I use `IPReassembly` and `TCPReassembly` to handle them. But the API of `IPReassembly` and `TCPReassembly` has a slight difference: When you feed packets to `IPReassembly`, you get `ReassemblyStatus` which tells you what the packet is and how it's handled:

```
- NON_IP_PACKET
- NON_FRAGMENT
- FIRST_FRAGMENT
- FRAGMENT
- OUT_OF_ORDER_FRAGMENT
- MALFORMED_FRAGMENT
- REASSEMBLED
```

You can decide how to handle the packet you feed to the `IPReassembly::processPacket` , by reading the `status`. 
For example:
1. if it's `NON_IP_PACKET` you can drop it immediately. 
2. If it's `OUT_OF_ORDER_FRAGMENT` you can store the packet id somewhere and wait for the IP defragmentation is done.
3. If it's `REASSEMBLED` you know payload is ready. You can scan the payload, and verdict all the packet ids you stored in 2.

But in `TcpReassembly` there' no such `status` we can read. A TCP packet may comes out of order so it's buffered by the reassembly engine. But we cannot know this immediately because the callback associated with this packet will only be called when the "in-order" packet arrives. So we cannot decide how to handle the packet after the `TcpReassembly::reassemblePacket` function call, like we did above for IP fragments.

I know this problem can be solved by some workarounds. For example, define a flag in the `userCookie` object, and only update this flag in the callback function. Then, check this flag after every `TcpReassembly::reassemblePacket` call, to see if callback funtion is actually called. 

But as I see it this is a little bit of inconvenient. Because `userCookie` object can only be passed once when you initialize the `TcpReassembly`, not every time you call the `TcpReassembly::reassemblePacket`. So you may have to share a map (e.g. map packet id to its status) or something like that.

IMO adding a `status` parameter for `TcpReassembly::reassemblePacket` would be a clean way to solve this problem. Anyway API compatibility is kept with function overloading.

This may be a somewhat strange use case, please share your thoughts about this. Thank you!

**Comment by seladb** [comment]
Thanks @starliiit for reaching out! This is indeed a very interesting use-case.

The reason `IPReassembly` returns status on every packet is because it doesn't use callbacks for providing the status, as opposed to `TcpReassembly` which does.

But of course we can add this feature to `TcpReassembly`. It shouldn't be that difficult. Would you like to give it a try?

**Comment by starliiit** [comment]
Please take a look at this PR #435

**Comment by seladb** [comment]
Thanks for creating the PR! I reviewed it and left a few comments, please take a look when you have some time

**Comment by starliiit** [comment]
I pushed a new commit based on your comments. Please check it out!

**Comment by seladb** [comment]
PR #440 was merged to `master`
