### ISSUE TITLE
Support for setting snapshot length 

### ISSUE THREAD

**Issue by wongsingfo** [seladb/PcapPlusPlus#436]
Very amazing library for packet manipulation! 

I found that setting a small snapshot length yields better performance, because live capturing would require less CPU time to copy and process the packets. It will be nice if pcap++ supports it. 

I think we only need to add a field to class `PcapLiveDevice::DeviceConfiguration` and change the following line.

https://github.com/seladb/PcapPlusPlus/blob/4366d2f86bf105025765a0ce3db6e647ba0f3508/Pcap%2B%2B/src/PcapLiveDevice.cpp#L244

**Comment by seladb** [comment]
Yes I agree that could be a nice addition to PcapPlusPlus. Please notice that if you limit the snaplen packets that are larger than the snaplen value will be truncated as explained here:

https://wiki.wireshark.org/SnapLen

Would you consider making this change an create a PR?

**Comment by wongsingfo** [comment]
OK. I am going to work on it.

**Comment by seladb** [comment]
PR #439 was merged to `master`
