### ISSUE TITLE
Provide pre-allocated and pre-filled buffer to Packet and assign PayloadLayer

### ISSUE THREAD

**Issue by maruu** [seladb/PcapPlusPlus#437]
Hi,

it's me again with a new proposal :-)

I will try to give you a background of what I am trying to achieve and I have already thought about the steps that are required to implement this. I wanted to hear your thoughts on this - maybe I have overlooked something or this is not a direction that you want PcapPlusPlus to evolve to.

**I have the following use-case:**
I need to provide the user of my library with a data buffer in which he can write its payload, that I then want to encapsulate into an Ethernet frame and send out. The data provided by the user is solely payload data. At the time of the user's request, I do not know which transport or routing protocol I am going to use, so I cannot build the Ethernet frame beforehand and use the already implemented SetPayload function of a PayloadLayer that I could add to the packet. Also, this would involve copying the data provided by the user to the PayloadLayer. I do not want that, since the payload involves complex data structures that the user could already construct in the provided data buffer.

I have visualized this here:
![image](https://user-images.githubusercontent.com/2047922/82227484-1cd9d180-9928-11ea-83fa-6de9e2360ef7.png)

As you can see, the buffer reserves memory in front of the payload location so a later addition of transport and routing protocol layers is possible.

You may ask yourself: How do you know how large the buffer needs to be so you can avoid costly reallocations?
Well, I know this very well for my use-case. For all other, I would implement the same reallocation strategy used in the available insertLayer method. And also, since the initial size of the buffer is not something that PcapPlusPlus has to mandate, but is actually provided by the user of the library, you don't limit the usability of this feature.

**What I need:**
A way to pass a pre-allocated and pre-filled buffer to the Packet. The payload which I can identify by pointer and length then needs to be encapsulated in a PayloadLayer.

This would involve adding the following constructor to the Packet:
Packet(uint8_t* buffer, size_t dataLen, uint8_t* payload, size_t payloadLen)

The buffer can also already be passed as a RawPacket.

The packet would then proceed to assign the buffer as its own Packet buffer and create a PayloadLayer with the given data pointer and length.

You may ask yourself: How can you add a layer to this packet, if the PayloadLayer is not at the start of the packet (i.e. not at the start of the linked list)?

For this, I propose a method called addLayerBefore() which does the reverse operation of the addLayer() method. 
The API looks like this: addLayerBefore(Layer* addBeforeThis, Layer* addThis)

The final packet will look like this, having added all needed layers:
![image](https://user-images.githubusercontent.com/2047922/82228019-d638a700-9928-11ea-8ce5-229a9dccb3fc.png)

As I have already mentioned in the graphic above, I think the resulting "wasted space" in some cases where too much has been allocated can be neglected on modern PCs with 16+GB of RAM :-)

Please let me know your thoughts. I will start with the implementation of this tomorrow, as I need this feature anyways. If you consider it useful, I will upstream the changes.

Sorry for the long post. :-)

Thanks and br,
maruu

**Comment by seladb** [comment]
hi, I'm sorry for the delayed response. 

I've read your use-case carefully and I hope I understand it well. If there's anything I'm missing please let me know.

As per my understanding you provide a data buffer to your users and they fill in some arbitrary data which you treat as a `PayloadLayer`. After you have the data you decide which transport and routing protocols to use, so you'd like to create these layers and add them to the same data buffer. 

If that is the case then you can create the data buffer and let the users write their data. Then you can create the routing/transport layer objects and copy their data to that buffer in the right places (you can use `Layer::getData()` and `Layer::getDataLen()` for that). After that you can create a `RawPacket` object that wraps this data buffer and then create a `Packet` object around it. The `Packet` object will parse the data automatically. Then you can make final changes to the packet before sending it on the network, for example: compute checksums etc. (you can use the `Packet::computeCalculateFields()` method to do it automatically).

I hope that covers most of your requirements. Please let me know if I'm missing anything

**Comment by maruu** [comment]
Hi,

thank you for your response and your thoughts.

I like your idea. I will discuss this with the other developers on the project and will get back to you on this. (Earliest I can do is monday..) Please ignore the draft PR for now, since I think that your mentioned workflow works better in this case.

Br,
maruu

**Comment by seladb** [comment]
sure @maruu please check with your team and get back to me

**Comment by maruu** [comment]
Hi @seladb 

sorry for the late response. I have talked to my colleagues about your proposal.

Please let me shortly summarize your proposal, so we make sure that there were no misunderstandings:
The frame is built by the user of PcapPlusPlus (me :-) ) by creating and adding layers manually to the buffer. Then the buffer is passed to the Parsing-workflow of the Packet, which then extracts necessary layer information from the buffer by means of parsing the raw frame. After that, changes can be made to the Packet through the provided API. (e.g. computeCalculateFields etc)

The problem I see with this approach is that the information about the layers already present in the buffer is lost by passing it to the Parsing-workflow as a raw byte array (or RawPacket). As soon as I only pass the raw byte data to the Packet, it has to extract information that my client application already has, since I am the one who has added all the layers manually to the packet.

For my use-case (high performance, avoid copying etc.) this seems like double the work for the application.

I see that you proposed this approach since it would not include any changes to PcapPlusPlus - I fully understand this. The draft PR I have already created for this issue where I have already implemented the needed functionality is messy - but I think that together with the improvements mentioned in [443](https://github.com/seladb/PcapPlusPlus/issues/443) this could be massively improved.

Maybe we can think about a performance-oriented way to solve this problem? Again, to avoid any misunderstandings, I will shortly summarize the requirements that I am faced with:

- Avoid copying as much as possible
- Avoid unnecessary computations when creating packets, since this must occur as fast as possible
- Have the ability to let the user write data into a buffer, which can later then be packaged into a frame with all of the necessary protocol headers. These protocol headers cannot be known in advance.

Please let us discuss this further and let us find a way on how to work this out together. Please also reconsider my initial proposal, adding the functionality of adding layers before an already present layer.

I'm looking forward to hearing from you.

All the best,
maruu

**Comment by seladb** [comment]
Thanks @maruu for getting back to me.

I think I understand your requirements better now, thank for providing the additional details.

I think my approach can still work with minimal data coping and parsing. Let me explain:
Once your users complete writing their data to the buffer you can write the transport and routing layers to the same buffer. I'd do that by creating the layers and then copy their data to the buffer, but if you want to avoid the copy you can write the data to the buffer directly without using layers.

Creating a `RawPacket` from this buffer costs almost nothing since `RawPacket` is just a wrapper around the buffer.

Creating the `Packet` object around `RawPacket` does have some overhead, but it's mainly for parsing the raw data into `Layer` objects for each protocol. This parsing process doesn't usually parse each and every field of every layer. In most protocols, the majority of the parsing work is to determine the boundaries of each layer. For example: in [`EthLayer`](https://github.com/seladb/PcapPlusPlus/blob/46840c644dfe9160c4111b06bbbf7731c9d1370c/Packet%2B%2B/header/EthLayer.h#L83) you can see that the c'tor does practically nothing, and same goes for [`IPv4Layer`](https://github.com/seladb/PcapPlusPlus/blob/46840c644dfe9160c4111b06bbbf7731c9d1370c/Packet%2B%2B/src/IPv4Layer.cpp#L210), [`TcpLayer`](https://github.com/seladb/PcapPlusPlus/blob/46840c644dfe9160c4111b06bbbf7731c9d1370c/Packet%2B%2B/src/TcpLayer.cpp#L294), [`UdpLayer`](https://github.com/seladb/PcapPlusPlus/blob/46840c644dfe9160c4111b06bbbf7731c9d1370c/Packet%2B%2B/header/UdpLayer.h#L47), etc. As you can see the overhead isn't huge and should be reasonable even for high performance systems.

BTW the reason behind parsing the bare minimum during layer creation is to reduce computation, but also to reduce complexity when packet is modified.

If you want to completely avoid any parsing or coping of data, PcapPlusPlus may not be the optimal solution for you. In those cases I'd advise to write a custom solution that will optimize your needs and requirements rather than using a "general purpose" library. 

But as I stated before, PcapPlusPlus should be able to meet your performance requirements. I know of few use cases where this library is being used in high performance / high-scale systems and users are pretty happy with it.

Please let me know what you think.

**Comment by maruu** [comment]
Hi @seladb,

sorry that it took me some while to get back to this. I have been thinking about your proposal and I have also tried to reflect your position on this topic. Currently, it is not an option for me to choose another solution other than PcapPlusPlus, since I have chosen it for its simplicity and its potential for extending it with further protocols. If you know of any other packet parsing / crafting library which would better suite my needs, I would be happy to hear about it. Maybe I have overlooked it when I was evaluating existing solutions.

Having stated that a switch to another solution is currently not an option for me, I would propose that I will try to meet my customer's requirements with your proposed approach. As you already know, I am not a fan of the fact that my application adds the layers to the buffer and then passes the raw buffer to the RawPacket. I understand your proposed workflow quite well, since I have already spent a lot of hours in the Layer / Packet / RawPacket implementations :-) What bothers me is that the information about the inserted layers, that my application already has, is lost by only providing the RawPacket with the raw buffer. Although you have undertaken steps to reduce computational effort while parsing, I still have to regain information that I would have already had at the first place. Since I am trying to avoid any unnecessary steps for performance sake, I hope you can see that this solution is not ideal for me. Overall, I think that this use-case could be implemented differently, which was the reason for my initial proposal.

What I would propose now is this: I will try your proposed approach, if it shouldn't suffice for me use-case I would get back to you and would include you more intensively in the solution finding process. I think that you, as the creator of the library, have much more insight into possible solutions than me. What I definitely want to avoid is to interfere with any of your architectural plans you have for the library. I understand that you see PcapPlusPlus as a general purpose library. Maybe we can then re-frame my requirements together, so they are more generally applicable? But this is a topic for another day.

I thank you for your thoughts and your time.

I will get back to this if something should not work out as required.

You will hear from me in #443 or with another issue/proposal. :-)

Br,
maruu

**Comment by seladb** [comment]
Thanks @maruu ! I certainty appreciate and admire your choice to go with PcapPlusPlus despite these architecture decisions that do not fit perfectly into your requirements.

I'm curious though what is the performance penalty you see. I'm sure you've measured it so sharing your would be very beneficial to me. I'm also curious what are the performance requirements you're trying to meet. It looks like you're using this library in a system that has pretty massive volume which is a very interesting and unique use-case. Anything you can share will help me come up with better solutions for your use-case.

If you don't want to share it publicly you can also shoot me and email: pcapplusplus@gmail.com

**Comment by maruu** [comment]
Hi @seladb ,

if you want we can close this so it does not unnecessarily push the number of open issues. 

As written in my previous answer, I would try to implement my requirements with your proposed solution and open another issue at a later time, if I am not able to meet my requirements.

Br,
maruu

**Comment by seladb** [comment]
thanks @maruu . Let me close this issue for now, we can reopen it at any time

**Comment by maruu** [comment]
Hi,

I am currently implementing your proposed approach in my system. One caveat I have stumbled upon is the following, maybe I have understood your proposal incorrectly and you can clarify further:

I have a memory buffer in which my user writes its payload.
I then create the Layer objects of the network layers that I require and copy their data in front of the user payload.
I then use the memory buffer as the basis for a rawPacket, and create a Packet from the raw packet.
Your intent, if I have understood it correctly, was that the packet will now parse the memory buffer for known layers and construct the list of protocols that it finds in my memory buffer. After it has done that, I can call computeCalculatedFields() on the packet and then all necessary fields should be set and I can send the packet.
The caveat I have stumbled upon lies in the parsing process of the involved layers. The parsing process of the underlying network layers require the fields that are being calculated by the call to computeCalculatedFields() to actually be already calculated before the parsing process. This is especially apparent with the case of the ETH-type field identifying the next layer that comes after the Ethernet layer. Of course, this field is not set if I just copy the data from the layers into a memory buffer and use this buffer to create a rawPacket. During the parsing process the Ethernet layer treats everything which comes after it as a PayloadLayer, since the Eth-type field does not identify any known protocol since it has never been set.

I hope you see my problem and can maybe further clarify how to correctly use your proposed approach.

Thanks,
maruu

**Comment by seladb** [comment]
I'm sorry for the late response @maruu.
I do agree that some fields need to be set beforehand in order for the parsing process to succeed. EthType is defiantly one of them.
If EthType is not set, it'd be very challenging (almost impossible) for the parser to guess what the next layer is.

Is there any specific reason why you can't set the EthType?

**Comment by maruu** [comment]
No, the type fields would not be the problem. But apart from them, I would also have to set all of the length fields, which would get a bit tedious. In essence, I would have to implement all of the `computeCalculateFields()` functionality on my own..

I just hoped that maybe I have overlooked something, and that this would not be necessary.. :-)

**Comment by seladb** [comment]
Unfortunately there is no way to avoid setting some of these fields which are important for parsing the packet.

However `computeCalculateFields()` can still be of use for complex calculations like checksum.

**Comment by maruu** [comment]
Thank you for the clarification!

Best regards,
maruu
