### ISSUE TITLE
when I parsed some raw packet,occurred core dumped!

### ISSUE THREAD

**Issue by NinethDimension** [seladb/PcapPlusPlus#441]
My project is using in security,so,the packet  is a little bit more complicated. when I received a lot packets from dpdk,occurred core dumped.I have been found the error packet from the pcap file in Wareshark. Can you help me to solve this problem? Thank you!
This is the error packet that copy from Wareshark.
0000   00 1c 54 ff 08 2a 00 03 b2 78 08 0a 08 00 45 00
0010   03 05 00 00 40 00 37 11 7c 9b 2a ec 25 48 ac 12
0020   c8 06 00 35 f1 22 02 f1 a2 22 0a 04 02 df 3c 43
0030   00 01 00 00 11 01 3a bd e7 7a 28 d7 ca 05 0d 6c
0040   93 95 85 95 4a 0e b2 00 b3 8e 4e ab 33 60 a1 ed
0050   12 bf ad 93 07 69 9e f7 a2 b4 d1 22 77 ca 50 3f
0060   c6 19 d5 80 b9 48 be 30 e0 40 e8 6a e1 88 44 18
0070   11 06 9b 07 9f 3c ff 52 a7 0b a0 03 aa 02 f7 55
0080   a5 01 a0 04 f4 0e a0 01 a5 50 f7 54 a4 07 a0 02
0090   a0 07 a6 0e ab 55 a4 50 aa 05 b9 03 a0 55 a4 57
00a0   f0 52 a0 02 f4 02 a0 04 aa 53 a0 02 a0 03 f3 55
00b0   ab 07 a6 52 f0 05 a7 06 f1 0e f3 05 a4 53 a1 54
00c0   f4 04 a3 1d a0 02 a0 00 f6 50 f3 02 ab 02 aa 00
00d0   a4 0f f6 00 a1 53 f7 06 a5 0f f7 03 ab 57 f3 54
00e0   a4 04 f3 55 a5 50 a6 54 f3 02 a2 07 f3 0f f7 0e
00f0   f0 03 a5 00 a6 04 f6 0e a5 0f a3 04 a1 0e a2 52
0100   a2 00 a5 06 9b 05 a2 18 a2 3f a2 3f a2 3f a2 3f
0110   a0 04 aa 06 9b 06 9b 3f 9b 3f 9b 06 9b 06 9b 3c
0120   f1 00 a0 54 f4 06 a1 01 f4 01 a1 53 f7 0e f3 55
0130   f7 0f f1 54 aa 53 f7 06 a6 00 a7 00 f7 53 f0 06
0140   b9 54 a6 0f f4 00 a4 00 f3 00 aa 07 a0 03 aa 0e
0150   a5 00 f0 03 f3 50 a2 57 f0 04 a2 02 a3 01 a1 0f
0160   aa 04 a5 00 f1 02 a7 55 f7 1d a1 05 f3 54 a4 57
0170   a7 05 a4 00 a0 05 a6 04 a7 52 aa 04 f4 02 a3 55
0180   f3 02 f7 57 a7 02 a5 52 f4 55 a0 04 a4 0e a0 0f
0190   a6 04 ab 50 ab 54 a5 05 a7 07 f3 04 f7 04 f3 0e
01a0   f7 01 a3 0f a3 57 a4 03 ab 50 9b 05 a2 18 a2 3f
01b0   a2 3f a2 3f a2 3f ab 05 a3 3f a2 3f 9b 3f 9b 3f
01c0   a2 3f a2 3f 98 01 f7 01 f0 06 aa 00 f1 07 f7 01
01d0   a4 54 ab 55 f6 04 a4 07 aa 57 f3 52 aa 07 a2 04
01e0   f0 50 a5 00 a5 1d f0 52 f3 00 a3 05 a5 06 f3 0e
01f0   ab 04 f3 57 a7 53 ab 05 aa 05 f3 0e a0 00 f7 50
0200   a7 57 f4 57 f4 54 f3 02 f6 05 f6 50 a0 50 b9 55
0210   a4 53 f1 53 f6 01 a1 05 a3 0e a3 00 f7 53 f0 52
0220   f4 0e a3 50 aa 55 f7 02 f0 53 a0 02 a7 53 a4 01
0230   a1 53 f7 0f a2 03 a0 53 a0 03 f4 00 ab 01 a7 50
0240   f4 07 ab 55 a7 52 f7 52 f7 05 a3 03 f1 0e a7 3f
0250   a1 06 bc 06 9b 06 9b 06 9b 06 9b 07 a1 01 a0 3f
0260   a2 3f 9b 3f 9b 3f a2 3f a2 3f 98 06 a5 04 a1 53
0270   a7 57 f7 02 a3 52 a6 02 a7 0f a4 57 a7 55 a6 50
0280   a6 57 a3 07 f1 57 f3 02 a1 04 a4 1d f4 05 a4 0f
0290   a0 54 aa 50 f0 57 aa 02 a0 57 a7 55 a0 55 f4 06
02a0   a5 0f f4 57 f1 07 f0 07 a7 05 a3 05 a2 57 a1 53
02b0   f3 55 f0 0e b9 0f a5 04 f0 00 ab 05 f1 07 a4 03
02c0   a5 06 f0 02 a2 06 f4 52 a5 06 f3 00 f3 02 a6 53
02d0   f1 01 a6 01 a1 52 aa 53 a2 53 a6 0e f0 04 a1 0e
02e0   a0 57 ab 06 a7 01 f4 07 f0 04 f0 01 f6 52 f6 00
02f0   a3 57 a0 02 f0 3f a1 06 bc 06 9b 06 9b 06 9b 06
0300   9b 07 a4 00 a1 3f a2 3f 9b 3f 9b 3f a2 3f a2 3f
0310   98 3b 98

 I have seen it is a DNS packet. And all of the error packets  are DNS packet. My pcap++ version is the lastest.

**Comment by seladb** [comment]
can you attach the pcap file that is causing the crush?

**Comment by NinethDimension** [comment]
[file_3.txt](https://github.com/seladb/PcapPlusPlus/files/4680761/file_3.txt)

**Comment by NinethDimension** [comment]
This is the raw pcap file .

**Comment by NinethDimension** [comment]
The last packet occurred the error.

**Comment by NinethDimension** [comment]
Program received signal SIGSEGV, Segmentation fault.
0x0000000000447262 in pcpp::IDnsResource::IDnsResource (this=<optimized out>, dnsLayer=<optimized out>,
    offsetInLayer=<optimized out>) at src/DnsResource.cpp:18
warning: Source file is more recent than executable.

**Comment by seladb** [comment]
Can you please share the code that causes your app to crash?

I ran [PcapPrinter](https://github.com/seladb/PcapPlusPlus/tree/master/Examples/PcapPrinter) on this file and it went smoothly, here is the output of the last packet (which is malformed, hence DNS parsing can't be completed):

> DNS layer contains more than 300 resources, probably a bad packet. Skipping parsing DNS resources
Packet length: 567 [Bytes], Arrival time: 2020-05-26 01:07:04.917963000
Ethernet II Layer, Src: 00:1c:54:ff:08:2a, Dst: 00:03:b2:78:08:0a
IPv4 Layer, Src: 172.18.200.6, Dst: 42.236.37.72
UDP Layer, Src port: 61731, Dst port: 53
DNS query response, ID: 2564; queries: 6288, answers: 1, authorities: 0, additional record: 32582

**Comment by NinethDimension** [comment]
Thank you ! 
This my test Code!

**Comment by NinethDimension** [comment]
#include <PcapFileDevice.h>
#include <Packet.h>
#include <stdlib.h>
#include <PacketUtils.h>
#include <iostream>
#include <fstream>
#include <PcapLiveDeviceList.h>
#include <PcapFileDevice.h>
#include <dirent.h>
#include <string>

using namespace std;
using namespace pcpp;

static int find_dir_file(const char *dir_name, vector<string> &v)//文件夹地址，文件列表
{
    DIR *dirp;
    struct dirent *dp;
    dirp = opendir(dir_name);
    while ((dp = readdir(dirp)) != NULL) {
        if (dp->d_type == DT_DIR)continue;
        v.push_back(std::string(dp->d_name));
    }
    (void) closedir(dirp);
    return 0;
}

int main(int argc, char **argv) {

    vector<string> v;
    string read_path = "/data/testdata/";
    string write_path = "/data/dstdata/";
    find_dir_file(read_path.c_str(), v);

    for (string s :v) {
        string filename = read_path + s;
        string dstfilename = write_path + s;
        PcapFileReaderDevice reader(filename.c_str());
        PcapFileWriterDevice writer(dstfilename.c_str());
        bool opflag = reader.open();
        opflag = writer.open();
        if (!opflag) continue;
        while (1) {

            RawPacket *rawPacket = new RawPacket;
            bool result = reader.getNextPacket(*rawPacket);

            if (!result) {
                break;
            }
            //Before parse the raw packet if core dumped the pcap will be record,
            //The last one is the bad packet
            writer.writePacket(*rawPacket);
            writer.flush();
            pcpp::Packet *parsedPacket = new Packet(rawPacket, true, UnknownProtocol, OsiModelTransportLayer);

            delete parsedPacket;
        }
        writer.close();
        reader.close();
    }
}

**Comment by NinethDimension** [comment]
I  tested 1.2t actual pcap files.  I read the pcap files and before parse the raw packet write them to a new pcapfile, if core dumped the error packets will be record.In theory ,the last one is the bad packet.

**Comment by NinethDimension** [comment]
I may have solved the problem,this morning I edit the [DnsLayer.cpp](https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/src/DnsLayer.cpp) 135 lines.

I changed the numOfOtherResources's type from uint16_t to uint32_t .I think this error probably occured by this variable.
You can see my shared pcap file , there are many DNS packets have more than 65535  resource in my pcap files. when this variable > 655535 it will be cut. if it happen to be less than 300 it will be parsing.

**Comment by NinethDimension** [comment]
uint32_t numOfOtherResources = numOfQuestions + numOfAnswers + numOfAuthority + numOfAdditional;

	if (numOfOtherResources > 100)
	{
		LOG_ERROR("DNS layer contains more than 100 resources, probably a bad packet. "
				"Skipping parsing DNS resources");
		return;
	}

**Comment by NinethDimension** [comment]
This error has never occurred in the same pcap files after I changed that.

**Comment by NinethDimension** [comment]
Thank you very very much!!

**Comment by seladb** [comment]
You find a very interesting bug in PcapPlusPlus, thank you so much!

I'm reopening this bug so we can fix it. Can you please attach a 1 packet pcap file that reproduces this issue?

Also, would you consider making this fix and create a PR?

**Comment by NinethDimension** [comment]
[11.txt](https://github.com/seladb/PcapPlusPlus/files/4687535/11.txt)
I find a packet,it has 65545 DNS resources it can ran to parsing.

**Comment by NinethDimension** [comment]
The error packet lead to core dumped  I don't find it. I think it could be a very large resource number and last 16 bit less than 300.

**Comment by NinethDimension** [comment]
I create a PR.

**Comment by seladb** [comment]
Thanks! I added a few review comments to your PR #442, can you please take a look?

**Comment by seladb** [comment]
PR #445 merge to `master`
