### ISSUE TITLE
Define clear separation of buffer management between RawPacket and Packet

### ISSUE THREAD

**Issue by maruu** [seladb/PcapPlusPlus#443]
Hello,

while implementing my recent proposal I found that the separation of buffer management is not clearly defined between RawPacket and Packet.

I see this at the following positions:
https://github.com/seladb/PcapPlusPlus/blob/46840c644dfe9160c4111b06bbbf7731c9d1370c/Packet%2B%2B/src/Packet.cpp#L31
https://github.com/seladb/PcapPlusPlus/blob/46840c644dfe9160c4111b06bbbf7731c9d1370c/Packet%2B%2B/src/Packet.cpp#L220-L228
https://github.com/seladb/PcapPlusPlus/blob/46840c644dfe9160c4111b06bbbf7731c9d1370c/Packet%2B%2B/src/Packet.cpp#L528-L535

Why does the Packet have to have information about the underlying buffer length?
Why does the Packet have to make the decision whether a reallocation is necessary?

I think that overall buffer management, as well as decisions on whether a has to occur reallocation should be separated into one component. The overall task of the RawPacket, as far as I have understood it, is to hold the RawData and manage it (e.g. destroy it, add something to it, remove something from it) - it would make sense - from my point of view - to also give the reallocation authority to it.

For the several code positions I have linked above, it is not essential to know whether a reallocation has happened or not, since the m_Data ptrs of the layers are updated anyways.

My proposal would be:
Push the complete buffer management to the Raw Packet. This would involve:

- Pushing the decision whether a reallocation is necessary or not to the Raw Packet, I think that the Packet does not need to know this - am I missing something here?
- Reallocations are automatically performed on inserts / extensions if they are deemed necessary
- Removal of the m_MaxPacketLen parameter of the Packet. Only the RawPacket knows about the length of the buffer. From my point of view, I dont see a reason why the Packet would need to know the buffer length, for it it is only relevant how long the underlying frame is (i.e. the RawData), or am I missing something here?

Furthermore, I would like to introduce an additional pointer and length variable to the RawPacket:

Use m_RawData and m_RawDataLen to point to (raw) frame inside of buffer

- m_RawData always points at the start of the frame - not necessarily the buffer
- m_RawDataLen always holds the length of the frame

Use m_Buffer and m_BufferLength to point to buffer

- m_Buffer always points to start of buffer
- m_BufferLength always holds the length of the buffer ( = m_MaxPacketLen)

I think that the pointer to the start of the buffer will make addition of other features (e.g. adding layers before the m_RawData ptr) much easier.

Please let us discuss about this and let me know your thoughts. :-)

br,
maruu

**Comment by seladb** [comment]
Thanks for your proposal. In a way it makes sense to move the buffer management to `RawPacket`. But in the current design `RawPacket` is a simple wrapper around the buffer, and the more complex logic resides in the `Packet` class. 

In most cases users don't create a `RawPacket`, they rather get it from a "device" object (a file, live device, etc.). Then they create a `Packet` object around it for parsing or editing of the packet.

In other use-cases users might want to create packets from scratch, and then they would create `Packet` objects and add layers to them. In those cases the `RawPacket` object is typically more "behind the scenes" and is used only for sending the packet on the wire or saving it to a file. The `m_MaxPacketLen` parameter was created for that use-case and that's the reason it resides in the `Packet` object.

I'm not saying we can't change this design, but we should think of these two main use-cases, which in high level can be summarized as:

1. Users who are interested in packet parsing of buffers coming from "devices"
2. User who are interested in modifying or creating packets

PcapPlusPlus API should be intuitive and easy to use for both of these use-cases.

Please let me know what you think.

**Comment by maruu** [comment]
Thank you for your quick response and for elaborating your thoughts.

I think that we have run into a misunderstanding here, since I am not entirely sure why this proposal would interfere with the mentioned use-cases. My intent was not to change any of the public interfaces of Packet, so in my opinion both of the use-cases would not be changed in any way. Please correct me if I am missing something here.

This change would only be relevant for developers actively developing PcapPlusPlus. No change would be visible for users of PcapPlusPlus, since none of the APIs are going to change.

The way I see it is, that with a clear separation of the buffer management between the Packet and RawPacket class, it is easier for developers to develop further features targeted at the Packet. For example, moving the decision whether the underlying buffer in the RawPacket needs to be reallocated or not to the RawPacket, which actually holds the buffer, would result in easier code for the Packet. This would not change any application behaviour for the user.

Please let me know what you think and if I could successfully re-state my intent :-)

**Comment by seladb** [comment]
If I understand your proposal correctly you suggest to move `m_MaxPacketLen` to `RawPacket` and let it can decide when to do data reallocation and what would be the new buffer size. Is that correct?

In that case let me ask a few questions:

- When users create a `Packet` object they give it the initial buffer size. Do you suggest `Packet` will pass it directly to its underlying `RawPacket` without storing it?
- When data reallocation happens, the `Packet` object needs to know about it because it needs to adjust the data pointer in each of the layers. This is mostly what happens now in `Packet::reallocateRawData()`. How do you envision this in the new design?
- I wouldn't introduce additional pointers inside `RawPacket` as it will make things more complex than what they already are. Unless you have a specific use-case where you think this complexity might be worth it?

**Comment by maruu** [comment]
Hi,

regarding your understanding of the proposal: Yes, this is correct.

Regarding the questions you have raised:

- Yes, I think that this would be the most suitable solution. 
- As far as I can tell, the data pointers of the layer are currently all reset to current pointers, independently of the event if the underlying buffer changed or not. Also independently of the event that e.g. an insertion happened after the layer, which would then not require an update of the data pointer of the layers before the insertion point. Currently, this is done nevertheless. So, pushing the reallocation decision to the RawPacket would not change any logic in the Packet, because currently the Packet implementation - sometimes - does unnecessary recalculations of all data pointers, although not all data pointers might be affected by a change. They would certainly all be affected if the underlying buffer has been reallocated. If you take a look at the insertLayer implementation Packet, the data pointers are first all updated to point to the new buffer in `Packet::reallocateRawData()` 
https://github.com/seladb/PcapPlusPlus/blob/cbe1ffdfe2deaf2fbdbae9c1c7927e083156c165/Packet%2B%2B/src/Packet.cpp#L190-L198
and then again all updated in the code of `Packet::insertLayer()`
https://github.com/seladb/PcapPlusPlus/blob/cbe1ffdfe2deaf2fbdbae9c1c7927e083156c165/Packet%2B%2B/src/Packet.cpp#L278-L298
Of course, this double update could be avoided by using if's. Furthermore, the RawPacket could return if a reallocation has happened to the users of the API (in this case Packet) to signal that all data pointers need to be updated.
- The introduction of the additional pointer is indeed deemed for easier addition of features in the future. I am still working out if these changes make sense in the current setting since I of course understand your position regarding the "general-purpose" aspect of the PcapPlusPlus library. Maybe we can talk about this in a different setting at a different time. :-) But I think that adding this pointer is not necessary at the moment. I will add it with a possible proposal in the future, if it should be necessary.

Please let me know if you have any further questions. I am looking forward to hearing from you.

Br,
maruu

**Comment by seladb** [comment]
I tend to agree with the points you made, but I think it'd be great if you can create a PR with the proposed changes and we can review them together. Please let me know what you think.

I'd separate those changes from the ones discussed in #437

**Comment by seladb** [comment]
@maruu do you think you can create a PR with your proposed changes?

**Comment by maruu** [comment]
@seladb Hi, I haven't forgotten about you. I will create the PR, it's just that some other things are currently on my to-do list with higher priority. If it's okay for you, I would leave this issue open until I have some time to create the PR.

I definitely agree with you about separating these changes from the ones discussed in #437.

Please let me know if this is okay for you, else I will talk to my colleagues about re-prioritizing this.

**Comment by seladb** [comment]
Thanks @maruu for getting back to me. Sure, we can leave the issue open until you have time to work on it.

On a separate thread, let's decide what's the next step on #437

**Comment by seladb** [comment]
hi @maruu can we close this issue?

**Comment by maruu** [comment]
Hi, sorry for the late reply, I was on vacation.

For now I think that this request can be closed, since with the other input you have provided, I have successfully reworked around some of the issues mentioned here.

Thank you for your patience. If anything similar comes up, or if I need to get back to this, I hope that it's okay for you if I reopen this issue?
