### ISSUE TITLE
sendPacket write twice

### ISSUE THREAD

**Issue by asaadmohammed74** [seladb/PcapPlusPlus#448]
calling sendPacket causes the packet to be send twice

`auto ethernetPacket = EthLayer(m_device->getMacAddress(), "ff:ff:ff:ff:ff:ff", PCPP_ETHERTYPE_ARP);
		auto arpPacket = ArpLayer(ArpOpcode::ARP_REQUEST, m_device->getMacAddress(), "00:00:00:00:00:00", GetLocalIP(), IPv4Address("192.168.1.56");
Packet arpRequest(50);
		arpRequest.addLayer(&ethernetPacket);
		arpRequest.addLayer(&arpPacket);
		arpRequest.computeCalculateFields();
m_device->sendPacket(&arpRequest);`

**Comment by seladb** [comment]
How do you know the packet is sent twice? Can you attach a screenshot or a way to reproduce it?

**Comment by asaadmohammed74** [comment]
![Capture](https://user-images.githubusercontent.com/33846280/84006908-d6e4bc00-a96f-11ea-9fee-5fb8fef79aab.PNG)

**Comment by seladb** [comment]
I ran the same code as mentioned above and only 1 packet is being sent. Could it be something with your code or network configuration?

**Comment by asaadmohammed74** [comment]
after some debugging, the buffer reaches `WriteFile` windows api. correctly  42 bytes.
but the write itself causes two packets to be sent

**Comment by seladb** [comment]
In that case it's probably something with the OS/network configuration in your Windows machine.

So I understand thee is no issue with PcapPlusPlus and WinPcap/Npcap?

**Comment by seladb** [comment]
Closing the issue now, please reopen if needed
