### ISSUE TITLE
Support DPDK 18.11.8 LTS out-of-box

### ISSUE THREAD

**Issue by rickyzhang82** [seladb/PcapPlusPlus#449]
I followed [the PcaPlusPlus doc recommended version](https://pcapplusplus.github.io/docs/dpdk#supported-dpdk-versions) to try on DPDK integration with PcapPlusPlus. I found that the latest DPDK 18.11 LTS changed its path target structure.

The DPDK doc suggest that two variables should be set:

- `$RTE_SDK `. The path to DPDK unzipped folder.
- `$RTE_TARGET `. The target DPDK is build. Eg, `x86_64-native-linuxapp-gcc`

Once DPDK was built, the static library and the header laid down to `$RTE_SDK\$RTE_TARGET` rather than `$RTE_SDK\$RTE_TARGET\build` (the current PcapPlusPlus assumes).

Do you want to support 18.11.8 LTS out-of-box? 

It is a minor fix. After the fix, the sample app like DPDK bridge stills works.

**Comment by seladb** [comment]
Thanks for letting me know!

Has the build folder changed between18.11.2 and 18.11.8? I'm currently using [18.11.2](https://github.com/seladb/PcapPlusPlus-DockerImages/blob/master/Dockerfile-ubuntu1604-dpdk1811) in [PcapPlusPlus CI](https://github.com/seladb/PcapPlusPlus/blob/0376f65957378c9235f9f094cec7c655ab836f15/.travis.yml#L31) and the build passes...

**Comment by rickyzhang82** [comment]
Under the `$RTE_SDK\$RTE_TARGET\build` folder, there will be no more `include` header folder.

The static libraries (not symlink) `lib` and the header `include` in 18.11.8 is under `$RTE_SDK\$RTE_TARGET`

**Comment by seladb** [comment]
I'm not sure I'm following you. 18.11 should have everything is under `$RTE_SDK/build`.

PcapPlusPlus CI uses 18.11.2 and I use 18.11.5 on my machine.

Here's how my folder structure looks like:

    |--$RTE_SDK/
      |-- build/
        |-- include/   (has symlinks to all header files)
        |-- lib/       (has all static libraries [not symlinks])
        |-- kmod/      (kernel modules)
        |-- app/
        |-- build/     (internal build files which aren't needed to build with DPDK)

**Comment by rickyzhang82** [comment]
I can't confirm when. But in 18.11.8 LTS the build folder has been changed:

```
|--$RTE_SDK/
  |--$RTE_TARGET/
    |-- app/
    |-- build/ (intermediate build binary)
    |-- include/ (actual file. not symlink)
    |-- kmod/
    |-- lib/ (actual static library file. not symlink)
```
You should not reference the build folder in 18.11.8 LTS. Please get 18.11.8 LTS and run `$RTE_SDK\usertools\dpdk-setup.sh`. You will see the change break the PcapPlusPlus build.

**Comment by seladb** [comment]
I just downloaded and installed DPDK 18.11.8 and I see the same folder structure.

One thing I do differently is that I don't use `$RTE+SDK/usertools/dpdk-setup.sh`. Instead I follow the instructions on [PcapPlusPlus web-site](https://pcapplusplus.github.io/docs/dpdk#download-and-install-dpdk) and [DPDK web-site](http://core.dpdk.org/doc/quick-start/) which is to run:
```
make config T=[platform_type_string] && make
```

**Comment by rickyzhang82** [comment]
Thanks for pointing it out. I will close it now.
