### ISSUE TITLE
license of PcapPlusPlus

### ISSUE THREAD

**Issue by alext234** [seladb/PcapPlusPlus#45]
I am curious about what the software license that it is adopting. GPLV3?

**Comment by seladb** [comment]
Hi, I was already asked this in the PcapPlusPlus support group: [https://groups.google.com/forum/#!topic/pcapplusplus-support/vR5csiyUY1Y](https://groups.google.com/forum/#!topic/pcapplusplus-support/vR5csiyUY1Y)
As I said in that page, you can use this library for whatever purpose you want, both commercial, open source, private use, etc. I'd appreciate the credit :)
I'm not sure what type of license is fit here, could be GPLv3 or some other license, I'd be happy to get your advice :)

**Comment by seladb** [comment]
At the end I chose going with Unilicense as it is the most permissive license I could find
