### ISSUE TITLE
configure-linux.sh not found

### ISSUE THREAD

**Issue by gerald-dotcom** [seladb/PcapPlusPlus#468]
I downloaded your pre-complied binary for Ubuntu which had tar.gz and uncompressed it. There is no configure-linux.sh.

**Comment by seladb** [comment]
The release file `tar.gz` contains pre-compiled binaries and header files, so there is no need to run `./configure-linux.sh`. The `tar.gz` file also contains and example app you can use to see how the binary files can be used (under `example-app/` and a `README.release` file containing detailed instructions.

Please let me know if anything is missing or can be explained better.

**Comment by gerald-dotcom** [comment]
Thanks...
