### ISSUE TITLE
Why do examples contains C code?

### ISSUE THREAD

**Issue by gerald-dotcom** [seladb/PcapPlusPlus#469]
This lib appear to be C++ but examples contain lot of C code. 

For example,

I see occurrences of .c_str() ,  #include "stdlib.h"

**Comment by seladb** [comment]
Yes, that's a good observation. The library mostly uses `printf()` which only accepts `char *` so every `std::string` object should be converted to `char *` through `.c_str()`.

At some point I'll probably replace it with `std::cout`.

**Comment by gerald-dotcom** [comment]
FYI, I noticed C-style casts like void pointer in some examples as I search through.

**Comment by seladb** [comment]
Yes that is true. I will put it in my todo list.

In the meantime if you want to make some of these changes please feel free to do so and create a PR.

**Comment by gerald-dotcom** [comment]
@seladb I absolutely can't do a PR. Just alone I can't even get-start at pointers to be honest. It just feel overwhelmed when working with Pointers. 

Honestly, I don't know what I'm doing when working with Pointers, I just know it just and will, must work.

**Comment by seladb** [comment]
Got it, that's totally ok.

If you are still interested in contributing to this project you can start with small changes that don't require handling with pointers like switching a `printf` statements to `std::cout` etc. Please let me know

**Comment by seladb** [comment]
I'll close this issue now as I don't think this is high priority.
