### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by gerald-dotcom** [seladb/PcapPlusPlus#470]
Makefile

`include /usr/local/etc/PcapPlusPlus.mk

# All Target
all:
        g++ $(PCAPPP_INCLUDES) -c -o main.o main.cpp
        g++ $(PCAPPP_LIBS_DIR) -o packetObserver main.o $(PCAPPP_LIBS)

# Clean Target
clean:
        rm main.o
        rm packetObserver`

main.cpp

`#include <iostream>
#include <stdexcept>
#include <stdio.h>
#include <IPv4Layer.h>
#include <Packet.h>
#include <vector>
#include <PcapLiveDeviceList.h>
#include <"shellExtension.h">

int main()
{    
    // Get Default Interface Name using Shell
    std::string defaultInterface = exec("ip r | awk '/^default/ {print $5}'");

    std::cout << defaultInterface << "\n";

    // Get Instance of Default Interface
    auto device = pcpp::PcapLiveDeviceList::getInstance().getPcapLiveDeviceByName(defaultInterface.c_str());

    std::cout << device -> getName() << "\n";
    return 0;
}`

Complied using Makefile. Ran the output using Ubuntu latest version's terminal.

Output 

`# ./packetObserver
eth0

Segmentation fault (core dumped)`

**Comment by gerald-dotcom** [comment]
Github sucks at formatting. So sorry!

**Comment by seladb** [comment]
Do you see that `device` contains an actual object and not NULL?

**Comment by gerald-dotcom** [comment]
> Do you see that `device` contains an actual object and not NULL?

No idea what you meant by that. I just used some of your users examples to write this code. 

Especially, https://github.com/seladb/PcapPlusPlus/issues/134

**Comment by gerald-dotcom** [comment]
> Do you see that `device` contains an actual object and not NULL?

How to check this actually? 

The crash happen at std::cout stage.

**Comment by seladb** [comment]
you should check if `device` has `NULL`, like that:

```cpp
if (device == NULL)
{
  printf("device is NULL\n");
}
```

If `device` is indeed `NULL` that means the default interface name you extracted cannot be found:

```cpp
std::string defaultInterface = exec("ip r | awk '/^default/ {print $5}'");
```

You can also check what value `defaultInterface` has and whether you have such an interface.

BTW, on Linux you might want to run your app with `sudo` in order for you app to be able to see all the interfaces

**Comment by gerald-dotcom** [comment]
I used your code. It print null but the interface is exists which is eth0 (Default).

**Comment by gerald-dotcom** [comment]
Even ran with Sudo. 

This` "ip r | awk '/^default/ {print $5}'"` prints eth0, both in code and manual terminal.

**Comment by seladb** [comment]
You can iterate over the devices in `pcpp::PcapLiveDeviceList::getInstance()` and see which interfaces you find therr

**Comment by gerald-dotcom** [comment]
I just ran below code and it print all devices including eth0 so it appear there is bug within your module that prevent accessing interface with interface name

```
for (auto dev : pcpp::PcapLiveDeviceList::getInstance().getPcapLiveDevicesList())
    {
        std::cout << dev->getDesc() << std::endl;
        if (!dev->getName())
        {
            std::cout << "\tno name" << std::endl;
            continue;
        }
        std::cout << "\t" << dev->getMacAddress().toString() << std::endl;
        std::cout << "\t" << std::string(dev->getName()) << std::endl;
        std::cout << "\t" << dev->getIPv4Address().toString() << std::endl;
    }
```

OUTPUT

        f2:3c:92:cc:a4:91
        eth0
        (IP HIDDEN FOR PRIVACY)

        00:00:00:00:00:00
        lo
        127.0.0.1
Pseudo-device that captures on all interfaces
        11:00:00:00:00:00
        any
        0.0.0.0
Bluetooth Linux Monitor
        73:00:27:4f:25:56
        bluetooth-monitor
        0.0.0.0
Linux netfilter log (NFLOG) interface
        20:00:0a:73:74:64
        nflog
        0.0.0.0
Linux netfilter queue (NFQUEUE) interface
        20:00:06:6c:6f:6f
        nfqueue
        0.0.0.0

**Comment by seladb** [comment]
The code for `pcpp::PcapLiveDeviceList::getInstance().getPcapLiveDeviceByName()` does pretty much the same:

https://github.com/seladb/PcapPlusPlus/blob/14a418ed4f9b72a832877dc8330e01259f617bf3/Pcap%2B%2B/src/PcapLiveDeviceList.cpp#L295

I suggest you debug it some more and try to find the root cause. This scenario isn't reproduced in my system...

**Comment by gerald-dotcom** [comment]
> The code for `pcpp::PcapLiveDeviceList::getInstance().getPcapLiveDeviceByName()` does pretty much the same:
> 
> https://github.com/seladb/PcapPlusPlus/blob/14a418ed4f9b72a832877dc8330e01259f617bf3/Pcap%2B%2B/src/PcapLiveDeviceList.cpp#L295
> 
> I suggest you debug it some more and try to find the root cause. This scenario isn't reproduced in my system...

I tried with std::string defaultInterface = "eth0"; and it works but ////exec("ip r | awk '/^default/ {print $5}'"); not, which also return eth0. 

Would you like to try with this function in your machine?

std::string exec(const char* cmd) {
    char buffer[128];
    std::string result = "";
    FILE* pipe = popen(cmd, "r");
    if (!pipe) throw std::runtime_error("popen() failed!");
    try {
        while (fgets(buffer, sizeof buffer, pipe) != NULL) {
            result += buffer;
        }
    } catch (...) {
        pclose(pipe);
        throw;
    }
    pclose(pipe);
    return result;
}

**Comment by gerald-dotcom** [comment]
Alright, the bug was resided inside the shell execution function that I copied and pasted from Stackoverflow. Fixed by using different answer.

Thanks for help anyway!
