### ISSUE TITLE
pcpp::ssl_tls_client_server_hello" has no member "CustomField"

### ISSUE THREAD

**Issue by gerald-dotcom** [seladb/PcapPlusPlus#471]
I'm trying to get value of a custom field that send on SSL client hello handshake but no idea how to do it. I thought this way would work but it seems it can't as per Intellisense. 

Since most examples are TCP, HTTP. I can't wrap my head around this. 

```
pcpp::SSLClientHelloMessage* clientHelloMessage = handshakeLayer->getHandshakeMessageOfType<pcpp::SSLClientHelloMessage>();

auto headers = clientHelloMessage -> getClientHelloHeader();
auto customvalue = headers -> CustomField;

```

**Comment by gerald-dotcom** [comment]
Actually the field is gmt_unix_time

It's not standard but most clients send it. 

Really want this!

**Comment by seladb** [comment]
I’m not sure what is this gmt_unix_time field. Where is it passed?

**Comment by gerald-dotcom** [comment]
Go here and search for gmt_unix_time
https://tools.ietf.org/html/rfc2246


It's passed in Client Hello Message's Random Object

**Comment by gerald-dotcom** [comment]
The ClientHello message includes a random structure, which is used
  later in the protocol.

     struct {
         uint32 gmt_unix_time;
         opaque random_bytes[28];
     } Random;

  gmt_unix_time
     The current time and date in standard UNIX 32-bit format
     (seconds since the midnight starting Jan 1, 1970, UTC, ignoring
     leap seconds) according to the sender's internal clock.  Clocks
     are not required to be set correctly by the basic TLS protocol;
     higher-level or application protocols may define additional
     requirements.  Note that, for historical reasons, the data
     element is named using GMT, the predecessor of the current
     worldwide time base, UTC.

  random_bytes
     28 bytes generated by a secure random number generator.

**Comment by gerald-dotcom** [comment]
@seladb 

Any update on this?

I've looked the source code and found following but not sure whether it's would work automatically by to putting  that Random struct nested inside struct ssl_tls_client_server_hello : ssl_tls_handshake_layer

Your library is complex and I can't wrap my head around it. 

#pragma pack(push, 1)
	struct ssl_tls_client_server_hello : ssl_tls_handshake_layer
	{
		/** SSL/TLS handshake version (one of ::SSLVersion) */
		uint16_t handshakeVersion;
		/** 32-bytes random number */
		uint8_t random[32];
	
	};
#pragma pack(pop)

**Comment by gerald-dotcom** [comment]
@seladb

I put that nested structure inside the guessed structure and I'm seeing output but not sure whether it's exact output or something else, but looks really like Unix Timestamp. 

I haven't done any parsing, just dropped nested one inside the other and magically output came. I had observations that you automatically parse buffer to those structures.

**Comment by gerald-dotcom** [comment]
If you can confirm what I done is correct or not, it would be great....

**Comment by gerald-dotcom** [comment]
Well, It appear it causes another bug

Cipher Name TLS_NULL_WITH_NULL_NULL

I'm seeing thousands of these and the whole thing turned into a mess....

**Comment by gerald-dotcom** [comment]
I just ran pre-complied binary of yours and modified header files at /usr/.....

Now, it appear Cipher Name TLS_NULL_WITH_NULL_NULL loop is gone..

I actually tried to add GREASE Cipher Support and I believe adding that caused the break. 

Need to research this again....

**Comment by gerald-dotcom** [comment]
Fixed all. Thanks for bearing with my spam!

**Comment by seladb** [comment]
I'm sorry for the late response. Can you please elaborate on what fix you made to solve your problem?

`gmt_unix_time` [was deprecated](https://tools.ietf.org/id/draft-mathewson-no-gmtunixtime-00.txt) a few years ago as per my understanding. You can still use `ssl_tls_client_server_hello->random` and extract the first 4 bytes to get this field

**Comment by gerald-dotcom** [comment]
> I'm sorry for the late response. Can you please elaborate on what fix you made to solve your problem?
> 
> `gmt_unix_time` [was deprecated](https://tools.ietf.org/id/draft-mathewson-no-gmtunixtime-00.txt) a few years ago as per my understanding. You can still use `ssl_tls_client_server_hello->random` and extract the first 4 bytes to get this field

I have added nested Random struct bearing that time field  on struct ssl_tls_client_server_hello : ssl_tls_handshake_layer

That's all I did, it magically started to work. 

This is a draft and it's not published. The field is still active. 
https://tools.ietf.org/id/draft-mathewson-no-gmtunixtime-00.txt

**Comment by gerald-dotcom** [comment]
I actually sucks at working with Binary. Head feel so overwhelmed and frozen.
