### ISSUE TITLE
TLS doesn't seems output specific cipher suites

### ISSUE THREAD

**Issue by gerald-dotcom** [seladb/PcapPlusPlus#473]
Besides GMT Time field issue, I discovered an another bug that resides inside cipher suites output.

Client Hello Request's  Cipher Suites Output (Tested from here https://clienttest.ssllabs.com:8443/ssltest/viewMyClient.html)

TLS_GREASE_9A (0x9a9a) | -
TLS_AES_128_GCM_SHA256 (0x1301)   Forward Secrecy | 128
TLS_AES_256_GCM_SHA384 (0x1302)   Forward Secrecy | 256
TLS_CHACHA20_POLY1305_SHA256 (0x1303)   Forward Secrecy | 256
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)   Forward Secrecy | 128
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)   Forward Secrecy | 128
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)   Forward Secrecy | 256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)   Forward Secrecy | 256
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca9)   Forward Secrecy | 256
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8)   Forward Secrecy | 256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)  WEAK | 128
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)  WEAK | 256
TLS_RSA_WITH_AES_128_GCM_SHA256 (0x9c)  WEAK | 128
TLS_RSA_WITH_AES_256_GCM_SHA384 (0x9d)  WEAK | 256
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)  WEAK | 128
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)  WEAK | 256

PcapPlusPlus C++ Client Hello Request's  Cipher Suites Output

TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_256_GCM_SHA384
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_256_CBC_SHA

it appear the following Cipher Suites are missing from PcapPlusPlus Output,

TLS_GREASE_9A (0x9a9a)
TLS_AES_128_GCM_SHA256 (0x1301)
TLS_AES_256_GCM_SHA384 (0x1302)
TLS_CHACHA20_POLY1305_SHA256 (0x1303)

**Comment by gerald-dotcom** [comment]
Update:

I converted the ExtensionTypeInt into Hex Value with 0x and 4 zero padding. 

Extension Type 0x3a3a

It appear to me the Grease Cipher Suite is recorded as an extension but I'm not sure. Quite hard to debug as the value change over next requests, may have different Grease Cipher Suite values. 

Extension Type 0x8a8a was recorded in second request I made but in really these are Cipher Suites rather Extensions.

**Comment by gerald-dotcom** [comment]
Another update:

GREASE it-self generate random extensions over next requests as per RFC 8701. 

That's quite interesting.

**Comment by seladb** [comment]
The 4 cipher suites you mentioned are indeed not supported in PcapPlusPlus. It should be pretty easy to add them. Here is the file that contains all supported cipher suites:

https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/src/SSLHandshake.cpp

Do you have a pcap file I can use to test them?

**Comment by gerald-dotcom** [comment]
@seladb I did add to that file but it behaved so wired and encountered endless loop of **TLS_NULL_WITH_NULL_NULL**. 

I'm going to go with raw Hex approach and parse them by myself.

**Comment by seladb** [comment]
Do you have a pcap file I can use to test these cipher suites?
