### ISSUE TITLE
Any examples on accessing values of IP Header Options/Extensions?

### ISSUE THREAD

**Issue by gerald-dotcom** [seladb/PcapPlusPlus#474]
I'm trying to access values of IPv6's Frag Extension and IPv4's RecordRoute Option but couldn't figure out a way to do so.

Looks like most methods are to add those when crafting not at parsing. I'm looking for parsing.

Appreciate your help on this matter!

**Comment by seladb** [comment]
IPv6 extension parsing happens automatically when the packet is parsed. Please use these references to understand how to access the frag extension data:

- [IPFragUtil](https://github.com/seladb/PcapPlusPlus/tree/master/Examples/IPFragUtil)
- [Packet++ unit-tests])https://github.com/seladb/PcapPlusPlus/blob/14a418ed4f9b72a832877dc8330e01259f617bf3/Tests/Packet%2B%2BTest/Tests/IPv6Tests.cpp#L69)

**Comment by gerald-dotcom** [comment]
Thanks, I was able to access values using dot notion.
