### ISSUE TITLE
Parsing Endace captures

### ISSUE THREAD

**Issue by jmazar** [seladb/PcapPlusPlus#475]
I have some .erf files which came from my Endace monitoring cards. I've tried to parse them using PcapPlusPlus with no success. I can successfully create a reader, but the first time I call `open()` the program crashes. Dunno if this isn't something that should work in general, or if I'm doing something wrong.

Thanks for the guidance.

**Comment by seladb** [comment]
I’m not sure what is .erf format. Is it similar to pcap format?

**Comment by jmazar** [comment]
Yeah, very similar to pcap. You can think of it as another layer. It's a format used by Endace network capture cards. https://wiki.wireshark.org/ERF. I followed these instructions https://www.netresec.com/?page=Blog&month=2012-11&post=Convert-Endace-ERF-capture-files-to-PCAP and was able to get my packets read with pcpp. I did notice you weren't able to identify the VLAN layers name though. Is that expected?

**Comment by seladb** [comment]
My understanding is that the ERF format is not similar to PCAP. 
PcapPlusPlus currently supports PCAP and PCAP-NG formats only. 

I'm not sure I understand your question about identifying the VLAN layer name. Can you please elaborate on that?

**Comment by seladb** [comment]
Let me close this issue for now. Please reopen it if you have additional information to share.
