### ISSUE TITLE
Looking for a way to modify outgoing packets from network interface

### ISSUE THREAD

**Issue by gerald-dotcom** [seladb/PcapPlusPlus#476]
I'm particularly interested in modifying outgoing (From my server) ACKs and SYNs replies. 

I know this is possible with PcapPlusPlus based on that Google Group's firewall thread but I'm not sure how I go implement this at first place. 

Would it be possible for you to put an example?

I'm worried about Duplicate Packets as-well. Eg, We edit Packet but Packet already transmitted by the Server/NIC. 

I don't know how to edit at first place. All examples I observed are for raw Pcap Files.

**Comment by gerald-dotcom** [comment]
https://pcapplusplus.github.io/docs/tutorials/packet-crafting#packet-editing

For example, This tut looks so smooth but I'm not sure whether this would work with live network interface and whether Pcapp hold the packet till we do the editing.

**Comment by seladb** [comment]
Can you please explain your use-case better?

Please keep in mind that you PcapPlusPlus App will not replace the server, so like you mentioned the server will send its own ACK or SYN/ACK packets and you app will send the modified packets, which will cause duplicates and unexpected behavior.

In most use-cases PcapPlusPlus acts as a [packet sniffer](https://en.wikipedia.org/wiki/Packet_analyzer) rather than replacing the client or the server.

**Comment by gerald-dotcom** [comment]
> Can you please explain your use-case better?
> 
> Please keep in mind that you PcapPlusPlus App will not replace the server, so like you mentioned the server will send its own ACK or SYN/ACK packets and you app will send the modified packets, which will cause duplicates and unexpected behavior.
> 
> In most use-cases PcapPlusPlus acts as a [packet sniffer](https://en.wikipedia.org/wiki/Packet_analyzer) rather than replacing the client or the server.

@seladb But as I see on this Google Thread, It's possible to archive packet modification on the fly

https://groups.google.com/forum/#!topic/pcapplusplus-support/6XubJ_YfTvo

My use-case is the same. I'm building a firewall that safeguard against Nmap style attacks. 

I know that PcapPlusPlus  will not replace the server but what i'm trying to do is modifying outgoing packets that goes into Client. 

It's quite hard to patch Kernel and maintain it. Otherwise I would have gone with that route. 

Does your DPDK implementation can hold outgoing packets till the modification begin done into packet so that it can be sent into the client?

**Comment by seladb** [comment]
In the thread you mentioned they were using PcapPlusPlus inside a man-in-the-middle application where their application acted as a bridge/switch and passed packets between interfaces. In this case you can indeed receive packets on one interface, change them and then send them on another interface. 

If this fits your use-case I'd recommend using DPDK. You can take a look on the [DpdkBridge example](https://github.com/seladb/PcapPlusPlus/tree/master/Examples/DpdkBridge) to understand how to achieve this.

**Comment by gerald-dotcom** [comment]
@seladb  I will look into this. Does that Bridge hold packets until we clear them via processing (aka running through Logic)? 

By all means, I want to avoid duplicate packets.

**Comment by gerald-dotcom** [comment]
@seladb  The issue can be closed, I got the idea. If I have further question, I will notify here.
