### ISSUE TITLE
DPDK: make install

### ISSUE THREAD

**Issue by gerald-dotcom** [seladb/PcapPlusPlus#478]
I've had chance to look into DPDK today and followed their installation guide. Complied the source then ran make install which created files inside /usr/local/share/dpdk

Should I include this path in pcapplusplus configuration?

**Comment by gerald-dotcom** [comment]
I think I shouldn't.

**Comment by seladb** [comment]
Yes, you shouldn't. You need to provide DPDK source path to PcapPlusPlus
