### ISSUE TITLE
cp: cannot stat 'examples/*, cannot stat 'mk/PcapPlusPlus.mk'

### ISSUE THREAD

**Issue by gerald-dotcom** [seladb/PcapPlusPlus#479]
I tried to do make only with libs and ran install then cp: cannot stat 'examples/* no such a file or dir came up, and I went on and edited install.sh script and removed examples/ after that re-ran make install, but again for the first time I see it return cannot stat 'mk/PcapPlusPlus.mk'

**Comment by gerald-dotcom** [comment]
The reason I went with making only libs because when I run make all, the make fail with /PcapPlusPlusSource/Examples/DpdkExample-FilterTraffic/main.cpp:457: undefined reference to `pcpp::DpdkDevice::m_RSSKey'

**Comment by gerald-dotcom** [comment]
Update:

I removed DPDK examples from makefile and it was able to built and install successfully but yet I still have to test DPDK functionality

**Comment by seladb** [comment]
Which DPDK version are you using?

**Comment by gerald-dotcom** [comment]
@seladb dpdk-stable-18.11.8

**Comment by seladb** [comment]
DPDK 18.11 is supported and runs smoothly in the CI, I'm not sure why you're getting this error

**Comment by gerald-dotcom** [comment]
it looks like "make" doesn't obey "if def" rules on Makefile.

I haven't initialize DPDK yet that's why DPDK examples can't compile.

Right now, I'm working on setting up DPDK as my server has only 1 NIC therefore losing SSH connection as soon as it set up.
________________________________

**Comment by gerald-dotcom** [comment]
Even tho you have to fix the install script because it trying to copy examples since examples are not build during libs only mode, it fails too.
________________________________

**Comment by gerald-dotcom** [comment]
I'm closing this issue because DPDK is not stable with my server, I'm taking different approach.
