### ISSUE TITLE
Isn't Possible to use startCaptureMultiThread() for multi devices in PF Ring?

### ISSUE THREAD

**Issue by gerald-dotcom** [seladb/PcapPlusPlus#481]
Question same  as title....

**Comment by seladb** [comment]
Can you please elaborate more on your use-case?

**Comment by gerald-dotcom** [comment]
@seladb Oh. I'm tired of answering use case every-time. If you followed my other threads, you should probably already know what's it. 

I need to bridge the two interfaces and route packets back and forth between them.

**Comment by gerald-dotcom** [comment]
As far as I see, the feature already exists in your DPDK but not so in PfRing. DPDK is not stable enough for me hence the PfRing.

**Comment by seladb** [comment]
I think it should be supported. What makes you think it's not?

**Comment by gerald-dotcom** [comment]
@seladb because startCaptureMultiThread only allows to specify a single interface.

It also allows to specify another NIC as outgoing NIC but the issue here is that I can't capture packets from outgoing NIC, only sending is possible with your PFRing implementation and isn't possible to capture packets back and forth from both interfaces.

**Comment by seladb** [comment]
I'm not sure I understand.

My understanding is that you have 2 interfaces: one that captures packets from the client and sends them towards the server, and another that captures packets from the server and sends them towards the client. Is that correct?

In that case you can have both interfaces capturing packets and send them to the other side.

What am I missing here?

**Comment by gerald-dotcom** [comment]
"My understanding is that you have 2 interfaces: one that captures packets from the client and sends them towards the server, and another that captures packets from the server and sends them towards the client. Is that correct?"

One that capture packets from the client coming from #1 NIC and send them towards to #2 NIC
Another that capture packets from coming from #2 NIC and modify them and send them towards to #1 NIC (Outgoing which then send to client. )


Your implementation only allows following,


Open Multi Threads -> A thread -> 1 NIC Capture -> Forward -> #2 NIC
                              -> B thread -> 1 NIC Capture -> Forward -> #2 NIC

Here, as you see it's 1 way flow, and isn't possible to capture both interfaces independently in independent threads like your DPDK implementation does. 

Your DPDK implementation allows following,

Open Multi Threads -> A thread -> 1 NIC Capture -> Forward -> #2 NIC
                              -> B thread -> 2 NIC Capture -> Forward -> #1 NIC


Please let me know if you still don't understand

**Comment by seladb** [comment]
I think you mean that the PF_RING implementation doesn't have the concept of worker thread, similar to `DpdkWorkerThread`, is that correct?

Yes, this part is indeed missing. No one requested it until now :)
Most people who build a switch or firewall app use DPDK and not PF_RING.

**Comment by gerald-dotcom** [comment]
Correct.

DPDK actually sucks for me. It doesn't support my NIC cards. PF_RING is simple and easy to use. 


So what to do?

**Comment by gerald-dotcom** [comment]
PF_RING itself support this, I don't know why you didn't added this

https://www.ntop.org/guides/pf_ring/examples.html#multi-threaded

"zbalance (in PF_RING/userland/examples_zc) is a sample application able to capture traffic from one or multiple interfaces, and load-balance packets to multiple consumer threads."

But I really need this, either elegant solution or hack (Temp workaround)

**Comment by gerald-dotcom** [comment]
By the way, I noticed the packet is a const on your PF Ring Implementation which means I can't modify it. Why did you made it a const?

		/**
		 * Send a raw packet. This packet must be fully specified (the MAC address up)
		 * and it will be transmitted as-is without any further manipulation.
		 * This method doesn't change or manipulate the data in any way (hence the "const" declaration).
		 * Note this method flushes the TX queues after the data is sent. So if you want to send several packets
		 * In the burst please use sendPackets()
		 * @param[in] rawPacket The raw packet to send
		 * @return True if raw packet was sent completely, false otherwise
		 */

**Comment by seladb** [comment]
Actually PF_RING ZC (Zero Copy) mentioned in your comment is not yet supported in PcapPlusPlus, please read [this section](https://pcapplusplus.github.io/docs/features#pf_ring-support) in PcapPlusPlus documentation.
Only [Vanilla PF_RING](https://www.ntop.org/guides/pf_ring/vanilla.html) is currently supported which doesn't really bypass most of the kernel network processing. 
PF_RING ZC also have a list of supported NICs as you can read [here](https://www.ntop.org/guides/pf_ring/zc.html). I believe all of the NICs in this list are already supported in DPDK, and of course DPDK supports many more.

The reason it wasn't implemented is that it was less of a priority to me, as most users who build high throughput applications use DPDK these days. Vanilla PF_RING is for applications who need more throughput than libpcap but don't want to have specific NIC or setup requirements.

Regarding your question on `PfRingDevice::sendPacket()` - the `RawPacket` is const which means `sendPacket` cannot change it. But it doesn't mean *you* can't change it before calling `sendPacket`. I hope that makes sense.

**Comment by gerald-dotcom** [comment]
> Actually PF_RING ZC (Zero Copy) mentioned in your comment is not yet supported in PcapPlusPlus, please read [this section](https://pcapplusplus.github.io/docs/features#pf_ring-support) in PcapPlusPlus documentation.
> Only [Vanilla PF_RING](https://www.ntop.org/guides/pf_ring/vanilla.html) is currently supported which doesn't really bypass most of the kernel network processing.
> PF_RING ZC also have a list of supported NICs as you can read [here](https://www.ntop.org/guides/pf_ring/zc.html). I believe all of the NICs in this list are already supported in DPDK, and of course DPDK supports many more.
> 
> The reason it wasn't implemented is that it was less of a priority to me, as most users who build high throughput applications use DPDK these days. Vanilla PF_RING is for applications who need more throughput than libpcap but don't want to have specific NIC or setup requirements.
> 
> Regarding your question on `PfRingDevice::sendPacket()` - the `RawPacket` is const which means `sendPacket` cannot change it. But it doesn't mean _you_ can't change it before calling `sendPacket`. I hope that makes sense.

My SSH getting disconnected after running DPDK.  Since my network only has 1 NIC which is Virtio, it's quite impossible to use DPDK without extra leg work. 

By leg work, I mean writing custom XDP code. I have no experience in XDP. 

PFRing runs on Transparent Mode 0 and it has no effect on my SSH. 

Is it impossible to achieve build firewall without zero copy implementation? 

I don't care about performance

**Comment by gerald-dotcom** [comment]
@seladb I have confirmation that one don't need zero copy to build firewall, it can be done without that. 

But I still need a way to somehow capture both interfaces.

Would two separate C++ apps that use your Lib could solve this?

I mean we write one program for watching one interface and another for other interface then run both apps in separately.

**Comment by seladb** [comment]
If your machine has only 1 NIC than I don’t think writing this app is even possible.

You need to have 2 NICs: one one the client side and one on the server side and then your app will exchange packets between them.

Assuming you have 2 NICs, you need to make sure you control the packet processing, otherwise the kernel might get involved and cause some confusion. For example: the kernel can respond to  TCP SYNs in some cases, ARP requests, etc.

You can achieve that by either using ip tables rules or use a kernel bypass framework like DPDK. Please let me know if that makes sense.

**Comment by gerald-dotcom** [comment]
> If your machine has only 1 NIC than I don’t think writing this app is even possible.
> 
> You need to have 2 NICs: one one the client side and one on the server side and then your app will exchange packets between them.
> 
> Assuming you have 2 NICs, you need to make sure you control the packet processing, otherwise the kernel might get involved and cause some confusion. For example: the kernel can respond to TCP SYNs in some cases, ARP requests, etc.
> 
> You can achieve that by either using ip tables rules or use a kernel bypass framework like DPDK. Please let me know if that makes sense.

Yes, vETH and IPTables bypass Kernel processing right now.

But I still need to capture both interfaces. 
 Since you only support 1 interface capture, I  asked you, Would two separate C++ apps that use your Lib could solve this?

**Comment by seladb** [comment]
Maybe, this is something you can check. I haven't tried it so I'm not sure what's the best way to do it.
You should also figure out a way to exchange packets between these two C++ processes. 

As I mentioned many times before, the recommended way to do it via PcapPlusPlus is using DPDK. The [`DpdkBridge`](https://github.com/seladb/PcapPlusPlus/tree/master/Examples/DpdkBridge) example can serve as a great framework for the kind of app you want to build. You said you couldn't get DPDK to work and that maybe your NIC isn't supported by DPDK. In that case I'd consider getting a NIC (or actually 2 NICs) that are supported by DPDK, and there are [many](https://core.dpdk.org/supported/).

Otherwise you can try to implement your idea or add the worker thread concept to the existing PF_RING implementation in PcapPlusPlus.

**Comment by gerald-dotcom** [comment]
DPDK is not portable, involve huge amount of configurations. I will switch to DPDK someday. Closing this issue.
