### ISSUE TITLE
cannot write a packet with a different link layer type

### ISSUE THREAD

**Issue by bug65536** [seladb/PcapPlusPlus#482]
in the examples https://github.com/seladb/PcapPlusPlus/blob/master/Examples/Tutorials/Tutorial-PcapFiles/main.cpp

i want to change the pcap packet link type,

line 29, I changed param 2:

pcpp::PcapFileWriterDevice pcapWriter("output.pcap", pcpp::LINKTYPE_ETHERNET);
==>
pcpp::PcapFileWriterDevice pcapWriter("output.pcap", pcpp::LINKTYPE_PPP);

then it prints :

cannot write a packet with a different link layer type.

if it cannot change the link layer type, the parameter has no use for PcapFileWriterDevice

**Comment by seladb** [comment]
Thanks for reaching out. I have a few questions that might help identifying the issue:

- is this the only change you've made?
- is the error happens during creating the `PcapFileWriterDevice` object or when you're writing packets to it?
- is it possible that you already have a file in this directory by the name of `output.pcap`?

**Comment by bug65536** [comment]
yes,the whole file main.cpp, I just changed param 2 into LINKTYPE_PPP, 
and then complied it and run it.
the error happens at line 64.
there is no output.pcap nor output.pcapng in the current directory.

as a result, there are two files in the current directory:
output.pcap with 0 bytes.
output.pcapng with some KBs.(this file is correctly write)

**Comment by seladb** [comment]
Here is the issue: in this tutorial you're reading packets from `input.pcap` and then write them to `output.pcap`. The link type of `input.pcap` is `pcpp::LINKTYPE_ETHERNET` which means that all the packets read from it have a similar link type. Pcap format doesn't support multiple link types, so you cannot initiate a file with link type of `pcpp::LINKTYPE_PPP` and then write packets that have a different link type. I hope that make sense.

BTW, pcapng does support multiple link types so you can run the same code with `pcpp::PcapNgFileWriterDevice`

**Comment by seladb** [comment]
Please let me know if we can close this issue

**Comment by seladb** [comment]
I'm closing the issue now. Please reopen it if needed
