### ISSUE TITLE
can not parse null/loopback packet

### ISSUE THREAD

**Issue by bug65536** [seladb/PcapPlusPlus#483]
hi, pcpp can not parse null/loopback packet correctly when the head data is 0f 00 08 00,

![1](https://user-images.githubusercontent.com/42331498/86311952-1ee7bd80-bc54-11ea-94df-91fe5921f898.png)

![2](https://user-images.githubusercontent.com/42331498/86312290-f613f800-bc54-11ea-9f69-138045816651.png)

here is my code
[issue.zip](https://github.com/seladb/PcapPlusPlus/files/4861777/issue.zip)

**Comment by seladb** [comment]
thanks for reporting this issue. I'll take a look and get back to you

**Comment by seladb** [comment]
That was indeed a bug. Fixed in https://github.com/seladb/PcapPlusPlus/commit/96fba43565e46496959d1b321163a1696eb49303

Thanks for reporting this issue!
