### ISSUE TITLE
PfRing's latest version doesn't work

### ISSUE THREAD

**Issue by gerald-dotcom** [seladb/PcapPlusPlus#485]
It's official, latest PfRing version doesn't work with PcapPlusPlus.

Tried to compile PfRingExample-FilterTraffic and here is output

**Comment by gerald-dotcom** [comment]
`==> Building target: PfRingExample-FilterTraffic
/usr/bin/ld: Obj/main.o: in function `pcpp::PfRingDevice::getMacAddress()':
/home/unit18/unit18Packets/PcapPlusPlusSource/Dist/header/PfRingDevice.h:116: undefined reference to `pcpp::PfRingDevice::setPfRingDeviceAttributes()'
/usr/bin/ld: Obj/main.o: in function `pcpp::PfRingDevice::getInterfaceIndex()':
/home/unit18/unit18Packets/PcapPlusPlusSource/Dist/header/PfRingDevice.h:122: undefined reference to `pcpp::PfRingDevice::setPfRingDeviceAttributes()'
/usr/bin/ld: Obj/main.o: in function `pcpp::PfRingDevice::getMtu()':
/home/unit18/unit18Packets/PcapPlusPlusSource/Dist/header/PfRingDevice.h:128: undefined reference to `pcpp::PfRingDevice::setPfRingDeviceAttributes()'
/usr/bin/ld: Obj/main.o: in function `listPfRingDevices()':
/home/unit18/unit18Packets/PcapPlusPlusSource/Examples/PfRingExample-FilterTraffic/main.cpp:136: undefined reference to `pcpp::PfRingDevice::getTotalNumOfRxChannels() const'
/usr/bin/ld: Obj/main.o: in function `pcpp::PfRingDevice::getMacAddress()':
/home/unit18/unit18Packets/PcapPlusPlusSource/Dist/header/PfRingDevice.h:116: undefined reference to `pcpp::PfRingDevice::setPfRingDeviceAttributes()'
/usr/bin/ld: Obj/main.o: in function `pcpp::PfRingDeviceList::getInstance()':
/home/unit18/unit18Packets/PcapPlusPlusSource/Dist/header/PfRingDeviceList.h:41: undefined reference to `pcpp::PfRingDeviceList::PfRingDeviceList()'
/usr/bin/ld: /home/unit18/unit18Packets/PcapPlusPlusSource/Dist/header/PfRingDeviceList.h:41: undefined reference to `pcpp::PfRingDeviceList::~PfRingDeviceList()'
/usr/bin/ld: Obj/main.o: in function `packetArrived(pcpp::RawPacket*, unsigned int, unsigned char, pcpp::PfRingDevice*, void*)':
/home/unit18/unit18Packets/PcapPlusPlusSource/Examples/PfRingExample-FilterTraffic/main.cpp:198: undefined reference to `pcpp::PfRingDevice::sendPacket(pcpp::Packet const&)'
/usr/bin/ld: Obj/main.o: in function `pcpp::PfRingDeviceList::getInstance()':
/home/unit18/unit18Packets/PcapPlusPlusSource/Dist/header/PfRingDeviceList.h:41: undefined reference to `pcpp::PfRingDeviceList::PfRingDeviceList()'
/usr/bin/ld: /home/unit18/unit18Packets/PcapPlusPlusSource/Dist/header/PfRingDeviceList.h:41: undefined reference to `pcpp::PfRingDeviceList::~PfRingDeviceList()'
/usr/bin/ld: Obj/main.o: in function `main':
/home/unit18/unit18Packets/PcapPlusPlusSource/Examples/PfRingExample-FilterTraffic/main.cpp:264: undefined reference to `pcpp::PfRingDeviceList::getPfRingDeviceByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const'
/usr/bin/ld: /home/unit18/unit18Packets/PcapPlusPlusSource/Examples/PfRingExample-FilterTraffic/main.cpp:256: undefined reference to `pcpp::PfRingDeviceList::getPfRingDeviceByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const'
/usr/bin/ld: /home/unit18/unit18Packets/PcapPlusPlusSource/Examples/PfRingExample-FilterTraffic/main.cpp:364: undefined reference to `pcpp::PfRingDevice::openMultiRxChannels(unsigned char, pcpp::PfRingDevice::ChannelDistribution)'
/usr/bin/ld: /home/unit18/unit18Packets/PcapPlusPlusSource/Examples/PfRingExample-FilterTraffic/main.cpp:385: undefined reference to `pcpp::PfRingDevice::getCurrentCoreId() const'
/usr/bin/ld: /home/unit18/unit18Packets/PcapPlusPlusSource/Examples/PfRingExample-FilterTraffic/main.cpp:439: undefined reference to `pcpp::PfRingDevice::startCaptureMultiThread(void (*)(pcpp::RawPacket*, unsigned int, unsigned char, pcpp::PfRingDevice*, void*), void*, unsigned int)'
/usr/bin/ld: /home/unit18/unit18Packets/PcapPlusPlusSource/Examples/PfRingExample-FilterTraffic/main.cpp:454: undefined reference to `pcpp::PfRingDevice::stopCapture()'
collect2: error: ld returned 1 exit status
make: *** [Makefile:37: PfRingTrafficFilter] Error 1`

**Comment by gerald-dotcom** [comment]
I did try with older PFRing version but it simply doesn't compile due to Kernel incompatibility.

What I'm going to do is downgrading Ubuntu from 20 to 16.04 

Sadly, that's the only option I see.

**Comment by gerald-dotcom** [comment]
Ubuntu downgrade made it work.  Everything complies successfully.

**Comment by seladb** [comment]
I just tried the latest PF_RING release [7.6.0](https://github.com/ntop/PF_RING/releases/tag/7.6.0) on Ubuntu 20.04 with the latest version of PcapPlusPlus from `master` and was able to build everything including `PfRingExample-FilterTraffic`

**Comment by gerald-dotcom** [comment]
@seladb I'm not sure why it doesn't compile on my side then but anyways I will stick to Ubuntu 16. Closing for now!
