### ISSUE TITLE
Build fails when g++-10 is used as compiler

### ISSUE THREAD

**Issue by mustafakemalgilor** [seladb/PcapPlusPlus#486]
Build is failing while Pcap++Test is being compiled.

Steps to reproduce:

In project root:

1-) bash configure-linux.sh

```
****************************************
PcapPlusPlus Linux configuration script 
****************************************

Number of arguments: 0

Compile PcapPlusPlus with PF_RING? n
Compile PcapPlusPlus with DPDK? n
```

2-) make -j12 -B CC=/usr/bin/gcc-10 CXX=/usr/bin/g++-10

Output:

```
make[1]: Leaving directory '/home/mustafa/workspace/scratchpad/PcapPlusPlus/Tests/Packet++Test'
make[1]: Entering directory '/home/mustafa/workspace/scratchpad/PcapPlusPlus/Tests/Pcap++Test'
==== Building target: Pcap++Test ====
Building file: Common/TestUtils.cpp
Building file: main.cpp
Building file: Tests/DpdkTests.cpp
Building file: Tests/FileTests.cpp
Building file: Tests/FilterTests.cpp
Building file: Tests/IPFragmentationTests.cpp
Building file: Tests/IpMacTests.cpp
Building file: Tests/KniTests.cpp
Building file: Tests/LiveDeviceTests.cpp
Building file: Tests/PacketParsingTests.cpp
Building file: Tests/PfRingTests.cpp
Building file: Tests/RawSocketTests.cpp
Building file: Tests/TcpReassemblyTests.cpp
make[2]: Entering directory '/home/mustafa/workspace/scratchpad/PcapPlusPlus/3rdParty/MemPlumber'
Building MemPlumber file: /home/mustafa/workspace/scratchpad/PcapPlusPlus/3rdParty/MemPlumber/MemPlumber/memplumber.cpp
make[2]: Leaving directory '/home/mustafa/workspace/scratchpad/PcapPlusPlus/3rdParty/MemPlumber'
/usr/bin/ld: Obj/Tests/FilterTests.o: in function `TestPcapFiltersOffline(int&, bool, bool)':
/home/mustafa/workspace/scratchpad/PcapPlusPlus/Tests/Pcap++Test/Tests/FilterTests.cpp:300: undefined reference to `pcpp::IDevice::open()'
/usr/bin/ld: /home/mustafa/workspace/scratchpad/PcapPlusPlus/Tests/Pcap++Test/Tests/FilterTests.cpp:324: undefined reference to `pcpp::IDevice::open()'
/usr/bin/ld: /home/mustafa/workspace/scratchpad/PcapPlusPlus/Tests/Pcap++Test/Tests/FilterTests.cpp:346: undefined reference to `pcpp::IDevice::open()'
/usr/bin/ld: /home/mustafa/workspace/scratchpad/PcapPlusPlus/Tests/Pcap++Test/Tests/FilterTests.cpp:368: undefined reference to `pcpp::IDevice::open()'
/usr/bin/ld: /home/mustafa/workspace/scratchpad/PcapPlusPlus/Tests/Pcap++Test/Tests/FilterTests.cpp:392: undefined reference to `pcpp::IDevice::open()'
/usr/bin/ld: Obj/Tests/FilterTests.o:/home/mustafa/workspace/scratchpad/PcapPlusPlus/Tests/Pcap++Test/Tests/FilterTests.cpp:416: more undefined references to `pcpp::IDevice::open()' follow
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:82: Pcap++Test] Error 1
make[1]: Leaving directory '/home/mustafa/workspace/scratchpad/PcapPlusPlus/Tests/Pcap++Test'
make: *** [Makefile:39: all] Error 2

```

**Comment by seladb** [comment]
I'm not sure why it gives you this error. I build `Pcap++Test` all the time and it works just fine...

**Comment by mustafakemalgilor** [comment]
> I'm not sure why it gives you this error. I build `Pcap++Test` all the time and it works just fine...

I am able to build with g++-9 without any problems. I am using g++ version 10.1.0 as compiler.

In my scenario, I am using the pcapplusplus conan package provided by the bincrafters. As a workaround, I had to override the MAKEFLAGS in order to suppress the compilation error produced by the Pcap++Test target.

```
conan_cmake_run(
    REQUIRES pcapplusplus/19.12@bincrafters/stable
    BASIC_SETUP CMAKE_TARGETS
    # Compile with -O3g 
    BUILD_TYPE "RelWithDebInfo"
    BUILD missing
    # Use GCC 10 for compilations
    SETTINGS compiler.version=10
    # Explicitly specify gcc-10, since /usr/bin/gcc & /usr/bin/g++ defaults to gcc-9.
    ENV CC=/usr/bin/gcc-10
    ENV CXX=/usr/bin/g++-10
    ENV MAKEFLAGS="-e -k -i --debug -W Pcap++Test -o Pcap++Test  -j32"
    # Do not write anything about build status to stdout
    # OUTPUT_QUIET
)

```

**Comment by gerald-dotcom** [comment]
> conan

This one wasted 4 hours of time. You better off using source from Git directly.

**Comment by mustafakemalgilor** [comment]
> > conan
> 
> This one wasted 4 hours of time. You better off using source from Git directly.

I've tried building source from git as well, it fails to build too. (with g++/v10.1.0)

**Comment by seladb** [comment]
I don't think I've ever tested PcapPlusPlus with g++/v10. As you mentioned, it does work with g++/v9 or less.

Let me try and get back to you.

**Comment by seladb** [comment]
I've just tried building PcapPlusPlus from source using g++/v10 on Ubuntu 20.04 and it works just fine.

I've tried both the latest from `master` as well as the 19.12 release.

I've used the exact same scenario you described in the beginning of the issue... could it be something with your specific setup?

**Comment by mustafakemalgilor** [comment]
> I've just tried building PcapPlusPlus from source using g++/v10 on Ubuntu 20.04 and it works just fine.
> 
> I've tried both the latest from `master` as well as the 19.12 release.
> 
> I've used the exact same scenario you described in the beginning of the issue... could it be something with your specific setup?

Yeah, I've successfully compiled with version 10.0.0 as well. I think the problem is specific to 10.1.0 release (btw I'm using Debian Sid).

I'm convinced that it is a bug in GCC. Behavior of the compiler should not change between minor software releases. If so, it is considered a bug.

Closing the issue, thanks!

**Comment by seladb** [comment]
Thanks! BTW, I've compiled it with 10.1.0 on Ubuntu 20.04 and it worked just fine...

**Comment by mustafakemalgilor** [comment]
Thanks for the info. My best guess is Debian release of the gcc is broken
right now (or it might be a linker bug too).
