### ISSUE TITLE
pfring_recv returned an error: [Err=-1]

### ISSUE THREAD

**Issue by gerald-dotcom** [seladb/PcapPlusPlus#488]
**Issue ---** 

Running resulted complied code that capture packets thru Pf_Ring causes an error

_Error Output_

```
pfring_recv returned an error: [Err=-1]
pfring_recv returned an error: [Err=-1]
pfring_recv returned an error: [Err=-1]
pfring_recv returned an error: [Err=-1]
pfring_recv returned an error: [Err=-1]
pfring_recv returned an error: [Err=-1]
....... More 
Segmentation fault (core dumped)
```

**My environment --** 

```
Ubuntu 16.04.12
Pf_Ring 6.4.1
GCC 5.4.0
```

**Here how I loaded pfRing's Kernel Module --** 

`sudo insmod pf_ring.ko min_num_slots=65536 enable_tx_capture=1 enable_ip_defrag=1
`

Of course, I was able to run your PfRing's example and print stats but mine isn't working, here is the code,

**main.cpp ---**

```
#include <iostream>
#include <string>
#include <array>
#include <vector>
#include <map>
#include <chrono>
#include <time.h>
#include <cstdint>
#include <sstream>
#include <iomanip>
#include <stdexcept>
#include <PfRingDevice.h>
#include <PfRingDeviceList.h>
#include <Packet.h>
#include <EthLayer.h>
#include <IPv4Layer.h>
#include <PacketUtils.h>
#include <IPv6Layer.h>
#include <TcpLayer.h>
#include <SSLLayer.h>
#include "dataObjects.h"
#include <PcapPlusPlusVersion.h>

using namespace pcpp;

void packetArrived(RawPacket* packets, std::uint32_t numOfPackets, std::uint8_t threadId, PfRingDevice* device, void* userCookie) {
    for (uint32_t i = 0; i < numOfPackets; i++) { 
        std::cout << "A packet arrived" << "\n";
        continue;
    }
}

int main(){
    PfRingDevice *device = NULL;
    PfRingDevice *sendPacketsToIface = NULL;

    // Get Default Interface Name using Shell
    std::string defaultInterface;
    execute("sudo ip r | awk '/^default/ {print $5}'", defaultInterface);

    // Get Instance of Default Interface
    device = pcpp::PfRingDeviceList::getInstance().getPfRingDeviceByName(defaultInterface.c_str());

    if (device == NULL)
    {
        std::cout << "Couldn't locate default Network Driver"
                  << "\n";
        return 1;
    }

    int systemCores = pcpp::getNumOfCores();
    int numOfCaptureThreads = systemCores-1;


    pcpp::CoreMask cores = 0;

    int threadId = 0;
    int threadCount = 0;

    while (threadCount < numOfCaptureThreads)
	{
		if (SystemCores::IdToSystemCore[threadId].Id != device->getCurrentCoreId().Id)
		{
			cores |= SystemCores::IdToSystemCore[0].Mask;
			threadCount++;
		}

		threadId++;
	}


    if (!device->openMultiRxChannels(numOfCaptureThreads, PfRingDevice::PerFlow)) {
        std::cout << "Couldn't open RX Channels"
                  << "\n";
        return 1;
    }

    // Create a flow table for each core
	std::map<std::uint32_t, bool> flowTables[1];

    // Initialize Data Object

    packetFingerprint dObj;

    // Initialize flow tables on Fingerprint Object

    dObj.flowTables = flowTables;

    // Start Packet Capturing

    std::cout << "Started Packet Capturing"
              << "\n";


    if(!device->startCaptureMultiThread(packetArrived, &dObj, cores)) {
        std::cout << "Unable To Start Packet Capturing" << "\n";
    }

}
```

**Makefile ---**

```
include /home/cornelius/PcapPlusPlusSource/mk/platform.mk
include /home/cornelius/PcapPlusPlusSource/mk/PcapPlusPlus.mk


# All Target
all:
	g++ -std=c++11 $(PCAPPP_INCLUDES) -c -o main.o main.cpp
	g++ -DUSE_PF_RING $(PCAPPP_LIBS_DIR) -o packetObserver main.o $(PCAPPP_LIBS)

# Clean Target
clean:
	rm main.o
	rm packetObserver

```

**Comment by seladb** [comment]
The code looks fine so I'm not sure why you're getting this error.

You can start from running 1 thread and see if that works.

**Comment by gerald-dotcom** [comment]
@seladb  The code already running in 1 thread because the machine has only 2 cores and as  I verified, it start with 1 thread/1 core.

**Comment by gerald-dotcom** [comment]
Does this works on your side?

**Comment by seladb** [comment]
I'll try to run the exact same code and get back to you

**Comment by seladb** [comment]
I debugged your code and found the issue: 

since you're doing the packet capture on another thread you need to make sure that the main thread (where `main()` runs) stays "alive". 

I added the following lines to the end of your `main()` method and things started working:

```cpp
while(true)
{
  sleep(1);
}
```

**Comment by gerald-dotcom** [comment]
I had that originally with termination thing, but it doesn't printed anything out. I will re-try. I also curious about it's propose, and yes I encountered similar stuff in other library but it had milliseconds instead seconds. I thought it add bottleneck but never thought about threads. 
 
`    // Termination Logic

    ///bool shouldStop = false;


    // // Register the on app close event to print summary stats on app termination
	// ApplicationEventHandler::getInstance().onApplicationInterrupted(onApplicationInterrupted, &shouldStop);

	// // Infinite loop (until program is terminated)
    // // Bottleneck
	// while (!shouldStop)
	// {
	// 	sleep(1);
	// }

	// // Stop capturing packets, close the device
	// device->stopCapture();
	// device->close();
`

**Comment by gerald-dotcom** [comment]
Indeed, re-adding that one made it work to print the **"A packet arrived"** message; however, I discovered few more issues when doing real world capturing beyond a message. 

My real world code looks like this,


main.cpp  ---

```
#include <iostream>
#include <string>
#include <array>
#include <vector>
#include <map>
#include <chrono>
#include <time.h>
#include <cstdint>
#include <sstream>
#include <iomanip>
#include <stdexcept>
#include <PfRingDevice.h>
#include <PfRingDeviceList.h>
#include <Packet.h>
#include <EthLayer.h>
#include <IPv4Layer.h>
#include <PacketUtils.h>
#include <IPv6Layer.h>
#include <TcpLayer.h>
#include <SSLLayer.h>
#include "dataObjects.h"
#include <PcapPlusPlusVersion.h>

using namespace pcpp;

void packetArrived(RawPacket* packets, std::uint32_t numOfPackets, std::uint8_t threadId, PfRingDevice* device, void* userCookie) {
    for (unsigned int i = 0; i < numOfPackets; i++) { 

        packetFingerprint *dObj = (packetFingerprint*)userCookie;

        // Get Current Packet
        pcpp::Packet packet(&packets[i]);
        // Parse Current Packet
        pcpp::Packet parsedPacket(packet);

        bool packetMatched = false;

        /// hash the packet by 5-tuple and look in the flow table to see whether this packet belongs to an existing or new flow
		std::uint32_t hash = hash5Tuple(&packet);
		std::map<std::uint32_t, bool>::const_iterator iter = dObj->flowTables[threadId].find(hash);

        // if packet belongs to an already existing flow
		if (iter !=dObj->flowTables[threadId].end() && iter->second)
		{
            std::cout << "A packet belongs to an already existing flow is matched" << "\n";
			packetMatched = true;
            continue;
		}

        packetMatched  = true;

        // Put new flow in flow table
		dObj->flowTables[threadId][hash] = true;

        // If not matched, loop again.

        if(!packetMatched) { continue; }; 

        // Start more parsing
        /// Bla Bla
        // Right now, nothing get this far, all appear to be existing flow ;(
    }
}

int main(){

    std::string defaultInterface = "eth0";

    // Get Instance of Interface
    auto device = pcpp::PfRingDeviceList::getInstance().getPfRingDeviceByName(defaultInterface.c_str());

    if (device == NULL)
    {
        std::cout << "Couldn't locate default Network Driver"
                  << "\n";
        return 1;
    }

    int systemCores = pcpp::getNumOfCores(); // This will usually 2 
    int numOfCaptureThreads = systemCores-1; // This will set 2-1 = 1 


    pcpp::CoreMask cores = 0;

    int threadId = 0;
    int threadCount = 0;

    while (threadCount < numOfCaptureThreads)
	{
		if (SystemCores::IdToSystemCore[threadId].Id != device->getCurrentCoreId().Id)
		{
			cores |= SystemCores::IdToSystemCore[0].Mask;
			threadCount++;
		}

		threadId++;
	}


    if (!device->openMultiRxChannels(numOfCaptureThreads, PfRingDevice::PerFlow)) {
        std::cout << "Couldn't open RX Channels"
                  << "\n";
        return 1;
    }

    // Create a flow table for each core

    // I'm unsure why we are creating flow tables for 2 System Cores when caputreThreads set to 1 ???
	std::map<std::uint32_t, bool> flowTables[systemCores];

    // Initialize Data Object

    packetFingerprint dObj;

    // Initialize flow tables on Fingerprint Object

    dObj.flowTables = flowTables;

    // Start Packet Capturing

    std::cout << "Started Packet Capturing"
              << "\n";


    if(!device->startCaptureMultiThread(packetArrived, &dObj, cores)) {
        std::cout << "Unable To Start Packet Capturing" << "\n";
    }

}

```

dataObjects.h ---


```
#include <iostream>
#include <array>
#include <vector>
#include <cstdint>
#include <map>

struct packetFingerprint{
    std::map<std::uint32_t, bool>* flowTables; /* Flow Tables manage threads */

    packetFingerprint() : flowTables(NULL) {}
};
```


VS Code says for line 433, **"expression must have a constant value -- the value of variable \"systemCores\" (declared at line 412) cannot be used as a constant"**, the exact code block the VSCode complaining can be found below, 

```
// Create a flow table for each core
// I'm unsure why we are creating flow tables for 2 System Cores when captureThreads set to 1 ???
std::map<std::uint32_t, bool> flowTables[systemCores];
```

However, the code can compile without any error. Now when I run the code, the packet capture starts but it identify all flows as existing flows thus can't do any further parsing. 

I'm unable to get the code to identify flows as new. Yes, I followed your code example exclusively but flow control phase of your flow table is hard to read.

I know you doing packet matching and actual parsing in a separate structure/class but my style is to do all inline except the flow tables, and data storage.

**Comment by seladb** [comment]
I think you have an issue here:

```cpp
    // Get Current Packet
==> pcpp::Packet packet(&packets[i]);
    // Parse Current Packet
    pcpp::Packet parsedPacket(packet);
```

The line marked in `==>` should be `pcpp::RawPacket` and not `pcpp::Packet`.

`RawPacket` is a wrapper class for the packet raw bytes.
`Packet` is a class for a parsed packet.

What you get in the `packetArrived` callback is an array of raw packets and you can decide whether to parse them or not.

**Comment by gerald-dotcom** [comment]
But your code say something else.....

 */
void packetArrived(RawPacket* packets, uint32_t numOfPackets, uint8_t threadId, PfRingDevice* device, void* userCookie)
{
	CaptureThreadArgs* args = (CaptureThreadArgs*)userCookie;
	for (uint32_t i = 0; i < numOfPackets; i++)
	{
		// parse packet
		Packet packet(&packets[i]);

**Comment by gerald-dotcom** [comment]
Do you have any comments regarding that VSCode error? 

Also, I have put a question in code block, "I'm unsure why we are creating flow tables for 2 System Cores when captureThreads set to 1 ???"

**Comment by gerald-dotcom** [comment]
> I think you have an issue here:
> 
> ```c++
>     // Get Current Packet
> ==> pcpp::Packet packet(&packets[i]);
>     // Parse Current Packet
>     pcpp::Packet parsedPacket(packet);
> ```
> 
> The line marked in `==>` should be `pcpp::RawPacket` and not `pcpp::Packet`.
> 
> `RawPacket` is a wrapper class for the packet raw bytes.
> `Packet` is a class for a parsed packet.
> 
> What you get in the `packetArrived` callback is an array of raw packets and you can decide whether to parse them or not.

hash5Tuple() only accept param type of packet not RawPacket type

Yeah, I know i made a mistake by repeating multiple parsed packets. So I removed "pcpp::Packet packet(&packets[i]);" and replaced with "pcpp::Packet parsedPacket(&packets[i]);"


However, it still don't work. All packets are identified as existing.

Here is updated code,

```
void packetArrived(RawPacket* packets, std::uint32_t numOfPackets, std::uint8_t threadId, PfRingDevice* device, void* userCookie) {
    for (unsigned int i = 0; i < numOfPackets; i++) { 

        packetFingerprint *dObj = (packetFingerprint*)userCookie;

        // Parse Current Packet
        pcpp::Packet parsedPacket(&packets[i]);

        bool packetMatched = false;

        /// hash the packet by 5-tuple and look in the flow table to see whether this packet belongs to an existing or new flow
		std::uint32_t hash = hash5Tuple(&parsedPacket);
		std::map<std::uint32_t, bool>::const_iterator iter = dObj->flowTables[threadId].find(hash);

        // if packet belongs to an already existing flow
		if (iter !=dObj->flowTables[threadId].end() && iter->second)
		{
            std::cout << "A packet belongs to an already existing flow is matched" << "\n";
			packetMatched = true;
            continue;
		}

        packetMatched  = true;

        // Put new flow in flow table
		dObj->flowTables[threadId][hash] = true;

        // If not matched, loop again.

        if(!packetMatched) { continue; }; 

        // Start more parsing
        /// Bla Bla
        // Right now, nothing get this far, all appear to be existing flow ;(
    }
}
```

**Comment by seladb** [comment]
Did you make sure you really get UDP/TCP packets from different flows?

I suspect your app somehow gets only packets from 1 or few flows. You can add a print to show which packets it’s getting and make sure they’re from different flows.

**Comment by gerald-dotcom** [comment]
> Did you make sure you really get UDP/TCP packets from different flows?
> 
> I suspect your app somehow gets only packets from 1 or few flows. You can add a print to show which packets it’s getting and make sure they’re from different flows.

I don't understand the whole flow thing, just followed your code example.

The thing run open 1 thread and that's it.

**Comment by gerald-dotcom** [comment]
Because it only has 2 processors, your code examples  substract -1 from actual processors, therefore, it use only 1 processor and 1 thread.

 

That's why I asked you I'm unsure why we are creating flow tables for 2 System Cores when captureThreads set to 1 ???

**Comment by gerald-dotcom** [comment]
The flow tables initialization `map<uint32_t, bool> flowTables[totalNumOfCores]; `use the value of `totalNumOfCores `which is 2 for my machine.


```
	int totalNumOfCores = getNumOfCores(); // Yields 2 
	int numOfCaptureThreads = totalNumOfCores-1; // This Yields 1 because 2-1
```


The core mask value also is 1 because the way you get core mask value is, 

`int threadId = 0;`
`while (threadCount < numOfCaptureThreads)`

**Comment by seladb** [comment]
If you have only 1 processing thread you don't have to create a flow table for 2 system cores. One should be sufficient. 
The reason I'm creating flow table per thread is because it's hard to predict which system cores will be used by the application. Let me give you an example:

Let's say your machine has 8 cores. One is used for control and the other 7 can be used for packet processing. However the person who is running the app decided to use only two cores (maybe cores 3 and 4), and leave the rest 5 cores for other purposes. In that case there will be 2 processing threads on cores 3 and 4 which will use the flow tables on index 3 and 4. But then the same person can decide to stop the app and re-run it on other cores. For the same reason it's also hard to predict which core will be the master (control) core, I didn't want to assume it's always core 0.
To support this use case I decided to create flow tables per number of cores, although not all of them will be used.

But as I said, if your app only uses 1 thread/core, you don't need all of this.

**Comment by gerald-dotcom** [comment]
> If you have only 1 processing thread you don't have to create a flow table for 2 system cores. One should be sufficient.
> The reason I'm creating flow table per thread is because it's hard to predict which system cores will be used by the application. Let me give you an example:
> 
> Let's say your machine has 8 cores. One is used for control and the other 7 can be used for packet processing. However the person who is running the app decided to use only two cores (maybe cores 3 and 4), and leave the rest 5 cores for other purposes. In that case there will be 2 processing threads on cores 3 and 4 which will use the flow tables on index 3 and 4. But then the same person can decide to stop the app and re-run it on other cores. For the same reason it's also hard to predict which core will be the master (control) core, I didn't want to assume it's always core 0.
> To support this use case I decided to create flow tables per number of cores, although not all of them will be used.
> 
> But as I said, if your app only uses 1 thread/core, you don't need all of this.

Alright that clear up everything. One thing still brother me is that Intellisense error. 

"expression must have a constant value -- the value of variable "systemCores" (declared at line 412) cannot be used as a constant"

Do you have any thoughts on this one?

**Comment by seladb** [comment]
I think that warning is probably because `systemCores` is not a const variable and we're trying to use it for statically allocating an array.

**Comment by gerald-dotcom** [comment]
> I think that warning is probably because `systemCores` is not a const variable and we're trying to use it for statically allocating an array.

Is it safe to ignore this error?

If not, what should i do?

I used exact same code as yours.

**Comment by seladb** [comment]
Yes, I think it's safe to ignore this warning

**Comment by gerald-dotcom** [comment]
Closing out then
