### ISSUE TITLE
TcpOptionBuilder corrupt the values

### ISSUE THREAD

**Issue by gerald-dotcom** [seladb/PcapPlusPlus#492]
I added a TCP option with unsigned int (32 bit) type value and then retrieved value from parsed packet, I see the option is added but the value is completely different even tho the length is same.  

I've tried htons too but that caused the value to appear as 0

**Comment by seladb** [comment]
Can you please post your code?

**Comment by gerald-dotcom** [comment]
Closing out, not worth time ;)
