### ISSUE TITLE
bool GeneralFilter::matchPacketWithFilter(RawPacket* rawPacket) hardcoded linkLayerType

### ISSUE THREAD

**Issue by skorup101** [seladb/PcapPlusPlus#498]
if (pcap_compile_nopcap(9000, **pcpp::LINKTYPE_ETHERNET**, m_program, filterStr.c_str(), 1, 0) < 0)
Is there a reason to use **pcpp::LINKTYPE_ETHERNET** here? I suggest using **rawPacket.getLinkLayerType()** instead.

Atm it's impossible to successfully match packets if they were previously captured with "any" device (in my case its linkLayerType for such capture device is LINKTYPE_LINUX_SLL=113).

I can create pull req after I test if it works well.

**Comment by seladb** [comment]
yes, that's a good point. I agree with you regarding the need to test other link types, but if they work I'm totally up for this change

**Comment by seladb** [comment]
PR merged, thanks for your contribution!
