### ISSUE TITLE
How to access IPv6's extension's data?

### ISSUE THREAD

**Issue by gerald-dotcom** [seladb/PcapPlusPlus#500]
So, I need to access IPv6's extension's data but can't find a way.

Here what I did,

```
            if (ip6Layer->isFragment())
            {
                ip6Layer->getExtensionOfType(pcpp::IPv6Extension::IPv6ExtensionType::IPv6Fragmentation);
            } 
```

I'm getting an error on VS Code and it says,

`no instance of function template "pcpp::IPv6Layer::getExtensionOfType" matches the argument list -- argument types are: (pcpp::IPv6Extension::IPv6ExtensionType) -- object type is: pcpp::IPv6Layer`

**Comment by seladb** [comment]
The way you should find the frag extension is: `ip6Layer->getExtensionOfType<pcpp::IPv6FragmentationHeader>()`.

Please take a look here: 

https://github.com/seladb/PcapPlusPlus/blob/6a78b5da5b5dbc31c4ccc0ff74513580a149c71e/Tests/Packet%2B%2BTest/Tests/IPv6Tests.cpp#L85
