### ISSUE TITLE
Do I have to use nthos with getValueAs?

### ISSUE THREAD

**Issue by gerald-dotcom** [seladb/PcapPlusPlus#501]
When I want to get the value of TCP option, I use,

`TCPLayer->getTcpOption(pcpp::TcpOptionType::TCPOPT_MSS).getValueAs<int>()`

Now, I'm puzzling around whether I have to use nthos or not.

**Comment by seladb** [comment]
Yes, you should use `htons`/`ntohs`, please take a look here:

https://github.com/seladb/PcapPlusPlus/blob/6a78b5da5b5dbc31c4ccc0ff74513580a149c71e/Tests/Packet%2B%2BTest/Tests/TcpTests.cpp#L104

**Comment by seladb** [comment]
@gerald-dotcom since you're moving to libtins, should we close the other open issues as well?

**Comment by gerald-dotcom** [comment]
Yes you can
________________________________
