### ISSUE TITLE
TCP Option's value being sent but when I read, it become 0

### ISSUE THREAD

**Issue by gerald-dotcom** [seladb/PcapPlusPlus#502]
I'm trying to capture TCP MSS value and confirmed with Wireshark that my computer sent non-zero value but when I run the following, it outputs zero instead:

    std::cout << TCPLayer->getTcpOption(pcpp::TcpOptionType::TCPOPT_MSS).getValueAs<std::uint16_t>() << "\n";

Do you think this as bug?

**Comment by seladb** [comment]
It's hard to say without a context. I'm not aware of any bug there. Can you post the code you're running and a tcpdump/Wireshark capture showing the value is non-zero?

**Comment by gerald-dotcom** [comment]
Too late. You can close. I switched to libtins :(


________________________________
