### ISSUE TITLE
vs2019 link error

### ISSUE THREAD

**Issue by babyaaaaaa** [seladb/PcapPlusPlus#503]
>Pcap++.lib(PcapLiveDeviceList.obj) : error LNK2001: unresolved external symbol __imp__GetNetworkParams@8
1>Pcap++.lib(PcapLiveDevice.obj) : error LNK2001: unresolved external symbol __imp__GetAdaptersInfo@8

**Comment by seladb** [comment]
Can you provide a little more context on what you're trying to do?

As you can see in the [CI logs](https://ci.appveyor.com/project/seladb/pcapplusplus/branch/master/job/46w4td4xvmc2kgl5) PcapPlusPlus is working fine on VS2019

**Comment by babyaaaaaa** [comment]
before project add this and it can build, thanks
#include <Winsock2.h>
#pragma comment(lib, "ws2_32.lib")
#include <Iphlpapi.h>
#pragma comment(lib, "Iphlpapi.lib")

> Can you provide a little more context on what you're trying to do?
> 
> As you can see in the [CI logs](https://ci.appveyor.com/project/seladb/pcapplusplus/branch/master/job/46w4td4xvmc2kgl5) PcapPlusPlus is working fine on VS2019

before project add this and it can build, thanks
#include <Winsock2.h>
#pragma comment(lib, "ws2_32.lib")
#include <Iphlpapi.h>
#pragma comment(lib, "Iphlpapi.lib")

**Comment by seladb** [comment]
I'm not sure what you mean. Please provide more context

**Comment by babyaaaaaa** [comment]
> I'm not sure what you mean. Please provide more context

in my project add those head it well

**Comment by seladb** [comment]
please let me know if we can close this issue

**Comment by babyaaaaaa** [comment]
yes，it works well，thanks



---Original---

**Comment by athola** [comment]
I wanted to add one thing for anyone coming across this, instead of adding the `pragma` to the header, you can link `iphlpapi` in the compiler/CMake
