### ISSUE TITLE
getPcapLiveDeviceByIp result is null

### ISSUE THREAD

**Issue by babyaaaaaa** [seladb/PcapPlusPlus#504]
this is part of the example, the ip is right, but can't get the dev, the result is dev null, and getPcapLiveDevicesList size is 0,  i use win10 vs2019 

int main(int argc, char* argv[])
{	
	std::string interfaceIPAddr = "192.168.0.100";

	pcpp::PcapLiveDevice* dev = pcpp::PcapLiveDeviceList::getInstance().getPcapLiveDeviceByIp(interfaceIPAddr.c_str());
	if (dev == NULL)
	{
		auto v = pcpp::PcapLiveDeviceList::getInstance().getPcapLiveDevicesList();
		std::cout << v.size() << "-------------" << std::endl;                             // here i get 0
		
		printf("Cannot find interface with IPv4 address of '%s'\n", interfaceIPAddr.c_str());
		exit(1);
	}
}

**Comment by seladb** [comment]
It looks like WinPcap can't find interfaces in your machine. Do you see these interfaces in Wireshark?

**Comment by babyaaaaaa** [comment]
> It looks like WinPcap can't find interfaces in your machine. Do you see these interfaces in Wireshark?

yes, in wireshark  can get interfaces,  but i just test  pcap_findalldevs it also can't get any interface

**Comment by babyaaaaaa** [comment]
i do some test, found that winpcap's pcap_findalldevs  is return success but the dev is null,  then i download a npcap and uninstall winpcap, use the npcap it work well

**Comment by seladb** [comment]
might be some issue with your system. I'm running WinPcap and it works fine

**Comment by seladb** [comment]
I'm closing this issue now, please reopen it if needed
