### ISSUE TITLE
ArpSpoofing Disconnect attacker too!

### ISSUE THREAD

**Issue by Shadow4walker** [seladb/PcapPlusPlus#505]
using the ArpSpoofing example should only disconnect the victim from internet is that right? but instead it's block me too from the internet!
is there a walkaround for this so that i can block some ip and still got the internet working for me?

**Comment by seladb** [comment]
it should disconnect the victim only, not you. Maybe it's something with your network configuration?

**Comment by Shadow4walker** [comment]
> it should disconnect the victim only, not you. Maybe it's something with your network configuration?

Nope there's nothing wrong with my network configuration! also I'm facing same issue with Sharppcap too!!

**Comment by seladb** [comment]
Let me check and get back to you

**Comment by seladb** [comment]
Ok, I tried but couldn't reproduce this issue. Can you provide more details about your network configuration and the machines being the attacker/victim/gateway?

**Comment by Shadow4walker** [comment]
I've tested today and it's working properly so i think it's an issue from my side after all! Sorry :/
is there a way to inspect the target "bandwidth usage" without Cutting it from the internet, like converting my pc to a router so that i can route all traffic through it?

**Comment by seladb** [comment]
Thanks for looking into it.

To your question: yes, there are ways to convert your (Linux) machine into a router. You can google and you'll find many guides. Here are a few I found from a very brief search (haven't tried them though):
https://linuxtechlab.com/turning-centosrhel-6-7-machine-router/
https://www.tecmint.com/setup-linux-as-router/

Please let me know if we can close this issue.

**Comment by Shadow4walker** [comment]
> Thanks for looking into it.
> 
> To your question: yes, there are ways to convert your (Linux) machine into a router. You can google and you'll find many guides. Here are a few I found from a very brief search (haven't tried them though):
> https://linuxtechlab.com/turning-centosrhel-6-7-machine-router/
> https://www.tecmint.com/setup-linux-as-router/
> 
> Please let me know if we can close this issue.

Thank You
