### ISSUE TITLE
IgmpLayer assigns "prevLayer" as NULL although it is  ipv4Layer

### ISSUE THREAD

**Issue by OrkunTokdemir** [seladb/PcapPlusPlus#507]
IgmpLayer does not assign what it get from Ipv4Layer's "parseNextLayer" function.

![image](https://user-images.githubusercontent.com/21346859/87921445-3fe94480-ca83-11ea-9b31-52e4891ad671.png)

![image](https://user-images.githubusercontent.com/21346859/87921274-0284b700-ca83-11ea-8e1e-d563d07e0e0e.png)

**Comment by seladb** [comment]
Thanks for reporting this issue! Indeed it looks like a bug. Would you consider fixing it and create a PR?

**Comment by OrkunTokdemir** [comment]
okay I will send pull request :)

**Comment by seladb** [comment]
Thank you for your contribution! You PR was merged to `master`
