### ISSUE TITLE
bug: SSLHandshake will loop forever

### ISSUE THREAD

**Issue by bug65536** [seladb/PcapPlusPlus#512]
hi, there is a bug in
[https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/src/SSLHandshake.cpp](url)

line 1195:
`
              
           while ((curPos - extensionPos) < (int)extensionLength 
		&& (curPos - m_Data) < (int)messageLen 
		&& (int)messageLen - (curPos - m_Data) >= (int)minSSLExtentionLen)
	{
		SSLExtension* newExt = NULL;
		uint16_t sslExtType = be16toh(*(uint16_t*)curPos);
		if (sslExtType == SSL_EXT_SERVER_NAME)
		{
			newExt = new SSLServerNameIndicationExtension(curPos);
		}
		else
		{
			newExt = new SSLExtension(curPos);
		}
		m_ExtensionList.pushBack(newExt);
		curPos += newExt->getTotalLength();
	}`

if the value returned by `newExt->getTotalLength()` is 0, the func `while` will loop forever.

maybe the code should change into :

`

        uint16_6 extLen = 0;
	while ((curPos - extensionPos) < (int)extensionLength 
		&& (curPos - m_Data) < (int)messageLen 
		&& (int)messageLen - (curPos - m_Data) >= (int)minSSLExtentionLen)
	{
		SSLExtension* newExt = NULL;
		uint16_t sslExtType = be16toh(*(uint16_t*)curPos);
		if (sslExtType == SSL_EXT_SERVER_NAME)
		{
			newExt = new SSLServerNameIndicationExtension(curPos);
		}
		else
		{
			newExt = new SSLExtension(curPos);
		}

		m_ExtensionList.pushBack(newExt);

                extLen = newExt->getTotalLength();
                if (extLen <= 0) break; // maybe something is wrong with the raw data, do not continue parsing

		curPos += extLen;
	}
`

**Comment by seladb** [comment]
Thanks for reporting this issue. Do you have a pcap file that can reproduce this issue?

**Comment by bug65536** [comment]
hi,this is the demo code and cap file, compile and run, the app will never exit.

the cap file 1.cap is in err1/Bin/1.cap

**may be there exists the same bug in both function SSLClientHelloMessage and SSLServerHelloMessage**

[err1.zip](https://github.com/seladb/PcapPlusPlus/files/4992167/err1.zip)

**Comment by seladb** [comment]
Thanks, I'll look into it

**Comment by seladb** [comment]
The fix went into `master`. Thanks for reporting this issue!
