### ISSUE TITLE
bug: TcpReassembly will lost packet when FIN close too early

### ISSUE THREAD

**Issue by bug65536** [seladb/PcapPlusPlus#513]
hi, i made a pcap which has tcp frames out of order.

and then i found a bug: if TcpReassembly found frame with FIN, it will close the connection, and the frame out of order after it will be droped.

in the 1.pcap, frame #8 cause close connection , however, frame #9 has not dealed , and it will never be dealed.

**so, maybe you should close the connection when all the frame are arrived?**

[1.pcap.zip](https://github.com/seladb/PcapPlusPlus/files/5021194/1.pcap.zip)

![1](https://user-images.githubusercontent.com/42331498/89275773-4e378300-d675-11ea-8a85-74076444687a.png)

**Comment by seladb** [comment]
This is not a bug, it's an expected behavior. 

I agree I could implement a buffering mechanism that waits for missing data even after FIN has arrived but it would make the implementation even more complex than what it already is, so I made a design decision not to do it.
