### ISSUE TITLE
Compilation with -Weffc++ and -Wall yields a lot of warnings

### ISSUE THREAD

**Issue by maruu** [seladb/PcapPlusPlus#514]
Hi,

I am currently in the midst of integrating PcapPlusPlus into my build system. The build system requires the use of -Weffc++ and -Wall compiler flags.

I have noticed that there are a lot of warnings that pop up and I would be willing to fix some of them. Especially warnings like signed/unsigned comparison worry me a bit, because I had problems with these in the past.

Before I invest too much time into this topic, I just wanted to know what you think about this.

As always, all the best,
maruu

**Comment by seladb** [comment]
I think it'd be great to fix some of those warnings. But I'm not sure I'd like to add additional compiler flags to the build system

**Comment by maruu** [comment]
You wouldn't have to.. I would check that the warnings are gone using my build environment.

I was just asking, so I don't start implementing stuff and then you wouldn't accept the PR since you don't see any sense in fixing warnings or something like that.

But I am glad that we are on the same page here. :-)

I will start implementing this after my vacation.

**Comment by seladb** [comment]
hi @maruu do you know when these changes will be ready? Should we keep this issue open?

**Comment by maruu** [comment]
This is still on my todo-list, I am just not sure when I am getting around to actually doing it...

We can close it if you want, and if I get back to it I will just reopen it :-)
