### ISSUE TITLE
Error_make uninstall

### ISSUE THREAD

**Issue by 6923403** [seladb/PcapPlusPlus#517]
# make uninstall 
delete my "usr/local/bin" all files.....

**Comment by seladb** [comment]
can you instruct me how to reproduce this?

As you can see [here](https://github.com/seladb/PcapPlusPlus/blob/a6b705cb121be6813d1e38e57df1e0870896a5a9/mk/uninstall.sh.template#L13) it should only delete the PcapPlusPlus example binaries

**Comment by seladb** [comment]
I'll close this issue for now, please reopen if needed
