### ISSUE TITLE
Segmentation fault inside pcpp::IDnsResource::decodeName()

### ISSUE THREAD

**Issue by prus1337** [seladb/PcapPlusPlus#519]
I have a malformed DNS packet. During the parsing of this packet the segmentation fault has accrued. Please find attached the pcap ([pcpp_malformed_dns_packet.zip](https://github.com/seladb/PcapPlusPlus/files/5137759/pcpp_malformed_dns_packet.zip)).
Also when I tried to do the following:
`pcpp::Packet parsedPacket(&rawPacket, pcpp::OsiModelTransportLayer);`
it doesn't help. 
How can I exclude the DNS packets parsing?

**Comment by seladb** [comment]
parsing the packet with `pcpp::OsiModelTransportLayer` should work. Let me look into it and get back to you

**Comment by seladb** [comment]
I tried to parse this packet and I don't get the segmentation fault you mentioned. Can you please share your code and the platform you're running it on?

**Comment by prus1337** [comment]
It's seems it happened because I use the previous version v19.12 (official release).
My mistake I haven't check the latest version v20.08.
Thanks for your help!

**Comment by seladb** [comment]
Sure thanks!
