### ISSUE TITLE
Does RawPacket store the time stamp in local time or UTC

### ISSUE THREAD

**Issue by ashley-b** [seladb/PcapPlusPlus#520]
From my test RawPacket::getPacketTimeStamp() sems to return local time but far as I understand pcap files store packets timestamps in UTC with a common time zone offset of the recording internal (see struct pcap_file_header).
So my question is there a way to get the UTC time and offset.
Also pcap files store a time resolution ```bpf_u_int32 sigfigs;	/* accuracy of timestamps */``` which would been nice to get.

Thanks

**Comment by seladb** [comment]
the timestamp returned by `RawPacket::getPacketTimeStamp()` is the same timestamp that is read from the pcap file. AFAIK in most cases the timezone information is not stored in the pcap file so I'm not sure how to retrieve it. If you know the timezone of your pcap files you can probably convert them to UTC.

Regarding `sigfigs` - I'm not sure how much [it is being used](https://wiki.wireshark.org/Development/LibpcapFileFormat) and also whether libpcap/WinPcap/Npcap support it. In libpcap there is [`pcap_get_tstamp_precision()`](https://www.tcpdump.org/manpages/pcap_get_tstamp_precision.3pcap.html) which seems to be what you're looking for but unfortunately it's not supported in WinPcap. If this is indeed what you need we can add it in the same way ["set direction" and "immediate mode" are enabled](https://pcapplusplus.github.io/docs/install/build-source/linux) which is through build flags.

**Comment by seladb** [comment]
@ashley-b please let me know if you got my response. Should we keep this issue open?

**Comment by seladb** [comment]
I'm closing this issue now, please reopen if needed
