### ISSUE TITLE
How to build shared lib?

### ISSUE THREAD

**Issue by DinoStray** [seladb/PcapPlusPlus#521]
I use ` ./configure-linux.sh --default `,  this only build static lib.
How to build shared lib?

**Comment by seladb** [comment]
There is already an issue about that: https://github.com/seladb/PcapPlusPlus/issues/61

Currently shared lib is not supported. I think it's going to take some effort to support it.

With your permission I'll close this issue, we can discuss this more in https://github.com/seladb/PcapPlusPlus/issues/61
