### ISSUE TITLE
Missing bytes field in TcpStreamData

### ISSUE THREAD

**Issue by cryptocode** [seladb/PcapPlusPlus#522]
Per discussion on support mail, adding this issue to propose adding a `bytesMissing` field to `TcpStreamData` as obtaining this currently requires parsing reassembly callback data.

**Comment by seladb** [comment]
Thanks for reporting this issue. Would you consider implementing a fix and create a PR?

**Comment by seladb** [comment]
Thank you so much for your contribution to this project!

Your PR was merged so I'm closing the issue now.
