### ISSUE TITLE
tcp 5 tuple hash flow key in 64 bit machine : fnv_hash 

### ISSUE THREAD

**Issue by jeremyko** [seladb/PcapPlusPlus#530]
Can fnv_hash function be used in 64 bit centos 7? According to other information, it is said that the FNV_PRIME and OFFSET_BASIS constants defined in **Common++/src/IpUtils.cpp** should have different values for each 32bit and 64bit. (https://www.boost.org/doc/libs/1_74_0/libs/unordered/examples/fnv1.hpp, http://www.isthe.com/chongo/tech/comp/fnv/#FNV-param) . A duplicate flow key value occurred while I was using it. So, when the value was changed as follows, no duplication occurred.

static const size_t FNV_PRIME = 1099511628211u;
static const size_t OFFSET_BASIS = 14695981039346656037u;

**Comment by seladb** [comment]
Thanks for reporting this issue! I didn't realize that there are different `FNV_PRIME` and `OFFSET_BASIS` for different archs. Unfortunately there is currently very little distinction between 32 and 64 bit systems, however this can be added (some methods are mentioned [here](https://stackoverflow.com/questions/1505582/determining-32-vs-64-bit-in-c)).

Would you consider making the fix and create a RP?

BTW, in the boost link you shared it looks like they also use the 32-bit version only, there other ones are commented out...
