### ISSUE TITLE
static libm and libc

### ISSUE THREAD

**Issue by semkin** [seladb/PcapPlusPlus#532]
I tried to compile example and it requires static libm and libc. Our installation doesn't have them
I think, documentation referred only to libstdc++.

Is it true, that libm.a and libc.a are mandatory ?

**Comment by seladb** [comment]
To be honest, I don't think I ever tried to build PcapPlusPlus on a system that doesn't have libc or libm. Those libraries are usually installed by default in most standard Linux distros. Can you point me to the areas in the code that require these libraries?

**Comment by seladb** [comment]
@semkin did you get a chance to look into it?

**Comment by seladb** [comment]
I'll close this issue for now. Please reopen if still relevant
