### ISSUE TITLE
parse reassembled tcp payload

### ISSUE THREAD

**Issue by kunkunLEE** [seladb/PcapPlusPlus#533]
What a wonderful library to parse different protocols and reassemble tcp payloads in such short time. However I have some trouble  in parsing reassembled tcp payload created by the example named "TcpReassembly". My task is to parse ssl/tls record layer above tcp. It seems that pcap++ can't parse tls/ssl record layers spread over serveral packets. For example, a  ApplicationDataLayer spreads in 10 packets, and next ApplicationDataLayer starts in 10th packet, it seems that no SSLLayer will be parsed in 10th packet. How can I parse the 10th packet mentioned above？Just parse reassembled tcp payload created by "TcpReassembly" or I make some mistakes.

 
![1602666332(1)](https://user-images.githubusercontent.com/30453329/95968125-ab06a500-0e3f-11eb-9a42-2246b36d94d5.png)
![1602666391(1)](https://user-images.githubusercontent.com/30453329/95968132-ac37d200-0e3f-11eb-9582-e3135bf10b87.png)

**Comment by seladb** [comment]
thanks @kunkunLEE for the kind words!

SSL/TLS messages are encrypted so I'm not sure what you're trying to parse.
Also, TCP reassembly streams only the TCP data, not the protocols on top of it. This means that basically you can see all the bytes that are moving from client to server and vice versa, but of course you won't be able to see the content since the messages are encrypted.

I hope this answers your question. Please let me know if you need more info.

**Comment by kunkunLEE** [comment]
thank you for your answers. I just want to parse ssl/tls record information, such as record type(handshake, application, alert etc) and record length, just as you can see in wireshark. I'm not mean to see what is encrypted content in the record.

**Comment by Active2626** [comment]
He means that when one packet contains two segments of different tls record , then the second tls record can't be recognized as ssl protocal traffic.

**Comment by kunkunLEE** [comment]
For example, in this pcap, as you can see in the picture below, No.50 packet contains the last segment of a SSLlayer and the first segment of next SSLlayer. I try to change some code in example "PacketParsing", and no SSLlayer can be parsed in this packet.
![1602724639(1)](https://user-images.githubusercontent.com/30453329/96062905-60ca0600-0ec9-11eb-8631-1e8a6e813271.png)
![1602724803(1)](https://user-images.githubusercontent.com/30453329/96062959-7c351100-0ec9-11eb-9a4c-40cd28ca75bc.png)

**Comment by seladb** [comment]
I think I understand now, thanks for clarifying. You are basically asking for a new "SSL/TLS reassembly" feature that will reassemble SSL/TLS message that are spread over more than one packet.

Unfortunately this feature isn't currently available in PcapPlusPlus. I do have in my roadmap a plan to support L7 protocol reassembly which can apply to protocols like SSL/TLS but also to other protocols like HTTP, SIP and more.

I'm not sure when I'll get to implement it. With the current architecture of PcapPlusPlus it will be quite challenging to fit this in so it needs to be designed carefully.

**Comment by kunkunLEE** [comment]
Thanks for your apply. I will consider trying to parse reassembled tcp payload. I hope I could extract what I need.

**Comment by seladb** [comment]
I'll close this issue now, please reopen it if needed
