### ISSUE TITLE
static libm and libc - reply to 532

### ISSUE THREAD

**Issue by semkin** [seladb/PcapPlusPlus#534]
Sorry, for delay.

This is simple program that requires libc.a and libm.a
Our installation has only libc.so and libm.so 

I use directly libpcap in C. So, question is not important to me now.
But it would be helpful, if installation PcapPlusPlus will build shared library too.

#include <iostream>
#include <iomanip>
#include <string>

#include "pcapplusplus/PcapFileDevice.h"
#include "pcapplusplus/RawPacket.h"

using namespace std;

using namespace pcpp;

int main(int argc, const char** argv) {
    string  fname("name.pcap");
    RawPacket rawPacket;
    int count;

    PcapFileReaderDevice  pcapRdr(fname.c_str());

    pcapRdr.open();

    while (pcapRdr.getNextPacket(rawPacket)) {
        ++count;
    }

    pcapRdr.close();
}

**Comment by seladb** [comment]
thanks for your response. There is already an open issue for creating shared libraries: https://github.com/seladb/PcapPlusPlus/issues/61. I'm not sure how to remove the need for `libc.a` and `libm.a` without creating shared libraries for PcapPlusPlus

**Comment by seladb** [comment]
@semkin please let me know what you think

**Comment by semkin** [comment]
I read discussions in  #61. It is not urgent for me. Will check from time to time and hope you will find solution. 
I will close this issue.
