### ISSUE TITLE
I want to get the src mac address, it's messy code.

### ISSUE THREAD

**Issue by CidoLiu** [seladb/PcapPlusPlus#536]
Here is my the part of my code:
```pcpp::EthLayer* ethernetLayer = parsedPacket.getLayerOfType<pcpp::EthLayer>();
            const char *srcMacAddr = ethernetLayer->getSourceMac().toString().c_str();
            const char *dstMacAddr = ethernetLayer->getDestMac().toString().c_str();
            printf("EthLayer:\n");
            printf("Source MAC address: %s\n", srcMacAddr);```

The print is just messy code, like this: ` 0��z
V`, how can I fix this problem?
And httpUserAgent and so on, in HTTPRequest is in the same situation.
Help~~~~

**Comment by seladb** [comment]
are you sure your packet is an Ethernet packet?

**Comment by CidoLiu** [comment]
> are you sure your packet is an Ethernet packet?

Of course, thank you for your reply immediately.

I test some pcap or pcapng file, even 'PcapPlusPlus/Examples/Tutorials/Tutorial-PacketParsing/1_http_packet.pcap', however when I run the example, everything is normal. In my code, it's become messy code, I didn't get any error message, it's a little puzzled me.

**Comment by CidoLiu** [comment]
When I run the example code, I get this:
```
Layer type: Ethernet; Total data: 443 [bytes]; Layer data: 14 [bytes]; Layer payload: 429 [bytes]
Layer type: IPv4; Total data: 429 [bytes]; Layer data: 20 [bytes]; Layer payload: 409 [bytes]
Layer type: TCP; Total data: 409 [bytes]; Layer data: 32 [bytes]; Layer payload: 377 [bytes]
Layer type: HTTP; Total data: 377 [bytes]; Layer data: 377 [bytes]; Layer payload: 0 [bytes]

Source MAC address: 00:50:43:01:4d:d4
Destination MAC address: 00:90:7f:3e:02:d0
Ether type = 0x800

Source IP address: 172.16.133.132
Destination IP address: 98.139.161.29
IP ID: 0x36E4
TTL: 64

Source TCP port: 54615
Destination TCP port: 80
Window size: 6
TCP flags: ACK PSH
TCP options: NOP NOP Timestamp

HTTP method: GET
HTTP URI: /serv?s=19190039&t=1361916157&f=us-p9h3
HTTP host: geo.yahoo.com
HTTP user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/534.55.3 (KHTML, like Gecko) Version/5.1.3 Safari/534.53.10
HTTP cookie: B=fdnulql8iqc6l&b=3&s=ps
HTTP full URL: geo.yahoo.com/serv?s=19190039&t=1361916157&f=us-p9h3
```
However, I run my code for the same pcap file, it's become this:
```
EthLayer:
Source MAC address: P��UU
Destination MAC address: P��UU
Ipv4Layer:
SrcIp: 172.16.133.132
DstIp: 98.139.161.29
TTL: 64
TcpLayer:
SrcPort: 54615
DstPort: 80
Tcp Flag: ACK PSH
HttpRequestLayer:
HTTP method: GET
HTTP URI:
HTTP Host: geo.yahoo.com
HTTP user-agent:
HTTP Cookie:
HTTP Url:
```
Some of message is normal, but some of them become messy code, if it's possible I can share my code for you in private way. :)

**Comment by seladb** [comment]
I think it would be helpful if you share your code. Are you using this pcap file https://github.com/seladb/PcapPlusPlus/blob/master/Examples/Tutorials/Tutorial-PacketParsing/1_http_packet.pcap?

You can send the code to PcapPlusPlus support email: pcapplusplus@gmail.com

**Comment by CidoLiu** [comment]
> I think it would be helpful if you share your code. Are you using this pcap file https://github.com/seladb/PcapPlusPlus/blob/master/Examples/Tutorials/Tutorial-PacketParsing/1_http_packet.pcap?
> 
> You can send the code to PcapPlusPlus support email: [pcapplusplus@gmail.com](mailto:pcapplusplus@gmail.com)

Yes, I just use that pcap file.  I'll send my code to support email, thanks.

**Comment by seladb** [comment]
@CidoLiu I don't think I've seen an email from you. Are you still experiencing this issue or did you figure it out?

**Comment by CidoLiu** [comment]
> @CidoLiu I don't think I've seen an email from you. Are you still experiencing this issue or did you figure it out?

Oh, I have sent an email to you with the subject "Code for issues 536" by my outlook email yesterday, maybe the PRC gov intercept my mail.

However, I figure that problem out by myself. The normal coad as follows:
```
            pcpp::EthLayer *ethernetLayer = parsedPacket.getLayerOfType<pcpp::EthLayer>();
            std::string srcMacAddr = ethernetLayer->getSourceMac().toString();
            std::string dstMacAddr = ethernetLayer->getDestMac().toString();            
            printf("EthLayer:\n");
            printf("Source MAC address: %s\n", srcMacAddr.c_str());
```

Just change the const char * to std::string, the messy code is going away.

**Comment by seladb** [comment]
awesome, thanks for the update!

I'll close the issue now. Please reopen if you have further questions.
