### ISSUE TITLE
tcp packet loss

### ISSUE THREAD

**Issue by xiaocaio** [seladb/PcapPlusPlus#539]
if pcap+ use libpcap backend, then tcp begin to loss packet when client send 6K packets sequence with no wait( 256 bytes per packet).
buf if pcap+  use pf_ring backend, then tcp begin to loss packet when client send 5.5K packets sequence. 
it's weired that pf_ring slower than libpcap.

retry 
client only send packets (packet's content is fixed, do nothing else)
server only receive packets, do nothing else
pcap+'s tcpassembly states all packet's length

any tips for me ? thanks

**Comment by seladb** [comment]
it's hard to say why pf_ring is slower than libpcap. It should be the other way around. Can you try using pf_ring without PcapPlusPlus? Is it faster that way?
Also, how many threads are you using for packet capture?

**Comment by xiaocaio** [comment]
> it's hard to say why pf_ring is slower than libpcap. It should be the other way around. Can you try using pf_ring without PcapPlusPlus? Is it faster that way?
> Also, how many threads are you using for packet capture?

it's network environment problem, thanks
