### ISSUE TITLE
Modifying code cause undefined behavior

### ISSUE THREAD

**Issue by gerald-dotcom** [seladb/PcapPlusPlus#540]
@seladb 

This issue more or less likely reproducible. But I don't know what's the root cause of this.

Anyway, I modified PcapPlusPlus's SSL as follows,

On SSLHandshake.cpp I replaced the following code

```
SSLCipherSuite* SSLClientHelloMessage::getCipherSuite(int index) const
{
	if (index < 0 || index >= getCipherSuiteCount())
		return NULL;

	size_t cipherSuiteStartOffset = sizeof(ssl_tls_client_server_hello) + sizeof(uint8_t) + getSessionIDLength() + sizeof(uint16_t);
	if (cipherSuiteStartOffset + sizeof(uint16_t) > m_DataLen)
		return NULL;

	uint16_t* cipherSuiteStartPos = (uint16_t*)(m_Data + cipherSuiteStartOffset);
	return SSLCipherSuite::getCipherSuiteByID(be16toh(*(cipherSuiteStartPos+index)));
}
```

**with**

```
uint16_t SSLClientHelloMessage::getCipherSuiteHexValue(int index) const
{
	if (index < 0 || index >= getCipherSuiteCount())
		return 0;

	size_t cipherSuiteStartOffset = sizeof(ssl_tls_client_server_hello) + sizeof(uint8_t) + getSessionIDLength() + sizeof(uint16_t);
	if (cipherSuiteStartOffset + sizeof(uint16_t) > m_DataLen)
		return 0;

	uint16_t* cipherSuiteStartPos = (uint16_t*)(m_Data + cipherSuiteStartOffset);
	return be16toh(*(cipherSuiteStartPos+index));
}
```

Then added following header declaration on SSLHandshake.h 

```
	/**
	 * Get hex value of a cipher-suite by index.
	 * @param[in] index The index of the cipher-suite to return
	 * @return The hex value of the cipher-suite or NULL if index is out of bounds
	 */

	uint16_t getCipherSuiteHexValue(int index) const;
```

Then I just removed tests related to SSL and compiled the lib as usual 

At first Iterations when I run my program, it works fine but after couple of days I noticing it outputs weird cipher suite counts like 1200 and 1500, 9000 and so on when calling the getCipherSuiteCount() method on lib.

The exact CipherSuiteCount for **Chrome** is 16 and for **Firefox** is 18

The program outputs 16 and 18 at first days but somehow magically it get broken after days even after re-compiled it output same wired numbers. 

I greatly appreciate your opinion on this matter!

**Comment by seladb** [comment]
@gerald-dotcom if I understand correctly the issue you're experiencing is not with your code change but rather with the `getCipherSuiteCount()` method? 

It's hard to tell what is happening without seeing your code and the network traffic input. Do you think you can provide a code snippet and a pcap file that reproduce this issue? I can take a look

**Comment by gerald-dotcom** [comment]
The code change seems affect **getCipherSuiteCount()** method (Perhaps it's dependencies.)

I've not observed this problem before the code change. I however noticed same kind of problem on https://github.com/seladb/PcapPlusPlus/issues/473 when I tried to add Ciphers myself to your code and I lacked time so went out with this way (I mean the way you can see how I implemented above)

Funny thing is that this happen randomly. Yesterday it happened all day, and today it gone.
 
Attached the code to this issue that I used for capturing logic also attached the pcap file. 

[file.zip](https://github.com/seladb/PcapPlusPlus/files/5506905/file.zip)

**Comment by gerald-dotcom** [comment]
Ahahhaa

I just ran the program for one more time and was able to reproduce the malformed cipher length case.

See the attached pcap files

[reprod_case.zip](https://github.com/seladb/PcapPlusPlus/files/5506987/reprod_case.zip)

**Comment by gerald-dotcom** [comment]
I just opened those pcap files on wireshark and there the length is 16 whereas yours is 1200

If you want I can share the lib binaries so you can directly place them on your /usr/ folder and test out.

**Comment by gerald-dotcom** [comment]
I'm not sure if this issue caused by the timestamp field  for TLS 1.2 I added on the struct
https://github.com/seladb/PcapPlusPlus/issues/471

But whatever hard to dig the root cause!!

**Comment by seladb** [comment]
thank for all the info @gerald-dotcom !

I tried to reproduce this issue using your code but unfortunately I wasn't able to.
I used both the pcap files you provided and also ran it on live traffic but couldn't reproduce the issue. On Firefox I usually get 18 as you mentioned and on Chrome I usually get 16.

Here is the setup I ran it on:
- Ubuntu 20.04 VirtualBox VM
- Latest PcapPlusPlus version from [master](https://github.com/seladb/PcapPlusPlus/commit/a8e038bbaef2eb2b988352c0c86bb9e809eb4d95)
- Browsers are Firefox 81 and Chromium 86
- The code and pcap files are the ones you provided

Are you also using the latest PcapPlusPlus version from `master`?

**Comment by gerald-dotcom** [comment]
@seladb 

I am using a stable version within this year and I don't remember exact version. 

Can you try this case and compile again?

I have attached .a files, could you please put them to /usr/local/lib?
[lib.tar.gz](https://github.com/seladb/PcapPlusPlus/files/5510823/lib.tar.gz)

**Comment by seladb** [comment]
I used the library files you provided and the issue is indeed reproduced. However I cannot reproduce it with my code.

Apparently you're using [the latest official release](https://github.com/seladb/PcapPlusPlus/commit/3977cd142500a03431397357bebf7f1d61be8ce8) from Aug 20. I used [`getGitCommit()`](https://pcapplusplus.github.io/api-docs/namespacepcpp.html#acae7542122e659b88073dc6b76564e6b) to find this out. I tried to revert my code to this revision but still the issue is not reproduced. 
My best guess is that this is something with your environment which is different than mine:
- Which OS are you using?
- What is your gcc version?
- Which version of libpcap?

Maybe this will shed some light on this issue...

**Comment by gerald-dotcom** [comment]
OS is  Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-118-generic x86_64)
GCC is for C not C++ and G++ is for C++ so my G++ version is g++ 7.5.0
libpcap-dev 1.8.1

**Comment by seladb** [comment]
Do these libs include any code change you made on your side or is it identical to the release version?

**Comment by gerald-dotcom** [comment]
They do include a code change. Scroll up where I described the code change "On SSLHandshake.cpp I replaced the following code

"

**Comment by seladb** [comment]
Got it. Let me add these code changes in my setup and see if I can reproduce the issue

**Comment by gerald-dotcom** [comment]
Perhaps you also can decompile the .a files and compare with your newly compiled .a files with the code changes and spot the bug

I lack expertise in C and ASM so I can't do this ;(

**Comment by seladb** [comment]
I'm also not an expert in these areas. Let me see what I can do... in the meantime, can you try to run your code on the latest version from `master` and let me know if you can reproduce it there?

**Comment by gerald-dotcom** [comment]
> I'm also not an expert in these areas. Let me see what I can do... in the meantime, can you try to run your code on the latest version from `master` and let me know if you can reproduce it there?

I did this every time the issue appeared; however, it start to reproduce same behavior after week. I'm tired of doing this. 
Not sure why this happening. It's like something on code patch binaries it-self. 

https://en.wikipedia.org/wiki/Self-modifying_code

**Comment by seladb** [comment]
I made the code changes you mentioned but still I cannot reproduce the issue.

It would be very helpful if you can reproduce it on a "clean" version without any of your code changes: either from `master` or from the [latest official version](https://github.com/seladb/PcapPlusPlus/archive/v20.08.tar.gz). Once it's reproduced please send me the pcap file and I'll check.

Are there anymore changes you made in PcapPlusPlus code except for the method change you mentioned in the [beginning of this thread](https://github.com/seladb/PcapPlusPlus/issues/540#issue-738324437)?

**Comment by gerald-dotcom** [comment]
Did you made the code change for header file as-well?

No, I can't reproduce this issue on a clean version. Tried yesterday.

I didn't made any more changes other than the ones I mentioned. 

Perhaps you can run GDB through the code flow and see anything?

**Comment by seladb** [comment]
> 
> 
> Did you made the code change for header file as-well?

Yes of course, otherwise build would fail
> 
> No, I can't reproduce this issue on a clean version. Tried yesterday.
> 
> I didn't made any more changes other than the ones I mentioned.
> 
> Perhaps you can run GDB through the code flow and see anything?

I'm not sure GDB would help but I'm willing to give it a shot. Maybe you can it try too on your setup, it's more likely that you can reproduce and track the problem faster because you have the source code and the binaries

**Comment by seladb** [comment]
As I suspected GDB might not give reliable information without the source code the library was compiled with. For example: when I print `sizeof(ssl_tls_client_server_hello)` I get a result of 70 which doesn't make sense (the result should be 38).

I suggest you try to debug it with your own source code and see if you get better results.

**Comment by gerald-dotcom** [comment]
I'm closing this for now and will re-open if I able to reproduce on my side again with upstream branch!

**Comment by gerald-dotcom** [comment]
@seladb  I was able to reproduce this issue on a fresh upstream branch with the code changes (and SSL tests removed).

For your inconvenience, download the complete source files from here
https://we.tl/t-7OXa05vxz5

**Comment by gerald-dotcom** [comment]
@seladb  Were you able to reproduce using the source files I provided?

**Comment by seladb** [comment]
I figured out the issue!!

Apparently, you made one more change in the code that you didn't mention:
```cpp
struct ssl_tls_client_server_hello : ssl_tls_handshake_layer
{
	/** SSL/TLS handshake version (one of SSLVersion::SSLVersionEnum) */
	uint16_t handshakeVersion;
	/** 32-bytes random number */
	uint8_t random[32];   // <=== You forgot to remove this
	
	struct    // <=== You added this struct
	{
		uint32_t gmt_unix_time;
		uint8_t random_bytes[28];
	} Random;
};
```

You added the `Random` struct inside `ssl_tls_client_server_hello` but you forgot to remove `uint8_t random[32]`, so now the struct `ssl_tls_client_server_hello` has 2 random fields instead of one! When I removed `uint8_t random[32]` the issue was gone.
This explains why I got `sizeof(ssl_tls_client_server_hello) == 70` when running with GDB, it's because in your code the struct is 32 bytes longer.

Actually, I'm surprised how the issue wasn't reproduced faster for you. This bug should have broken the whole TLS parsing...

**Comment by gerald-dotcom** [comment]
Interesting. I thought about that too but discarded because it worked fine even with that change so I thought this is related to something else.  Well, Is it correct to say it may cause undefined behavior? 

My other machine is working still fine without any wired ciphers and it has the the struct as its with the anon struct

**Comment by gerald-dotcom** [comment]
The reason I didn't delete that field because of TLS 1.3

**Comment by seladb** [comment]
> 
> 
> Interesting. I thought about that too but discarded because it worked fine even with that change so I thought this is related to something else. Well, Is it correct to say it may cause undefined behavior?

Yes, to say the least. This bug can cause a lot of issues in parsing TLS packets
> 
> My other machine is working still fine without any wired ciphers and it has the the struct as its with the anon struct

This is very surprising actually

> The reason I didn't delete that field because of TLS 1.3

Can you please explain how TLS 1.3 is relevant here?

**Comment by gerald-dotcom** [comment]
TLS 1.3 uses uint8_t random[32];  wheres TLS 1.2 uses that anon struct
