### ISSUE TITLE
[Packet++] HttpResponse dissector crash (sigabrt)

### ISSUE THREAD

**Issue by slinkinone** [seladb/PcapPlusPlus#544]
### Description

`HeaderField` class has the following `int` fields: `m_NameOffsetInMessage`, `m_ValueOffsetInMessage` and at the same type `m_FieldSize`, `m_FieldValueSize`, `m_FieldNameSize` that are `size_t` type.

The error occurs in `HeaderField(TextBasedProtocolMessage* TextBasedProtocolMessage, int offsetInMessage, char nameValueSeperator, bool spacesAllowedBetweenNameAndValue)` constructor at the following line:
```
else
{
         m_FieldValueSize = fieldEndPtr - fieldValuePtr;          // INTEGER-OVERFLOW
         // if field ends with \r\n, decrease the value length by 1
         if ((*(--fieldEndPtr)) == '\r')
                  m_FieldValueSize--;
}
```

It is an __integer-overflow__ that leads to memory-access-violation. `m_FieldValueSize` has become equal to `0xFFFFFFFFFFFFFFF3`. (and then to `0xFFFFFFFFFFFFFFF2` due to the last line of the snippet)

![integer-overflow](https://user-images.githubusercontent.com/11265408/99504236-4d123380-2990-11eb-8344-81c5dfdd1cc5.png)

While it is not visible error, but when we start process each layer and namely printing **HTTP**  __header-values__ we get a case of trying to create a string with length = `0xFFFFFFFFFFFFFFF2` in `getFieldValue()` method.

![integer-overflow-2](https://user-images.githubusercontent.com/11265408/99504249-513e5100-2990-11eb-85d6-9b17d5c34101.png)

I've made a small changes to PcapPrinter example to demonstrate how user can catch this crash. I didn't touch the library code - only example of usage. See extra include files and `printPcapNgPackets` function. 

### Suggestion

It is a really insecure approach to assign __signed__ and __unsigned__ variables to each other.  `m_NameOffsetInMessage`, `m_ValueOffsetInMessage`  have to be `size_t` and before each arithmetic operation we have to check values to avoid integer-overflow. It is more logical - offsets shouldn't  be used as negative values. I know that we can work with offsets as with negative values and it is not restricted - but it leads to hidden behavior like an __integer-overflow__.

Also the following checking looks a little weird: 
```
if (m_FieldNameSize != (size_t)-1)
```

I realize what it does, but it is not guaranty check and few paragraphs ago we have faced with it. Easier - If __string-length__ is equal to **0** it means we don't have a value. From that we can use `size_t` for that member.

### Attached files
The archive with slightly modified PcapPrinter example and with pcang dump file: [http-resp-crash.zip](https://github.com/seladb/PcapPlusPlus/files/5558716/http-resp-crash.zip)

**Comment by seladb** [comment]
Thanks for the detailed description @slinkinone !

What you say makes a lot of sense. I've written this code a few years ago so I'm not sure I remember all the details, but I do remember that the `HeaderField` needs to handle few different use-cases:
- Parsing of HTTP/SIP header fields
- Incomplete header fields, i.e a field that starts in this packet but ends in the next
- Header fields created by the user and are not a part of a packet

Assigning a value of `-1` to an offset variable means we can't find the offset, as opposed to `0` which means offset zero. I know it's not very clean but can't find a better way to indicate that an offset is invalid (other than having another variable for example `bool m_IsValueOffsetInMessageValid` which will make the code even more complex).

The issue you describe is actually not related to mixing signed and unsigned integers, it's related to subtracting pointers which may lead to (unsigned) integer overflow. I think we can add checks before doing that and it will solve the problem, right?

Regarding the weird statement `if (m_FieldNameSize != (size_t)-1)` - I agree that it's pretty ugly. I think we can try `0` instead and see if there are any issues with that.

Would you consider making the fixes and open a PR?

**Comment by slinkinone** [comment]
Hi @seladb !
Thanks for your response.
If I have free time until New Year - I will fix it.

**Comment by seladb** [comment]
hi @slinkinone ! I wanted to ping you to see if you're still interested in working on the fix. Please let me know

**Comment by slinkinone** [comment]
Hi @seladb !
Unfortunately, I hadn't free time to work on that bug(
Currently, I'm busy at work and 100% will not be able to do that until March.
If anyone on your radar is able to do that - I don't mind. If not - I can start only close to March.

Waiting for your answer.

**Comment by seladb** [comment]
thanks for getting back to me @slinkinone . Let me see if I can find time to fix it before March, otherwise please let me know when you can start working on this

**Comment by slinkinone** [comment]
@seladb Got you, no problem.
Take care!

**Comment by seladb** [comment]
hi @slinkinone I created a fix for this bug, it's in PR #577 . Please feel free to review and make your comments.
The only fix I needed to make is to check whether the pointer to the field value comes after the pointer to the end of the field.
Regarding assigning (-1) to variables of type `size_t` - this is done on purpose to mark an offset as invalid. It's pretty safe to do so and it gives the 2's complement of the negative number (as explained [here](https://stackoverflow.com/questions/2711522/what-happens-if-i-assign-a-negative-value-to-an-unsigned-variable)). 

I've also added a test with your example to cover this case.

Please let me know if you have any questions.

**Comment by slinkinone** [comment]
hi @seladb!
Great! I will do it to the end of the week.

**Comment by slinkinone** [comment]
Hi @seladb.
I've reviewed that. If I understand correctly - the reason of the bug was in the following header field:

```
x-amz-request-id2 CA4DB8F36423461F
```

`pcap++` found the `:` separator that was located outside the *field-length* (`\n` separator). In other words, `pcap++` found a `:` that belonged to the following header-field.

I agree with that fix.
Good job! Thanks for your work.

**Comment by seladb** [comment]
> pcap++ found the : separator that was located outside the field-length (\n separator). In other words, pcap++ found a : that belonged to the following header-field.

Yes that's correct!

Issue is fixed and merged to `master`. Thanks for reporting it and working with me on the fix, much appreciated!
