### ISSUE TITLE
[ Documentation ] Suggestion - doxygen documentation should match latest release

### ISSUE THREAD

**Issue by iwubcode** [seladb/PcapPlusPlus#549]
The latest release is in august of this year but there were changes to the code that caused changes in the doxygen documentation.  At first I was confused because I assumed the documentation matched the latest release (it seems instead to match master?).

My suggestion is to keep the doxygen documentation linked to the latest release (or provide documentation for each release including `master`).

**Comment by seladb** [comment]
I'm sorry you find it confusing. There are actually separate places for the latest official release (currently v20.08) and `master`:
- API reference for the latest from `master` is on the main website: https://pcapplusplus.github.io/api-docs/
- API reference for the latest official release (v20.08) is here: https://pcapplusplus.github.io/v2008/api-docs/ . You can find this link in the [Releases](https://pcapplusplus.github.io/docs/releases) page

Please let me know if this answers your question.

**Comment by iwubcode** [comment]
Ah, totally missed that.  I went straight for "API Reference" underneath the release window.  This should suffice, thank you for the explanation!
