### ISSUE TITLE
Add option to make libraries with position independent code (-fPIC)

### ISSUE THREAD

**Issue by iwubcode** [seladb/PcapPlusPlus#550]
Trying to use any of the statically built libraries in a shared library will give errors about recompiling with `-fPIC`.  It'd be nice if this was an option in the build scripts.

**Comment by seladb** [comment]
the `-fPIC` flag is already added to all of the makefiles:
https://github.com/seladb/PcapPlusPlus/blob/633fdfb78b85d795f4b437cdb5fbdc041ae2b622/mk/PcapPlusPlus.mk.common#L16

Can you please elaborate on the compilation errros you encounter?

**Comment by iwubcode** [comment]
> the -fPIC flag is already added to all of the makefiles

Ah so it is, it is not however in the latest release, which is why I missed it.

I also had to add it to:  https://github.com/seladb/PcapPlusPlus/blob/master/3rdParty/LightPcapNg/Makefile#L18 .  Maybe there's a way to not require that library?  I just used the default options in the `configure-linux` script.

**Comment by seladb** [comment]
You're absolutely right, thanks for noticing that! There is currently no way to exclude this library as it is used for reading and writing pcapng files. Do you want to open a PR with this fix or prefer I do it?

**Comment by seladb** [comment]
Actually, I looked again and the `-fPIC` flag is there: https://github.com/seladb/PcapPlusPlus/blob/ea577d9cda23608671edfaef705eabc33de97273/3rdParty/LightPcapNg/Makefile#L12

@iwubcode do you still see issues there?

**Comment by iwubcode** [comment]
Yeah, looks like it was already added to master.  Like I mentioned, I was using the latest tag (so there can be some version tracking).  Regardless, this can be closed.

Thank you and happy holidays!
