### ISSUE TITLE
DNS layer contains more than 300 resources, probably a bad packet. Skipping parsing DNS resources

### ISSUE THREAD

**Issue by CidoLiu** [seladb/PcapPlusPlus#553]
There are so many messages like follows:
DNS layer contains more than 300 resources, probably a bad packet. Skipping parsing DNS resources

I'm sure that doesn't affect the function of my program, how can I  shield those message?

I saw this issue were raised by others, but I didn't find any solution about that.

**Comment by seladb** [comment]
Parsing of those DNS packets fails, probably because they are malformed. If you want to suppress those error messages you can use:
```cpp
pcpp::LoggerPP::getInstance().supressErrors()
```

Here is an example: https://github.com/seladb/PcapPlusPlus/blob/f30de1387acc1f823e0d4779e5565f4cc32dd4a6/Tests/Pcap%2B%2BTest/Tests/LiveDeviceTests.cpp#L44

**Comment by CidoLiu** [comment]
thx
