### ISSUE TITLE
ESP and AH protocol header parsing support?

### ISSUE THREAD

**Issue by pa5h1nh0** [seladb/PcapPlusPlus#555]
I expect for this to be a really easy task to do by myself, but the code I'd write would be a client code, so won't be part of PcapPlusPlus :( . I'm just wondering if adding this to PcapPlusPlus would make sense, as there are lots of other protocol headers parsing you already support, but not ESP and AH.

Thanks

**Comment by seladb** [comment]
thanks for your suggestion! I think that adding IPSec would really make sense!
I didn't understand your comment about writing client code that won't be part of PcapPlusPlus... do you think you can implement this and open a PR? I can guide you on how to add a new protocol

**Comment by seladb** [comment]
Done! Added to `master` branch on commit https://github.com/seladb/PcapPlusPlus/commit/bb7a2b232b9ec864665312a1552faf2f5d5bc31b

Thank you so much for the suggestion, let me know if you have any questions. 
I'm closing the issue for now, please reopen if needed.

**Comment by pa5h1nh0** [comment]
Thx a lot for this, really. Sorry I didn't answer earlier though, I had to put this on hold due to some other higher priorities. Anyway, I'll try to use this as soon as I'll resume, and in case of any issue will write down here (or open an issue?).
