### ISSUE TITLE
Issue with TestDpdkDeviceWorkerThreads & TestDpdkMbufRawPacket test in unit tests of Pcap++Test

### ISSUE THREAD

**Issue by cartman-156** [seladb/PcapPlusPlus#556]
I have installed pcap++(v20.08) & dpdk(v18.11.10) in my CentOS7 VM. 
Installation was done as follows.
**DPDK Installation**
`make config T=x86_64-native-linuxapp-gcc` and `make install`
**PCAP++ Installation**
Using `install-with-dpdk.sh` with DPDK path as input. 
Port was bound to DPDK driver using `dpdk-setup.sh` present inside DPDK installer.

Traffic generation is handled manually using `tcpreply` via another VM which is connected to the port which is linked with DPDK-compatible driver. 

With this setup I am trying to run the` Pcap++Test` which comes with pcap++ installation with input `-i <my_vm_ip>` and `-d 0` since there only one DPDK port. With this inputs TestDpdkDeviceWorkerThreads & TestDpdkMbufRawPacket keeps on failing with 
`(Tests/DpdkTests.cpp:645). assert lower than failed: actual: 20 >= expected: 20` & 
`(Tests/DpdkTests.cpp:867). assert lower than failed: actual: 30 >= expected: 30` respectively. 
When port is detached from dpdk the traffic is successfully received on the same via same `tcpreply` command.

PFB the complete output from `Pcap++test`

```
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:0b:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 15ad:7b0 net_vmxnet3
EAL: PCI device 0000:13:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 15ad:7b0 net_vmxnet3
EAL: PCI device 0000:1b:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 15ad:7b0 net_vmxnet3
subnet prefixLength '0' illegal
TestIPAddress                 : PASSED
TestMacAddress                : PASSED
TestLRUList                   : PASSED
TestGeneralUtils              : PASSED
TestGetMacAddress             : PASSED
TestPcapFileReadWrite         : PASSED
TestPcapSllFileReadWrite      : PASSED
TestPcapRawIPFileReadWrite    : PASSED
TestPcapFileAppend            : PASSED
TestPcapNgFileReadWrite       : PASSED
TestPcapNgFileReadWriteAdv    : PASSED
TestPcapLiveDeviceList        : PASSED
TestPcapLiveDeviceListSearch  : PASSED
TestPcapLiveDevice            : PASSED
TestPcapLiveDeviceNoNetworking: PASSED
TestPcapLiveDeviceStatsMode   : PASSED
TestPcapLiveDeviceBlockingMode: PASSED
TestPcapLiveDeviceSpecialCfg  : PASSED
TestWinPcapLiveDevice         : PASSED
TestSendPacket                : PASSED
TestSendPackets               : PASSED
TestRemoteCapture             : PASSED
TestPcapFilters_MatchStatic   : PASSED
TestPcapFiltersLive           : PASSED
TestPcapFilters_General_BPFStr: PASSED
TestPcapFiltersOffline        : PASSED
TestPcapFilters_LinkLayer     : PASSED
TestHttpRequestParsing        : PASSED
TestHttpResponseParsing       : PASSED
TestPrintPacketAndLayers      : PASSED
TestDnsParsing                : PASSED
TestDpdkInitDevice            : PASSED
TestDpdkDevice                : PASSED
TestDpdkMultiThread           : PASSED
TestDpdkDeviceSendPackets     : PASSED
TestDpdkDeviceWorkerThreads   : FAILED (Tests/DpdkTests.cpp:645). assert lower than failed: actual: 20 >= expected: 20
TestDpdkMbufRawPacket         : FAILED (Tests/DpdkTests.cpp:867). assert lower than failed: actual: 30 >= expected: 30
TestTcpReassemblySanity       : PASSED
TestTcpReassemblyRetran       : PASSED
TestTcpReassemblyMissingData  : PASSED
TestTcpReassemblyOutOfOrder   : PASSED
TestTcpReassemblyWithFIN_RST  : PASSED
TestTcpReassemblyMalformedPkts: PASSED
TestTcpReassemblyMultipleConns: PASSED
TestTcpReassemblyIPv6         : PASSED
TestTcpReassemblyIPv6MultConns: PASSED
TestTcpReassemblyIPv6_OOO     : PASSED
TestTcpReassemblyCleanup      : PASSED
TestTcpReassemblyMaxSeq       : PASSED
TestIPFragmentationSanity     : PASSED
TestIPFragOutOfOrder          : PASSED
TestIPFragPartialData         : PASSED
TestIPFragMultipleFrags       : PASSED
TestIPFragMapOverflow         : PASSED
TestIPFragRemove              : PASSED
TestRawSockets: NON-CRITICAL: (Tests/RawSocketTests.cpp:83). actual: 0 != expected: 1
TestRawSockets                : PASSED

NOT ALL TESTS PASSED!!
Test cases: 65, Passed: 54, Failed: 2, Skipped: 9

```

Request you to help with this.

Edit:

I've tested the same setup with `DpdkExample-FilterTraffic` utility and when I send the traffic to the port from another VM, I can see packets being received in the output. PFB the output from that utility.

```
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| Core ID | Packet Cnt  | Eth Cnt     | ARP Cnt     | IPv4 Cnt    | IPv6 Cnt    | TCP Cnt     | UDP Cnt     | HTTP Cnt    | Matched TCP Flows  | Matched UDP Flows  | Matched Packets    |
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| 1       | 0           | 0           | 0           | 0           | 0           | 0           | 0           | 0           | 0                  | 0                  | 0                  |
| 2       | 2           | 2           | 0           | 2           | 0           | 0           | 0           | 0           | 0                  | 0                  | 2                  |
| 3       | 2400        | 2400        | 0           | 2400        | 0           | 2400        | 0           | 120         | 1                  | 0                  | 2400               |
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| Total   | 2402        | 2402        | 0           | 2402        | 0           | 2400        | 0           | 120         | 1                  | 0                  | 2402               |
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

```

**Comment by seladb** [comment]
It looks like in both tests the device is opened with:
```cpp
dev->openMultiQueues(dev->getTotalNumOfRxQueues(), dev->getTotalNumOfTxQueues())
```

It looks like packets are not received on any of the open queues, but it worth making sure. Can you check, please?
Also, can you check how many queues are open? If it's more than one, maybe you can change it to one and see if the behavior changes

**Comment by cartman-156** [comment]
> Also, can you check how many queues are open? If it's more than one, maybe you can change it to one and see if the behavior changes

Changing the number of queues to 1 in tests file worked. All the tests are passing now. System was opening 16 queues for the port before the changes. Is there any way to send the traffic on particular queue? Because, as per my understanding the test is trying to receive the packets on queue id 0 for 20 seconds and if no traffic is received it gives error. However as you can see from my output of `DpdkExample-FilterTraffic`, queue 0 assigned to core 1 is not receiving any traffic at all. Irrespective of how much traffic I send.

**Comment by seladb** [comment]
Yes, the test assumes packets are received on queue id 0. Maybe we can consider changing the test so it starts with queue id 0 and iterates over the queues until it finds one where packets are captured?

**Comment by cartman-156** [comment]
Yes, that approach worked for number of attempts ASSERT. However, I again got ASSERT on number of packets received on all the queues at the end of test `TestDpdkDeviceWorkerThreads`. As per verbose output I can see it's only using assigning first 3 queues to 3 cores (I've 4 cores for my VM) and all the traffic is received on queue 12/13 which is not getting tracked and thus giving error as no packets received. I'll try to solve this if I can and update.

Thanks for all your help @seladb . I feel much wiser now thanks to you 👍  Happy new year!

**Comment by seladb** [comment]
thanks for the kind words @cartman-156 ! 
Would you consider opening a PR for the test fix we discussed?
Happy new year!

**Comment by cartman-156** [comment]
sure @seladb 
Happy to contribute.

**Comment by seladb** [comment]
Thank you so much for your contribution to this project, I really appreciate it!
