### ISSUE TITLE
Does pcapplusplus support MLX5 poll mode driver?

### ISSUE THREAD

**Issue by yh5** [seladb/PcapPlusPlus#557]
I am using MLNX_DPDK_16.11_3.0 & PcapPlusPlus: v17.11
NIC: Mellanox Technologies MT27800 Family [ConnectX-5]
I noticed that for mlx5, igb_uio is not used and do not have to be loaded to run DPDK.
However, the document mentioned that I have to use `./setup-dpdk.sh ` to set up pcapplusplus and it will bind with igb_uio.
```
$ ./tools/dpdk-devbind.py --status

Network devices using DPDK-compatible driver
============================================
0000:02:00.0 'MT27800 Family [ConnectX-5]' drv=igb_uio unused=mlx5_core,vfio-pci
0000:02:00.1 'MT27800 Family [ConnectX-5]' drv=igb_uio unused=mlx5_core,vfio-pci

Network devices using kernel driver
===================================
0000:05:00.0 'I350 Gigabit Network Connection' if=eno1 drv=igb unused=igb_uio,vfio-pci 
0000:05:00.1 'I350 Gigabit Network Connection' if=eno2 drv=igb unused=igb_uio,vfio-pci 
```
```
$ ./tools/dpdk-devbind.py --status

Network devices using DPDK-compatible driver
============================================
<none>

Network devices using kernel driver
===================================
0000:02:00.0 'MT27800 Family [ConnectX-5]' if=enp2s0f0 drv=mlx5_core unused=igb_uio,vfio-pci 
0000:02:00.1 'MT27800 Family [ConnectX-5]' if=enp2s0f1 drv=mlx5_core unused=igb_uio,vfio-pci 
0000:05:00.0 'I350 Gigabit Network Connection' if=eno1 drv=igb unused=igb_uio,vfio-pci 
0000:05:00.1 'I350 Gigabit Network Connection' if=eno2 drv=igb unused=igb_uio,vfio-pci 
```
I tried both settings above, the results are the same.
Whether I bind igb_uio or not, running DpdkTrafficFilter doesn't work.
```
$ sudo ./Examples/DpdkExample-FilterTraffic/Bin/DpdkTrafficFilter -l
EAL: Detected 32 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: PCI device 0000:05:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:05:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
Zero DPDK ports are initialized. Something went wrong while initializing DPDK
Zero DPDK ports are initialized. Something went wrong while initializing DPDK
Zero DPDK ports are initialized. Something went wrong while initializing DPDK
Application terminated in error: couldn't initialize DPDK
```
Does pcapplusplus support MLX5 poll mode driver? Or I have missed something?
Thanks!

**Comment by seladb** [comment]
I've never tried PcapPlusPlus with Mellanox DPDK so I don't know if it should work or not.
Also, you're using a very old version of PcapPlusPlus, would you consider upgrading to v20.08?

The error indicates something went wrong in this method:
https://github.com/seladb/PcapPlusPlus/blob/ea577d9cda23608671edfaef705eabc33de97273/Pcap%2B%2B/header/DpdkDeviceList.h#L127

Did you remember to run `DpdkDeviceList::initDpdk(...)` at the start of your program? Does it throw any error or returns `false`?

Also, did you follow all of the guidelines [here](https://pcapplusplus.github.io/docs/tutorials/dpdk)?

**Comment by seladb** [comment]
@yh5 have you had a chance to look at this? Please let me know

**Comment by yh5** [comment]
@seladb I tried v20.08 and it also has the same error.
Also, I am running the example code [DpdkExample-FilterTraffic](https://github.com/seladb/PcapPlusPlus/tree/master/Examples/DpdkExample-FilterTraffic), and it do run `DpdkDeviceList::initDpdk(...)`
It failed when running initDpdkDevices
https://github.com/seladb/PcapPlusPlus/blob/3977cd142500a03431397357bebf7f1d61be8ce8/Pcap%2B%2B/src/DpdkDeviceList.cpp#L163

Thanks.

**Comment by seladb** [comment]
It looks like loading `igb_uio` interferes with the MLX driver. For some reason DPDK tries to load the interfaces with `net_e1000_igb` instead of MLX. I'm not sure how the MLX driver works, do you know what is the process to load and init DPDK on MLX without PcapPlusPlus?

**Comment by yh5** [comment]
@seladb The main difference is that MLX5 doesn't need to bind to `igb_uio` driver. Alternatively, it uses MLNX_OFED firmware.
I can run DPDK without PcapPlusPlus with the setting below.
```
$ ./tools/dpdk-devbind.py --status

Network devices using DPDK-compatible driver
============================================
<none>

Network devices using kernel driver
===================================
0000:02:00.0 'MT27800 Family [ConnectX-5]' if=enp2s0f0 drv=mlx5_core unused=igb_uio,vfio-pci 
0000:02:00.1 'MT27800 Family [ConnectX-5]' if=enp2s0f1 drv=mlx5_core unused=igb_uio,vfio-pci 
0000:05:00.0 'I350 Gigabit Network Connection' if=eno1 drv=igb unused=igb_uio,vfio-pci 
0000:05:00.1 'I350 Gigabit Network Connection' if=eno2 drv=igb unused=igb_uio,vfio-pci 
```
Brief steps to run testpmd:
1. install MLNX_OFED
2. setup hugepages by `dpdk-setup.sh`
3. run testpmd 
`sudo ./x86_64-native-linuxapp-gcc/app/testpmd -c 0xff -n 4 -w 02:00.0 -w 02:00.1 -- --rxq=2 --txq=2 -i`

Some reference here:
[MLX5 poll mode driver](https://doc.dpdk.org/guides/nics/mlx5.html)
[mellanox-dpdk](https://community.mellanox.com/s/article/mellanox-dpdk)
Thanks.

**Comment by seladb** [comment]
Thanks for the information!
In the latest PcapPlusPlus version in `master` I've replaced the `setup-dpdk.sh` script with a new [`setup_dpdk.py`](https://github.com/seladb/PcapPlusPlus/blob/master/mk/setup_dpdk.py) python script that does everything [`dpdk-devbind`](https://doc.dpdk.org/guides/tools/devbind.html) is doing plus initializes hugepages, sets up the DPDK driver and more. You can read more about it [here](https://pcapplusplus.github.io/docs/dpdk#initialization-before-application-is-run).
I'll need your help to make this script work for MLX as well. As a first step I guess we'll need to allow the option not to load `igb_uio` or `uio_pci_generic`, is that correct? Which additional steps do we need to add to this script?

**Comment by seladb** [comment]
@yh5 did you have a chance to see my previous comment? Since I don't have access to MLX NIC I can't run tests myself so I'll need your help on this.

**Comment by yh5** [comment]
@seladb I didn't find the latest modified `setup_dpdk.py` in `master` branch?
I tried the latest commit and it still doesn't work.

**Comment by seladb** [comment]
The script is located here: https://github.com/seladb/PcapPlusPlus/blob/master/mk/setup_dpdk.py
But after you run `./configure-linux.sh` it should copy it to PcapPlusPlus root folder

**Comment by yh5** [comment]
The latest `setup_dpdk.py` still forces to bind with `igb_uio`.
However, I simply marked out `set_interfaces_down()`, `bind_interfaces()` in `setup_dpdk.py` and then run  `DpdkExample-FilterTraffic`. It still doesn't work. MLX may need more additional settings.

**Comment by seladb** [comment]
just to make sure - did you manage to successfully run the DPDK sample applications https://doc.dpdk.org/guides/sample_app_ug/index.html?

**Comment by seladb** [comment]
@yh5 let me know if you have the time to debug this issue and help solve it. Otherwise I think we can mark it as `wontfix` and close it as I don't have access to MLX NICs

**Comment by seladb** [comment]
@yh5 I marked this issue as `wontfix` and will close it for now. Please reopen if needed
