### ISSUE TITLE
Compile error for rte_mbuf.h: No such file or directory

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#558]
==== Building target: Pcap++ ====
Building file: src/PcapRemoteDeviceList.cpp
Building file: src/LinuxNicInformationSocket.cpp
Building file: src/MBufRawPacket.cpp
src/MBufRawPacket.cpp:8:10: fatal error: rte_mbuf.h: No such file or directory
    8 | #include "rte_mbuf.h

![image](https://user-images.githubusercontent.com/12936259/103738453-f7bcdf00-502e-11eb-862e-fd050b7a3562.png)

**Comment by seladb** [comment]
Can you please specify which DPDK and PcapPlusPlus versions you're using?

Also, did you follow the instructions [here](https://pcapplusplus.github.io/docs/dpdk) on how to install DPDK and configure PcapPlusPlus to work with DPDK?

**Comment by angelyouyou** [comment]
@seladb thanks very much. 
I used DPDK v18.11, just like the example in the blog and I follow the instruction of the source building guide steps.
https://pcapplusplus.github.io/docs/install/build-source/linux

**I attach some picture to describe this issue.**

![image](https://user-images.githubusercontent.com/12936259/103843616-1f658300-50d3-11eb-9f15-91fcbd098778.png)

![image](https://user-images.githubusercontent.com/12936259/103843721-4a4fd700-50d3-11eb-8394-2f098088d195.png)

![image](https://user-images.githubusercontent.com/12936259/103844037-fb567180-50d3-11eb-8e1a-a0963ceab26e.png)

**Comment by seladb** [comment]
Did you build DPDK before building PcapPlusPlus? If not, you need to build it first: https://pcapplusplus.github.io/docs/dpdk#download-and-install-dpdk
The reason I'm asking is because I don't see a `build/` directory under your DPDK directory.

also, what PcapPlusPlus version are you using?

**Comment by angelyouyou** [comment]
@seladb 

I'm using PcapPlusPlusv20.08, I will try to recompile the project according to your method.

Because there is no need to pre-compile dpdk in the Prerequisites chapter of Build From Source on Linux, I did not compile dpdk. I thought that ./configure-linux.sh would compile it automatically.

Thank you very much for your help. At the same time, it is recommended to add a description of DPDK pre-compilation in the Prerequisites chapter, which will help reduce the possibility of mistakes by novices like me.

**Comment by angelyouyou** [comment]
@seladb because I use dpdk-setup.sh* script in usertools directory of dpdk, there is no build directory create.

**Comment by seladb** [comment]
thanks for the feedback @angelyouyou !
I'm sorry the documentation mislead you, can you please help me understand what can be added?
Currently, there is this section in the documentation which instructs how to build DPDK:
![image](https://user-images.githubusercontent.com/9059541/103978936-7ac65e00-5131-11eb-8149-49677b133240.png)

Can you help me understand what is missing or how it can be improved?

Also, I'm not sure how the `dpdk-setup.sh` script works and where it puts the lib and header files. As of now, PcapPlusPlus assumes these files are under the `build/` directory. Maybe we can consider changing that in the future.

**Comment by angelyouyou** [comment]
@seladb 
Okay, thank you for your help. Let me analyze the difference between the script and the make tool before telling you.

So far, I have successfully compiled pcapplusplus, but when I run Packet++Test, I find that a large number of use cases have failed to execute. The failed information is as follows but the test files exist(see the picture below).
![image](https://user-images.githubusercontent.com/12936259/103979737-6463e500-51b9-11eb-8c80-eaed9655c961.png)
![image](https://user-images.githubusercontent.com/12936259/103979813-8b221b80-51b9-11eb-904b-640f8faa2b04.png)

**Comment by seladb** [comment]
You should run the tests from `Packet++Test` directory, not from the `Packet++Test/Bin` directory:

```shell
seladb@ubuntu2004:~/PcapPlusPlus/Tests/Packet++Test$ Bin/Packet++Test
```

This is mentioned here: https://pcapplusplus.github.io/docs/tests

![image](https://user-images.githubusercontent.com/9059541/103985514-ec0c0e00-513d-11eb-8978-c5d66353d46c.png)

**Comment by angelyouyou** [comment]
@seladb Thanks for your help, now my Packet++Test is passed.

**Comment by angelyouyou** [comment]
@seladb I built the Visual Studio 2019 version on my local PC, there was another issue. I think the [example ](https://pcapplusplus.github.io/docs/quickstart/vs#step-2---create-your-first-app)need to be updated.
![image](https://user-images.githubusercontent.com/12936259/104115907-3b755880-534f-11eb-9efd-e94b869e9a3e.png)

I found the include dirctory is '$(PcapPlusPlusHome)\header', but in the 'PcapPlusPlusPropertySheet.props' in the example is anther one.

Visual Studio 2019:
![image](https://user-images.githubusercontent.com/12936259/104115942-77a8b900-534f-11eb-8b23-a3b858fd7c46.png)

PcapPlusPlus:
![image](https://user-images.githubusercontent.com/12936259/104115983-af176580-534f-11eb-889d-7869e39e2ecd.png)
![image](https://user-images.githubusercontent.com/12936259/104116006-d837f600-534f-11eb-881b-2c49b403566f.png)

**Comment by seladb** [comment]
@angelyouyou I'm not sure I understand the issue. The `ExampleProject` is included as part of the release package and provides a template for users to get started more quickly. The [VS quickstart](https://pcapplusplus.github.io/docs/quickstart/vs) guide walks through the steps to get this example working. 
Please note this guide assumes you're using the [pre-built version](https://github.com/seladb/PcapPlusPlus/releases/download/v20.08/pcapplusplus-20.08-windows-vs2019.zip) that is included in the [release](https://github.com/seladb/PcapPlusPlus/releases/tag/v20.08) where you don't build PcapPlusPlus but use the DLLs provided in the package itself.
Please let me know if this answers your question.

**Comment by seladb** [comment]
@angelyouyou should we keep this issue open?

**Comment by seladb** [comment]
I'm closing the issue for now, please reopen if needed
