### ISSUE TITLE
Expose pcap_set_immediate_mode()

### ISSUE THREAD

**Issue by gpean** [seladb/PcapPlusPlus#56]
It would be nice if this setting was exposed. Sometimes you need to get to packets in the fastest way possible (assuming there is not a lot of them).

**Comment by gpean** [comment]
```
In immediate mode packets get delivered to the application as soon as they 
arrive, rather than after a timeout. This makes it very important for latency 
sensitive live captures. In my app this cuts the latency introduced by pcap 
from 2.5ms to 0.5ms.
```

(From https://github.com/google/gopacket/issues/36)

**Comment by seladb** [comment]
The problem is this API isn't exposed in WinPcap and also not in libpcap < 1.5.0. What do you suggest?

**Comment by gpean** [comment]
Hmm only expose if `-DHAS_PCAP_IMMEDIATE_MODE` i.e. if requested at
configure time?

**Comment by seladb** [comment]
That's a great idea. Would you mind doing this change and create a pull request?

**Comment by seladb** [comment]
Hi, I see you did a lot of changes in you branch. Do you have any plans to merge at least some of it back to master?

**Comment by gpean** [comment]
I would need to clean them up - Right now I'm pressured to finish a project and as a result, I have to make quick changes in more places, which wouldn't necessary be fit for all the users of this library. I'll do my best to give back, if I find the time. If you want to copy paste some targeted changes, feel free to do it too. Thanks...

**Comment by seladb** [comment]
Ok, I'll really appreciate if you find the time to merge some of the code back to master

**Comment by seladb** [comment]
Fixed by @f-squirrel (many thanks!)
