### ISSUE TITLE
There are no byteorder transform macros in SystemUtils.h on windows platform.

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#565]
There are no byteorder macros on windows platform.
![image](https://user-images.githubusercontent.com/12936259/104118778-6ae38f80-5366-11eb-9837-73fdc0b5ce28.png)

**Comment by seladb** [comment]
You're absoultly right, I introduced these changes after the latest release: https://github.com/seladb/PcapPlusPlus/commit/aaf8d0a589ec2e40224804ee1257201b7d82ca34

The release happened in August 2020 and these changes were made in October 2020. They will be included in the next release

**Comment by seladb** [comment]
I'm closing the issue for now, please open if still relevant
