### ISSUE TITLE
multiple capture threads on a single device

### ISSUE THREAD

**Issue by weyrick** [seladb/PcapPlusPlus#567]
Hello, I understand that currently only one capture thread is allowed per device. I'd like to understand why this limitation exists, as I'm interested in removing it if possible. The use case is to allow capture threads with different bpf filters per thread, so that filtering happens in the kernel rather than having to manually filter in userspace.

Is the limitation only due to the current implementation of a singleton representing devices once per process, with a single thread each, or is there a deeper technical issue?

Thanks!

**Comment by seladb** [comment]
I'm not sure libpcap/WinPcap support the option to open the same device twice on two different threads and capture packets simultaneously on both of them. I don't think I've tried that though, so it might worth a shot. If you give it a try please let me know and we can figure out how to enable more that one thread per device.

**Comment by weyrick** [comment]
I see, even just doing a little googling I can see that libpcap does not support multiple threads on the same device. On a related note then, would you consider adding support for capturing with AF_PACKET in Linux to the library, even though it is not portable to the other platforms? Or would you like to keep all capture methods available on all platforms in the library?

**Comment by weyrick** [comment]
I suppose since DPDK and PF_RING are also linux only it should be ok. In fact it might be a good alternative to PF_RING that doesn't require a custom kernel module. Ok thanks I will close this for now as I investigate possibilities.
