### ISSUE TITLE
Can we support the specification of operating parameters based on json or yaml format for DPDK mode? 

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#569]
Since DPDK has a large number of parameters that need to be specified in the code when it is started (such as the number of RX/TX queues, ports, thread binding, etc.), this will cause a lot of repeated code and lack of flexibility during initialization. Can we support the specification of operating parameters based on json or yaml format for DPDK mode? I think this is a nice enhancement.

**Comment by seladb** [comment]
Thanks for the suggestion! Can you please clarify what you mean? We already have the `DpdkDeviceConfiguration` struct that has all the configuration and you can use it within the code. How can json/yaml help here?
https://github.com/seladb/PcapPlusPlus/blob/c231dbefc8060d865e7e54af7bb27c280182ba6e/Pcap%2B%2B/header/DpdkDevice.h#L223

**Comment by angelyouyou** [comment]
@seladb 
The current DpdkDevice.h based on DPDK has described the parameters and attributes of the device well, but it does not have the ability to modify at runtime. For example, when you want to dynamically adjust parameters such as threads and ports but do not want to recompile the program, it cannot be achieved without a configuration file-based approach.

Is it possible to read these settings based on json or yaml configuration files, and block these trivial and repetitive (different DPDK applications) code fragments through, for example, C language macros or functions, similar to the entry of macros and functions like Microsoft's MFC. I think this is very helpful to further reduce the user's threshold and complexity.

![image](https://user-images.githubusercontent.com/12936259/104839763-3b043100-58fe-11eb-86c6-1cff9c4c937e.png)

**Comment by seladb** [comment]
That's an interesting suggestion!
This is more of an application-level framework that can sit on top of DpdkDevice and abstract some of the code there.
I currently don't have plans to write such a framework but I invite you to write one and contribute it back to PcapPlusPlus. We can discuss how to design and implement it.

**Comment by seladb** [comment]
I'm closing this issue now. If you plan to build such a framework please let me know and I can help you design it.
