### ISSUE TITLE
The link type 228 is not supported?

### ISSUE THREAD

**Issue by abdolahsa** [seladb/PcapPlusPlus#57]
cannot open fileReaderDevice for filename ... the link type 228 is not supported. how can I resolve it?

**Comment by seladb** [comment]
Indeed, link type 228 is not supported. But you can add it quite easily:
- In [Packet.cpp](https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/src/Packet.cpp#L66) you should add this link type to be able to parse packets with this link type
- 2 changes in PcapFileDevice.cpp:
  - Add support in [PcapFileReaderDevice](https://github.com/seladb/PcapPlusPlus/blob/master/Pcap%2B%2B/src/PcapFileDevice.cpp#L130)
  - Add support in [PcapFileWriterDevice](https://github.com/seladb/PcapPlusPlus/blob/master/Pcap%2B%2B/src/PcapFileDevice.cpp#L508)
- Test your changes and add a unit-test to [Pcap++Test](https://github.com/seladb/PcapPlusPlus/blob/master/Tests/Pcap%2B%2BTest/main.cpp#L4357) - the test should be quite similar to the existing [TestPcapSllFileReadWrite](https://github.com/seladb/PcapPlusPlus/blob/master/Tests/Pcap%2B%2BTest/main.cpp#L706) test

That's it... Could you please do these changes for both link-types 228 and 229 and submit a pull request?

**Comment by seladb** [comment]
Hi @abdolahsa , do you intend to fix that issue and submit a pull request?
If not, please provide pcap file as an example and I'll do that fix

**Comment by seladb** [comment]
Since I didn't get your response and I don't have pcap examples to test it myself I'm closing this issue for now. 
Please feel free to reopen it when you have pcap examples or when you have the time to fix this yourself (and issue a pull request)
