### ISSUE TITLE
Hopeful to add netflow, sflow protocol support.

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#570]
I am planning to add protocols such as netflow, sflow, ipfix to the current PcapPlusPlus, which is very helpful in many detection areas.

**Comment by seladb** [comment]
Sure, that'd be great!!
Please let me know if you need any help in adding new protocol to PcapPlusPlus

**Comment by angelyouyou** [comment]
@seladb 
Okay, if you have any questions, I will ask you, thank you.

**Comment by angelyouyou** [comment]
@seladb Can I add one protocol with pcapplusplus-20.08-windows-vs2019?

**Comment by seladb** [comment]
what do you mean by adding a protocol with `pcapplusplus-20.08-windows-vs2019`?

**Comment by seladb** [comment]
@angelyouyou is this issue still relevant? should we keep it open?

**Comment by seladb** [comment]
Let me close this issue for now, please reopen if relevant
