### ISSUE TITLE
Have we considered porting the project to vpp? 

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#572]
There are many protocols supported in VPP(FD.io), and it has complete host protocol stack support.

**Comment by seladb** [comment]
I'm not familiar with VPP and I'm not sure what you mean by porting the project to VPP, can you please elaborate?

**Comment by seladb** [comment]
Did you have a chance to see my previous comment/question?

**Comment by seladb** [comment]
I'm closing this issue for now, please reopen if relevant
