### ISSUE TITLE
integrate with dpdk19.11

### ISSUE THREAD

**Issue by mohammadMighani** [seladb/PcapPlusPlus#574]
Hi I am trying to integrate pcapplusplus with dpdk
according to documentation run the following command:
./configure-linux.sh 

****************************************
PcapPlusPlus Linux configuration script 
****************************************

Number of arguments: 0

Compile PcapPlusPlus with PF_RING? n
Compile PcapPlusPlus with DPDK? y
Enter DPDK source path: /root/dpdk
grep: /root/dpdk/pkg/dpdk.spec: No such file or directory

I try on dpdk19.11 and dpdk19.08 and dpdk 19.02.

do I miss something or pcap doesn't support these versions?

**Comment by seladb** [comment]
PcapPlusPlus should support these versions. Did you build DPDK itself before running configure-linux.sh?

**Comment by mohammadMighani** [comment]
For Assurance, a few minutes ago I built dpdk 19.11 with this command:
_make config T=x86_64-native-linux-gcc  && make_
and still, there is no pkg directory

**Comment by seladb** [comment]
I forgot to ask - which version of PcapPlusPlus are you using?

**Comment by mohammadMighani** [comment]
I used this file:
https://github.com/seladb/PcapPlusPlus/archive/v20.08.zip

**Comment by seladb** [comment]
Ok I figured out what's the issue. You're using the latest release (v20.08) which has a bug in `configure-linux.sh`. I fixed this bug in commit https://github.com/seladb/PcapPlusPlus/commit/b634b953dbbd7625cabf219a868627339a4d3f39
If you can use the latest version from `master` this issue should be resolved.

**Comment by mohammadMighani** [comment]
Thanks. The problem solved, I tested it with DPDK 19.11
