### ISSUE TITLE
TcpLayer: getSrcPort() getDstPort() missing

### ISSUE THREAD

**Issue by neoxic** [seladb/PcapPlusPlus#578]
Hi,

Following your [Tutorial](https://pcapplusplus.github.io/docs/tutorials/packet-parsing), I can't get the following snippet to compile:

```C++
cout << "Source port: " << tcp->getSrcPort() << endl;
cout << "Destination port: " << tcp->getDstPort() << endl;
```

The tutorial is apparently outdated because instead of `getPortSrc()` and `getPortDst()` (tutorial), the [Reference](https://pcapplusplus.github.io/api-docs/classpcpp_1_1_tcp_layer.html) mentions `getSrcPort()` and `getDstPort()` respectively. But surprisingly, those two are not present either:

```
test-pcap.cpp: In function ‘bool callback(pcpp::RawPacket*, pcpp::PcapLiveDevice*, void*)’:
test-pcap.cpp:19:34: error: ‘class pcpp::TcpLayer’ has no member named ‘getSrcPort’
  cout << "Source port: " << tcp->getSrcPort() << endl;
                                  ^
test-pcap.cpp:20:39: error: ‘class pcpp::TcpLayer’ has no member named ‘getDstPort’
  cout << "Destination port: " << tcp->getDstPort() << endl;
```

I checked the headers - no such methods defined indeed. Are the tutorial and the reference both misleading, or am I missing something?

Downloaded here: https://github.com/seladb/PcapPlusPlus/releases/download/v20.08/pcapplusplus-20.08-centos-7-gcc-4.8.5.tar.gz

**Comment by neoxic** [comment]
I can also see that pkg-config fails to find the libraries when installed at a non-standard location. Note that the headers work fine.

```
gcc $(PKG_CONFIG_PATH=/home/neoxic/local/lib/pkgconfig pkg-config PcapPlusPlus --cflags --libs) test-pcap.cpp -o test-pcap
```
```
/usr/bin/ld: cannot find -lPcap++
/usr/bin/ld: cannot find -lPacket++
/usr/bin/ld: cannot find -lCommon++
collect2: error: ld returned 1 exit status
```

**Comment by neoxic** [comment]
Ok, I can see now that these methods have not been released yet. I guess looking into the tutorial will make no sense for some time. Closing...

**Comment by seladb** [comment]
Yes, this is a new feature that is available in the `master` branch. It will be included in the next release.
Please note that `master` is always considered stable so feel free to use it.
