### ISSUE TITLE
Centos 7 linking problem

### ISSUE THREAD

**Issue by neoxic** [seladb/PcapPlusPlus#579]
Withe the [latest binaries](https://github.com/seladb/PcapPlusPlus/releases/download/v20.08/pcapplusplus-20.08-centos-7-gcc-4.8.5.tar.gz) for Centos 7, I get the following with a local installation prefix:
```
$ g++ $(PKG_CONFIG_PATH=~/local/lib/pkgconfig pkg-config PcapPlusPlus --cflags --libs) test-pcap.cpp
/usr/bin/ld: cannot find -lPcap++
/usr/bin/ld: cannot find -lPacket++
/usr/bin/ld: cannot find -lCommon++
collect2: error: ld returned 1 exit status
```
So the linker can't find the libraries while the headers are found no problem. But after adding the path explicitly and attemting to compile the following simple code, I get undefined references:
```C++
#include "PcapLiveDeviceList.h"

int main(int argc, char* argv[]) {
    pcpp::PcapLiveDevice* dev = pcpp::PcapLiveDeviceList::getInstance().getPcapLiveDeviceByIp("127.0.0.1");
    return 0;
}
```
```
$ g++ $(PKG_CONFIG_PATH=~/local/lib/pkgconfig pkg-config PcapPlusPlus --cflags --libs) test-pcap.cpp -L ~/local/lib
/tmp/cc3shRKG.o: In function `main':
test-pcap.cpp:(.text+0x4a): undefined reference to `pcpp::PcapLiveDeviceList::getPcapLiveDeviceByIp(std::string const&) const'
/tmp/cc3shRKG.o: In function `pcpp::PcapLiveDeviceList::getInstance()':
test-pcap.cpp:(.text._ZN4pcpp18PcapLiveDeviceList11getInstanceEv[_ZN4pcpp18PcapLiveDeviceList11getInstanceEv]+0x32): undefined reference to `pcpp::PcapLiveDeviceList::PcapLiveDeviceList()'
test-pcap.cpp:(.text._ZN4pcpp18PcapLiveDeviceList11getInstanceEv[_ZN4pcpp18PcapLiveDeviceList11getInstanceEv]+0x4b): undefined reference to `pcpp::PcapLiveDeviceList::~PcapLiveDeviceList()'
collect2: error: ld returned 1 exit status
```

What am I doing wrong?

**Comment by seladb** [comment]
hi, thanks for reaching out!
Did you run the `./install.sh` script that is provided with the installation package? This script copies the binaries and header files to `/usr/local`. 
As a first step I'd recommend going through the [quick start guide](https://pcapplusplus.github.io/docs/quickstart/linux) and see if it works. Then you can use the `Makefile` and source files provided in the example app to create your own app.

Please let me know if you have more questions.

**Comment by neoxic** [comment]
My primary goal was to cut the corners and avoid building from source.

First of all, the provided [archive](https://github.com/seladb/PcapPlusPlus/releases/download/v20.08/pcapplusplus-20.08-centos-7-gcc-4.8.5.tar.gz) is not recognized in CentOS 7:
```
$ cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
$ tar xzf pcapplusplus-20.08-centos-7-gcc-4.8.5.tar.gz
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```
Trying different compression types didn't work either. I also tried the above in Arch Linux with no luck. Eventually, I managed to unpack the archive in MacOS. Not sure what's going on here. How do you make your tar balls?

Yes, I ran `./install.sh`. When installing to the default location, i.e. `/usr/local`, all looks good, but only on the surface. When changing `INSTALL_DIR=~/local` to install to a user's local path, things start falling apart:
```
$ mcedit install.sh
$ grep ^INSTALL_DIR install.sh
INSTALL_DIR=~/local
$ ./install.sh
$ cd example-app
$ g++ main.cpp $(PKG_CONFIG_PATH=~/local/lib/pkgconfig pkg-config PcapPlusPlus --cflags --libs)
/usr/bin/ld: cannot find -lPcap++
/usr/bin/ld: cannot find -lPacket++
/usr/bin/ld: cannot find -lCommon++
collect2: error: ld returned 1 exit status
```
Ok, the same problem - the linker can't find the libraries. Let's look at the pkg-config file:
```
$ cat ~/local/lib/pkgconfig/PcapPlusPlus.pc
prefix=/home/seny/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: PcapPlusPlus
Description: a multiplatform C++ network sniffing and packet parsing and crafting framework. It is meant to be lightweight, efficient and easy to use
Version: 20.08
URL: https://pcapplusplus.github.io
Libs: -lPcap++ -lPacket++ -lCommon++ -lpcap -lpthread
CFlags: -I/home/seny/local/include/pcapplusplus -I/usr/include/netinet
```
Two problems here:
1. `libdir` and `includedir` are defined, but never used.
2. `Libs:` doesn't have an `-L` option.

Fixing the above to look like this:
```
...
Libs: -L${libdir} -lPcap++ -lPacket++ -lCommon++ -lpcap -lpthread
CFlags: -I${includedir}/pcapplusplus -I/usr/include/netinet
```
fixes the initial issue:
```
$ g++ main.cpp $(PKG_CONFIG_PATH=~/local/lib/pkgconfig pkg-config PcapPlusPlus --cflags --libs)
$
```

Hope that helps. With best wishes to your project.

**Comment by neoxic** [comment]
For libraries, it is important to make sure a library can be built and used in a non-standard location. Not everybody is comfortable installing third-party stuff system-wide. As a rule of thumb, I always build and install in an unprivileged user's home location.

**Comment by seladb** [comment]
That's a very good point, thanks for reporting this issue!
The bug is in this script which creates `PcapPlusPlus.pc`: https://github.com/seladb/PcapPlusPlus/blob/master/mk/install.sh.template#L42-L44

Would you consider making a fix and open a PR?

**Comment by neoxic** [comment]
I just made a report of what I had encountered briefly coming across your project, so it's up to you now. I ended up using libpcap directly.

**Comment by seladb** [comment]
@neoxic thanks for reporting this issue!
I've fixed one issue here: https://github.com/seladb/PcapPlusPlus/commit/954ce17c917f7fe47284314f59fbce4e72c53a6d
The other issue was already fixed by @weyrick in this revision https://github.com/seladb/PcapPlusPlus/commit/9556458f3a5d45acc6d9e37eae830f29807e782b
