### ISSUE TITLE
Why is PCPP parsing DNS with parseUntil=TCP and parseUntilLayer=Transport?

### ISSUE THREAD

**Issue by ganleynovetta** [seladb/PcapPlusPlus#580]
I started using PCPP for the first time today - great library! I expect to get a lot of use out of it, and hopefully contribute as well.

Now... I am parsing raw packets like this:

`const pcpp::Packet pp(&rp, false, pcpp::TCP, pcpp::OsiModelTransportLayer)`  // rp is RawPacket

I am getting `DNS layer contains more than 300 resources` warnings, which I see come from the `DnsLayer` code.

My question is, why is the DNS layer getting parsed at all when I have parseUntil and parseUntilLayer set to TCP/layer 4?

I can dive in and try to debug this myself, but first wanted to make sure I'm not just misunderstanding something.

**Comment by seladb** [comment]
thanks @ganleynovetta for reaching out!

DNS usually uses UDP and not TCP so you should probably put `pcpp::UDP` instead of `pcpp::TCP`. 
I have tried reproducing this issue in my local environment but couldn't. Can you please try adding these lines of code:
```cpp
if (pp.isPacketOfType(pcpp::DNS))
	printf("PACKET IS OF TYPE DNS\n");
```
And let me know what is the output?
If the issue still persists it'd help if you can share the exact code and pcap file that reproduces this issue.

**Comment by ganleynovetta** [comment]
That makes sense. If I'm only interested in something from the TCP layer, is there any way to say "parse until TCP, or until you know this isn't a TCP packet"?

And is it possible to suppress or reroute those warning messages?

**Comment by ganleynovetta** [comment]
Never mind, I figured out how to suppress them.

**Comment by seladb** [comment]
> is there any way to say "parse until TCP, or until you know this isn't a TCP packet"?

Unfortunately there isn't a good way to know that this is not a TCP packet before parsing the whole packet. But you can use `pcpp::OsiModelTransportLayer` which will parse only up to the transport layer (TCP, UDP, etc.)

I'm closing this issue now, please reopen it if needed.
