### ISSUE TITLE
/usr/bin/ld: cannot find -librte_pmd_bond

### ISSUE THREAD

**Issue by behzad-kh** [seladb/PcapPlusPlus#585]
hi all
When I was trying to install the PCAPPLUSPLUS, the following error is shown:
![image](https://user-images.githubusercontent.com/24776390/107439481-5fdb7500-6b47-11eb-9d97-79591a8aa4fc.png)
It worth mentioning that I have complied the DPDK (19.11.6) already.
I have instructed to use DPDK with the following command.
![image](https://user-images.githubusercontent.com/24776390/107439519-708beb00-6b47-11eb-9cc9-b13e2e695b9a.png)
However, the Dist directory does not include the required files:
![image](https://user-images.githubusercontent.com/24776390/107439660-a16c2000-6b47-11eb-8322-2f0ace5e4209.png)

any help is much appreciated.

**Comment by vipinpv85** [comment]
Looks like libPcap and LibPacket is looking for DPDK shared library to link too. That is for pcaptest application you have passed `USE_DPDK`` to trigger DPDK based built

```
ifdef USE_DPDK
DEPS += -DUSE_DPDK
endif
```

But I am not able to find `DPDK_CFLAGS` or `DPDK_LIBS` passed in [makefile](https://github.com/seladb/PcapPlusPlus/blob/master/Tests/Pcap%2B%2BTest/Makefile). Since it is makefile can you try passing `CFLAGS=[DPDK cflags] LDFLAGS=[DPDK LDFLAGS] make `?

**Comment by seladb** [comment]
@behzad-kh you should provide `configure-linux.sh` the home directory of DPDK, for example:

```shell
./configure-linux.sh --dpdk --dpdk-home /root/dpdk-stable-19.11.6
```

**Comment by seladb** [comment]
@vipinpv85 I'm not sure what you mean by `DPDK_CFLAGS` and `DPDK_LIBS`.
The Pcap++Test uses `PCAPPP_BUILD_FLAGS`, `PCAPPP_INCLUDES` and `PCAPPP_LIBS_DIR` which include all the libraries, header files and build flags required to build it.

Those variables are imported from `mk/PcapPlusPlus.mk` which is created during the configuration process (i.e when running `configure-linux.sh`)

**Comment by behzad-kh** [comment]
> 
> 
> @behzad-kh you should provide `configure-linux.sh` the home directory of DPDK, for example:
> 
> ```shell
> ./configure-linux.sh --dpdk --dpdk-home /root/dpdk-stable-19.11.6
> ```

![image](https://user-images.githubusercontent.com/24776390/107486642-85459e80-6b9a-11eb-986a-868ed75d77fa.png)
![image](https://user-images.githubusercontent.com/24776390/107486663-8c6cac80-6b9a-11eb-9d56-050c3835025b.png)
thanks for you responses.
The error is not fixed by changing the DPDK-home
![image](https://user-images.githubusercontent.com/24776390/107486792-b1f9b600-6b9a-11eb-9488-21f2a0db7ebe.png)

**Comment by behzad-kh** [comment]
> LDFLAGS

![image](https://user-images.githubusercontent.com/24776390/107487453-6b588b80-6b9b-11eb-970f-19e501e29e6a.png)

**Comment by vipinpv85** [comment]
> @vipinpv85 I'm not sure what you mean by `DPDK_CFLAGS` and `DPDK_LIBS`.
> The Pcap++Test uses `PCAPPP_BUILD_FLAGS`, `PCAPPP_INCLUDES` and `PCAPPP_LIBS_DIR` which include all the libraries, header files and build flags required to build it.
> 
> Those variables are imported from `mk/PcapPlusPlus.mk` which is created during the configuration process (i.e when running `configure-linux.sh`)

@seladb as I have already pointed, the possible reason why `ld` is unable to link with DPDK libraries is that it has not found the DPDK libraries and Cflags in the desired PATH. For a x86_64 platform DPDK_CFLAGS are `-include rte_config.h -march=native -I/usr/local/include` and LDFLAGS are `-L/usr/local/lib/x86_64-linux-gnu -Wl,--as-needed -lrte_node -lrte_graph -lrte_bpf -lrte_flow_classify -lrte_pipeline -lrte_table -lrte_port -lrte_fib -lrte_ipsec -lrte_vhost -lrte_stack -lrte_security -lrte_sched -lrte_reorder -lrte_rib -lrte_regexdev -lrte_rawdev -lrte_pdump -lrte_power -lrte_member -lrte_lpm -lrte_latencystats -lrte_kni -lrte_jobstats -lrte_ip_frag -lrte_gso -lrte_gro -lrte_eventdev -lrte_efd -lrte_distributor -lrte_cryptodev -lrte_compressdev -lrte_cfgfile -lrte_bitratestats -lrte_bbdev -lrte_acl -lrte_timer -lrte_hash -lrte_metrics -lrte_cmdline -lrte_pci -lrte_ethdev -lrte_meter -lrte_net -lrte_mbuf -lrte_mempool -lrte_rcu -lrte_ring -lrte_eal -lrte_telemetry -lrte_kvargs`

Since @behzad-kh has not mentioned whether he uses DPDK or not, I have pointed out, PacketTest 

1. if built with `./configure-linux.sh --dpdk --dpdk-home /root/dpdk-stable-19.11.6` will use  `-DUSE_DPDK` is expecting DPDK libraries. 
2. if PacketTest is only configured using `./configure-linux.sh` it will not be using `-DUSE_DPDK` DPDK dependency.  

note: 
 - So quick dirty test to pass DPDK cflags and LDFLAGS to make command, if this solves (Assuming @behzad-kh has used for DPDK) there is something wrong in configuration or path.
 - I have checked `configure-linux.sh`, There it picks up DPDK_HOME as RTE_SDK. But there is no mention of RTE_TARGET. 
 - RTE_TARGET can be inside RTE_SDK or it can be placed in any desired folder. 

I can only address DPDK related linking and issue,  while @seladb you will have more insights into these are you are the maintainer and project.

**Comment by behzad-kh** [comment]
> 
> 
> > @behzad-kh you should provide `configure-linux.sh` the home directory of DPDK, for example:
> > ```shell
> > ./configure-linux.sh --dpdk --dpdk-home /root/dpdk-stable-19.11.6
> > ```
> 
> ![image](https://user-images.githubusercontent.com/24776390/107486642-85459e80-6b9a-11eb-986a-868ed75d77fa.png)
> ![image](https://user-images.githubusercontent.com/24776390/107486663-8c6cac80-6b9a-11eb-9d56-050c3835025b.png)
> thanks for you responses.
> The error is not fixed by changing the DPDK-home
> ![image](https://user-images.githubusercontent.com/24776390/107486792-b1f9b600-6b9a-11eb-9488-21f2a0db7ebe.png)

@seladb It worth mentioning that I have change the lrte-*.a file to librte-*.a file in the make file as the librte libraries are compiled by the DPDK.
And I am running the PCAPPLUSPLUS with DPDK on the Ubuntu 20.0.4
![image](https://user-images.githubusercontent.com/24776390/107487715-b6729e80-6b9b-11eb-9a9c-ddf90d1fcad4.png)

**Comment by behzad-kh** [comment]
> 
> 
> > @vipinpv85 I'm not sure what you mean by `DPDK_CFLAGS` and `DPDK_LIBS`.
> > The Pcap++Test uses `PCAPPP_BUILD_FLAGS`, `PCAPPP_INCLUDES` and `PCAPPP_LIBS_DIR` which include all the libraries, header files and build flags required to build it.
> > Those variables are imported from `mk/PcapPlusPlus.mk` which is created during the configuration process (i.e when running `configure-linux.sh`)
> 
> @seladb as I have already pointed, the possible reason why `ld` is unable to link with DPDK libraries is that it has not found the DPDK libraries and Cflags in the desired PATH. For a x86_64 platform DPDK_CFLAGS are `-include rte_config.h -march=native -I/usr/local/include` and LDFLAGS are `-L/usr/local/lib/x86_64-linux-gnu -Wl,--as-needed -lrte_node -lrte_graph -lrte_bpf -lrte_flow_classify -lrte_pipeline -lrte_table -lrte_port -lrte_fib -lrte_ipsec -lrte_vhost -lrte_stack -lrte_security -lrte_sched -lrte_reorder -lrte_rib -lrte_regexdev -lrte_rawdev -lrte_pdump -lrte_power -lrte_member -lrte_lpm -lrte_latencystats -lrte_kni -lrte_jobstats -lrte_ip_frag -lrte_gso -lrte_gro -lrte_eventdev -lrte_efd -lrte_distributor -lrte_cryptodev -lrte_compressdev -lrte_cfgfile -lrte_bitratestats -lrte_bbdev -lrte_acl -lrte_timer -lrte_hash -lrte_metrics -lrte_cmdline -lrte_pci -lrte_ethdev -lrte_meter -lrte_net -lrte_mbuf -lrte_mempool -lrte_rcu -lrte_ring -lrte_eal -lrte_telemetry -lrte_kvargs`
> 
> Since @behzad-kh has not mentioned whether he uses DPDK or not, I have pointed out, PacketTest
> 
>     1. if built with `./configure-linux.sh --dpdk --dpdk-home /root/dpdk-stable-19.11.6` will use  `-DUSE_DPDK` is expecting DPDK libraries.
> 
>     2. if PacketTest is only configured using `./configure-linux.sh` it will not be using `-DUSE_DPDK` DPDK dependency.
> 
> 
> note:
> 
>     * So quick dirty test to pass DPDK cflags and LDFLAGS to make command, if this solves (Assuming @behzad-kh has used for DPDK) there is something wrong in configuration or path.
> 
>     * I have checked `configure-linux.sh`, There it picks up DPDK_HOME as RTE_SDK. But there is no mention of RTE_TARGET.
> 
>     * RTE_TARGET can be inside RTE_SDK or it can be placed in any desired folder.
> 
> 
> I can only address DPDK related linking and issue, while @seladb you will have more insights into these are you are the maintainer and project.

I am trying to integrate the PCAPPLUSPLUS with DPDK
![image](https://user-images.githubusercontent.com/24776390/107488107-284ae800-6b9c-11eb-85c9-12c9c909d415.png)

**Comment by seladb** [comment]
@behzad-kh did you build DPDK as instructed here: https://pcapplusplus.github.io/docs/dpdk#download-and-install-dpdk ?

**Comment by behzad-kh** [comment]
> 
> 
> @behzad-kh did you build DPDK as instructed here: https://pcapplusplus.github.io/docs/dpdk#download-and-install-dpdk ?

yes

**Comment by behzad-kh** [comment]
> 
> 
> > @behzad-kh did you build DPDK as instructed here: https://pcapplusplus.github.io/docs/dpdk#download-and-install-dpdk ?
> 
> yes

![image](https://user-images.githubusercontent.com/24776390/107488476-a60ef380-6b9c-11eb-8a76-d5cb23a6ae31.png)
I'm running it one more time

**Comment by seladb** [comment]
Can you please paste the content of `mk/PcapPlusPlus.mk`?

Also, can you paste the content of the following directories:
`ll /root/dpdk-stable-19.11.6/build/lib`
`ll /root/dpdk-stable-19.11.6/build/include`

**Comment by behzad-kh** [comment]
> 
> 
> Can you please paste the content of `mk/PcapPlusPlus.mk`?
> 
> Also, can you paste the content of the following directories:
> `ll /root/dpdk-stable-19.11.6/build/lib`
> `ll /root/dpdk-stable-19.11.6/build/include`

content of PcapplusPlus.mk
https://paste.ubuntu.com/p/kNkMXHzYv4/
content of  ll /root/dpdk-stable-19.11.6/build/lib
https://paste.ubuntu.com/p/Bd69XxyNJS/
content of  ll /root/dpdk-stable-19.11.6/build/include
https://paste.ubuntu.com/p/m846MmXJ9V/

**Comment by behzad-kh** [comment]
> 
> 
> > Can you please paste the content of `mk/PcapPlusPlus.mk`?
> > Also, can you paste the content of the following directories:
> > `ll /root/dpdk-stable-19.11.6/build/lib`
> > `ll /root/dpdk-stable-19.11.6/build/include`
> 
> content of PcapplusPlus.mk
> https://paste.ubuntu.com/p/kNkMXHzYv4/
> content of ll /root/dpdk-stable-19.11.6/build/lib
> https://paste.ubuntu.com/p/Bd69XxyNJS/
> content of ll /root/dpdk-stable-19.11.6/build/include
> https://paste.ubuntu.com/p/m846MmXJ9V/
> 
> The files are also attached.
> 
> [files.zip](https://github.com/seladb/PcapPlusPlus/files/5957068/files.zip)

![image](https://user-images.githubusercontent.com/24776390/107493532-f7ba7c80-6ba2-11eb-94a0-fc4139f25391.png)

**Comment by seladb** [comment]
it's weird, some of the files are there and some aren't. For example: `librte_pmd_bond.a` is there but `librte_pmd_vmxnet3_uio.a` isn't.
In my local DPDK repo I see all the files. Can you download DPDK again and make a fresh install?

**Comment by behzad-kh** [comment]
> librte_pmd_vmxnet3_uio

![image](https://user-images.githubusercontent.com/24776390/107496359-72d16200-6ba6-11eb-8abf-1e368223f01c.png)
the librte_pmd_vmxnet3_uio.a is also there.
thanks I will try it one more time.

**Comment by behzad-kh** [comment]
> 
> 
> > librte_pmd_vmxnet3_uio
> 
> ![image](https://user-images.githubusercontent.com/24776390/107496359-72d16200-6ba6-11eb-8abf-1e368223f01c.png)
> I have made a fresh DPDK make install, but no progress
> as you can see the files librte_pmd_vmxnet3_uio is there.
> content of ll /root/dpdk-stable-19.11.6/build/lib ==> after fresh make
> https://paste.ubuntu.com/p/8ZddVddnpT/
> content of ll /root/dpdk-stable-19.11.6/build/include ==> after fresh make
> https://paste.ubuntu.com/p/Xf5HVbjbPk/

I believe there might be some sort of permission issues (I have checked and all of them have read access at least) and I'm making the file with the root user.
Another possibility might be the Pcapplusplus.mk file that the Lib64 is not right (just a thought)

**Comment by seladb** [comment]
Yes, that might be the case. Maybe you can try installing DPDK and PcapPlusPlus on a non root user?

**Comment by behzad-kh** [comment]
> 
> 
> Yes, that might be the case. Maybe you can try installing DPDK and PcapPlusPlus on a non root user?

The problem is resolved.
The root cause was that I was trying to make the PcapPlusPlus with root user. As I make the DPDK and the Pcapplusplus with non-root user, the make process is done with no error.
I would like to thanks @seladb for your time and support and also @vipinpv85 .

**Comment by vipinpv85** [comment]
> As I make the DPDK and the Pcapplusplus with non-root user, the make process is done with no error.

good to hear your problem is solved. I am able to build the project both with root and non root user in my system without any issues.
