### ISSUE TITLE
error: invalid new-expression of abstract class type â€˜L2FwdWorkerThreadâ€™

### ISSUE THREAD

**Issue by behzad-kh** [seladb/PcapPlusPlus#586]
Hi
When I was trying to compile the Tutorial-DpdkL2Fwd, the following error message is shown:
![image](https://user-images.githubusercontent.com/24776390/107526191-d79fb300-6bcc-11eb-980e-f83245351b06.png)
Here are the DPDK interfaces:
![image](https://user-images.githubusercontent.com/24776390/107526267-eb4b1980-6bcc-11eb-8159-99f22d4e7998.png)

**Comment by seladb** [comment]
That's indeed a bug in the tutorial, thanks for reporting it!
There's a missing `const` in `L2FwdWorkerThread::getCoreId()`. I'm fixing it and will soon merge to `master`

**Comment by behzad-kh** [comment]
> 
> 
> That's indeed a bug in the tutorial, thanks for reporting it!
> There's a missing `const` in `L2FwdWorkerThread::getCoreId()`. I'm fixing it and will soon merge to `master`

thank you.
the problem is resolved.
