### ISSUE TITLE
UDP checksum calculation should flip 0x0000 to 0xFFFF

### ISSUE THREAD

**Issue by inspire1989** [seladb/PcapPlusPlus#588]
Hi!
We found a bug with the UDP checksum calculation in the UdpLayer::calculateChecksum method. [RFC 768](https://tools.ietf.org/html/rfc768) states 

> If the computed checksum is zero, it is transmitted as all ones (the equivalent in one's complement arithmetic).

However, the calculateChecksum method lacks this check/functionality. We saw packets in Wireshark with the checksum 0x0000 where Wireshark complained this checksum would be "illegal". Also, our software that is supposed to receive the packet never got it because the Linux kernel dropped it beforehand.

Our workaround simply consists of:

`

    if (parsedPacket.isPacketOfType(pcpp::UDP))

        if (parsedPacket.getLayerOfType<pcpp::UdpLayer>()->getUdpHeader()->headerChecksum == 0x0000)

            parsedPacket.getLayerOfType<pcpp::UdpLayer>()->getUdpHeader()->headerChecksum = 0xFFFF;
`

However I think this should be implemented in the UdpLayer::calculateChecksum method.

Best,
Martin

**Comment by seladb** [comment]
Hi @inspire1989 , I'm sorry for the late response. Thank you for reporting this issue, I wasn't aware of this edge case.
It should be a very easy fix in [`UdpLayer::calculateChecksum()`](https://github.com/seladb/PcapPlusPlus/blob/26bfa99be1b91814602820c5f4bfb11f98134a99/Packet%2B%2B/src/UdpLayer.cpp#L44).

Would you consider opening a PR for it?

**Comment by inspire1989** [comment]
Thanks a lot and sorry for my late answer. I have a test pcap file but I'm afraid I'm not allowed to share it cause it's property of the company I'm working in and I don't want to provide internal data ... sorry my friend :( but your fix seems to be perfect!
