### ISSUE TITLE
Is there any problem to sniff for long periods of time?

### ISSUE THREAD

**Issue by DamyHao** [seladb/PcapPlusPlus#595]
I'm looking for a C library or to get broadcast packets information in realtime. I've seen that tshark is not suitable for this because it will eventually run out of memory. I don't need to reconstruct de UDP packets, I'm only interested in the broadcast packets.

Is pcapplusplus suitable for this or it will also run out of memory after a period of time? Thanks in advance.

**Comment by seladb** [comment]
hi @DamyHao , thanks for your question!
PcapPlusPlus doesn't keep any packet data internally. That means that if you use PcapPlusPlus to read and analyze a packet and then you release its memory you shouldn't run out of memory.
I hope this answers your question.

**Comment by DamyHao** [comment]
Ok! Thank you for your quick answer.
