### ISSUE TITLE
Move contrstructors?

### ISSUE THREAD

**Issue by amirgon** [seladb/PcapPlusPlus#599]
A [move constructor](https://en.cppreference.com/w/cpp/language/move_constructor) is not defined for `RawPacket` .   

Instead of copying `m_RawData` buffers when `RawPacket` is moved between C++ containers, it would make more sense to define a move constructor and save the need for copying the entire raw packet data every time.

**Comment by seladb** [comment]
You're absolutely right! However currently PcapPlusPlus tries to be compatible with older C++ versions (prior to C++11) where move semantics are not defined.
Having said that, I do plan to move PcapPlusPlus to C++11 at some point and this will probably be one of the tasks in my TODO list

**Comment by amirgon** [comment]
The performance gain can be large. Many copies can be eliminated.  

If you really need to retain backward compatibility with older C++ versions you can use `#ifdef` to limit move constructors to newer compilers.

**Comment by seladb** [comment]
Yes, I totally agree about the performance gain. It's definitely something to be considered when PcapPlusPlus officially moves to C++11.
I'm trying to avoid `#ifdef` statements as much as possible, especially for features that are not currently supported at the language/framework level. I suggest we wait with this for now and build C++11 support from the ground up - starting with build flags and `Makefiles`, and then move on to changing code.
Please let me know what you think.

**Comment by amirgon** [comment]
> It's definitely something to be considered when PcapPlusPlus officially moves to C++11.

Do you have a timeline for moving to C++11?

> starting with build flags and `Makefiles`, and then move on to changing code.

If you are planning a wider change, I suggest you consider moving from Makefiles to CMake.   
Especially important when you are targeting different platforms and OSs.  

I've already noticed some problems with your makefile (regarding incremental builds) and was considering whether to open a new issue for that.

**Comment by seladb** [comment]
> Do you have a timeline for moving to C++11?

Not yet... I'm planning to release the next version sometime soon and then start working on it. Probably a few months?

> If you are planning a wider change, I suggest you consider moving from Makefiles to CMake.
> Especially important when you are targeting different platforms and OSs.

There is a long discussion here: https://github.com/seladb/PcapPlusPlus/issues/164 about moving to `CMake`. I worked on it for a while a few years back and it made me realize that moving to `CMake` will probably not decrease the level the complexity the current build system has. In fact, it will probably make few things even harder, given the large variety of dependencies and OS support this project has. But I'm still open to hearing more opinions 😃 

> I've already noticed some problems with your makefile (regarding incremental builds) and was considering whether to open a new issue for that.

Can you describe which issues you noticed?

**Comment by amirgon** [comment]
> Can you describe which issues you noticed?

Dependency handling.  
When a header file changes I expected the build system to detect this and build what is required.
Cmake handles this automatically, but [you can achieve this with pure Makefiles as well](http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/).  

After changing `Packet++/header/EthLayer.h` I ran `make libs` but it did not detect the change. A `make clean` was required for the changes in the header file to be captured.

**Comment by seladb** [comment]
Should we keep this issue open?
Moving to C++11 will require a lot of work, this is only one issue...

**Comment by amirgon** [comment]
Closing.
