### ISSUE TITLE
Are RadioTap and 802.11 protocols supported?

### ISSUE THREAD

**Issue by DamyHao** [seladb/PcapPlusPlus#600]
Hi,
I'm using a network card in monitor mode which gives the packets with a RadioTap layer. Pcap++ detects this as a "GenericPayload" (0x1000000) and doesn't parse the packet. 
Is 802.11 supported or there is any plan to support this in the future? In my case, i think that Pcap++ is an extremely well-documented library and I really want to use it but the lack of 802.11 is stopping me.

**Comment by seladb** [comment]
Hi @DamyHao thanks for the kind words!
Unfortunately PcapPlusPlus doesn't currently support 802.11 protocol, but I encourage you to help adding support for it!
Let me know if you'd like to do that, I can provide you all the help and support you might need

**Comment by seladb** [comment]
@DamyHao should we keep this issue open or can we close it?

**Comment by DamyHao** [comment]
Thanks, when I feel prepared I will try to implement it.

**Comment by eldadcool** [comment]
Hi,
Did someone stated to work on 802.11 implementation?

**Comment by seladb** [comment]
> Hi, Did someone stated to work on 802.11 implementation?

@eldadcool not yet, unfortunately. You can find a list of all supported protocols here: https://pcapplusplus.github.io/docs/features#supported-network-protocols

Would you consider working on it?
