### ISSUE TITLE
Makefile dependencies

### ISSUE THREAD

**Issue by amirgon** [seladb/PcapPlusPlus#602]
This continues the discussion on #599 :

When a header file changes the build system does not detect it and does not build the required files as expected.
(Cmake handles this automatically, but [you can achieve this with pure Makefiles as well](http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/).  )

It looks like the dep files are created (with `-MF ` gcc option) but not used or not used correctly.

To reproduce:

- Run `make libs`
- Change a header file (for example `Packet++/header/EthLayer.h`)
- Run `make libs`

The second run of `make libs` does not detect the changed header and does not build the project with the modified header fille.

**Comment by amirgon** [comment]
> Just to make sure I understand: what do you mean by "does not build the project with the modified header fille"? Do you mean that the object files aren't rebuilt or the header file isn't copied to `Dist/`?

Object files aren't rebuilt.

> BTW, did you find any clues on how to solve it?

It's explained very well on http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/
I recommend reading this.

What's basically missing is an include in the Makefile to the dep files.
But there are are some subtle details, like the include position in the Makefile, preventing Make from failing when deps are missing etc., everything is explained in that link.

If you want to avoid this headache - you probably need to switch to CMake.

**Comment by seladb** [comment]
Thanks for your help @amirgon ! I think I figured out the issue - please see PR #603 .
Please let me know what you think

**Comment by seladb** [comment]
Thanks @amirgon for reporting this issue and for your help in solving it, I really appreciate it!
The fix is now pushed to `master` so I'll close this ticket. Please reopen if any issue.
