### ISSUE TITLE
How to create a customize layer

### ISSUE THREAD

**Issue by bug65536** [seladb/PcapPlusPlus#605]
hi, there already many layer provided by pcpp, and i want to add some new, for example SmtpLayer, or SmbLayer,

should I add my code to the source code and recompiled all ?

can you provide a example step by step?

thank you very much!  :-)

**Comment by seladb** [comment]
Adding a layer isn't that complex. You need to follow these guidelines:
- Create a new class in Packet++ that inherits from `Layer`
- Implement the [abstract methods](https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/header/Layer.h#L137-L160) inherited from `Layer`
- Add your layer to `parseNextLayer()` of the underlying protocols - for example if your layer comes right after TCP then you should add code in [`TcpLayer::parseNextLayer()`](https://github.com/seladb/PcapPlusPlus/blob/79dec541ff151720c7c69b8abdb2464d03804a7f/Packet%2B%2B/src/TcpLayer.cpp#L343) to create your layer
- Add tests in [`Packet++Test`](https://github.com/seladb/PcapPlusPlus/tree/master/Tests/Packet%2B%2BTest/Tests) to parse, create and edit your layer

As a reference you can take a look at [`VlanLayer`](https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/header/VlanLayer.h) or [`ArpLayer`](https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/header/ArpLayer.h). These are fairly simple layers. If you're interested in a slightly more complex example you can look into [`IcmpLayer`](https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/header/IcmpLayer.h).

Please let me know if that makes sense.

**Comment by bug65536** [comment]
well, should I add the custom layer in 

[ProtocolType.h](https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/header/ProtocolType.h)

`const ProtocolType SMTP = 0x2000000000;`

and then i can write code like this:

```
if (protocoltype == pcpp::SMTP)
 // balabalabala
```

**Comment by seladb** [comment]
Yes you're right, I forgot to mention that

**Comment by bug65536** [comment]
thank you very much !

**Comment by angelyouyou** [comment]
> Adding a layer isn't that complex. You need to follow these guidelines:

Do I need to modify some makefiles to compile?

**Comment by seladb** [comment]
> Do I need to modify some makefiles to compile?

No, probably not

**Comment by angelyouyou** [comment]
> > Do I need to modify some makefiles to compile?
> 
> No, probably not

After I modified some files, my test code in Packet++Test had compiled.I want to know can I import this project to CLion for debugging?How to do?My TestCase failed...

**Comment by seladb** [comment]
> After I modified some files, my test code in Packet++Test had compiled in the project.I want to know can I import this project to CLion or other method for debugging ?How to do?My TestCase failed...

I'm not very familiar with CLion, but you can use any code editor or IDE you want in order to debug your code. PcapPlusPlus uses the standard Make build system so it should be compatible with any tool
