### ISSUE TITLE
BUG: stopCapture may block for infinite time.

### ISSUE THREAD

**Issue by skorup101** [seladb/PcapPlusPlus#606]
Hello seladb,

**Expected behavior:**
PcapLiveDevice::stopCapture() stops the capture and close the capture thread.

**Problem:**
PcapLiveDevice::stopCapture() function blocks.

**How to reproduce:**
It happened on rhel8.3 in development environment. Unfortunately I couldn't reproduce it yet in test env.

**Details and debugging info:**
In my option reason is here: pthread_join(m_CaptureThread->pthread, NULL); If somehow the m_CaptureThread do not progress it will never exit it's main loop.

This happened when I was using buffer & timeout for pcpp::PcapLiveDevice::open(const DeviceConfiguration& config). Reason might be this (https://www.tcpdump.org/manpages/pcap.3pcap.html):
_NOTE: the packet buffer timeout cannot be used to cause calls that read packets to return within a limited period of time, because, on some platforms, the packet buffer timeout isn't supported, and, **on other platforms, the timer doesn't start until at least one packet arrives**. This means that the packet buffer timeout should NOT be used, for example, in an interactive application to allow the packet capture loop to ``poll'' for user input periodically, as there's no guarantee that a call reading packets will return after the timeout expires even if no packets have arrived.
The packet buffer timeout is set with pcap_set_timeout()._

To backup the thesis I also found that the m_CaptureThread **progresses (and exits) when it finally receives a packet**.
Being precise: the thread blocked until I curled the rare combination of host/port being captured.

**Comment by skorup101** [comment]
My quick suggestion is to add pcap_breakloop() before joining the capture thread in the stopCapture() function. What do you think?

**Comment by seladb** [comment]
thanks @skorup101 for reporting this issue!
I'm actually aware of this issue but was not sure how to solve it. Do you think that calling `pcap_breakloop()` will make `pcap_dispatch()` to exit in any scenario? It might be worth trying... I didn't try this approach so far

**Comment by skorup101** [comment]
It seems that there **have been** problems to break pcap_dispatch() with pcap_breakloop(). See: https://github.com/the-tcpdump-group/libpcap/issues/903 . 
pcap_breakloop() did not break pcap_dispatch() loop due to poll() call block (which is exactly what I've experienced during debugging).

It seems that pcap_breakloop should succesfully break the "capturing loop" since pcap 1.9.0. Adding pcap_breakloop  in stopCapture() should help (and it won't do any harm even if somehow it wouldn't work - i.e someone uses older versions of pcap).

I can create such pull request, what do you think?

**Comment by seladb** [comment]
Sure, please open a PR. I remember seeing that issue with poll causing pcap_breakloop not to work. I'm happy to see they've fixed it in libpcap 1.9.0. I agree it won't do any harm and might solve the issue in newer versions of libpcap and Npcap

**Comment by seladb** [comment]
I've merged your PR to `master`. Thank you so much for your contribution to this project!

I'll close this issue now, please reopen if needed.

**Comment by WojtekMs** [comment]
Hey, thanks a lot for the fix, it resolved the issue for me :) However, I would like to say that the fix in `libpcap` was applied in version 1.10.0, not 1.9.0.
