### ISSUE TITLE
PcapSplitter does not correctly splits UDP feed by server-port

### ISSUE THREAD

**Issue by manuka89** [seladb/PcapPlusPlus#609]
When I invoke the PcapSplitter on an UDP feed and split by server-port I have some missing ports. After having checked the code I could see that, in case of UDP, always the default case is used:

	uint32_t getValue(pcpp::Packet& packet, PacketType packetType, uint16_t srcPort, uint16_t dstPort)
	{
		switch (packetType)
		{
		case SYN:
			return dstPort;
		case SYN_ACK:
			return srcPort;
		// other TCP packet or UDP packet
		default:
			return std::min<uint16_t>(srcPort, dstPort);
		}
	}

In my feed, the dstPort should be the server port but it is sometimes larger than the srcPort so that the port is not detected correctly.

Why it is not possible to check the source and destination IP whether it is in a multicast address range to decide whether it is the server port or not?

**Comment by seladb** [comment]
This is a very good idea! I haven't thought of it!

Would you consider implementing it and open a PR?

**Comment by manuka89** [comment]
Thanks, yes I will do it. Although, there is a limitation, it will only work for multicast addresses.

For the rest, I can use the the std:min algo.

**Comment by seladb** [comment]
thank you so much @mmizi for working on this, I really appreciate the great time and efforts you put into this, BIG THANK YOU!
I encourage you to contribute more, it's because of people like this project can grow and evolve.

I'll close this issue now, please reopen if needed.

**Comment by mmizi** [comment]
Thank you for your help and time during the PR process! It was a really good experience!
