### ISSUE TITLE
[Feature request]: Build shared libraries

### ISSUE THREAD

**Issue by lgbaldoni** [seladb/PcapPlusPlus#61]
At least on Linux. Or is the API still too unstable?

**Comment by seladb** [comment]
I tried to do it a few months back but various parts in the API assume memory allocation on both shared library and API caller sides so this separation doesn't work.
Doing it will require quite a lot of work and changes in these parts in the API. 
Unfortunately I don't think I'll have the time for it in the near future

**Comment by shidaoxuan** [comment]
Build shared libraries of "libCommon++.so libPacket++.so libPcap++.so"
Is it possible to provide a way to switch from a static library to a dynamic library?

**Comment by seladb** [comment]
As I explained in the comment above this is not trivial because several parts in PcapPlusPlus API assume memory allocation on both sides (shared library and caller) so this separation doesn't work out-of-the-box.

I guess this is doable but will require a significant amount of efforts which I currently don't have...

**Comment by bornlibra23** [comment]
Hi Could you point us to the issues & code areas which require work? Perhaps I can take it up.

**Comment by seladb** [comment]
To be honest, it's been a long time so I don't quite remember... but you can try to build the PcapPlusPlus as shared library, [run the unit-tests](https://pcapplusplus.github.io/docs/install/build-source/tests) and you'll probably bump into the issues.

**Comment by DinoStray** [comment]
I have met  `undefined reference` problem several times, like
```
 undefined reference to `pcpp::MacAddress::toString[abi:cxx11]() const'
```
and try several sequence of link libs
```
        pthread
        pcap
        Common++
        Pcap++
        Packet++
```
And now I have no idea to solve the problem, maybe the only way is choose shared libs

**Comment by seladb** [comment]
> 
> 
> I have met `undefined reference` problem several times, like
> 
> ```
>  undefined reference to `pcpp::MacAddress::toString[abi:cxx11]() const'
> ```
> 

Are you trying to build PcapPlusPlus as a shared library?

**Comment by DinoStray** [comment]
> > I have met `undefined reference` problem several times, like
> > ```
> >  undefined reference to `pcpp::MacAddress::toString[abi:cxx11]() const'
> > ```
> 
> Are you trying to build PcapPlusPlus as a shared library?

No, I just rebuild the latest PcapPlusPlus version(v20..08), then everything is OK

**Comment by clementperon** [comment]
@lgbaldoni could you retry with cmake build system it should works properly.

**Comment by seladb** [comment]
@clementperon I remember there we some problems with shared libraries, but I don't remember what they were and on which platforms. I guess we can close this issue now, but first maybe we can document how to compile PcapPlusPlus as static or shared libraries?

**Comment by seladb** [comment]
I'll close the issue now as building shared libraries is now supported. Thanks @clementperon for working on this!
