### ISSUE TITLE
Bad result on IPV4Address comparison

### ISSUE THREAD

**Issue by manuka89** [seladb/PcapPlusPlus#611]
Hello,

I think that IPV4Address operator< does not work correctly. Small example to demonstrate:

    #include <IPv4Layer.h>
    #include <Packet.h>
    #include <PcapFileDevice.h>
    #include <iostream>
    
    using namespace pcpp;
    int main(int argc, char* argv[])
    {
        const IPv4Address smallerAddress { "212.0.0.1" };
        const IPv4Address largerAddress { "224.0.0.0" };

        std::cout << "SmallerAddress: " << smallerAddress.toString()
                  << " LargerAddress: " << largerAddress.toString()
                  << " Comparison (smallerAddress < largerAddress): " << (smallerAddress < largerAddress) << std::endl;

        return 0;
    }

The result is:

SmallerAddress: 212.0.0.1 LargerAddress: 224.0.0.0 Comparison (smallerAddress < largerAddress): 0

The operator< of IPv4Address uses the toInt() method:

	uint32_t IPv4Address::toInt() const
	{
		uint32_t addr;
		memcpy(&addr, m_Bytes, sizeof(m_Bytes));
		return addr;
	}

The byte array should be reversed in my opinion in a temporary variable before converting it to uint32_t.

**Comment by seladb** [comment]
Yes, I believe you're right, thanks for reporting this issue!

Would you consider opening a PR with the fix?

**Comment by manuka89** [comment]
Thanks for your response,. Yes I will do that.

**Comment by seladb** [comment]
Thanks you so much @mmizi for providing the fix! 
Your PR #621 has been merge to `master` so I'll close this issue
