### ISSUE TITLE
Flawed packet parsing?

### ISSUE THREAD

**Issue by rjo** [seladb/PcapPlusPlus#617]
I have some code using PF_RING ZC and I'm experimenting with pcap++.  I have an existing capture loop that pulls packets from zc and parses the headers using the pfring functions to do so. 

This code is old and has been heavily tested using a some packet generation tools I've written. I can generate a known number of UDP packets, and via API calls get those counters and compare the number of packets captured vs the number generated as a functional test.

I added pcap++ to that loop and created a raw packet using the buffer from pfring, and a parsed packet. Then I count packets based on the same criteria as I do with zc and my counts do not match. Over a million packets generated, my zc count will be accurate, but the pcap++ count will have 20 or so extra packets counted, which is bizarre.  Consider the following:

```
    unsigned long zcCount=0;
    unsigned long pcapCount=0;
    while (!captureThreadShouldShutdown) {
    
        if(pfring_zc_recv_pkt(zq, &buffers[0], 1) > 0) {
            u_char *pkt_data = pfring_zc_pkt_buff_data(buffers[0], zq);

            memset(&hdr, 0, sizeof(hdr));
            hdr.len = buffers[0]->len;
            hdr.caplen = buffers[0]->len;
            pfring_parse_pkt(pkt_data, &hdr, 4, 0, 1);
            if(hdr.extended_hdr.parsed_pkt.l3_proto == 0x11) {
                if(hdr.extended_hdr.parsed_pkt.l4_dst_port == 9000) {
                    ++zcCount;
                }
            }

            ts.tv_sec = buffers[0]->ts.tv_sec;
            ts.tv_usec = buffers[0]->ts.tv_nsec/1000;
            pcpp::RawPacket rawPacket((const uint8_t*)pkt_data,buffers[0]->len,ts,false);
            pcpp::Packet parsedPacket(&rawPacket);
            pcpp::UdpLayer* udpLayer = parsedPacket.getLayerOfType<pcpp::UdpLayer>();
            if(udpLayer != NULL) {
                if(udpLayer->getDstPort() == 9000) ++pcapCount;
            }

            filter(rawPacket, parsedPacket);
           
            incrementInterfaceStats(interfaceId, hdr.len,zcCount,pcapCount);

       } else {
            spdlog::error("Error while calling pfring_zc_recv_pkt()");
            throw probe_exception("Error while calling pfring_zc_recv_pkt()");
        }

    }

```

The values of zcCount and pcapCount should be equal, and they are not. Unless I'm missing something excruciatingly obvious this can only mean that something bad is happening when pcap++ parses these packets.

Thoughts?

**Comment by seladb** [comment]
thanks @rjo for reaching out, this is indeed interesting!
In order to understand where the issue is it'd be great if you can save these 20 packets to a pcap file and send them to me. Please let me know if you can do that.

**Comment by rjo** [comment]
@seladb I have no idea which of the 20 are errant at this time. Since its 20 out of a million it would be hard to pinpoint. I'm gonna do some experimentation to see if i can tickle this problem in a smaller sample set, and perhaps generate a pcap file for it. I'll keep you posted.

**Comment by rjo** [comment]
Turns out I was getting some ICMP type 3 packets, and since those do have a UDP layer associated I was mistakenly counting them!

My bad.
