### ISSUE TITLE
will the definition of protocol be too long?

### ISSUE THREAD

**Issue by bug65536** [seladb/PcapPlusPlus#620]
hi, entil now, the definition of protocoltype in
[ProtocolType.h](https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/header/ProtocolType.h)

`	const ProtocolType IPSec = 0x1800000000;`

As the number of protocoltype increases, maybe there will be a very very long type? just like :

`    const ProtocolType xxxxxx = 0x8000000000000000;`

as you defined ProtocolType as uint64

`typedef uint64_t ProtocolType;`

what if more protocol type added?

**Comment by seladb** [comment]
Yes, that's a good question! It actually used to be `uint32_t` and we increased it to `uint64_t` at some point. I'm not sure what would be the solution but we have some time to think about it 😄

**Comment by seladb** [comment]
Closing this issue now, please reopen if needed
