### ISSUE TITLE
Windows 10 sendPacket not working

### ISSUE THREAD

**Issue by neighbads** [seladb/PcapPlusPlus#628]
System: Windows 10 1904
npcap : npcap-sdk-1.07.zip  npcap-1.20.exe

I ping ip by `ping 10.0.61.1 -n 1` and copy as hex stream from Wireshark.
Then send by 
```
bool sendPacket(const uint8_t* packetData, int packetDataLength);
```
Ping request show in Wireshark. But no response(remote ip is good).

I alse try 
```
bool sendPacket(Packet* packet);
```
it's not working too.

Test Code
```
    dev->open();
    pcpp::MacAddress srcMacAddr = ui->edit_src_mac->text().toLocal8Bit().data();
    pcpp::MacAddress dstMacAddr = ui->edit_dst_mac->text().toLocal8Bit().data();
    pcpp::IPv4Address srcIPAddr = dev->getIPv4Address();
    const uint8_t bytes[4] = {0x0a, 0x00, 0x3d, 0x01};
    pcpp::IPv4Address dstIPAddr(bytes);
    // a static variable that holds an incrementing IP ID
    static uint16_t ipID = 0x1234;

    // keep IP ID in the range of 0x1234-0xfff0
    if (ipID == 0xfff0)
        ipID = 0x1234;

    // create the different layers

    // Eth first
    pcpp::EthLayer ethLayer(srcMacAddr, dstMacAddr, PCPP_ETHERTYPE_IP);

    // then IPv4 (IPv6 is not supported)
    pcpp::IPv4Layer ipLayer(srcIPAddr, dstIPAddr);
    ipLayer.getIPv4Header()->timeToLive = 128;
    // set and increment the IP ID
    ipLayer.getIPv4Header()->ipId = htons(ipID++);

    // then ICMP
#define ICMP_FT_START 0xd45ae6c2e7a3cd67ULL

    pcpp::IcmpLayer icmpLayer;
    if (icmpLayer.setEchoRequestData(1, 0, ICMP_FT_START, (unsigned char *)"data", 4) == NULL) {
        qDebug() << "Cannot set ICMP echo request data";
        return;
    }

    // create an new packet and add all layers to it
    pcpp::Packet packet;
    packet.addLayer(&ethLayer);
    packet.addLayer(&ipLayer);
    packet.addLayer(&icmpLayer);
    packet.computeCalculateFields();

    // send the packet through the device
    dev->sendPacket(&packet);
```

Wireshark screenshot：
![Dingtalk_20210412161339](https://user-images.githubusercontent.com/16126598/114362689-33c18c00-9baa-11eb-8aa2-69c2848217ad.jpg)

**Comment by seladb** [comment]
hi @neighbads I'd suggest comparing all of the layers of the ICMP request that works vs. the one that doesn't work. Something must be different: it might be the MAC addresses, one of the IP parameters, the ICMP payload, etc. Once you identify what's different you will probably understand how to fix it

**Comment by neighbads** [comment]
@seladb Thanks for reply. I compare two request , It is all same. Actually I also try udp with same way, remote udp server also not receive packet.

This is test pcap file.

[icmp.zip](https://github.com/seladb/PcapPlusPlus/files/6296102/icmp.zip)

**Comment by seladb** [comment]
Yes, as you mentioned the 2 packets are the same. Just to make sure:
- The first request is the one that was sent by Windows and the second request is the one you created?
- How did you capture those packets? Were you listening to a specific network interface? Is `dev` equal to the network interface that Windows uses to send the ICMP request?

**Comment by neighbads** [comment]
When I change wlan to cable directly connected, it is good.

I don't know why all same packet can not send to remote in wlan. 

![desc](https://user-images.githubusercontent.com/16126598/114646022-10fbb880-9d0d-11eb-9e5e-2ed4831068d7.jpg)

[test_icmp2.zip](https://github.com/seladb/PcapPlusPlus/files/6307849/test_icmp2.zip)

**Comment by seladb** [comment]
For wlan I think you need to install a special adapter for Npcap, please see their devguide: https://nmap.org/npcap/guide/npcap-devguide.html
I don't have experience with wlan so I'm not sure how to set it up.

**Comment by seladb** [comment]
@neighbads what should we do with this issue? Should we keep it open or close it?
