### ISSUE TITLE
Compute etherType in VlanLayer::computeCalculateFields()

### ISSUE THREAD

**Issue by siadatism** [seladb/PcapPlusPlus#629]
Hi, thanks for well-designed library.

Why next layer ether-type for vlan layer is not calculated in computeCalculateFields method?

When using PcapPlusPlus to craft packets, next layer ether type should be given in Vlan layer, but it could be removed from constructor and be calculated in mentioned method.

What's your opinion about it?

**Comment by seladb** [comment]
hi @siadatism thanks for your suggestion! I guess we could do that, I don't see any reason why it won't work. 
Like in [`EthLayer`](https://github.com/seladb/PcapPlusPlus/blob/d2bba7d03c56c35da53981b55005bfa47b81c464/Packet%2B%2B/header/EthLayer.h#L95) I'd keep this parameter in the c'tor but give it a default value of 0 to allow users to provide it if they don't want to use `computeCalculateFields()`

**Comment by siadatism** [comment]
Thank you for fast reply. I could provide a PR if you want.

**Comment by seladb** [comment]
Sure, that would e great, thank you!

**Comment by seladb** [comment]
hi @siadatism , did you have time to work on the PR?

**Comment by seladb** [comment]
The fix was merged to `master`. Thanks for suggesting this idea!
