### ISSUE TITLE
PcapSplitter libpcap 0.8 dependency

### ISSUE THREAD

**Issue by stephanieleevillanueva** [seladb/PcapPlusPlus#63]
Hi,

I am having issues running PcapSplitter on a Centos/Amazon Linux AMI machine because the libpcap versions installed are 1.5 and 1.4 respectively and PcapSplitter is looking for the 0.8 version (please see screenshot). I was just wondering if there is a way to compile PcapSplitter with the newer versions of libpcap. I do not know much about C/C++, any help would be much appreciated!

![pcapsplitter-dependency-error](https://user-images.githubusercontent.com/1335714/29883541-88dba5e2-8d65-11e7-922b-e5254440feb3.png)

Thanks,
Stephanie

**Comment by stephanieleevillanueva** [comment]
Ok sure, I'll give it a shot. Will update you. Thanks!

**Comment by stephanieleevillanueva** [comment]
update: I am getting a lot of warnings and errors on `step 4: Run make all from PcapPlusPlus main directory`... and Dist/ directory in step 6 is not being created.

Would you have an idea of why I'm getting these errors?
![screen shot 2017-08-30 at 4 11 25 pm](https://user-images.githubusercontent.com/1335714/29899092-3355df78-8d9e-11e7-9515-fca931659b73.png)

**Comment by seladb** [comment]
Unfortunately libpcap 0.8 is missing pcap_offline_filter which is necessary for PcapPlusPlus compilation.
This capability was added on libpcap 1.0. How problematic is it for you to update to a newer libpcap version?
I think `sudo yum install libpcap-devel` should install a newer version of libpcap. Could you please try and let me know if it works?

**Comment by stephanieleevillanueva** [comment]
Oh, I actually do want my PcapPlusPlus to work with a newer libpcap version (1.4 or 1.5) and I am trying to recompile but I can't get it to work. I have an older version of PcapPlusPlus that I think was compiled with libpcap 0.8 but it looks like it's not compatible with Linux Centos distro which has libpcap 1.5 installed.

Here are the steps I took:
1. `sudo yum install libpcap-devel`
2. `sudo yum install libstdc++-static`
3. Ran `configure-linux.sh`, with "n" on both DPDK and PF_RING
4. Ran `make all`

It is during step 4 `make all` that I get these errors.

**Comment by seladb** [comment]
That's weird. Could you please check the installed version on libpcap?
You can run `yum list installed`and look for libpcap version.
Please take a look here: https://www.google.co.il/amp/s/www.tecmint.com/list-installed-packages-in-rhel-centos-fedora/amp/

**Comment by stephanieleevillanueva** [comment]
Here it is...
libpcap.x86_64                                 14:1.4.0-1.20130826git2dbcaa1.10.amzn1           @amzn-main   
libpcap-devel.x86_64                      14:1.4.0-1.20130826git2dbcaa1.10.amzn1           @amzn-main

**Comment by seladb** [comment]
It seems like you have libpcap 1.4.0 installed and still you see these weird problems. Is there any way I can install or get access to a similar machine like you're using?

**Comment by stephanieleevillanueva** [comment]
Hmm... upon compile it should pick up the correct libpcap version right? I am using Amazon's default EMR cluster. It would be great if you can spin up an AWS cluster to test but I do not know how much that costs. If not, don't worry about it. Is the PcapPlusPlus code in the repo current?

**Comment by seladb** [comment]
Yes, the code in PcapPlusPlus repo is current. Unfortunately Amazon EMR costs money so I won't be able to set it up. You should check using `ldconfig` what is the default version of libpcap PcapPlusPlus is trying to use on compilation and try to change that default to be version 1.4.0 which is installed on your system.
Please let me know if it worked

**Comment by seladb** [comment]
I found some commands that may help us understand what version of libpcap is installed on your machine:

1. Run `sudo ldconfig -v | grep pcap` to view which libpcap versions are installed and where they point to. This will help us understand to which version of libpcap gcc is refering to
2. Run `sudo find / -name libpcap.so*` to see where libpcap.so is installed

I'd appreciate if you can paste the output of these 2 command

**Comment by stephanieleevillanueva** [comment]
Update:  

I ran `ldconfig` (from your second to the last comment) then followed the compile instructions again. There were some warnings but the compile ran all the way through and did not exit upon error. I did the test check and here's what I got:  

![packet test](https://user-images.githubusercontent.com/1335714/30075546-d845daac-922a-11e7-86b3-cfb08b9f6c68.png)  

However, I am now able to see the Dist folder and it seems like PcapSplitter works. I don't get the dependency issue anymore. I think this is sufficient for now. Thanks!! :)  

I will let you know if I run into more problems.

**Comment by stephanieleevillanueva** [comment]
Btw, here are the output of the 2 commands for reference:

1. `sudo ldconfig -v | grep pcap`
![screen shot 2017-09-05 at 11 14 55 am](https://user-images.githubusercontent.com/1335714/30075878-06ff6952-922c-11e7-8c9c-c1f511805923.png)

2. `sudo find / -name libpcap.so*`
![screen shot 2017-09-05 at 11 15 59 am](https://user-images.githubusercontent.com/1335714/30075903-1cc39bbe-922c-11e7-8bdc-1705dab22bcb.png)

**Comment by seladb** [comment]
Thanks for the update! I'm glad that you made it work. Did you find what was the problem?
Regarding the tests: what you need to do is run it from Packet++Test folder:

    cd [PcapPlusPlus_folder]/Tests/Packet++Test
    Bin/Packet++Test

Please let me know if that worked

**Comment by stephanieleevillanueva** [comment]
Oh cool, I get all "PASSED" now. Thanks for the tip! 

As for the problem before, I just ran `ldconfig` before compiling and that seems to have fixed the errors I was getting during the build.

**Comment by seladb** [comment]
Great, thanks for letting me know.
With your permission I'll close the issue now. Please reopen it if you need further information
