### ISSUE TITLE
Which C++ version does PcapPlusPlus support? 

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#630]
![image](https://user-images.githubusercontent.com/12936259/114659175-b0c54080-9d25-11eb-94d9-298f97f47c49.png)

**Comment by seladb** [comment]
PcapPlusPlus should support all C++ versions from C++03

**Comment by angelyouyou** [comment]
@seladb 
There are only five versions in CLion, which version should I choose for PcapPlusPlus?
![image](https://user-images.githubusercontent.com/12936259/114681228-86cd4780-9d40-11eb-91ef-50f41948c6f3.png)

**Comment by seladb** [comment]
I think all should work, C++11 and above for sure
