### ISSUE TITLE
[Question] Packet does not match connection side

### ISSUE THREAD

**Issue by mmizi** [seladb/PcapPlusPlus#636]
Hello,

I have a question with regards of this log: **"Error occurred - packet doesn't match either side of the connection!!"**

It occurs a lot in one of my PCAP file. Do you have any idea in which case we can have this logs? The resulted **flowkey** correspond to another connection? Why could this happen?

Thanks!

**Comment by seladb** [comment]
Yes, the only logical explanation I can think of is a collision between two flow keys, meaning 2 connections that have the same flow key. That should be pretty rare though. You can add a few prints in TCP reassembly code to check if this is really the case

**Comment by seladb** [comment]
@mmizi please let me know if we can close this issue

**Comment by mmizi** [comment]
Yes it looks like that there is an overflow, I changed the type to 64 bit and now I have no such errors. Should I create a PR?

**Comment by seladb** [comment]
the only caveat is that it will increase the size of the flow table... wdyt?

**Comment by mmizi** [comment]
Sorry for my late response. Yes it will. With 4GB memory it can handle 4 billion connection. Now it passes to 8GB. In my point of view today's machine can have easily at least 8 GB.

**Comment by seladb** [comment]
The thing is that in many cases the number of connections is not very large (a few thousands or even less), but still there might be collisions. Another way to handle it is by keeping a list of `TcpReassemblyData` objects per bucket and check the connection 5-tuple (or at least part of it) to determine which connection it matches to, but this means extra work per packet...

**Comment by seladb** [comment]
@mmizi what should we do with this issue?

**Comment by seladb** [comment]
I'll close this issue now, please reopen if needed
