### ISSUE TITLE
How can I add a protocol? Is there a guidance note step by step?

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#637]
I want to add some protocol, after this I want to modify it and send it .
Is there a guidance note step by step to add a protocol(encapsulation and ecapsulation )? Thanks.

**Comment by seladb** [comment]
there is no official guide yet, but you can take a look at these steps:
https://github.com/seladb/PcapPlusPlus/issues/605#issuecomment-796542438

**Comment by seladb** [comment]
Closing this issue as it's being discussed in #605
