### ISSUE TITLE
Changing / Crafting for IPv6 packets

### ISSUE THREAD

**Issue by jafar75** [seladb/PcapPlusPlus#638]
Hi there, 

I was reading [tutorial ](https://pcapplusplus.github.io/docs/tutorials/packet-crafting)about changing and crafting packets. there is not any 'set' function for [IPv6Layer ](https://pcapplusplus.github.io/api-docs/classpcpp_1_1_i_pv6_layer.html)similar to IPv4Layer. 
How can I change some info like src/dst IP for a layer created by IPv6Layer?

regards

**Comment by seladb** [comment]
Good catch! we should definitely add `set` method for `IPv6Layer`. Would you consider adding that and open a PR?

**Comment by jafar75** [comment]
Sure, I'll try to provide a PR

**Comment by seladb** [comment]
Thank you @jafar75 for your contribution to this project, much appreciated!
