### ISSUE TITLE
compressed files (*.zstd) cannot be read using IFileReaderDevice.getReader()

### ISSUE THREAD

**Issue by naugler** [seladb/PcapPlusPlus#639]
IFileReaderDevice.getReader(<path>) checks to see if the filename ends in *.pcapng to pass the file to PcapNgFileReaderDevice, but the file has to end in *.zstd for the lightpcapng library to recognize it as a compressed file.

A workaround is to just open the file using a PcapNgFileReaderDevice directly.

**Comment by seladb** [comment]
I'm not sure every `*.zstd` is a pcapng file. What happens if you pass a file with the same extension which is not a pcapng file?

**Comment by naugler** [comment]
That is true, but right now if you pass a file which does not end in *.pcapng, then a regular PcapFileReaderDevice is returned. So any file extension except *.pcapng is handled as a *.pcap, and if it is not a valid *.pcap file then the FileReaderDevice fails on open().

So if you attempt to open a *.zstd file which is not a valid compressed pcapng file, it will fail on open, just like if you attempt to open any invalid file.

**Comment by seladb** [comment]
Yes, that makes sense, I merged your PR. Thanks for your contribution!
