### ISSUE TITLE
Incorrect workersCoreMask in DPDK l2fwd Tutorial

### ISSUE THREAD

**Issue by harshgondaliya** [seladb/PcapPlusPlus#641]
Hi all,

In the below code snippet from `main.cpp` file of DPDK l2fwd Tutorial,
we want to generate a `workersCoreMask` equal to `0x6` (core 1 and core 2).
But, the code is actually generating `workersCoreMask` equal to `0x12`.
	
```
	// Create core mask - use core 1 and 2 for the two threads
	int workersCoreMask = 0;
	for (int i = 1; i <= 2; i++)
	{
		workersCoreMask = workersCoreMask | (1 << (i+1));

```	
https://github.com/seladb/PcapPlusPlus/blob/master/Examples/Tutorials/Tutorial-DpdkL2Fwd/main.cpp#L103

**Comment by seladb** [comment]
Good catch! It should be:

```cpp
int workersCoreMask = 0;
for (int i = 1; i <= 2; i++)
{
	workersCoreMask = workersCoreMask | (1 << i);
}
```

I'll fix it

**Comment by seladb** [comment]
The fixed was pushed to `master`. Thanks for reporting this issue!
