### ISSUE TITLE
Timestamps in nano seconds?

### ISSUE THREAD

**Issue by pedro-esteves-pinto** [seladb/PcapPlusPlus#645]
Hi, does PcapPlusPlus support nano-second resolution timestamping? I have a pcap that has nanosecond resolution but I seem to only get microsecond resolution when I get time via getPacketTimeStamp().

**Comment by seladb** [comment]
As far as I know the pcap format only support microseconds resolution: https://wiki.wireshark.org/Development/LibpcapFileFormat#Record_.28Packet.29_Header

however, the pcapng format does support nanoseconds: https://pcapng.github.io/pcapng/draft-gharris-opsawg-pcap.html#name-packet-record and PcapPlusPlus supports it

**Comment by pedro-esteves-pinto** [comment]
You are right. My file was in the pcapng format but it still had a pcap extension so I guess PcapPlusPlus treated it as pcap? simply changing the extension gave me the nanosecond precision I was looking for.
