### ISSUE TITLE
Example Tutorial-LiveTraffic does not compile

### ISSUE THREAD

**Issue by slhck** [seladb/PcapPlusPlus#649]
I am running Ubuntu 20.04 with the following compiler:

    c++ (Ubuntu 10.2.0-5ubuntu1~20.04) 10.2.0

When I try to compile part of [the example](https://github.com/seladb/PcapPlusPlus/blob/master/Examples/Tutorials/Tutorial-LiveTraffic/main.cpp), it errors out with:

```
[1/2] Compiling C++ object src/pcap_test.p/pcap_test.cpp.o
FAILED: src/pcap_test.p/pcap_test.cpp.o 
c++ -Isrc/pcap_test.p -Isrc -I../src -I../include/pcapplusplus -I../include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -g -MD -MQ src/pcap_test.p/pcap_test.cpp.o -MF src/pcap_test.p/pcap_test.cpp.o.d -o src/pcap_test.p/pcap_test.cpp.o -c ../src/pcap_test.cpp
../src/pcap_test.cpp: In function ‘int main(int, char**)’:
../src/pcap_test.cpp:38:59: error: request for member ‘c_str’ in ‘dev->pcpp::PcapLiveDevice::getName()’, which is of non-class type ‘const char*’
   38 |   printf("   Interface name:        %s\n", dev->getName().c_str());
      |                                                           ^~~~~
../src/pcap_test.cpp:40:59: error: request for member ‘c_str’ in ‘dev->pcpp::PcapLiveDevice::getDesc()’, which is of non-class type ‘const char*’
   40 |   printf("   Interface description: %s\n", dev->getDesc().c_str());
      |                                                           ^~~~~
```

It does not complain when I simply use `dev->getName()` or `dev->getDesc()`.

I have installed the latest headers and libraries from the August 2020 release of PcapPlusPlus (v20.08).

**Comment by slhck** [comment]
Oh, I see that this was changed after the last release: https://github.com/seladb/PcapPlusPlus/commit/149b08d30cde44f834502f023374033dd356b910

May I suggest that the documentation links to the examples at the time of the last release, and not the current `master` version?

Or that documentation is frozen for a specific release and navigable based on the release, so that people can simply look at the correct examples for their matching release.

**Comment by seladb** [comment]
hi @slhck there is documentation that is frozen per release, here is the one relevant for the last release: https://pcapplusplus.github.io/v2008/ 
However, the links still point to `master`...

This week I'm releasing a new version v21.05 and I'll try to fix it there

**Comment by slhck** [comment]
Thanks, that would be awesome!

**Comment by seladb** [comment]
Fixed in the new release:  https://pcapplusplus.github.io/v2105

**Comment by slhck** [comment]
Awesome, that's much better in terms of usability. Congratulations on the new release!
