### ISSUE TITLE
Timestamp below one second gets cut off

### ISSUE THREAD

**Issue by IVIexx** [seladb/PcapPlusPlus#659]
The following commit leads to the effect, that timestamps below one second get cut off completely:

https://github.com/seladb/PcapPlusPlus/commit/58151de20720d9cd5753919d99553e3e0a6619d6

So the nanoseconds are always zero until one complete second is reached.

What was that commit for? Locally I will just undo that part and hope it works for me.

**Comment by seladb** [comment]
I think you're right @IVIexx , I'm not sure why this was added. Maybe @Akvinikym remember?

**Comment by Akvinikym** [comment]
@seladb hmm I've looked at this code and don't understand as well why it's there. Also there is a similar `if` [here](https://github.com/seladb/PcapPlusPlus/blob/master/3rdParty/LightPcapNg/LightPcapNg/src/light_pcapng_ext.c#L417), I believe comparison with zero is not needed in that case also.

**Comment by seladb** [comment]
Thanks @Akvinikym for the quick response!
@IVIexx I guess we can remove that part and test that everything works. Would you consider opening a PR with a fix? It seems that you have a pcapng file you can test it with...

**Comment by seladb** [comment]
@IVIexx will you consider opening a PR with the fix?

**Comment by IVIexx** [comment]
I was testing if it works when I undo the changes from that commit. This works for me and I am using this code now.
I am usually not using github, so I would prefer not to make the pull request, since I am not so familiar with the workflow.

**Comment by seladb** [comment]
if you're interested in learning about pull requests here is a short guide from GitHub:
https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
This should be an easy fix and a learning opportunity for you, let me know if you're interested

**Comment by seladb** [comment]
Fixed in https://github.com/seladb/PcapPlusPlus/commit/0a5716b841c7c671026added8f89b49c2f89ab93
Thanks for reporting this issue, much appreciated!
