### ISSUE TITLE
Linux cooked capture header

### ISSUE THREAD

**Issue by pchaigno** [seladb/PcapPlusPlus#66]
I just compiled (from 0283655f274cdfff56adbf5b5076665784fc99f4) and ran PcapSplitter on a pcap file captured with tcpdump. I get the following error:
```
$ tcpdump --version
tcpdump version 4.9.2
libpcap version 1.7.4
$ file tmp.pcap
tmp.pcap: tcpdump capture file (little-endian) - version 2.4 (Linux "cooked", capture length 262144)
$ ./Bin/PcapSplitter -f tmp.pcap -o tmp -m connection
Cannot write a packet with a different link layer type
Cannot write a packet with a different link layer type
... (1 per packet)
Cannot write a packet with a different link layer type
Cannot write a packet with a different link layer type
```
The output files are all empty.

**Comment by seladb** [comment]
It seems that the pcap file you're trying to split has more than one link type, which mean it's actually a pcapng file and not a pcap file. Could you please try to rename the file from tmp.pcap to tmp.pcapng and run PcapSplitter again?

**Comment by pchaigno** [comment]
Thanks for the quick answer!

Looks like I opened this issue a bit too quickly. While it is a pcap file, it looks like when using `tcpdump -i any`, Linux replaces the link layer header by its own *Linux cooked capture* header. This new header is causing the present issue. If I limit the capture to a specific Ethernet interface, it works fine.

Not sure that's something you can accomodate...? If not, feel free to close this issue :smiley:

**Comment by seladb** [comment]
I'm not entirely sure what you mean. PcapPlusPlus supports both Ethernet and Linux cooked capture link types. So if your pcap file's link type is Linux cooked capture PcapSplitter should work...
Is it possible you send me a sample of the problematic pcap file?

**Comment by pchaigno** [comment]
I can't share the whole pcap file, but I might be able to share a subset. Let me see...

I captured it (I tried with 3 other captures and I always have the same error) with the following command:
```
tcpdump -i any -w tmp.pcap
```
while receiving and sending packets over both a loopback interface and a Wi-Fi interface.

All packets do have the same link type (Linux cooked capture).

**Comment by pchaigno** [comment]
Here is a minimal, anonymized capture file, with a single packet. I still have the error with this single packet: [sample.zip](https://github.com/seladb/PcapPlusPlus/files/1308682/sample.zip)

**Comment by seladb** [comment]
The file you sent me is in pcap-ng format:

![image](https://user-images.githubusercontent.com/9059541/30520487-8c6a5bb2-9bb7-11e7-8359-21151a4e2875.png)

When I convert it into pcap format it works

**Comment by pchaigno** [comment]
Ah! That's because I used editcap without changing the default output format.
Here it is again: [sample.zip](https://github.com/seladb/PcapPlusPlus/files/1309050/sample.zip)

**Comment by seladb** [comment]
There was indeed a bug, thanks for founding it!
I fixed it, please pull the latest code

**Comment by pchaigno** [comment]
Glad I could help!

**Comment by fridayguo** [comment]
at file PcapLiveDevice.cpp:132 
>  RawPacket rawPacket(packet, pkthdr->caplen, pkthdr->ts, false, LINKTYPE_ETHERNET);

when listening on the interface "any",  this link type LINKTYPE_ETHERNET  is wrong.

**Comment by seladb** [comment]
Currently PcapPlusPlus supports packet capture from Ethernet devices only, but this could be changed of course. I suggest you open a separate issue for that
