### ISSUE TITLE
[Feature Request] Read packet comment from pcang

### ISSUE THREAD

**Issue by Matheus-Garbelini** [seladb/PcapPlusPlus#660]
Dear all, is there some way to read back the packet comment we have written using pcang writer class?

Since I'm using comments as a way to save packet analysis information, It would be useful to read those values back when iterating over a packet loop with the reader class.

Is there some way I can do that even if it involves applying some workaround to the current library?

Regards.

**Comment by seladb** [comment]
hi @Matheus-Garbelini , thanks for reaching out!
Yes, [`pcpp::PcapNgFileReaderDevice`](https://pcapplusplus.github.io/api-docs/classpcpp_1_1_pcap_ng_file_reader_device.html) allows reading the packet comment, please take a look at [`getNextPacket()`](https://pcapplusplus.github.io/api-docs/classpcpp_1_1_pcap_ng_file_reader_device.html#a9bf1e61be8334e31a329451ad2397b27) which takes the `packetComment` parameter which you can read the comment from.

You can also see here how to use it:
https://github.com/seladb/PcapPlusPlus/blob/7d3c3db327a96d73c8b0e1a2484653b9c0676d63/Examples/PcapPrinter/main.cpp#L168

**Comment by Matheus-Garbelini** [comment]
Hi @seladb thanks a lot, I didn't see that.
