### ISSUE TITLE
capture packet change its payload 

### ISSUE THREAD

**Issue by amir110** [seladb/PcapPlusPlus#661]
Hi
i am new to this library .
i want to know is it possible to capture packets and changes its content, payload ... and resend it?

**Comment by seladb** [comment]
Yes, this should be possible. Please see the tutorials: https://pcapplusplus.github.io/docs/tutorials

In particular: 
 - capture/send packets: https://pcapplusplus.github.io/docs/tutorials/capture-packets
 - packet crafting: https://pcapplusplus.github.io/docs/tutorials/packet-crafting

**Comment by seladb** [comment]
I'm closing this issue now, please reopen if relevant
