### ISSUE TITLE
the Ethernet type of VLAN is not fixed

### ISSUE THREAD

**Issue by hlzeng2011** [seladb/PcapPlusPlus#665]
In function of EthLayer::computerCalculateFields(), the Ethernet type of VLAN may be STAG or CTAG. So the Ethernet type should be configurable.

**Comment by seladb** [comment]
what are these ether types? I don't know them...

**Comment by hlzeng2011** [comment]
the TPID of VLAN, it may be 0x88a8 0011, or 0x8100 0011

**Comment by hlzeng2011** [comment]
I consider them as Ethernet type:),
Currently, it can only use CTAG(0x8100) as the first VLAN tag

**Comment by seladb** [comment]
hi @hlzeng2011 , is the structure of S-TAG vlan the same as C-TAG?

**Comment by hlzeng2011** [comment]
Hi Saladb, Yes, only the tpid is 0x88a8 instead of 0x8100. Thanks Hlzeng

**Comment by seladb** [comment]
The fix is pushed to `master`. Thanks for reporting this issue!
