### ISSUE TITLE
the bottom flag of MPLS label

### ISSUE THREAD

**Issue by hlzeng2011** [seladb/PcapPlusPlus#666]
Hi,
The condition of setbottomflag in MplsLayer::computerCalculateField should be != MPLS.

**Comment by seladb** [comment]
@hlzeng2011 you're right, thanks for reporting this issue! Would you consider opening a PR with the fix?

**Comment by hlzeng2011** [comment]
I don't know how to open a PR and i am a beginner of github

**Comment by hlzeng2011** [comment]
I don't know how to open a PR and i am a beginner of github

**Comment by seladb** [comment]
I encourage you to try @hlzeng2011 ! Here is a short guide from GitHub on how to create pull requests:
https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
Let me know if you're interested...

**Comment by seladb** [comment]
Fixed in https://github.com/seladb/PcapPlusPlus/commit/9c8f376a5af44466152dfb8f22634842fb7134e4
Thank you so much for reporting this issue!
