### ISSUE TITLE
It doesn't support Ethernet over GRE

### ISSUE THREAD

**Issue by hlzeng2011** [seladb/PcapPlusPlus#668]
Hi,
In the function of GreLayer::computerCalculaterFields, it needs support Ethernet protocol instead of VLAN protocl.

**Comment by seladb** [comment]
@hlzeng2011 why does it need to support Ethernet instead of VLAN and not together with VLAN?

**Comment by hlzeng2011** [comment]
Hi Seladb, The ethernet over GRE is more useful than VLAN over GRE. Thanks Hlzeng

**Comment by seladb** [comment]
so should we support both?

**Comment by hlzeng2011** [comment]
Hi Seladb, Yes, it would be better. Thanks Hlzeng

**Comment by seladb** [comment]
@hlzeng2011 just to make sure I'm getting this right: if the next layer after GRE is Ethernet then the GRE protocol type should be `Transparent Ethernet Bridging 0x6558`?

**Comment by hlzeng2011** [comment]
Hi Seladb, Yes, we always using ethernet/ip/mpls over GRE. Thanks Hlzeng

**Comment by seladb** [comment]
The fix is pushed to `master`. Thank you for reporting this issue!
