### ISSUE TITLE
Capture URLs of media files

### ISSUE THREAD

**Issue by Deleora** [seladb/PcapPlusPlus#669]
Hey, I was wondering if I could use this repo to capture exact URLs of media files being fetched from apps like direct links of posts on Instagram. Is it possible? I'm completely clueless how this works so any help is really appreciated!
Thank you.

**Comment by seladb** [comment]
PcapPlusPlus focuses mostly on capturing, parsing, and crafting of network packets. What you're referring to is parsing of websites and media files which are out of the scope of this project. Essentially what you need is a tool that can:
- Decrypt the web traffic, as most websites use TLS
- Scrape the specific website you're interested in (Instagram for example) and find the media files links
- Follow the link to the media file, fetch it, and parse it. There are different parsers, depends on the media file type (images, videos, etc.)

I'm not sure PcapPlusPlus is the right tool for this job...

**Comment by seladb** [comment]
@Deleora I'm closing this issue now, please reopen if needed

**Comment by Deleora** [comment]
Alright, I think I understand. Anyways, thanks for letting me know. I really appreciate it!
