### ISSUE TITLE
[logic error] happened in SSLHandshake.cpp

### ISSUE THREAD

**Issue by bug65536** [seladb/PcapPlusPlus#673]
hi,there is a logic error happened in SSLHandshake.cpp, however, i can not provide sample cap file.
in the source code of
[SSLHandshake.cpp](https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/src/SSLHandshake.cpp)

line 1333,

`curPos += newExt->getTotalLength();`

however, if the return length `newExt->getTotalLength()==0`, **curPos will never change, and the loop will never break**.

so, i think you should check first like this:

`if (newExt->getTotalLength() > 0)`
`curPos += newExt->getTotalLength();`
`else`
`break;`

sorry, i write c/c++ badly.

**Comment by seladb** [comment]
thanks for reaching out!
Maybe I'm missing something but I think this code already exists, no?
https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/src/SSLHandshake.cpp#L1325-L1329

**Comment by bug65536** [comment]
i am sorry for wasting your time. maybe i got the old version of source code. :-)
