### ISSUE TITLE
How to build a complete packet using PcapPlusPlus?Is there some introduction step by step?

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#683]
How to build a complete packet using PcapPlusPlus?Is there some introduction step by step?
I wrote a NetFlow edit test app with the parameters in .dat, but the result packet is not equal to the .dat file.
I do no know what's the wrong? I do not know which fields of IP/UDP/TCP layers will be filled.

**The step 7 report assert:**
"NetFlowV1CreateAndEditTest    : FAILED (Tests/NetFlowTests.cpp:118). assert equal failed: actual: 105 != expected: 106"

**Below are some code snippets related to constructing a message.** 

   ```
    PTF_TEST_CASE(NetFlowV1CreateAndEditTest)
{
    /** 1.Build ethernet/IP/UDP header */
    pcpp::EthLayer ethLayer(pcpp::MacAddress("ca:01:33:92:00:08"), pcpp::MacAddress("00:50:79:66:68:00"));

    pcpp::IPv4Address srcIp("192.168.10.100");
    pcpp::IPv4Address dstIp("192.168.10.254");
    pcpp::IPv4Layer ipLayer(srcIp, dstIp);
    ipLayer.getIPv4Header()->ipId = htobe16(0xdde);
    ipLayer.getIPv4Header()->timeToLive = 255;

    pcpp::UdpLayer udpLayer(61985, 9996);

    /** 2.Build NetFlow header */
    pcpp::NetFlowV1Header v1Header;
    memset(&v1Header, 0, sizeof(v1Header));
    v1Header.version = pcpp::hostToNet16(NetFlow_Version_1);
    v1Header.count = pcpp::hostToNet16(0);
    v1Header.sysUptime = pcpp::hostToNet16(0xdac8);
    v1Header.unix_secs = pcpp::hostToNet32(0x60b4e857);
    v1Header.unix_nsecs = pcpp::hostToNet32(0x039335be);

    pcpp::NetFlowV1Layer netFlowV1Layer;
    netFlowV1Layer.setNetFlowHeader((uint8_t*)&v1Header);
    PTF_ASSERT_NOT_NULL(&netFlowV1Layer)
    PTF_ASSERT_EQUAL(netFlowV1Layer.getVersionByData(), 1, int)

    /** 3.Build NetFlow record */
    pcpp::NetFlowV1Record v1Record1;
    memset(&v1Record1, 0, sizeof(v1Record1));
    v1Record1.dPkts = pcpp::hostToNet32(1);
    v1Record1.dOctets = pcpp::hostToNet32(80);
    v1Record1.first = pcpp::hostToNet32(80);
    v1Record1.last = pcpp::hostToNet32(0x76ec);
    v1Record1.input = pcpp::hostToNet32(0x76ec);
    pcpp::IPv4Address ipv4SrcAddress1("10.1.12.2");
    uint32_t ipv4SrcAddressInt1 = pcpp::hostToNet32(ipv4SrcAddress1.toInt());
    v1Record1.srcaddr = ipv4SrcAddressInt1;
    pcpp::IPv4Address ipv4DstAddress1("10.1.12.1");
    uint32_t ipv4DstAddressInt1 = pcpp::hostToNet32(ipv4DstAddress1.toInt());
    v1Record1.dstaddr = ipv4DstAddressInt1;
    v1Record1.proto = 89;
    v1Record1.tos = 0xc0;
    v1Record1.tcp_flags = 0x10;

    uint8_t* record1 = netFlowV1Layer.addRecordAtLast((uint8_t*)&v1Record1);
    PTF_ASSERT_NOT_NULL(record1)

    /** 4.Build all layers */
    pcpp::Packet netflowV1Packet;
    PTF_ASSERT_TRUE(netflowV1Packet.addLayer(&ethLayer))
    PTF_ASSERT_TRUE(netflowV1Packet.addLayer(&ipLayer))
    PTF_ASSERT_TRUE(netflowV1Packet.addLayer(&udpLayer))
    PTF_ASSERT_TRUE(netflowV1Packet.addLayer(&netFlowV1Layer))

    //netFlowV1Layer.computeCalculateFields();

    /** 5.Remove and add netflow record */
    PTF_ASSERT_TRUE(netFlowV1Layer.removeRecordAtIndex(0));

    netFlowV1Layer.addRecordAtLast((uint8_t*)&v1Record1);
    PTF_ASSERT_NOT_NULL(record1)

    pcpp::LoggerPP::getInstance().suppressErrors();
    PTF_ASSERT_FALSE(netFlowV1Layer.removeRecordAtIndex(4));
    (netFlowV1Layer.getNetFlowHeader())->countOrLen = htobe16(100);
    PTF_ASSERT_FALSE(netFlowV1Layer.removeRecordAtIndex(4));
    pcpp::LoggerPP::getInstance().enableErrors();

    /** 6.Read netflow file to buffer */
    READ_FILE_INTO_BUFFER(1, "PacketExamples/NetFlow-V1.dat")

    /** 7.Compare the packet content with the buffer of file */
    PTF_ASSERT_EQUAL(netflowV1Packet.getRawPacket()->getRawDataLen(), FILE_INTO_BUFFER_LENGTH(1), int);
    PTF_ASSERT_BUF_COMPARE(netflowV1Packet.getRawPacket()->getRawData(), FILE_INTO_BUFFER(1), netflowV1Packet.getRawPacket()->getRawDataLen());

    FREE_FILE_INTO_BUFFER(1);
}
```

**Comment by seladb** [comment]
I'm not sure how you built the netflow layer, but in order to debug the differences you can use `savePacketToPcap()` that is inside `TestUtils.h`. You need to build Packet++Test with `PCPP_TESTS_DEBUG` build flag:

https://github.com/seladb/PcapPlusPlus/blob/f94bbf8133a32033fcb80b765d543ce147f57a46/Tests/Packet%2B%2BTest/Utils/TestUtils.h#L32

**Comment by angelyouyou** [comment]
@seladb 
I have push my complete code in my [repository](https://github.com/angelyouyou/PcapPlusPlus)

**Comment by angelyouyou** [comment]
@seladb 
They are different on IP layer and other upper-layers.

My packet built(NetFlowV1CreateAndEditTest) is:
00 50 79 66 68 00 ca 01 33 92 00 08 00 00 05 00
00 00 0d de 00 00 ff 00 00 00 c0 a8 0a 64 c0 a8
0a fe f2 21 27 0c 00 00 00 00 00 01 00 64 da c8
00 00 60 b4 e8 57 03 93 35 be 02 0c 01 0a 01 0c
01 0a 00 00 00 00 00 00 00 00 00 00 00 01 00 00
00 50 00 00 00 50 00 00 76 ec 00 00 00 00 00 00
59 c0 10 00 00 00 00 00 00
[my packet built.pcap.zip](https://github.com/seladb/PcapPlusPlus/files/6791518/my.packet.built.pcap.zip)

NetFlow-V1.dat :
005079666800ca013392000808004500005c0dde0000ff111700c0a80a64c0a80afef221270c00486e62000100010000dac860b4e857039335be0a010c020a010c0100000000000300000000000100000050000076ec000076ec00000000000059c01000000000000000
[NetFlow-V1.pcap.zip](https://github.com/seladb/PcapPlusPlus/files/6791520/NetFlow-V1.pcap.zip)

**Comment by angelyouyou** [comment]
> I'm not sure how you built the netflow layer, but in order to debug the differences you can use `savePacketToPcap()` that is inside `TestUtils.h`. You need to build Packet++Test with `PCPP_TESTS_DEBUG` build flag:
> 
> https://github.com/seladb/PcapPlusPlus/blob/f94bbf8133a32033fcb80b765d543ce147f57a46/Tests/Packet%2B%2BTest/Utils/TestUtils.h#L32

It's my mistakes.Thanks.
I will write some instructions for packet creation.
