### ISSUE TITLE
CentOS 7 DpdkTrafficFilter Floating point exception (core dumped)

### ISSUE THREAD

**Issue by wo0d** [seladb/PcapPlusPlus#69]
First, I run setup-dpdk.sh, the result: 
*******************************
PcapPlusPlus setup DPDK script 
*******************************

1. Reserve huge-pages - DONE!
2. 00:03.0 is already binded to DPDK or doesn't exist. Exiting

Network devices using DPDK-compatible driver
============================================
0000:00:03.0 '82540EM Gigabit Ethernet Controller' drv=igb_uio unused=

Network devices using kernel driver
===================================
0000:00:08.0 '82540EM Gigabit Ethernet Controller' if=enp0s8 drv=e1000 unused=igb_uio *Active*

Other network devices
=====================
<none>

Crypto devices using DPDK-compatible driver
===========================================
<none>

Crypto devices using kernel driver
==================================
<none>

Other crypto devices
====================
<none>

Then run DpdkTrafficFilter, Floating point exception…… result: 
[root@localhost examples]# ./DpdkTrafficFilter -d 0
EAL: Detected 1 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:00:03.0 on NUMA socket -1
EAL:   probe driver: 8086:100e net_e1000_em
EAL: PCI device 0000:00:08.0 on NUMA socket -1
EAL:   probe driver: 8086:100e net_e1000_em
Floating point exception (core dumped)

**Comment by wo0d** [comment]
[root@localhost examples]# ./DpdkTrafficFilter -l
EAL: Detected 1 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:00:03.0 on NUMA socket -1
EAL:   probe driver: 8086:100e net_e1000_em
EAL: PCI device 0000:00:08.0 on NUMA socket -1
EAL:   probe driver: 8086:100e net_e1000_em
EAL: PCI device 0000:00:09.0 on NUMA socket -1
EAL:   probe driver: 8086:100e net_e1000_em
DPDK port list:
    Port #0: MAC address='08:00:27:08:b9:24'; PCI address='0000:00:08.0'; PMD='net_e1000_em'
    Port #1: MAC address='08:00:27:54:8b:2b'; PCI address='0000:00:09.0'; PMD='net_e1000_em'


[root@localhost examples]# ./DpdkTrafficFilter -d 0 -s 1
EAL: Detected 1 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:00:03.0 on NUMA socket -1
EAL:   probe driver: 8086:100e net_e1000_em
EAL: PCI device 0000:00:08.0 on NUMA socket -1
EAL:   probe driver: 8086:100e net_e1000_em
EAL: PCI device 0000:00:09.0 on NUMA socket -1
EAL:   probe driver: 8086:100e net_e1000_em
Floating point exception (core dumped)

**Comment by wo0d** [comment]
[root@localhost examples]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)

**Comment by seladb** [comment]
Did you try running DpdkTrafficFilter with sudo?

**Comment by wo0d** [comment]
I run DpdkTrafficFilter with root user.
but i run it in VMWare CentOS system, when i setting the system to use 2 cpu cores, this problem solved……
btw, sorry for my ugly english,I don't even know if you understand what I'm talking about

**Comment by seladb** [comment]
Fixed in commit: https://github.com/seladb/PcapPlusPlus/commit/98abc4c097e017969286717000d1897f61be5d1e
