### ISSUE TITLE
Does pcapplusplus support dhcpv6?

### ISSUE THREAD

**Issue by amitguptakiitian** [seladb/PcapPlusPlus#690]
is dhcpv6 supported on pcapplusplus? if not then any idea when this feature will be available with pcapplusplus?

**Comment by seladb** [comment]
@amitguptakiitian thanks for reaching out!
Unfortunatly dhcpv6 isn't currently supported in PcapPlusPlus and I don't have concrete plans to add it. But you're more than welcome to add it and contribute back to the project, I can guide you on how to do that.

**Comment by seladb** [comment]
Done in commit https://github.com/seladb/PcapPlusPlus/commit/a86c2a12f5b9dcbf3278b925dff1e53b244044a5

**Comment by amitguptakiitian** [comment]
Thanks @seladb for adding DHCPv6 support in PcapPlusPlus. Any plan for tagging the repo?
