### ISSUE TITLE
Does PcapPlusPlus provide thread-safe packet parsing or creation function?

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#703]
Judging from some codes (such as BGPLayer, TLVData, etc.), the STL container library is used, which may cause unsafe writing under multi-threaded scenarios in certain performance requirements.

**Comment by seladb** [comment]
If you ask whether a `Packet` or a `Layer` object can be accessed from multiple threads for edit/write then the answer is no. It is assumed that each layer/packet is parsed/edited/forged in a single thread, and then it can be accessed for reading by other threads.
Please let me know if that answers your question.

**Comment by angelyouyou** [comment]
> If you ask whether a `Packet` or a `Layer` object can be accessed from multiple threads for edit/write then the answer is no. It is assumed that each layer/packet is parsed/edited/forged in a single thread, and then it can be accessed for reading by other threads.
> Please let me know if that answers your question.

In many cases, we need to analyze a certain type of message in a high-concurrency, multi-threaded environment to improve business processing performance. In this case, is there any good solution to use the PcapPlusPlus library?

**Comment by seladb** [comment]
This is a complex question and depends a lot on the specific use case. If you're using DPDK, for example, you can build a multi-threaded application where each thread is running on a different core and DPDK does the load balance between them. PcapPlusPlus supports DPDK, so you can use them together.

If you're using libpcap you can design an application that, for example, uses a process/core/thread to capture packets and then analyze them in a different thread or thread pool in a way that the heavy lifting is done in these workers, and there is a queue between the capture thread and the processing threads.

Again, it depends on your use-case. PcapPlusPlus provides packet analysis capabilities but the architecture of your application is on you 😃

**Comment by angelyouyou** [comment]
> This is a complex question and depends a lot on the specific use case. If you're using DPDK, for example, you can build a multi-threaded application where each thread is running on a different core and DPDK does the load balance between them. PcapPlusPlus supports DPDK, so you can use them together.
> 
> If you're using libpcap you can design an application that, for example, uses a process/core/thread to capture packets and then analyze them in a different thread or thread pool in a way that the heavy lifting is done in these workers, and there is a queue between the capture thread and the processing threads.
> 
> Again, it depends on your use-case. PcapPlusPlus provides packet analysis capabilities but the architecture of your application is on you 😃

Judging from the current test benchmarks, the performance of PcapPlusPlus is good enough (using libpcap), and it is likely to meet my performance requirements. If the performance requirements are not met, I will consider using the DPDK solution in PcapPlusPlus.
thank you very much.
