### ISSUE TITLE
Can TLVRecord's type and length can extend to uint16_t type?Many cases need the uint16_t type to storage.

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#704]
TLVRecordType getTLVRecord(uint8_t recordType, uint8_t* tlvDataBasePtr, size_t tlvDataLen) const

**Comment by seladb** [comment]
Yes, I'm aware that certain protocols use `uint16_t` for the type and therefore can't use the `TLVRecord` infrastructure.
`PPPoETag` and `SSLExtension` are good examples of that.
The solution would be to make `TLVRecord` a templated class that can take any type for the `type` and `recordLen` fields. This will require various changes in `TLVRecord`, `TLVRecordBuilder` and perhaps also in `TLVRecordReader`. We can add it to the backlog, unless you're will to take up this work.

**Comment by angelyouyou** [comment]
Thanks for your help.
I am trying to add netflowv1/v5/v7/v9/ipfix protocol and support customed port(s) of TCP or UDP protocol.There is still a lot of work to be done.After these I will try to it.

**Comment by seladb** [comment]
The fix was pushed to `master`
