### ISSUE TITLE
It is recommended to add the description of the "Sending Packets" feature to the "Feature Overview" page.

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#705]
So that readers can know that the current PcapPlusPlus supports sending capabilities.
![image](https://user-images.githubusercontent.com/12936259/132834262-92e5c858-8492-470c-8363-1401d8e8aea1.png)

[Sending Packets](https://pcapplusplus.github.io/docs/tutorials/capture-packets) add to [Feature Overview
](https://pcapplusplus.github.io/docs/features) pages.

**Comment by seladb** [comment]
This is already mentioned in the Feature Overview, here:
https://pcapplusplus.github.io/docs/features#packet-capture

> The main features provided for each one are:
> 
> - Browse all interfaces available on the machine
> - Capture network traffic on a specific interface
> - HERE ==> Send packets to the network <== HERE
> - Filter packets
