### ISSUE TITLE
is there a function to get mac address from pcap file?

### ISSUE THREAD

**Issue by bug65536** [seladb/PcapPlusPlus#707]
hi, i can get ip address like this:

`
// parse the raw packet into a parsed packet
pcpp::Packet parsedPacket(&rawPacket);

// check if it's an IPv4 packet
if (parsedPacket.isPacketOfType(pcpp::IPv4)) {
  // extract source and dest IPs
  pcpp::IPv4Address srcIP = 
    parsedPacket.getLayerOfType()->getSrcIpAddress();
  pcpp::IPv4Address destIP = 
    parsedPacket.getLayerOfType()->getDstIpAddress();

  // print source and dest IPs
  printf("Source IP is '%s'; Dest IP is '%s'\n", 
    srcIP.toString().c_str(), destIP.toString().c_str());
}
`

is there a function to get mac address ?

thanks!

**Comment by seladb** [comment]
yes, of course! Here is the easiest way to get the MAC address:

```cpp
// parse the raw packet into a parsed packet
pcpp::Packet parsedPacket(&rawPacket);

// assuming this is an Ethernet packet
pcpp::EthLayer* ethLayer = parsedPacket.getLayerOfType<pcpp::EthLayer>();
pcpp::MacAddress srcMac = ethLayer->getSourceMac();
pcpp::MacAddress dstMac = ethLayer->getDestMac();

// print source and dest MAC
printf("Source MAC address is: %s; Dest MAC address is: %s\n", srcMac.toString().c_str(), dstMac.toString().c_str());
```

**Comment by bug65536** [comment]
thank you very much! it helps a lot!
