### ISSUE TITLE
Pcap Packet Decode

### ISSUE THREAD

**Issue by ashokmcapbi** [seladb/PcapPlusPlus#709]
Is there any method or example to get complete pcap packet decode like wireshark?

**Comment by seladb** [comment]
PcapPlusPlus is not exactly like wireshark, but you can find a good example in this tutorial:
https://pcapplusplus.github.io/docs/tutorials/packet-parsing

Please let me know if you have more questions.

**Comment by seladb** [comment]
I'm closing this issue now, please reopen if needed.

**Comment by ashokmcapbi** [comment]
> PcapPlusPlus is not exactly like wireshark, but you can find a good example in this tutorial:
> https://pcapplusplus.github.io/docs/tutorials/packet-parsing
> 
> Please let me know if you have more questions.

Thanks for the reply. 
I read this article but my requirement is different. I need to display complete TCP Packet decode like wireshark. it seems I have to write custom code to achieve that.

**Comment by seladb** [comment]
> Thanks for the reply.
> I read this article but my requirement is different. I need to display complete TCP Packet decode like wireshark. it seems I have to write custom code to achieve that.

I think you can use some of the code in [`pcpp::Packet::toString()`](https://github.com/seladb/PcapPlusPlus/blob/ff2268c06f94af748a275a98f3fa25e20d385d39/Packet%2B%2B/header/Packet.h#L307) or [`pcpp::Packet::toStringList()`](https://github.com/seladb/PcapPlusPlus/blob/ff2268c06f94af748a275a98f3fa25e20d385d39/Packet%2B%2B/header/Packet.h#L314) to print general info for the various layers in the packet

**Comment by ashokmcapbi** [comment]
I already looked in the these functions. my requirement is to display packet data like :

 version   = 6,  tc        = 0,  fl        = 168505,plen      = 1376,  nh        = Fragment Header,  hlim      = 255,  src       = 2001:268:b16b:ed6d:0:d:1e13:be01,  dst       = 2001:268:e637:8012::8
[IPv6 Extension Header - Fragmentation header ] 
     nh        = ESP Header,  res1      = 0,     offset    = 0,     res2      = 0,     m         = 1,     id        = 1433296607
[ ESP ] 
        spi       = 0xb670cb74,        seq       = 4

I think I have to write individual value of each parameter. Is there any example or function which output bit similar to this
