### ISSUE TITLE
Can we define a new macro for LOG_ERROR/DEBUG/INFO and other macros based on parameter formatting?

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#711]
The definition of the LOG_ERROR macro has been changed to the C++ stream mode in the new version. In this case, it is more cumbersome to use when formatting multiple parameters and alternating strings. Can we define a new macro based on parameter formatting? This simplifies the formatting operation.

New:
![image](https://user-images.githubusercontent.com/12936259/133595786-07927258-996f-4d49-a793-2a9d94fde9ce.png)

Old:
![image](https://user-images.githubusercontent.com/12936259/133595827-6b1dd644-15c9-4cc9-a15a-a0566a632469.png)

**Comment by seladb** [comment]
why is this cumbersome? can you give an example?

also, I'm curious why do you need to use it, are you extending PcapPlusPlus code?

I recently refactored the internal logger of PcapPlusPlus and improved its code, this is why I changed the macros.

**Comment by angelyouyou** [comment]
> why is this cumbersome? can you give an example?
> 
> also, I'm curious why do you need to use it, are you extending PcapPlusPlus code?
> 
> I recently refactored the internal logger of PcapPlusPlus and improved its code, this is why I changed the macros.
Yes. I am extending the NetFLow protocol of PcapPlusPlus.

Using old C-Style(printf) way, a complete debug content can be written coherently, and parameters can be added after the string.
After adopting the C++ stream method, the format of strings and parameters cannot be written out completely, and many output symbols (<<) need to be added.

New code about:
`LOG_ERROR("Parse NetFlow v9 data flowset "
                              << NetFlowV9Template::getNetFlowTemplateName(templateType)
                              << "failed, for data length(" << remain
                              << ")is smaller than template(" << totalBytes << ").");`

Old ode：
`LOG_ERROR("Parse NetFlow v9 data flowset %s failed, for data length(%u) is smaller than template(%d).", name, remain,totalBytes);`

**Comment by seladb** [comment]
I agree it's a little less readable but it's much easier to print different types without worrying about their format, which might differ between platforms. For example: using c-format to print a `uint64_t` variable is not the same on all platforms. On some platforms `PRId64` should be used, on others `%llu` or `%I64d`.
With the stream operator `<<` you don't need to worry about all this.

**Comment by angelyouyou** [comment]
> I agree it's a little less readable but it's much easier to print different types without worrying about their format, which might differ between platforms. For example: using c-format to print a `uint64_t` variable is not the same on all platforms. On some platforms `PRId64` should be used, on others `%llu` or `%I64d`.
> With the stream operator `<<` you don't need to worry about all this.

OK.Thanks.
I have change my code to adapt the stream method.
