### ISSUE TITLE
How to open the LOG_DEBUG of module or adjust the output level?

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#712]
I add NetFlow protocol in PcapPlusPlus, I  add enum type in LogModule
![image](https://user-images.githubusercontent.com/12936259/133726495-78911fb2-0b9d-433a-9a6a-29debdaec274.png)

After that I add LOG_DEBUG in my files.But there is no any debug output(debug code is excuted).
`LOG_DEBUG("Get NetFlow record failed, for protocol is invalid.");`

How to open the LOG_DEBUG to output and adjust the output level?Are there some code snippets of logger module?

**Comment by seladb** [comment]
You need to add a `#define` statement in the top of your source file:

```cpp
#define LOG_MODULE PacketLogModuleNetFlowLayer
```

Here is an example: https://github.com/seladb/PcapPlusPlus/blob/a285b4521b56762d241aa5780ee1075027190863/Packet%2B%2B/src/ArpLayer.cpp#L1

**Comment by angelyouyou** [comment]
Thanks very much.My debug information is out.It is recommended to add an example description in document.
