### ISSUE TITLE
[Question]Packet parsing for tun devices

### ISSUE THREAD

**Issue by karnilamit** [seladb/PcapPlusPlus#715]
Hi,
I am working on a project which reads packets from a tun interface in Linux. The packets received need to be parsed for IPv4 headers to determine the actual source and destination.  The buffer in which the packets are stored can have more than 1 IP packet. What would be the best approach to have Packet++ parse those packets? I don't see any API's in Packet or RawPacket to traverse a sequence of packets. Can someone help me with the same?

Thanks,
A.K.

**Comment by seladb** [comment]
hi @karnilamit , do you know which link layer your packets are captured with?
If you use PcapPlusPlus to capture packets you can do:

```cpp
static void onPacketArrives(pcpp::RawPacket* packet, pcpp::PcapLiveDevice* dev, void* cookie)
{
	pcpp::LinkLayerType linkType = packet->getLinkLayerType();
	std::cout << "The link layer type is: " << linkType << std::endl;
}
```

When parsing a packet the first layer is determined by the link layer type. If it's of one of these types: `pcpp::LINKTYPE_RAW`, `pcpp::LINKTYPE_DLT_RAW1`, `pcpp::LINKTYPE_DLT_RAW2`, `pcpp::LINKTYPE_IPV4`, `pcpp::LINKTYPE_IPV6` then the first layer will (usually) be IPv4/IPv6.
You can see the first layer parsing code here: https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/src/Packet.cpp#L706-L774

If you're parsing packets directly from a byte array, you need to create a `RawPacket` with one of these link types, for example:

```cpp
// assuming you have a `buffer` and `bufferSize`
pcpp::RawPacket rawPacket(buffer, bufferSize, false, pcpp::LINKTYPE_RAW);
pcpp::Packet parsePacket(&rawPacket);
```

Please let me know if you have any questions.

**Comment by karnilamit** [comment]
Thanks @seladb 
I will be parsing packets directly from a byte array. Those will be of type LINKTYPE_IPV4, The buffer will have many packets of IPV4 type (It's a circular buffer to store packets as they are received). For simplicity, let's assume that the buffersize will always be at packet boundaries.
How do I quickly traverse the entire buffer for all the packets?
Is there any way I can do
pcpp:Packet p = currentPacket->next(); ??
I can do this in my source code based on the packet length, but was wondering if I can traverse all the packets using Packet++ itself.

**Comment by seladb** [comment]
Unfortunately no, a `Packet` object is designed to store and parse one packet only. If you have a buffer of many packets, how do you know the size of each packet? Meaning where in the buffer one packet ends and the next begins?

If you do know the sizes you can probably iterate over the buffer and create a `Packet` object for each portion of the buffer that contains a full packet 🤔

**Comment by karnilamit** [comment]
Thanks @seladb 
We got the packet length pushed with each packet so the method you mentioned should work. Thanks again for taking time to respond.
