### ISSUE TITLE
How to get xxxLayer from PcapLiveDevice. reassemble and verify the received packets.

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#719]
I want to use PcapLiveDevice or WinPcapLiveDevice class to capture and real-time analysis NetFlow (based on UDP protocol) packets for improving packet receiving performance.
However, the packets captured by libpcap have not passed the kernel protocol stack (for winpcap I am not sure), so there is no way to guarantee reassembly and verification.
But these packets may be fragmented or wrong (errors in fields, checksums, etc.), or non-fragmented/valid IP and UDP layer packets.
In business, I only want to deal with the reorganized (or non-fragmented) and verified local (destination is the local unicast address) valid packets through the IP/UDP layer, 
which may be the scenario faced by many online real-time analysis.

What I want to ask is: 
when I get a data packet that contains the link layer, IP, UDP and payload, how to use PcapPlusPlus to verify the validity of the relevant layer and reorganize the packet (IP layer, TCP also May be involved).
How to convert the packet to xxxxLayer object?

If PcapPlusPlus do not support to verify, do you have some suggestions for me?
Thanks very much!

In addtion:
I found PcapPlusPlus support reassemble the packets, what is the timeout?

**Comment by seladb** [comment]
PcapPlusPlus supports 2 types of packet reassembly, both are mentioned [here](https://pcapplusplus.github.io/docs/features#packet-reassembly):
- IP reassembly (defragmentation) which basically turns IP fragments into a while IP packet
- TCP reassembly which reassembles TCP data split across multiple packets 

I think that what you need is IP defragmentation, so I suggest you read the documentation [here](https://pcapplusplus.github.io/api-docs/_i_p_reassembly_8h.html) and look at the [`IPFragUtil`](https://github.com/seladb/PcapPlusPlus/tree/master/Examples/IPFragUtil) example.
IP fragmentation doesn't have a timeout, it has a configurable limit on the number of packets to store in its buffer before it determines the fragment is lost forever. You can read about it in [`IPReassembly` c'tor documentation](https://pcapplusplus.github.io/api-docs/classpcpp_1_1_i_p_reassembly.html#a9a55c126f0361bc1a928d0e39924c16d).

I'm not sure what you mean by "validity" of a layer. Once a packet is parsed you can see if it contains a certain layer or not. Do you need anything beyond that?

**Comment by angelyouyou** [comment]
> an by "validity" of a layer. Once a packet is parsed you can see if it contains a certain layer or not. Do you need anything beyond that?

Thank you for the explanation on how IP handles fragmented packets. I have also seen the IPFragUtil example and IPReassembly, and I will continue the follow-up work.
Users of PcapPlusPlus often want to process only those packets that are correct (legal) at the IP, UDP, and TCP layers. Legal here means:
1. The packets have passed the IP, UDP/TCP checksum;
2. The fields in the IP, UDP, and TCP layers are legal. mainly includes:
(1) The IP header/total length, UDP and TCP length fields cannot be greater than the actual message length;
(2) UDP and TCP length fields cannot be greater than the actual message length and the total IP length;
(3) The fragment offset length cannot be greater than the total length of the IP;
(4) When the fragments are reassembled, if there is overlap or error in the offset length of the fragments, the fragments need to be ignored to ensure that there is no abnormality in the reassemble operation;
![image](https://user-images.githubusercontent.com/12936259/135008249-a9704551-8be3-4ded-bb09-4cef7f242427.png)
![image](https://user-images.githubusercontent.com/12936259/135009169-2134d14e-0921-4b50-9d3d-b1ef2c095bbe.png)


Add addtional, if the PcapPlusPlus user only wants to process the packets to the machine, I think it can be achieved with the filtering tool provided by PcapPlusPlus, as opposed to the query routing table in the standard protocol stack.

**Comment by angelyouyou** [comment]
> the same flow/stream

What I mean is the general check for headers such as IP, UDP and TCP, without considering the correlation between different packets. E.g:
1. Check whether the checksum of the IP header is correct;
2. For IP fragment packets, verify the correctness of the fragment offset, IP header and total length;
3. In addition to verifying the above 1, the UDP/TCP fragment packet verification needs to verify the correctness of the UDP/TCP length and its checksum;
4. TCP packets require logic such as window verification, which will be relatively troublesome, but there should be some related logic in the TCP reorganization.
-->Whether the above 1-3 can add general functions to the Layer class to facilitate the user to call? In addition, is there any combination solution proposal for this part that is missing relative to the standard kernel protocol stack?

**Comment by seladb** [comment]
@angelyouyou some of these checks already exist in PcapPlusPlus, especially checking the length which is relevant for parsing packets. Here are a few reference to the code:
- TCP checks: https://github.com/seladb/PcapPlusPlus/blob/f1a52b1092545e3a7d01fd931176123041be87ec/Packet%2B%2B/header/TcpLayer.h#L494-L500
- IPv4 checks: https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/header/IPv4Layer.h#L669-L673
- IPv6 checks: https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/header/IPv6Layer.h#L292-L295

However, there is no check for the correctness of the checksum because it's not relevant for parsing the packet. I do see a value in adding such method to the relevant layers, for example: `isChecksumCorrect()`. Would you consider adding that?

**Comment by angelyouyou** [comment]
> @angelyouyou some of these checks already exist in PcapPlusPlus, especially checking the length which is relevant for parsing packets. Here are a few reference to the code:
> 
> * TCP checks: https://github.com/seladb/PcapPlusPlus/blob/f1a52b1092545e3a7d01fd931176123041be87ec/Packet%2B%2B/header/TcpLayer.h#L494-L500
> * IPv4 checks: https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/header/IPv4Layer.h#L669-L673
> * IPv6 checks: https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/header/IPv6Layer.h#L292-L295
> 
> However, there is no check for the correctness of the checksum because it's not relevant for parsing the packet. I do see a value in adding such method to the relevant layers, for example: `isChecksumCorrect()`. Would you consider adding that?

@seladb 
OK.I will add these functions.

**Comment by angelyouyou** [comment]
> > @angelyouyou some of these checks already exist in PcapPlusPlus, especially checking the length which is relevant for parsing packets. Here are a few reference to the code:
> > 
> > * TCP checks: https://github.com/seladb/PcapPlusPlus/blob/f1a52b1092545e3a7d01fd931176123041be87ec/Packet%2B%2B/header/TcpLayer.h#L494-L500
> > * IPv4 checks: https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/header/IPv4Layer.h#L669-L673
> > * IPv6 checks: https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/header/IPv6Layer.h#L292-L295
> > 
> > However, there is no check for the correctness of the checksum because it's not relevant for parsing the packet. I do see a value in adding such method to the relevant layers, for example: `isChecksumCorrect()`. Would you consider adding that?
> 
> @seladb OK.I will add these functions.

`bool IPv4Layer::isChecksumCorrect(const uint8_t* data, size_t dataLen)
    {
        const iphdr* ipHdr = reinterpret_cast<const iphdr*>(data);
        size_t hdrLen = (ipHdr->internetHeaderLength) * 4 ;
        if (dataLen < hdrLen) {
            return false;
        }

        ScalarBuffer<uint16_t> scalar = { (uint16_t*)ipHdr, hdrLen } ;

        return (computeChecksum(&scalar, false) == 0);
    }`

![image](https://user-images.githubusercontent.com/12936259/135279307-b7e6c241-8337-4806-b159-e75eb0ecea95.png)

**Comment by angelyouyou** [comment]
> > > @angelyouyou some of these checks already exist in PcapPlusPlus, especially checking the length which is relevant for parsing packets. Here are a few reference to the code:
> > > 
> > > * TCP checks: https://github.com/seladb/PcapPlusPlus/blob/f1a52b1092545e3a7d01fd931176123041be87ec/Packet%2B%2B/header/TcpLayer.h#L494-L500
> > > * IPv4 checks: https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/header/IPv4Layer.h#L669-L673
> > > * IPv6 checks: https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/header/IPv6Layer.h#L292-L295
> > > 
> > > However, there is no check for the correctness of the checksum because it's not relevant for parsing the packet. I do see a value in adding such method to the relevant layers, for example: `isChecksumCorrect()`. Would you consider adding that?
> > 
> > 
> > @seladb OK.I will add these functions.
> 
> @seladb I am trying to add a function to check whether the IPv4 checksum is correct. But I found that when reading a valid IPv4 packet, the internetHeaderLength field in the IP header did not meet expectations (it should be 5, but the actual debugging value found that it was 10). Is it the wrong way to obtain it? In addition, I found that the total IP length field in the IPv4Layer constructor also does not match the actual length (it should be 148 bytes, and the actual debugging value found that the value is 192 bytes.)
> 
> ```
> bool IPv4Layer::isChecksumCorrect(const uint8_t* data, size_t dataLen)
>     {
>         const iphdr* ipHdr = reinterpret_cast<const iphdr*>(data);
>         size_t hdrLen = (ipHdr->internetHeaderLength) * 4 ;
>         if (dataLen < hdrLen) {
>             return false;
>         }
> 
>         ScalarBuffer<uint16_t> scalar = { (uint16_t*)ipHdr, hdrLen } ;
> 
>         return (computeChecksum(&scalar, false) == 0);
>     }
> ```
> 
> Packets: [Packets.zip](https://github.com/seladb/PcapPlusPlus/files/7252469/Packets.zip)
> 
> ![image](https://user-images.githubusercontent.com/12936259/135279307-b7e6c241-8337-4806-b159-e75eb0ecea95.png) ![image](https://user-images.githubusercontent.com/12936259/135280994-a96d6100-fef1-4e5b-a5cb-9088c2315671.png)
> 
> Test code:
> 
> ```
> PTF_TEST_CASE(IPv4Checksum) {
>     timeval time;
>     gettimeofday(&time, NULL);
> 
>     READ_FILE_AND_CREATE_PACKET(1, "PacketExamples/IPv4-Checksum.dat");
>     READ_FILE_AND_CREATE_PACKET(2, "PacketExamples/IPv4-Checksum-Bad.dat");
> 
>     pcpp::Packet ipv4Packet1(&rawPacket1, pcpp::IPv4);
>     pcpp::Packet ipv4Packet2(&rawPacket2, pcpp::IPv4);
>     pcpp::IPv4Layer* ipv4Layer1 = ipv4Packet1.getLayerOfType<pcpp::IPv4Layer>();
>     pcpp::IPv4Layer* ipv4Layer2 = ipv4Packet2.getLayerOfType<pcpp::IPv4Layer>();
>     PTF_ASSERT_NOT_NULL(ipv4Layer1);
>     PTF_ASSERT_NOT_NULL(ipv4Layer2);
>     bool ret1 = ipv4Layer1->isChecksumCorrect(ipv4Packet1.getRawPacket()->getRawData(), ipv4Packet1.getRawPacket()->getRawDataLen());
>     bool ret2 = ipv4Layer2->isChecksumCorrect(ipv4Packet2.getRawPacket()->getRawData(), ipv4Packet2.getRawPacket()->getRawDataLen());
>     PTF_ASSERT_EQUAL(ret1, true);
>     PTF_ASSERT_EQUAL(ret2, false);
> }
> ```

@seladb 
Have you ever encountered this case?
Is it a defect of PcapPlusPlus or is it a mistake in my use? Thank you for your help.

**Comment by seladb** [comment]
In your test code you give `isChecksumCorrect()` the entire packet instead of just the IPv4 layer:
```cpp
bool ret1 = ipv4Layer1->isChecksumCorrect(ipv4Packet1.getRawPacket()->getRawData(), ipv4Packet1.getRawPacket()->getRawDataLen());
```

I'm not sure why `isChecksumCorrect()` should even get the raw data, it already has it internally.
You can probably do something like this:

```cpp
bool IPv4Layer::isChecksumCorrect()
{
    const iphdr* ipHdr = getIPv4Header();
    ScalarBuffer<uint16_t> scalar = { (uint16_t*)ipHdr, (size_t)(ipHdr->internetHeaderLength*4) } ;
    return ipHdr->headerChecksum == htobe16(computeChecksum(&scalar, 1));
}
```

**Comment by angelyouyou** [comment]
> In your test code you give `isChecksumCorrect()` the entire packet instead of just the IPv4 layer:
> 
> ```c++
> bool ret1 = ipv4Layer1->isChecksumCorrect(ipv4Packet1.getRawPacket()->getRawData(), ipv4Packet1.getRawPacket()->getRawDataLen());
> ```
> 
> I'm not sure why `isChecksumCorrect()` should even get the raw data, it already has it internally. You can probably do something like this:
> 
> ```c++
> bool IPv4Layer::isChecksumCorrect()
> {
>     const iphdr* ipHdr = getIPv4Header();
>     ScalarBuffer<uint16_t> scalar = { (uint16_t*)ipHdr, (size_t)(ipHdr->internetHeaderLength*4) } ;
>     return ipHdr->headerChecksum == htobe16(computeChecksum(&scalar, 1));
> }
> ```

@seladb 
This is my fault. I accidentally parsed the packets from the link layer to the IP layer. After referring to the code you provided, I found that the checksum recalculated by isChecksumCorrect was 0 (different from the correct checksum 26870 carried in the message), which caused the checksum to be considered wrong.

```
bool IPv4Layer::isChecksumCorrect()
{
    const iphdr* ipHdr = getIPv4Header();
    if (ipHdr == nullptr) {
        return false;
    }

    ScalarBuffer<uint16_t> scalar = { (uint16_t*)ipHdr, (size_t)(ipHdr->internetHeaderLength * 4) } ;
    uint16_t headerChecksumCalc = htobe16(computeChecksum(&scalar, 1));

    return (ipHdr->headerChecksum == headerChecksumCalc);
}
```
Packet:
ca02167e001cca011789001c0800450000c026320000ff1168f60a010c010a010c02da65270c00ac43d700090002003f73905f3e18d80000001f000000000000005c0100001500150004001600040001000400020004000a0002000e000200080004000c0004000400010005000100070002000b00020030000100330001000f0004000d00010009000100060001003d0001001100020010000201000034003f1db4003f1db40000003800000001000300000a010c020a010c0101c0000003030000000000002018100000000000

**Comment by angelyouyou** [comment]
> @angelyouyou can we close this issue?

As mentioned above:
After referring to the code you provided, I found that the checksum recalculated by isChecksumCorrect was 0 (different from the correct checksum 63080 with network order carried in the message), which caused the checksum to be considered wrong. Can you help me?

**Comment by angelyouyou** [comment]
> @angelyouyou sorry, I mislead you. What you really should be looking for is if `headerChecksumCalc == 0`. The reason is that the checksum calculation uses all the IP header buffer **including** the checksum field. So if the existing checksum on the packet is correct, this calculation will result in `0`. If it's not `0` that means the checksum on the packet is wrong.
> 
> Please let me know if you have any questions.

It does not matter.
I also ignore the result.
Now the test passed.I will push the code after TCP and UDP checksum is completed.
Thanks.
