### ISSUE TITLE
How to add C++11 json library to PcapPlusPlus?

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#720]
I want to add JSON [parse library](https://github.com/nlohmann/json) to PcapPlusPlus to process protocol information.
I add directory and code file below:
![image](https://user-images.githubusercontent.com/12936259/134799247-b30953fe-9625-42c8-8568-e7b47544f32c.png)
![image](https://user-images.githubusercontent.com/12936259/134799648-5fa5601e-6e92-4358-a34d-de60c5a8d065.png)

After that I compiled PcapPlusPlus, error occurred in compiling.
![image](https://user-images.githubusercontent.com/12936259/134799576-3812b86e-8c93-41ac-a5bb-09426034bddc.png)

I added -std=c++11 to CXXFLAGS, but error still exist.

![image](https://user-images.githubusercontent.com/12936259/134799387-48653696-3532-4be4-ae5b-19734f9babd8.png)
Can you help me to fix it?

Here is my json file and code.
[json-code.zip](https://github.com/seladb/PcapPlusPlus/files/7231001/json-code.zip)

**Comment by seladb** [comment]
I have no idea why the json library emits those errors. This is something you need to figure out with the library maintainers.
PcapPlusPlus doesn't currently require C++11, so adding this library to PcapPlusPlus will not be possible.

**Comment by angelyouyou** [comment]
> I have no idea why the json library emits those errors. This is something you need to figure out with the library maintainers.
> PcapPlusPlus doesn't currently require C++11, so adding this library to PcapPlusPlus will not be possible.
@seladb  I will use RapidJSON to parse json file. It is compatable with C++ 03, the same with PcapPlusPlus, and just need include one header file.

**Comment by seladb** [comment]
So far a json parser was not needed in PcapPlusPlus, is json required specifically for NetFlow?

**Comment by angelyouyou** [comment]
> So far a json parser was not needed in PcapPlusPlus, is json required specifically for NetFlow?

@seladb 
Another issue.see the link.
https://github.com/seladb/PcapPlusPlus/issues/671

**Comment by seladb** [comment]
> @seladb
> Another issue.see the link.
> #671

Got it. I haven't looked into any json library so it's hard for me to say. One thing that is weird about RapidJSON is that it's being updated regularly however the last release was in 2016. We need to decide whether to take that last release or one of the recent commits (and how do we track it?).

Is this something that you plan to contribute back to the main repo or keep in your branch?

**Comment by angelyouyou** [comment]
> > @seladb
> > Another issue.see the link.
> > #671
> 
> Got it. I haven't looked into any json library so it's hard for me to say. One thing that is weird about RapidJSON is that it's being updated regularly however the last release was in 2016. We need to decide whether to take that last release or one of the recent commits (and how do we track it?).
> 
> Is this something that you plan to contribute back to the main repo or keep in your branch?

@seladb 
After my evaluation, xxx's j'son parsing library is better in style and updated, but it is based on C++11 (which conflicts with the current project based on version 03).
I plan to submit the features of the custom protocol port to the master repo. Except for json parsing, the rest of the code has been completed.
Do you have any other better suggestions or solutions?

**Comment by seladb** [comment]
Unfortunately I don't have better solutions as I haven't looked into any json parsing libraries... I plan to port PcapPlusPlus to C++11 but I'm not sure when it's going to happen, probably not in the next 2-3 months...

**Comment by angelyouyou** [comment]
> Unfortunately I don't have better solutions as I haven't looked into any json parsing libraries... I plan to port PcapPlusPlus to C++11 but I'm not sure when it's going to happen, probably not in the next 2-3 months...

@seladb 
Another question:
I will try to integrate in the local branch.
In which class is it appropriate to add a custom port  capability from the configuration file?

**Comment by seladb** [comment]
I'm not sure I understand the question. Can you elaborate?

**Comment by angelyouyou** [comment]
> I'm not sure I understand the question. Can you elaborate?

@seladb 
At present, I have added a custom port to parse the upper-layer protocol (by reading the custom port in the configuration file), in my local repo. 
May I ask which class you need to add this to whether you use a custom way to parse the application (Layer?)? 
And when is the time to load the configuration file?

**Comment by seladb** [comment]
I'm not sure what you mean by "upper-layer protocol", but let me share my thoughts:
- Currently, all of the port checkings is done in static methods - this means that custom ports should be in a singleton, and that singleton should probably do lazy loading (meaning load the JSON file only on the first call to the singleton)
- This singleton should have at least these two things in its interface:
  - Let the user specify where the JSON file is (and make sure it's there)
  - Let different layers request their custom ports (if exist in the JSON file) - otherwise there should be a fallback to the default ports - probably in the layer itself
 
Let me know what you think

**Comment by angelyouyou** [comment]
> I'm not sure what you mean by "upper-layer protocol", but let me share my thoughts:
> 
> * Currently, all of the port checkings is done in static methods - this means that custom ports should be in a singleton, and that singleton should probably do lazy loading (meaning load the JSON file only on the first call to the singleton)
> * This singleton should have at least these two things in its interface:
>   
>   * Let the user specify where the JSON file is (and make sure it's there)
>   * Let different layers request their custom ports (if exist in the JSON file) - otherwise there should be a fallback to the default ports - probably in the layer itself
> 
> Let me know what you think

@seladb 
The "upper layer protocol" I mean here is the currently supported application layer protocol (as opposed to UDP, TCP and other transport protocols), such as DHCP, SSH, BGP...

Okay, I basically implement it according to your method, and I will optimize for a little difference in details. At present, the location of the JSON file is fixed (Packet++/config, please let me know if there is a more reasonable location), and it is temporarily not supported for users to specify the location of JSON storage.

What I want to know is when to trigger the loading of the newly added single instance? And in which class to add the corresponding attribute field setting, so that the user can choose whether to use a custom port method (UDP/TCP/IPv4Layer/IPv6Layer)?

**Comment by seladb** [comment]
> and it is temporarily not supported for users to specify the location of JSON storage.

I think we should let the user specify the location of the JSON file, what is the complexity there?

>What I want to know is when to trigger the loading of the newly added single instance? And in which class to add the corresponding attribute field setting, so that the user can choose whether to use a custom port method (UDP/TCP/IPv4Layer/IPv6Layer)?

If it's a singleton instance then there is no need to load it. The singleton will load the file in the first call

**Comment by angelyouyou** [comment]
> > and it is temporarily not supported for users to specify the location of JSON storage.
> 
> I think we should let the user specify the location of the JSON file, what is the complexity there?
> 
> > What I want to know is when to trigger the loading of the newly added single instance? And in which class to add the corresponding attribute field setting, so that the user can choose whether to use a custom port method (UDP/TCP/IPv4Layer/IPv6Layer)?
> 
> If it's a singleton instance then there is no need to load it. The singleton will load the file in the first call

@seladb 
How can users specify the json path of their configuration files? I am not very sure how to achieve this in detail.
