### ISSUE TITLE
Two questions about Layer check.

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#729]
@seladb 
Should UdpLayer::isDataValid() and TcpLayer::isDataValid() be added to the parseNextLayer() function of UdpLayer and TcpLayer, and just construct the PayloadLayer after the verification fails? Does the same problem exist for RawIP and the IP protocol layer?

In addition, can UdpLayer::isDataValid() and TcpLayer::isDataValid() functions include UDP and TCP checksum checks?

I have already tested IP/UDP/TCP checksum check successfully in my local repo.Can I submit them to the PcapPlusPlus?

**Comment by seladb** [comment]
> Should UdpLayer::isDataValid() and TcpLayer::isDataValid() be added to the parseNextLayer() function of UdpLayer and TcpLayer, and just construct the PayloadLayer after the verification fails? Does the same problem exist for RawIP and the IP protocol layer?

> In addition, can UdpLayer::isDataValid() and TcpLayer::isDataValid() functions include UDP and TCP checksum checks?

@angelyouyou I'm not sure I understand your question. `TcpLayer::isDataValid()` is already used whenever a TCP layer is constructed: [here](https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/src/IPv4Layer.cpp#L271-L273), [here](https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/src/IPv6Layer.cpp#L225-L227) and [here](https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/src/IPSecLayer.cpp#L70-L72).

`UdpLayer::isDataValid()` doesn't exist yet, but we can consider adding it.

I don't think those methods should include a checksum check because the checksum is not always correct in standard network packets.

> I have already tested IP/UDP/TCP checksum check successfully in my local repo.Can I submit them to the PcapPlusPlus?

Do you mean that you added a method for `IPv4Layer`, `IPv6Layer`, `TcpLayer`, and `UdpLayer` that checks if the checksum is correct? In that case yes, it'd be a nice addition to PcapPlusPlus

**Comment by angelyouyou** [comment]
> > Should UdpLayer::isDataValid() and TcpLayer::isDataValid() be added to the parseNextLayer() function of UdpLayer and TcpLayer, and just construct the PayloadLayer after the verification fails? Does the same problem exist for RawIP and the IP protocol layer?
> 
> > In addition, can UdpLayer::isDataValid() and TcpLayer::isDataValid() functions include UDP and TCP checksum checks?
> 
> @angelyouyou I'm not sure I understand your question. `TcpLayer::isDataValid()` is already used whenever a TCP layer is constructed: [here](https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/src/IPv4Layer.cpp#L271-L273), [here](https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/src/IPv6Layer.cpp#L225-L227) and [here](https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/src/IPSecLayer.cpp#L70-L72).
> 
> `UdpLayer::isDataValid()` doesn't exist yet, but we can consider adding it.
> 
> I don't think those methods should include a checksum check because the checksum is not always correct in standard network packets.
> 
> > I have already tested IP/UDP/TCP checksum check successfully in my local repo.Can I submit them to the PcapPlusPlus?
> 
> Do you mean that you added a method for `IPv4Layer`, `IPv6Layer`, `TcpLayer`, and `UdpLayer` that checks if the checksum is correct? In that case yes, it'd be a nice addition to PcapPlusPlus

UdpLayer::isDataValid() doesn't exist yet, but we can consider adding it.
**-->I wll add it and submit to PcapPlusPlus with checksum check.**

I don't think those methods should include a checksum check because the checksum is not always correct in standard network packets.
**-->Yes, the packet is not always correct (that is, it passes the checksum). What I mean is that when processing packets, users often want to get those correct packets, not including the wrong ones.

Adding this checksum check (also including isDataValid check) to the underlying protocols such as UDP and TCP can prevent L4 protocols (such as BGP, DHCP, and other protocols over TCP and UDP) from processing wrong packets.**

**Comment by seladb** [comment]
> I don't think those methods should include a checksum check because the checksum is not always correct in standard network packets.
> _**-->Yes, the packet is not always correct (that is, it passes the checksum). What I mean is that when processing packets, users often want to get those correct packets, not including the wrong ones. Adding this checksum check (also including isDataValid check) to the underlying protocols such as UDP and TCP can prevent L4 protocols (such as BGP, DHCP, and other protocols over TCP and UDP) from processing wrong packets.**_

I see 2 issues here:
1. `isDataValid()` is used on a layer and not on its next layers, meaning: we run `TcpLayer::isDataValid()` to check if the data should be parsed as TCP or not. If it fails a generic `PayloadLayer` will be created **instead of** the TCP layer, and not after it. The same goes for IP/UDP. I think that what you meant is to parse the TCP but not the next layers, please correct me if I'm wrong
2. I think most users will want to parse the whole packet even if the checksum is wrong. Nobody complained about that so far...

**Comment by angelyouyou** [comment]
> > I don't think those methods should include a checksum check because the checksum is not always correct in standard network packets.
> > _**-->Yes, the packet is not always correct (that is, it passes the checksum). What I mean is that when processing packets, users often want to get those correct packets, not including the wrong ones. Adding this checksum check (also including isDataValid check) to the underlying protocols such as UDP and TCP can prevent L4 protocols (such as BGP, DHCP, and other protocols over TCP and UDP) from processing wrong packets.**_
> 
> I see 2 issues here:
> 
> 1. `isDataValid()` is used on a layer and not on its next layers, meaning: we run `TcpLayer::isDataValid()` to check if the data should be parsed as TCP or not. If it fails a generic `PayloadLayer` will be created **instead of** the TCP layer, and not after it. The same goes for IP/UDP. I think that what you meant is to parse the TCP but not the next layers, please correct me if I'm wrong
> 2. I think most users will want to parse the whole packet even if the checksum is wrong. Nobody complained about that so far...

@seladb 
1. isDataValid() is used on a layer and not on its next layers, meaning: we run TcpLayer::isDataValid() to check if the data should be parsed as TCP or not. If it fails a generic PayloadLayer will be created instead of the TCP layer, and not after it. The same goes for IP/UDP. I think that what you meant is to parse the TCP but not the next layers, please correct me if I'm wrong

--->_If the isDataValid() of UDP and TCP returns a failure, it should return UdpLayer or TcpLayer, and cannot continue to parse to the lower layer._


2. I think most users will want to parse the whole packet even if the checksum is wrong. Nobody complained about that so far...
--->
If the IP/UDP/TCP layer checksum or length field of the packet is wrong, it means that the packet may be damaged or forged. According to the IETF RFC standard, the processing should not be continued, otherwise it may cause the upper layer protocol to process illegal data.
You can refer to the TCP/IP protocol and operating system kernel.^_^

**Comment by angelyouyou** [comment]
> > 1. isDataValid() is used on a layer and not on its next layers, meaning: we run TcpLayer::isDataValid() to check if the data should be parsed as TCP or not. If it fails a generic PayloadLayer will be created instead of the TCP layer, and not after it. The same goes for IP/UDP. I think that what you meant is to parse the TCP but not the next layers, please correct me if I'm wrong
> > 
> > --->_If the isDataValid() of UDP and TCP returns a failure, it should return UdpLayer or TcpLayer, and cannot continue to parse to the lower layer._
> 
> That's not always true. What if `isDataValid()` returns false because the size of the payload is less than the size of `tcphdr`? In that case we must not parse the TCP layer, otherwise we run into invalid memory
> 
> > 1. I think most users will want to parse the whole packet even if the checksum is wrong. Nobody complained about that so far...
> >    --->
> >    If the IP/UDP/TCP layer checksum or length field of the packet is wrong, it means that the packet may be damaged or forged. According to the IETF RFC standard, the processing should not be continued, otherwise it may cause the upper layer protocol to process illegal data.
> >    You can refer to the TCP/IP protocol and operating system kernel.^_^
> 
> You're right, however PcapPlusPlus is sometimes used to detect damaged, forged or invalid packets. In those cases the user probably wants to see the whole packet, and analyze why the IP length / checksum is wrong

@seladb 
1. That's not always true. What if isDataValid() returns false because the size of the payload is less than the size of tcphdr? In that case we must not parse the TCP layer, otherwise we run into invalid memory
-->Y_ou are right, but we can distinguish them. For example, checksum errors can be returned as UdpLayer/TcpLayer, but for length errors, PayloadLayer must be returned.
Like you said, you really need to distinguish the scenes to avoid getting a higher layer, which may cause illegal memory access._

2. You're right, however PcapPlusPlus is sometimes used to detect damaged, forged or invalid packets. In those cases the user probably wants to see the whole packet, and analyze why the IP length / checksum is wrong
_-->
I think these are 2 main scenarios:
Scenario 1. Check where the packet has an error, this may be mainly used as a packet probe;
Scenario 2. Only processing legitimate packets (including IP, UDP and TCP layer checksum, length and other fields are legal), this possibility is mainly used for real-time packet analysis.

If you only want to deal with such legitimate packets in scenario 2, are there any good solutions or suggestions?_

**Comment by seladb** [comment]
I think we can add those checks, but only if we find a way to make it backward compatible. I think that by default a wrong checksum should not block the parsing of certain layers, but we may allow the user to do so

**Comment by seladb** [comment]
yes, I think it's possible - we can probably add a `verifyChecksum` parameter (with a default value of `false`) to `TcpLayer::isDataValid()`, `IPv4Layer::isDataValid()` and create a new `UdpLayer::isDataValid(const uint8_t* data, size_t dataLen, bool verifyChecksum = false)`

Can you make this change and open a PR?

**Comment by seladb** [comment]
@angelyouyou are you planning to work on this and open a PR?

**Comment by seladb** [comment]
@angelyouyou what should we do with this issue? Are you planning to work on it or should we close it?

**Comment by seladb** [comment]
@angelyouyou I'm closing this issue due to lack of response, please reopen if needed
