### ISSUE TITLE
About fatal bugs on the aarch64 platform

### ISSUE THREAD

**Issue by ghost** [seladb/PcapPlusPlus#732]
This tool is very easy to use, but there is currently no aarch64 linux support version. I hope to add cross-compilation and run on the target aarch64 Linux platform.

**Comment by inSilo** [comment]
> please correct me if I'm wrong, but I think your command is missing the `-` character before the `i` argument, it should be:

please correct me if I'm wrong, but I think your command is missing the - character before the i argument, it should be:

**Comment by inSilo** [comment]
> `getopt_long` is a part of GNU: https://www.gnu.org/software/libc/manual/html_node/Getopt-Long-Options.html
> 
> Do you know of any specific issue it has on `aarch64`? Unfortunately I don't have a `aarch64` device so I can't test it...
<img width="1176" alt="137068898-d3a7169a-f74f-431e-bb59-69dfae364c2b" src="https://user-images.githubusercontent.com/53564509/137075525-49b057b2-6bd1-45ed-bcaa-db5f3a2c9b7a.png">
<img width="1139" alt="137069115-e0378dc9-f52f-4f99-99fb-ca3e8b5d0a2a" src="https://user-images.githubusercontent.com/53564509/137075533-3692bc9b-ce18-446a-9b58-7d54e2c0c2fc.png">

**Comment by seladb** [comment]
I think I found a similar issue in some other project: https://github.com/wg/wrk/issues/87

The fix was to define `opt` as an `int` instead of `char`: https://github.com/wg/wrk/commit/b8431944edfd122f91ab8879a8d9c3f29a7d880c#diff-8f28ea08d2b754de6ba485bb5a3da17434336407cb9ab13b786bc4f82490014d

Can you check if that solves the problem?

**Comment by seladb** [comment]
> You are welcome, you can correct it, after all, this problem is a minor problem. This problem may only occur in aarch64

Sure, I can make the fix



> But I suggest that the project can be cross-compiled to aarch64 version, first compile libpcap, and then cross-compile to aarach64 through aarch64-linux-gnu-g++。
> 
> Or clang++，For example: platform.mk.linux.aarch64
> 
> ```
> ...
> CXX := clang++
> CC := clang
> AR := llvm-ar
> ....
> GLOBAL_FLAGS := --target=aarch64-linux-gnu
> ```

Here I need your help because I don't have a lot of experience with `aarch64`. I just saw that CirrusCI supports Arm containers so we may be able to run it there: https://cirrus-ci.org/guide/linux/
Will you be able to help?

**Comment by inSilo** [comment]
> > You are welcome, you can correct it, after all, this problem is a minor problem. This problem may only occur in aarch64
> 
> Sure, I can make the fix
> 
> > But I suggest that the project can be cross-compiled to aarch64 version, first compile libpcap, and then cross-compile to aarach64 through aarch64-linux-gnu-g++。
> > Or clang++，For example: platform.mk.linux.aarch64
> > ```
> > ...
> > CXX := clang++
> > CC := clang
> > AR := llvm-ar
> > ....
> > GLOBAL_FLAGS := --target=aarch64-linux-gnu
> > ```
> 
> Here I need your help because I don't have a lot of experience with `aarch64`. I just saw that CirrusCI supports Arm containers so we may be able to run it there: https://cirrus-ci.org/guide/linux/ Will you be able to help?


I recommend cross-compiling to aarch64 through x86_64 without compiling on a specific arm64 host platform.

**Comment by inSilo** [comment]
> > You are welcome, you can correct it, after all, this problem is a minor problem. This problem may only occur in aarch64
> 
> Sure, I can make the fix
> 
> > But I suggest that the project can be cross-compiled to aarch64 version, first compile libpcap, and then cross-compile to aarach64 through aarch64-linux-gnu-g++。
> > Or clang++，For example: platform.mk.linux.aarch64
> > ```
> > ...
> > CXX := clang++
> > CC := clang
> > AR := llvm-ar
> > ....
> > GLOBAL_FLAGS := --target=aarch64-linux-gnu
> > ```
> 
> Here I need your help because I don't have a lot of experience with `aarch64`. I just saw that CirrusCI supports Arm containers so we may be able to run it there: https://cirrus-ci.org/guide/linux/ Will you be able to help?

Also, I suggest that your project be compiled directly with the libpcap source code, so that it can be compiled for cross-platform use! (After all, I see that the official Android build has to manually specify the path of the libpcap source, which is extremely inconvenient), the above is my suggestion.

**Comment by seladb** [comment]
> Also, I suggest that your project be compiled directly with the libpcap source code, so that it can be compiled for cross-platform use. (After all, I see that the official Android build has to manually specify the path of the libpcap source, which is extremely inconvenient), the above is my suggestion.

Thanks for your suggestion, but I don't think PcapPlusPlus should be compiled with libpcap source code for a number of reasons:
- Some users use PcapPlusPlus with package managers such as `conan` or `vcpkg` which take care of these dependencies
- Most standard Linux distros (maybe `aarch64` is an exception) already provide easy libpcap installation via `apt` or `yum`/`dnf`, so there is no reason to compile libpcap again
- Windows users use PcapPlusPlus with WinPcap/Npcap which are extremely more difficult to compile from source.

Android is indeed a unique use case, but I don't think we should follow this pattern on all platforms.



> Which version of my warehouse is relatively old, because some of my old projects still use the old version of the header file dependency，but the cross-compilation ideas provided therein can be used for reference, [TyraProdoehl/PcapPlusPlus@649e66a](https://github.com/TyraProdoehl/PcapPlusPlus/commit/649e66a512b818814dcbe28618ae7a9885be1660) [TyraProdoehl/PcapPlusPlus@ea823e3](https://github.com/TyraProdoehl/PcapPlusPlus/commit/ea823e34883c998e444d7162b8ff1320687a5d14) . If the author agrees with my approach, can the project be modified according to this idea?

I took a quick on these commits. I agree with the approach of adding `platform.mk.linux.aarch64` and integrating it into `configure-linux.sh`, but would avoid the part that compiles libpcap. Would you consider opening a PR with these changes?
