### ISSUE TITLE
[Timestamp] Issue with TS precision

### ISSUE THREAD

**Issue by zolt4n** [seladb/PcapPlusPlus#735]
I am not sure what I am doing wrong (if I am), but I am writing a packet with a specific timestamp (with nanosec) but when I read back the pcap with Wireshark I see a different timestamp.

here is my code : 
```c++
    timespec nsec_time;
    nsec_time.tv_sec = 1632111693;
    nsec_time.tv_nsec = 905739620;
    std::cout << "Set timestamp to " << nsec_time.tv_sec << " " << nsec_time.tv_nsec << "\n";
    rawPacket.setPacketTimeStamp(nsec_time);
    m_pcapNgWriters->writePacket(rawPacket);
 ```

 in Wireshark I see 
 Timestamp: 1632111693
 Nanoseconds: 875294208

**Using version : **  21.05

Well after checking in python with python-pcapng module I am getting : 

 <EnhancedPacket interface_id=0 timestamp_high=**380005616** timestamp_low=**889405284** packet_payload_info=(72, 72, b'\x01\x00^\x00M\x0b\x00\x1cs\x86Dy\x08\x00E\x00\x00:\x00\x00\x00\x00{\x11\xccI\xa2E\xa4\x18\xe0\x00M\x0bU\xfbU\xfb\x00&\x15\xfb\x1e\x00\x0c\x01\x01\x00\x00\x00M\x0cHa\x00\xee+4\x0e\x00\x01\x00\x07\x0cHa\x00\xfbs\x0f\x0b>') options=Options({})>

the uint64_t representation of 1632111693905739620 in 2 uint_32 is   380005616   **889405284** so I guess the bug is in wireshark. You guys confirm ?

**Comment by seladb** [comment]
@zolt4n I'm closing this issue for now, please reopen if required
