### ISSUE TITLE
`aarch64` support

### ISSUE THREAD

**Issue by seladb** [seladb/PcapPlusPlus#737]
Continuing the discussion that started here: https://github.com/seladb/PcapPlusPlus/issues/732

@inSilo let's discuss here how we want to proceed

**Comment by inSilo** [comment]
> Continuing the discussion that started here: #732
> 
> @inSilo let's discuss here how we want to proceed

Sorry, I have been too busy these few days, I haven't had time to come and see the reply. Today I saw "change the variable type that holds getopt_long result from char to int", which is pretty good, and the rest is to cross-compile to aarch64 platform. If you don't respect the integration of libpcap into the project and compile it is also possible. Cross-compilation is currently configured in platform.mk.linux.aarch64 and configure-linux.sh. The cross-target tool chain of aarch64 is configured in platform.mk.linux.aarch64, and then a "--" is configured in configure-linux.sh. The "aarch64" option allows users to specify the cross-compilation target as the aarch64 platform. The author's idea is great, I hope the author can integrate it according to the idea of ​​my last post.

**Comment by sebastiandavalle** [comment]
any update regarding this? 
I need PcapPlusPlus compiled for aarch64 (need to run it on ubuntu aarch64 - Raspberry pi) . I've been trying to cross-compile it but without success

**Comment by sjdavalle** [comment]
any update regarding this?
I need PcapPlusPlus compiled for aarch64 (need to run it on ubuntu aarch64 - Raspberry pi) . I've been trying to cross-compile it but without success
