### ISSUE TITLE
Include paths after installing

### ISSUE THREAD

**Issue by mfontanini** [seladb/PcapPlusPlus#74]
I noticed this while adding Pcap++ to my benchmarks. I can't include headers like `<pcapplusplus/PcapFileDevice.h>` because the include paths in it are absolute. e.g.:

```
/usr/local/include/pcapplusplus/PcapFileDevice.h:4:24: fatal error: PcapDevice.h: No such file or directory
 #include <PcapDevice.h>
```

This is not great as then you need to make (in this specific case) `/usr/local/include/pcapplusplus` part of your include path and that shouldn't be necessary. This also increases the odds of header file collisions with other libraries.

**Comment by seladb** [comment]
I agree that you need to include `/usr/local/include/pcapplusplus` as part of the include path and that in some (probably rare?) cases it might collide with other libraries having files with the same name but I'm not sure changing includes to `<pcapplusplus/...h>` is the right solution which would work on all platforms. For example, on Windows there is no `make install` so you need to work with the `Dist/` folder. In this case I'll need to artificially create a "pcapplusplus" folder inside `Dist/header` which doesn't make much sense. Same thing if you want to work in Linux/MacOS without running `make install`.

Please let me know what you think

**Comment by mfontanini** [comment]
I would create a `pcapplusplus` directory inside your headers one, that's what a bunch of projects do (e.g. boost). Otherwise you could use relative includes by using `#include "filename"` rather than `#include <filename>`. If you use the former, that will also look up in the local directory where the file that contains the include directive is.

**Comment by seladb** [comment]
I think I understand your point but I'm not sure I'm 100% convinced. What's wrong with keeping it that way? Maybe just change all `#include <filename>` to `#include "filename"`?

**Comment by mfontanini** [comment]
I see headers installed in `/usr/local/include/pcapplusplus` however, even if `/usr/local/include` is one of my default include paths, I can't just include `pcapplusplus/somefile.h`. For this to work, I need to use `-I/usr/local/include/pcapplusplus` when building which is odd given `/usr/local/include` is one of my default include directories but I still need to provide a subdirectory of it.

**Comment by seladb** [comment]
So maybe a simpler solution would be moving the header files to `/usr/local/include`?
Probably any solution has its pros and cons...

**Comment by mfontanini** [comment]
No, please don't do that :P. You should still group your files inside `pcapplusplus`. As a quick workaround you can use `#include "file"` rather than `#include <file>` for pcap++ includes _inside_ the code. So basically every include directive in pcap++'s code that includes headers that belong to pcap++ should be turned into `#include "filename"`. That should fix it.

**Comment by seladb** [comment]
That's a great idea, at least as a temporary solution. Would you mind doing this change and create a pull request?
