### ISSUE TITLE
DpdkExample-FilterTraffic test sample problem RX mbuf RX mbuf cannot be allocated

### ISSUE THREAD

**Issue by huangpan110** [seladb/PcapPlusPlus#746]
Today, I used PcapPP to call dpdk, run the dpdk sample, and found that it could not run ERROR: Couldn't open DPDK device #0, PMD'net_ixgbe', carefully check that the problem is RX mbuf alloc failed I don’t know how to solve it

------------------------------------------
root@huangpan-analysis:/home/huangpan/PcapPlusPlus/Examples/DpdkExample-FilterTraffic# ./Bin/DpdkTrafficFilter -d 0 -f ./
EAL: Detected 32 lcore(s)
EAL: Detected 4 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: PCI device 0000:43:00.0 on NUMA socket 1
EAL:   probe driver: 8086:154d net_ixgbe
EAL: PCI device 0000:43:00.1 on NUMA socket 1
EAL:   probe driver: 8086:154d net_ixgbe
ixgbe_alloc_rx_queue_mbufs(): RX mbuf alloc failed queue_id=31
ixgbe_dev_rx_queue_start(): Could not alloc mbuf for queue:31
ixgbe_dev_start(): Unable to start rxtx queues
ixgbe_dev_start(): failure in ixgbe_dev_start(): -1
[ERROR: src/DpdkDevice.cpp: startDevice:371          ] Failed to start device 0. Error is -5
[ERROR: src/DpdkDevice.cpp: openMultiQueues:159      ] failed to start device 0

ERROR: Couldn't open DPDK device #0, PMD 'net_ixgbe'

**Comment by seladb** [comment]
@huangpan110 can we close this issue?
