### ISSUE TITLE
TCP packet Seq and Ack big-endian or little-endian issue

### ISSUE THREAD

**Issue by FisherDock** [seladb/PcapPlusPlus#749]
Hi,

I found PcapPlusPlus uses **little endian** to parse TCP header  to get seq and ack, which should be calculated using **big endian**.   But tcp port is computed with big endian.
`tcphdr->sequenceNumber, tcphdr->ackNumber`

One can easily reproduce this issue with Wireshark. Or is there a setup to use big endian for Seq/Ack?

Thanks.

**Comment by seladb** [comment]
@FisherDock are you referring to the parsing done by [TCP reassembly](https://github.com/seladb/PcapPlusPlus/blob/master/Packet++/src/TcpReassembly.cpp) or in other parts of PcapPlusPlus

**Comment by FisherDock** [comment]
@FisherDock  No, just in normal packet parsing,  e.g., 

```
tcphdr* header = tcp_layer->getTcpHeader();
uint32_t seq = header->sequenceNumber;      // sequenceNumber is calculated in little endian
uint32_t ack = header->ackNumber;                //  ackNumber is calculated in little endian
```

BTW, the TCP reassembly feature you mentioned is a new feature recently added?

**Comment by seladb** [comment]
As you can see [here](https://github.com/seladb/PcapPlusPlus/blob/6f5fc732a0b713955ea348d07950175093046ac3/Packet%2B%2B/header/TcpLayer.h#L369) `getTcpHeader()` casts the packet's raw data into a `tcphdr` struct. This means that `tcphdr` fields are in network byte order which is [usually big endian](https://stackoverflow.com/questions/13514614/why-is-network-byte-order-defined-to-be-big-endian). It's strange that you see them in little endian 🤔 Which platform are you running PcapPlusPlus on?

> BTW, the TCP reassembly feature you mentioned is a new feature recently added?

No, [TCP reassembly](https://pcapplusplus.github.io/docs/features#packet-reassembly) is not a new feature, it's been there for a few years now

**Comment by seladb** [comment]
@FisherDock can we close this issue?

**Comment by FisherDock** [comment]
@seladb The code was compiled with Clang++.  So far it's still little-endian, and I used `nota()` to convert manually.  and I would look into it. Thanks for reply!  

BTW,  I haven't tested PcapPlusPlus on Windows and Mac M1, not sure it works nicely. Can you give me some hints?

**Comment by seladb** [comment]
> BTW, I haven't tested PcapPlusPlus on Windows and Mac M1, not sure it works nicely. Can you give me some hints?

What do you mean by _"not sure it works nicely"_? Have you seen any issues?

**Comment by FisherDock** [comment]
No, I haven't tested it on other platforms. Hopefully it works well :)

**Comment by seladb** [comment]
I'm closing this issue for now, please reopen if still relevant
