### ISSUE TITLE
SIP protocol port restriction

### ISSUE THREAD

**Issue by aleksandarpu** [seladb/PcapPlusPlus#75]
I discovered that in detection of the SIP protocol (UdpLayer.cpp) only destination port is tested and only against 5060 and 5061
In my test case UDP port is often 5062.
A bit better is to test source port too.
lines 97 - 101

	else if (((portSrc == 5060) || (portSrc == 5061) || (portDst == 5060) || (portDst == 5061)) && 
		(SipRequestFirstLine::parseMethod((char*)(m_Data + sizeof(udphdr)), m_DataLen - sizeof(udphdr)) != SipRequestLayer::SipMethodUnknown))
		m_NextLayer = new SipRequestLayer(m_Data + sizeof(udphdr), m_DataLen - sizeof(udphdr), this, m_Packet);
	else if (((portSrc == 5060) || (portSrc == 5061) || (portDst == 5060) || (portDst == 5061)) && 
		(SipResponseFirstLine::parseStatusCode((char*)(m_Data + sizeof(udphdr)), m_DataLen - sizeof(udphdr)) != SipResponseLayer::SipStatusCodeUnknown))

**Comment by seladb** [comment]
Actually both source and dest port are tested for SIP protocol discovery as you can see in the code snippet you sent (`portSrc` is for source port and `portDst` is for dest port).
In your use cases - do you have a case where neither source and dest ports are 5060 or 5061?

**Comment by aleksandarpu** [comment]
Actualy code in my post is my patch
here is original function, UdpLayer.cpp line 82:

void UdpLayer::parseNextLayer()
{
if (m_DataLen <= sizeof(udphdr))
return;

udphdr* udpHder = getUdpHeader();
uint16_t portDst = ntohs(udpHder->portDst);
uint16_t portSrc = ntohs(udpHder->portSrc);

if ((portSrc == 68 && portDst == 67) || (portSrc == 67 && portDst == 68) ||
(portSrc == 67 && portDst == 67))
m_NextLayer = new DhcpLayer(m_Data + sizeof(udphdr), m_DataLen -
sizeof(udphdr), this, m_Packet);
else if (portDst == 4789)
m_NextLayer = new VxlanLayer(m_Data + sizeof(udphdr), m_DataLen -
sizeof(udphdr), this, m_Packet);
else if ((m_DataLen - sizeof(udphdr) >= sizeof(dnshdr)) &&
(DnsLayer::getDNSPortMap()->find(portDst) !=
DnsLayer::getDNSPortMap()->end() ||
DnsLayer::getDNSPortMap()->find(portSrc) !=
DnsLayer::getDNSPortMap()->end()))
m_NextLayer = new DnsLayer(m_Data + sizeof(udphdr), m_DataLen -
sizeof(udphdr), this, m_Packet);
else if ((*(portDst == 5060) || (portDst == 5061*)) &&
(SipRequestFirstLine::parseMethod((char*)(m_Data + sizeof(udphdr)),
m_DataLen - sizeof(udphdr)) != SipRequestLayer::SipMethodUnknown))
m_NextLayer = new SipRequestLayer(m_Data + sizeof(udphdr), m_DataLen -
sizeof(udphdr), this, m_Packet);
else if (((*portDst == 5060) || (portDst == 5061*)) &&
(SipResponseFirstLine::parseStatusCode((char*)(m_Data + sizeof(udphdr)),
m_DataLen - sizeof(udphdr)) != SipResponseLayer::SipStatusCodeUnknown))
m_NextLayer = new SipResponseLayer(m_Data + sizeof(udphdr), m_DataLen -
sizeof(udphdr), this, m_Packet);
else
m_NextLayer = new PayloadLayer(m_Data + sizeof(udphdr), m_DataLen -
sizeof(udphdr), this, m_Packet);
}

**Comment by seladb** [comment]
Oh, you're right, sorry for that.
What are the client and server ports in your case? By your code snippet I'd guess the client port is 5060/5061 and the server port is 5062, right?
When implementing this the way I did I used [this ](https://en.wikipedia.org/wiki/Port_(computer_networking)) Wikipedia article and [this one](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers) who say SIP is most commonly used on (server) ports 5060 and 5061. Port 5062 is actually allocated for something else (Localisation access)

**Comment by seladb** [comment]
@aleksandarpu - did you see my comment above? Let's decide together whether to fix this issue or not

**Comment by aleksandarpu** [comment]
I'm build an SIP protocol sniffer, and I got stream on edge of the SIP provider network meaning that I see both sides to and from SIP provider. Because of that SIP port 5060 I can observe as source or destination port.
Yes, all SIP packets have port 5060 but current code in PcapPlusPlus ignore all responses
With my modification (by testing src and dst UDP port against well known SIP port) I'm able to catch all required data.

**Comment by seladb** [comment]
I think I understand your point now. I will make that fix. Thanks!
