### ISSUE TITLE
Does PcapPlusPlus support Apple M1 silicon?

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#751]
Does PcapPlusPlus support Apple M1 silicon?

**Comment by seladb** [comment]
Yes, Apple M1 is supported:
https://pcapplusplus.github.io/docs/install/build-source/macos#configuration
https://pcapplusplus.github.io/docs/platforms#-macos

**Comment by alacic** [comment]
Will pcpp suport for macos Monterey?
Compiling with error "Undefined symbols for architecture arm64" using "clang++" with "macos Monterey"

**Comment by seladb** [comment]
Thank you @alacic for figuring it out! Do you know if there is a generic `target` that would work for both macOS 11 and 12?

**Comment by alacic** [comment]
Sorry, I don't know. @seladb

**Comment by seladb** [comment]
@alacic I asked this question in StackOverflow and here is the answer I got:
https://stackoverflow.com/a/73773711/5007125

If I understand the answer correctly, it says that any binary that is compiled for macOS 11 should work on macOS 12 as well...

Please see their comment:
![image](https://user-images.githubusercontent.com/9059541/191168183-05794da6-85d3-4a7a-b463-7696244a1bef.png)

Feel free to chime in and provide more information about the errors you get etc.

**Comment by seladb** [comment]
@alacic I tried to run it on macOS 12 in the GitHub Actions (without changing the `-target`) and it seems to work:
https://github.com/seladb/PcapPlusPlus/actions/runs/3096371576/jobs/5012485355

Can you describe the issue you saw?

**Comment by alacic** [comment]
@seladb Thank you for the work. I change -target back to "-target arm64-apple-macos11", It works well.
I can't reproduce the issue. It seems like my coding error.
I will change the first comment for not misleading the others.
