### ISSUE TITLE
A question about computing pseudo header for IPv6.

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#755]
@seladb 

From [RFC8200](https://datatracker.ietf.org/doc/rfc8200/) chapter 8.1, we know the format of IPv6 pseudo header is like below:
```
struct ip6_pseudo_header {
        uint8_t ipSrc[16];
        uint8_t ipDst[16];
        uint32_t upperLen;
        uint8_t zero[3];
        uint8_t nextHeader;
    };
```
_**Can you help me to explain for the two questions below ? I am planning to submit the pseudo header computing function to master repo and want to know the reason.**_
After I read the PcapPlusPlus Code(UDPLayer and TCP Layer), I found the format and length in PcapPlusPlus is different with the RFC8200.But the checksum result is correct.
1. The format is different with RFC8200, include the length of upperLen, zero and nextHeader fields.
2. The total length of IPv6 pseudo header in RFC8200 is 40 bytes, but PcapPlusPlus is 36 bytes(see UDPLayer code snippet below).
![image](https://user-images.githubusercontent.com/12936259/141037209-5fedcc01-adf8-4df9-a256-8d328231bcd9.png)

My code for computing general pseudo header for IPv4 and IPv6(It is now running correct)
_**Can you help me review this function and make suggestions? In this case, I can modify it locally and then submit the pr.**_
[code snippet for pseudo header computing.txt](https://github.com/seladb/PcapPlusPlus/files/7509375/code.snippet.for.pseudo.header.computing.txt)

**Comment by angelyouyou** [comment]
> @seladb
> 
> From [RFC8200](https://datatracker.ietf.org/doc/rfc8200/) chapter 8.1, we know the format of IPv6 pseudo header is like below:
> 
> ```
> struct ip6_pseudo_header {
>         uint8_t ipSrc[16];
>         uint8_t ipDst[16];
>         uint32_t upperLen;
>         uint8_t zero[3];
>         uint8_t nextHeader;
>     };
> ```
> 
> _**Can you help me to explain for the two questions below ? I am planning to submit the pseudo header computing function to master repo and want to know the reason.**_ After I read the PcapPlusPlus Code(UDPLayer and TCP Layer), I found the format and length in PcapPlusPlus is different with the RFC8200.But the checksum result is correct.
> 
> 1. The format is different with RFC8200, include the length of upperLen, zero and nextHeader fields.
> 2. The total length of IPv6 pseudo header in RFC8200 is 40 bytes, but PcapPlusPlus is 36 bytes(see UDPLayer code snippet below).
>    ![image](https://user-images.githubusercontent.com/12936259/141037209-5fedcc01-adf8-4df9-a256-8d328231bcd9.png)
> 
> My code for computing general pseudo header for IPv4 and IPv6(It is now running correct) _**Can you help me review this function and make suggestions? In this case, I can modify it locally and then submit the pr.**_ [code snippet for pseudo header computing.txt](https://github.com/seladb/PcapPlusPlus/files/7509375/code.snippet.for.pseudo.header.computing.txt)

@seladb

**Comment by seladb** [comment]
@angelyouyou when calculating the pseudo-header for IPv6 you only need to take the source and dest IP addresses, protocol and the TCP/UDP length. Here is a StackOverflow issue that describes it:
https://stackoverflow.com/a/33133544

The size of the pseudo-header is 36 bytes: IP src (16 bytes) + IP dst (16 bytes) + protocol (2 bytes) + TCP/UDP length (2 bytes)

**Comment by angelyouyou** [comment]
> @angelyouyou when calculating the pseudo-header for IPv6 you only need to take the source and dest IP addresses, protocol and the TCP/UDP length. Here is a StackOverflow issue that describes it: https://stackoverflow.com/a/33133544
> 
> The size of the pseudo-header is 36 bytes: IP src (16 bytes) + IP dst (16 bytes) + protocol (2 bytes) + TCP/UDP length (2 bytes)

From RFC8200 chapter 8.1, the format of IPv6 pseudo header is define like below(40bytes):

```
struct ip6_pseudo_header {
        uint8_t ipSrc[16];
        uint8_t ipDst[16];
        uint32_t upperLen;
        uint8_t zero[3];
        uint8_t nextHeader;
    };
```

![image](https://user-images.githubusercontent.com/12936259/144573965-8ff07730-93c2-47a0-aa24-35fb82f5231e.png)

**Comment by seladb** [comment]
I think they basically represent the same values:
- 3 bytes of trailing zeros + next header == protocol (can be 6 for TCP and 17 for UDP)
- Upper-Layer Packet Length == TCP/UDP length

The `computeChecksum()` method basically adds all of these values so the trailing zeros don't really matter
