### ISSUE TITLE
A question about byte order of computeChecksum.

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#756]
I have wrote over VRRP packet in PcapPlusPlus.I found the checksum is not correct after calling computeChecksum. 
The checksum is network order(value is correct, value is 0x38FA), after calling macro htobe16 is wrong(value is 0xFA38).

**_Can you help me to fix it?Thanks very much._**

My develop CPU architecture is Intel x64(MacOS).
```
 uint16_t VrrpV2Layer::calculateChecksum(bool writeResultToPacket) {
        vrrp_packet* vrrpPacket = (vrrp_packet*)getData();
        ScalarBuffer<uint16_t> buffer = {(uint16_t*)vrrpPacket, getHeaderLen()};

        uint16_t checksum = computeChecksum(&buffer, 1);
        if (writeResultToPacket) {
            vrrpPacket->checksum = htobe16(checksum);
        }

        return checksum;
    }
```

The correct VRRP packet have correct checksum:
`01005e00001200005e000101080045c0002800000000007018cec0a8001ee000001221016403000138fac0a80001c0a80002c0a80003`

The VRRP packet have wrong checksum:
`01005e00001200005e000101080045c0002800000000007018cec0a8001ee0000012210164030001f6f6c0a80001c0a80002c0a80003`

![image](https://user-images.githubusercontent.com/12936259/141046542-15e210bf-24ba-4aae-8d60-8a71956a084e.png)
@seladb

**Comment by seladb** [comment]
@angelyouyou I'm currently out and can't look into this issue. I'll try to take look when I'm back next week

**Comment by angelyouyou** [comment]
> @angelyouyou I'm currently out and can't look into this issue. I'll try to take look when I'm back next week

@seladb OK.Thanks.

**Comment by seladb** [comment]
@angelyouyou I'm not familiar with the VRRP protocol so I'm not sure how the checksum should be calculated.

Here is the Wireshark decoder for this protocol, maybe you can use it as a reference:
https://github.com/wireshark/wireshark/blob/eb5f4eea99593b92298bacecc5c9d885cc13a9ad/epan/dissectors/packet-vrrp.c

**Comment by angelyouyou** [comment]
> https://github.com/wireshark/wireshark/blob/eb5f4eea99593b92298bacecc5c9d885cc13a9ad/epan/dissectors/packet-vrrp.c

@seladb 
I have read many implements about VRRP include wireshark, but have no idea .....

**Comment by seladb** [comment]
Unfortunately I don't know how to help you further as I'm not familiar with the VRRP protocol...
