### ISSUE TITLE
ipv4::parseNextLayer doesn't support ipv6 protocol ( protocol field value equal to 41 ).

### ISSUE THREAD

**Issue by alexdrobinsky** [seladb/PcapPlusPlus#758]
Hello dear developers,

I stumbled upon problem with parsing of pcap with ipv6 encapsulated into ipv4 , looks like switch case missing following lines:

    case PACKETPP_IPPROTO_IPV6:
        m_NextLayer = new IPv6Layer(payload, payloadLen, this, m_Packet);
        break;

I verified with test pcap file that fix works properly. Could you add it to IPV4Layer.cpp ?
Best regards,
Alexander

**Comment by seladb** [comment]
You're right @alexdrobinsky , that's indeed missing. Would you consider opening a PR with the fix?
Also - can you provide a sample pcap file we can use in the [tests](https://github.com/seladb/PcapPlusPlus/blob/master/Tests/Packet++Test/Tests/IPv4Tests.cpp)?

**Comment by alexdrobinsky** [comment]
Sorry for huge delay in response, below attached pcap with relevant scenario

ср, 24 нояб. 2021 г. в 07:48, seladb ***@***.***>:

**Comment by seladb** [comment]
thanks @alexdrobinsky, however I cannot see the pcap file. Can you attach it again to the issue?

**Comment by alexdrobinsky** [comment]
Attached for sure, hopefully some dumb antivirus doesn't prevent it

пт, 3 дек. 2021 г. в 09:03, seladb ***@***.***>:

**Comment by seladb** [comment]
@alexdrobinsky I still can't see this file, maybe it's because you're replying from an email? 🤔 
Can you reply from GitHub directly and drag/attach the file to the issue?

**Comment by alexdrobinsky** [comment]
[FTP_ipv6_onlyControl.zip](https://github.com/seladb/PcapPlusPlus/files/7728004/FTP_ipv6_onlyControl.zip)
Looks like this e-mail ( even drag and drop ) doesn't support pcap files. Hopefully, storing it in zip file should solve the issue.

**Comment by seladb** [comment]
thanks @alexdrobinsky , I can see the file now. I'll work on the fix and keep you posted

**Comment by seladb** [comment]
Fixed in #810 , thank you @egecetin ! 🙏
