### ISSUE TITLE
The IPFilter fails to capture any data

### ISSUE THREAD

**Issue by jmp19940829** [seladb/PcapPlusPlus#759]
//pcpp::PortFilter portFilter1(2000, pcpp::SRC_OR_DST);
	pcpp::ProtoFilter protocolFilter(pcpp::TCP);
	std::string strIp = "112.114.50.228";
	pcpp::IPFilter portFilter(strIp, pcpp::SRC_OR_DST);

	pcpp::AndFilter andFilter;
	std::string str;
	
	andFilter.addFilter(&protocolFilter);
	andFilter.addFilter(&portFilter);
	dev->setFilter(andFilter);
	andFilter.parseToString(str);
	dev->startCapture(onPacketArrives, &stats);

**Comment by seladb** [comment]
@jmp19940829 the code is somewhat confusing, `portFilter` is actually an IP filter? 🤔 

Anyway, this can happen for many reasons. Are you sure the packets actually arrive to the network card? Did you capture them using Wireshark or tcpdump?

**Comment by jmp19940829** [comment]
> @jmp19940829 the code is somewhat confusing, `portFilter` is actually an IP filter? 🤔 
> 
> 
> 
> Anyway, this can happen for many reasons. Are you sure the packets actually arrive to the network card? Did you capture them using Wireshark or tcpdump?

I have tested, using portFilter for port filtering, is able to capture the packet, using IPFilter IP is captured nothing! It's confusing to me

**Comment by seladb** [comment]
Here are a few ways to debug:
- Try to capture the same traffic (TCP + IP address) using Wireshark/tcpdump. Do you incoming packets?
- What happens if you disable the TCP filter and try to capture with only IP filter?

**Comment by jmp19940829** [comment]
> Here are a few ways to debug:
> 
> - Try to capture the same traffic (TCP + IP address) using Wireshark/tcpdump. Do you incoming packets?
> 
> - What happens if you disable the TCP filter and try to capture with only IP filter?
> 
> 

Everything else is normal! Disable TCP filtering and catch nothing!

**Comment by seladb** [comment]
It's hard to debug it without further information...

**Comment by seladb** [comment]
I'm closing this issue, please reopen it if needed
