### ISSUE TITLE
how to Parse https(such as RSA)

### ISSUE THREAD

**Issue by ygm521** [seladb/PcapPlusPlus#76]
when has the private key, how to Parse https(such as RSA), thanks!

**Comment by seladb** [comment]
I guess you're asking about how to decrypt HTTPS data if you have the private key.
Unfortunately this is currently not available in PcapPlusPlus.

**Comment by seladb** [comment]
please let me know if you have any more questions. Otherwise, can you close this issue?

**Comment by seladb** [comment]
Closing this issue due to lack of responsiveness. Please reopen it if needed
