### ISSUE TITLE
Does PcapPlusPlus support to be integrated with CMake project?

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#760]
Can I use PcapPlusPlus from a CMakeList project? 
If PcapPlusPlus supports it, is there a corresponding development guide?

**Comment by seladb** [comment]
@angelyouyou yes, PcapPlusPlus can be used with a CMake project. You can search in GitHub and find projects that use it:
https://github.com/search?l=CMake&q=pcapplusplus&type=code

**Comment by angelyouyou** [comment]
> @angelyouyou yes, PcapPlusPlus can be used with a CMake project. You can search in GitHub and find projects that use it: https://github.com/search?l=CMake&q=pcapplusplus&type=code

OK.Thanks very much.It wil be more friendly if the example in our example and manual.

**Comment by seladb** [comment]
This is not officially supported, hence it doesn't appear in the documentation

**Comment by angelyouyou** [comment]
Can it be turned into an official version? At the same time maintain Pcapplusplus's own build method (make). This is one more choice for external users.
