### ISSUE TITLE
Missing the first and second packet when reading pcap, write into pcap.zstd file then decompress this pcap.zstd file (pcpp v2008).

### ISSUE THREAD

**Issue by ThinhNX** [seladb/PcapPlusPlus#764]
(First, Im sorry because I can not see any forums to talk about this, then I create this issue.)
Pcpp v20.08, g++ 4.8.2, RHEL 6.8
What did I do?
1. Compression
- Creat a IFile reader to read **original.pcap** file
- Create a pcapng writer to write the rawPacket from reader into a pcap.zstd file  **pcapNgWritter("original.pcap.zstd", 10)** (without any filters). 
2. Decompression
- Create a ngpcap reader to read the file .pcap.zstd created before
- Create a ngpcap writter to write rawPacket into original_output.pcap (without any filters)

Then I got a problem:
- The file **original_output.pcap** misses the first and the second packet compare with the **original.pcap**

Please let me know how to fix this.
Thank you very much.

**Comment by seladb** [comment]
@ThinhNX did you try to open `pcap.zstd` in Wireshark? Does it contain all the packets?
Also, can you post the code that writes and reads and maybe also `original.pcap`?

**Comment by seladb** [comment]
@ThinhNX should we keep this issue open?

**Comment by seladb** [comment]
I'm closing this issue now, please reopen if needed
