### ISSUE TITLE
Failed to link for android project

### ISSUE THREAD

**Issue by xfxdev** [seladb/PcapPlusPlus#765]
Hi, when I link to android project, I got this error:

```
ld: error: undefined symbol: sigemptyset
  >>> referenced by SystemUtils.cpp:378 (src/SystemUtils.cpp:378)
  >>>               SystemUtils.o:(pcpp::ApplicationEventHandler::onApplicationInterrupted(void (*)(void*), void*)) in archive 
```

This is because android-19 is the last platform version where sigemptyset() (and many other functions) was declared as inline just at platform headers. As result - system libc on that devices doesn't contain such functions.

**Comment by seladb** [comment]
thanks @xfxdev for reporting this issue!
Can you please elaborate on what is android-19? AFAIK the latest API level is 30 and the build passes successfully with it, so I'm not sure on which target / API level is fails

**Comment by xfxdev** [comment]
@seladb Hi, thanks for your reply.
It will link fail with `minSdkVersion=19 / targetSdkVersion=30`. After check your document, I learned that the support API versions is 21-30. So I change minSdkVersion to 21, and there is no problem, thanks!

**Comment by seladb** [comment]
Ok great, I'm glad the issue has been solved, thanks for the update 👍
