### ISSUE TITLE
How to get the traffic statistics of each domain name of http and https? And how to get the file information sent in the tcp and udp packets (Deep Packet Inspection)

### ISSUE THREAD

**Issue by LoveChina-3000** [seladb/PcapPlusPlus#768]
How to get the traffic statistics of each domain name of http and https? And how to get the file information sent in the tcp and udp packets (Deep Packet Inspection)

**Comment by seladb** [comment]
I think you can look at the following examples:
- [HttpAnalyzer](https://github.com/seladb/PcapPlusPlus/tree/master/Examples/HttpAnalyzer)
- [SSLAnalyzer](https://github.com/seladb/PcapPlusPlus/tree/master/Examples/SSLAnalyzer)

Please let me know if you have further questions

**Comment by seladb** [comment]
I'm closing the issue now, please reopen if you have further questions
