### ISSUE TITLE
how to parse http packet?

### ISSUE THREAD

**Issue by ygm521** [seladb/PcapPlusPlus#77]
we get http packet, and how to parse http packet? such as get headers, post body.

**Comment by seladb** [comment]
Currently only HTTP headers can be parsed, please take a look at [this tutorial](http://seladb.github.io/PcapPlusPlus-Doc/tutorial_packet_parsing.html) to see how to parse them

**Comment by seladb** [comment]
please let me know if you have any more questions. Otherwise, can you close this issue?

**Comment by seladb** [comment]
Closing this issue due to lack of responsiveness. Please reopen it if needed
