### ISSUE TITLE
[Question] Use dpdk with Libpcap-based PMD

### ISSUE THREAD

**Issue by Matheus-Garbelini** [seladb/PcapPlusPlus#770]
Hello, I was trying to test `DpdkBridge` example with  dpdk running in a pcap interface which sets a [pmd for pcap](https://github.com/seladb/PcapPlusPlus/blob/4a20054a1f150134405c85bf1724d9309caf4fa1/Pcap%2B%2B/src/DpdkDevice.cpp#L440).

It seems I cannot pass the name of the pcap interface to this example the same way it's possible to do with [dpdk example](https://doc.dpdk.org/guides/nics/af_packet.html):
`./<build_dir>/app/dpdk-testpmd -l 0-3 -n 4 --vdev 'net_pcap0,rx_iface_in=eth1,tx_iface=eth1'`

Previously, I could pass the EAL `--vdev` argument which selected the correct pmd drivers.
Do you have an example on how to pass the correct arguments via PcapPlusPlus?

**Comment by seladb** [comment]
@Matheus-Garbelini sorry for the late response. Unfortunately passing additional arguments to `DpdkBridge` is not currently possible. As you can see [here](https://github.com/seladb/PcapPlusPlus/blob/master/Pcap%2B%2B/src/DpdkDeviceList.cpp#L96-L125) there is only a specific set of parameters that can be passed in DPDK initialization. 

This request seems somewhat similar to this PR: https://github.com/seladb/PcapPlusPlus/pull/769

Maybe we can consider adding `argc` and `argv` params to [`DpdkDeviceList::initDpdk()`](https://github.com/seladb/PcapPlusPlus/blob/85e34dc165a7954d7aa28d4ccf56b49349b5cec5/Pcap%2B%2B/src/DpdkDeviceList.cpp#L69) which can contain optional parameter the user wants to pass 🤔

**Comment by seladb** [comment]
@Matheus-Garbelini I merged PR #769 so it's now possible to pass additional args to `DpdkDeviceList::initDpdk()`, however this is not yet used in any of the examples including `DpdkBridge`. Would you consider adding it to the examples?

**Comment by Matheus-Garbelini** [comment]
@seladb thanks a lot. I'll try to add something when I have time.
I really appreciate your project. For example, I've been using pcapng reader/writter with packet comments for many things.
