### ISSUE TITLE
Error "Too many open files" when analyzing a number of pcaps

### ISSUE THREAD

**Issue by FisherDock** [seladb/PcapPlusPlus#771]
Hi,

I'm using PcapPlusPlus to analyze a large number of pcaps (about 1500+ files) in a single directory, and error occurred:

`[ERROR: src/PcapFileDevice.cpp: open:142 ] Cannot open file reader device for filename. xx.pcap. Too many open files`.

Is there a file number limit? Please let me know how to solve this issue. Thanks.

**Comment by seladb** [comment]
I think this error comes from the operating system or from libpca, not from PcapPlusPlus. There is a limit to the number of concurrent open files.
I've tackled this problem in the [PcapSplitter example](https://github.com/seladb/PcapPlusPlus/blob/master/Examples/PcapSplitter/Splitters.h#L70-L155) which keeps no more than `MAX_NUMBER_OF_CONCURRENT_OPEN_FILES` and closes files that were least recently used. 
You can use this example for your project.

**Comment by FisherDock** [comment]
@seladb Thanks very much.  BTW, any suggestion to use multithread to process multiple pcaps using PcapPlusPlus?  I haven't tried multiple threading. Hopefully it works.

**Comment by seladb** [comment]
Yes, it is possible to use multithreading to process multiple pcap files simultaneously. Just make sure you don't share a `PcapFileReaderDevice` or `PcapFileWriterDevice` instance between multiple threads

**Comment by FisherDock** [comment]
@seladb  Many thanks. I may add a multiple threading example to the project later if there is no such example.

**Comment by seladb** [comment]
Sounds good, that would be a nice contribution! 🙏
