### ISSUE TITLE
Alpine/Musl compilation not working

### ISSUE THREAD

**Issue by dehmarc** [seladb/PcapPlusPlus#773]
Hello,

I used the latest version 21.11 as I saw that it now has an additional flag for musl.

**Steps to reproduce:**
Clone v21.11
`run configure-linux.sh --musl`

The following errors occur during build:
`3rdParty/MemPlumber/MemPlumber/memplumber.cpp:361:10: fatal error: execinfo.h: No such file or directory`
` 361 | #include <execinfo.h>`

**Analysis**
I checked the relevant files and it seems that MemPlumber [only looks at mk/platform.mk](https://github.com/seladb/PcapPlusPlus/blob/ddce58723a4ef7ab19bf1507e6323990b4d2d15e/3rdParty/MemPlumber/Makefile.defs#L5).
The problem is that the musl flag is only written to the [mk/PcapPlusPlus.m](https://github.com/seladb/PcapPlusPlus/blob/ddce58723a4ef7ab19bf1507e6323990b4d2d15e/configure-linux.sh#L343)

**Solution**
exemplary PR to fix the issue will be created separately. 
PR for reference #774

**Comment by seladb** [comment]
Thanks for providing the fix @dehmarc !
I just merged your PR
