### ISSUE TITLE
problem with installing 

### ISSUE THREAD

**Issue by eladcohen333** [seladb/PcapPlusPlus#776]
hi 
im try to install the packege , but i dont successful .
i have vs 2019
when i go to configure-windows-visual-studio when i enter the last path of pthreads-32 the cmd just turned off(windows closed Suddenly)
i wiil be happy to any help please

tnx elad
eladcohen333@gmail.com

**Comment by seladb** [comment]
do you mean that the command-line window suddenly closes?
What I'd suggest is that you:
1. Open a command line (Start -> "cmd")
2. Go to PcapPlusPlus folder (`cd ......`)
3. Run `configure-windows-visual-studio.bat` and fill in the necessary details
4. After you're done you should see a message that starts like this: `PcapPlusPlus Visual Studio configuration is complete. Files created (or modified): .....`

You can also follow the instructions on PcapPlusPlus web-site: https://pcapplusplus.github.io/docs/install/build-source/vs

**Comment by eladcohen333** [comment]
in level 3 on cd when i arrive to last message :"pthreads-win32 is required for compiling PcapPlusPlus."
this p have a 3 p: QueueUserAPCEx  , pthreads.2,Pre-built.2) 
i put all in 1 folder and when i put the path in cd ,
its just close after 2-3 secondes without any message , just closed .
i follow the instructions and still stucking with this problem
please help me
tnx elad

**Comment by seladb** [comment]
Can you attach a short video to show what happens?
I'm not sure why the command-line window may close, maybe your user doesn't have permission to write to this folder?

**Comment by eladcohen333** [comment]
yes

**Comment by eladcohen333** [comment]
https://user-images.githubusercontent.com/77234157/149680658-a7360c89-0784-4a86-ada8-4b0e5358e54c.mp4

**Comment by seladb** [comment]
@eladcohen333 I think the configuration script actually succeeded 😃 
Since you're double-clicking the `.bat` file it runs in a separate command-line window which closes when the script ends.
If you want to see the full output you should follow the steps I mentioned before:
1. Click the "Start" button and then type "cmd". A new command-line window will open
2. Navigate to the PcapPlusPlus folder (using the `cd` command etc.)
3. Run the `configure-windows-visual-studio.bat` script from the PcapPlusPlus folder
4. Follow the same steps steps you did in this video
5. Now the command-line window will not close (because you opened it yourself)
6. At the end you should see an output like this which indicates the script ran successfully:
   ```shell
   PcapPlusPlus Visual Studio configuration is complete. Files created (or modified): PcapPlusPlusPropertySheet.props, Arping.vcxproj,
   ArpSpoofing.vcxproj, Common++.vcxproj, DNSResolver.vcxproj, DnsSpoofing.vcxproj, HttpAnalyzer.vcxproj, IcmpFileTransfer-catcher.vcxproj,
   IcmpFileTransfer-pitcher.vcxproj, IPDefragUtil.vcxproj, IPFragUtil.vcxproj, LightPcapNg.vcxproj, Packet++.vcxproj, Packet++Test.vcxproj,
   Pcap++.vcxproj, Pcap++Test.vcxproj, PcapPrinter.vcxproj, PcapSearch.vcxproj, PcapSplitter.vcxproj, SSLAnalyzer.vcxproj, TcpReassembly.vcxproj,
   Tutorial-HelloWorld.vcxproj, Tutorial-LiveTraffic.vcxproj, Tutorial-PacketCraftAndEdit.vcxproj, Tutorial-PacketParsing.vcxproj,
   Tutorial-PcapFiles.vcxproj
   ```

**Comment by eladcohen333** [comment]
its work tnx you
now i dont s to run the  tests file how i can do it ?

**Comment by seladb** [comment]
If you're referring to PcapPlusPlus tests please take a look here:
https://pcapplusplus.github.io/docs/tests

**Comment by eladcohen333** [comment]
what i can do?
the project cant be loaded

**Comment by seladb** [comment]
it seems you're opening the wrong `.sln` file. If you're using VS 2019 the `.sln` file will be in:
`C:\Users\DELL\Desktop\pca\mk\vs2019\PcapPlusPlus.sln`

**Comment by seladb** [comment]
@eladcohen333 can we close this issue?

**Comment by seladb** [comment]
@eladcohen333 I'm closing this issue now, please reopen if needed
