### ISSUE TITLE
Are there plans to support the ND (Neighbor Discovery) protocol in ICMPv6? 

### ISSUE THREAD

**Issue by angelyouyou** [seladb/PcapPlusPlus#779]
Are there plans to support the ND (Neighbor Discovery) protocol in ICMPv6? This is crucial in IPv6 communication, similar to the ARP protocol in IPv4. Is it possible to consider supporting NA (Neighbor Advertisement) and NS (Neighbor Solicitation) first, so that the user can learn the MAC address normally (similar to ARP request and response).

**Comment by seladb** [comment]
ICMPv6 is not yet supported in PcapPlusPlus, but you're more than welcome to add it 😃

**Comment by angelyouyou** [comment]
> ICMPv6 is not yet supported in PcapPlusPlus, but you're more than welcome to add it 😃

OK.I am planning to submit VRRP and NetFlow protocol to master.Theres are some bugs to be fixed. After that I will try to add ICMPv6.

ICMPv6 is more important and complex than ICMPv4. Examples include ICMP ND (NA, NS, RS, RA, Redidrect), MLD (IPv6 version of IGMP), Ping (request and response), and so on. Can you help me with some abstract ideas of code framing to do it better?

**Comment by seladb** [comment]
Sounds good, thank you! 🙏

**Comment by seladb** [comment]
@angelyouyou any progress on this?

**Comment by maruu** [comment]
Hi @seladb 

we are planning on creating a PR with a limited version of ICMPv6 and NDP.

We used it to parse and craft NDP Neighbor solicitation and Advertisements.

We are currently preparing another protocol for upstreaming to PcapPlusPlus. (SOME/IP)
Afterwards we would continue with ICMPv6 / NDP.

Looking forward to the collaboration.

All the best,
maruu

**Comment by seladb** [comment]
@maruu sounds good, I really appreciate your contribution and support! 🙏

**Comment by maruu** [comment]
@angelyouyou we have created https://github.com/seladb/PcapPlusPlus/pull/902 to add support for ICMPv6 and NDP. Let me know what you think

**Comment by seladb** [comment]
ICMPv6 and NDP were added in #902 . Thank you @kolbex for this great contribution!
