### ISSUE TITLE
C++17 incompatibility in Packet++ lib

### ISSUE THREAD

**Issue by echo-Mike** [seladb/PcapPlusPlus#78]
Library Packet++ can't be build with gcc/g++ version 7.0.* or higher if -std=c++17 flag is specified within build instructions for object files in next Makefiles:  
* Common++/Makefile:42
* Pacp++/Makefile:70
* Packet++/Makefile:36
* Pcap++Test/Makefile:39
* Packet++Test/Makefile:23  

My purpose was to use PcapPlusPlus library in project that written in terms of c++17 standard.  
Using flag -std=c++14 was found that in following files deprecated function (constructors) definitions was used:  
* Packet++/header/SipLayer.h:542 paired with  Packet++/src/SipLayer.c:133
* Packet++/header/HttpLayer.h:573 paired with  Packet++/src/HttpLayer.c:212  

See [P0003R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0003r0.html)  for details on deprecated definition.  
Pull request for closing this issue will be done in next couple of hours. The build process of library with changes was tested on Ubuntu 16.04.3 LTS with gcc 7.1.0.

**Comment by seladb** [comment]
Resolved in PR #79
