### ISSUE TITLE
pcpp::IPv4Address::toBytes()

### ISSUE THREAD

**Issue by JasMetzger** [seladb/PcapPlusPlus#783]
I just started using PCAP++. After parsing a raw packet and analyzing the IPv4 layer addresses, the toString() appears to work but the toBytes() returns rubbish on Linux but returns correct information on Visual Studio. Version using is 21.11

**Comment by JasMetzger** [comment]
It appears that this will work:

pcpp::IPv4Address srcipaddress = ipv4Layer->getSrcIPv4Address();
const uint8_t *ipv4src = srcipaddress.toBytes();

but this will not
const uint8_t *ipv4src =  ipv4Layer->getSrcIPv4Address().toBytes();
probably regarding a copy constructor I suppose

**Comment by seladb** [comment]
could you please elaborate on what you mean by "rubbish"? What is actually returns vs. what you expect it to return?

**Comment by JasMetzger** [comment]
Hello seladb. Yes, The address bytes are not returned. I print out the array of 4 bytes and I get FF FF FF FF and not the address bytes of the packet. It seems to be pointing to some other place in memory? Or, my theory, there might be a copy constructor not allocating the bytes and copying them? Not sure. I just thought I'd point this out. What was working in VS gave a different result in GCC and it may be something different about how the compilers interpret the phrase.

**Comment by seladb** [comment]
Got it, let me check and get back to you

**Comment by seladb** [comment]
@JasMetzger I think I know what's the issue.
`toBytes()` returns the address of the internal `m_Bytes` array. Now, `ipv4Layer->getSrcIPv4Address()` creates a new instance of `IPv4Address`. So what happens is:
```cpp
const uint8_t *ipv4src = ipv4Layer->getSrcIPv4Address().toBytes()  ---> the new instance of IPv4Address is freed
                         |----------------------------| |-------|
                                a new instance of        returns
                             IPv4Address is created    the address
                                                        of m_Bytes
----> because IPv4Address was freed `ipv4src` contains garbage now and when accessing it you're actually trying to access unallocated memory
```

Please let me know if it makes sense

**Comment by JasMetzger** [comment]
seladb thanks for confirming my suspicion--I figured that was something of the problem. But it worked on Visual Studio just fine (or I was getting lucky?) and did not work in linux (gcc 9.3.0). Is this a bug? Wouldn't the m_Bytes array get copied in the new instance too? At this point I have a work around so I'm cool. I just wanted to bring it to the community's attention.

**Comment by seladb** [comment]
I don't think it's a bug, this is how c++ works. I'm not sure why VS gives the "right" result, but anyway it's accessing unallocated memory...
A way to "fix" it is by allocating a new buffer within IPv4Address and return it, but then the user will need to free it (otherwise there will be a memory leak)

**Comment by seladb** [comment]
@JasMetzger should we close this issue?

**Comment by JasMetzger** [comment]
Sure--I only brought it to your attention because I thought it was an issue. I have a working set and am content. Please close the issue.
