### ISSUE TITLE
配置成功后，用Vs2019打开就报错

### ISSUE THREAD

**Issue by qq805005062** [seladb/PcapPlusPlus#784]
![1642649600(1)](https://user-images.githubusercontent.com/22863573/150267529-3accbb84-2405-4723-a238-7cdb09e8a1ed.png)
![1642649680(1)](https://user-images.githubusercontent.com/22863573/150267550-18743911-6edd-4f44-bc7e-6872c516ae9d.png)
![1642649697(1)](https://user-images.githubusercontent.com/22863573/150267567-baabc005-025f-47bb-82b6-e7a952f40d8c.png)
是不是我少了那步骤没执行？

**Comment by angelyouyou** [comment]
@qq805005062 这个是VS的问题，百度一下就能解决了，跟当前这个项目没有关系。

**Comment by qq805005062** [comment]
> @qq805005062 这个是VS的问题，百度一下就能解决了，跟当前这个项目没有关系。

好的

**Comment by qq805005062** [comment]
> @qq805005062 这个是VS的问题，百度一下就能解决了，跟当前这个项目没有关系。
与第一行开头乱码有关
![1642657604(1)](https://user-images.githubusercontent.com/22863573/150280864-62ad707b-e073-4453-9566-1661c5bfd8cf.png)
所有的.vcxproj文件第一行开头都是乱码的，改完后正常了
![1642659405(1)](https://user-images.githubusercontent.com/22863573/150284029-7afc1352-9cb3-465b-9b3e-8a53947689c1.png)

**Comment by seladb** [comment]
BTW, I don't understand Chinese so please use English in issues...
