### ISSUE TITLE
如何设置让configure-windows-visual-studio.bat 使用静态链接库pthreadVSE2.lib，而不是动态链接库

### ISSUE THREAD

**Issue by qq805005062** [seladb/PcapPlusPlus#786]
error MSB3073: 命令“xcopy "E:\pthreads-w32\Pre-built.2\dll\x64\pthreadVC2.dll" "D:\workspace\github\PcapPlusPlus\Tests\Pcap++Test\Bin" /Y
我使用Pcap++.lib静态库的时候它提示要我给提供pthreadVC2.dll动态库，而静态库的路径我已经添加了，根本不调用

**Comment by seladb** [comment]
Please translate to English

**Comment by qq805005062** [comment]
> Please translate to English
I use pcap + +.lib When the Lib static library, it prompted me to provide pthreadvc2 DLL Dynamic Library, and I have added the path of static library.don't call pthreadvc2 at all lib

**Comment by seladb** [comment]
I'm not sure I understand. I think that WinPcap actually needs `pthreadvc2`, not PcapPlusPlus directly.

**Comment by seladb** [comment]
@qq805005062 should we close this issue?

**Comment by seladb** [comment]
@qq805005062 I'm closing this issue now, please reopen if needed
