### ISSUE TITLE
Windows 10，WpdPack_4_1_2 or npcap-1.60  run DnsSpoofing of Examples fail

### ISSUE THREAD

**Issue by qq805005062** [seladb/PcapPlusPlus#792]
![1643094878(1)](https://user-images.githubusercontent.com/22863573/150928922-1c9ef779-c319-4373-a3f2-cc845f7cae99.png)
Run failed here
"Error setting the capture mode for device"

**Comment by seladb** [comment]
Maybe a permissions issue with the user running it? 🤔

**Comment by qq805005062** [comment]
> Maybe a permissions issue with the user running it? 🤔
Permissions have been configured
1、requireAdministrator (/level='requireAdministrator')

2、[ERROR: D:\workspace\github\PcapPlusPlus\Pcap++\src\WinPcapLiveDevice.cpp: pcpp::WinPcapLiveDevice::startCapture:29] Error setting the capture mode for device '\Device\NPF_{22642BEC-89C2-48C3-9FF2-9F4012299A2C}'
![1643111968(1)](https://user-images.githubusercontent.com/22863573/150973163-c89d67fb-a0fa-4b5e-bec3-728c0998127e.png)
3、Just comment it out here
![1643112304(1)](https://user-images.githubusercontent.com/22863573/150973924-b9fcafc3-33f4-4c76-95a5-ef082f79d38c.png)

5、
Now you can only grab Ethernet messages，Can I support the wireguard network card to capture packets?
thank you

**Comment by seladb** [comment]
@qq805005062 can you try to add `pcap_geterr()` to see what the error is?

```cpp
if (pcap_setmode(m_PcapDescriptor, MODE_STAT) < 0)
{
    LOG_ERROR("Error setting the statistics mode for device '" << m_Name << "', error is: " << pcap_geterr(m_PcapDescriptor));
    return false;
}
```

**Comment by qq805005062** [comment]
> If that works you can open a PR with this change, might be useful for others

[ERROR: D:\workspace\github\PcapPlusPlus\Pcap++\src\WinPcapLiveDevice.cpp: pcpp::WinPcapLiveDevice::startCapture:29] Error setting the statistics mode for device '\Device\NPF_{22642BEC-89C2-48C3-9FF2-9F4012299A2C}', error is: driver error: working mode not recognized

 error is: driver error: working mode not recognized

**Comment by seladb** [comment]
@qq805005062 I googled this error and here are a few interesting threads I found:

https://github.com/odedshimon/BruteShark/issues/99

https://www.winpcap.org/pipermail/winpcap-users/2007-October/002137.html

It looks like this error comes from this part of WinPcap / Npcap / libpcap code:
https://github.com/limhoff-r7/libpcap/blob/master/pcap-win32.c#L140-L148

Which actually call `PacketSetMode()` which is defined in `Packet32`:
https://github.com/clemensg/pcap/blob/master/packetNtx/Dll/Packet32.c#L2590

Is the NIC you're trying to capture packets from a standard Ethernet device or is it a WiFi, USB or AirPcap interface?

**Comment by qq805005062** [comment]
> Ethernet device
 interface is Hardware network card，Ethernet of windows 10，Just comment out these lines of code

**Comment by seladb** [comment]
to be honest, I don't know what's causing the error. It works fine on every Windows machine I used. Do you have another Windows machine with a different NIC to test with?

**Comment by seladb** [comment]
I'm closing the issue now, please reopen if still relevant
