### ISSUE TITLE
TcpReassembly OnTcpMessageReady function signature

### ISSUE THREAD

**Issue by echo-Mike** [seladb/PcapPlusPlus#80]
Currently TcpReassembly::OnTcpMessageReady function type is defined as follows:  
```
typedef void (*OnTcpMessageReady)(int side, TcpStreamData tcpData, void* userCookie)
```  
This definition contains a big drawback - `tcpData` object is passed by value. By the definition of TcpStreamData copy constructor will be called which will result in full packet copy in TcpStreamData::copyData and this is an impractical behaviour in highload systems.  
The major reason to change OnTcpMessageReady function signature to:  
```
typedef void (*OnTcpMessageReady)(int side, TcpStreamData& tcpData, void* userCookie)
```  
or
```
typedef void (*OnTcpMessageReady)(int side, TcpStreamData&& tcpData, void* userCookie)
```   
with subsequent addition of move constructor and assignment operator to TcpStreamData class is that on every occasion of this function call from TcpReassembly object side (via m_OnMessageReadyCallback function pointer) in:  
* TcpReassembly.c:281
* TcpReassembly.c:316
* TcpReassembly.c:357
* TcpReassembly.c:478
* TcpReassembly.c:514
* TcpReassembly.c:596  

provided `tcpData` object is temporary and have no reason to be copied.  
As well no other class in whole library have access to this pointer so there is no other calls possible.

**Comment by seladb** [comment]
I passed `tcpData` by value on purpose thinking that in some cases the user would like to use this data outside of the context of the callback. If the data isn't copied it may not be valid anymore.
I agree that coping the data may be problematic in high load systems, but I wanted it to be safer and less error prone

**Comment by echo-Mike** [comment]
@seladb I provided some information to You by the email to pcapplusplus@gmail.com  
Please check it and give a response by email or provide some other email to send my response to.

**Comment by seladb** [comment]
I don't think this should be changed to prevent mis-usage if this data outside of the callback. I'm closing this issue now. Please re-open if it you think otherwise
