### ISSUE TITLE
te_mempool_create get memory error!

### ISSUE THREAD

**Issue by ygm521** [seladb/PcapPlusPlus#81]
搞dpdk的请教下  rte_mempool_create 玩意申请内存失败。
我这都已经设置过了 还要设置啥？
/sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
2048

**Comment by seladb** [comment]
I don't understand Chinese so it'd be great if you can translate to English.
Are you asking about failure in creating memory pools?
Please read [this documentation](http://seladb.github.io/PcapPlusPlus-Doc/dpdk-pf_ring.html) about setting up DPDK in PcapPlusPlus and let me know if the problem still persists
