### ISSUE TITLE
TcpReassembly - OnTcpMessageReady should return original RawPacket object

### ISSUE THREAD

**Issue by topeolufe** [seladb/PcapPlusPlus#82]
Great work on creating this library! One suggestion I had is that the OnTcpMessageReady, OnTcpConnectionStart and OnTcpConnectionEnd callbacks should all have the original pointer to RawPacket as one of its parameters.

**Comment by seladb** [comment]
Thanks for expressing interest in PcapPlusPlus!
Regarding your suggestion - what can be the benefit of adding the pointer to RawPacket?
Can you describe me the use case where you need this pointer?

**Comment by topeolufe** [comment]
For scenarios where you want to use PcapPlusPlus solely for TCP packet reordering on a proxy that you can then forward unaltered to other nodes on your network for further processing. 

It also seems logical that since you call TcpReassembly.ReassemblePacket with the RawPacket*, then you should be able to get your RawPacket pointer back whenever any of those callbacks are fired.

**Comment by echo-Mike** [comment]
This suggestion works well. I personally agree with it. But, following my experience the base idea of owning a packet resource must be reworked first (in RawPacket, MBufRawPacket, Packet and TcpStream classes).

**Comment by topeolufe** [comment]
I think you will have to only make some changes in TcpStream, TcpReaseembly and TcpFragment classes along with obviously the callback signatures.

**Comment by seladb** [comment]
This scenario makes sense, let's do it. I also don't think it's a lot of work to add it.
@topeolufe - can you add it yourself and create a PR?
I'm currently working on adding IPv4 reassembly (de-fragmentation) to PcapPlusPlus so it'd be a great help if you can add it.

**Comment by echo-Mike** [comment]
@seladb I may take care of this proposal in holiday time (1-8 January), as a part of other enhancements block.

**Comment by seladb** [comment]
@echo-Mike - that would be great, thanks for all your help!

**Comment by topeolufe** [comment]
@seladb I'm currently tied up with some other development work on my end and I unfortunately do not have the bandwidth to make those changes.

@echo-Mike Thanks for taking the initiative on this!

**Comment by 11septday** [comment]
Thanks for you project. Please say, how I can read HTTP POST params? Example: name=Mike, age=23.

**Comment by seladb** [comment]
POST params are in the HTTP request body. I'm currently don't parse the body because it's usually compressed with gzip and is usually spreads over several packets. So in order to support full parsing of the body I need to support streaming + opening the compression. I have it in my roadmap but I can't provide specific timelines for this feature.
However, POST requests are often quite short (contained in 1 packet) and in some cases are not compressed. If that is the case then the way to read the HTTP body is by using the method `httpRequestLayer->getLayerPayload()` and parse the string you get

**Comment by seladb** [comment]
@topeolufe, @echo-Mike - I thought about this a little and maybe it's worth creating a new TCP packet reordering module alongside TPC reassembly. We can write a TCP packet reordering module which is simpler and more lightweight in terms of memory and performance comparing to TCP reassembly. So maybe it deserves a module of its own.
Please let me know what you think

**Comment by dijiang** [comment]
@seladb Great work on creating this library.
I'm using this library to analyse HTTP protocol. I agree that It's worth creating a new TCP packet reordering module . After that, we could analyse any protocol based on TCP easily.

**Comment by topeolufe** [comment]
@seladb - I agree...simpler and more lightweight is always good. I'll also suggest that the new TCP reassembly module should forward all packets (SYN and ACK included) - perhaps on demand by the user - for proxy scenarios mentioned earlier.

**Comment by seladb** [comment]
@dijiang - thanks for the feedback and thanks for using this library!
If you're analyzing HTTP protocol then you probably don't need TCP packet reordering module. If you're interested only in analyzing HTTP headers, than you have HttpLayer who does this for you. If you're interested in parsing the HTTP body as well you can use TCP reassembly module to give you the raw data and parse the rest yourself.
By the way, I have a plan to write an HTTP body parser on-top of TCP reassembly but it'll probably take some time to implement.

**Comment by seladb** [comment]
@topeolufe - thanks for the feedback. It's a good idea to pass all packets (including SYN, ACK, FIN, etc.), I'll make sure to include that. Just a quick question to make sure: by saying "new TCP reassebmly module" you actually mean "new TCP packet reordering module", right?

**Comment by echo-Mike** [comment]
@seladb Hi, i will probably finish my attempt to rework TcpReassembly on this holidays (03/02/18 - 04/02/18)

**Comment by seladb** [comment]
@echo-Mike Thanks! which improvements are you planning to add? and do you plan to do this work on the main branch?

**Comment by echo-Mike** [comment]
Hello @seladb and others.  I might inform You that unfortunately I can not finish the rework in appointed time. But there is a good news too, i have found the way to add something like move semantics to C++98 using constant overhead (via proxy classes). I will add found solution to my fork later today.

**Comment by seladb** [comment]
I'll close this issue now and open a new one for creating a TCP reordering module
