### ISSUE TITLE
TLS fingerprinting example on tailor made packets

### ISSUE THREAD

**Issue by sammasak** [seladb/PcapPlusPlus#825]
I'm having issues with running the TLS fingerprinting example on data that I have generated myself. 

According to wireshark the attached pcap file contains  two tls handshakes (packet 4 and packet 44) but when running the tls fingerprinting example none is found. I have found that it is because when the TLS fingerprinting example looks for a packet of type SSL it fails since the packet type is GenericPayload, and wont parse the packet further. 

Is there anything that I'm missing or are there any workarounds for this?
Is this due to bad packet capture, or is this a PcapPlusPlus related issue?

The pcap file is recorded in wireshark and records data from two vms that use python scripts with sockets to setup tcp/tls communication between each other with self signed certificates. 

Anyway thanks for a great library, I will keep looking for possible workaround or solutions!

[pcap_file.zip](https://github.com/seladb/PcapPlusPlus/files/8176749/pcap_file.zip)

**Comment by egecetin** [comment]
I guess it's because of your ports. 60000 and 60002 are not registered ports for SSL/TLS so the parser chooses  `GenericPayload`. Could you change and test your python script using one of the ports below? If I'm right it should parse

https://github.com/seladb/PcapPlusPlus/blob/fa88a6a428b566972e82ad766ae2a4d2b6a8f7fe/Packet%2B%2B/header/SSLLayer.h#L181-L208

**Comment by sammasak** [comment]
> I guess it's because of your ports. 60000 and 60002 are not registered ports for SSL/TLS so the parser chooses `GenericPayload`. Could you change and test your python script using one of the ports below? If I'm right it should parse
> 
> https://github.com/seladb/PcapPlusPlus/blob/fa88a6a428b566972e82ad766ae2a4d2b6a8f7fe/Packet%2B%2B/header/SSLLayer.h#L181-L208

Yes this solved it! Looking at the other issues it seems that this has been discussed before and that: [#671 ](https://github.com/seladb/PcapPlusPlus/issues/671) would allow for custom ports to be assigned to protocols.  

Thanks for the help, I'm closing the issue!
