### ISSUE TITLE
compile error: src/DpdkDevice.cpp:11:24: fatal error: rte_config.h

### ISSUE THREAD

**Issue by lawtech0902** [seladb/PcapPlusPlus#83]
dpdk version:17.02

**Comment by echo-Mike** [comment]
Hi @lawtech0902 can You provide version of your Unix distributive, g++ compiler and a build log file or copy of the error via pastebin, please.

**Comment by seladb** [comment]
Also, did you follow the configuration instructions listed [here](http://seladb.github.io/PcapPlusPlus-Doc/dpdk-pf_ring.html)?

**Comment by lawtech0902** [comment]
@seladb , thx. I'm sure that I follow the instructions correctly.

**Comment by lawtech0902** [comment]
@echo-Mike @seladb , Thx for your help.

Ubuntu 16.04,  gcc version 5.4.0

fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
==> Building target: Common++
Finished successfully building: Common++.lib
 
Finished successfully building: Common++.debug
 
==> Building target: Packet++
Finished successfully building: Packet++
 
==> Building target: Pcap++
Building file: src/DpdkDevice.cpp
src/DpdkDevice.cpp:11:24: fatal error: rte_config.h: \u6ca1\u6709\u90a3\u4e2a\u6587\u4ef6\u6216\u76ee\u5f55
 #include "rte_config.h"
                        ^
compilation terminated.
Makefile:69: recipe for target 'Obj/DpdkDevice.o' failed
make[1]: *** [Obj/DpdkDevice.o] Error 1
Makefile:76: recipe for target 'libs' failed
make: *** [libs] Error 2

**Comment by seladb** [comment]
Can you please paste the content of the file **mk/PcapPlusPlus.mk** ?
It seems like a problem with the way DPDK path is defined, please take a look at similar problem:
https://github.com/spdk/spdk/issues/5

**Comment by lawtech0902** [comment]
@seladb yes, I found that the **PCAPPP_INCLUDES** dir is **$(RTE_SDK)/build/include**, but there is actually no build folder under RTE_SDK, rte_config.h is in the **/home/root123/dpdk-stable-17.02.1/x86_64-native-linuxapp-gcc/include**.



PCAPPLUSPLUS_HOME := /home/root123/PcapPlusPlus-master
RTE_SDK := /home/root123/dpdk-stable-17.02.1

USE_DPDK := 1


### COMMON ###^M
^M
# includes^M
PCAPPP_INCLUDES := -I$(PCAPPLUSPLUS_HOME)/Dist/header^M
^M
# libs dir^M
PCAPPP_LIBS_DIR := -L$(PCAPPLUSPLUS_HOME)/Dist^M
^M
# libs^M
PCAPPP_LIBS := -lPcap++ -lPacket++ -lCommon++^M
^M
# post build^M
PCAPPP_POST_BUILD :=^M
^M
# build flags^M
PCAPPP_BUILD_FLAGS :=^M
^M

# libs
PCAPPP_LIBS += -lpcap -lpthread


### DPDK ###

# includes
PCAPPP_INCLUDES += -I$(RTE_SDK)/build/include

# libs dir
PCAPPP_LIBS_DIR += -L$(RTE_SDK)/build/lib -L/lib64

#flags
PCAPPP_BUILD_FLAGS += -msse -msse2 -msse3 -Wall

# libs
PCAPPP_LIBS += -Wl,--whole-archive -lrte_pmd_bond -lrte_pmd_vmxnet3_uio -lrte_pmd_virtio -lrte_pmd_enic -lrte_pmd_i40e -lrte_pmd_fm10k -lrte_pmd_ixgbe -lrte_net -lrte_pmd_e1000 -lrte_pmd_ring -lrte_pmd_af_packet -lrte_ethdev -lrte_eal -lrte_mbuf -lrte_mempool -lrte_ring -lrte_kvargs -lrte_hash -lrte_cmdline -lrt -lm -ldl -lpthread -Wl,--no-whole-archive

**Comment by lawtech0902** [comment]
@seladb yes, I found that the PCAPPP_INCLUDES dir is $(RTE_SDK)/build/include, but there is actually no build folder under RTE_SDK, rte_config.h is in the /home/root123/dpdk-stable-17.02.1/x86_64-native-linuxapp-gcc/include.

PCAPPLUSPLUS_HOME := /home/root123/PcapPlusPlus-master
RTE_SDK := /home/root123/dpdk-stable-17.02.1

USE_DPDK := 1

COMMON 
includes
PCAPPP_INCLUDES := -I$(PCAPPLUSPLUS_HOME)/Dist/header
libs dir
PCAPPP_LIBS_DIR := -L$(PCAPPLUSPLUS_HOME)/Dist^M
libs
PCAPPP_LIBS := -lPcap++ -lPacket++ -lCommon++
post build
PCAPPP_POST_BUILD :=
build flags
PCAPPP_BUILD_FLAGS :=
libs
PCAPPP_LIBS += -lpcap -lpthread
DPDK
includes
PCAPPP_INCLUDES += -I$(RTE_SDK)/build/include
libs dir
PCAPPP_LIBS_DIR += -L$(RTE_SDK)/build/lib -L/lib64
#flags
PCAPPP_BUILD_FLAGS += -msse -msse2 -msse3 -Wall
libs
PCAPPP_LIBS += -Wl,--whole-archive -lrte_pmd_bond -lrte_pmd_vmxnet3_uio -lrte_pmd_virtio -lrte_pmd_enic -lrte_pmd_i40e -lrte_pmd_fm10k -lrte_pmd_ixgbe -lrte_net -lrte_pmd_e1000 -lrte_pmd_ring -lrte_pmd_af_packet -lrte_ethdev -lrte_eal -lrte_mbuf -lrte_mempool -lrte_ring -lrte_kvargs -lrte_hash -lrte_cmdline -lrt -lm -ldl -lpthread -Wl,--no-whole-archive

**Comment by lawtech0902** [comment]
@seladb I change the way of compiling DPDK and it finally works. I use `make install T=x86_64-native-linuxapp-gcc` to compile before and now I use `make config T=x86_64-native-linuxapp-gcc make`. I think it is necessary to improve the document to better remind users to use the appropriate compilation of DPDK, so as not to encounter such a situation that I had.
Anyway thank you for your help.

**Comment by echo-Mike** [comment]
Basicaly there is a problem with the way pcpp build system interacts with DPDK distribution.  
The most common and simle way to build DPDK is to use dpdk_folder/usertools/dpdk-setup.sh shell script. It provides a simplest way to build this complex system.  
But current PCPP build system don't support this way. It is only supports the way described in [Compiling the DPDK Target from Source](http://dpdk.org/doc/guides-17.02/linux_gsg/build_dpdk.html) guideline a.e. `make config T=platform_type_string && make` which creates DPDK distribution not inside platform_type_string folder but in DPDK folder itself.  
I mean this way is not most intuitive way to do it. Especially when you need to distribute it in automatic fashion.
I mean this way is not most intuitive way to do it. Especially when you need to destribute it in automatic fassion.

**Comment by seladb** [comment]
@lawtech0902 @echo-Mike - both ways you mention builds DPDK in a folder named by the platform type (e.g x86_64-native-linuxapp-gcc). In this sense DPDK developers maintain backward compatilbilty because in earlier versions of DPDK that was the only option to build DPDK. In later versions they added the option to build with `make config T=platform_type_string && make` which builds DPDK into a `/dpdk_folder/build` directory which is cleaner for my opinion. I can add support for both options but it'll make PcapPlusPlus configuration script more complicated and less easy to understand.
I suggest following @lawtech0902 suggestion and add this comment to the documentation. I'll do that later today.

**Comment by seladb** [comment]
Fixed the documentation: https://github.com/seladb/PcapPlusPlus-Doc/commit/41500457d6daa5bb1ae7f311f55d7554473115cc
