### ISSUE TITLE
ETH_RSS_IPV4？

### ISSUE THREAD

**Issue by maliwen2015** [seladb/PcapPlusPlus#830]
https://github.com/seladb/PcapPlusPlus/blob/d8d702acc99bf8bbf1531f00a3162c6b11a3cd2c/Pcap%2B%2B/src/DpdkDevice.cpp#L1181

This is ETH_RSS_IPV4 or ETH_RSS_FRAG_IPV4?

**Comment by seladb** [comment]
To be honest, I don't remember why I put `ETH_RSS_IPV4` and not `ETH_RSS_FRAG_IPV4`... 😳 
Maybe in previous versions of DPDK `ETH_RSS_FRAG_IPV4` didn't exist?

**Comment by seladb** [comment]
Closing this issue due to lack of responsivenss. Please reopen if relevant
