### ISSUE TITLE
PcapPlusPlus don't support  parser dns answer Address?

### ISSUE THREAD

**Issue by jiangjiongyu** [seladb/PcapPlusPlus#839]
pcpp::DnsResource* answer = dnsLayer->getFirstAnswer();
answer->get?

**Comment by seladb** [comment]
You have [`answer->getData()`](https://pcapplusplus.github.io/api-docs/v21.11/classpcpp_1_1_dns_resource.html#ae1b717cd474c5d401a4a31a69cdd48b9) where you can get the data.

If you know it an IPv4 or IPv6 address you can do:
```cpp
answer->getData().castAs<pcpp::IPv4DnsResourceData>()->getIpAddress(); // For IPv4
answer->getData().castAs<pcpp::IPv6DnsResourceData>()->getIpAddress(); // For IPv6
```

You also can cast to other types described [here](https://pcapplusplus.github.io/api-docs/v21.11/classpcpp_1_1_i_dns_resource_data.html) based on the answer type:
- `pcpp::StringDnsResourceData`
- `pcpp::MxDnsResourceData`
- `pcpp::GenericDnsResourceData`

You can see how to use these APIs in PcapPlusPlus tests:
https://github.com/seladb/PcapPlusPlus/blob/master/Tests/Packet%2B%2BTest/Tests/DnsTests.cpp

**Comment by jiangjiongyu** [comment]
It works!Thanks so much for your answer!
