### ISSUE TITLE
Find a way to add wireshark protocols

### ISSUE THREAD

**Issue by abdolahsa** [seladb/PcapPlusPlus#84]
Wireshark has many protocols (more than 2000) but all of them has been written in c legacy code and are very dirty. If we can find a way to add it's protocols to pcap++ then it will be very rich.
Can you find a way to add it's protocols here? is there an automatic way (using scripts, ...) to add them?

**Comment by seladb** [comment]
Unfortunately the answer is no. Wireshark dissectors (protocol analyzers) are written over the Wireshark SDK/API which is very specific to the way Wireshark works. This is not something that is portable to PcapPlusPlus
