### ISSUE TITLE
TCPReassembly Connection List keeps growing if FIN/RST packets don't arrive.

### ISSUE THREAD

**Issue by leoparente** [seladb/PcapPlusPlus#843]
Investigating the issue https://github.com/ns1labs/pktvisor/issues/226 I noticed that there is no timeout for TCP reassembly connections. Connections still open if no FIN/RST packets arrives on BOTH sides.

I have some questions also.

1. Should we handle timeout on user side? I mean, add a logic to check a period of time for open connection when was the last time that a packet arrived, then close this connection if it is older than a given timeout.
   1.1. If so, closing connections manually like this is expected behavior?

Even so, to achieve that on user side we have to have the last time that a packet arrived for a given connection and I notice that the ConnectionData endTime is not updated to Connection Info List, which is only updated when a new packet arrives or when a connection is closed (removed from the List).

**Comment by seladb** [comment]
Hi @leoparente thanks for reaching out!

Did you look at [`TcpReassemblyConfiguration`](https://github.com/seladb/PcapPlusPlus/blob/ee7658d29d318bf075f4ac9d3cc2cdc58edd91e8/Packet%2B%2B/header/TcpReassembly.h#L180)? It contains a few config params you can pass to TCP reassembly to clean up the stored data. Will any of this work for your use case?

**Comment by leoparente** [comment]
Hello @seladb. Thank you for the reply.

Yes, we have been using that with this setup: `{true, 5, 500, 50}`
We tried to increase `maxNumToClean` to a big number (100000) and set `closedConnectionDelay` to 1 second. But we got the same result.

**Comment by seladb** [comment]
Hi @leoparente I'm sorry for the late response...
I look in the code and you're correct, open connections are not closed automatically. They're closed if a FIN/RST packet is seen. The reason is performance - going over all the connections will impact performance. A way to solve it would be to keep an LRU list in addition to the flow table, and go over it to detect stale connections.
As you mentioned, what you can do is go over all the open connections and close the ones that are stale. I believe `endTime` is updated on every packet so you should be able to compare the time now with `endTime` and determine if a connection should be closed.
Please let me know if I'm missing anything

**Comment by leoparente** [comment]
Hello @seladb . 
`endTime` is updated every packet. however it seems that it is not updated to `ConnectionInfoList`.
If i'm right, the `ConnectionInfoList` is only updated when a new connection arrives ([TcpReassembly:L131](https://github.com/seladb/PcapPlusPlus/blob/d8d702acc99bf8bbf1531f00a3162c6b11a3cd2c/Packet%2B%2B/src/TcpReassembly.cpp#L131)) and not when every packet arrives.

**Comment by seladb** [comment]
You're right @leoparente ! I think it's not a huge change. Would you consider implementing it and open a PR?

**Comment by leoparente** [comment]
@seladb thanks for landing my PR! I would like to check your opinion about the code on our side (pktvisor) in this PR:
[pktvisor tcp timeout #244](https://github.com/ns1labs/pktvisor/pull/244/files#diff-4916a5616cbba75fbd9d5b976273f3cf7534622d5359879c538a793f4af54482)

The idea is to not do checking for staled connections every new arrived packet to not slow things down. I also don't think that I need to spend time checking if the connection is open or not (performing a `map::find` for every item in the map) because my `TcpReassemblyConfiguration` I've set that closed connections will be removed after 1 second and I'm doing checking for packets older then 10 seconds. Also calling `closeConnection` in already closed packets does not seems to be a problem.

You can drop your opinion there. I will close this issue. Many thanks!
