### ISSUE TITLE
False negative results in tcpreassembly testing.

### ISSUE THREAD

**Issue by Thell** [seladb/PcapPlusPlus#845]
Hi! I didn't find this reported already so I thought I'd report it. First, I was doing some setup for custom tcpreassembly handling and before making any changes I decided to run the tests to ensure I didn't mess things up... I got failures on tcpreassembly. Knowing that everything was default and even though there are a ton of warnings I had no errors on any of the builds so I grabbed the prebuilt binaries and modified the tcpreassembly tests to use them instead of my newly built ones... still got failures. This made me scratch my head so I read the output a bit closer and noted the location of the outputs being tested and did a directory compare (just on the sanity test since that is what I though I was losing) and guess what... no differences.

![Screenshot 2022-03-19 014715](https://user-images.githubusercontent.com/2185020/159110805-10bced9d-9863-4566-965a-e96f52187c8b.png)
![Screenshot 2022-03-19 014624](https://user-images.githubusercontent.com/2185020/159110806-0d123d5f-0cdd-432a-9a61-d075f3a968eb.png)

This was on Windows 10 19044.1586 using VS2019 (up to date) run in an elevated command prompt console with a venv using VSStudio's installed `python` which is python 3.9.2. If the tests are all passing for others I'll gladly look into the other results more closely as well, but if it is a known issue or is reproducible simply by building and testing in a similar environment then I'll just move along into learning more about the projects setup and "how things work". :)

**Comment by seladb** [comment]
Hmm I can't think of a reason why this test would fail, it runs in the CI all the time including in Windows and VS 2019, here is an example: https://github.com/seladb/PcapPlusPlus/runs/5614062394?check_suite_focus=true#step:15:60.

Can you please run a diff on these files and paste the result?

**Comment by Thell** [comment]
I couldn't think of a reason either since the CI environment matched everything except the python version but then it hit me... what could make file compares on windows say things are the same when they aren't...

drumroll please... line endings... and sure enough a `diff a b | cat -e -` shows a difference (not for the whole file but for parts of it)

Someday (please!), we will see standardized line endings.

**Comment by seladb** [comment]
That's very interesting, thank you for checking!
I'm still curious how the Windows CI passes... What's different between the Windows VM running in the CI and your Windows machine? 🤔

**Comment by Thell** [comment]
appveyor vm default => `git config --global core.autocrlf input`
This is neither the git default (`false`) nor git on windows default (`true`). Again, `.gitattributes` would have stopped this from happening.

**Comment by seladb** [comment]
oh I see. We actually have a pre-commit rule that is not enabled yet and should take care of that: https://github.com/seladb/PcapPlusPlus/blob/ebd6a77ffbfb6b76257008ee14b55ddf30749fb7/.pre-commit-config.yaml#L10

But maybe `.gitattributes` can also be a good idea...

**Comment by seladb** [comment]
@Thell should we close this issue or is there a reason to keep it open?
The pre-commit rule is a known issue and we'll take care of it soon.

**Comment by Thell** [comment]
Yeah, closing is fine. The pre-commit rule isn't the issue here, but rather the mismatch of the users (my) global config on windows not matching what the CI uses. Its the check out, not the check in, that is what would be resolved by having a `.gitattributes` in the repo.
