### ISSUE TITLE
app says RSS hash function not supported even though getrsshashfunction method gives that it is present

### ISSUE THREAD

**Issue by AlienX2001** [seladb/PcapPlusPlus#849]
Hey, So I was working with PcapPlusPlys v21.05

And whats happening is, i got an error that rss hash function 0x41 was not supported, I then read about the documentation on the classes and all of PCPP and then basically edited the dpdkl2fwd sample application to also print out the getrsshashfunction method which would give me the rss hash function supported by my NIC, which is intel XL710
![image](https://user-images.githubusercontent.com/64488123/160036156-b5b02a3d-d846-4be9-ae47-92e9c7cd7b63.png)
Now as you can see it says 0x41 is not supported and the supported are 0x1fbd, so i referred to the documentation and it seems that function 0x40, which is for RSS IPv6 is not supported, so now what I did was I changes the dpdkDevices.h in the PcPP/headers and then in line 280 i replaced `uint64_t rssHashFunction = RSS_IPV4 | RSS_IPV6` with `uint64_t rssHashFunction = RSS_IPV4` and recompiled PcPP.

According to me what this should do is, it should invoke the hashfunction 0x1 instead of 0x41, and now since our NIC supports 0x1fbd so it the function 0x1 also comes under 0x1fbd, but apparently even then we are getting this error
![image](https://user-images.githubusercontent.com/64488123/160036423-e8668ef2-ad10-4efa-ac94-d1b555924906.png)

If anyone could help with it, it would be great

**Comment by seladb** [comment]
PcapPlusPlus uses DPDK to determine whether RSS functions are supported:

Here is where this check happens: https://github.com/seladb/PcapPlusPlus/blob/master/Pcap%2B%2B/src/DpdkDevice.cpp#L1314-L1319

And here is the conversion between PcapPlusPlus RSS hash macros to DPDK hash macros: https://github.com/seladb/PcapPlusPlus/blob/0994212b0fe59f60b0d07c06289cfa172c5237bb/Pcap%2B%2B/src/DpdkDevice.cpp#L1240

Maybe you can debug this on your system, see which values are extracted from `rte_eth_dev_info_get()` and compare them to the value coming form PcapPlusPlus?

**Comment by AlienX2001** [comment]
![image](https://user-images.githubusercontent.com/64488123/160093961-046b2e7e-f6d8-4243-b31a-c02dfd63a73f.png)
in here the `rte_eth_dev_info_get` takes a m_Id parameter doing which resulted in this
![image](https://user-images.githubusercontent.com/64488123/160094572-4176f284-9c38-4eab-a100-61a935a0533b.png)
meaning this m_Id is a private variable so cant view it directly, and I dont seem to find any getter function of this variable

**Comment by AlienX2001** [comment]
We recompiled pcpp with only ipv6 this time
![image](https://user-images.githubusercontent.com/64488123/160295246-7d762833-1a87-424b-bc1a-fa05e4645cae.png)

and this is what we are getting, now we have no clue why ipv6 is not working

**Comment by seladb** [comment]
hi @AlienX2001 !
I printed all the supported RSS functions based on the value you got from DPDK (`0x7ef8`) and I don't see `RSS_IPV4` or `RSS_IPV6` in this list:

```shell
DPDK supported value: 0x7rf8
PcapPlusPlus supported value: 0x1fbe

ETH_RSS_FRAG_IPV4
ETH_RSS_NONFRAG_IPV4_TCP
ETH_RSS_NONFRAG_IPV4_UDP
ETH_RSS_NONFRAG_IPV4_SCTP
ETH_RSS_NONFRAG_IPV4_OTHER
ETH_RSS_FRAG_IPV6
ETH_RSS_NONFRAG_IPV6_TCP
ETH_RSS_NONFRAG_IPV6_UDP
ETH_RSS_NONFRAG_IPV6_SCTP
ETH_RSS_NONFRAG_IPV6_OTHER
ETH_RSS_L2_PAYLOAD
```

Are you sure you NIC supports one of them?

**Comment by AlienX2001** [comment]
Hey, thanks for the prompt response
1st, since the DPDK supported hash function obtained here is 7ef8 and I also tried to get the hash using testpmd and got 7ef8, following this SO link https://stackoverflow.com/questions/42342723/how-to-set-up-rss-hash-fuction-in-xl710-to-receive-ipv4-flow-type/42344025 and according to this my NIC may not support `ETH_RSS_IPV4`  RSS function, so to circumvent it what I did was I simply hardcoded 7ef8 instead of `RSS_IPV4 | RSS_IPV6` for checking purposes in `uint64_t rssHashFunction` and this is what happened
![image](https://user-images.githubusercontent.com/64488123/160361052-520e5a67-cdd2-4164-b02a-0289ec78d0b3.png)

Now I am completely baffled as to why this is not working, I mean at this moment it doesnt even matter what mappings are followed, I simply hardcoded the rss hash masks just to check if it should work, and its not working

**Comment by seladb** [comment]
Let me walk you through the code, maybe it'll clear a few things out:
- When you call [`getSupportedRssHashFunctions()`](https://github.com/seladb/PcapPlusPlus/blob/0994212b0fe59f60b0d07c06289cfa172c5237bb/Pcap%2B%2B/src/DpdkDevice.cpp#L1322) it first fetches the supported RSS functions from DPDK using [`rte_eth_dev_info_get()`](https://github.com/seladb/PcapPlusPlus/blob/0994212b0fe59f60b0d07c06289cfa172c5237bb/Pcap%2B%2B/src/DpdkDevice.cpp#L1325). In your case `devInfo.flow_type_rss_offloads` equals to `0x7ef8`
- Now this value is converted from DPDK to PcapPlusPlus using [`convertDpdkRssHfToRssHf()`](https://github.com/seladb/PcapPlusPlus/blob/0994212b0fe59f60b0d07c06289cfa172c5237bb/Pcap%2B%2B/src/DpdkDevice.cpp#L1240). This method goes over the bits in `0x7ef8`, matches them with DPDK RSS consts and converts them to the corresponding values in PcapPlusPlus. In your case the result of this method is `0x1fbd`
- `0x7ef8` and `0x1fbd` are equivalent - the first is in "DPDK terminology" while the second is in "PcapPlusPlus terminology"
- If you want to force RSS functions that aren't necessarily supported you can comment out [`rte_eth_dev_info_get(m_Id, &devInfo)`](https://github.com/seladb/PcapPlusPlus/blob/0994212b0fe59f60b0d07c06289cfa172c5237bb/Pcap%2B%2B/src/DpdkDevice.cpp#L1325) and just call `convertDpdkRssHfToRssHf()` with whatever value you want. But don't expect it to work if your NIC doesn't support those RSS functions

I hope this is a bit more clear, please let me know if you have any questions

**Comment by AlienX2001** [comment]
Ok, I see,
So now what we attempted is we hardcoded the RSS function in pcapplusplus convention thereby hardcoding 0x1fbd
![image](https://user-images.githubusercontent.com/64488123/160571984-c5e2f774-36b3-40ad-8f01-02642f4ebe40.png)

and now it says unsupported 0x1fbd
![image](https://user-images.githubusercontent.com/64488123/160572418-3ff1f9d7-55d7-400b-8e46-742d62db862a.png)

I have passed 0x1fbd because I believe that the rsshashfunction variable is taking masks in pcapplusplus convention and not dpdk convention, since it was basically using those variables `RSS_IPV4, RSS_IPV6` which had values in pcapplusplus convention. Also 0x1fbd mask has to be compatible on our NIC, since thats what a normal call to getRssHashFunction() is giving us.

**Comment by AlienX2001** [comment]
Sure, its basically your dpdkl2fwd code, only that i commented most of them code, and simply printed out the rss hashes
```C++
#include <vector>
#include <unistd.h>
#include <sstream>
#include "SystemUtils.h"
#include "DpdkDeviceList.h"
#include "TablePrinter.h"
#include "rte_pci.h"
#include "rte_config.h"
#include "rte_ethdev.h"
#include "rte_errno.h"
#include "rte_malloc.h"
#include "rte_cycles.h"
#include "WorkerThread.h"


#define MBUF_POOL_SIZE 16*1024-1
#define DEVICE_ID_1 0
#define DEVICE_ID_2 1

#define COLLECT_STATS_EVERY_SEC 2


// Keep running flag
bool keepRunning = true;

void onApplicationInterrupted(void* cookie)
{
        keepRunning = false;
        printf("\nShutting down...\n");
}


void printStats(pcpp::DpdkDevice* rxDevice, pcpp::DpdkDevice* txDevice)
{
        pcpp::DpdkDevice::DpdkDeviceStats rxStats;
        pcpp::DpdkDevice::DpdkDeviceStats txStats;
        rxDevice->getStatistics(rxStats);
        txDevice->getStatistics(txStats);

        std::vector<std::string> columnNames;
        columnNames.push_back(" ");
        columnNames.push_back("Total Packets");
        columnNames.push_back("Packets/sec");
        columnNames.push_back("Bytes");
        columnNames.push_back("Bits/sec");

        std::vector<int> columnLengths;
        columnLengths.push_back(10);
        columnLengths.push_back(15);
        columnLengths.push_back(15);
        columnLengths.push_back(15);
        columnLengths.push_back(15);

        pcpp::TablePrinter printer(columnNames, columnLengths);

        std::stringstream totalRx;
        totalRx << "rx" << "|" << rxStats.aggregatedRxStats.packets << "|" << rxStats.aggregatedRxStats.packetsPerSec << "|" << rxStats.aggregatedRxStats.bytes << "|" << rxStats.aggregatedRxStats.bytesPerSec*8;
        printer.printRow(totalRx.str(), '|');

        std::stringstream totalTx;
        totalTx << "tx" << "|" << txStats.aggregatedTxStats.packets << "|" << txStats.aggregatedTxStats.packetsPerSec << "|" << txStats.aggregatedTxStats.bytes << "|" << txStats.aggregatedTxStats.bytesPerSec*8;
        printer.printRow(totalTx.str(), '|');
}


int main(int argc, char* argv[])
{
        // Register the on app close event handler
        pcpp::ApplicationEventHandler::getInstance().onApplicationInterrupted(onApplicationInterrupted, NULL);

        // Initialize DPDK
        pcpp::CoreMask coreMaskToUse = pcpp::getCoreMaskForAllMachineCores();
        pcpp::DpdkDeviceList::initDpdk(coreMaskToUse, MBUF_POOL_SIZE);

        // Find DPDK devices
        pcpp::DpdkDevice* device1 = pcpp::DpdkDeviceList::getInstance().getDeviceByPort(DEVICE_ID_1);
        if (device1 == NULL)
        {
                printf("Cannot find device1 with port '%d'\n", DEVICE_ID_1);
        return 1;
        }

        pcpp::DpdkDevice* device2 = pcpp::DpdkDeviceList::getInstance().getDeviceByPort(DEVICE_ID_2);
        if (device2 == NULL)
        {
                printf("Cannot find device2 with port '%d'\n", DEVICE_ID_2);
        return 1;
        }
        rte_eth_dev_info devInfo;
        rte_eth_dev_info_get(device1->getDeviceId(), &devInfo);
        printf("RSS: from dpdk : %lx\n",devInfo.flow_type_rss_offloads);
        printf("RSS: get supported rss hashfunction:  %lx\n",device1->getSupportedRssHashFunctions());
        // Open DPDK devices
        if (!device1->openMultiQueues(1, 1))
        {
                printf("Couldn't open device1 #%d, PMD '%s'\n", device1->getDeviceId(), device1->getPMDName().c_str());
        return 1;
        }

        if (!device2->openMultiQueues(1, 1))
        {
                printf("Couldn't open device2 #%d, PMD '%s'\n", device2->getDeviceId(), device2->getPMDName().c_str());
                return 1;
        }
        //rte_eth_dev_info devInfo;
        //printf("RSS: from dpdk : %d",rte_eth_dev_info_get(device1->getDeviceId(), &devInfo));
        //printf("RSS: get supported rss hashfunction:  %lx",device1->getSupportedRssHashFunctions());

        /*
        // Create worker threads
        std::vector<pcpp::DpdkWorkerThread*> workers;
        workers.push_back(new L2FwdWorkerThread(device1, device2));
        workers.push_back(new L2FwdWorkerThread(device2, device1));

        // Create core mask - use core 1 and 2 for the two threads
        int workersCoreMask = 0;
        for (int i = 1; i <= 2; i++)
        {
                workersCoreMask = workersCoreMask | (1 << i);
        }

        // Start capture in async mode
        if (!pcpp::DpdkDeviceList::getInstance().startDpdkWorkerThreads(workersCoreMask, workers))
        {
                printf("Couldn't start worker threads");
                return 1;
        }

        uint64_t counter = 0;
        int statsCounter = 1;

        // Keep running while flag is on
        while (keepRunning)
        {
                // Sleep for 1 second
                sleep(1);

                // Print stats every COLLECT_STATS_EVERY_SEC seconds
                if (counter % COLLECT_STATS_EVERY_SEC == 0)
                {
                        // Clear screen and move to top left
                        const char clr[] = { 27, '[', '2', 'J', '\0' };
                const char topLeft[] = { 27, '[', '1', ';', '1', 'H','\0' };
                printf("%s%s", clr, topLeft);

                        printf("\n\nStats #%d\n", statsCounter++);
                        printf("==========\n\n");

                        // Print stats of traffic going from Device1 to Device2
                        printf("\nDevice1->Device2 stats:\n\n");
                        printStats(device1, device2);

                        // Print stats of traffic going from Device2 to Device1
                        printf("\nDevice2->Device1 stats:\n\n");
                        printStats(device2, device1);
                }
                counter++;
        }

        // Stop worker threads
        pcpp::DpdkDeviceList::getInstance().stopDpdkWorkerThreads();

        */
        // Exit app with normal exit code
        return 0;
}
```

**Comment by AlienX2001** [comment]
To follow up this, we tried to debug further and put some printf's in the `DpdkDevice::isDeviceSupportRssHashFunction` function, since we figured out that this function was giving false instead of true.
like this
```C++
bool DpdkDevice::isDeviceSupportRssHashFunction(uint64_t rssHFMask) const
{
        uint64_t dpdkRssHF = convertRssHfToDpdkRssHf(rssHFMask);
        printf("rssHFMask: %lx\n",rssHFMask);
        printf("dpdkRssHF: %lx\n",dpdkRssHF);
        rte_eth_dev_info devInfo;
        rte_eth_dev_info_get(m_Id, &devInfo);
        printf("devInfo.flow_type_rss_offloads: %lx\n",devInfo.flow_type_rss_offloads);

        return ((devInfo.flow_type_rss_offloads & dpdkRssHF) == dpdkRssHF);
}
```

and now it's giving the following output
![image](https://user-images.githubusercontent.com/64488123/160630392-99da2c30-b79d-427d-babd-7ac8efc124a5.png)

**Comment by seladb** [comment]
Maybe I found the bug! I think it was fixed in this commit: https://github.com/seladb/PcapPlusPlus/commit/5fd8db1dae9fd8395395e82a1d19017d60a0e632
I realized that the value you see is `1fbd` whether the value I see is `1fbe` and then I went through the code and saw this fix. Unfortunately there is not yet a release with this fix (it was just committed a few weeks back), but can you try again with the latest code from `master`?

**Comment by AlienX2001** [comment]
Thanks for your support.
The changes made in this commit worked for us, 1 more change we had to make was to change line number 281 in Pcap++/header/DpdkDevice.h from `uint64_t rssHashFunction = RSS_IPV4 | RSS_IPV6,` to `uint64_t rssHashFunction = RSS_NONFRAG_IPV4_UDP | RSS_NONFRAG_IPV4_TCP | RSS_FRAG_IPV4 | RSS_NONFRAG_IPV4_OTHER | RSS_NONFRAG_IPV4_SCTP | RSS_FRAG_IPV6 |  RSS_NONFRAG_IPV6_OTHER | RSS_NONFRAG_IPV6_SCTP  | RSS_NONFRAG_IPV6_UDP |  RSS_NONFRAG_IPV6_TCP` since PMD net_i40e (intel xl710) doesnt support `RSS_IPV4 | RSS_IPV6` these 2 RSS functions hence, with the help of this link https://stackoverflow.com/questions/42342723/how-to-set-up-rss-hash-fuction-in-xl710-to-receive-ipv4-flow-type/42344025 we figured out `RSS_NONFRAG_IPV4_UDP | RSS_NONFRAG_IPV4_TCP | RSS_FRAG_IPV4 | RSS_NONFRAG_IPV4_OTHER | RSS_NONFRAG_IPV4_SCTP | RSS_FRAG_IPV6 |  RSS_NONFRAG_IPV6_OTHER | RSS_NONFRAG_IPV6_SCTP  | RSS_NONFRAG_IPV6_UDP |  RSS_NONFRAG_IPV6_TCP` these functions should work, it may not give the optimum performance, according to this SO answer, but atleast it's getting the work done.

So if you could commit these changes on these lines of DpdkDevice.h, would be great,

Thanks Again

**Comment by AlienX2001** [comment]
And hey, these changes in the flag are only for net_i40e PMD, I cant say about other NIC's since I have only worked with xl710

**Comment by seladb** [comment]
`RSS_IPV4 | RSS_IPV6` is just the default value that works for most NICs, but you can create your own instance of `DpdkDeviceConfiguration`, initialize it with the value you need and then give it to `DpdkDevice::openMultiQueues()`

**Comment by seladb** [comment]
Please let me know if we can close this issue

**Comment by AlienX2001** [comment]
Yes, sure, thanks for the help, we have resolved any doubts for pcapplusplus
