### ISSUE TITLE
High CPU on windows machines

### ISSUE THREAD

**Issue by yosizelensky** [seladb/PcapPlusPlus#85]
There is a problem on windows machines that causes high CPU usage.

The bug is that you pass `-1` ([here](https://github.com/seladb/PcapPlusPlus/blob/4b5e72ed882d76b804ccbd8c6b6e2800f100662e/Pcap%2B%2B/src/PcapLiveDevice.cpp#L37)) to pcap_set_timeout ([here](https://github.com/seladb/PcapPlusPlus/blob/master/Pcap%2B%2B/src/PcapLiveDevice.cpp#L234)) and that causes winpcap to not do context switches when you start the capture.

The fix should be to use a proper timeout (like 1000 ms).
I don't know what the timeout should be on Mac but I think it should also be 1000 ms.

Steps to reproduce:

1. Clone this repo on a windows machine
2. Build the PcapPlusPlus.sln and the PcapPlusPlus-Examples.sln
3. Run the DnsSpoofing.exe example
4. Observe the high CPU (25% in a 4 cores machine, meaning 1 core is at 100%) 

Image from Task Manager:
![image](https://user-images.githubusercontent.com/5243906/34820048-2bd60384-f6c8-11e7-8fc2-d78d5480d1a6.png)

**Comment by seladb** [comment]
This high CPU load is on purpose - please see my comment on your PR #86
