### ISSUE TITLE
Cant run the DpdkExample-FilterTraffic

### ISSUE THREAD

**Issue by AlienX2001** [seladb/PcapPlusPlus#869]
Hey, we arent able to run the DpdkExample-Filter for some reason.
We are able to run other dpdk applications like the DpdkBridge app and other dpdk example apps, but not this Example app.
We added a few debug print statements and the output is as follows
![image](https://user-images.githubusercontent.com/64488123/164946935-90c8d8d1-a8ed-4313-a1ec-1c39f7bc42f1.png)
 We tried reducing the mbuf by reducing 'DEFAULT_MBUF_POOL_SIZE' but still we still are getting this error.

**Comment by seladb** [comment]
It looks like it cannot allocate mbufs: https://github.com/DPDK/dpdk/blob/main/drivers/net/i40e/i40e_rxtx.c#L2847-L2850
Maybe you ran out of memory or didn't configure DPDK correctly?

**Comment by AlienX2001** [comment]
We do have a lot of hugepages left
![image](https://user-images.githubusercontent.com/64488123/165047438-dbf6badf-0b55-4b6b-8b07-f3f6b1bccf22.png)

And the dpdkbridge example app is working fine too, other dpdk based example apps from the dpdk repository are also working

**Comment by seladb** [comment]
It won't be easy for me to figure out the reason, you probably need to debug it yourself and find out why mbufs are not released...

**Comment by AlienX2001** [comment]
https://github.com/seladb/PcapPlusPlus/blob/b6c56a3a087cb16215703ba99bc945669532ec11/Pcap%2B%2B/src/DpdkDevice.cpp#L368

I think this is where it is failing, but why is it working on other programs then

**Comment by seladb** [comment]
It looks like DPDK cannot initialize the device because there are not enough mbufs. The question is why there are not enough mbufs...

**Comment by AlienX2001** [comment]
No idea, other example apps just start fine, we even increased the hugepages to 16GB, but still the same error

**Comment by seladb** [comment]
I tried to check why [`rte_mbuf_raw_alloc()`](https://github.com/DPDK/dpdk/blob/main/lib/mbuf/rte_mbuf.h#L563-L564) might return `NULL` and it only happens if `rte_mempool_get()` failed, which means a mbuf cannot be allocated from the mempool. Maybe something about allocating the mempool?
The best way to debug is to look into the DPDK code and understand what is wrong - either by using a debugger or by adding prints in DPDK code...
