### ISSUE TITLE
Inclusion pcapplusplus in project via CMake.

### ISSUE THREAD

**Issue by gleb-kun** [seladb/PcapPlusPlus#874]
Hello! I'm sorry if my question is stupid, but I can't figure it out.

I installed pcapplusplus on Ubuntu (Downloaded package from here: https://github.com/seladb/PcapPlusPlus/releases/tag/v21.11). The example that was in the archive compiles and works, everything is fine with it! But when I try to include the library in my project using CMake nothing works.

I write a line in CMakeLists.txt file:
```
include_directories("/usr/local/include/pcapplusplus")
```
After that, the header files are connected to the project. However, the project does not compile, various errors appear depending on the functions that I use. Most likely the linker does not see the files: libCommon++.a, libPacket++.a, and libPcap++.a. 
I tried to connect them like this:
```
target_link_libraries(${PROJECT_NAME} libCommon++.a libPacket++.a libPcap++.a)
```
But it did not help.
Tried this:
```
find_package(pcapplusplus REQUIRED)
include_directories(${PCAPPLUSPLUS_INCLUDE_DIRS})
```
This didn't help either.

In fact, other people have already encountered such a problem, for example, netleap tom wrote about this on the StackOverflow. https://stackoverflow.com/questions/48165990/cmake-linking-against-static-libraries-do-you-have-to-tell-cmake-where-to-look
However, no one there suggested a solution to him. I hope someone will tell me what to do. 🥺🙏

Thanks in advance!

**Comment by gleb-kun** [comment]
For example, in the general case, I have similar errors:

```
/usr/bin/ld: CMakeFiles/test.dir/main.cpp.o: in function `main':
main.cpp:(.text.startup+0x5c): undefined reference to `pcpp::IFileReaderDevice::IFileReaderDevice(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: main.cpp:(.text.startup+0x63): undefined reference to `vtable for pcpp::PcapFileReaderDevice'
/usr/bin/ld: main.cpp:(.text.startup+0xb5): undefined reference to `pcpp::IFileDevice::~IFileDevice()'
/usr/bin/ld: CMakeFiles/test.dir/main.cpp.o:(.data.rel.ro._ZTIN4pcpp17IFileReaderDeviceE[_ZTIN4pcpp17IFileReaderDeviceE]+0x10): undefined reference to `typeinfo for pcpp::IFileDevice'
/usr/bin/ld: CMakeFiles/test.dir/main.cpp.o:(.data.rel.ro._ZTVN4pcpp17IFileReaderDeviceE[_ZTVN4pcpp17IFileReaderDeviceE]+0x28): undefined reference to `pcpp::IFileDevice::close()'
/usr/bin/ld: CMakeFiles/test.dir/main.cpp.o:(.data.rel.ro._ZTVN4pcpp17IFileReaderDeviceE[_ZTVN4pcpp17IFileReaderDeviceE]+0x38): undefined reference to `pcpp::IPcapDevice::setFilter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/bin/ld: CMakeFiles/test.dir/main.cpp.o:(.data.rel.ro._ZTVN4pcpp17IFileReaderDeviceE[_ZTVN4pcpp17IFileReaderDeviceE]+0x40): undefined reference to `pcpp::IPcapDevice::clearFilter()'
/usr/bin/ld: CMakeFiles/test.dir/main.cpp.o:(.data.rel.ro._ZTVN4pcpp17IFileReaderDeviceE[_ZTVN4pcpp17IFileReaderDeviceE]+0x78): undefined reference to `non-virtual thunk to pcpp::IPcapDevice::setFilter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/bin/ld: CMakeFiles/test.dir/main.cpp.o:(.data.rel.ro._ZTVN4pcpp17IFileReaderDeviceE[_ZTVN4pcpp17IFileReaderDeviceE]+0x80): undefined reference to `non-virtual thunk to pcpp::IPcapDevice::clearFilter()'
```

**Comment by gleb-kun** [comment]
I did it. It turned out that I made a very stupid mistake. A little later I will make a Hello World using CMake and post a link here so that newbies like me do not get into awkward situations. 😅

**Comment by gleb-kun** [comment]
https://github.com/gleb-kun/pcappp_hw

**Comment by seladb** [comment]
@gleb-kun I'm sorry for my slow response, I'm glad to see you figured it out yourself!
