### ISSUE TITLE
pcapng damaged files

### ISSUE THREAD

**Issue by Beatle95** [seladb/PcapPlusPlus#879]
Hello, I have recently discovered, that LightPcapNg (that used as 3d party dependency for PcapPlusPlus) does not support truncated or damaged files. I was implemented that support by using more clever system of return statuses. I can improve it and make a pull request. Does this feature required for PcapPlusPlus?

**Comment by seladb** [comment]
Yea sure @Beatle95 , that would be great!
What do you mean by damaged files and which kind of support are you planning to add?

**Comment by seladb** [comment]
Sure, sounds good! Please submit a PR when you have one

**Comment by seladb** [comment]
Hi @Beatle95 ! Are you still planning to open a PR for this issue?

**Comment by Beatle95** [comment]
Hi, I have recently got big new project on my main work, so I don't have much time on this in the nearest time(

**Comment by seladb** [comment]
@Beatle95 no worries at all! Should we keep this issue open until you have time to work on it or should we close it for now?

**Comment by Beatle95** [comment]
I think it is better to close it for now.

**Comment by seladb** [comment]
Sure I'll close it. Please feel free to reopen whenever you have time to work on it
