### ISSUE TITLE
linker error

### ISSUE THREAD

**Issue by xxhenglyxx** [seladb/PcapPlusPlus#88]
Platform: Macosx - High Sierra

First time using this library, I cloned the repository and successfully built it. I am trying to test if it works by copying and running the reading pcap example from the documentation. Here is how i compile and build it

    g++ -Iinclude -c main.cpp --std=c++14
    g++ main.o lib/libCommon++.a lib/libPacket++.a lib/libPcap++.a

And I used the pcaps that was being captured by using wireshark and export it as .pcap file, changed the file name and run it, and this is the output i got:

![screen shot 2018-02-07 at 11 39 40 pm](https://user-images.githubusercontent.com/28291947/35928636-36e3e6a8-0c60-11e8-8049-da2330f673d9.png)

**Comment by echo-Mike** [comment]
@xxhenglyxx You need to install libpcap to your PC. Please refer to this guide(MacOS section):
http://seladb.github.io/PcapPlusPlus-Doc/download.html

**Comment by xxhenglyxx** [comment]
@echo-Mike I already have libpcap installed from brew before installing PcapPlusPlus, and I did followed the instruction from the page you refer me to, but still did not work.

**Comment by seladb** [comment]
Hi @xxhenglyxx thanks for using PcapPlusPlus. Regarding your problem:

- You said you successfully compiled the library, which means you also compiled the examples provided with the library. Did I get this right? Are the examples working?
- Did you install Xcode command line tools (by running `xcode-select --install`)?
- Please try to remove the `--std=c++14` and see if it's working

**Comment by seladb** [comment]
@xxhenglyxx did you have a chance to go over the items mentioned above?

**Comment by xxhenglyxx** [comment]
@seladb sorry for the late replies. I compiled it successfully but I did not compiled the example provided with the library. I already install the Xcode command line tools, removing --std=c++14 did not help also.

**Comment by xxhenglyxx** [comment]
I went to look at the Tests folder and ran the Packet++Test, the result was only 3 pass and the rest got failed, why is like that ? The 3 that was passed is EthPacketCreation, Ipv4PacketCreation, InsertDataToPacket.
And this is the Pcap++Test
![screen shot 2018-02-10 at 3 11 39 pm](https://user-images.githubusercontent.com/28291947/36060101-cb04486c-0e74-11e8-8e6e-a827a74619c5.png)

**Comment by seladb** [comment]
@xxhenglyxx you should run it from Packet++Test folder, meaning:

```
cd /<your_pcapplusplus_folder>/Tests/Packet++Test
Bin/Packet++Test
```

Same for Pcap++Test:

```
cd /<your_pcapplusplus_folder>/Tests/Pcap++Test
sudo Bin/Pcap++Test -i <interface_ip>
```

**Comment by xxhenglyxx** [comment]
@seladb Yes I did run exactly like that. I feel like I miss something so that is why it wont work, is there anything I should have beside the thing inside the documentation ?

**Comment by seladb** [comment]
have you run the `configure-mac_os_x.sh` script?

I'd advise to to start fresh - clone the library, run the configuration script, run the make command and then try to run the unit-tests.
If possible, it'd be great if you can attach the output to this ticket

**Comment by seladb** [comment]
Hi, any news on that?

**Comment by xxhenglyxx** [comment]
@seladb Yes so sorry for the late reply. I did run the ``configure-mac_os_x.sh`` script and the script ran successfully.

**Comment by xxhenglyxx** [comment]
running ``make all`` this time throws me these errors:
![screen shot 2018-02-19 at 9 35 09 pm](https://user-images.githubusercontent.com/28291947/36382825-e5181cca-15bc-11e8-8364-3a13f6954ab5.png)

**Comment by seladb** [comment]
@xxhenglyxx you shouldn't run `configure-linux.sh --use-immediate-mode` since you're on a Mac. You should run only `configure-mac_os_x.sh`. If you want to use immediate mode you can run: `configure-mac_os_x.sh --use-immediate-mode`.
Please let me know if it solves these errors

**Comment by xxhenglyxx** [comment]
It successfully build but here are the test results:
![screen shot 2018-02-21 at 11 05 38 pm](https://user-images.githubusercontent.com/28291947/36490810-c3ca13de-175b-11e8-8b6a-0caad0ecd147.png)
![screen shot 2018-02-21 at 11 05 28 pm](https://user-images.githubusercontent.com/28291947/36490811-c439907e-175b-11e8-92eb-8ec8b8c094df.png)
![screen shot 2018-02-21 at 11 05 17 pm](https://user-images.githubusercontent.com/28291947/36490812-c46f07c2-175b-11e8-8455-0800204863b2.png)

**Comment by seladb** [comment]
You should run the unit-test from its own directory:
```
cd <pcapplusplus_home>/Tests/Packet++Test
Bin/Packet++Test

cd <pcapplusplus_home>/Tests/Pcap++Test
sudo Bin/Pcap++Test -i <your_ip_address>
```

**Comment by xxhenglyxx** [comment]
Yes I did run it from its own unit-test directory. After I cloned it at some location, then cd into it, follow all the installation steps, then run unit test withnin it.

**Comment by seladb** [comment]
The unit-test applications fail to read the input files for some reason, with the info I have it's hard for me to say why.
One more thing I can suggest is to record everything you do and send me the output as a text file, not as an image. Please record everything from cloning the project to running the unit-tests

**Comment by xxhenglyxx** [comment]
Ok I will do that and send it to you.

**Comment by xxhenglyxx** [comment]
Here is the file: [output.txt](https://github.com/seladb/PcapPlusPlus/files/1765589/output.txt)

**Comment by seladb** [comment]
Thanks! 
# I've identified the problem:
You're running:
```
cd Tests/Packet++Test/Bin
./Packet++Test
```

But you **should** run:
```
cd Tests/Packet++Test
Bin/Packet++Test
```

Same for Pcap++Test, you're running:
```
cd Tests/Pcap++Test/Bin
./Pcap++Test
```

but you **should** run:
```
cd Tests/Pcap++Test
sudo Bin/Pcap++Test -i <your_ip_address>
```

Please let me know if it solves the problem

**Comment by xxhenglyxx** [comment]
@seladb Yes everything are passed now.

**Comment by seladb** [comment]
Awesome! If that's ok with you, I'll close the issue now. Please reopen it if you still encounter issues
