### ISSUE TITLE
Http Parsing fails

### ISSUE THREAD

**Issue by omaffeis** [seladb/PcapPlusPlus#881]
Hello, 

I am a newbie with pcapplusplus. 
I was trying to parse the HTTP packet in the attached pcap using Examples/HttpAnalyzer on port 5985.
While it is decoded as HTTP in Wireshark, it is not identified as a Post request using HttpAnalyzer.
When I display the layers of the packet, I get :
```
TCP Packet: Packet length: 275 [Bytes], Arrival time: 2022-03-08 14:56:17.093269000
Ethernet II Layer, Src: 00:21:d7:47:30:77, Dst: 00:e0:4c:d5:e0:0e
IPv4 Layer, Src: 192.168.33.12, Dst: 192.168.104.2
TCP Layer, [ACK], Src port: 50363, Dst port: 5985
Payload Layer, Data length: 221 [Bytes]
```
The layer HTTP is not parsed as HTTP but as "Payload Layer"
What do I get wrong ? 
![httppost](https://user-images.githubusercontent.com/20130714/166954257-7e76ffef-0c68-494c-a44e-fd583af4f8b7.jpg)

**Comment by seladb** [comment]
Hi @omaffeis , thanks for reaching out!
I can't see the attached pcap file, but from the screenshot I can understand what's the problem: currently, [only 80 and 8080 ports are recognized as HTTP packets](https://github.com/seladb/PcapPlusPlus/blob/0aea8feb9dcccf0eed7c23db2e6a9361d2192fe2/Packet%2B%2B/header/HttpLayer.h#L81). PcapPlusPlus doesn't support custom ports such as 5985

**Comment by omaffeis** [comment]
Thank you very much for your answer.
I left this restriction for testing. 
First tests on HTTP parsing are working and I will proceed.
If you have any expected issues doing so, do not hesitate to give details.
