### ISSUE TITLE
intel XL710 i40e driver got PMD 'net_i40e' doesn't support the request RSS hash functions 0x41 

### ISSUE THREAD

**Issue by laskdjlaskdj12** [seladb/PcapPlusPlus#882]
Just as title, I got issue of intel XL710 NIC 

Envirorment
dpdk 20.11 LTS
PcapPlusPlus 21.11
Ubuntu 20.04

setup command
./setup_dpdk.py setup -g 2048 -i enp11s0f0

execute command
```
./PcapPlusPlus-21.11/Dist/DpdkExample-FilterTraffic -d 0
```

envirorment
```
driver: i40e
version: 2.14.13
firmware-version: 8.60 0x8000bd7c 1.3140.0
expansion-rom-version: 
bus-info: 0000:0b:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes
```

How can i fix it?

**Comment by laskdjlaskdj12** [comment]
And I've tried solution of previous PcapPlusPlus issue with XL710 i40e.

but it didn't work for me

**Comment by seladb** [comment]
Hi @laskdjlaskdj12 ! Can you check if this is related to this issue: https://github.com/seladb/PcapPlusPlus/issues/849#issuecomment-1082653871
I'd suggest you try the latest version (v22.05) and see if the issue still persists

**Comment by laskdjlaskdj12** [comment]
Thank you @seladb. I'll try it right away

**Comment by laskdjlaskdj12** [comment]
@seladb no it didn't work.

I install [pcapplusplus-22.05-source-linux.tar.gz](https://github.com/seladb/PcapPlusPlus/releases/download/v22.05/pcapplusplus-22.05-source-linux.tar.gz)
this version and get same error as image below
<img width="974" alt="image" src="https://user-images.githubusercontent.com/16471540/168271742-e9fc8aef-7089-43dd-a52e-d35cfce884d5.png">

**Comment by laskdjlaskdj12** [comment]
my NIC is xl710 intel 40G

**Comment by laskdjlaskdj12** [comment]
I've clean install ubuntu 20.04 and dpdk 20.11.5 
and set GRUB_CMDLINE_LINUX="iommu=pt"
after that i've got this

CPU type is threadRipper 
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/16471540/168290819-2f17e8b0-d2d9-4945-86b1-c0d617010260.png">

**Comment by laskdjlaskdj12** [comment]
And if i disable RSS in DpdkDeviceConfiguration, I've got this error.

same as issue from reported dpdk rss issue
<img width="877" alt="image" src="https://user-images.githubusercontent.com/16471540/168296392-1272322a-ed34-4e88-b9af-99d67e58f44e.png">

**Comment by seladb** [comment]
This issue looks pretty similar to https://github.com/seladb/PcapPlusPlus/issues/869. I don't know why DPDK cannot allocate mbufs and unfortunately I don't have a `i40e` NIC to test on. 
@laskdjlaskdj12 @AlienX2001 - I'll need your help to debug it, or access to your system to debug it myself.
I'd start with this: https://github.com/seladb/PcapPlusPlus/issues/869#issuecomment-1115764872
If you prefer to give me access so I can debug we can discuss it privately over the email pcapplusplus@gmail.com

**Comment by AlienX2001** [comment]
Hey @laskdjlaskdj12 in my fix, i recompiled PCAP++ with the flags as mentioned in https://github.com/seladb/PcapPlusPlus/issues/849#issuecomment-1082818880 after that i recompiled the example apps as well.

**Comment by AlienX2001** [comment]
https://stackoverflow.com/questions/42342723/how-to-set-up-rss-hash-fuction-in-xl710-to-receive-ipv4-flow-type/42344025 This is the reason for why the `RSS_IPV4 | RSS_IPV6` wont work

**Comment by AlienX2001** [comment]
And sorry, I had exams this month, now since they are over, I can be more available for the same

**Comment by AlienX2001** [comment]
But again, in my fix, its working for apps, but for some it says cant allocate mbufs

**Comment by AlienX2001** [comment]
I have a similar issue opened here #869

**Comment by laskdjlaskdj12** [comment]
@AlienX2001 Then, could it be because the CPU is not intel? My CPU is AMD ThreadRipper, and I wonder what kind of environment the code you tested #849 at that time is in.

**Comment by laskdjlaskdj12** [comment]
@seladb I'll check it that you can access the system. i won't be longer to wait

**Comment by AlienX2001** [comment]
For #849 I had the following cpu
```
iiitd@server1:~$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          40
On-line CPU(s) list:             0-39
Thread(s) per core:              2
Core(s) per socket:              10
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           63
Model name:                      Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz
Stepping:                        2
CPU MHz:                         1199.462
CPU max MHz:                     3000.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        4594.54
Virtualization:                  VT-x
L1d cache:                       640 KiB
L1i cache:                       640 KiB
L2 cache:                        5 MiB
L3 cache:                        50 MiB
NUMA node0 CPU(s):               0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38
NUMA node1 CPU(s):               1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe sysca
                                 ll nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq
                                  dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_
                                 timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexprior
                                 ity ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat p
                                 ln pts md_clear flush_l1d
```
The gcc version is 
```
iiitd@server1:~$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
and the dpdk version is 19.11.8

**Comment by laskdjlaskdj12** [comment]
Thank you. I will recompile and try same like #849. And if didn't work, I'll make access for you about checking. Wish you luck on your exam.

> For #849 I had the following cpu
> 
> ```
> 
> iiitd@server1:~$ lscpu
> 
> Architecture:                    x86_64
> 
> CPU op-mode(s):                  32-bit, 64-bit
> 
> Byte Order:                      Little Endian
> 
> Address sizes:                   46 bits physical, 48 bits virtual
> 
> CPU(s):                          40
> 
> On-line CPU(s) list:             0-39
> 
> Thread(s) per core:              2
> 
> Core(s) per socket:              10
> 
> Socket(s):                       2
> 
> NUMA node(s):                    2
> 
> Vendor ID:                       GenuineIntel
> 
> CPU family:                      6
> 
> Model:                           63
> 
> Model name:                      Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz
> 
> Stepping:                        2
> 
> CPU MHz:                         1199.462
> 
> CPU max MHz:                     3000.0000
> 
> CPU min MHz:                     1200.0000
> 
> BogoMIPS:                        4594.54
> 
> Virtualization:                  VT-x
> 
> L1d cache:                       640 KiB
> 
> L1i cache:                       640 KiB
> 
> L2 cache:                        5 MiB
> 
> L3 cache:                        50 MiB
> 
> NUMA node0 CPU(s):               0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38
> 
> NUMA node1 CPU(s):               1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39
> 
> Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
> 
> Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
> 
> Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
> 
> Vulnerability Meltdown:          Mitigation; PTI
> 
> Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
> 
> Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
> 
> Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
> 
> Vulnerability Srbds:             Not affected
> 
> Vulnerability Tsx async abort:   Not affected
> 
> Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe sysca
> 
>                                  ll nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq
> 
>                                   dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_
> 
>                                  timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexprior
> 
>                                  ity ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat p
> 
>                                  ln pts md_clear flush_l1d
> 
> ```
> 
> The gcc version is 
> 
> ```
> 
> iiitd@server1:~$ gcc --version
> 
> gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
> 
> Copyright (C) 2019 Free Software Foundation, Inc.
> 
> This is free software; see the source for copying conditions.  There is NO
> 
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> ```
> 
> and the dpdk version is 19.11.8

**Comment by laskdjlaskdj12** [comment]
@seladb @AlienX2001 First of all, I change DpdkDevice.h Header to 

```RSS_NONFRAG_IPV4_UDP | RSS_NONFRAG_IPV4_TCP | RSS_FRAG_IPV4 | RSS_NONFRAG_IPV4_OTHER | RSS_NONFRAG_IPV4_SCTP | RSS_FRAG_IPV6 | RSS_NONFRAG_IPV6_OTHER | RSS_NONFRAG_IPV6_SCTP | RSS_NONFRAG_IPV6_UDP | RSS_NONFRAG_IPV6_TCP```

and recompile it again. but it didn't work properly.

so no i'm trying to download dpdk version to 19.11.8 from 20.11 LTS.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/16471540/168543773-f76b25b5-09c4-45c4-ab76-2851cf6b2d09.png">

**Comment by AlienX2001** [comment]
Yes, this is the error I am getting for dpdktrafficfilter.
Other apps are running fine

**Comment by laskdjlaskdj12** [comment]
oh.. then is there any chance to run properly in dpdkTrafficfilter?

**Comment by laskdjlaskdj12** [comment]
I just see issue #869 properly. 
@seladb I'll send you ssh access key in Gmail. and will metion you when it sended.
It is all clean installed. So you can debug it properly.

**Comment by AlienX2001** [comment]
Hey @seladb @laskdjlaskdj12 would be great if you could share the results on how you go about fixing the issue on @laskdjlaskdj12 's machine. I will try to recreate the fix on our server. And sorry I can't give access to the server at this moment since the server's not mine, it's my college's server.

**Comment by laskdjlaskdj12** [comment]
@AlienX2001 Okay I'll share the progress.

**Comment by laskdjlaskdj12** [comment]
@seladb Machine is still preparing, because of security work. Could you please wait a little bit?
it takes less then 5hours.

**Comment by seladb** [comment]
> @seladb Machine is still preparing, because of security work. Could you please wait a little bit? it takes less then 5hours.

Sure @laskdjlaskdj12 , I hope I'll have time to get to it once the machine is ready

**Comment by laskdjlaskdj12** [comment]
@seladb @AlienX2001 Okay, And if you guys don't mind, howabout creating slack channel? 
It would be more faster follow up.

**Comment by AlienX2001** [comment]
Discord would be better, but slack works aswell

**Comment by seladb** [comment]
There is already a slack workspace for PcapPlusPlus, here is an invite to it: https://join.slack.com/t/pcapplusplusworkspace/shared_invite/zt-199xbjskh-w2Nv3kSv0CEhEkFCH6hx7A

I created a channel called `#dpdk-ie40`, once you sign in you can add yourself to it: https://slack.com/app_redirect?channel=C03FR9Y7A6P
