### ISSUE TITLE
22.05 build fails on dpdk

### ISSUE THREAD

**Issue by lgbaldoni** [seladb/PcapPlusPlus#883]
Using openSUSE Tumbleweed on x86_64, after the 22.05 update I'm seeing this error:

```
==== Building target: Pcap++ ====
Building file: src/DpdkDevice.cpp
src/DpdkDevice.cpp: In member function 'bool pcpp::DpdkDevice::configurePort(uint8_t, uint8_t)':
src/DpdkDevice.cpp:44:57: error: 'ETH_RSS' was not declared in this scope; did you mean 'ETH_RSS_AH'?
   44 | #define DPDK_CONFIG_MQ_MODE                             ETH_RSS
      |                                                         ^~~~~~~
src/DpdkDevice.cpp:249:35: note: in expansion of macro 'DPDK_CONFIG_MQ_MODE'
  249 |         portConf.rxmode.mq_mode = DPDK_CONFIG_MQ_MODE;
      |                                   ^~~~~~~~~~~~~~~~~~~
src/DpdkDevice.cpp: In member function 'bool pcpp::DpdkDevice::startCaptureSingleThread(pcpp::OnDpdkPacketsArriveCallback, void*)':
src/DpdkDevice.cpp:566:36: error: 'rte_get_master_lcore' was not declared in this scope; did you mean 'rte_get_main_lcore'?
  566 |                 if (coreId == (int)rte_get_master_lcore() || !rte_lcore_is_enabled(coreId))
      |                                    ^~~~~~~~~~~~~~~~~~~~
      |                                    rte_get_main_lcore
```

Using dpdk 21.11.1.

**Comment by seladb** [comment]
Hi @lgbaldoni !
Yes, PcapPlusPlus doesn't yet support DPDK 21.11. It supports versions 20.11 and below, as mentioned in the [documentation](https://pcapplusplus.github.io/docs/dpdk#supported-dpdk-versions).
The DPDK team removed a few APIs in 21.11 that are used in PcapPlusPlus. I'll add support for it soon. In the meantime - can you use DPDK 20.11?

**Comment by lgbaldoni** [comment]
> Yes, PcapPlusPlus doesn't yet support DPDK 21.11. It supports versions 20.11 and below, as mentioned in the [documentation](https://pcapplusplus.github.io/docs/dpdk#supported-dpdk-versions).

Right, I should have checked that first. It wasn't mentioned in the changelog, so I made a bad assumption.

> In the meantime - can you use DPDK 20.11?

Not feasible. I suppose it's best to keep the old stable instead of disabling dpdk.

Thanks

**Comment by seladb** [comment]
Why isn't it possible to use an older version of DPDK? 🤔

**Comment by lgbaldoni** [comment]
> Why isn't it possible to use an older version of DPDK?

Either I create another package with the older version, have it accepted in the repository and maintain it or I build dpdk statically and link to it, which OBS/openSUSE maintainers don't like very much. Also I have very little time of late.

**Comment by seladb** [comment]
So the PcapPlusPlus package you built always pulls the latest version of DPDK? Is it possible to modify it and pin a specific version of DPDK?
In general, it's not necessarily a good idea to pull the latest version because DPDK often introduces breaking changes in its releases. It's better to use a specific version and update it from time to time.
I'm sorry for all these questions, I have very little knowledge of openSUSE packages...

**Comment by lgbaldoni** [comment]
> So the PcapPlusPlus package you built always pulls the latest version of DPDK? Is it possible to modify it and pin a specific version of DPDK?

I pull in the version the distribution provides.
Like I said, I could create a separate legacy package, but then I'd have to maintain it. Also this package is not in Factory, so I can't really count on anyone else to fix it.

> In general, it's not necessarily a good idea to pull the latest version because DPDK often introduces breaking changes in its releases. It's better to use a specific version and update it from time to time.

I know, a library update breaking API/ABI is an average Wednesday on openSUSE.

> I'm sorry for all these questions, I have very little knowledge of openSUSE packages...

Oh, don't worry at all.

**Comment by seladb** [comment]
> > So the PcapPlusPlus package you built always pulls the latest version of DPDK? Is it possible to modify it and pin a specific version of DPDK?
> 
> I pull in the version the distribution provides. Like I said, I could create a separate legacy package, but then I'd have to maintain it. Also this package is not in Factory, so I can't really count on anyone else to fix it.

I see what you mean: the DPDK version for openSUSE Tumbleweed is 21.11: https://software.opensuse.org/package/dpdk
Is it possible to update PcapPlusPlus for older openSUSE versions (where DPDK version is still 19.11)?

**Comment by lgbaldoni** [comment]
> I see what you mean: the DPDK version for openSUSE Tumbleweed is 21.11: https://software.opensuse.org/package/dpdk
Is it possible to update PcapPlusPlus for older openSUSE versions (where DPDK version is still 19.11)?

Alas no, because pcapplusplus is not an official distro package and dpdk lives in the same project (network)  and that's 21.11 LTS for every target.

I tried creating a dpdk-20 package, but it's a rather complex piece of software and I don't have the time to debug it, let alone maintain it.

**Comment by seladb** [comment]
Got it 😔
By the way, does it mean the existing version of PcaPlusPlus will stop working as well?

**Comment by seladb** [comment]
> I would say so, now that I think of it. As you can see [here](https://download.opensuse.org/repositories/network/openSUSE_Tumbleweed/x86_64/) , libdpdk-19 is nowhere to be found😒

That's a bummer, how can we fix that for the existing pcapplusplus version?



> In short, if this package needs to be relied upon, it needs a regular maintainer to submit it for distro inclusion.

By "this package" do you mean pcapplusplus or DPDK 19.11?

**Comment by lgbaldoni** [comment]
> This is a bummer, how can we fix that for the existing pcapplusplus version?

The only way is that someone creates a dpdk-legacy package and maintains it. Unfortunately, I can't.

> By "this package" do you mean pcapplusplus or DPDK 19.11?

Pcapplusplus. As I understand DPDK is always kept on LTS releases on openSUSE.

**Comment by seladb** [comment]
I am the maintainer of PcapPlusPlus so I can theoretically do all of that, however I know nothing about openSUSE package maintenance. Where should I start and how much work is it?

Also - I think we can remove the dependency on DPDK and have PcapPlusPlus depend only on libpcap which interface doesn't usually introduce breaking changes. This will make the package management much easier. What do you think?

**Comment by lgbaldoni** [comment]
> I am the maintainer of PcapPlusPlus so I can theoretically do all of that, however I know nothing about openSUSE package maintenance. Where should I start and how much work is it?

Frankly, the main thing is keeping the patches fresh. If the package is submitted for inclusion into Factory, one also has to take care of breakages and bug reports.
By the way, have you considered a different build system like meson or CMake?

> Also - I think we can remove the dependency on DPDK and have PcapPlusPlus depend only on libpcap which interface doesn't usually introduce breaking changes. This will make the package management much easier. What do you think?

Oh well, that's already the case for every non x86 arch. Not sure about the performance hit, though.
22.05 is now up

**Comment by lgbaldoni** [comment]
> TBH, I didn't understand almost any of it rofl

Oh well, it's trivial. The coding part (your end) is orders of magnitude more complex.

> I just saw that the latest version is indeed 22.05: https://build.opensuse.org/package/show/network/pcapplusplus
> So does it mean it's done?

Update done with dpdk disabled for every architecture. However end users still need to add a repository to access it.
If I had more time I'd submit it for inclusion with the distribution.

By the way, do you have a list of packages using this library? That might generate interest.

**Comment by seladb** [comment]
> Update done with dpdk disabled for every architecture. However end users still need to add a repository to access it.

that's great news! I think we can disable DPDK support for now. What do you mean by adding a repository to access it?

> If I had more time I'd submit it for inclusion with the distribution.

is it something I can do or only do I need to be part of the openSUSE community in order to submit?



> By the way, do you have a list of packages using this library? That might generate interest.

No, I don't have such a list. In that sense C++ is a bit more tricky because there's no centralized package manager. However I know there are some open source projects that use it

**Comment by lgbaldoni** [comment]
> What do you mean by adding a repository to access it?

I mean [this](https://software.opensuse.org/download/package?package=pcapplusplus&project=network)
Also packages in projects are unsupported.

> is it something I can do or only do I need to be part of the openSUSE community in order to submit?

All you need is an OBS account, which I think you already have.
Thing is, should the need arise, as maintainer you will be on the receiving end of bugzilla tickets.

**Comment by seladb** [comment]
Got it, thanks for all the info!
Since I'm not familiar with these processes in the openSUSE community - it'd be great if you can guide me and share these tickets and requests as they arrive. That way I can learn and eventually maintain this package myself. Let me know what you think

**Comment by lgbaldoni** [comment]
>  Since I'm not familiar with these processes in the openSUSE community - it'd be great if you can guide me and share these tickets and requests as they arrive. That way I can learn and eventually maintain this package myself. Let me know what you think

Ok, I added you as co-maintainer. I will now try and submit the package to Factory and see what happens.

**Comment by seladb** [comment]
Sure, thanks!

Should we close this issue now or keep it open?

**Comment by lgbaldoni** [comment]
Sure, as it's not an actual bug.
BTW; you should have received a few OBS notifications by now.

**Comment by seladb** [comment]
> BTW; you should have received a few OBS notifications by now.

I logged into my OBS account and saw 1 notification that leads here: https://build.opensuse.org/request/show/979371?notification_id=32688706#comments-list

**Comment by lgbaldoni** [comment]
> I logged into my OBS account and saw 1 notification that leads here: 

Perhaps you have email notifications disabled or you don't check the mailbox used for registration?

**Comment by seladb** [comment]
I turned on email for all notification types, let's see if that'll help...

**Comment by lgbaldoni** [comment]
@seladb as you probably saw from the notifications, pcapplusplus is now an official openSUSE package, although only for Tumbleweed at the present.

Do you happen to have a list of other programs relying on it?

**Comment by seladb** [comment]
WOW, this is great news!! 🌟 🎆 

Actually, I didn't get any notification for that - I'm not sure what's wrong 😕 



> Do you happen to have a list of other programs relying on it?

Unfortunately I don't maintain such a list, I do know a few open-source projects using it, but it's not a comprehensive list....
