### ISSUE TITLE
Memory leak in version of LightPcapNg

### ISSUE THREAD

**Issue by cswindle** [seladb/PcapPlusPlus#885]
Currently with the current code there is a memory leak when making use of the LightPcapNg code due to changes which have been made to that code in PcapPlusPlus. Below is the very simplest code which is able to reproduce the issue:

```
#include <PcapFileDevice.h>

/**
 * main method of this utility
 */
int main(int argc, char* argv[])
{
        pcpp::PcapNgFileWriterDevice pcap_writer("test.pcap");
        pcap_writer.open(false);
        pcap_writer.close();
        return 0;
}
```

If you compile and run this under a tool to verify memory leaks (for example valgrind) you will see that there is a memory leak.

The issue is caused by memory being allocated in light_open, but not being freed in light_close. I will be shortly be raising a PR which includes the fix for the issue.

**Comment by seladb** [comment]
Thanks for providing the fix 🙏 
Your PR was merged to `dev`

**Comment by seladb** [comment]
This PR was merged to `master`, thanks again for your contribution!
