### ISSUE TITLE
fcs

### ISSUE THREAD

**Issue by GilbertoTheMighty** [seladb/PcapPlusPlus#890]
Hello. How to append and enable [FCS](https://tools.ietf.org/id/draft-gharris-opsawg-pcap-00.html) to existing packet? 
[PacketTrailerLayer](https://pcapplusplus.github.io/v1904/Documentation/a01186.html) looks like the thing, but it is not obvious how to use it. How can one compute checksum and append it to file header?

**Comment by seladb** [comment]
Yep, I think `PacketTrailerLayer` is actually FCS. Can you elaborate on what is not clear in how to use it?

BTW, here is the updated API link (for the latest version of PcapPlusPlus 22.05): https://pcapplusplus.github.io/api-docs/v22.05/classpcpp_1_1_packet_trailer_layer.html

**Comment by GilbertoTheMighty** [comment]
According to [PCAP Capture File Format](https://tools.ietf.org/id/draft-gharris-opsawg-pcap-00.html) FCS with its length resides in file header, while TrailerLayer applies to packet and have no useful functions like `calculateChecksum`
Could you please provide me with example on how I can add fsc to 3 existing packets inside pcap file without fsc?

**Comment by seladb** [comment]
IIRC libpcap doesn't provide an interface to view or edit FCS in the packet header, so the heuristic done [here](https://github.com/seladb/PcapPlusPlus/blob/5dd6cec932e5dee2d040206c4b17c63994940ed8/Packet%2B%2B/src/Packet.cpp#L100-L118) is to check for extra data in the packet (which may come from FCS) and create a `PacketTrailerLayer` out of it.
As explained [here](https://pcapplusplus.github.io/api-docs/v22.05/classpcpp_1_1_packet_trailer_layer.html) there is currently no option to add or edit FCS / packet trailer. The main reason is that I don't think libpcap provides such an interface.

**Comment by seladb** [comment]
@GilbertoTheMighty I'm closing the issue now, please reopen if needed
