### ISSUE TITLE
DNS response NX domains are classified as DNS query because there are no answers

### ISSUE THREAD

**Issue by AlienX2001** [seladb/PcapPlusPlus#893]
Hey, from me again,
During my work with PcapPlusPlus I noticed that dns response NX domains were treated as DNS queries as seen in the screenshot
![image](https://user-images.githubusercontent.com/64488123/170861312-b85963f6-d6d0-4d3b-9bf6-8614f41953a1.png)

The code for the following pcapplusplus is as follows
```C++
#include "PcapFileDevice.h"
#include "DnsLayer.h"
#include "IPv4Layer.h"
#include "Packet.h"
#include <iostream>
#include <fstream>
#include <stdlib.h>
#include <string.h>
#include <unordered_map>

int main(int argc, char* argv[])
{
    //if less arguments
    if(argc<3){std::cout<<"Usage: "<<argv[0]<<" PcapFile BatchSize"<<std::endl; return -1;}
    //checking if pcap file exists
    std::ifstream f;
    f.open(argv[1]);
    if(!f){std::cout<<"PcapFile doesnt Exist!!"<<std::endl; return -1;}
    f.close();
    // use the IFileReaderDevice interface to automatically identify file type (pcap/pcap-ng)
    // and create an interface instance that both readers implement
    pcpp::IFileReaderDevice* reader = pcpp::IFileReaderDevice::getReader(argv[1]);

    // verify that a reader interface was indeed created
    if (reader == NULL)
    {
        std::cerr << "Cannot determine reader for file type" << std::endl;
        return -1;
    }
    // open the reader for reading
    if (!reader->open())
    {
        std::cerr << "Cannot open "<<argv[1]<<" for reading" << std::endl;
        return -1;
    }

    pcpp::RawPacket rawPacket; //raw packet taken from pcap
    std::vector<std::string> srcIP; // dest IP of the amplification
    std::unordered_map<std::string,int> floodScore; // map of dest IP and count of packets to it
    unsigned long long batch = 0;
    while(reader->getNextPacket(rawPacket)){
        pcpp::Packet parsedPacket(&rawPacket); // making parsed packet from raw packet to extract information layer by layer
        if (parsedPacket.isPacketOfType(pcpp::IPv4)) // if the packet is of IPv4
        {
            pcpp::DnsLayer* dnsLayer = parsedPacket.getLayerOfType<pcpp::DnsLayer>();
            if(dnsLayer == NULL){continue;} // continue if the packet is not of dns
            std::cout<<dnsLayer->toString()<<" from IP "<<parsedPacket.getLayerOfType<pcpp::IPv4Layer>()->getSrcIPAddress().toString()<<std::endl;
            //if(dnsLayer->getQueryCount() == 0){std::cout<<"Strange anomaly query flag is 0"<<std::endl;} // something sus, idk
            //else if(dnsLayer->getAnswerCount() == 0){continue;} // if it is a dns query then do nothing
            /*else{ //if it is a dns response
                // check if it has an NX domain or not
                //batch++;
                std::cout<<dnsLayer->getFirstAnswer()->getName()<<std::endl;
            }*/
        }
    }
    // displaying all destination IPs and how many packets they recieved
    /*for (auto x : ampPacket){
        std::cout<<"IP: "<<x.first<<"; Count: "<<x.second<<std::endl;
    }*/
}
```
The 2nd half of the screenshot is from tcpdump.

I think I might have identified the problem in https://github.com/seladb/PcapPlusPlus/blob/5dd6cec932e5dee2d040206c4b17c63994940ed8/Packet%2B%2B/src/DnsLayer.cpp#L393
Here it is looking for answers, if there exists 1 or more answers then it classifies it as DNS response or else it classifies it as a query, but NX domains and other statuses like SERVFAIL, etc. are the exceptions of this logic as even though they are reponses they dont have any answer content in them.
A better way to classify DNS Query and DNS Responses would be to check the flags in their header. The 1st bit in the flag area of the DNS header should be how it should be classifed as 0 stands for query and 1 stands for response.

**Comment by AlienX2001** [comment]
Oh figured out a fix, you should classify the query or response using getDnsHeader()->queryOrResponse.
Its 0 for query and 1 for Response.

**Comment by seladb** [comment]
@AlienX2001 this is a very good point, and I agree with the solution you propose. Would you consider opening a PR with the fix?
It's be great if you can also and a [test](https://github.com/seladb/PcapPlusPlus/blob/5dd6cec932e5dee2d040206c4b17c63994940ed8/Tests/Packet%2B%2BTest/Tests/DnsTests.cpp) with a small pcap file that reproduces this issue

**Comment by seladb** [comment]
Thank you @AlienX2001 for providing the fix, I really appreciate your contribution!
Your PR was merged to `master`, I'm closing the issue now
