### ISSUE TITLE
CPU utilization exceeds 100%

### ISSUE THREAD

**Issue by qq452739204** [seladb/PcapPlusPlus#907]
When using this code, the CPU utilization rate of httpanalyzer in the example is 100% after startup, but the traffic is not large at this time. I would like to ask why there is no such problem and how to solve it?
![1](https://user-images.githubusercontent.com/16432513/177069874-45d64fe1-d395-4912-9c18-42cc8041f15c.png)

**Comment by seladb** [comment]
@qq452739204 sorry for the late reply. I think this issue is already discussed here: https://github.com/seladb/PcapPlusPlus/issues/126

You can change value of `pcpp::PcapLiveDevice::DeviceConfiguration::packetBufferTimeoutMs` to change the buffer timeout which should reduce the CPU utilization

**Comment by qq452739204** [comment]
Find the Libpcap packet capturing mechanism and study the Libpcap related interface call methods in the source code. It is found that there is an overloaded function open (pcpp:: pcaplivedevice:: deviceconfiguration config). This problem has been solved by modifying the parameter value of packetbuffertimeouts.

Thank you for your reply
