### ISSUE TITLE
error: inlining failed in call to always_inline

### ISSUE THREAD

**Issue by coder-sjn** [seladb/PcapPlusPlus#908]
I get the following error after executing the command ‘make all’：

Building file: src/MBufRawPacket.cpp
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/include/immintrin.h:51,
                 from /usr/lib/gcc/x86_64-linux-gnu/9/include/x86intrin.h:32,
                 from /usr/local/include/rte_vect.h:28,
                 from /usr/local/include/rte_memcpy.h:17,
                 from /usr/local/include/rte_mempool.h:51,
                 from /usr/local/include/rte_mbuf.h:38,
                 from src/MBufRawPacket.cpp:8:
/usr/lib/gcc/x86_64-linux-gnu/9/include/avxintrin.h: In function ‘void rte_mov32(uint8_t*, const uint8_t*)’:
/usr/lib/gcc/x86_64-linux-gnu/9/include/avxintrin.h:926:1: error: inlining failed in call to always_inline ‘void _mm256_storeu_si256(__m256i_u*, __m256i)’: target specific option mismatch

![1657435234857](https://user-images.githubusercontent.com/75304827/178134229-c5c72a2f-b29d-4a60-811b-f317964a53f8.png)

**Comment by seladb** [comment]
@coder-sjn sorry for the late reply. It looks like something is wrong with building a DPDK app on your platform. Does DPDK (without PcapPlusPlus) works for you on this platform?

**Comment by coder-sjn** [comment]
> @coder-sjn sorry for the late reply. It looks like something is wrong with building a DPDK app on your platform. Does DPDK (without PcapPlusPlus) works for you on this platform?

thanks for reply. DPDK does not work.

**Comment by seladb** [comment]
I'm not sure what is your setup, but maybe you should clean PcapPlusPlus (run `make clean`) or even run `./configure-linux.sh` again?

**Comment by seladb** [comment]
@coder-sjn should we keep this issue open or can we close it?

**Comment by coder-sjn** [comment]
> @coder-sjn should we keep this issue open or can we close it?

sorry, i forgot this issue.thanks for your reply.
