### ISSUE TITLE
Question about the capturing packets.

### ISSUE THREAD

**Issue by gleb-kun** [seladb/PcapPlusPlus#909]
Hello!
What wireless interface modes are supported by classes `PcapLiveDevice` and `WinPcapLiveDevice`?

1. Can I read packets from an interface when it is in access point mode?
2. Can I read packets from an interface when it is in monitor mode (sniffer)?

**Comment by seladb** [comment]
@gleb-kun I'm not sure how to answer these questions because I'm not an expert on wireless interfaces. The best option is to try and see what's working...

**Comment by gleb-kun** [comment]
@seladb, okay, I'll try it and post the results here.

**Comment by gleb-kun** [comment]
Okay, I have tried capturing packets while my wireless interface was in monitor mode and in AP mode. I used the example from [here](https://pcapplusplus.github.io/docs/tutorials/capture-packets), but I added a count of the total number of packets.


Output result for capturing packets in access point mode:
```
Results:
Ethernet packet count: 6538
IPv4 packet count:     6518
IPv6 packet count:     8
TCP packet count:      6468
UDP packet count:      55
DNS packet count:      44
HTTP packet count:     0
SSL packet count:      364
Other packet count:    6538

```


Output result for capturing packets in monitor mode:
```
Results:
Ethernet packet count: 0
IPv4 packet count:     0
IPv6 packet count:     0
TCP packet count:      0
UDP packet count:      0
DNS packet count:      0
HTTP packet count:     0
SSL packet count:      0
Other packet count:    44849
```

Based on this, I can answer both my questions "yes". But I have one more question. When capturing a packet in monitoring mode, I get an 802.11 protocol packet with a radiotap header, it looks like this:
<details>
  <summary>Packet example</summary>
  pcap: https://dropmefiles.com/5tvhO
  ```
  0000   00 00 29 00 ee 48 00 a0 a0 08 00 a0 a0 08 00 00
  0010   10 02 85 09 a0 00 d0 00 64 00 00 00 00 34 00 00
  0020   00 00 00 00 01 00 00 00 02 80 00 00 00 ff ff ff
  0030   ff ff ff 60 a4 b7 ce c5 eb 60 a4 b7 ce c5 eb d0
  0040   31 0d a0 14 f0 9b 00 00 00 64 00 31 14 00 07 73
  0050   77 5f 74 65 73 74 01 08 82 84 8b 96 0c 12 18 24
  0060   03 01 06 05 04 00 01 00 00 2a 01 00 32 04 30 48
  0070   60 6c 30 18 01 00 00 0f ac 02 02 00 00 0f ac 04
  0080   00 0f ac 02 01 00 00 0f ac 02 0c 00 dd 1a 00 50
  0090   f2 01 01 00 00 50 f2 02 02 00 00 50 f2 04 00 50
  00a0   f2 02 01 00 00 50 f2 02 46 05 53 0e 00 00 00 3b
  00b0   02 51 00 2d 1a 6f 08 03 ff ff 00 00 01 00 00 00
  00c0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 3d
  00d0   16 06 08 04 00 00 00 00 00 00 00 00 00 00 00 00
  00e0   00 00 00 00 00 00 00 4a 0e 14 00 0a 00 2c 01 c8
  00f0   00 14 00 05 00 19 00 7f 06 05 10 08 82 00 40 6b
  0100   01 00 6c 02 7f 00 bf 0c b2 60 a0 03 fa ff 00 00
  0110   fa ff 00 00 c0 05 00 06 00 fc ff dd 1a 00 90 4c
  0120   04 08 bf 0c b2 60 a0 03 fa ff 00 00 fa ff 00 00
  0130   c0 05 00 06 00 fc ff ff 23 23 e1 70 80 12 40 11
  0140   02 30 04 b6 00 01 94 04 02 00 00 fa ff fa ff 7b
  0150   1c c7 71 1c c7 71 1c c7 71 1c c7 71 ff 07 24 f4
  0160   01 01 04 fc ff ff 0e 26 20 00 ff ff 20 ff ff 40
  0170   ff ff 60 ff ff ff 02 27 00 dd 18 00 50 f2 02 01
  0180   01 80 00 03 a4 00 00 27 a4 00 00 42 43 5e 00 62
  0190   32 2f 00 dd 1d 00 50 f2 04 10 4a 00 01 10 10 44
  01a0   00 01 02 10 3c 00 01 03 10 49 00 06 00 37 2a 00
  01b0   01 20 dd 07 50 6f 9a 16 01 01 40 dd 05 00 09 86
  01c0   01 00 7d 26 cd 01
  ```

  ![Image alt](https://raw.githubusercontent.com/gleb-kun/hosting_repo/master/Screenshot%20from%202022-07-13%2011-53-02.png?token=GHSAT0AAAAAABU6AKRSGQSKTDGZCP5BY43GYWORHWA)
</details>

Is it possible to get the type of such a packet and parse it using pcapplusplus?

**Comment by gleb-kun** [comment]
I'm confused about opening/closing issue 😅 Sorry!

**Comment by seladb** [comment]
Unfortunately we don't currently plan to support Radiotap and 802.11, but if you're interested you're more than welcome to add support for these protocols

**Comment by gleb-kun** [comment]
Thank you very much for the answer!

**Comment by seladb** [comment]
Should we keep this issue open or can we close it?
