### ISSUE TITLE
Issue: Dpdk server-client app

### ISSUE THREAD

**Issue by JakeAbo** [seladb/PcapPlusPlus#93]
Hey,

I'm trying to write a simple client server application.
I noticed that DpdkDevice::receivePackets(...) and DpdkDevice::sendingPackets(...) are only for receive  and send over the networks.

Is PcapPlusPlus library have the functionality to send and receive to a specific PORT(for instance: loopback, like socket communication)?

I would really appreciate your help,
Thanks Jack

**Comment by seladb** [comment]
I'm not sure I understand your question. DPDK is a kernel bypass library for sending and receiving packets in wire speed which is achieved by accessing directly to the network card without going through the kernel. 
You are asking about sending and receiving packets from loopback interface which is created by the kernel so DPDK is probably not what you're looking for.
Fortunately, libpcap does provide an option to capture/send packets using the loopback interface like with any other interface. So you can simply use `PcapLiveDevice` as explained in this [tutorial](http://seladb.github.io/PcapPlusPlus-Doc/tutorial_live_capture.html) and use the loopback interface instead of a "regular" one.
Please let me know if this answers your question

**Comment by JakeAbo** [comment]
Thank you for your answer.

I think you miss understood me, I would like to ask my question again.
I'm looking for a way to make Server client application(on DPDK) which enables functionality of loading packets from pcap file, send it using dpdk virtual device(PORT 0) and recieve it on the server on other virtual device (PORT 1), filter the passed packets and send the passed packets back to the client using dpdk application (PORT 1).

In order to do that i need a recv and send functions of the dpdk device to a specific device.
More over, i wondering if there is an functionality of sending and reciving data(Instead of Packets).

**I am not looking for sniffing traffic, I am looking for a way to send messages between clients and server(the messages includes: packets, pass/not pass, reasons and more...) on DPDK.

Thank you,
Jack

**Comment by seladb** [comment]
I'm not sure I'm following you. What are DPDK virtual devices? Could you please send me a link to read about it? Maybe I know it by a different name, but I don't think I've heard about it.
If I understand what you wrote correctly, it seems that DPDK virtual device is a kind of dummy interface, a little bit like the loopback concept. But please elaborate more.
Anyway, DPDK wrapper implementation in PcapPlusPlus currently doesn't include sending and receiving of data, only packets. Does DPDK supports that?

**Comment by seladb** [comment]
I'm not sure if you've seen my previous message. I'd really appreciate if you can read it and answer the questions there

**Comment by JakeAbo** [comment]
I will just make my question simpler...

I looked in the PcapPlusPlus Docs on DpdkDevice::ReceivePackets:
"Receive parsed packets from the network"

Is there an opportunity to find out which computer send those packets to me? and send them back to him?
Like a simple server client program.
Client send "hello" -> Server reveive "hello" -> send back "hello" to client...

Is there an opportunity to do it with the PcapPlusPlus API(in dpdk)?

**Comment by seladb** [comment]
I guess the answer to your question would be "yes". What you need to do is to receive parsed packets  using `DpdkDevice::receivePackets()` and then check IP address or MAC address (depends whether you want to work in L2 or L3) to identify the specific client. Then you should create a new packet, or even better - modify the packet you got so the client IP/MAC addresses are reversed and send it back on the network.
Please let me know if that answers your question

**Comment by JakeAbo** [comment]
I'm having a difficulty to understand how to determine which client send the packet because I can also receive packets with "bla bla" IP or MAC... and it cant be the client...

**Comment by seladb** [comment]
What do you mean "bla bla" IP or MAC? Aren't those real packets?

**Comment by JakeAbo** [comment]
In my project i send the packets to the network and all computers in the LAN network receive the packets.
I'm interesting in sending packets to a specific computer without all other computers on LAN receive it. How can I implement `DpdkDevice::sendPackets()` to a specific computer...

**Comment by seladb** [comment]
You should build the packets with a MAC address and IP address that corresponds to the specific computer you want to send the packets to

**Comment by seladb** [comment]
Hi, any updates on this issue?

**Comment by seladb** [comment]
Since I didn't see any reply on the last 2.5 I'm closing this issue now. Please reopen it if needed
