### ISSUE TITLE
Different compiler support 

### ISSUE THREAD

**Issue by zliucd** [seladb/PcapPlusPlus#939]
Hi,

I want to compile PcapPlusplus with Clang++, and ```configure.sh``` does not support compiler options.   I don't know how can I change compiler, or it would be nice to add in ```configure.sh``` options.

**Comment by seladb** [comment]
Hi @zliucd ! you can use Clang++ to build PcapPlusPlus, although it's probably not very well documented. You just need to set the `CC` and `CXX` env variables to `clang` and `clang++` respectively. For example:
```shell
./configure-xxx.sh
...
CXX=clan++ CC=clang make
```

**Comment by zliucd** [comment]
@seladb  Thanks, and it's ok to close this issue.  The default of ```CC``` and ```CXX``` in OSX is Clang/Clang++, and there is no problem of compiling PcapPlusPlus; in Linux, I have to manually switch compilers.
