### ISSUE TITLE
Run multiple Dpdk applications

### ISSUE THREAD

**Issue by liorzemah** [seladb/PcapPlusPlus#94]
Hey, i try to run two Dpdk applications that using PcapPlusPlus library, the first one run successfully but the second application print the following error:

EAL: Detected 4 lcore(s)
EAL: Error - exiting with code: 1
Cause: Cannot create lock on '/var/run/.rte_config'. Is another primary process running?

I understand that the EAL is locked by the first Dpdk application. How can i support running two or more applications.

**Comment by seladb** [comment]
I must admit I never tried that...
One thing I'm sure of is that you cannot run 2 DPDK applications that use the same core(s). You must provide each application a different set of cores and then it may work.
What I suggest you to do is to run this test with DPDK test application provided with DPDK (without PcapPlusPlus) and see if that works. If it works we can try to see how to make it work with PcapPlusPlus.
Please let me know what you think

**Comment by seladb** [comment]
Did you have a chance to try that?

**Comment by liorzemah** [comment]
I tried to run 2 DPDK applications that unuse the same cores and i got the following error (when i tried to run the second application):

Launching app
EAL: Detected 4 lcore(s)
EAL: Error - exiting with code: 1
  Cause: Cannot create lock on '/var/run/.rte_config'. Is another primary process running?

I guess the problem is not related to the cores but is related to the file mentioned, it is probably not possible for 2 or more applications to use the same file and DPDK does not know how to duplicate the file for more use in a same time.

**Comment by seladb** [comment]
Thanks for sharing this information!
With your permission I'll close the issue now. Please re-open it if you have any more questions.
