### ISSUE TITLE
FTP.h error during make

### ISSUE THREAD

**Issue by ArkAngeL43** [seladb/PcapPlusPlus#943]
```
In file included from Modules/header/Methods.hpp:6,
                 from Modules/header/JSON.hpp:7,
                 from Modules/Loader.cpp:14,
                 from main.cpp:1:
/usr/local/include/pcapplusplus/FtpLayer.h: In constructor ‘pcpp::FtpLayer::FtpLayer(uint8_t*, size_t, pcpp::Layer*, pcpp::Packet*)’:
/usr/local/include/pcapplusplus/FtpLayer.h:21:154: error: ‘FTP’ was not declared in this scope; did you mean ‘NTP’?
   21 |   FtpLayer(uint8_t *data, size_t dataLen, Layer *prevLayer, Packet *packet) : SingleCommandTextProtocol(data, dataLen, prevLayer, packet) { m_Protocol = FTP; };
      |                                                                                                                                                          ^~~
      |                                                                                                                                                          NTP
/usr/local/include/pcapplusplus/FtpLayer.h: In constructor ‘pcpp::FtpLayer::FtpLayer(std::string, std::string)’:
/usr/local/include/pcapplusplus/FtpLayer.h:22:113: error: ‘FTP’ was not declared in this scope; did you mean ‘NTP’?
   22 |   FtpLayer(std::string command, std::string option) : SingleCommandTextProtocol(command, option) { m_Protocol = FTP; };
      |                                                                                                                 ^~~
      |                                                                                                                 NTP
make: *** [Makefile:5: all] Error 1
```

not sure if this is an issue on the developer side or my side

**MAKEFILE**

```
include /usr/local/etc/PcapPlusPlus.mk

# All Target
all:
	g++ $(PCAPPP_BUILD_FLAGS) $(PCAPPP_INCLUDES) -c -o main.o main.cpp
	g++ $(PCAPPP_LIBS_DIR) -static-libstdc++ -o main main.o $(PCAPPP_LIBS)

# Clean Target
clean:
	rm main.o
	rm main
```

**Comment by seladb** [comment]
@ArkAngeL43 can you check `/usr/local/include/pcapplusplus/ProtocolType.h` and see if you can find this line?

https://github.com/seladb/PcapPlusPlus/blob/543880bb3aa9527cec748dcb12fd8a819e7e3e36/Packet%2B%2B/header/ProtocolType.h#L268

**Comment by seladb** [comment]
@ArkAngeL43 I'm not sure if you saw my previous question/comment?

**Comment by ArkAngeL43** [comment]
hey dude thank you for the response, so sorry i was not able to keep up with this i have been so easy. give me about 2-3 more hours and i should have a valid response ready for you!

**Comment by ArkAngeL43** [comment]
**Update** 

looked inside of the directory that you gave me, the file was there but this is what was on line 268

```cpp
	enum OsiModelLayer
	{
		/** Physical layer (layer 1) */
		OsiModelPhysicalLayer = 1,
		/** Data link layer (layer 2) */
		OsiModelDataLinkLayer = 2,
		/** Network layer (layer 3) */
		OsiModelNetworkLayer = 3,
		/** Transport layer (layer 4) */
		OsiModelTransportLayer = 4,
		/** Session layer (layer 5) */
		OsiModelSesionLayer = 5,
		/** Presentation layer (layer 6) */
		OsiModelPresentationLayer = 6,
		/** Application layer (layer 7) */
		OsiModelApplicationLayer = 7,
		/** Unknown / null layer */
		OsiModelLayerUnknown = 8
	};
```

I noticed that during development i had to manually copy the FtpLayer.h file into the include directory because when i went to go mess around with the layer it said it was not in that directory, nor was the TelNet layer, it told me during install that the files were all directly OK and tested, all files of .h and .cpp were built, included and ran correctly but when i went to the include directory only half of the files were in there i believe it was all the header files in the `PCAP++` file from the repo, and very few from the `PACKET++` file inside of the repo.

**Comment by seladb** [comment]
I suspect you ran `make install` on a version different from the one you're currently working on.

Can you checkout the code again on a separate directory, then run `configure-linux`, `make` and `make install`?

Let me know if you see all the files in `/usr/local/include/pcapplusplus/`

**Comment by ArkAngeL43** [comment]
thank you i will report back when i have done this!

**Comment by ArkAngeL43** [comment]
**UPdate**

Sorry for such a laggy response time i have been super busy with development but i just got back to working with things and here is the result

**BUILD RESULT**
```
Build successful!
```
every file was built with no warnings or errors the file FtpLayer.h is also in the directory now along with the file ProtoColType.h with line 

```cpp
const ProtocolType FTP = 0x10000000000;
```

thank you for the help, i must have been using the wrong flags or as said different version. sorry for late response again

**Comment by seladb** [comment]
Thanks for the update @ArkAngeL43 !
I'm glad everything worked out 🙂
