### ISSUE TITLE
IPv6 Support for TCP reassembly

### ISSUE THREAD

**Issue by jannik3141** [seladb/PcapPlusPlus#95]
Hi again,

How difficult would that be to implement TCP reassembly for IPv6? I am wondering if I could do that by myself, but I'm not sure if my skills and my knowledge about the TcpReassembly internals are good enough. I've only looked shortly into TcpReassembly.cpp but so far I would say there is not that much to change. Though there is probably a reason why it is not implemented yet. What is your opinion? 

Thanks in advance, Jannik

**Comment by seladb** [comment]
It shouldn't be a huge work, but a couple of changes are needed:

- Change `ConnectionData` to support both IPv4 and IPv6
- Internal `TcpOneSideData` struct should support IPv4 and IPv6
- Calculate `tcpPayloadSize` using PayloadLength field in IPv6 instead of TotalLength field in IPv4
- Add unit-tests for TCP reassembly with IPv6

Maybe there are more changes, but these are the major ones.
I'm currently don't have much time to do this, do you think you handle this and submit a PR?
I'm here to support you wherever needed.
Please let me know what you think

**Comment by seladb** [comment]
Thanks, please keep me posted

**Comment by echo-Mike** [comment]
Hey @jannik3141, 
it would be great if you took into account that the implementation of Packet and RawPacket may be changed (I finishing my work on that part: https://github.com/echo-Mike/PcapPlusPlus/tree/feature/rawpacket_memory_rework ). So please do not rely on direct access to the fields of specified structures, use their interface where ever it is possible.

**Comment by jannik3141** [comment]
Okay @echo-Mike, thanks for the notice.

**Comment by seladb** [comment]
Hi @jannik3141, thanks for taking this on yourself, much appreciated!

Regarding the unit-tests - they are on `Tests/Pcap++Test`, here is a link:

https://github.com/seladb/PcapPlusPlus/blob/3bb8d141ea740cb2ed6fd36eebee47a0b0a57aa9/Tests/Pcap%2B%2BTest/main.cpp#L5391

**Comment by jannik3141** [comment]
Ah, thanks @seladb. I searched in Packet++Test because the TcpReassembly Code belongs to the Packet++ lib.

**Comment by seladb** [comment]
Yes, I know this is not the ideal place to put the unit-tests. I did that because I wanted to read pcap files and I used `PcapFileReaderDevice` (which is in Pcap++) to do that

**Comment by jannik3141** [comment]
Hey all,

I'm sorry to say that I haven't had much time to work on this enhancement yet. We got some higher priority issues in our project that I needed to work on first. Because of this I won't continue my work on IPv6 Tcp Reassembly before April. But IPv6 support is still on my todo list, so I will probably be back with questions and/or a pull request in April/May.

**Comment by seladb** [comment]
Thanks @jannik3141 , please let me know if you have some time before April/May. I'll also try to take this if I have time

**Comment by seladb** [comment]
Done!
Please pull the latest code from master

**Comment by jannik3141** [comment]
Wow! Thank you very much @seladb !
