### ISSUE TITLE
Add contribution guide

### ISSUE THREAD

**Issue by echo-Mike** [seladb/PcapPlusPlus#96]
Recently, more and more developers want to join the library development process. I find it reasonable to add at least a basic official contribution guideline.  

Let me propose some key points for this guideline:
* Use GitFlow (or just it's branch naming convention)
* Documnet your code with Doxygen (use **@** for keywords)
* Register an account on Appveyor and TravisCI and use it during your feature development cycle  
* Try merge on your fork befor posting a Merge Request (MR)
* Propose MR into **dev** branch of main repository
* Start development of your feature from last stable (the CI is passed successfully) commit on **dev** branch of main repository
* Add issues to main repository which describe your intentions about adding new feature, changing current implementation or other stuff that you want to do. Listen to feedback.
* Before MR make sure that:
    - All CI is passed
    - Documentation generated by Doxygen is not broken

**Comment by seladb** [comment]
Thanks @echo-Mike , I totally agree. It seems that a contribution guide can indeed be useful in the current phase of this project. You also make great points regarding the content of the guide, please let me add a few comments:

- I'm not sure we should follow GitFlow approach in this phase of the project. It's not like there are dozens of people waiting to contribute to this project. If we get there one day, we should definitely re-think about this
- I do agree that feature branched should be merged to **dev** branch first
- Few additions to this guide that I can think of:
   - Please make sure to write unit-tests for each new feature, either in Packet++Test (if your code is in Packet++ lib) or in Pcap++Test (if your code is in Pcap++ lib) 
   - Every PR will be reviewed and approved by a maintainer

Please let me know what you think

**Comment by seladb** [comment]
Done! Please see commit: c69d9a6c276569b0006c4ac7e84885530f8524bb

I'll close the issue now. If you have any comments, please re-open it
