### ISSUE TITLE
Issue copying code from the Install docs

### ISSUE THREAD

**Issue by InfiniteVerma** [seladb/PcapPlusPlus#962]
In several places of the Installation section in the documentation, copying the snippets adds unnecessary text to the clipboard. An example from [Build on Linux](https://pcapplusplus.github.io/docs/install/linux#cross-compilation-or-build-for-different-architectures):

![image](https://user-images.githubusercontent.com/45547198/189599233-468b8fd5-841f-48f4-9ea5-d1c4b5c98138.png)

This copies the shell prompt text too. There's some instances in other "Build on ..." pages as well.

I'd like to work on this.

**Comment by seladb** [comment]
Thanks @InfiniteVerma for reporting this issue! 
Yes, I agree this is not nice. Please feel free to open a PR with the fix

**Comment by seladb** [comment]
Thank you @InfiniteVerma for providing this fix, much appreciated! 🙏 ❤️
