### ISSUE TITLE
UDP Reassembly

### ISSUE THREAD

**Issue by a7mad7aydar** [seladb/PcapPlusPlus#964]
Hi Guys!

I'm a newbie to your library (thanks for the great docs) and come from the python world.

I tried to reassemble UDP packets using the IPReassembly exmple shown here: 
https://github.com/seladb/PcapPlusPlus/blob/master/Examples/IPDefragUtil/main.cpp

I even passed the parameter parseUntil = UdpLayer but it didn't work.

The results looked quite different from the results in wireshark. One thing that I noticed is that the Ethernet checksum (frame check sequence) at the end won't be removed from the fragments, which will mess the whole thing up.

I ended up building a reassembly mechanism on my own, which works fine, I just have to remove the 8-byte UDP header myself, which not a very clean way.

Even though the IPv4 header has the protocol set to 17 (UDP), ```pcpp::UdpLayer* udpLayer = parsedPacket.getLayerOfType<pcpp::UdpLayer>();``` returns nothing.

I don't rule out, that I did something wrong, but I tried A LOT before writing.

Cheers!

**Comment by seladb** [comment]
IPReassembly is for reassembling fragmented IP packets, which doesn't seem to be your use case. We currently don't support UDP reassembly, we only have TCP reassembly.

But that's a good feature to add!

**Comment by a7mad7aydar** [comment]
Well it did 80% of the job correctly, it only missed the last step.

Do you know why the udp layer of the fragments are not detected? I can't filter them according to the destination port.

**Comment by seladb** [comment]
I assume the reason it looked like it did 80% of the job correctly is that either most of the UDP packets were IP-fragmented and then it created full UDP packets from these IP fragments, or your file didn't have IP fragments at all but the packets were already ordered correctly and all it did was just write them to the output file.



> Do you know why the udp layer of the fragments are not detected? I can't filter them according to the destination port.

IP fragmentation basically takes a large packet and separates its payload into smaller IP packets. Suppose you have a packet like this:
```text
----------------------------------------
| Eth layer                            |
----------------------------------------
| IPv4 layer                           |
----------------------------------------
| UDP layer                            |
| src port | dst port | len | checksum |
----------------------------------------
| UDP Payload (some other protocol)    |
|    8 bytes                           |
|    8 bytes                           |
----------------------------------------
```

And suppose the size of each IP fragment 8 bytes, the fragments will look like this:

```text
Fragment 1:

----------------------------------------
| Eth layer                            |
----------------------------------------
| IPv4 layer                           |
----------------------------------------
| src port | dst port | len | checksum |
----------------------------------------

Fragment 2:

----------------------------------------
| Eth layer                            |
----------------------------------------
| IPv4 layer                           |
----------------------------------------
|    8 bytes                           |
----------------------------------------

Fragment 3:

----------------------------------------
| Eth layer                            |
----------------------------------------
| IPv4 layer                           |
----------------------------------------
|    8 bytes                           |
----------------------------------------
```

As you can see, only the first fragment "looks like" a UDP packet because it has its headers, but the rest don't.

Now suppose the fragment size is 4 (which cannot really happen, but just for the example) - the 2 first fragments will look like this:

```text
Fragment 1:

----------------------------------------
| Eth layer                            |
----------------------------------------
| IPv4 layer                           |
----------------------------------------
| src port | dst port |
-----------------------

Fragment 2:

----------------------------------------
| Eth layer                            |
----------------------------------------
| IPv4 layer                           |
----------------------------------------
| len | checksum |
------------------
```

As you can see in this example, even the UDP header is split between 2 fragments, so none of them can be identified as a UDP packet.
Please let me know if that makes sense.

**Comment by a7mad7aydar** [comment]
Yep, it makes sense. You're right, I must reassemble, if I want to filter the destPort. 

And yes, the packets are IP fragmented.

Thanks for the clarifications

**Comment by seladb** [comment]
Sounds good, I hope this helps!
If you don't have further questions, should we close the issue?

**Comment by a7mad7aydar** [comment]
Yes I will close it! thanks!
