### ISSUE TITLE
TCP reassembly treats FIN and RST the same

### ISSUE THREAD

**Issue by neilstephens** [seladb/PcapPlusPlus#967]
Gday,

I've just finished debugging an issue in my application that uses pcpp::TcpReassembly. I was having an issue where the number of tracked connections would continue to grow, even though pcpp::TcpReassemblyConfiguration::removeConnInfo == true, and in reality the number of established connections was steady state. After a while I was getting pcpp::TcpReassembly::ReassemblyStatus::Ignore_PacketOfClosedFlow when new connections were clashing with the stale flows in the tracked connections.

I eventually reproduced the issue under test conditions and figured out that the problem is that pcpp::TcpReassembly treats a RST flag as if it was a FIN flag. That is, it only marks the flow in one direction closed and expects a FIN/RST in the other direction before it would mark the connection as fully closed and add it to the cleanup list.

The problem is that RST (with valid sequence), unlike FIN, deems a connection immediately closed, and the other side should never respond on a reset connection. But that means that pcpp::TcpReassembly is left with a half closed connection in it's collection that never gets cleaned up.

I've worked around the issue in my application for now, by checking tcpLayer->getTcpHeader()->rstFlag myself and calling pcpp::TcpReassembly::closeConnection().

I'm using the pre-compiled binaries at the moment, but if you would like me to attempt to fix the library code and submit a patch, I'm happy to have a go but it might take a while to find the time.

**Comment by seladb** [comment]
Thank you @neilstephens for reporting this issue. You have a valid point and it's something that needs to be fixed. If you can spend the time to fix it and submit a PR I'd really appreciate it. 

You already have all the information and I assume you also have an example pcap file that reproduces this issue and can be added as a test to verify the fix.

**Comment by seladb** [comment]
Thank you @neilstephens for reporting this issue and providing a fix, I really appreciate your contribution to this project! 🙏 ❤️
