### ISSUE TITLE
How can I check the network connection status?

### ISSUE THREAD

**Issue by luckygg** [seladb/PcapPlusPlus#968]
Hi all.

I would like to check the network connection status.

I have a desktop and laptop.
They are directly connected by Ethernet cable.

If I disconnect and reconnect the laptop's Ethernet cable, I can see the 'M-SEARCH * HTTP/1.1' messages via the Wireshark on the desktop.

![no title](https://user-images.githubusercontent.com/17895255/191006466-9187a99f-dd6c-44d8-950b-b1b19a9e7ec0.png)

So, I think I can check the network connection status using this message.

Is this the correct way?
If yes, how can I check this message via PcapPlusPlus?
If not, could you please let me know the correct way?

Thank you :)

**Comment by seladb** [comment]
I guess this question is not related to the PcapPlusPlus project. Checking network connectivity can be done in various ways which depend on the OS (on both sides), the installed software and other factors. You can probably google it or ask in other forums?

**Comment by seladb** [comment]
I'll close this issue now, please reopen if needed

**Comment by luckygg** [comment]
Sorry, I'm so late.
Your mention is very helpful for me.
Thank you for your guide!
