### ISSUE TITLE
[Feature] MBufRawPacket array reusage

### ISSUE THREAD

**Issue by echo-Mike** [seladb/PcapPlusPlus#97]
Hello. 
## The feature
When receiving packets from DPDK NIC using `DpdkDevice::receivePackets` overload with pointer to an array of `MBufRawPacket` objects as its first argument the reusage of that array is possible.
## Current situation 
Array of `MBufRawPacket` objects is allocated on every call to `DpdkDevice::receivePackets` which is not efficient in concurrent environment.  
## The proposed solution
The additional flag parameter to the function that will signify to function logic that not a `NULL` pointer was provided as  its first argument but an array of some size.  
## Use case
DPDK thread workers.  
Proposed solution makes it possible to allocate array of `MBufRawPacket` objects only once per thread.
```C++
bool MyDpdkWorker::run(uint32_t coreId)
{
    /* Setup code */
    // RX_BURST_SIZE must be enough to not allocate at all
    MBufRawPacket* myArray = new MBufRawPacket[RX_BURST_SIZE];
    int myArraySize = RX_BURST_SIZE;
    int newArraySize = myArraySize;
    // Main thread loop
    while(/* expression */)
    {
        /**
        ... 
        Routine code 
        ...
        **/
        // Array is reused
        myDpdkDevPtr->receivePackets(&myArray, newArraySize, myRxQueueNum, true);
        // Array size corrected
        myArraySize = myArraySize < newArraySize ? newArraySize : myArraySize;
        for (int i = 0; i < myArraySize; ++i)
        {
             /* Packet processing */
        }
    }
}
```
## PR and CI
[AppVeyor](https://ci.appveyor.com/project/echo-Mike/pcapplusplus/build/1.0.34)
[TravisCI](https://travis-ci.org/echo-Mike/PcapPlusPlus/builds/348600615)  
PR #98

**Comment by seladb** [comment]
Thanks for adding this feature! This is a very important feature that should improve performance.
Please see some comments inside the PR

**Comment by seladb** [comment]
PR merged and unit-tests passed. Closing the issue now
