### ISSUE TITLE
How to write pcap file with split mode?

### ISSUE THREAD

**Issue by luckygg** [seladb/PcapPlusPlus#989]
Hi all.

I'm using PcapFileWriterDevice to save packets to a pcap file.
However, I did not know that there is a limit to the number of lines that can be stored in a pcap file.
(Max lines: 53,000,000)

When writing a packet to a file with PcapFileWriterDevice, is there a way to save it by splting it according to max file size?

I have referenced the example code below.
https://github.com/seladb/PcapPlusPlus/blob/master/Examples/PcapSplitter/main.cpp

But, I understood the example code as an example to split the file after reading it.

Could you please advise to me?

Thank you!

**Comment by seladb** [comment]
There is no way to "ask" `PcapFileWriterDevice` to start writing to another file when hitting the limit automatically.

However it should be pretty easy to write code for it - keep a packet counter, and whenever it hits the limit close the existing file and open a new one. Please let me know if you have any questions

**Comment by luckygg** [comment]
@seladb I got it! Thank you for your reply 😄
