### ISSUE TITLE
Invalid link layer (276) for reader device filename xxx.pcap

### ISSUE THREAD

**Issue by jiangjiongyu** [seladb/PcapPlusPlus#992]
at the windows platform 
npcap-sdk-1.13

I have already updated the latest pcapplusplus version to compile my paser tool, but still doesn't work.

**Comment by seladb** [comment]
@jiangjiongyu I'm sorry for the delayed response.
Link layer 276 isn't currently supported, I'm not even sure what it is. Can you attach the pcap file you're using?

**Comment by seladb** [comment]
> @jiangjiongyu I'm sorry for the delayed response. Link layer 276 isn't currently supported, I'm not even sure what it is. Can you attach the pcap file you're using?

@jiangjiongyu I'm not sure if you saw my previous message...

**Comment by jiangjiongyu** [comment]
> > @jiangjiongyu I'm sorry for the delayed response. Link layer 276 isn't currently supported, I'm not even sure what it is. Can you attach the pcap file you're using?
> 
> @jiangjiongyu I'm not sure if you saw my previous message...

Because of company security policy, I can't upload pcap file directly.Maybe you can contact with me through jiangjiongyu@163.com, I have to try to communicate with security department firstly...

**Comment by seladb** [comment]
Thank you for the info @jiangjiongyu ! Feel free to send me an email at pcapplusplus@gmail.com

**Comment by jiangjiongyu** [comment]
> Thank you for the info @jiangjiongyu ! Feel free to send me an email at [pcapplusplus@gmail.com](mailto:pcapplusplus@gmail.com)

I have sent it to project email,hope for perfect resolvation.

**Comment by seladb** [comment]
Thank you @jiangjiongyu ! I tried to open the file in Wireshark but is also can't recognize this link layer type...

**Comment by jiangjiongyu** [comment]
> Thank you @jiangjiongyu ! I tried to open the file in Wireshark but it also can't recognize this link layer type...

I have updated wireshark to 4.0.1,the source file can be parsered.Maybe you can try it.

**Comment by seladb** [comment]
@jiangjiongyu apparently it's `Linux cooked-mode capture v2`. PcapPlusPlus currently only supports v1: https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/header/SllLayer.h.

This can be a nice addition to the project. Would you consider adding it?

Please consider that when adding a new layer we need a pcap file with a few examples to run in our [test suite](https://github.com/seladb/PcapPlusPlus/tree/master/Tests/Packet%2B%2BTest). Do you think you can provide such pcap file that will reside in the project public repo?

**Comment by jiangjiongyu** [comment]
> @jiangjiongyu apparently it's `Linux cooked-mode capture v2`. PcapPlusPlus currently only supports v1: https://github.com/seladb/PcapPlusPlus/blob/master/Packet%2B%2B/header/SllLayer.h.
> 
> This can be a nice addition to the project. Would you consider adding it?
> 
> Please consider that when adding a new layer we need a pcap file with a few examples to run in our [test suite](https://github.com/seladb/PcapPlusPlus/tree/master/Tests/Packet%2B%2BTest). Do you think you can provide such pcap file that will reside in the project public repo?

I have so many things to deal with in daily work, so I'm afraid of having no time to add a new layer.
As for source file,you can use tcpdump in andoird root phone to grap this kind of pcap file.(tcpdump -i any -w location).

**Comment by seladb** [comment]
> I have so many things to deal with in daily work, so I'm afraid of having no time to add a new layer.
> As for source file,you can use tcpdump in andoird root phone to grap this kind of pcap file.(tcpdump -i any -w location).

Unfortunately I don't have a rooted Android phone that I can use to capture these packets. Will you be able to capture and send a small sample that can be used for the tests?

**Comment by jiangjiongyu** [comment]
> Can you describe what a small sample have?I've send a pcap source file to your email or you need more?



> > I have so many things to deal with in daily work, so I'm afraid of having no time to add a new layer.
> > As for source file,you can use tcpdump in andoird root phone to grap this kind of pcap file.(tcpdump -i any -w location).
> 
> Unfortunately I don't have a rooted Android phone that I can use to capture these packets. Will you be able to capture and send a small sample that can be used for the tests?

Can you describe what a small sample have?I've send a pcap source file to your email or you need more?

**Comment by seladb** [comment]
This sample is enough, can we use it publicly and add it to the repo?

Can I add it to this issue?

**Comment by jiangjiongyu** [comment]
> This sample is enough, can we use it publicly and add it to the repo?
> 
> Can I add it to this issue?

No problem.I 'm so glad to supply a sample to your project.

**Comment by seladb** [comment]
Thank you @jiangjiongyu !
I currently don't have time to work on it, but we can keep the issue open. Maybe someone will volunteer to work on it.

Here is the file that contains the example: [tcpdump.zip](https://github.com/seladb/PcapPlusPlus/files/10365969/tcpdump.zip).

To open it Wireshark version  >= 4.0.1 is needed.

**Comment by seladb** [comment]
Here is the specification and implementation for SLL2 (Linux cooked-mode capture v2) in libpcap/tcpdump: 

https://github.com/the-tcpdump-group/libpcap/blob/fbcc461fbc2bd3b98de401cc04e6a4a10614e99f/pcap/sll.h#L98
https://www.tcpdump.org/linktypes/LINKTYPE_LINUX_SLL2.html
