### ISSUE TITLE
How to check Keep-Alive packet

### ISSUE THREAD

**Issue by luckygg** [seladb/PcapPlusPlus#995]
Hi all.
I have a question how to check Keep-Alive packet.

I can see the Keep-Alive packet by using Wireshark.
![image](https://user-images.githubusercontent.com/17895255/202451669-a4e222f7-6920-4284-970e-048b623609f4.png)

But I can't find how to check it on pcapplusplus apis.

Could you please advise me?

Thank you.

**Comment by seladb** [comment]
TCP keep-alive packets have the `ACK` flag turned on and have a TCP payload length of 0, you can use those characteristics to find them:
```cpp
tcpLayer = packet.getLayerOfType<pcpp::TcpLayer>();
if (tcpLayer != nullptr && tcpLayer->getTcpHeader()->ackFlag && tcpLayer->getPayloadLen() == 0)
    std::cout << "This packet is TCP keep-alive";
```

**Comment by luckygg** [comment]
@seladb Thank you for your reply!

I already have found the article how to know the packet is Keep-Alive.
https://www.wireshark.org/docs/wsug_html_chunked/ChAdvTCPAnalysis.html

Do I have to calculate not only keep-alive but also messages like [Dup] and [Retransmission] by hand?
If there is a function conveniently provided by pcapplusplus, could you please let me know?

Thank you :)

**Comment by seladb** [comment]
There is currently no way to calculate those things, mainly because most need some context on other packets. For example: in order to calculate duplication or retransmission you need to know which packets came before, however packet parsing is done per packet and doesn't have this context. Please let me know if that makes sense

**Comment by seladb** [comment]
I'm closing this issue now, please reopen if needed
