### ISSUE TITLE
Insufficient documentation for IPReassembly::processPacket

### ISSUE THREAD

**Issue by Heysunk** [seladb/PcapPlusPlus#997]
`Packet* IPReassembly::processPacket(RawPacket* fragment, ReassemblyStatus& status, ProtocolType parseUntil, OsiModelLayer parseUntilLayer)`

Running `IPReassembly::processPacket` with parseUntilLayer set to 
`pcpp::OsiModelPhysicalLayer` results in returning with status set to `NON_IP_PACKET` independent of fragment. The same issue should occur if parseUntil is set to a protocol above IP.

This is because the function parses the rawPacket according to the restrictions set in OsiModelLayer and thereafter tries to find the IP layer in the parsed packet (which obviously won't exist).

https://github.com/seladb/PcapPlusPlus/blob/6d156bfda910cff94b04124abdb58020b5e1c2a0/Packet%2B%2B/src/IPReassembly.cpp#L478-L481

https://github.com/seladb/PcapPlusPlus/blob/6d156bfda910cff94b04124abdb58020b5e1c2a0/Packet%2B%2B/src/IPReassembly.cpp#L280-L284

This is not necessarily a bug in the code but it did lead to some confusion before I realized why none of my packets were being properly reassembled. I think that this could be clarified in the documentation.

**Comment by seladb** [comment]
Thank you @Heysunk for providing a fix, I really appreciate your contribution! 🙏 ❤️ 

Your PR was merged to `master`, I'm closing the issue now
